### ISSUE TITLE
Both builds (Dreamcast and Naomi) crash on Android 4.4.2

### ISSUE THREAD

**Issue by RaduNastase** [flyinghead/flycast#1]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Galaxy Note 3 Snapdragon version | Installed OS and version (Android 4.4.2) | Flycast build a4eb9c2	(both Dreamcast and Naomi)

After successful install, the app crashes when opening it. I canot reach any settings at all, it crashes 2 seconds after i touch it, with an "app has crashed" message"

**Comment by flyinghead** [comment]
I tested this build on Android 4.4.4 (Samsung Galaxy J1) without issue.

Can you try to gather logs from your device?

**Comment by flyinghead** [comment]
No answer so assuming it's resolved
