### ISSUE TITLE
Recent Radeon drivers break PowerVR2 GLSL shader

### ISSUE THREAD

**Issue by leilei-** [flyinghead/flycast#1005]
Since driver 2022.7 (and this is current behavior as of the 2023.4.1driver) the shader would drench the screen in green.

All I can suggest is adding some =0 initializations to the RGB vectors to avoid taking in uninitialized garbage and the green since the shader was written when I was naive enough to assume GLSL compilers would politely =0 everything, but in the name of 'minecraft performance' that was axed in the driver last year.

**Comment by flyinghead** [comment]
Note that the powervr2 filter was broken by 5722dc90f06cc62eb05aa6e70e89be2e8d4718bf. It's now fixed on the dev branch.
Here is the proposed change. Is it what you have in mind?
```
index 9989dbe28..73155f9e6 100644
--- a/core/rend/gles/postprocess.cpp
+++ b/core/rend/gles/postprocess.cpp
@@ -80,7 +80,7 @@ void main()
        vec2 texcoord4  = vTexCoord;
        texcoord4.y -= tap * 2.f;
        int bl;
-       vec4 ble;
+       vec4 ble = vec4(0.0);
 
        for (bl=0;bl<taps;bl++)
        {
@@ -140,8 +140,8 @@ void main()
        texcoord4.y = texcoord4.y;
        vec4 blur1 = texture(Source, texcoord4);
        int bl;
-       vec4 ble;
+       vec4 ble = vec4(0.0);
        for (bl=0;bl<taps;bl++)
        {
                float e = 1;
                if (bl>=3)
```

**Comment by leilei-** [comment]
That looks fine. I can't build Flycast to see if that's effective myself, but had noticed my other shader breakages across other things after updating to the recent drivers (i.e. uninitialized garbage in leilei-/someshaders causing chaos, and openarena/engine's shaders failing), so I had assumed this got bit by the same driver problem.

**Comment by flyinghead** [comment]
I pushed the fix on the dev branch.

**Comment by leilei-** [comment]
Checked out the libretro artifact of the dev branch in glcore and it appears to be fixed! The composite and VGA shaders work properly.
