### ISSUE TITLE
The graphics in the RetroArch Flycast core are far "blurrier" than the Flycast standalone

### ISSUE THREAD

**Issue by antoniodesousa** [flyinghead/flycast#1007]
I hope this is the right place to open the issue...

Platform / OS / Hardware:
Windows 11 Pro 22H2
AMD Ryzen 9 6900HX with AMD Radeon 680M Graphics
32GB RAM + 2TB SSD

Github hash: [a21b79cfb](https://github.com/flyinghead/flycast/commit/a21b79cfbe9770d6718cb9ef6068de698e3d7f98)
RetroArch version and the Flycast core are the latest.

**_Description of the Issue_**

Like the title says, the graphics in the RetroArch Flycast core are far "blurrier" than the Flycast standalone. You can see in the screenshots, specially in the distance, that the road and the boards in the game are super sharp in the Flycast standalone compared to RetroArch. Also, the graphics look like running at half the resolution in RetroArch compared to the standalone even though both are running at the same resolution 2880x2160. I could only try the D3D11 renderer in RetroArch since Vulkan was crashing every single time on me. In the standalone, both Vulkan and D3D11 look super sharp.

**_Screenshots_**

18 Wheeler running on RetroArch:
![18 Wheeler - RetroArch](https://user-images.githubusercontent.com/10920974/230457902-c5d0cacd-2aec-475a-9e4c-37d6457e7c77.png)

18 Wheeler running on Flycast:
![18 Wheeler - Flycast](https://user-images.githubusercontent.com/10920974/230458033-e5bd7223-778c-4385-9bea-caedba3fc1af.png)

**Comment by flyinghead** [comment]
Can you try OpenGL?
I did a quick test with Vulkan at 1280x960 (x2) and it looks better than your screenshot.
![image](https://user-images.githubusercontent.com/16261910/230465970-f00b3764-7cbb-4adb-be67-a332cc541d4d.png)

Make sure you don't have Full Framebuffer Emulation enabled in retroarch as this forces render resolution to native (640x480).

**Comment by antoniodesousa** [comment]
I just tried OpenGL and it looks pretty much the same as D3D11.

18 Wheeler running on RetroArch (OpenGL):
![RetroArch 06_04_2023 20_51_43](https://user-images.githubusercontent.com/10920974/230471082-a03be73c-de00-4fec-bf07-c7831e91b597.png)

Flycast standalone is always super sharp. It doesn't matter what renderer I use.

**Comment by flyinghead** [comment]
Did you check your settings?
Also try the most recent core update. You're running v2.1 from Feb 15th.

**Comment by antoniodesousa** [comment]
Yes, I don't have the Framebuffer enabled. And like I said before, I'm using the latest release of RetroArch and I updated all the cores today. So, I'm pretty sure that I have the latest changes. By the way, your screenshot is quite blurry if you compare it with the one I took using Flycast standalone.

Your screenshot:
![001](https://user-images.githubusercontent.com/10920974/230495301-3310060c-4771-4c5b-8e3e-e5dd2416b5ff.png)

Mine screenshot:
![002](https://user-images.githubusercontent.com/10920974/230495364-6c9f58a4-06c4-4c26-9b1f-0416c67b3893.png)

**Comment by flyinghead** [comment]
you said your version is:
> Github hash: [a21b79cfb](https://github.com/flyinghead/flycast/commit/a21b79cfbe9770d6718cb9ef6068de698e3d7f98)

where does it come from?

**Comment by antoniodesousa** [comment]
Ah that's the Flycast standalone.

**Comment by flyinghead** [comment]
Here is a screenshot at x3 resolution of RetroArch using dx11. As you can see the quality is correct and much better than yours.
Something seems to be limiting the rendering resolution in your case so check the core and RA settings. Also can you generate some logs (RA + core)?
![Screenshot (126)](https://user-images.githubusercontent.com/16261910/230715163-31e3acec-fd39-4d33-a6d5-d17014d2aeed.png)

**Comment by antoniodesousa** [comment]
I reinstall everything from scratch and now it's working fine. Only thing that I noticed is that the option "PowerVR2 Post-processing filter" doesn't work anymore. The screen just go black if I enable it. It used to work before.

![RetroArch Flycast 187674d 08_04_2023 13_51_22](https://user-images.githubusercontent.com/10920974/230719771-ecaa0cf3-fc84-47c9-b340-365bc549c652.png)

**Comment by flyinghead** [comment]
The PowerVR2 issue is fixed on the dev branch: https://github.com/flyinghead/flycast/commit/eb3ebe24e8c790b414847bd9e0a313426feea9de

**Comment by antoniodesousa** [comment]
> The PowerVR2 issue is fixed on the dev branch: https://github.com/flyinghead/flycast/commit/eb3ebe24e8c790b414847bd9e0a313426feea9de

OH nice! I hope that it gets release soon :)
I like the colors better with that filter on.

I gonna close the ticket since the issue was not related to this anyways.
