### ISSUE TITLE
Allow "Horizontal Stretching" to go over 150

### ISSUE THREAD

**Issue by Gonckzilla** [flyinghead/flycast#1012]
Hey there! As always, loving flycast. 

Briefly, the "Horizontal Stretching" option only goes as far as 150, which results in black bars on the sides in a 20:9 phone screen. This became an issue when using a custom 20:9 widescreen code with integrated options "Widescreen", and "Widescreen Game Cheats" turned off. When these options are on, 150 is more than enough - but of course, these are not used when a user-code is applied for doing the adjustment.

For now, I had to edit the emu.cfg file and manually change the stretching option to 167, which filled the screen nicely 🙂.

Either this or adding a "Stretch To Fill" option could also be appropriate, maybe both.

**Comment by flyinghead** [comment]
Horizontal stretching can now go up to 250%
