### ISSUE TITLE
How to fix this flickering issue

### ISSUE THREAD

**Issue by pantomm** [flyinghead/flycast#1014]
https://user-images.githubusercontent.com/50849304/232162857-0580bfb8-a0f2-4df1-ae5f-7991bd360219.mp4

Platform / OS / Hardware:
Xiaomi 11t / Android 13

**Comment by flyinghead** [comment]
It looks like a GPU driver bug.
What Video settings are you using?

**Comment by pantomm** [comment]
> It looks like a GPU driver bug. What Video settings are you using?

It only happens when I'm using per pixel sorting

**Comment by pantomm** [comment]
I Just test it on retroarch and it doesn't have any flickering whatsoever

**Comment by flyinghead** [comment]
There's no per-pixel on OpenGL ES (mobile) because of limitations of the API.

The flycast core for retroarch is using the same code as standalone.

**Comment by flyinghead** [comment]
The latest master build includes a tentative fix for this issue. Please test and report.

**Comment by MANGOM1LK** [comment]
I've been messing around with fixing this issue on my Retroid Pocket 4 Pro (Mali G77 MC9 if i recall correctly) (my test game is Sonic Adventure 2) and I have noticed the corruption seems to be reduced significantly when Enable RTT is turned on (I'm also using Delay Frame Swapping, Native Depth Interpolation, and Fix Upscale Bleeding Edge but none of those seem to be doing very much? it's difficult to tell). Running the game at 640x480 seems to eliminate it entirely outside of the title screen. Interesting results. I should also note that the first Sonic Adventure experiences this much less than the provided video.

Android 14, Flycast Retroarch core bc51aef, RA 1.17.0

**Comment by TreeBranches** [comment]
Despite what I said, after being done with Sonic Adventure (which generally only crashed if I used fast forward) and some very, very brief visual corruption during some menu transitions), I switched to playing Rayman 2 and was getting crashes not only when using fast forward every time, but when reaching a certain point in the World Map/Level Select, halting my progress.

Despite the significant visual benefits to using per-pixel on Vulkan, the Vulkan driver support is just far too crashy to be usable. I was willing to not fast forward, but it's halting progress now lol
