### ISSUE TITLE
Neither save states work or vmu saves

### ISSUE THREAD

**Issue by wraiththirteen** [flyinghead/flycast#1015]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: flycast/emuelec/s905x3 board

Github hash: 

Hardware: 

**_Description of the Issue_**

I was able to save several states a day ago, but now for some reason when I try to save states it says 0% but when I try to go back to the emulec menu it freezes. That said I can play the game with the save state staying at zero, or even loading a state. It wouldnt be so bad but it will not let me use vmu saves either. I was able to use them yesterday. I had not updated anything and yet saves still stopped working. 

**_Debugging Steps Tested_**

I deleted the dreamcast bios I had, then installed a new one, but that didnt help, then deleted all bios except for the one that stays in the file, but that didnt help either. Also deleted all my saves and that didnt help. I also turned off the thread ripper that allowed multithread since someone stated it helped on an earlier version. I also downloaded vmu explorer for the vmu issue but again that didnt help although I think thats only supposed to help for pc version but I tried. 

```


**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
that's very likely a local issue: disk full/corrupted, permission issue, ...?
Things don't stop working with no reason, and I can't really help without more information like logs
