### ISSUE TITLE
Missing build instructions / issues building on Windows 11 (Visual Studio 2019)

### ISSUE THREAD

**Issue by AltoRetrato** [flyinghead/flycast#1018]
Apologies if this is written somewhere, but I could not find instructions to build Flycast on Windows 11 using Visual Studio 2019. I'm not even sure if there are compatibility or other major issues with this... Is MingW / MSYS2 preferred?

I've found [core build instruction on the libretro site, but they use MingW](https://docs.libretro.com/development/cores/core-specific/flycast/).

I managed to build Flycast (from the dev branch) with VS 2019 anyway, but encountered two issues in the process. Here's what I did:
```
git clone -b dev https://github.com/flyinghead/flycast.git
cd flycast
git submodule update --init --recursive
cmake -S . -B Build
(Build\flycast.sln is created, and can be built from the VS IDE or with msbuild from CLI)
```

*1st issue*: missing `d3dx9shader.h` when building the `Debug` configuration of `Build\flycast.sln`:
```
Error	C1083	Cannot open include file: 'd3dx9shader.h': No such file or directory (compiling source file C:\flycast\flycast\core\rend\dx9\d3d_shaders.cpp)	flycast	C:\flycast\flycast\core\rend\dx9\d3d_shaders.h	22	
Error	C1083	Cannot open include file: 'd3dx9shader.h': No such file or directory (compiling source file C:\flycast\flycast\core\rend\dx9\d3d_renderer.cpp)	flycast	C:\flycast\flycast\core\rend\dx9\d3d_shaders.h	22	
Error	C1083	Cannot open include file: 'd3dx9shader.h': No such file or directory (compiling source file C:\flycast\flycast\core\rend\dx9\dxcontext.cpp)	flycast	C:\flycast\flycast\core\rend\dx9\d3d_shaders.h	22	
```
I`m not sure what the solution would be for this, but as a workaround, I disabled the use of DX9:
```
cmake -S . -B Build -DUSE_DX9=OFF
```

*2nd issue*: can't find `zlib.lib`:
```
LINK : fatal error LNK1104: cannot open file 'core\deps\libchdr\deps\zlib-1.2.12\Debug\zlib.lib' [C:\flycast\flycast\build\flycast.vcxproj]
```
This happens because `flycast\core\deps\libchdr\deps\zlib-1.2.12\CMakeLists.txt` adds a `d` suffix when building a debug version with MS Visual C++, generating `zlibd.lib` instead:
```
if(MSVC)
    set(CMAKE_DEBUG_POSTFIX "d")
```
Again, I'm not sure what the best solution would be (changing zlib's or Flycast's `CMakeLists.txt`?), but either renaming `zlibd.lib` to `zlib.lib` or commenting out `set(CMAKE_DEBUG_POSTFIX "d")` (and running `cmake` again) allows the build to complete.

![image](https://user-images.githubusercontent.com/22997468/232927170-34c8e892-6725-4bde-a400-b36494dfdf3d.png)

**Comment by Helder1981** [comment]
> Thanks again!
> 
> The CI have 4 configurations for building on Windows:
> 
> * i686-pc-windows-msvc
> * x86_64-pc-windows-msvc
> * x86_64-w64-mingw32
> * libretro-x86_64-w64-mingw32
> 
> I built the `x86_64-pc-windows-msvc` config, but the resulting .exe had some issues, such as being slow to start and crashing when starting some games. It may require some fiddling to use VS 2019 to build Flycast correctly.
> 
> OTOH, building with the `x86_64-w64-mingw32` configuration worked like a charm! I recommend using MinGW64 to build Flycast on Windows, for now.

How do you use this file to compile it on windows msys64?
