### ISSUE TITLE
CD-DA is not cued when retrying in-game

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1019]
BGM does not start from the beginning and keeps the previous state.
It seems to be caused by the fix made in [#690](https://github.com/flyinghead/flycast/issues/690).
Confirmed with the following games that have CD-DA.

Reel Fishing: Wild (Go to Spot - throwing - underwater - reel in)
Mr.Driller (Game Start - Pause - Retry)
Bust-A-Move 4 (Puzzle - Collection - Game Over - Retry)
Wetrix+ (Pause - StartAgain)

**Comment by flyinghead** [comment]
The fix for #690 looks wrong so I will revert it. Unfortunately I haven't been able to find another fix for it so far.

**Comment by flyinghead** [comment]
Should be fixed in the latest dev build

**Comment by kihato** [comment]
I have confirmed that it has returned to its previous state. Thanks.
