### ISSUE TITLE
Undercover A.D.2025 Kei - Some of the textures are missing

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1020]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 187674d

No matter what settings I tried it didn't work.
So I built from the past commit and tested it.

I found that it occurred in 6208553(left image) and not in its parent 95a00a1(right image).

![UnderCover_s](https://user-images.githubusercontent.com/14366233/233754635-ce45f254-51e1-4b4f-86eb-4b6f4015e870.png)

**Comment by flyinghead** [comment]
This same commit is causing this issue: https://www.reddit.com/r/RetroArch/comments/12twcsg/flycast_shenmue_animation_glitching/

It doesn't seem to happen on linux.

**Comment by kihato** [comment]
I built it and confirmed it was fixed.
Thanks a lot.
