### ISSUE TITLE
Gaiamaster Kessen! - Missing texture colors

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1021]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 187674d

The 3D characters that appear when a dice game wins or loses are not colored.
You can watch the video [here](https://youtu.be/1vlfCipEgj4?t=1539).
 [SaveState](https://github.com/flyinghead/flycast/files/11303498/Gaiamaster.-.Kessen.Seikioh.Densetsu.zip)

![Gaiamaster1](https://user-images.githubusercontent.com/14366233/233834599-14f9f3f1-c7ba-41be-9e3a-e34128258a1a.png)

Although the size is different, similar 3D characters appear in battle scenes, but they are displayed normally.
![Gaiamaster3](https://user-images.githubusercontent.com/14366233/233836232-80390379-ef4e-4713-80b4-1a38e7a5cd96.png)

**Comment by flyinghead** [comment]
This game sets the color intensity of these polygons to -NaN, which is randomly interpreted as 0. Using 1 instead fixes the issue.
