### ISSUE TITLE
Frame rate glitching / pacing issues Dead or Alive 2

### ISSUE THREAD

**Issue by fallaha56** [flyinghead/flycast#1022]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Win11 / 5950x / 3080Ti

Github hash: 

Hardware: Dreamcast

**_Description of the Issue_**

When on the latest build the game seems to switch between 60fps and 30fps for cutscenes in the intro but when in 30fps frame pacing is extremely erratic regardless of backend or other settings; have tried game in PCSX2 and behaviour seems to be different

**_Debugging Steps Tested_**

  * tried all backends
  * tried adjusting settings in nVidia control panel including presentation method
  * reviewed pacing in ReShade and seems to be very different depending if is 60 vs 30 fps part of presentation

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by Nejsplitter** [comment]
@fallaha56 try this: use the latest core on Retroarch, in RA video settings set 'vsync swap interval' to 'auto' and in flycast core settings set 'detect framerate changes' to on, this should give perfect frame pacing regardless of game framerate, the reason that pcsx2 behaves differently is because it uses frame duplication for better frame pacing in 30fps games/scenarios

**Comment by fallaha56** [comment]
> @fallaha56 try this: use the latest flycast core on Retroarch, in RA video settings set 'vsync swap interval' to 'auto' and in flycast core options set 'detect framerate changes' to on, this should give perfect frame pacing regardless of game framerate, the reason that pcsx2 behaves differently is because it uses frame duplication for better frame pacing in 30fps games/scenarios

thanks, did manage to get to the settings and try it but RA glitches even worse and starts trying to resize the window

FWIW it looks like DOA2 on PS2 is actually running at 60fps throughout including cut scenes...

perhaps frame duplication one day in Flycast...?

**Comment by cinnamonmatexfce** [comment]
> > @fallaha56 try this: use the latest flycast core on Retroarch, in RA video settings set 'vsync swap interval' to 'auto' and in flycast core options set 'detect framerate changes' to on, this should give perfect frame pacing regardless of game framerate, the reason that pcsx2 behaves differently is because it uses frame duplication for better frame pacing in 30fps games/scenarios
> 
> thanks, did manage to get to the settings and try it but RA glitches even worse and starts trying to resize the window
> 
> FWIW it looks like DOA2 on PS2 is actually running at 60fps throughout including cut scenes...
> 
> perhaps frame duplication one day in Flycast...?



WDYM?
In standalone you have duplicate frames. Did you know it?

**Comment by Nejsplitter** [comment]
> > > @fallaha56 try this: use the latest flycast core on Retroarch, in RA video settings set 'vsync swap interval' to 'auto' and in flycast core options set 'detect framerate changes' to on, this should give perfect frame pacing regardless of game framerate, the reason that pcsx2 behaves differently is because it uses frame duplication for better frame pacing in 30fps games/scenarios
> > 
> > 
> > thanks, did manage to get to the settings and try it but RA glitches even worse and starts trying to resize the window
> > FWIW it looks like DOA2 on PS2 is actually running at 60fps throughout including cut scenes...
> > perhaps frame duplication one day in Flycast...?
> 
> WDYM? In standalone you have duplicate frames. Did you know it?

thats only for vulkan and 120hz displays i think, not for 30fps games as mentioned above

**Comment by flyinghead** [comment]
This is due to some intro sequences being rendered at 30 FPS on a 60 Hz monitor. All 30 FPS games have the same issue. See issue #1083.

One solution is to enable `Full Framebuffer Emulation`, which will output 60 FPS with all games.

Another possible future enhancement is to duplicate frames. See issue #520.

**Comment by fallaha56** [comment]
> This is due to some intro sequences being rendered at 30 FPS on a 60 Hz monitor. All 30 FPS games have the same issue. See issue #1083.
> 
> One solution is to enable `Full Framebuffer Emulation`, which will output 60 FPS with all games.
> 
> Another possible future enhancement is to duplicate frames. See issue #520.

thanks, in case it's good to know i did try the FFE but still seeing the same issue...
