### ISSUE TITLE
Idol Janshi wo Tsukucchaou - Temporary graphical glitch when panel match ends

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1025]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 187674d

Compared to the previous image, it seems to have been stretched twice in the right direction.

[SaveState](https://github.com/flyinghead/flycast/files/11309773/Idol.Janshi.wo.Tsukucchaou.zip) (Select panels in the order ABC to end.)

![Idol Janshi](https://user-images.githubusercontent.com/14366233/233977592-d2262a37-67f2-4a55-bb7d-5edc0202c90f.png)

**Comment by flyinghead** [comment]
should be fixed on the dev branch

**Comment by kihato** [comment]
I can confirm that it has been fixed. thanks.
