### ISSUE TITLE
Urban Chaos - Nearby buildings are covered with shadows and become dark

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1026]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 187674d

If you hold down the X button and look around, it will gradually brighten, and if you release the button, it will gradually darken.
[SaveState](https://github.com/flyinghead/flycast/files/11310005/Urban.Chaos.zip)

You can't see the building and it's very dark.
![Urban Chaos1](https://user-images.githubusercontent.com/14366233/233982173-7a52335c-36f3-42b1-80a8-c6da3e5e73a1.png)

Original brightness (hold X button).
![Urban Chaos2](https://user-images.githubusercontent.com/14366233/233982588-77f06558-6a5d-421a-b5fb-c6374c8eb53f.png)

**Comment by flyinghead** [comment]
How is this supposed to work on real hardware?
I watched some youtube videos but can't figure out the exact problem, if any.

**Comment by kihato** [comment]
Unfortunately I can't check the game on my DC due to drive failure.
I also watched some youtube videos but couldn't find any difference with flycast.
I thought that the screen would be displayed with the same brightness as the PC version, but it was my assumption.
I am sorry to have taken up your precious time.

**Comment by kihato** [comment]
This bug appears to have been fixed in commits after e96b38f. I also confirmed it with the real hardware, and the building next door did not become dark. I have compared them in other places and I think they are almost the same.
