### ISSUE TITLE
Dynamite Cop! - Audio glitches in OP movies and cutscene movies

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1034]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 92a1c18

Holding down the X button during fast forward will cause a black square to appear in the center of the screen.

The master build does not have these issues.

**Comment by flyinghead** [comment]
Should be fixed on the dev branch. Not related to Dynamite Cop! or any game in particular.

**Comment by kihato** [comment]
additional information.

52754cb: Cannot reproduce
095e5ed: Can be reproduced

There are many games that have problems with movies, but the most notable ones are as follows. 

- Resident Evil 2: Setting the cable type to composite causes a problem with the Capcom logo movie, but changing to VGA resolves the problem.

- Dino Crisis (JP version): Subtitles in videos are not displayed at the appropriate time.

- Ultimate Fighting Championship: The positional relationship between the player and the background is not displayed properly in the entrance scene.

- South Park: Rally: Freezes while loading. This occurs when VMU is installed on both A1 and A2.

**Comment by flyinghead** [comment]
Should be fixed in the latest master build
