### ISSUE TITLE
Opening cutscene not showing for Pier Solar

### ISSUE THREAD

**Issue by Starman99x** [flyinghead/flycast#1037]
While the game itself works fine in GDI format with HLE bios enabled, the [opening cutscene](https://youtu.be/O-gzZhmQfds) does not show up and the game skips right to the title screen.

Platform / OS / Hardware: Windows 7 PC / RetroArch

**Comment by flyinghead** [comment]
There are many problems with this game so let's keep everything in the same github issue. See #378
