### ISSUE TITLE
Opengl graphics glitches KOF XI

### ISSUE THREAD

**Issue by batista280** [flyinghead/flycast#104]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android

Github hash: 

Hardware: 

**_Description of the Issue_**

Graphic glitches in the all stages and menú, this did not happen

**_Debugging  Tested_** since versión 7449230 to versión dd102c8

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screensh[[]() ]() ots_**

(Replace this line with any issue screenshots

**Comment by flyinghead** [comment]
Can you test the latest build?

**Comment by batista280** [comment]
> Can you test the latest build?

Well, I saw that you fixed it, you are great, keep on going, I will keep testing and I will notify you, I saw that you improved the performance in Vulkan, it still slows down for example in kof XI when I make a super special (for example from Athena) but how I use opengl it runs super good
