### ISSUE TITLE
Izumo - Some graphical glitches in 3D maps

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1040]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: d3a3cab

The floor under the player's feet is often black.
The background should fade out after the battle ends, but it doesn't.
[SaveState](https://github.com/flyinghead/flycast/files/11343065/Izumo.zip)

**Comment by flyinghead** [comment]
Should be fixed in the next dev build.
