### ISSUE TITLE
Eldorado Gate - Button input is disabled on the menu screen

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1043]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: fc3b904

Vol.4 - Vol.7 cannot proceed from the menu screen.

**Comment by flyinghead** [comment]
This is due to a copy-protection feature

**Comment by flyinghead** [comment]
Fixed in the latest dev build

**Comment by kihato** [comment]
This is big news. Thanks for your great job.
