### ISSUE TITLE
ECW Anarchy Rulz - freeze on loading screen

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1047]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 5f161df

Repeat the title, demo and credits twice.
It freezes on the loading screen after the third title screen.
But with HLE BIOS it seems to be fine.
[SaveState](https://github.com/flyinghead/flycast/files/11358979/ECW.-.Anarchy.Rulz.zip)

**Comment by flyinghead** [comment]
It doesn't happen with the PAL version, even when selecting 60 Hz.

More importantly it doesn't seem to happen on the dev branch (5415442), which means it's probably fixed.

**Comment by kihato** [comment]
Confirmed that the freeze on the dev branch has cleared. Thanks.
