### ISSUE TITLE
Some BIOS fonts displayed incorrectly

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1059]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 1a5a2f6

When using the HLE BIOS, the fonts in the "So" and "Ta" columns are partially replaced by the fonts in the other columns.

Left image: HLE BIOS / Right image: real BIOS
![font_ta_BIOS](https://user-images.githubusercontent.com/14366233/236660829-13cabeb7-20d0-479e-91b5-02435ff255cb.png)

**Comment by crashGG** [comment]
You are really sharp-eyed,didn't expect this to be discovered by you!

**Comment by flyinghead** [comment]
All I can say is: great catch!
JIS X0208 row 66 was actually row 65
