### ISSUE TITLE
Dinosaur - unexpected jump

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1064]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 06270e6

If you move along the coastline, there is a point where you jump in front of the rock for some reason.
I thought it was a bug in the game, but I'm not sure.
[SaveState](https://github.com/flyinghead/flycast/files/11441077/Dinosaur.zip) (ALADAR is placed as a mark.)

https://github.com/flyinghead/flycast/assets/14366233/6e2c101e-3b27-42f7-9e43-45a52e0f059c

**Comment by superkid101Programer** [comment]
Probably just a collision problem.

**Comment by flyinghead** [comment]
The real question is: Does this happen on real hardware?

**Comment by superkid101Programer** [comment]
I can't test it, but looking at it makes me think that spot is the cause of his falling.

**Comment by superkid101Programer** [comment]
I've seen this many times before.

**Comment by superkid101Programer** [comment]
If I open the game, then I can check.

**Comment by kihato** [comment]
It's late, but I got the real hardware and tested it, and was able to confirm that the same bug happen on the real hardware as well.

**Comment by flyinghead** [comment]
Thanks a lot for testing
