### ISSUE TITLE
RE-VOLT - Japanese font colors are wrong

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1065]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 5415442

These are originally displayed in white color.
![Revolt](https://github.com/flyinghead/flycast/assets/14366233/5726a428-305f-4133-8900-8047b6e6d4fc)

**Comment by flyinghead** [comment]
should be fixed in the latest dev build

**Comment by MastaG** [comment]
@flyinghead  Sorry to spam the issue tracker with offtopic questions.
But if I compare the commits between dev and master, I notice that quite a lot of fixes are in the dev branch and not in master.
Is there some roadmap on when you'll merge those into master?

**Comment by kihato** [comment]
Thanks for the fix.
