### ISSUE TITLE
Mr.Driller - Screen goes black when certain settings are selected

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1067]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 5415442

When using DX11 with a composite cable type and Full Framebuffer Emulation enabled, the screen goes black.
It may not be directly related to this game.
If you forget to uncheck the Full Framebuffer Emulation, you may encounter it.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by kihato** [comment]
DX11: The text that should appear after the Sega License logo is no longer displayed.

**Comment by flyinghead** [comment]
Which text?

**Comment by kihato** [comment]
Loading text is not visible. (Both US version and JP version)
Vulkan (Left image) / DX11 (Right image)
![Driller_02](https://github.com/flyinghead/flycast/assets/14366233/73ae3cd1-3d57-4e80-8bfd-70177e9a88ed)

![Driller_01](https://github.com/flyinghead/flycast/assets/14366233/b986e5c0-253e-45ad-a860-1e94099b3b1e)

In the JP version, the text in the window disappears quickly.
![Driller_2](https://github.com/flyinghead/flycast/assets/14366233/19cabc43-8755-4399-a895-2ed837c49609)

**Comment by flyinghead** [comment]
I'm not seeing this issue here. Running on windows 10 with an Intel 640 GPU.
I've tried all combinations of per-tri/per-pix with or without Full Framebuffer Emulation to no avail.
I also tried the latest windows build (2023-09-24) from the builds page to make sure we were running the same code.
No unexpected dx11 warning or error when running in debug mode.

Unfortunately I don't have the JP version and I have limited internet connectivity at the moment.

Any setting on your side that could trigger this issue?

**Comment by kihato** [comment]
I apologize for the inconvenience. 
I don't know the original cause, but it seems that "dx11oit_shader_cache.bin" was causing the problem. 
When I removed this file, it started displaying normally, and when I placed it again, it disappeared.

I don't understand the main cause at all.
If the same problem occurs again, we may find out something, but should we close this issue for now?

**Comment by flyinghead** [comment]
It's possible that this file became corrupted for some reason. Or it might be caching an older version of a shader (which would be a driver bug I guess.) This cache can also cause problems when the GPU driver is updated.
The content of this file is proprietary and depends on the GPU driver and version. Flycast just asks dx11 to load it at startup and save it when shutting down.

If you experience recurrent issues with this cache, please open a new issue.

**Comment by kihato** [comment]
I found a way to reproduce it, so I'll open a new issue.
