### ISSUE TITLE
Disc swapping not working with D2

### ISSUE THREAD

**Issue by trstmp** [flyinghead/flycast#107]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows x64

Github hash: 125c1ff

Hardware: 

**_Description of the Issue_**

Disc swapping doesn't seem to work with D2. It works fine with other games but not D2.

**_Debugging Steps Tested_**

  * Start D2 with disc 1.
  * In the main menu select "Opening Movie." The game will ask for disc 4.
  * Eject disc 1 and insert disc 4. The opening movie should play but it won't.
  * Alternatively, start the game with discs 2, 3 or 4 and select "Start Game". Ejecting the disc and then inserting disc 1 will not start the game.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

Edit: This actually works fine with the Retroarch core, it's only the stand-alone emulator that has the issue.

**Comment by flyinghead** [comment]
This is a regression and I will push a fix shortly.

Note that it works fine with HLE BIOS.

**Comment by trstmp** [comment]
It works now, thank you.
