### ISSUE TITLE
Rent a Hero No.1 - When booting with HLE BIOS, the colors across the screen are darker than normal

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1070]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 5415442

Only on certain screens in the game?
Left image: HLE BIOS - Right image: real BIOS
![Renta_0](https://github.com/flyinghead/flycast/assets/14366233/ba7e34f0-2bd8-4d18-8b5c-6fb1f6b9eae2)
![Renta_2](https://github.com/flyinghead/flycast/assets/14366233/9b59c9eb-faf3-4574-baf6-da1ec576f6de)

**Comment by flyinghead** [comment]
Fixed in the latest dev build

**Comment by kihato** [comment]
Confirmed. Thanks.
