### ISSUE TITLE
Virtua Athlete 2K - World record is not displayed and forced to skip

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1071]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 5415442

The world record for the first 100m dash is displayed, but the subsequent ones are skipped.
Is this also related to GD-ROM speed?

Also, most of the images in this game's ED are not displayed unless Full Framebuffer Emulation is enabled, so if you don't know in advance, you may not notice it.

**Comment by flyinghead** [comment]
I'd rather keep the current gdrom speed as it is
