### ISSUE TITLE
In some cases, it is not possible to change the color of the lightgun crosshair

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1074]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 5415442

After presetting the crosshair color, launch any lightgun game and quit the game from the flycast pause menu.
Open the control tab and you will see the crosshair color gradually change on its own to #FFFFFF00.
(Except for House of the Dead 2)

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by kihato** [comment]
Confirmed. Thanks!
