### ISSUE TITLE
Omikron The Nomad Soul - flycast freezes after EIDOS logo when booting in realBIOS with cable type set to composite

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1080]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: e94babe

It doesn't seem to freeze when booting with VGA or HLE BIOS.
flycast becomes inoperable and must be terminated from the task manager.

9f2ffd1: does not freeze
5c5c872: flycast freezes (#980)

**Comment by flyinghead** [comment]
Should be fixed in the latest dev build.

Thanks for finding the offending commit. It makes things much much easier.

**Comment by kihato** [comment]
No longer freezes. Thanks.
