### ISSUE TITLE
Retroarch not changing vsync swap interval when detecting 3840 x 240p 120hz

### ISSUE THREAD

**Issue by Theoldnation** [flyinghead/flycast#1081]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Retroarch.
Windows/Linux Groovyarcade,
Xeon E5 2640 v3
16gb of ram
Rx 6600 

**_Description of the Issue_**

Apparently Auto vsync swap interval is not detecting that i'm on 120hz nor in progressive and interlaced
this could be a problem combined with switchres as my vga adapter only supports 31khz
so for all res have to by in a minimum of 120hz or interlaced, yet in neither of this two options
swap interval detects my screen refresh rate and chooses to use 1

just leaving on swap auto, 31khz 120hz in switchres with super resolution
3840
open sonic the hedgehog, and won't make the change despite detecting the change
of resolution 

in my log i had first opened the game on swap 2, and change to auto to confirm, and yes auto uses 1 instead of using 2

[retroarch__2023_05_23__15_22_13.log](https://github.com/flyinghead/flycast/files/11545826/retroarch__2023_05_23__15_22_13.log)

**Comment by flyinghead** [comment]
Retroarch cores have no control, or even knowledge, of the monitor refresh rate. You should open an issue on the RetroArch github for this.
