### ISSUE TITLE
Trickstyle (1999) freezes on Libretro, works fine on regular emulator

### ISSUE THREAD

**Issue by Mabadman** [flyinghead/flycast#1082]
**_Platform / OS / Hardware_**
AMD Ryzen 5 5600X, GTX 3060 TI, 16 GB Ram
Windows 10 (Pro, 19044.2965)

**_Description of the Issue_**
When using libretro, Trickstyle (1999) will freeze upon the first menu. The "Press Start button" text is also missing from the title screen.

**_Debugging Steps Tested_**
  * Different ROMs tested, issue persists
  * Nightly build tested, issue persists
  * Flycast.exe tested, issue does not persist

**_Logs Gathered_**
[retroarch-log.txt](https://github.com/flyinghead/flycast/files/11548340/retroarch-log.txt)

**_Screenshots_**
![image](https://github.com/flyinghead/flycast/assets/42493726/1b0dcec1-bf26-4fea-8942-4f9698012dc0)

**Comment by flyinghead** [comment]
No issue here:
![image](https://github.com/flyinghead/flycast/assets/16261910/c0f2806e-6fa3-4ed1-9a55-004f0af35be3)
(linux/vulkan)

What renderer are you using? Have you tried other ones?  Any non-default frontend or core setting/option?
Also please indicate actual version numbers or git hash.

**Comment by flyinghead** [comment]
Interesting find. I can reproduce it on standalone as well when switching language.

@kihato The default Flycast language is English with standalone. Does the libretro core default to German?

**Comment by Mabadman** [comment]
Hi. I see you can reproduce the issue now, but still here's the information you asked for;
I've tried Vulkan, D3D13, and OpenGL (glcore, gl, gl1). Issue persists on all of them.
I didn't provide the git hash because I didn't know how to get it, but I see now Retroarch provides it at the bottom.
I've tested 17ab0ab and 76af42a

I've tried the EU/PAL versions of the game in addition to NA, but same issue persists.
If the issue is indeed tied to the libretro defaulting to german, is there a way to fix this on my end? Thanks.

**Comment by Mabadman** [comment]
Thank, can confirm this fixes it for me as well.

**Comment by flyinghead** [comment]
fixed on the dev branch
