### ISSUE TITLE
Metal Slug 6 inaccurate framerate/bg scroll stutter

### ISSUE THREAD

**Issue by riggles1** [flyinghead/flycast#1083]
Can't find an open issue for this but it's been known since before (threads online mentioning it).
For only this particular game Flycast doesn't handle the scrolling of the background smoothly for some reason, as if the framerate is off, it's constantly unevenly stuttering at all times even when not much is going on action wise (not related to performance).

Using the MAME current set dump, and the conversion just as a test.

Emulating other games including other 2D games and Atomiswave games results in perfectly smooth framerates without any scrolling inconsistencies, Dolphin Blue for example is perfect using the exact same configs, both native and upscaled internal resolutions and testing various settings to try rule out specific settings, using Vulkan as the driver.

Metal Slug 6 when played on a GDEMU on Dreamcast plays at perfect smoothness, indicating that the game is supposed to scroll smoothly.

Platform / OS / Hardware: 
Windows 10 64bit GTX1070 

Both Flycast standalone and RetroArch (which I use a lot for CRTSwitchres CRT output)

**Comment by flyinghead** [comment]
This is due to this game rendering at 30 FPS on a 60 Hz monitor. All 30 FPS games have the same issue. See issue #1022.

One solution is to enable `Full Framebuffer Emulation`, which will output 60 FPS with all games.

Another possible future enhancement is to duplicate frames. See issue #520.

**Comment by riggles1** [comment]
Integer 30 on 60 results in a normal motion jitter, a perfect doubling of moving elements, like the third UFO at 1/2 Hz https://blurbusters.com/wp-content/uploads/2017/12/strobed-display-image-duplicates.png

The game played on hardware will give a consistent 30fps scroll, I can record both at 60fps to show the scroll inconsistency of emulated metal slug 6 without the full frame buffer enabled.

Frame buffer method seems to do the trick however! And is giving me an even 30fps it seems (just a quick boot and test, things seem to motion jitter correctly, I'll have an easier time telling on the CRT due to motion clarity). But I need to compare it with hardware again to be sure how consistent it is.

I'll update you on how it fares, as playing this game on the dreamcast has been really smooth. 

(again not related to performance just to emphasize that, I'm sensitive to framerate mismatches and drops, all other games perform beatifully)

Thank you so much for the reply btw! The frame buffer setting does seem to put it on par with how it scrolls on the dreamcast.

If there's a mismatch I'll make 1080p60fps recordings of both hardware and flycast.

**Comment by riggles1** [comment]
Just tested it properly. Alright yeah full frame buffer on does it and puts it on par with Dreamcast!
Thanks for the tip, I've been testing various settings but totally missed that one. 30fps at 60Hz, with drops when things get hectic, just like it does on hardware.

Hope this issue being here helps others who are wondering why Metal Slug 6 looks so off in the motion department, I've seen it mentioned elsewhere. Would be great if there were a default where it was automatically set to full frame buffer for this particular game. As it's to my knowledge the only game that requires it?

Either case, thanks a lot : D
