### ISSUE TITLE
vsync swap interval based on screen refresh rate

### ISSUE THREAD

**Issue by Theoldnation** [flyinghead/flycast#1084]
I had been trying to configure 31khz 120hz but some of resolutions has to 60hz as my crt can't use
15khz, and interlaced doesn't work in amd windows, so it has to be 240p 120hz and when console is switching to 480p it has to be
60hz, i had setup vsync swap interval to auto, but it won't change the interval when using 120hz to 2, it will still be using 1 or another unknown swap interval

so what do i consider is to add an option to based swap interval in screen reported refresh rate instead of core refresh rate

a hotkey and a controller combo to change vsync swap interval manually

**Comment by flyinghead** [comment]
Is this about the libretro core or standalone?

Standalone already detects the monitor refresh rate and chooses the appropriate swap interval. So with 120 Hz it would choose a swap interval of 2.

**Comment by Theoldnation** [comment]
Dammit, i reported on dreamcast github, sorry
