### ISSUE TITLE
Test Drive V-Rally - When using OpenGL, the top of the laptime font is cut off

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1088]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 76af42a

With full framebuffer emulation enabled, it seems to work fine, but the bottom of the screen is truncated slightly.

**Comment by flyinghead** [comment]
This is due to OpenGL having an inverted Y coordinate system compared to vulkan or dreamcast. The HUD characters are all drawn at .5 coordinates and this causes rounding issues when using nearest sampling.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by kihato** [comment]
Thanks. Wonderful!
