### ISSUE TITLE
Cardcaptor Sakura - Misdisplay of all BestShot images when using OpenGL

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1089]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 76af42a

Start the game with "Copy to VRAM" enabled and take the best shot.
When using OpenGL, an image of a different scene is displayed than the image of the scene where the best shot should be displayed.
Is it correct to understand that this problem is caused by what is explained in (#232)?
I have 6 more games with the same problem, but if they don't use OpenGL, they're fine.

**Comment by flyinghead** [comment]
Yes, it looks like the same issue as #232. Best shots are rendered to the same texture in vram. Presumably the game then copies them to main RAM but the async OpenGL transfer isn't necessarily finished when this copy is done.

**Comment by flyinghead** [comment]
Can I have the list of games that have this issue? I suppose they all need "Copy to VRAM" enabled so it would be nice to force it.
I'm going to remove this OpenGL asynchronous copy to fix these issues.

**Comment by kihato** [comment]
There are 8 games with this issue, slightly more than before.

- **Canvas**
[Canvas.zip](https://github.com/flyinghead/flycast/files/12707424/Canvas.zip)

- **Grandia II**
[Grandia II.zip](https://github.com/flyinghead/flycast/files/12707433/Grandia.II.zip)

- **Kimi ga Nozomu Eien**
[Kimi ga Nozomu Eien.zip](https://github.com/flyinghead/flycast/files/12707435/Kimi.ga.Nozomu.Eien.zip)

- **Pro Mahjong Kiwame D**
[Pro Mahjong Kiwame D.zip](https://github.com/flyinghead/flycast/files/12707445/Pro.Mahjong.Kiwame.D.zip)

- **Sakura Taisen 3**
[Sakura Taisen 3 (Disc1).zip](https://github.com/flyinghead/flycast/files/12707446/Sakura.Taisen.3.Disc1.zip)

- **Tamacue**
[Tamacue.zip](https://github.com/flyinghead/flycast/files/12707447/Tamacue.zip)

The text in the window is not visible.
I don't know if this is the same issue, but Vulkan and DX11 are fine.
- **Miss Moonlight**
- **Yoshia no Oka de Nekoronde**

**Comment by flyinghead** [comment]
I'm not sure where the problem is with Sakura Taisen. I don't see any obvious change when enabling/disabling Copy to VRAM.
Miss Moonlight is fixed by not using GL asynchronous copy so I guess it's the same issue.
Grandia II is also fixed with Copy to VRAM and synchronous copy.

**Comment by kihato** [comment]
In my environment, select the top left image, select the top left image again, and finally press the B button to display the image below.
![Sakura3](https://github.com/flyinghead/flycast/assets/14366233/a079c72c-ac51-41fe-9675-18075aef6b7c)

Grandia's transitions are difficult to understand.
Image from the previous frame.
![Grandia](https://github.com/flyinghead/flycast/assets/14366233/cdaf1d75-195e-416b-8e94-566bd6d73f38)
OpenGL (one frame later)
![Grandia_OpenGL](https://github.com/flyinghead/flycast/assets/14366233/16f48c34-8dec-4863-82d0-7ae2a2c15882)
Vulkan (one frame later)
![Grandia_Vulkan](https://github.com/flyinghead/flycast/assets/14366233/e3bb75fb-041d-4028-8ef2-d775b6fbdc78)

**Comment by flyinghead** [comment]
I see the problem with ST3. So it needs Copy to VRAM and is fixed by using synchronous copy.
I had already noticed the Grandia II issue in the battle start animation.
Thanks

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by kihato** [comment]
I have confirmed that all of the above games are displayed correctly.
Thank you for your hard work!
