### ISSUE TITLE
Fist of the North Star (Atomiswave) - intro music bug

### ISSUE THREAD

**Issue by KamiLordus** [flyinghead/flycast#1101]
During the intro of the Atomiswave version, the background song has a bug. The song is interrupted and a strange sound loop is heard.
I also checked the port on the Dremcast version and didn't notice the problem there.
Retroarch 1.15 (flycast newest core version)
Win 11, rtx 3070ti, i7 8700k

edit:
I noticed one thing:
After deleting the files in Retroarch/saves/reicast/
fotns.zip.nvmem
fotns.zip.nvmem2
The intro plays as soon as I start the game and the song works fine without errors.
After closing the game and restarting, the problem I described above appears.
Restarting the game, it also takes much longer to wait for the intro. First there is the demo, ranking and intro. Completely different than the first launch.

**Comment by KamiLordus** [comment]
It's weird but setting coin assignments to free to play makes the song work properly.
If the game starts when a coin has been "placed", then the song is cut off (around the time of Jagi character introduction).

**Comment by KamiLordus** [comment]
I just found what causes the problem:
Region in the machine settings. Changing the region to english, usa causes the problem described above.
However, I noticed that you don't have to change the region, only the language to have the game in English.
region - japanese
language english
With these settings the song works fine and the game is in English.
I think you can close this issue.

**Comment by flyinghead** [comment]
Interesting find. I can reproduce the audio problem now.
It could be a game bug though.

**Comment by flyinghead** [comment]
assuming it's a game bug

**Comment by kihato** [comment]
This does not appear to have been a bug in the game.
With commit e894d4d, background music now plays properly regardless of region or language selection.
