### ISSUE TITLE
xbox Shenmue 2 PAL disc 1 hle bios freeze on boot

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#1103]
shenmue 2 disc 1 freezes after intro logos at the "now loading" screen with hle bios, lle bios is fine, tested on v2.1 265 g4ca85e959 dev xbox series x

**Comment by flyinghead** [comment]
I can't reproduce it. I tried both the EU and JP versions to no avail.

Do you have any non-default setting? Which edition are you running and what are your settings for Cable and Broadcast?

**Comment by Nejsplitter** [comment]
it freezes on the other discs too but only when loading a game save, default emu.cfg, happens on both standalone dev and libretto dev

**Comment by Nejsplitter** [comment]
https://github.com/flyinghead/flycast/actions/runs/5121859944 i thought i tagged the ver in original post

**Comment by Nejsplitter** [comment]
> Also don't use the dev branch for now since it's lagging behind master atm.

but i like the 500mhz overclock that dev build provides

**Comment by flyinghead** [comment]
I mean: are you running Shenmue II NTSC-Japan edition or PAL-EU edition?
If PAL, do you have Broadcast = PAL?

And I say it again: the dev branch is lagging behind the master branch. Everything on dev is now on master including overclocking. The reverse isn't true.

**Comment by Nejsplitter** [comment]
> I can't reproduce it. I tried both the EU and JP versions to no avail.

which flycast version are you running that you cant reproduce it?

**Comment by Nejsplitter** [comment]
@flyinghead, ok so upon further investigation this seems to be an xbox specific issue, i have tried bisecting but the builds go so far back that they expired and it happens even on the oldest 3-4 month old ones, i have tried master https://github.com/flyinghead/flycast/commit/236539c88161671350f6aa55580b2117400cd830 and the dev build before it on both xbox and my pc and the issue does not happen on pc, i set both versions to use the same default settings

**Comment by flyinghead** [comment]
If the issue is also happening with the lr core then it really is a platform-specific issue since the lr core is the regular windows one. Unfortunately I have no clue at what could be the root cause.

**Comment by Nejsplitter** [comment]
fixed, turns out i had a bad dump
