### ISSUE TITLE
Soul Reaver - Music issue

### ISSUE THREAD

**Issue by RainaAudron** [flyinghead/flycast#1104]
Platform / OS / Hardware: 
Windows 10

Github hash: 
236539c88

Hardware: 
GTX 1060 6GB
i5-6600k

**_Description of the Issue_**
Music in the game does not seem to be playing correctly. See video comparison.

**_Debugging Steps Tested_**
Go to the Ash Village and change to spectral realm and go near an enemy.
The music does not sound correct in comparison to Redream.

**_Logs Gathered_**
https://youtu.be/PugdED_-aac

**Comment by Nejsplitter** [comment]
have you tried enabling dsp in audio settings?

**Comment by flyinghead** [comment]
Can you upload a savestate?

**Comment by flyinghead** [comment]
That won't be necessary: I was able to reproduce the problem

**Comment by RainaAudron** [comment]
Really sorry, I did not have time to upload the save state yet! Great to hear you could reproduce this, though. Thanks for looking into this!

**Comment by flyinghead** [comment]
Should be fixed in the latest master build

**Comment by RainaAudron** [comment]
Just tested it, all correct now, thank you very much!
