### ISSUE TITLE
Star Wars Demolition - Naboo Invincibility Causes Visual Corruption, Powerups Sometimes Crash game

### ISSUE THREAD

**Issue by LenSkozzy** [flyinghead/flycast#1108]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10

Github hash: 236539c88

Hardware: NVIDIA GeForce GTX 750 TI

**_Description of the Issue_**

When picking up the invincibility powerup on Naboo (a pillar of light) the intended blue shader shows visual corruption. Additionally, all powerups (regardless of map) will sometimes cause the emulator to crash

**_Debugging Steps Tested_**

Start the game, choose battle, choose naboo, choose any vehicle. You must push one of the orange chess pieces in the map spawn area into one of the dark blue ones, or vice versa, and a powerup will spawn, which you can walk into; this will either be the invincibility column or a droid.

**_Logs Gathered_**

[windbg_flycast_20880.txt](https://github.com/flyinghead/flycast/files/11727799/windbg_flycast_20880.txt)

[flycast_dumps_2023-06-12.zip](https://github.com/flyinghead/flycast/files/11727800/flycast_dumps_2023-06-12.zip)

**_Screenshots_**

![image](https://github.com/flyinghead/flycast/assets/113231244/2f72f15d-70b0-48b3-8ff7-8d220eea1e34)

![image](https://github.com/flyinghead/flycast/assets/113231244/45370e6e-e8df-4a12-84d7-3980f4d5699c)

![image](https://github.com/flyinghead/flycast/assets/113231244/f029f8a2-41a7-432b-9e00-f6a7e1150291)

![image](https://github.com/flyinghead/flycast/assets/113231244/59cfeb49-5819-4949-87bd-51fcc5ac49bf)

![image](https://github.com/flyinghead/flycast/assets/113231244/8d6c82c8-b8ca-41f5-9a99-84d39b0f49d4)

**Comment by flyinghead** [comment]
Should be fixed in the latest master build
