### ISSUE TITLE
[Switch] Sound issue in cinematics

### ISSUE THREAD

**Issue by Just-me24** [flyinghead/flycast#1116]
Hi
I'm running it on the Switch.
During the cinematics, of any game, the sound quality is very bad/distorded.
I tried to change different settings but it did not help.
Any idea?
Thanks a lot

**Comment by flyinghead** [comment]
Likely a CPU performance issue. Did you overclock your switch?

**Comment by Just-me24** [comment]
Thank you for the answer.
By the way, great job!

No, I did not overclock it.
Guess you are right and It's a CPU performance issue.
The issue is the same with all the games I tried and in different possible file types (bin and cue, cdi, gdi).
I'll leave it like that.
The cinematics are not that important for me.

**Comment by flyinghead** [comment]
Video decoding is notoriously CPU intensive on dreamcast

**Comment by Just-me24** [comment]
Right!
I ran the same games with the PC version of the emulator and the videos play perfectly.
