### ISSUE TITLE
[Switch] Thumbnails in game selection menu

### ISSUE THREAD

**Issue by Just-me24** [flyinghead/flycast#1117]
Hi.

I tried to add pictures to the games in the selection menu like:
jpg or png files named the same as the cue file.

is there any trick to do that?

**Comment by flyinghead** [comment]
edit the file `data/boxart/flycast-gamedb.json`

**Comment by Just-me24** [comment]
I'm afraid my data/boxart folder is empty.
And I found no flycast-gamedb.json anywhere on my sd card.
Is there a way to generate it? Or do I have to download it somewhere?

**Comment by flyinghead** [comment]
Are you using standalone flycast? Which version? 
Do you have the `General > Box Art Game List` option enabled?

The file flycast-gamedb.json is created automatically and it should exist.

**Comment by Just-me24** [comment]
I'm using the lastest flycast.nro on the Nintendo switch.
I pasted it in the /switch/ folder located on the root of my micro SD card so it can be run from hbMenu.
Home directory is /flycast/ located on the root of the micro SD.

Yes, 'Box art game list' was (and is) enabled.
I tried to disable, apply, enable again but no .json file came up.

**Comment by flyinghead** [comment]
On the switch, the folder should be `/flycast/data/boxart/flycast-gamedb.json`

**Comment by flyinghead** [comment]
Can you post a screenshot of the flycast game list?

**Comment by Just-me24** [comment]
Here are the screenshots of my file locations.
I downloaded flycast.nro again and ran it. Still no .json file appeared :-(
It was the same file version that I already had.
Weird.

Please correct me if I'm wrong.
To create a .json file I can open a .txt file, type in what I want and save it.
then I change its extension into .json

If that's right, as last solution you could copy/paste me the file content. If you agree of course.

Children are playing with it at the moment.
I try to get the screenshot without being murdered :-)

Do you want a screenshot of the game selection menu, or the files in the explorer?

**Comment by Just-me24** [comment]
![2023062121055300](https://github.com/flyinghead/flycast/assets/136880125/34c193e4-fef0-422a-82fb-bf5ca59b440c)
![2023062121061700](https://github.com/flyinghead/flycast/assets/136880125/7eb52813-7fad-48ce-8f5c-3544238278f5)

**Comment by flyinghead** [comment]
It's possible that the `flycast-gamedb.json` file doesn't exist because it's only saved when exiting flycast cleanly, and I don't know if it's even possible on switch. That is: flycast is killed and doesn't have a chance to save the file.

**Comment by Just-me24** [comment]
True!
I didn't find the "exit" button.
I always pushed the "home" button and killed the task.

**Comment by Just-me24** [comment]
What if I give him the file?

Can I for example run the PC version on my computer, generate the file and give it to the Nintendo?

**Comment by flyinghead** [comment]
> Can I for example run the PC version on my computer, generate the file and give it to the Nintendo?

Yes, provided the path to thumbnail images are correct.

You can also try to bind the `Exit` button and use it to exit the app.

**Comment by Just-me24** [comment]
I managed to get the file from the PC version.
I will also try to map the "exit" button directly on the switch... tomorrow.
Pretty late now.

Thanks a lot!

**Comment by Just-me24** [comment]
I mapped the "exit" button, but leaving flycast using that button did not generate the .json file.
I took the "flycast-gamedb.json" of the PC version, pasted it on my micro sd card in the folder flycast/data/boxart folder and edited it like this:
`[
    {
        "boxart_path": "",
        "file_name": "",
        "name": "",
        "overview": "",
        "parsed": true,
        "region": 0,
        "release_date": "",
        "scraped": true,
        "search_name": "",
        "unique_id": ""
    },
    {
        "boxart_path": "/flycast/data/boxart/Dino crisis.jpg",
        "file_name": "Dino Crisis (France)[FFF].cdi",
        "name": "Dino Crisis",
        "overview": "",
        "parsed": true,
        "region": 4,
        "release_date": "2000-02-29",
        "scraped": true,
        "search_name": "Dino Crisis",
        "unique_id": "T36806D 09"
    },
    {
        "boxart_path": "/flycast/data/boxart/Bios.png",
        "file_name": "",
        "name": "",
        "overview": "",
        "parsed": true,
        "region": 0,
        "release_date": "",
        "scraped": true,
        "search_name": "",
        "unique_id": ""
    }
]`
It works fine

**Comment by flyinghead** [comment]
The latest `dev` build now saves the boxart database regularly when scraping and provides a clean `Exit` button. So the database should now be properly saved.
