### ISSUE TITLE
Skies of Arcadia - Controller Vibration forgets to stop

### ISSUE THREAD

**Issue by TreeBranches** [flyinghead/flycast#1128]
Platform / OS / Hardware: 
Ryzen 5700G/8GB RAM/Batocera Linux (Retroarch Core)

**_Description of the Issue_**

Xbox Series controller, latest firmware. 

During a battle sequence, the controller will vibrate when performing or receiving an attack or special move (not magic). 

Occasionally, though not consistently, the vibration doesn't stop after an attack. The vibration continues on 100% through the battle results screen, into the world map and until the next battle is triggered. As the battle transition has vibration normally, the controller only stops vibrating then. 

I can also disable the vibration in game and re-enable it, which triggers a vibration and also causes it to stop. 

In an hours play it's guaranteed to happen at least once. 

**_Debugging Steps Tested_**

Other than disabling vibration from Retroarch I'm not sure what else there is to try. 

**_Logs Gathered_**

If you tell me what logs to submit I can send them.

**Comment by flyinghead** [comment]
I haven't been able to reproduce it with RetroArch and looking at the code I don't see how this could happen.
There is an absolute max rumble time of 64 secs, which should stop the vibration. Obviously this is quite a long time but it would be interesting to know if this timeout happens or not.
