### ISSUE TITLE
Web Browsers (Planetweb, Dreamkey, XDP) stop rendering shortly after load

### ISSUE THREAD

**Issue by mrnamwen** [flyinghead/flycast#114]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 1909

Github hash: `a9f1a89`

Hardware: 
AMD Ryzen 3600 @ 4.00Ghz
ASUS RoG Vega 56, Clocked to 1670Mhz
32GB DDR4 RAM at 3200Mhz

**_Description of the Issue_**

Browser successfully opens and connects to the internet. However, following a few minutes of use, the browser will fail to render the page and will appear to have crashed. Links are still clickable and the UI will still function, but the page itself will render on top of almost all text, forcing the user to exit the browser.

The issue was discovered on Dreamkey, but I have since been able to confirm the same bug occurs on both Planetweb and XDP. The bug itself also appears only trigger sometimes, with some XDP sessions working completely fine, although it seems that you can possibly trigger the bug in some scenarios by scrolling with the left stick.

**_Debugging Steps Tested_**

  * Verified if the issue could be reproduced on Planetweb and XDP.
  * Tested using both OpenGL and Vulkan renderers
  * Tested using different cable modes (VGA, Component at 60Hz, Composite)
  * Tested with Copy to VRAM enabled
  * Tested with Delay Frame Swapping enabled
  * Tested with different transparent sorting methods (Triangle, Strip, Pixel)

**_Logs Gathered_**

```
00:00:000 rend/vulkan/vulkan_context.cpp:224 N[RENDERER]: Vulkan API 1.0. Device Radeon RX Vega
00:00:057 rend/vulkan/vulkan_context.cpp:300 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:02:485 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:02:497 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:02:601 imgread/common.cpp:125 W[GDROM]: Warning: CDI Image Loaded! Many CDI images are known to be defective, GDI, CUE or CHD format is preferred. Please only file bug reports when using images known to be good (GDI, CUE or CHD).
00:02:608 ./nullDC.cpp:104 N[BOOT]: Game ID is [MK-51057  ]
20:14:864 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
20:15:201 ./nullDC.cpp:104 N[BOOT]: Game ID is [MK-5104950]
20:15:201 ./cheats.cpp:316 N[COMMON]: Applying widescreen hack to game MK-5104950
26:27:987 windows/winmain.cpp:185 E[COMMON]: [GPF]Unhandled access to : 000000004f2ef060

```
XDP CDI loaded first, then switched to Chu-Chu Rocket GDI and loaded Dreamkey from there.

**_Screenshots_**

I haven't been able to obtain screenshots of the bug yet, as the bug itself seems to only trigger sometimes. I'm attempting to replicate the bug again, and will update the issue with screenshots of the glitched UI.

**Comment by flyinghead** [comment]
The last build should improve web browsing experience in general.

I did reproduce the issue where a page seems to be "stuck" on top of the browser, even when navigating back or away. It seems to happen when using the stick to scroll through the page. I'm not sure this is linked to network/modem emulation. Anyway this issue is probably not fixed.

**Comment by flyinghead** [comment]
More modem improvements in the last build: https://github.com/flyinghead/flycast/commit/579db85b3bc41712f57c4a615031245341da26e2

**Comment by flyinghead** [comment]
assuming this is fixed
