### ISSUE TITLE
Add dual analog controller support

### ISSUE THREAD

**Issue by LuanVSO** [flyinghead/flycast#1143]
According to this [post](https://twitter.com/falco_girgis/status/1678263652732788740?t=WyUhKp57VRVkA53rZbzLug&s=19) at least quake III arena and unreal tournament suport it

Op also provided some [helpful documentation](https://twitter.com/falco_girgis/status/1678477646194176019?t=tsIH6HXJ--NEjuELcaes9A&s=19) on it

**Comment by flyinghead** [comment]
Dual analog controllers are already supported. However the only maple devices that make use of them are the Maracas and the Fishing controller. Probably not ideal for playing quake III...

**Comment by LuanVSO** [comment]
https://github.com/flyinghead/flycast/assets/43626415/4b6d416f-6eab-4e91-b24c-46aaddf54c09

Confirmed it works using the maracas controller. the only problem is the missing buttons

**Comment by flyinghead** [comment]
You must be the first person in the world to have played Quake III with maracas. Congrats!
