### ISSUE TITLE
Mortal Kombat Gold on Flycast UWP is unplayable

### ISSUE THREAD

**Issue by TheElecPlay** [flyinghead/flycast#1145]
Platform / OS / Hardware:  Xbox Series X

Hardware: Xbox Series X

**_Description of the Issue_**

Love the flycast app but I've had issues running Mortal Kombat Gold. Having tested multiple builds of Flycast on Xbox Series X, Mortal Kombat Gold still has graphical issues. I'm running on 3bf817a and it still has these strange lines and I get a white screen as soon as the fight starts. I'm running the game at a native resolution much like my other Dreamcast/Naomi games and I've used per-pixel and have enabled Native Depth interpolation. Any suggestions on how to fix these issues would be appreciated.

The last build where MK Gold was working was  - 5415442 if that helps?

**Comment by flyinghead** [comment]
Knowing the last build that worked is very useful but I don't think the following build would introduce any issue. What is the oldest build you tested that has the issue?

**Comment by TheElecPlay** [comment]
> Knowing the last build that worked is very useful but I don't think the following build would introduce any issue. What is the oldest build you tested that has the issue?

The last build I tried that had the issue was 76af42a and I've tested the subsequent master/dev builds from May 23rd up until the most recent master.

**Comment by flyinghead** [comment]
There's been no change for UWP between these two builds, and the github build environment hasn't changed either.
The only changes are: a MacOS build fix, a Linux AppImage build fix, a breakpad update (not used by UWP) and a libretro core change.

So if you're positive about these build numbers, then it might be due to an xbox firmware update, and not a flycast regression. Re-installing an old flycast build that is known to not have the issue (like https://github.com/flyinghead/flycast/commit/541544292a3d051839672ffa7bd4524a3e1c1c51) would confirm (or not) this point.

**Comment by TheElecPlay** [comment]
> There's been no change for UWP between these two builds, and the github build environment hasn't changed either. The only changes are: a MacOS build fix, a Linux AppImage build fix, a breakpad update (not used by UWP) and a libretro core change.
> 
> So if you're positive about these build numbers, then it might be due to an xbox firmware update, and not a flycast regression. Re-installing an old flycast build that is known to not have the issue (like [5415442](https://github.com/flyinghead/flycast/commit/541544292a3d051839672ffa7bd4524a3e1c1c51)) would confirm (or not) this point.

Appreciate the response. The Xbox firmware might be plausible, but having tested the RetroArch UWP flycast core 5415442 (I'm aware its very outdated) there's no graphical issues with Mortal Kombat Gold. Is there a direct link to download the [5415442] perhaps I'll try it out and see if I have issues with that build.

**Comment by flyinghead** [comment]
You can download the 541544292a3d051839672ffa7bd4524a3e1c1c51 build for UWP here: https://flycast-builds.s3.amazonaws.com/xbox/heads/master-541544292a3d051839672ffa7bd4524a3e1c1c51/flycast.appx
It will be automatically deleted on Aug. 13rd.

**Comment by flyinghead** [comment]
The first step is to find out which change is causing the problem. Once it's identified it can be fixed, or worked around, or avoided in a way or another (or not).
Unfortunately I don't see how any of the 4 commits can affect the UWP build in any way, let alone introduce a regression.
- 415d8c2ea3d35c3feefa3d81a94b8e8774940d98 Fetch translations & Recreate libretro_core_options_intl.h 
- 416e4c5366978ffbe3fc38c7b31f52be2a99fef1 appimage: AppImageKit-checkrt -> linuxdeploy-plugin-checkrt 
- e94babe57e4a8a2c33363e53bc0955eca2368c19 update breakpad submodule 
- 76af42ae6e1a67ef8e00ca96cf2d226407d2618a Latest Vulkan SDK has a new volume name VulkanSDK

**Comment by TheElecPlay** [comment]
> Sorry to bother you again but can you double check that build [76af42a](https://github.com/flyinghead/flycast/commit/76af42ae6e1a67ef8e00ca96cf2d226407d2618a) is failing? You can download it here: https://flycast-builds.s3.amazonaws.com/xbox/heads/master-f679fd9ba9f43d19b0851931513484212f2cdbc1/flycast.appx
> 
> On the contrary, the following build ([ee806bc](https://github.com/flyinghead/flycast/commit/ee806bc) from May 30th) contains many changes and could very well be the culprit.

No worries! I just tested 76af42a and unfortunately its back to being unplayable. White screen and random graphical lines.

**Comment by flyinghead** [comment]
Thank you for your help!

**Comment by TheElecPlay** [comment]
> Thank you for your help!

No worries!

**Comment by TheElecPlay** [comment]
Let me know if there’s anything else I can test for you. Was also wondering if flycast uwp will allow config files and save data files to the external USB drive at some point?

**Comment by flyinghead** [comment]
I still have no idea which change is causing the problem. But here is a non-official build:
[flycast.zip](https://github.com/flyinghead/flycast/files/12071525/flycast.zip)
(rename to .appx)
It uses the latest version of SDL and links statically, instead of using the vcpkg dll version. Pretty much a shot in the dark but who knows...

**Comment by TheElecPlay** [comment]
> I still have no idea which change is causing the problem. But here is a non-official build: [flycast.zip](https://github.com/flyinghead/flycast/files/12071525/flycast.zip) (rename to .appx) It uses the latest version of SDL and links statically, instead of using the vcpkg dll version. Pretty much a shot in the dark but who knows...

Sorry for the late response I just tried the build you provided and unfortunately it still has graphical errors.

**Comment by flyinghead** [comment]
Disabling `Native Depth Interpolation` fixes the issue. This is now done automatically for this game.
