### ISSUE TITLE
"Make Game Config" doesn't work

### ISSUE THREAD

**Issue by xZabuzax** [flyinghead/flycast#115]
I'm using the latest version "a9f1a89" and the option "Make Game Config" doesn't work, changing the button mappings or a emulator option while the game is running and then creating a config file (before changing anything or after changing it) for the game via "Make Game Config" doesn't do anything, it only changes the config globally but not for the specific game.

Hopefully this issue can be resolved.

**Comment by kage2051** [comment]
As far as I know, per-game settings in standalone is not properly implemented yet. @flyinghead might know more about this.

**Comment by flyinghead** [comment]
This should be fixed in the latest build. Per-game button mapping is still not supported though.

**Comment by kathyrollo** [comment]
Hi @flyinghead , I was able to configure specific game buttons for Wild Riders for a session but "Make Game Config" does not save my button configurations per game permanently. Is this still not supported?

**Comment by flyinghead** [comment]
Make sure to create the per-game config like this:
- Start the game
- Pause it and go to Settings > Controls > (your controller) > Map
- Select Arcade Controls (or Dreamcast for a dreamcast game)
- Click Make Game Config
- Set up your game-specific mappings
- Click Done twice

**Comment by kathyrollo** [comment]
Thanks @flyinghead , that did it! I was doing it in reverse (map specific keys before clicking Make Game Config) because other emulators do it that way. All good now. 👍
