### ISSUE TITLE
Sonic Adventure 2 [NTSC] having odd flickering borders at specific part of Egg Quarters

### ISSUE THREAD

**Issue by TailsGuy** [flyinghead/flycast#1151]
Platform / OS / Hardware: Windows 11

Github hash: a21b79cf

Hardware: AMD Ryzen 7 5700X, EVGA NVIDIA GeForce RTX 3070 FTW3

**_Description of the Issue_**

So, there's an odd issue in Egg Quarters in Sonic Adventure 2 (NTSC), (Real BIOS, Automatically sets language to Japanese in game)
where at this specific spot in the level, there are various borders popping in an out rapidly. I've put some photos.

**_Debugging Steps Tested_**

  * Boot SA2 Normally, and go into the Stage Select, Choose Egg Quarters, a Rouge stage near the pyramid in the stage select.
  * You're not far at all, you're in the red room and walk left into the door way which leads into the iron room. You'll notice the flickering by the door way.

**_Logs Gathered_**

These are logs from a second run with logs enabled.

[flycast.log](https://github.com/flyinghead/flycast/files/12092235/flycast.log)

**_Screenshots_**

![Screenshot 2023-07-19 032220](https://github.com/flyinghead/flycast/assets/70661792/b4434ee3-2ad7-48e0-b57d-822c9338ba47)
![Screenshot 2023-07-19 032225](https://github.com/flyinghead/flycast/assets/70661792/ed720728-60e3-41c3-b169-395bb4be698d)
![Screenshot 2023-07-19 032239](https://github.com/flyinghead/flycast/assets/70661792/fe08e3b7-fbd9-49ce-aa3e-34b98af5a5c3)
![Screenshot 2023-07-19 031301](https://github.com/flyinghead/flycast/assets/70661792/a13067d9-032b-4dd5-91e6-c14f530be375)

**Comment by TailsGuy** [comment]
I've upgraded, and it's still there.

Everything's on default except the resolution, and even on native it's still there. I'm on the latest graphics driver, and on DX9.

**Comment by flyinghead** [comment]
Did you try other graphics api?
DX11 is now the default on windows and, based on the crash reports I get, the DX9 nvidia drivers are pretty bad.
Vulkan is worth a try too.

**Comment by TailsGuy** [comment]
Oh, sure, let me do that right now, sorry!

**Comment by TailsGuy** [comment]
It works with DX11 and Vulkan!
