### ISSUE TITLE
VMU support for NAOMI

### ISSUE THREAD

**Issue by Gorilli09** [flyinghead/flycast#1156]
**Is your feature request related to a problem? Please describe.**
Some NAOMI games such as Cyber Troopers Virtual-On: Oratorio Tangram M.S.B.S. Ver. 5.66 and Street Fighter Zero 3 Upper supports VMUs.

**Describe the solution you'd like**
I'd really like VMU support for NAOMI

**Comment by flyinghead** [comment]
VMUs support for Naomi games is already available.
