### ISSUE TITLE
Sonic adventure 1 broken physics.

### ISSUE THREAD

**Issue by tails101** [flyinghead/flycast#1157]
Platform / OS / Hardware: flycast RetroArch android shield tv

Hardware: shield tv 2015

**Broken physics in the game make the game harder to play**

It seems the physics emulation broke somewhere making the game harder to play.
Some area stops you or collide you when you shouldn't.
As exemple thé speed dash attack in the hotel doesn't work properly.
Some loops are harder to pass.
And knuckles dies in the auto demo when it shouldn't because it hit something that shouldn't be there.

The game doesn't work anymore when you use a Dreamcast bios. It seems rendering and all physics break apart without hle.

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
You seem to imply there is a regression with this game.
Which version are you currently using?
And which version was working fine before that?

**Comment by tails101** [comment]
> You seem to imply there is a regression with this game.
> Which version are you currently using?
> And which version was working fine before that?

I think i complained about a similar problem in 2020 but it seems rendering was still working with a bios. I'm using latest stable RetroArch freshly downloaded APK from the site. Not the market version.

**Comment by flyinghead** [comment]
I've never heard of an issue when using a real BIOS with this game.
Can you post a screenshot?
Does Flycast standalone have the same issues?

**Comment by Nejsplitter** [comment]
@tails101 are you using a modded rom or the 60fps sonic adventure patch? and what is your cpu overclock set to in flycast settings?

**Comment by tails101** [comment]
> @tails101 are you using a modded rom or the 60fps sonic adventure patch? and what is your cpu overclock set to in flycast settings?

I'm using the pal original iso no mod no oc

**Comment by tails101** [comment]
> I've never heard of an issue when using a real BIOS with this game.
> Can you post a screenshot?
> Does Flycast standalone have the same issues?

I'm not using flycast standalone sorry, is it compatible android tv?

**Comment by flyinghead** [comment]
> I'm not using flycast standalone sorry, is it compatible android tv?

Yes

**Comment by Nejsplitter** [comment]
> > I've never heard of an issue when using a real BIOS with this game.
> > Can you post a screenshot?
> > Does Flycast standalone have the same issues?
> 
> I'm not using flycast standalone sorry, is it compatible android tv? I'm sorry i would love to take a screenshot but I don't have the original controller for that sadly. I'll describe. When using a bios the title screen background is black. When selecting a character, the character 3d model is missing. And in game after you load, everything is black and you hear sonic dying like there was no ground.
> 
> Everything works as it should when you set force hle to on. Outside the few physics bugs that bugs the spin dash and a few loops.

have you tried GL and Vulkan?

**Comment by tails101** [comment]
> > > I've never heard of an issue when using a real BIOS with this game.
> > > Can you post a screenshot?
> > > Does Flycast standalone have the same issues?
> > 
> > 
> > I'm not using flycast standalone sorry, is it compatible android tv? I'm sorry i would love to take a screenshot but I don't have the original controller for that sadly. I'll describe. When using a bios the title screen background is black. When selecting a character, the character 3d model is missing. And in game after you load, everything is black and you hear sonic dying like there was no ground.
> > Everything works as it should when you set force hle to on. Outside the few physics bugs that bugs the spin dash and a few loops.
> 
> have you tried both GL and Vulkan?

I'm using Vulcan since it is a sertified Vulcan device.

**Comment by tails101** [comment]
> You seem to imply there is a regression with this game.
> Which version are you currently using?
> And which version was working fine before that?

Core version 17b82ab

**Comment by Nejsplitter** [comment]
> > > > I've never heard of an issue when using a real BIOS with this game.
> > > > Can you post a screenshot?
> > > > Does Flycast standalone have the same issues?
> > > 
> > > 
> > > I'm not using flycast standalone sorry, is it compatible android tv? I'm sorry i would love to take a screenshot but I don't have the original controller for that sadly. I'll describe. When using a bios the title screen background is black. When selecting a character, the character 3d model is missing. And in game after you load, everything is black and you hear sonic dying like there was no ground.
> > > Everything works as it should when you set force hle to on. Outside the few physics bugs that bugs the spin dash and a few loops.
> > 
> > 
> > have you tried both GL and Vulkan?
> 
> I'm using Vulcan since it is a sertified Vulcan device.

does the issue also happen when you switch to open gl?

**Comment by flyinghead** [comment]
Assuming this is fixed

**Comment by tails101** [comment]
Well no you assume it wrong.
During the auto demo tails is still stuck
And knuckles still dies so there is still something very wrong in the emulated phisics.

**Comment by MastaG** [comment]
Hi @flyinghead 
I can reproduce the issues with the auto-demo on my Android 14 phone.
It's connected to a USB-C dock and monitor.

I'm running the unmodified GDI on the latest master build for android (as of yesterday) with OpenGL (per-triangle), retail bios and no widescreen hacks/cheats.


https://github.com/flyinghead/flycast/assets/15012115/c6e34c56-a3dd-43ac-bf7d-48c2146743f4



https://github.com/flyinghead/flycast/assets/15012115/5a4ff1b6-d3e3-44fc-af19-9b66e0fbe70f


So there must be some precision issues when running Sonic Adventure on flycast on ARM64 and/or Android?

**Comment by flyinghead** [comment]
There are floating precision issues on all platforms and CPUs. They tend to manifest themselves in demo/attract mode, particularly with driving games but could affect other types of games.
See #644 and #760 for example.

**Comment by tails101** [comment]
> There are floating precision issues on all platforms and CPUs. They tend to manifest themselves in demo/attract mode, particularly with driving games but could affect other types of games. See #644 and #760 for example.

We know this,that doesn't mean it can't be improved.
At the time the emulator was still called demul , sonic was dying in the first demo in speed highway.
But nowdays it pass this demo without issues.
So there was improvement.and it can have more.
