### ISSUE TITLE
Toy Story graphics corruption

### ISSUE THREAD

**Issue by Tasosgemah** [flyinghead/flycast#1159]
Platform / OS / Hardware: 

Windows 10

Hardware: 

i5 4670, GTX 1060

**_Description of the Issue_**
Toy Story polygons are glitchy with many of them disappearing depending on the camera position.

Demul and Redream don't have these issues and the game looks perfect.

**_Screenshots_**

![Toy Story 2 - Buzz Lightyear to the Rescue! (USA)-230727-210145](https://github.com/flyinghead/flycast/assets/12124465/5cb61046-d653-4e0d-a045-93576ce68c51)

**Comment by flyinghead** [comment]
Use per-pixel in the video settings.

**Comment by Tasosgemah** [comment]
> Use per-pixel in the video settings.

This is with the "per-pixel" option.

**Comment by Tasosgemah** [comment]
Version is 9c61006

Everything is default except per-pixel.

I was using OpenGL but Vulkan seems to fix the issue.

Should i change to Vulkan for all games?

**Comment by flyinghead** [comment]
Pick the one that works best on your platform. DirectX 11 is the default on windows so it's also worth a try.

**Comment by flyinghead** [comment]
Can't reproduce with GTX 1080
