### ISSUE TITLE
Feature Request: The ability to increase the size of the on screen VMU

### ISSUE THREAD

**Issue by PABastien1** [flyinghead/flycast#1165]
**Is your feature request related to a problem? Please describe.**
It's kind of hard to read the VMU in games that use it to track things like health. For example Resident Evil 2 or Dino Crisis.

**Describe the solution you'd like**
The ability to increase the size by 2 to 6 times. Maybe the ability to bind a hotkey to cycle sizes.

**Comment by flyinghead** [comment]
Duplicate of #162
