### ISSUE TITLE
Android：The emulator froze

### ISSUE THREAD

**Issue by android-1995** [flyinghead/flycast#1168]
Platform / OS / Hardware: HarmonyOs(Android)

Github hash: 92a10ba0f0a5ca0d1ec9498962002f4cdcc8e7f6

Hardware:  Phone:**HONOR nova 4** CPU:**HiSilincon Kirin 970** GPU:**Mali-G72**

**_Description of the Issue_**

When the app returns to the front desk from the background for the first time, it will get stuck for about 15 seconds, and then switch to the front and back desk to no longer get stuck
**I also tested Snapdragon's phone and there was no such issue.**

**_Debugging Steps Tested_**

  * Open the emulator and place it in the background
  * Restore the emulator to the foreground. (At this point, it will be stuck for 15 seconds)
  * Repeat the above steps. (no longer get stuck)

**Comment by flyinghead** [comment]
This looks like an issue with the graphics drivers on this phone. Flycast doesn't pause during initialization.
Does it happen for both OpenGL and Vulkan?

**Comment by android-1995** [comment]
yes,it happen for both OpenGL and Vulkan

**Comment by flyinghead** [comment]
assuming this is a GPU driver issue
