### ISSUE TITLE
[Flycast APK rev.a9f1a89] [2D Graphics Glitch] [Crashing]

### ISSUE THREAD

**Issue by Gamemulatorer** [flyinghead/flycast#117]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

### Platform / OS / Hardware: 
Android/Marshmallow 6.0.1/Mali-450 GPU
### Github hash: 
a9f1a89
**_Description of the Issue_**
I tried to use flycast apk during 1st installation the emulator works fine but with a graphics glitches
![Screenshot_20200923-105434](https://user-images.githubusercontent.com/37603562/93963059-c32e5b80-fd8e-11ea-9f82-17a38463f6e8.png)
![Screenshot_20200923-105510](https://user-images.githubusercontent.com/37603562/93963095-d6d9c200-fd8e-11ea-9328-6b33ba836297.png)
After I play a minutes I exit the emulator and try again to play the emulator is now always crashing :(
![Screenshot_20200923-112210](https://user-images.githubusercontent.com/37603562/93963169-0d174180-fd8f-11ea-97d3-357ad31e3d95.png)

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**
[Flycast_logcat.zip](https://github.com/flyinghead/flycast/files/5265365/Flycast_logcat.zip)

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**Comment by flyinghead** [comment]
The graphic glitches are probably due to a GPU driver bug. Android 6 is quite old and old Mali drivers have issues.

The crash when exiting a game and restarting might be a different issue. Thanks for the logs.

**Comment by Gamemulatorer** [comment]
> The graphic glitches are probably due to a GPU driver bug. Android 6 is quite old and old Mali drivers have issues.
I don't have to much graphics issue using reicast unlike this flycast.

>  The crash when exiting a game and restarting might be a different issue. Thanks for the logs.

No problem 👍

**Comment by flyinghead** [comment]
Could you try this build? fbe9cc3936e0853907b6562d7e79c3b3ce585b15
And the next build: 7449230af8f88e84f861bf17dd8b6690e0f93383

The glitches might be due to handling palettes on the GPU, which was added in build 7449230a. This would explain why reicast doesn't have these glitches.

**Comment by Gamemulatorer** [comment]
Both build fbe9cc3 and 7449230 are stuck on black screen :(
![Screenshot_2020-10-13-00-04-01](https://user-images.githubusercontent.com/37603562/95767737-c3fc4280-0ce7-11eb-9e1d-efd3146754bd.png)
