### ISSUE TITLE
Beach Spikers (NAOMI 2) Some screens are smaller than normal

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1177]
Platform / OS / Hardware: Windows 11 

Github hash: 56b082d

Hardware: Nvidia Geforce RTX 3050ti Laptop GPU, AMD Ryzen 5600H @3.3GHz

Some screens including the parental advisory screen is smaller than on original hardware, this also effects the staff roll, this doesnt happen on og hardware, using per pixel with the Vulkan renderer. 

https://www.youtube.com/watch?v=OpBaUHEgeMY

![Flycast 8_24_2023 9_23_29 AM](https://github.com/flyinghead/flycast/assets/91135037/11ee2c40-e665-4cf6-9beb-e188b008b24d)

https://github.com/flyinghead/flycast/assets/91135037/051aba6a-cb41-467c-9b34-4188d1278a2a

**Comment by flyinghead** [comment]
should be fixed in the last dev build
