### ISSUE TITLE
[NVIDIA Quadro 3000M] Virtua Fighter 4 Final Tuned - NAOMI2 (vf4tuned) DirextX11/OpenGL - Unresponsive/Black screen/Rainbow Water

### ISSUE THREAD

**Issue by Silverfoenix** [flyinghead/flycast#1178]
Laptop / Windows10 pro 64-bit 22H2/ Dell Precision M6600

Using Master build [92a10ba](https://github.com/flyinghead/flycast/commit/92a10ba)

Hardware: 
[DxDiag.txt](https://github.com/flyinghead/flycast/files/12448135/DxDiag.txt)

If only my other ATI mobility Laptop was alive I would have tested if it was Nvidia issue only HOWEVER
I Also tried out of curiosity on a very old laptop Acer Aspire 4720 intel 965 graphics running windows 8.1 pro 64-bit with same bug on same stage...
Surprisingly it can handle Naomi 1 with some slow downs in Ikaruga 😁 Naomi2 is slide show due to hardware limitations.
IDK how it ran DirectX11 on hardware that barely support DX9 tho~🤔

**_Description of the Issue_**

Water texture corruption Sometimes causes Unresponsive Crash or black display or Rainbow textures (Behavior changes but the cause is the same?)
 The Unresponsive Crash occured in Shun Di Stage IN PARTICULAR (Trying again result in Black), While Aoi Umenokoji stage runs showing rainbow water 😂
Basically Other stages run fine except for those that have WATER !!!!

**_Debugging Steps Tested_**

  * Set Video options to bare minimum, Resolution NATIVE, No Widescreen, etc.. (Disabling/Enabling Fog & Shadows have no effect)
  * Copy to VRAM is Disabled in reference to issue [778](https://github.com/flyinghead/flycast/issues/778#issuecomment-1278095120)
  * Tried latest Dev version [3aa2f92](https://github.com/flyinghead/flycast/commit/3aa2f92) also crashes on the Old
  * Tried release 2.0 (Stage no longer crash Flycast & managed to get a screenshot with Rainbow water)
  * Tried OpenGL backend, Stage now loads with black screen (Voices & BGM work), NOW loading a savestate from the previous attempt shows correct water (Second screenshot)!!!
  * Tried Dev version again with same OpenGl settings it loaded the Shun Di stage with Rainbow Water, loading save state keeps the rainbow water...
  * Changed Naomi2 bios to a recent mame 0.257 one~
  * Back to release 2.0 its now the same behavior as Dev Version (RAINBOW) (I noticed Dev version shows "Network System" in BIOS screen BTW)

**_Logs Gathered_**
Right after enabling logging:
[flycast.log](https://github.com/flyinghead/flycast/files/12448174/flycast.log)

Final Log:
[flycast.log](https://github.com/flyinghead/flycast/files/12448230/flycast.log)

**_Configuration_**
```
[audio]
backend = auto

[config]
BoxartDisplayMode = yes
Debug.GDBEnabled = no
Debug.GDBPort = 3263
Debug.GDBWaitForConnection = no
Debug.SerialConsoleEnabled = no
Debug.SerialPTY = no
Dreamcast.AutoLoadState = no
Dreamcast.AutoSaveState = no
Dreamcast.Broadcast = 0
Dreamcast.Cable = 3
Dreamcast.ContentPath = F:\GAMES\Dreamcast\ROMS;E:\.emulationstation\roms
Dreamcast.ForceWindowsCE = no
Dreamcast.FullMMU = no
Dreamcast.HideLegacyNaomiRoms = no
Dreamcast.Language = 1
Dreamcast.Region = 1
Dreamcast.SavestateSlot = 0
Dynarec.Enabled = yes
Dynarec.idleskip = yes
FastGDRomLoad = no
FetchBoxart = yes
ForceFreePlay = yes
LuaFileName = flycast.lua
Profiler.DrawGUI = no
Profiler.Enabled = no
Profiler.FrameWarningTime = 0.018182
Profiler.OutputTTY = no
UploadCrashLogs = yes
UseReios = no
aica.AutoLatency = no
aica.BufferSize = 2822
aica.DSPEnabled = yes
aica.Volume = 100
pvr.AutoSkipFrame = 1
pvr.MaxThreads = 3
pvr.rend = 2
rend.AnisotropicFiltering = 1
rend.CrossHairColor1 = -16316424
rend.CrossHairColor2 = -73599738
rend.CrossHairColor3 = 0
rend.CrossHairColor4 = 0
rend.CustomTextures = no
rend.DelayFrameSwapping = yes
rend.DumpTextures = no
rend.DupeFrames = no
rend.EmulateFramebuffer = no
rend.ExtraDepthScale = 1.000000
rend.FloatVMUs = no
rend.Fog = yes
rend.MaxFilteredTextureSize = 256
rend.ModifierVolumes = yes
rend.NativeDepthInterpolation = no
rend.PerPixelLayers = 50
rend.PerStripSorting = yes
rend.PixelBufferSize = 536870912
rend.RenderToTextureBuffer = no
rend.Resolution = 480
rend.Rotate90 = no
rend.ScreenStretching = 100
rend.ShowFPS = no
rend.SuperWideScreen = yes
rend.TextureFiltering = 0
rend.TextureUpscale = 1
rend.ThreadedRendering = yes
rend.TranslucentPolygonDepthMask = no
rend.UseMipmaps = yes
rend.WideScreen = no
rend.WidescreenGameHacks = no
rend.vsync = yes
ta.skip = 1

[input]
MouseSensitivity = 122
RawInput = yes
VirtualGamepadVibration = 20
device1 = 0
device1.1 = 1
device1.2 = 1
device2 = 0
device2.1 = 10
device2.2 = 10
device3 = 10
device3.1 = 10
device3.2 = 10
device4 = 10
device4.1 = 10
device4.2 = 10
maple_raw_keyboard_\\?\ACPI#PNP0303#4&d0e7fd3&0#{884b96c3-56ef-11d1-bc8c-00a0c91405dd} = 0
maple_raw_mouse_VID_192F&PID_0916#7&3a9394bd&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 0
maple_raw_mouse_\\?\ACPI#DLL04A4#4&d0e7fd3&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 1
maple_sdl_keyboard = 0
maple_sdl_mouse = 0

[log]
LogToFile = yes

[network]
ActAsServer = no
DNS = 46.101.91.123
EmulateBBA = no
Enable = no
EnableUPnP = yes
GGPO = no
GGPOAnalogAxes = 0
GGPOChat = yes
GGPOChatTimeout = 10
GGPOChatTimeoutToggle = yes
GGPODelay = 0
LocalPort = 37391
NetworkOutput = no
Stats = yes
server = 

[validate]
OpenGlChecks = no

[window]
fullscreen = no
height = 480
left = 640
maximized = yes
top = 300
width = 640

```

**_Screenshots_**
Hitting any button while screen like this may cause Flycast to be Unresponsive
![image](https://github.com/flyinghead/flycast/assets/48087298/3bbf52b1-9ae5-49c3-8c60-fa59bb0455c4)

Took a savestate under DirectX11 backend
![image](https://github.com/flyinghead/flycast/assets/48087298/a26384e0-799e-4575-a080-8fdeddd2765f)

Loaded savestate under OpenGL backend
![image](https://github.com/flyinghead/flycast/assets/48087298/7f05b1aa-d3d7-4bde-8afc-53c5ac290491)

**Comment by flyinghead** [comment]
These problems are very likely due to limitations of your GPU or its driver. Naomi 2 is much more demanding than Naomi 1 and your GPU is quite old (thus slow and limited).

Stages with water render in 2 passes: the first one renders the water surface reflections, and the second renders the complete scene mapping the texture obtained in pass 1 for the water surface. Consequently these stages are even more demanding (120 renders/s instead of 60).

**Comment by Silverfoenix** [comment]
I downloaded Retroarch64, downloaded the Flycast core 92a10ba
Anyhow this is the result!
![image](https://github.com/flyinghead/flycast/assets/48087298/8911cb0f-05b0-4176-beaa-22fe4a76d762)
Any idea?

**Comment by flyinghead** [comment]
I suppose retroarch is doing something different somewhere and your GPU likes it. I suggest you use RA for naomi 2 emulation since it's working fine on your platform.
