### ISSUE TITLE
Spikers Battle (NAOMI) Sound samples cut off or missing entirely 

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1180]
Platform / OS / Hardware: Windows 11

Github hash: d29645c

Hardware: Nvidia Geforce RTX 3050ti Laptop GPU, AMD Ryzen 5600H @3.3GHz

Some of the audio samples are either missing, or simply get cut off too early, for example, this mostly affects the samples from the announcer. Enable audio dsp is enabled.

**Comment by flyinghead** [comment]
Should be fixed in the  latest dev build.
