### ISSUE TITLE
Kao the Kangaroo has glitchy sounds in the menu

### ISSUE THREAD

**Issue by ualaa1** [flyinghead/flycast#1181]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10

Github hash: a21b79cf

Hardware: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz

**_Description of the Issue_**

Kao the Kangaroo has glitchy sounds on the title screen menu

See https://imgur.com/a/eAqjktI

**Comment by flyinghead** [comment]
These glitches are the VMU sounds. You can disable them in the game options menu or in the Flycast settings.
