### ISSUE TITLE
Sonic adventure bug light speed dash

### ISSUE THREAD

**Issue by Klaruuss** [flyinghead/flycast#1183]
Platform / OS / Hardware: android

Github hash: 

Hardware: Ram:2,00gb
Rom:16,00gb

**_Description of the Issue_**
In the game, in the underground part where you get the light speed dash, there's a bug where Sonic doesn't follow the ring trail, I think it's already a known bug.

**_Screenshots_**
![Screenshot_20230904-115020](https://github.com/flyinghead/flycast/assets/109044258/e13fb11f-48aa-40b6-a8ca-0ea1252e0351)

**Comment by PiKeyAr** [comment]
This usually happens when you use bad CDI rips of the game, even on a real console. Try a GDI rip.
