### ISSUE TITLE
[Bug/Libretro/GL] Per-pixel isn't working

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1191]
I recently went back to GL from DX11/Vulkan as it's the most stable for me with AMD latest drivers. Performance is also the best with GL now (thanks AMD).

I found a strange quirk with Per-Pixel setting. It's for all games but the game we'll be talking about is Capcom vs. SNK.

The winning KO is only correct with that setting but it doesn't behave properly with GL. It's like the setting is off. The strange way to solve it is to change any setting in the core option (even reverting it) and Per-Pixel will correctly activate.

You can test it with the attached save state.

![Capcom vs  SNK - Millennium Fight 2000 (Japan)-230909-092853](https://github.com/flyinghead/flycast/assets/47425204/55d53ac0-1f8b-4f84-9a2c-cbc8dc83384d)
[retroarch.log](https://github.com/flyinghead/flycast/files/12565263/retroarch.log)
[Capcom vs. SNK - Millennium Fight 2000 (Japan).zip](https://github.com/flyinghead/flycast/files/12565264/Capcom.vs.SNK.-.Millennium.Fight.2000.Japan.zip)

This doesn't occur with Standalone.

**Comment by flyinghead** [comment]
Should be fixed in the next core update.

**Comment by Immersion95** [comment]
Now works perfectly :)
