### ISSUE TITLE
[Bug] D3D11 with threaded rendering OFF - No SEGA logo screen at startup

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1192]
The famous SEGA blue logo screen should appear after the swirl but it doesn't on D3D11. No problem with GL/Vulkan.

![Ecco the Dolphin - Defender of the Future (Europe) (En,Fr,De,Es)-230909-102814](https://github.com/flyinghead/flycast/assets/47425204/7641a4b2-fbba-496d-b0b2-9db7cb11e22f)

**Comment by flyinghead** [comment]
I can't reproduce this issue here.
Using RA 1.14.0 and the flycast core (1377e61d) on win10.
D3D11 with GPU Intel Iris+ Graphics 640
I tried both HLE and normal BIOS, per-triangle and per-pixel. In all cases the Sega logo is visible.

**Comment by Immersion95** [comment]
> I can't reproduce this issue here. Using RA 1.14.0 and the flycast core ([1377e61](https://github.com/flyinghead/flycast/commit/1377e61d03c14399e4298f1af1a871cc8f00c12a)) on win10. D3D11 with GPU Intel Iris+ Graphics 640 I tried both HLE and normal BIOS, per-triangle and per-pixel. In all cases the Sega logo is visible.

Sorry, you have tohave Threaded off.

Please note that I disable it as it adds 2 frames of input lag and that my PC is strong enough (I thing it's needed for old CPU/GPU).

**Comment by flyinghead** [comment]
Should be fixed in the next core update.

**Comment by Immersion95** [comment]
> Should be fixed in the next core update.

Thanks @flyinghead, you're the best ! It works perfectly!
