### ISSUE TITLE
[Retroarch] Vulkan driver and 120hz monitor problem.

### ISSUE THREAD

**Issue by KamiLordus** [flyinghead/flycast#1194]
In retroarch on the flycast core, I use the vulkan driver to be able to enable shaders.
The problem is that I use a 120 hz monitor and I have problems with the speed of games on the flycast core with the vulkan driver.
I have vsync turned on and the games show 60 fps all the time, but they clearly run slower.
In such a case, the "vsync swap interval" option comes in handy - it works great on other cores with the dx11 driver.
Unfortunately, it doesn't quite work properly with vulkan. After enabling vsync swap interval to 2, games have the correct speed (smooth 60 fps).
However, each time you activate the retroarch menu, the screen flashes for a while. This is quite frustrating.
Is there any way to fix this?

RA 1.16
Flycast core latest
Win 11, rtx 3070ti
Vulcan driver

**Comment by Immersion95** [comment]
Can't you use Slang shaders with DX11 too ? I personally have VRR on my 120hz screen and it's perfectly smooth. Your Vulkan problem is more if a RA's problem for me.

**Comment by KamiLordus** [comment]
Exactly, shaders on dx11 do not work.
For me, Vulcan at 120 h with a monitor has a problem with the menu or the speed of the flycast.
On GL, the swap interval driver works properly, but it has graphics errors.
