### ISSUE TITLE
Metropolis Street Racer no full screen

### ISSUE THREAD

**Issue by SSRRedDevil** [flyinghead/flycast#1195]
The game starts in fullscreen, but when you're in a race there is a huge boarder on both sides. Is there a way that this can be fixed? Thanks.

**Comment by flyinghead** [comment]
There is a small border on the left side due to the game using unusual video sync values:
![image](https://github.com/flyinghead/flycast/assets/16261910/b9bd98f8-98d6-4e4f-8063-ee091fe127bd)
However there's no "huge" border. If you have a wide screen, enable Widescreen Cheats.

**Comment by SSRRedDevil** [comment]
I get a weird strobe/mirrored effect when I turn wide-screen on

**Comment by flyinghead** [comment]
`Widescreen Game Cheats`, not `Widescreen`

**Comment by SSRRedDevil** [comment]
The only "fix" I can find is horizontal stretching to 125 and that gets rid of the boarder.

**Comment by SSRRedDevil** [comment]
Thanks for the help though.

**Comment by SSRRedDevil** [comment]
Just to clarify, this issue was on the Series S, not on a PC.

**Comment by vkedwardli** [comment]
With standard video settings, when you play a 4:3 game on a widescren monitor, you should get a "huge border on both sides", aka a **Letterbox**.
When  `Widescreen` enabled, if the game is not drawing the 3D objects correctly in the extended area, it is known as the **Edge Culling problem**.
When  `Widescreen Game Cheats` is enabled, but the game is still not drawing 3D objects correctly in the extended area, then there is a problem.

Try to enable `Widescreen Game Cheats` first before loading the game?
