### ISSUE TITLE
Rush 2049 Graphical Corruption [Vulkan]

### ISSUE THREAD

**Issue by Abystus** [flyinghead/flycast#1197]
**_Github hash:_**

b564b0b

![image](https://github.com/flyinghead/flycast/assets/1529049/1fe30642-9124-41f4-b43b-94a52db2e842)

**_Hardware:_**

Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.2.0-32-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 16.0 GiB of RAM
Graphics Processor: AMD Radeon RX 5500
Vulkan Instance Version: 1.3.204 (from vulkaninfo)
Mesa Version: 23.0.4

**_Description of the Issue_**

When using the Vulkan implementation, the top and bottom borders of the screen appear blank or corrupted, and there is texture jumping, blinking, or skewing. All of these issues are shown in the screenshots below, denoted by green boxes. Switching to OpenGL corrects these issues.

**_Screenshots_**

![image](https://github.com/flyinghead/flycast/assets/1529049/d2da4a0f-9df8-43e5-978f-a71832ade706)
![image](https://github.com/flyinghead/flycast/assets/1529049/e0da4200-2d5b-4693-8129-792c25e9f45c)
![image](https://github.com/flyinghead/flycast/assets/1529049/52aba0c1-f411-4da3-b427-3b6b30d66fe0)
![image](https://github.com/flyinghead/flycast/assets/1529049/686c213d-0177-417e-b188-caf548b3d9e7)
![image](https://github.com/flyinghead/flycast/assets/1529049/d08033f4-93fe-4d9b-8bab-5e6113eb1123)

**Comment by flyinghead** [comment]
The issues in the last 2 screenshots (grass, sky, road) are likely due to AMD loss of precision when interpolating. Try enabling `Video > Native Depth Interpolation`

The other issues (top and bottom rectangles) are different and not specific to AMD.

**Comment by Abystus** [comment]
> The issues in the last 2 screenshots (grass, sky, road) are likely due to AMD loss of precision when interpolating. Try enabling `Video > Native Depth Interpolation`
> 
> The other issues (top and bottom rectangles) are different and not specific to AMD.

Enabling that option indeed resolved the graphical corruptions in the textures, just as you mentioned. Hopefully the other issue is easily correctable going forward. Thanks for the quick reply.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build
