### ISSUE TITLE
[flatpak] Stack Smashing Detected: Terminated

### ISSUE THREAD

**Issue by victorsvcs** [flyinghead/flycast#1199]
Platform / OS / Hardware: 
Ubuntu 22.04.2 LTS
64 bits
GNOME Version 42.5

Github hash: 

Hardware: 
Dell Inc. Inspiron 5420
Memory 6,0 GiB
Processor Intel® Core™ i5-3210M CPU @ 2.50GHz × 4
Graphics GeForce GT 630M/PCIe/SSE2 / GeForce GT 630M/PCIe/SSE2

**_Description of the Issue_**

After running Flycast I get this message, what is it?

Stack Smashing Detected: Terminated

![Captura de tela de 2023-09-18 14-08-13](https://github.com/flyinghead/flycast/assets/145380088/b8da6119-5349-47ae-a4e8-cd831769db6f)

**Comment by flyinghead** [comment]
I can't reproduce this issue with the latest Flycast flatpak build (on Ubuntu 20.04.6 LTS).
It could be due to the GPU driver.
Does flycast run normally or does it crash immediately at startup?

**Comment by victorsvcs** [comment]
Flycast doesn't even open. I only get to know the reason through the terminal.

Of all emulators, this is happening only with Flycast and PPSSPP after the last update.

**Comment by flyinghead** [comment]
If it also happens with PPSSPP then it's very likely an issue with flatpak or one of its installed dependencies.

**Comment by victorsvcs** [comment]
What should I do? Keep updating flatpak until it eventually get corrected?

**Comment by victorsvcs** [comment]
Thanks.

**Comment by flyinghead** [comment]
Is this still happening?
I updated flatpak to 1.14.4 and Flycast to latest and it still runs fine on ubuntu 20.04.6 LTS.

Based on the linked issue above, it's happening for other software as well.

**Comment by vkedwardli** [comment]
> The bug concerns the flatpak version, when used with "org.freedesktop.Platform 23.08"; it is not there with "org.freedesktop.Platform 22.08"

**Comment by flyinghead** [comment]
Trying to use `org.freedesktop.Platform 22.08` didn't succeed for me, which is why I didn't mention it.
```
$ flatpak run --runtime=org.freedesktop.Platform//22.08 org.flycast.Flycast
flycast: /usr/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by flycast)
flycast: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by flycast)
flycast: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by flycast)
flycast: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by flycast)
```

**Comment by flyinghead** [comment]
Any update on this?

**Comment by flyinghead** [comment]
Assuming this is fixed
