### ISSUE TITLE
Fist of the north star (Atomiswave) HP bar, layer bug

### ISSUE THREAD

**Issue by pyjmj05** [flyinghead/flycast#120]
EmuELEC 3.8 / Odroid N2+

![1](https://user-images.githubusercontent.com/73285776/96862208-200d5680-14a0-11eb-9f75-e4984b2bd09b.PNG)

↑ The layers of the HP bar were reversed. (EmuELEC)

![2](https://user-images.githubusercontent.com/73285776/96862623-b3468c00-14a0-11eb-982e-d8f48502b55d.PNG)

↑ It should be like this originally. (Retro Arena)

**Comment by flyinghead** [comment]
Doesn't seem to happen with latest master. Reopen if the issue persists
