### ISSUE TITLE
Mouse Capture activating with default Mame Controls

### ISSUE THREAD

**Issue by Psypher37** [flyinghead/flycast#1202]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10 / Latest Master build

Github hash: 

Hardware: 

Is there a way to disable Mouse Capture and/or change the hot keys that enable/disable it?

I've built a home arcade setup that using a IPAC Ultimate with Mame & other emulators.  As such, the buttons are programs are setup to match the Mame defaults.

When mapping those arcade controls to Flycast, P1B1 is mapped to Left Ctrl & P1B2 is mapped to Left ALT.

In games like Cannon Spike or Gundam, certain special moves that require both B1 & B2 to be pressed don't work for P1 as a result & instead bring up Mouse-Capture.

**_Debugging Steps Tested_**

Changing the key assignments is possible work around (and does work), but would also require me to change them across other games/emulators which I'd rather avoid.  Is it possible instead to disable mouse capture, or change the trigger buttons for it?

Thanks!

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by Psypher37** [comment]
Thanks!  I was able to test this & it works.

Is it possible to also enable this when RawInput is not enabled too? 

I am using a StreamDeck for admin functions (Add coin, service/test menus, volume adjustment) which stops working once RawInput is off (as it's not recognized as either a Mouse/Keyboard).

**Comment by vkedwardli** [comment]
I'm not quite sure what are you referring to.
With the pull request above, when RawInput is not enabled, you can also use the `Left Alt` and `Left Ctrl` keys together now, without triggering the Mouse Capture.

Are you using the Stream Deck for `Left Alt` / `Left Ctrl` ?

**Comment by Psypher37** [comment]
Hi,

Which build would the changes be included in?  I had tried a test build (I think dated Sept 24th) that disabled mouse capture only in RawInput mode, but still triggered MouseCapture with Left Alt /Left Control when Rawinput was selected.


Just some background on my setup:
Keyboard / IPAC Ultimate (in keyboard mode) & a Streamdeck.

The Streamdeck is setup with hotkeys to simulate keyboard strokes in Mame & Flycast (like "1" for Player 1 Start).    When Rawinput is not on, I believe all the inputs are pooled together, so my Streamdeck works as a keyboard hotkey replacement to add coins, start the game, or any other windows shortcuts.

With RawInput - the Streamdeck is not recognized as a separate HID Keyboard, so I can't use it to map keys, nor are any keypresses of buttons that are mapped to keyboard keys work.

**Comment by vkedwardli** [comment]
Can you try the latest master build from https://flyinghead.github.io/flycast-builds/ ? 

f75a16f | 2023-09-24T14:04:40.000Z

**Comment by Psypher37** [comment]
Thank you, the latest build worked for me.
