### ISSUE TITLE
Trackball / Mouse Input Issue

### ISSUE THREAD

**Issue by oldskool8bit** [flyinghead/flycast#1206]
First off sorry I am VERY new to this so if I did not provide enough details please let me know what else you need and I will get it.

I am trying to get my trackball / KB combo to work on games like Super Monkey Ball in the latest version. I cannot get the emulator to pick up the trackball. I have tried setting it up as a mouse, as a light gun...anything I can think of. Anytime I try to map the X +/- and Y +/- it never picks up the movement. FYI I am only using the Keyboard to load coins, start, and 1 button for character/stage/difficulty settings. The movement should be 100% controlled by the trackball.

**Comment by flyinghead** [comment]
There is no need to map mouse movement, only the mouse buttons can be mapped. The default system mouse should be usable as a trackball for arcade games that use it.
However Monkey Ball uses an analog joystick, not a trackball. So you can't use a mouse or trackball to control it.

**Comment by oldskool8bit** [comment]
> There is no need to map mouse movement, only the mouse buttons can be mapped. The default system mouse should be usable as a trackball for arcade games that use it. However Monkey Ball uses an analog joystick, not a trackball. So you can't use a mouse or trackball to control it.

Wow I did not know this. The original arcade used a trackball so I assumed it would be the same here. I wonder if there is mod/way to map/trick it into thinking your trackball is an analog joystick

**Comment by flyinghead** [comment]
Monkey Ball was actually famous for its banana shaped joystick:
![image](https://github.com/flyinghead/flycast/assets/16261910/ffe8e63b-6364-4b52-838c-4e5563ebbca1)

Super Monkey Ball was a Game Cube game that later got released as an arcade cabinet, with a trackball.
