### ISSUE TITLE
Rayman 2 : The Great Escape - When using per-pixel, the background texture of the prison exit becomes white.

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1209]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: f75a16f

4b0d377: Reproducible
ae2bc81: Can't reproduce
[Rayman 2 - The Great Escape.zip](https://github.com/flyinghead/flycast/files/12737709/Rayman.2.-.The.Great.Escape.zip)

OpenGL, Vulkan, DX11 have no problems with per-triangle and per-strip, but DX9 has problems with both.

Left image: ae2bc81 / Right image: 4b0d377

![Rayman2_3](https://github.com/flyinghead/flycast/assets/14366233/dfd1a7ad-8180-427f-95ab-e48544bb8df7)

**Comment by flyinghead** [comment]
Should be fixed in latest `dev`
