### ISSUE TITLE
Planet Ring - Port forwarding

### ISSUE THREAD

**Issue by RolandTi** [flyinghead/flycast#121]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 x64

Github hash: 

Hardware: Lenovo P52

**_Description of the Issue_**

I can join Planet Ring server, but not the mini-games. I'm seeing "Table is full".
The reason seems to be the "port forwarding".
https://dreamcastlive.net/connection-guide/
Does I need to do port forwarding outside flycast, on my system ? thanks :)

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Yes, you need to forward some ports to the computer running flycast.
Check the link your mention at the bottom of the page:
```Planet Ring: UDP 7648 | UDP 1285 | UDP 1028```

So you need to forward UDP ports 7648, 1285 and 1028

**Comment by RolandTi** [comment]
Thanks !

**Comment by flyinghead** [comment]
assuming this is resolved
