### ISSUE TITLE
Virtua Tennis 2 (Europe)

### ISSUE THREAD

**Issue by blisstik** [flyinghead/flycast#1210]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: f75a16f

Hardware: 

Steam Deck

Add a short, concise description of the issue here

Play an exhibition game, wait for a replay, it slows down during replay

Hello Flyinghead - this may be a regression, I remember the replays no longer having slow motion during replays but it seems to be back. I am not sure which version when it was working properly.

**Comment by flyinghead** [comment]
which rendering API are you using? Does it make a difference with other APIs?

> I am not sure which version when it was working properly.

That's not very helpful

**Comment by blisstik** [comment]
I'm sorry. I'm using RetroArch on SteamDeck if that helps.

**Comment by blisstik** [comment]
Setting overclock to 220 seems to fixed it.
