### ISSUE TITLE
Save/Load State Hotkeys Are Not Exposed Through CLI

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#1212]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Steam Deck/SteamOS

Github hash: N/A

Hardware:  Steam Deck/SteamOS

**_Description of the Issue_**

When running a Flycast ROM through CLI, ex: `flatpak run org.flycast.Flycast /path/to/ROM`, any bound save/load state hotkeys do not seem to work. When I open the Flycast menu in game and look in the controls menu, these hotkeys are absent. 

However, when I open Flycast directly, I can bind the hotkeys and when I open a game from Flycast, the hotkeys do work. 

**_Debugging Steps Tested_**

 * Open Flycast, bind save/load state hotkeys
 * Test save/load state hotkeys when opening a Flycast ROM through the CLI
 * Open the Flycast menu while in game and check if save/load state hotkeys can be bound

**_Logs Gathered_**

N/A

**_Screenshots_**

Launching a game from CLI: 

![image](https://github.com/flyinghead/flycast/assets/108900299/6da6f312-7757-49ff-a65e-a464ed618fe6)

Launching a game from Flycast directly:

![image](https://github.com/flyinghead/flycast/assets/108900299/a2f79700-d793-45d9-bcac-8909d846f151)

**Comment by flyinghead** [comment]
You likely have more than one version of Flycast on your system, one with load/save state hotkey, and one without (it’s a relatively new feature).

Check the version number in the About screen in each case.
