### ISSUE TITLE
Vanishing Point - When playing a replay, the left channel sound becomes choppy

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1215]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: cb91ad3
[Vanishing Point.zip](https://github.com/flyinghead/flycast/files/12790168/Vanishing.Point.zip)

Select defaults for all items and start the game.
Once you pause with the start button, set Music Vol and Ambient Vol to 0 in Sound Settings.

Continue playing the game and play the replay after going around the course twice.
At this time, when I press the top of the direction key to switch to the internal camera, the left channel sound becomes choppy.

Could this be a bug in the game? (It doesn't seem to happen on anything other than the Ford Explorer.)

**Comment by flyinghead** [comment]
I can see the pan setting for channels 0,1,5 and 6 switching from full right to full left and back very quickly. And only when the internal camera is selected.
But I don't know if it's a game bug or an emulation one.

**Comment by kihato** [comment]
I tested it on the real hardware, and the sound did not become choppy.

**Comment by kihato** [comment]
Sorry. I tested again with the real hardware and the sound from the left channel was choppy, just like with flycast.
This seems to be a bug in the game, so I'm closing this issue.
