### ISSUE TITLE
[AMD/GL/Per-Pixel] Weird rectangle artifacts (even at native resolution)

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1216]
I found some weird graphical artefacts in some places, it happens in native with GL and is actually a little better with higher res but still there.

It works perfectly in Vulkan/DX11.

- Music player in bios with some games with audio cover : _Marvel vs. Capcom 2_, _Capcom vs. SNK 2_ - _Street Fighter Zero 3_ has no problem though
![Marvel vs  Capcom 2 - New Age of Heroes (Japan)-231002-223857](https://github.com/flyinghead/flycast/assets/47425204/009fa0ba-0918-4017-b091-79437ca0b20b)
![Marvel vs  Capcom 2 - New Age of Heroes (Japan)-231002-223840](https://github.com/flyinghead/flycast/assets/47425204/31ac4906-34e6-4acb-8ec8-2a96c81b19ff)

- _Street Fighter Zero 3_ - The second Capcom logo (just after pressing start)
![Street Fighter Zero 3 - Saikyo-ryu Dojo for Matching Service (Japan)-231003-121523](https://github.com/flyinghead/flycast/assets/47425204/2f4b429f-17c1-4498-a6ef-b5902ef1e5a6)

**Comment by flyinghead** [comment]
Please indicate Flycast version/git hash.
Is this a regression?
Does it happen with standalone?

**Comment by Immersion95** [comment]
> Please indicate: Flycast version/git hash Which GPU you have
> 
> Is this a regression? Does it happen with standalone?

With latest git https://github.com/flyinghead/flycast/commit/cb91ad3ae0c1291485892bf3a9663a2fd303ce83
AMD GPu - 6800 XT
Here is the RA log 
[retroarch.log](https://github.com/flyinghead/flycast/files/12792149/retroarch.log)

Will test standalone ASAP

**Comment by Immersion95** [comment]
Same with standalone, it's definitely a regression.

The issue is only occuring with Per-pixel, here is a log + another screenshot : 
![Capture d'écran 2023-10-03 140200](https://github.com/flyinghead/flycast/assets/47425204/64c3f679-8058-4bdd-988f-ce719a49e243)
[flycast.log](https://github.com/flyinghead/flycast/files/12792226/flycast.log)

**Comment by flyinghead** [comment]
Do you have `Native Depth Interpolation` enabled?

I can't reproduce the issue with Nvidia.

**Comment by Immersion95** [comment]
> Do you have `Native Depth Interpolation` enabled?
> 
> I can't reproduce the issue with Nvidia.

Native Depth Interpolation On/Off doesn't change anything. Will try to find the latest build that doesn't have this issue.

**Comment by Immersion95** [comment]
> > Do you have `Native Depth Interpolation` enabled?
> > I can't reproduce the issue with Nvidia.
> 
> Native Depth Interpolation On/Off doesn't change anything. Will try to find the latest build that doesn't have this issue.

Tries with older builds from July, dev builds and it's the same. I will try older AMD drivers but I think I'm out of luck :(.

**Comment by flyinghead** [comment]
But July is way before this commit so that can't be it.
Does it also happen with v2.1?
If that's the case it's very likely a driver problem.

**Comment by Immersion95** [comment]
> But July is way before this commit so that can't be it. Does it also happen with v2.1? If that's the case it's very likely a driver problem.

Same thing with older AMD drivers BUT Flycast 2.1 works perfectly ! This is a regression then.

**Comment by flyinghead** [comment]
Unfortunately v2.1 is 8 months old and there's been 386 commits since then...
And I have no clue which one is the cause, let alone find a workaround since I can't reproduce it.

**Comment by Immersion95** [comment]
> Unfortunately v2.1 is 8 months old and there's been 386 commits since then... And I have no clue which one is the cause, let alone find a workaround since I can't reproduce it.

I'll try to find it by building the different commits

**Comment by flyinghead** [comment]
What's the oldest version you tested from the builds page (July?)

**Comment by Immersion95** [comment]
I will download the builds from web.archive, this should be faster. I'll test everything when I get home :)

**Comment by Immersion95** [comment]
What I found :

Master : 
Last known working build : 17ab0ab
Where it starts to bug : ea4354b

Dev : 
Last known working build : 9512ee6
Where it starts to bug : 7cce77c

There were builds between those commits but Wayback Archive doesn't have it

**Comment by flyinghead** [comment]
Based on the dev commits it's likely this one:
https://github.com/flyinghead/flycast/commit/eb3ebe24e8c790b414847bd9e0a313426feea9de

**Comment by PiKeyAr** [comment]
I ran into the same issue with Flycast standalone after switching from nVIDIA to an RX 6800. Only happens in OpenGL, not Vulkan or D3D11. I can confirm that I've never seen anything like this on nVIDIA.
![image](https://github.com/flyinghead/flycast/assets/23312549/e058f92a-9ecd-4dda-a617-d4ae338e6654)
![image](https://github.com/flyinghead/flycast/assets/23312549/42f64f7c-67e5-4e36-959e-ea8ba5213001)

Interestingly enough I get the same artifacts in Demul, which disappear if I disable transparency sorting... I thought the GPU was dying but then I found out there were similar looking aftifacts reported with other games.

**Comment by Immersion95** [comment]
> Based on the dev commits it's likely this one: [eb3ebe2](https://github.com/flyinghead/flycast/commit/eb3ebe24e8c790b414847bd9e0a313426feea9de)
> 
> PS: tu n'as jamais remarqué cette odeur persistente de fromage quand tu démarres flycast? 🧀

Sorry I was totally wrong, I'll get the correct commit that introduced the bug.

**Comment by Immersion95** [comment]
So I found the culprit, it's this commit https://github.com/flyinghead/flycast/commit/9f2ffd102ca0951f59f78d6aed3e9b28ee08f744

Here are the Win64 standalone binaries : 

- Last working build 
[master-34f8941.zip](https://github.com/flyinghead/flycast/files/12835884/master-34f8941.zip)

- First commit that introduce the bug 
[master-9f2ffd1.zip](https://github.com/flyinghead/flycast/files/12835885/master-9f2ffd1.zip)

**Comment by PiKeyAr** [comment]
Tested the two commits and got the same results as @Immersion95. [34f8941](https://github.com/flyinghead/flycast/files/12835884/master-34f8941.zip) works, [9f2ffd1](https://github.com/flyinghead/flycast/files/12835885/master-9f2ffd1.zip) has the issue.

**Comment by flyinghead** [comment]
Interestingly, this commit is removing an optimization (that wasn't working in some cases). Fully transparent pixels were discarded early in the pipeline. This included those bogus pixels at the edge of triangles.
So they were fully transparent when discarded early in the pipeline, but not anymore after being sorted and blended?!?

This looks more and more like a driver bug.

**Comment by PiKeyAr** [comment]
It does sound a lot like a driver bug... Especially considering that it also happens on a different emulator, which uses D3D11, and also only with per-pixel sorting. I would be interested in filing a bug report with AMD but I honestly have no idea how to formulate this so it gets through.

**Comment by flyinghead** [comment]
assuming it's a driver issue

**Comment by Immersion95** [comment]
Works perfectly with latest AMD driver 24.1.1
