### ISSUE TITLE
The loading text that appears after the SEGA logo is not displayed when using OpenGL and Vulkan

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1217]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: cb91ad3

Loading text etc. will not be displayed in the following games. (Only DX9 and DX11 are displayed)

Akihabara Dennougumi - Pata Pies!
Angel Wish - Kimi no Egao ni Chu!
Taisen Net Gimmick - Capcom & Psikyo All Stars
Trizeal
Soldier of Fortune

**Comment by flyinghead** [comment]
should be fixed in the latest master

**Comment by kihato** [comment]
I confirmed that everything is displayed.
Thanks for fixing it.
