### ISSUE TITLE
Analog Axis Gamepad Issues - Raphtech Dreamcast Adapter

### ISSUE THREAD

**Issue by cglmrfreeman** [flyinghead/flycast#122]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
PC / Linux 5.9.1-1 (OpenSUSE Tumbleweed) / AMD Ryzen 7 3800X 8-Core @ 16x 3.9GHz w/GeForce RTX 2060 (NVIDIA not nouveau)

Github hash:
621083c035694542a2faa752198c30fdd442a3dc

Hardware: 
(Redundant?)
**_Description of the Issue_**
After assigning the analog axis with the Dreamcast controller, the analog control will only move UP, UP+LEFT, UP+RIGHT directions. You can not move left, right, or down.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Screenshot_20201030_152119](https://user-images.githubusercontent.com/9744201/97761579-46944880-1ac3-11eb-97a5-2c4ce99a46b5.png)
(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Does it only happens with flycast? No issue with other games/emulators?

Can you try to check what values the analog axes have using a joystick utility?

**Comment by cglmrfreeman** [comment]
I get the following results from the axis in the "Game Controller" setup in System Settings:
![Screenshot_20201102_143620](https://user-images.githubusercontent.com/9744201/97926757-8738cf80-1d18-11eb-9c7d-3ab528adf9e5.png)

Values for 1(x) range from -32767 (left) to 32767 (right) and values for 2(y) range from -32767 (up) and 32767 (down).

**Comment by flyinghead** [comment]
Do you have any of these mapped in the left-hand side (Buttons)?
![image](https://user-images.githubusercontent.com/16261910/97987132-127a9980-1ddb-11eb-81ce-88c6dfb06309.png)

**Comment by cglmrfreeman** [comment]
Nope. I realize posting the full list might be more useful, oops.

![Screenshot_20201103_085656](https://user-images.githubusercontent.com/9744201/98015989-48575800-1db2-11eb-8a5e-f0af478742db.png)

**Comment by cglmrfreeman** [comment]
Compiled and tested latest build as of 62a1e296700a75fdb758662959baa8b8f5e0a642

The issue still persists.

**Comment by flyinghead** [comment]
Sorry it's hard to troubleshoot this issue since I don't own this controller. Have you tried compiling with SDL support? By default flycast evdev on linux. Compile with `make USE_SDL=1` to use SDL instead.

**Comment by cglmrfreeman** [comment]
Recompiled with `make USE_SDL=1` and all analog axis are ignored now in gameplay. Setup is the same as above and did recognize the analog inputs when requested.

**Comment by cglmrfreeman** [comment]
Is there anywhere I can add some code to print axis information to the console during runtime?

Additionally, when running `reicast-joyconfig.py` I can not configure any axis through that script.

**Comment by flyinghead** [comment]
you can compile with `make DEBUGFAST=1`, which will enable logging.
Add this to emu.cfg to control logging:
```
[log]
AICA = no
COMMON = yes
DYNAREC = no
GDROM = no
INPUT = yes
MAPLE = no
MEMORY = no
REIOS = no
RENDERER = no
SH4 = no
VMEM = yes
Verbosity = 5
```
The category you want is INPUT

**Comment by flyinghead** [comment]
Actually there isn't any logging for analog axes, only for buttons. So you might as well add printf's to https://github.com/flyinghead/flycast/blob/master/core/input/gamepad_device.cpp

**Comment by cglmrfreeman** [comment]
After asking for a little assistance from @GerbilSoft to pinpoint where best to place some printf()s, they asked to alter this code section here:
https://github.com/flyinghead/flycast/blob/17274132474e6ef55da7af41f74ee6697329aef7/core/input/gamepad_device.cpp#L244
To remove the if/else and just leave `*this_axis = (s8)v;`

Apparently my radial dead zone was being miscalculated. Omitting this code is obviously just a little hotfix for me for the time being, but I'm able to progress past the first boss fight in Sonic Adventure very smoothly. If there's any variables you'd like me to toss your way which might aide in better deadzone detection let me know.

**Comment by flyinghead** [comment]
So it is a dead zone calculation issue. So two things:

1. There is a way to adjust the dead zone for a given controller by adding these lines to the `.cfg` mapping file:
```
[emulator]
dead_zone = 10
```
The value is a percentage and the default is 10%. If you set it to 0, you effectively disable the dead zone and your controller *should* work without the changes you made.

2. I would be interested in the values of `v`, `*other_axis` and `input_mapper->dead_zone` when the problem happens. It would be nice if you could printf's some of these values. The calculation being trivial, it should reveal which one(s) of these is wrong or has an unexpected value.

**Comment by cglmrfreeman** [comment]
When the analog stick is at an absolute direction of UP/DOWN/LEFT/RIGHT, the value of `v` is 0. `*other_axis` and `input_mapper->dead_zone` also always report 0 no matter which direction.

When at a diagonal angle, it's very hard to report what `v` actually is. For instance, down+left jumps around from 100 to -70 with the slightest touch. The largest values for `v` I am seeing are +/- 122.

**Comment by flyinghead** [comment]
Could you print out the values of `get_axis_min_value(code)` and `get_axis_range(code)` in the `gamepad_axis_input()` function? Thanks

**Comment by cglmrfreeman** [comment]
`get_axis_min_value(code)` yields -32768 while `get_axis_range(code)` yields 65535, which sounds about right because that's exactly what was posted back up in [this comment](https://github.com/flyinghead/flycast/issues/122#issuecomment-720763922).

**Comment by flyinghead** [comment]
Unfortunately I still don't see the root cause of the problem. Is there any way you could printf's the `code` and `value` parameters in `gamepad_axis_input()` ?
I need to see which values are being read from your controller. Depending on the size of the log file, you can post it here or to pastebin.com or equivalent.

**Comment by cglmrfreeman** [comment]
I've created some log files by doing the following: booting into BIOS and simply held as close to an absolute direction as I could for 2-3 seconds. The results seem (at least to me) erratic but I assure you I wasn't going wild with the joystick or anything and only tried to hold in an absolute direction. I hope this helps somehow but I think this just raises more questions.

[up.log](https://github.com/flyinghead/flycast/files/5811575/up.log)
[down.log](https://github.com/flyinghead/flycast/files/5811576/down.log)
[left.log](https://github.com/flyinghead/flycast/files/5811577/left.log)
[right.log](https://github.com/flyinghead/flycast/files/5811579/right.log)

**Comment by flyinghead** [comment]
I extracted the numbers from your logs to simulate your controller on my machine. Here is the result:
[flycast.log](https://github.com/flyinghead/flycast/files/5815760/flycast.log)

Conclusion: I don't see any issue. Both axes go roughly full range: from -123 to 120. When one axis is at max deflection, the other isn't at zero but within 10% of it, which is expected for gamepads. Also, I don't see how the dead zone calculation would affect these numbers when the joystick isn't near its center. I left it at the default 10% here.

**Comment by cglmrfreeman** [comment]
Strange update: I was going to try to make a video showing the strange axis issue, the one where I can only go UP or UP+DIAGONAL, but now the joystick input refuses to work. Even if I add the `dead_zone = 0` to emu.cfg.

The joystick now _only_ works with that code in the if/else condition I mentioned before is removed.

**Comment by cglmrfreeman** [comment]
So I decided to create a new clone of flycast in a different directory because things just weren't adding up...

I also renamed my /.config/reicast/ folder to /.config/reicast-old/

APPARENTLY, when launching Flycast again for the first time, it created a /.config/flycast/ directory, since I guess there was no reicast directory.

_This solved all directional issues_.

NOW, however, I've just realized that the left and right triggers do not work, so there is still, but a different, axis issue now...

**Comment by cglmrfreeman** [comment]
Researching this further, it looks like flycast is now building with an SDL default? And I found out why the analog axis was not working [here](https://github.com/flyinghead/flycast/issues/122#issuecomment-754987302), it is because the `SDL_raphnet technologies Dreamcast to USB.cfg` generated had this code:
```
[emulator]
dead_zone = 100
mapping_name = Default
```
Why it would generate with a `dead_zone` of 100 is beyond me but it did.

Now, compiling with `USE_EVDEV=1`... does nothing... it still says "SDL" under "System".

Going to checkout commit 621083c035694542a2faa752198c30fdd442a3dc and try again, as that's where the problem first started (when I first started using the program) for me.

Hmmm... I can't seem to get flycast to use evdev anymore.... and _that is where the issue lies_. In any case, here is my evdev config for the controller.
[evdev_raphnet technologies Dreamcast to USB.cfg.txt](https://github.com/flyinghead/flycast/files/5827100/evdev_raphnet.technologies.Dreamcast.to.USB.cfg.txt)

If I can get evdev to work with flycast again I will let you know if it does that weird deadzone thing.

**Comment by flyinghead** [comment]
SDL still isn't the default on linux. This hasn't changed. Make sure to `make clean` when changing Makefile parameters such as USE_SDL or USE_EVDEV.

Looking at the code I don't see how it could end up with a dead zone of 100. It defaults to 10% (0.1) and the only way to change is by editing the mapping .cfg file. If you have a reproducible scenario for this bug, let me know.

Also there shouldn't be any significant difference between using SDL vs evdev (SDL being a front-end for evdev on linux). Again let me know if you find otherwise.

**Comment by cglmrfreeman** [comment]
>SDL still isn't the default on linux. This hasn't changed. Make sure to `make clean` when changing Makefile parameters such as USE_SDL or USE_EVDEV.

Typically I am just deleting the build folder and remaking it using `cmake ..` but I also did a `make clean` after that and still, no. It refuses to use EVDEV. I don't understand what has changed.

**Comment by cglmrfreeman** [comment]
As reicast is now an archived repo, and I haven't been able to reproduce this issue ever again since, I'm closing this.
