### ISSUE TITLE
[Bug/All platform/All renderer] Upscaling problems with Capcom & SNK games (only on higher resolution)

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1223]
Follow up from the issue in the old repo https://github.com/libretro/flycast/issues/818

After 3 years, I finally was able to build cores myself in order to find the culprit.

Culprit ---> https://github.com/libretro/flycast/commit/a2137ce23b71b3d13857a770a6f13e6e68158850

https://github.com/libretro/flycast/commit/bc5be5e69510376a5a24bfef19fce3286b0921aa [Last working build.zip](https://github.com/flyinghead/flycast/files/12823274/Last.working.build.zip)

**Examples :**
Chun-Li's standing pose in CVS 1/PRO at 1280x960 (integer multiple of 640x480, you'll see stripes on non-integer multiple)

**Correct Chun-Li :**
https://github.com/flyinghead/flycast/assets/47425204/046de5a6-140d-43d7-bd16-d79cc686b4fa

**Warped Chun-Li (today's latest core) - Her shoulder is increasing and decreasing :**
https://github.com/flyinghead/flycast/assets/47425204/38d775d4-851e-4069-8301-e3c1b2316f44

This only happens on Capcom characters (thus no SNK characters are affected) in CVS because their sprites comes from the CPS2 with a strange ratio, it also happens on all characters from MVC2.

Why is upscaling important for these 2D games ?

1. Sprites from CPS2 have a weird resolution of 384×224 (4/3 non pixel perfect) which doesn't translate well with the Naomi resolution of 640x480 (pixel-perfect 4/3), thus they are horrible at native with pixels from hell
2. MVC2 has 3D stages
3. CVS has 3D elements in the UI

**Comment by flyinghead** [comment]
This is a very minor glitch and you have several workarounds: don't upscale or upscale by an integer multiple.

The commit you mention helps avoiding some of these issues, which are by far more severe and affect many games:
![image](https://github.com/flyinghead/flycast/assets/16261910/3d007e5f-de76-4f06-a7e5-69722dca9678)

**Comment by Immersion95** [comment]
> This is a very minor glitch and you have several workarounds: don't upscale or upscale by an integer multiple.
> 
> The commit you mention helps avoiding some of these issues, which are by far more severe and affect many games: ![image](https://user-images.githubusercontent.com/16261910/273130831-3d007e5f-de76-4f06-a7e5-69722dca9678.png)

Sorry I wasn't clear enough.

Upscaling by integer doesn't solve it at all, it's not warping at native and that's it but the game is ugly at native unfortunately.

Integer multiple only helps with stripes but the warping is always there after this commit.

Thanks anyway.

**Comment by Immersion95** [comment]
I built a core without the bleeding edge fix and the games are perfect in 4K.

I gave a custom name to that core and will play those specific games like that.

I know that it's not urgent at all but would you consider adding a option like that ?

- Fix Upscale Bleeding Edge = ON (default option)

I would thus be able to disable it for those specific games.

Merci beaucoup pour ton temps :).

**Comment by crashGG** [comment]
<img width="263" alt="1_cr" src="https://github.com/flyinghead/flycast/assets/80488411/bc09bfd8-4274-4025-93c0-86c78c5f7fc9">
<img width="310" alt="2_cr" src="https://github.com/flyinghead/flycast/assets/80488411/5c8c73da-d58a-4c42-a6bb-6e3b6bc1fe5f">
<img width="227" alt="3_cr" src="https://github.com/flyinghead/flycast/assets/80488411/4e01357e-fa32-460d-a98c-3375b0020224">
<img width="191" alt="4_cr" src="https://github.com/flyinghead/flycast/assets/80488411/426b60bc-4c96-48ef-acde-9282ac69c88c">
Same image issue, using 1280x960 internal rendering resolution (2x integer upscaling), game：mvsc2 + wild screen hack。
I also tried the repair build on the first floor, and the issue was alleviated, but it did not disappear completely.

**Comment by Immersion95** [comment]
> <img alt="1_cr" width="263" src="https://user-images.githubusercontent.com/80488411/274244521-bc09bfd8-4274-4025-93c0-86c78c5f7fc9.png"> <img alt="2_cr" width="310" src="https://user-images.githubusercontent.com/80488411/274244539-5c8c73da-d58a-4c42-a6bb-6e3b6bc1fe5f.png"> <img alt="3_cr" width="227" src="https://user-images.githubusercontent.com/80488411/274244562-4e01357e-fa32-460d-a98c-3375b0020224.png"> <img alt="4_cr" width="191" src="https://user-images.githubusercontent.com/80488411/274244582-426b60bc-4c96-48ef-acde-9282ac69c88c.png">
> 
> Same image issue, using 1280x960 internal rendering resolution (2x integer upscaling), game：mvsc2 + wild screen hack。 I also tried the repair build on the first floor, and the issue was alleviated, but it did not disappear completely.

Please try my build here https://github.com/Immersion95/flycast/actions/runs/6443085776

Disable Widescreen hack

You can also try higher resolution

I don't have any glitch like you with widescreen disabled.

**Comment by riggles1** [comment]
Just tested your build, it works!!!
Finally! Using it with CRTEmudriver (2560 super res with 4x internal rendering), libretro core version for easy CRT output, looks absolutely breathtaking to have the horizontal so clean. Tried both 480p and a forced custom 224p (makes the scanlines match character sprites exactly, slight bit of vertical filtering through a shader to make high res elements cleaner).

There's so much detail now! Thank you, please have it merged into main!

**Comment by Immersion95** [comment]
> Just tested your build, it works!!! Finally! Using it with CRTEmudriver (2560 super res with 4x internal rendering), libretro core version for easy CRT output, looks absolutely breathtaking to have the horizontal so clean. Tried both 480p and a forced custom 224p (makes the scanlines match character sprites exactly, slight bit of vertical filtering through a shader to make high res elements cleaner).
> 
> There's so much detail now! Thank you, please have it merged into main!

Thanks ! Don't forget to change the texture filtering to Nearest when you upscale.

**Comment by crashGG** [comment]
Thank you for the buid you provided. If you didn't have the **Sharingan**,  might not be able to detect the subtle pixel jitter of the sprites.Since most of the images in cvs1 are at the native resolution, I think the only game that is really affected is mvsc2. Before flycast merged , this game had been set to this dedicated lib core.Now I'm trying to see if cvs2 is also affected.

**Comment by Immersion95** [comment]
@flyinghead : Hi, I would like to add this option in the settings myself.

While I'm searching, would it be possible to give me a rough summary on how to do it ? If you can't, I will try to find a way, thanks anyway !

**Comment by blueminder** [comment]
You can add it as an option in `core/cfg/option.cpp` and `core/cfg/option.h`. Something like this:

option.h:
`extern Option<bool> FixUpscaleBleedingEdge;`

option.cpp:
Option<bool> ShowFPS("rend.FixUpscaleBleedingEdge", true);

From there, you can wrap your code changes in a conditional like `if (config::FixUpscaleBleedingEdge)`.

From there, the option will be shown in your `emu.cfg` file, and you can adjust it there. If you want to add it to the Settings UI, head to `core/rend/gui.cpp` and add the option in the `gui_display_settings()` function.

**Comment by yudhiyou** [comment]
I don't know man. I have tried to turn off that upscale bleeding edge option on MVC2 game in 1080p resolution but the sprite is still broken when the character moving.
