### ISSUE TITLE
[Tony Hawk's Pro Skater] Visual Artifacts on Sides of Screen with Widescreen on

### ISSUE THREAD

**Issue by ZT-1** [flyinghead/flycast#1225]
Platform / OS / Hardware: Windows 10

Github hash: 18f9b84

Hardware: i7-11700k / rtx 3070 ti

There is visual artifacting on the sides of the screen in outdoor locations when widescreen is enabled.
https://streamable.com/i9v8cq

**Comment by flyinghead** [comment]
Yes, this is expected with widescreen. It actually gives pretty good results with this game.
