### ISSUE TITLE
[Feature Request] VRR / FreeSync / G-Sync in standalone

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1226]
With my AMD 6800 XT on Win 11, VRR/Freesync isn't supported on standalone. It's working perfectly in RetroArch though.

I need to disable VRR/Freesync and enable Vsync for it to be smooth but this introduces input lag. Switching renderer doesn't change anything.

Is there a setting that I missed ? Does it work with Intel/Nvidia ?

In RA --> The VRR overlay shows 59-60fps
In standalone --> The VRR overlay shows 80-120 fps

**Comment by flyinghead** [comment]
Flycast uses external VSync as a source of synchronization, so it's not surprising that it doesn't like VRR. The audio output is the only other source of synchronization but having both enabled is recommended.

All dreamcast/naomi/atomiswave games (and hardware) are designed to run with a 60 Hz monitor (50 Hz for PAL games) so VRR is useless for Flycast.
