### ISSUE TITLE
The image on the game selection screen is not displayed correctly

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1231]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 4e079b5

Assume that there is no cover art registered in the boxart directory.
If you check Fetch Box Art and register a game (for example, Crazy Taxi), the acquired cover image will be displayed on the game selection screen.
Next, uncheck Fetch Box Art, delete the Crazy Taxi you just registered, and then register a new, different game (for example, Crazy Taxi 2).
Then, the disc image of Crazy Taxi, which is not currently registered, will be displayed on the game selection screen.

This is completely unrelated, but if you close flycast in full screen mode, the next time you start it up and change it to window mode, the flycast icon in the top left will no longer be displayed.

**Comment by kihato** [comment]
As you said, if you restart flycast, the ROM list will be updated and there will be no problem.
What I assumed was the case without restarting flycast.

(boxart directory and ContentPath are empty)
After you get the Box Art of Crazy Taxi (MK-51035) from the database, it will be displayed in the ROM list.
![CrazyTaxi](https://github.com/flyinghead/flycast/assets/14366233/c456b88c-8bdb-45ba-9736-3e0097c02353)

After disabling Fetch Box Art, remove Crazy Taxi (MK-51035) from the ROM list and add Crazy Taxi 2 (MK-51136).
(Don't restart the flycast after this.)
Crazy Taxi (MK-51035) no longer exists in the ROM list, but 0GDTEX.PVR of Crazy Taxi (MK-51035) is displayed.
![CrazyTaxi2](https://github.com/flyinghead/flycast/assets/14366233/915069fc-ecff-4f0e-bbf2-beecceaf6b71)

Of course, if you restart flycast, it will be displayed correctly.
![CrazyTaxi2_2](https://github.com/flyinghead/flycast/assets/14366233/1b264a62-3fad-4e62-80ec-0551289da11d)

Thanks for looking into window icons. This is my first time hearing about this.

**Comment by flyinghead** [comment]
Should be fixed in the latest master build

**Comment by kihato** [comment]
It is now displayed correctly. Thanks as always.

**Comment by legolas119** [comment]
hi, i have just configured Flycast. But there are 3 games (Gunlord, Neo XyX and fast striker) with missign boxart. I could add them adding the png file into the boxart folder, but i don't know which is the number i have to use to rename the .png file of the missing box...
can you help me please? thank you
