### ISSUE TITLE
Flycast with upside down image

### ISSUE THREAD

**Issue by spielvan** [flyinghead/flycast#1233]
@flyinghead Flycast with image upside down, I'm using it on retroarch1.16.0 android 5.1.1, in the latest flycast colors the image is upside down, using an older flycast core the image is normal, so I imagine it's a bug caused in the latest core versions.

**Comment by flyinghead** [comment]
Should be fixed in the next core update

**Comment by spielvan** [comment]
> Should be fixed in the next core update

I updated the core here and it was perfect, thank you very much bro.
