### ISSUE TITLE
RPI3 - Receiving: Error creating sdl gl context

### ISSUE THREAD

**Issue by m33ts4k0z** [flyinghead/flycast#1235]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Raspberry Pi OS Bullseye 64bit -> Raspberry Pi 3 Model B+

Github hash: 
[4e079b5](https://github.com/flyinghead/flycast/commit/4e079b5d0bf9e4335d4153be42d531f99e80dea8)

**_Description of the Issue_**
Using the latest Raspberry Pi OS Bullseye 64bit, and the Experimental KMS driver, I am unable to run flycast from the command line or from the desktop environment. 
Using the legacy driver does look like the emulator is running but I only see the log and listen to the game's audio while I see no video.
The thing is that I need to use the experimental driver since I'm trying to add the standalone Flycast to Retropie's EmulationStation and it looks like ES is only starting with the experimental driver.
I have tried with both the flatpak version of Flycast as well as I compiled the hash above myself.

**_Logs Gathered_**
Error creating sdl gl context
Error initiliazing the graphics API

**Comment by flyinghead** [comment]
How do you build Flycast? What are the cmake options?

This error is due to SDL not being able to create the OpenGL context. Are you using the host SDL lib or building and linking with the one with Flycast?

**Comment by flyinghead** [comment]
You shouldn't have to modify CMakeList.txt. Simply run:
`cmake -DUSE_HOST_SDL=ON -DUSE_GLES2=ON -DUSE_VULKAN=OFF (...)`

**Comment by m33ts4k0z** [comment]
Ok so I did try to compile it but I receive this now:

```
[100%] Linking CXX executable flycast
/usr/bin/ld: cannot find -lbrcmGLESv2
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/flycast.dir/build.make:4100: flycast] Error 1
make[1]: *** [CMakeFiles/Makefile2:308: CMakeFiles/flycast.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
I know that this library no longer exists in bullseye for Raspberry Pi OS. I read on Rpi forums that we can use `-lGLESv2` instead? 
Is that the same? or?

**Comment by flyinghead** [comment]
Adding `-DUSE_VIDEOCORE=OFF` to cmake should do the trick. It's off by default but you might have enabled it in an earlier build attempt.

**Comment by m33ts4k0z** [comment]
> Adding `-DUSE_VIDEOCORE=OFF` to cmake should do the trick. It's off by default but you might have enabled it in an earlier build attempt.

Thank you I will try that. I noticed something else now actually. The emulator fires up pretty fast but when trying to load metal slug 6, it looks like it gets stuck in the "notice all backup data was cleared" for about 10-15 minutes, then it moves on and the game is quite playble for the rest of it. 

This happens with the standalone but the retroarch core works fine. 

I have removed the envm files (are they called that? :D ) from the directory but the issue is still the same.

I can actually start the game using SSH and capture the log to send it to you if you need to have a look at it.

**Comment by flyinghead** [comment]
This message is normally only displayed once, when starting the game for the first time and initializing eeprom and flash memory. However it should take less than a minute.
Does the delay also happen with subsequent runs?

**Comment by m33ts4k0z** [comment]
yes the delay is actually huge now. 

Its very hard to explain what is happening but it doesn't look like there are eny errors in the logs.

I see the Sammy logo and then the screen goes gray and the delay starts. I have a lot of the same message repeating in the console:

```
00:59:377 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:377 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
00:59:378 hw/sh4/sh4_mmr.cpp:393 D[SH4]: read TMU_TCNT0
```

**Comment by flyinghead** [comment]
Wow! You're running a debug version with full logging.
`cmake -DCMAKE_BUILD_TYPE=Release` would help (although it's the default afaik)

**Comment by m33ts4k0z** [comment]
Well that was embarassing. I remembered now that I was messing with the CMakeLists.txt yesterday and I enabled both debug as well as the VIDEOCORE... I am recompiling now but I am quite certain that disabling these 2 has already solved my issues. Thanks a lot for your patience 😁
