### ISSUE TITLE
Caesars Palace 2000 - Transparent sorting doesn't work

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1236]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: abd9219
cc1b45b: reproducible
4d99094: Cannot reproduce

Left image: 4d99094 / Right image: cc1b45b
![Caesars_3](https://github.com/flyinghead/flycast/assets/14366233/ea629f81-caeb-419b-89e4-93ecc71e2dc7)

**Comment by flyinghead** [comment]
should be fixed in the next master build

**Comment by kihato** [comment]
Confirmed. Thanks for your hard work.
