### ISSUE TITLE
Add a option for overclocking the GPU...

### ISSUE THREAD

**Issue by RetroGamingX** [flyinghead/flycast#1238]
I have noticed that for some time the emulator has had the option to overclock the CPU, but testing some WinCE games there is no speed improvement, it is probably related to a GPU frequency issue. It would be great if someone implemented this function.

**Comment by flyinghead** [comment]
Some games benefit from overclocking but it depends how the game is designed. 30 FPS games will still render at 30 FPS but variable rate games may render faster.

Anyway the GPU isn't timed the way the CPU is so it really can't be under/overclocked.
