### ISSUE TITLE
Vulkan not working on standalone on Armbian/Orange pi 5 plus

### ISSUE THREAD

**Issue by m33ts4k0z** [flyinghead/flycast#1241]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Armbian 23.8.2 Bookworm (CLI)
Flycast standalone compiled from source
Weston desktop (Wayland)

Github hash: 
[2f52492](https://github.com/flyinghead/flycast/commit/2f524923da85be1eb77f25ca92c0bcfa43537494)

Hardware: 
Orange Pi 5 Plus 16GB / Mali G610 

**_Description of the Issue_**

There is an error about invalid access when trying to switch to the vulkan renderer in Weston (Wayland) desktop environment using the standalone flycast that I compiled.

I also compiled the libretro lib from the same hash and that works with vulkan in Weston through Retroarch, although very slow rendering.

**_Screenshots_**

![vulkan_error](https://i.imgur.com/WUlzODi.jpg)

**Comment by m33ts4k0z** [comment]
Hello.

Sure here comes the verbose logging. I just change the vulkan option through the GUI menu without trying to load a game. Just a note, I use the mesa-vulkan-drivers package for the vulkan drivers.

```
00:00:731 sdl/sdl.cpp:625 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:740 wsi/sdl.cpp:90 I[RENDERER]: Created SDL Window and GL Context successfully
00:00:741 wsi/gl_context.cpp:39 I[RENDERER]: OpenGL version: 4.5 (Core Profile) Mesa 22.3.6
00:00:742 rend/gui.cpp:297 N[RENDERER]: Screen DPI is 91, size 640 x 480. Scaling by 1.00
00:00:742 oslib/storage.cpp:187 I[COMMON]: Cannot stat file './/gamecontrollerdb.txt' errno 2
00:01:189 rend/gles/gles.cpp:576 N[RENDERER]: OpenGL version 4.5
00:01:235 rend/boxart/boxart.cpp:178 D[COMMON]: Loading boxart database from /home/retropie/.local/share/flycast//boxart/flycast-gamedb.json
00:07:244 rend/TexCache.h:820 I[RENDERER]: Texture cache cleared
00:07:342 sdl/sdl.cpp:625 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:07:354 rend/vulkan/vulkan_context.cpp:238 N[RENDERER]: Vulkan API 1.1. Device llvmpipe (LLVM 15.0.6, 128 bits)
00:07:354 rend/vulkan/vulkan_context.cpp:260 N[RENDERER]: eR4G4B4A4UnormPack16 not supported for optimal tiling
00:07:354 rend/vulkan/vulkan_context.cpp:382 D[RENDERER]: Using Graphics+Present queue family
00:07:364 rend/vulkan/vulkan_context.cpp:566 D[RENDERER]: Supported surface format: B8G8R8A8Srgb
00:07:364 rend/vulkan/vulkan_context.cpp:566 D[RENDERER]: Supported surface format: B8G8R8A8Unorm
00:07:364 rend/vulkan/vulkan_context.cpp:582 D[RENDERER]: Surface capabilities: -1 x -1, Identity, image count: 4 - 0
00:07:364 rend/vulkan/vulkan_context.h:264 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:07:365 rend/vulkan/vmallocator.cpp:34 D[RENDERER]: VMAAllocator: 33554432 bytes allocated (type 0)
00:07:368 rend/vulkan/vulkan_context.cpp:724 I[RENDERER]: Vulkan swap chain created: 640 x 480, swap chain size 4
00:07:368 rend/vulkan/vulkan_renderer.cpp:30 N[RENDERER]: VulkanRenderer::Init
00:07:492 linux/common.cpp:69 E[COMMON]: SIGSEGV @ 0xaaaac2706c24 invalid access to 0xf8
```

**Comment by flyinghead** [comment]
can you run flycast in gdb?
```
gdb ./flycast
run
```
then try switching to vulkan and it should break into gdb:
```
bt
```

**Comment by m33ts4k0z** [comment]
So here is the result:

![flycast_debug_gdb_result](https://i.imgur.com/cIiyZRu.jpg)

**Comment by flyinghead** [comment]
As expected it's crashing in some system library (libdecor-0.so).
It is possible that switching from OpenGL to Vulkan is the problem.
Try editing emu.cfg and change the following line to select Vulkan (0 is OpenGL, 4 is Vulkan):
```
[config]
pvr.rend = 4
```
Then start Flycast.

**Comment by m33ts4k0z** [comment]
That actually worked to start flycast with vulkan but when trying to load a Naomi 2 game ( club kart / clubkrt.zip ) it is very slow and when I am actually about to get into a race, flycast crashes with a similar error:

![vulkan_error1](https://i.imgur.com/f9M9e78.jpg)

And running with the debugger (I had to kill it because nothing was happening after initially loading the rom's files):

![vulkan_error2](https://i.imgur.com/jflO9gK.jpg)

The same game runs perfectly fine with OpenGL.

**Comment by flyinghead** [comment]
You are running a debug version of Flycast with full logging enabled, so it's not surprising that it's slow.
Compile with `cmake -DCMAKE_BUILD_TYPE=Release` (or `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo` if you need to debug)

**Comment by m33ts4k0z** [comment]
Sorry I wasn't very clear. 

I said on my initial post that the libretro core runs with vulkan but slowly. That wasn't compiled with debug. I forgot to add to that even the core crashes exactly before loading the ingame graphics and leaving the menu.

Now, when starting the GUI with vulkan and getting into the same game, I experience the exact same slow speed and the game crashing again at the very same spot. 

I will recompile without debug and come to you but let me know if you need any more traces to look into this. Thanks for the help :)

**Comment by flyinghead** [comment]
Well, it looks like the vulkan driver is slow and buggy in this platform. There isn't much I can do.

**Comment by flyinghead** [comment]
Using different drivers could help, like proprietary Mali ones. But I'm not familiar with this platform.

**Comment by m33ts4k0z** [comment]
Thanks for your help. I know the drivers got released recently and are beta but I will try to find the non-free ones and try flycast again 😊
