### ISSUE TITLE
When using DX9, the screen will no longer update due to certain operations

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1243]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 2f52492

![Trick](https://github.com/flyinghead/flycast/assets/14366233/10e272a7-b613-4e74-8b87-961fa741c57f)

Start Trickstyle in windowed mode.

When you see the text following the Sega logo on the screen, pause the flycast and then immediately press F11 to go full screen.
If all goes well, you should be able to reproduce it.

You can also perform the reverse procedure (The image above is the result of switching from full screen to windowed).

**Comment by flyinghead** [comment]
should be fixed in the next master build

**Comment by kihato** [comment]
It works fine. Thanks a lot!
