### ISSUE TITLE
The Grinch - Personal Notebook graphics in pause menu glitches when using DX11 and per-pixel combination

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1244]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 2f52492

![Grinch_5](https://github.com/flyinghead/flycast/assets/14366233/d4fe77b0-9a60-4ad4-b578-5b97af7ee903)

I also encountered another strange situation.

When I try to save to a VMU with 0 remaining capacity, it becomes unresponsive,
No matter what button I press, no messages appear and no progress is made.
[vmu_save_A1.zip](https://github.com/flyinghead/flycast/files/12883382/vmu_save_A1.zip)

Additional Information:
When you remove the VMU in slot A1, a message is displayed, and when you insert a new VMU, you can save it.
It seems to be a bug in the game. (Forgot to add a message?)

**Comment by flyinghead** [comment]
should be fixed in the next master build

**Comment by kihato** [comment]
Thanks for fixing it.
