### ISSUE TITLE
Still having problems with Z-fighting on AMD

### ISSUE THREAD

**Issue by usagiDamaci** [flyinghead/flycast#1245]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 7 Ultimate x64
ATI Radeon 3000 Graphics (Integrated :') )
AMD Sempron 140 Processor, 2.70 GHz
6 GB RAM

Github hash:  [2f52492](https://github.com/flyinghead/flycast/commit/2f52492)

**_Description of the Issue_**

Games run smoothly, but I still have the Z-fighting issue related to AMD cards. I've tried my games in Redream and there are no graphic issues at all.

**_Debugging Steps Tested_**

  * Enabled and disabled Native Depth Interpolation, which doesn't seem to work in my case. (Graphics appear to look the same, or only a few polygons seem to get 'fixed' with the option enabled.)
  * Changed all graphic settings and noticed no differences, other than in performance.
  * Switching to OpenGL (looks exactly the same) and to DX9 (displays nothing at all, only a black screen).
  * Tested different games:
         **1.** Monkey Ball (Naomi) seems to display correctly.
         **2.** Shenmue 1 shows the typical glitches around Ryo's eyes + the notepad being half brown at the bottom.
         **3.** Seaman shows many of the same glitches, especially outside the pond, around Seaman's eyes and the seam(an) of his head.
         **4.** Sonic Adventure used to have the same issues with the character's eyes, back in October 2021 (first time using the emulator, and I don't have the game anymore, so I can't test it again currently).

**_Logs Gathered_**

Latest log, simply running Shenmue's intro for a minute or so before closing the emulator.
```

01:03:010 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
01:03:019 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 000007ffdf710000 RAM(16 MB) 000007ffeb710000 VRAM64(8 MB) 000007ffe3710000 ARAM(2 MB) 000007ffff710000
01:03:035 emulator.cpp:54 N[BOOT]: Game ID is [MK-5105950]
01:03:038 emulator.cpp:54 N[BOOT]: Game ID is [MK-5105950]
02:25:813 rend/dx11/dx11_renderer.cpp:175 N[RENDERER]: DX11 renderer terminating
02:25:818 rend/dx11/dx11context.cpp:208 N[RENDERER]: DX11 Context terminating
02:25:819 rend/dx11/dx11_shaders.cpp:694 N[RENDERER]: Saved 137 shaders to D:\***********

```

**_Screenshots_**

Since Shenmue's glitches are the usual ones, I'm attaching some Seaman screenshots.
![seaman1](https://github.com/flyinghead/flycast/assets/10482896/e4aeb1e6-30c6-4d11-937d-ddd9f64436bf)
![seaman3](https://github.com/flyinghead/flycast/assets/10482896/d09785aa-c96c-4c82-bcad-98231ce6ba6f)

**Comment by flyinghead** [comment]
Enable Per Pixel Transparent Sorting in Settings > Video

**Comment by flyinghead** [comment]
That's because your graphic card doesn't support the features needed for accurate per pixel transparent sorting.
What you're seeing isn't z-fighting but transparent polygon sorting issues, which happens with approximations such as per triangle or per strip sorting.
