### ISSUE TITLE
Failed to load content with libretro core

### ISSUE THREAD

**Issue by Shatur** [flyinghead/flycast#1248]
Platform / OS / Hardware: RetroArch / PinePhone Pro / ArchLinux.

Github hash: 4e079b5d0bf9e4335d4153be42d531f99e80dea8 (lastest version from the repository)

Hardware: RK3399

**_Description of the Issue_**

When I launch any game RetroArch says "Failed to load content". If I use standalone emulator all my games works. Also libretro core of the same version works on my PC amd64. Bios files in place on all my machines. So I assume that there could be a RetroArch and Arm-specific issue.

**_Debugging Steps Tested_**

1. Run any game in RetroArch and using flycast core

**_Logs Gathered_**

`retroarch --verbose &> log.txt`: [log.txt](https://github.com/flyinghead/flycast/files/12909548/log.txt)

**Comment by flyinghead** [comment]
This seems to be the cause of the failure:
```
[ERROR] Requesting OpenGL context, but RetroArch is compiled against OpenGLES. Cannot use HW context.
```
The Flycast core is compiled to use OpenGL, whereas RA is compiled against OpenGLES.

The Flycast core should probably be recompiled to use OpenGLES on this platform.

**Comment by Shatur** [comment]
Oh, so it could be a distro problem. Let me try to compile it myself.

**Comment by Shatur** [comment]
What flag should I use to build against OpenGLES?

**Comment by flyinghead** [comment]
`cmake -DUSE_GLES=ON -DLIBRETRO=ON`

**Comment by Shatur** [comment]
Solved the issue, thank you a lot!
