### ISSUE TITLE
NBA Showtime: NBA on NBC - BGM cuts out after start

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1249]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: e96b38f

After pressing Start on the title screen, if you do nothing for a while on the option selection screen or team selection screen, the BGM may be interrupted or temporarily become inaudible.
Strangely enough, if I move the cursor periodically, the background music repeats normally.

**Comment by kihato** [comment]
When I looked into the code, it seems that disabling the channel with AEG's EG_Release causes a bug in the BGM.
I don't know if it affects other games, but at least in this game, if you comment out `ch->disable()` here, the BGM will play normally.

**Comment by kihato** [comment]
Further testing yielded good results in the following games.
As for "Ready 2 Rumble Boxing", it's better than before, but the audio sometimes seems to disappear.

Ready 2 Rumble Boxing: #1030
Confidential Mission: #472
The Maze of the Kings: #483
Spikers Battle: #1180

**Comment by flyinghead** [comment]
Great find! It looks like this fixes a number of audio issues.
Should be fixed in the  latest dev build.

**Comment by kihato** [comment]
I forgot to close this issue. Thanks!
