### ISSUE TITLE
Sakura Taisen1(Dream Cast)：The background collapses in the event movie after defeating the final boss

### ISSUE THREAD

**Issue by nemimi2194** [flyinghead/flycast#1252]
Hello. I'm Japanese and I'm not good at English, so I'm using Google Translate to post.

Platform / OS / Hardware: 
RetroArch/windows11/RTX4080 i9-13900kf
fly cast version:1.16.0(e94b26f)

In the final episode of the DC version of Sakura Wars 1, the background collapses in the event scene after defeating the boss.
BIOS version:Dream Cast version1.004（Japan）

![disc-231019-181324](https://github.com/flyinghead/flycast/assets/148392391/7981f610-0cdd-426d-b9c3-11b31c5e2e07)

State save data and memory card data for the relevant scene
[savedata.zip](https://github.com/flyinghead/flycast/files/13040567/savedata.zip)

**Comment by flyinghead** [comment]
You need to enable `Video > Render to Texture > Copy to VRAM` for this game.
I will make it automatic in future versions.

**Comment by nemimi2194** [comment]
Thank you.
It's fixed.
