### ISSUE TITLE
Cleopatra Fortune - Fatal: SH4 exception when blocked

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1253]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: e94b26f
e894d4d: Can be reproduced.
c58ae4d: Unable to reproduce.

This seems to occur with a combination of DX11 and per-pixel.

Delete the data directory.
Start the game and choose a mystery.
Select "From opening".
Press the A button repeatedly to advance through the scene until you reach the puzzle screen.
End the game by clicking Exit in the flycast pause menu.
Launch the game again on the game selection screen.

![Error_1](https://github.com/flyinghead/flycast/assets/14366233/b3ce60fb-8826-474d-a57e-1639729bd0e7)

It may also freeze.
![Error_2](https://github.com/flyinghead/flycast/assets/14366233/213e250e-91ce-4921-a3fe-525584fc9963)

In addition, other games have also experienced stuttering or slow BGM.

**Comment by flyinghead** [comment]
Should be fixed in the latest master.

**Comment by kihato** [comment]
No more crashes or freezes.
Thanks for your hard work.
The issue of background music stuttering and lagging can still be reproduced.
I will close this issue and open a new one.
