### ISSUE TITLE
Tag version 2.2?

### ISSUE THREAD

**Issue by xiota** [flyinghead/flycast#1254]
Version 2.1 was tagged eight months ago.  Wondering when 2.2 is planned.  Thanks.

**Comment by cinnamonmatexfce** [comment]
> Version 2.1 was tagged eight months ago.  Wondering when 2.2 is planned.  Thanks.

Any particular reason why you need the next `X` release? You can download binaries on the builds page.
Or you can even compile by yourself from `master` if you know how to do it.

**Comment by xiota** [comment]
I have no problem obtaining recent builds.  It's just nice to have releases be regular and reasonably recent. There have been 420 commits since the release , so there should have been sufficient change to warrant a release.

**Comment by flyinghead** [comment]
The best way to make releases happen more often is to help by testing recent builds and reporting issues.
