### ISSUE TITLE
Sakrura Taisen2：In a picture scene, a square shadow appears where the character's eyes and mouth move.

### ISSUE THREAD

**Issue by nemimi2194** [flyinghead/flycast#1256]
Hello. I'm Japanese and I'm not good at English, so I'm using Google Translate to post.
In a picture scene, a square shadow appears where the character's eyes and mouth move.

Platform / OS / Hardware:
RetroArch/windows11/RTX4080 i9-13900kf
fly cast core version:35b7be3
BIOS version:Dream Cast version1.004（Japan）

I tried starting directly from Flycast without using Retroarch, but the same symptoms occurred.

**_Screenshots_**

(Replace this line with any issue screenshots)
![disc-231022-150300](https://github.com/flyinghead/flycast/assets/148392391/a25b5800-9fbe-4d24-8734-462b1d774a9f)

State save data and memory card data for the relevant scene
[sakura2_save.zip](https://github.com/flyinghead/flycast/files/13062479/sakura2_save.zip)

**Comment by flyinghead** [comment]
Should be fixed in the latest master build

**Comment by nemimi2194** [comment]
Thank you very much for your quick fix!
