### ISSUE TITLE
Flag to Flag - The screen does not update after the race starts

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1257]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 35c71eb
e96b38f: Can be reproduced.
e894d4d: Cannot reproduce.

This happens when using a combination of DX11 and per-pixel or DX9 and per-strip.
Select arcade and start racing.
After a while after rolling start, it should switch to the driver's perspective, but this does not happen and the screen stops updating.

**Comment by flyinghead** [comment]
should be fixed in the next master build

**Comment by kihato** [comment]
Confirmed. Other games affected by this issue have also been fixed. Thanks a lot!
