### ISSUE TITLE
[Vulkan] Wayland and KMS/DRM support?

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#1258]
**Is your feature request related to a problem? Please describe.**
I have just built standalone Flycast on GNU/Linux after configuring the sources with:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_VULKAN=ON -DUSE_OPENGL=OFF`

I disabled OPENGL in order to avoid legacy OpenGL linkage (GLX) which is not on my systems anymore.

The problem is that, upon running Flycast, I get:
```
00:00:058 rend/gui.cpp:3166 E[COMMON]: Fatal error : Cannot initialize the graphics API
 in initRenderApi -> /root/src/libretro/flycast/core/wsi/switcher.cpp : 90
```
This happens on both Wayland and KMS/DRM.
Looking at the code, it seems the Wayland or KMS/DRM(AKA KHR_Display) WSI code is missing or I can't find it.

So, as far as I understand, Vulkan on GNU/Linux is only supported on the old X11 graphics server.

**Describe the solution you'd like**

Would it be possible to have the missing Wayland and KMS/DRM WSI support incorporated, so Flycast standalone can operate on modern GNU/Linux desktops, please?

**Describe alternatives you've considered**
Building Flycast as a libretro core works around this, but that has it's own problems. 

**Additional context**
KMS/DRM Vulkan context would be desired for lightweight systems.

**Comment by flyinghead** [comment]
The default renderer is OpenGL on linux and there's no fallback from OpenGL to Vulkan if OpenGL isn't compiled in or fails.
Edit emu.cfg to set it to Vulkan (`[config] pvr.rend = 4`)
or change the default renderer type to Vulkan in core/cfg/option.h:416

**Comment by vanfanel** [comment]
Ah, thanks!
Where can I find all the available options for emu.cfg, please?

**Comment by vanfanel** [comment]
Ah, forget it, it seems a complete emu.conf is created after first run. Perfect!
