### ISSUE TITLE
Soul Calibur Fatal Exception - RetroArch

### ISSUE THREAD

**Issue by KongsNutz** [flyinghead/flycast#1259]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Core using RetroArch
Github hash: 

Hardware: 
Shield TV, PC
**_Description of the Issue_**

When skipping opening battle animations, Fatal MH4 Exception when Blocked

**_Debugging Steps Tested_**

  Tested Shield TV using nightlys Vulkan
  Tested PC RetroArch Win11 Vulkan

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Please provide some more details as I'm unable to reproduce the issue:
- Flycast core version / github hash
- Core options
- Screenshot or description of when to skip, button used, etc.

**Comment by KongsNutz** [comment]
Core ver - (0.1 4a913e0)
Core Options - 
• Detect framerate
• 1280*960 Resolution
• Per Strip/Pixel doesn't seem to matter
• Vulkan

Description - 
Sometime before finishing arcade mode using Sophitia (not sure if anyone else only trying to do her line first) in-between a match if pressing A repeatedly to skip the animations it will crash with the Fatal SH4 Exception.

Using Android Shield TV and less frequently on PC, both RetroArch.

**Comment by flyinghead** [comment]
0.1 4a913e0 is from the defunct libretro/flycast fork and is 2 years old.
Please upgrade to the latest version.

**Comment by KongsNutz** [comment]
Here the thing though, I just told it to update the core and it gives the same version number.

**Comment by KongsNutz** [comment]
Update:
Manually updated the core to e55d70c on the Shield TV (tube) and am no longer getting the error.  
  
Sophitias armour arm rests start glitching after a few battles but that maybe just the game itself but I'm able to complete story mode.

**Comment by KongsNutz** [comment]
So using the core above I'm now getting some random gfx issues. Characters legs flickering, and some gfx bugs in general like the image.

![20231024_083152](https://github.com/flyinghead/flycast/assets/32734141/138dcd03-81dd-4f02-862e-38a47048aaf3)

**Comment by flyinghead** [comment]
This looks similar to #556

**Comment by flyinghead** [comment]
Should be fixed in the latest master build.

**Comment by KongsNutz** [comment]
Can confirm it is now fixed in both RetroArch and Stand alone. Awesome job.

**Comment by KongsNutz** [comment]
Can confirm it is now fixed, good stuff.
