### ISSUE TITLE
Glitches in the menu -  Intel HD Graphics

### ISSUE THREAD

**Issue by DiktatorShadaloo** [flyinghead/flycast#126]
Platform / OS / Hardware:  
 Windows 7 Ultimate 64-bits (6.1 version 7601)

Github hash: 

Hardware: 
 Lenovo m92p tiny
 Intel Core i5-3740T 2.90Ghz
 8GB RAM
 Intel HD Graphics
  
Description of the Issue:

I tried CVS2 and the game runs good but I found some glitches in the menu that they don't let me map the inputs and configure  other things. 

**_Debugging Steps Tested_**

  * I tried to change some video options
  * I tried to run as administrator, compatibility mode and disable aero.

**_Screenshots_**

![image](https://user-images.githubusercontent.com/42413627/98975003-5153d200-24f4-11eb-8920-5176c747c759.png)

Nothing is visible in the "general" tab.
![image](https://user-images.githubusercontent.com/42413627/98975038-616bb180-24f4-11eb-9aaa-f2412cd54a77.png)

By clicking blindly I changed the tab
![image](https://user-images.githubusercontent.com/42413627/98975076-6df00a00-24f4-11eb-9eb2-c909b45f1f38.png)

 this happen when you try to map the inputs
![image](https://user-images.githubusercontent.com/42413627/98975094-75171800-24f4-11eb-8a38-8251d1234689.png)

**Comment by flyinghead** [comment]
This looks like a GPU driver issue. Are you running the latest version of the Intel HD drivers?
I've already had issues with Intel drivers.

Have you tried Vulkan (if supported)?

**Comment by DiktatorShadaloo** [comment]
With the latest version of the Intel HD drivers for some reason it doesnt open. It doesnt support Vulkan, I tried it but it closes instantly.

**Comment by flyinghead** [comment]
Which version of the Intel driver are you running?

**Comment by DiktatorShadaloo** [comment]
This [one](https://downloadcenter.intel.com/en/download/24970/Intel-Graphics-Driver-para-Windows-15-28-?product=80939) In theory the compatible one  with my cpu was this one [one](https://downloadcenter.intel.com/en/download/29969/Intel-Graphics-Driver-for-Windows-15-33-?v=t) but for some reason the screen delays on refresh and flycast opens and closes instantly.
