### ISSUE TITLE
[Vulkan] [Daytona USA 2001] Cars have missing surfaces

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#1260]
Platform / OS / Hardware:  X86_64 GNU/Linux, Debian 12

Github hash: e55d70c0e6bc09a0ee6d7b8cae3136bb66af537c

Hardware: I5 1235U with Intel XE graphics, latest MESA GitLab code.

**_Description of the Issue_**

Cars in Daytona USA 2001 have missing surfaces as they rotate in the car select menu or in-game.

**_Debugging Steps Tested_**

I have tried the different **Transparent Sorting** modes available.
The picture below is taken with the default **Per Triangle**.
With **Per Strip** even more parts are missing, and with **Per Pixel** there are car no surfaces missing but there are other artifacts on the tracks (hard to take a picture, they happen very fast).
 
**_Screenshots_**
![daytonaaaa](https://github.com/flyinghead/flycast/assets/837585/89849211-2ab9-456a-842a-c99514d51fd4)

**Comment by flyinghead** [comment]
Per-pixel is required for proper rendering in this game.
The artifacts you are seeing in per pixel are due to your GPU driver or GPU.

**Comment by vanfanel** [comment]
Ok, then is it a good practice to leave Per-pixel set by default? I mean, if CPU&GPU don't complain, seems to fix at least Daytona 2001 and REZ (which is my perfect game, a colossal piece of digital art like no other).

Or are there games that will fail or have artifacts with Per-Pixel?

**Comment by vanfanel** [comment]
Well, on Daytona, other than some very sporadic flickering on the grass texture of the left part of the screen, and some flickering trees almost out of view on the left too, I see no other problems with Per-pixel.
Maybe the game has those small glitches on original hardware too? I don't have a DC at hand to test, sadly.

**Comment by vanfanel** [comment]
@flyinghead I noticed something VERY interesting: Activating "Native Depth Interpolation" fixes the small glitches introduced on the tracks by "Per-Pixel".

Does it make any sense? Is "Native Depth Interpolation" also more demanding? (I understand it should be less demanding if it uses the native depth interpolation of the GPU, but maybe I am wrong on this).

**Comment by flyinghead** [comment]
Yes, sorry about that. "Native Depth Interpolation" is required for AMD but it also helps Intel GPUs with some games. And Daytona USA is one of them.
It has no impact on performance.

**Comment by vanfanel** [comment]
Thanks a lot! Now I perfectly understand and everything is fine on my hardware.
