### ISSUE TITLE
OpenGL per-pixel graphical glitches

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1262]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: e55d70c

Any combination other than OpenGL per-pixel will be displayed correctly.

Images on the left: (OpenGL per-pixel) / Images on the right: (DX11 per-pixel)					

![Alone_3](https://github.com/flyinghead/flycast/assets/14366233/6e3cc4d8-30c5-45cb-a4c8-bbdd19521f8b)
![Demolition_2](https://github.com/flyinghead/flycast/assets/14366233/32d0f0c1-87cc-4053-a596-f63bf97d10ad)
![ECW_2](https://github.com/flyinghead/flycast/assets/14366233/e985a187-102c-4707-9209-8f23b0eecdf1)
![LE_MAN_2](https://github.com/flyinghead/flycast/assets/14366233/1fcbfbd3-47d8-4446-981a-8d3dc219c3fd)

**Comment by flyinghead** [comment]
Should be fixed in the latest master build.
Hopefully no regressions were introduced.

**Comment by kihato** [comment]
I confirmed that it is displayed.
Thanks for your prompt fix.
