### ISSUE TITLE
[Sonic Adventure(NTSC/USA)] Audio is heavily distorted during action level.

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#1264]
**Platform / OS / Hardware:** X86_64 GNU/Linux, Debian 12

**Github hash:** https://github.com/flyinghead/flycast/commit/e55d70c0e6bc09a0ee6d7b8cae3136bb66af537c

**Hardware:** I5 1235U with Intel XE graphics, latest MESA GitLab code.

**Description of the Issue**

Audio in Sonic Adventure (NTSC/USA) is heavily distorted on the first level.
Until that point (intros, animations..) everything seems fine.

**Debugging Steps Tested**

I have tried enabling and disabling DSP emulation, but that makes no difference.

**Screenshots**

Since this is an audio issue, I recorded a small video of it:

https://github.com/flyinghead/flycast/assets/837585/fab6516f-0226-4a40-8489-6805c3838a91

**Comment by flyinghead** [comment]
Confirmed and it is a consequence of dac5b991e07150880f685e5ed167cda5e8994039

**Comment by flyinghead** [comment]
Should be fixed in the latest master build.

**Comment by vanfanel** [comment]
@flyinghead Yes! Works perfectly now, no more distorted audio! Thanks!!
