### ISSUE TITLE
Whether forced "copy to VRAM" is required

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1265]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 8fb3def

Enabling "Copy to VRAM" in the following games will resolve the graphical glitches, but I'm not sure if it's the right way to do it.

Images on the left (Enable "Copy to VRAM") / Images on the right (Disable "Copy to VRAM")

**AIR** ([AIR.zip](https://github.com/flyinghead/flycast/files/13183830/AIR.zip))
(APPENDIX -> CG viewing mode -> Select one of the character names -> Back)
![AIR_3](https://github.com/flyinghead/flycast/assets/14366233/e963ee9a-1010-4b1e-892b-6f71f33b1357)

**Aikagi** ([Aikagi.zip](https://github.com/flyinghead/flycast/files/13184002/Aikagi.zip))
(Load the second file from the top)
![Aikagi_3](https://github.com/flyinghead/flycast/assets/14366233/41fe298b-3477-452d-b34d-dcad386cfb8b)

**Kanon** ([Kanon.zip](https://github.com/flyinghead/flycast/files/13184025/Kanon.zip))

![Kanon_3](https://github.com/flyinghead/flycast/assets/14366233/055ef196-dd00-4e27-9a69-3601d70b76f4)

**Hundred Swords**
![Hundred_3](https://github.com/flyinghead/flycast/assets/14366233/6a6f6e62-041a-488d-b393-b243196bc764)

**Musapey no Choco Marker**
![Musapy_3](https://github.com/flyinghead/flycast/assets/14366233/d472b3da-2022-4b0a-b362-1675c5a8e7c9)

**Sister PrincessS Premium Edition**
![Sister_3](https://github.com/flyinghead/flycast/assets/14366233/7783a323-8bcd-48b9-8c1f-1833a881d9f3)

**Sentimental Graffiti 2** ([Sentimental Graffiti 2(Disc1).zip](https://github.com/flyinghead/flycast/files/13183847/Sentimental.Graffiti.2.Disc1.zip))
(Previous image is displayed when switching screens)

https://github.com/flyinghead/flycast/assets/14366233/5515b2cf-7061-4c1b-9519-77926de5690a

**Sentimental Graffiti - Yakusoku**
![Senti_yakuyoku_3](https://github.com/flyinghead/flycast/assets/14366233/39461cf5-c894-481a-a4dc-60606e26a6b9)

**Worms World Party**
![WWP_3](https://github.com/flyinghead/flycast/assets/14366233/6ecb2cee-10cb-4bab-a9f7-a20d456a481d)

**Comment by flyinghead** [comment]
So yes, all of these games need Copy to VRAM enabled, for various reasons.
Interestingly the Naomi Choco Marker also needs it for the same reason as the console version.
Worms World Party already forces the setting but only for the EU version (I forgot the US one.)
In most cases it is due to missing texture updates (RTT textures can't be updated.)
Hundred Swords renders its font atlas at the beginning of the game but use smaller portions of it afterwards.

Should be fixed in the latest master build.

**Comment by kihato** [comment]
It's working fine. Thanks!

**Comment by kihato** [comment]
Cool Boarders Burrrn (The US and PAL versions do not have this issue.)

Since only costume selection is required, this may not be necessary.

![CoolBordersBurrrn00](https://github.com/flyinghead/flycast/assets/14366233/190062d6-b400-401f-aeef-9728d61a6837)

Castle Fantsia - Seima Taisen (Missing button texture.)

![CastleFantasia00](https://github.com/flyinghead/flycast/assets/14366233/b726d969-557d-4a09-a491-b3cbfa2d57c9)

**Comment by flyinghead** [comment]
Copy to VRAM forced for Cool Boarders Burrrn and Castle Fantasia  in the latest `dev` build

**Comment by kihato** [comment]
Thanks! I confirmed that it has been fixed.
