### ISSUE TITLE
Forcing Full Framebuffer Emulation

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1266]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: c1f0a5a

The following games cannot be played unless Full Framebuffer Emulation is enabled.

Eisei Meijin III
Marionette Company
World Neverland Plus - Olerud Kingdom Story

**Comment by flyinghead** [comment]
Should be fixed in latest master

**Comment by kihato** [comment]
Thanks for fixing it.
Only Marionette Company has a little problem.
There is no problem with Vulkan, but with OpenGL, DX11, and DX9, if you pause and cancel the flycast, the text disappears.
So it seems better to disable multi-threaded emulation.

**Comment by flyinghead** [comment]
I believe the text blinking after pausing/unpausing is due to #1079

**Comment by kihato** [comment]
Ah, I see, it's the same. I finally understood. Thanks!
