### ISSUE TITLE
Test Drive Le Mans - broken background music

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1267]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: c1f0a5a
c7d214e: Can be reproduced.
8cdd171: Unable to reproduce.

Quick Race -> Go Race
Once the race has started, wait patiently until the lap time has passed for about 5 minutes without moving the car at all.
I don't know when it will happen.

https://github.com/flyinghead/flycast/assets/14366233/9cedaa2a-1bef-4838-90c1-a0895b03cc05

**Comment by KongsNutz** [comment]
Can confirm on latest Android and Xbox builds also

**Comment by flyinghead** [comment]
Should be fixed in latest master

**Comment by kihato** [comment]
No more audio freezes. Thanks a lot!
