### ISSUE TITLE
Virus detected in release version 2.2

### ISSUE THREAD

**Issue by possom2009** [flyinghead/flycast#1269]
Virustotal detects a virus in the release version but not in the buildbot version of the same comit.

2.2 release version comit (c1f0a5a)
https://www.virustotal.com/gui/file/0918261b650d8ae1ffc308e6aca0d8d0f639f418ddceea89dc65a092a905f550

Buildbot dev version comit (same comit number)
https://www.virustotal.com/gui/file/728ed83558fff3ab97f370dc1a44d1dc38776adc3ce37b005dca622576185434/detection

**Comment by flyinghead** [comment]
Likely a false positive since only one vendor flagged it

**Comment by possom2009** [comment]
> Likely a false positive since only one vendor flagged it

That's what I figured. Aren't they the same file? I'm just confused as to why they give different results.

Also, I forgot to mention it's the Android version.

**Comment by flyinghead** [comment]
They aren't from the same build but should very similar.

**Comment by possom2009** [comment]
Strange, now Virustotal detects a virus in the previously stated buildbot version. Any idea what would be causing it to be dected?

I know it's a false positive, just trying to figure out why it's being flagged in the first place.

**Comment by flyinghead** [comment]
I don't know exactly how these tools detect threats. I guess it's not pubic information but I would assume it's a deterministic process for a given file.
I suppose they are detecting a byte pattern somewhere in the binary that matches a known threat. There's nothing I can do about it (unless it's a real threat/virus/trojan of course).

**Comment by vkedwardli** [comment]
From my experience, usually the Windows Defender is generated false positive for MSVC builds, and I would need to submit a false positive report to M$.

[We can do that also for Trend Micro](https://success.trendmicro.com/dcx/s/solution/1119869-reporting-a-false-positive-issue-in-deep-security?language=en_US&sfdcIFrameOrigin=null), but I would love to see if such false positive indeed block any users before taking the time to communicating with them.

**Comment by possom2009** [comment]
It's A false positive. Closing the issue.
