### ISSUE TITLE
Headhunter - The video and sound in the OP are not synchronized

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1272]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: c1f0a5a

new game -> Skip training mission

You can see that the pitch of the BGM at the beginning of the video is abnormally low and that the sound of the gun firing is out of sync.
Sometimes it plays correctly, but I haven't found a reliable way to do it.

https://github.com/flyinghead/flycast/assets/14366233/5ce0e848-ba4c-4bdd-8a9a-ff3c3f64cb5c

**Comment by flyinghead** [comment]
The game is slowing down the pitch of the soundtrack (OCT -1 FNS 314) when it starts playing, then increases it back to normal (OCT 0 FNS 0). After that it seems to constantly adjust the pitch but with smaller values.
So the issue seems to be on the SH4 side.

**Comment by kihato** [comment]
Surprisingly, this issue seems to have been fixed now.
I looked into it and found that it was fixed in a7702c6.
I didn't notice because it's different from the other examples.
So I'm going to close this issue.
