### ISSUE TITLE
Dead or Alive 2 Europe/USA Inputs not working correctly, story mode timer starts at 00

### ISSUE THREAD

**Issue by cosmocanyon** [flyinghead/flycast#1275]
Platform / OS / Hardware:  Linux

Github hash: c1f0a5a15

Hardware: x86/64 GTX 1660

Any button input in training mode comes out as block.
Story mode timer starts at 00s instead of 90s with instant lose.

To reproduce problem it's necessary both Dead or Alive 2 PAL and Dead or Alive 2 USA.

How I reproduced the problem:
Delete all save game files created in the flycast folder.
Start DOA2 USA or PAL.
Create save game.
Play (training mode).
Exit.
Load DOA2 PAL or USA
Create save game.
Play (training mode).
Each button is block.
Return main menù.
Start story mode.
Timer at 00.

In the options controller the buttons pressed are correctly recognized, only in game is always blocking.

The same issue is also reproduced with the games ordered the other way around.

I tried with DOA 2 Japan Shokai Genteiban and works without any issue together the other two versions.

**Comment by flyinghead** [comment]
This looks like a game bug.
Does it happen if you use different VMUs for the EU and US editions?
(Enable Per-game VMU A1 so that each game has its own A1 VMU)

**Comment by cosmocanyon** [comment]
I enabled the option and indeed both issues disappeared.
Thanks!
