### ISSUE TITLE
Stupid Invaders disk change failure in dynarec.

### ISSUE THREAD

**Issue by Neckilljo** [flyinghead/flycast#1277]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: PC Windows, Ryzen 5 / RTX 3070

Github hash: 

Hardware: 

** Stupid Invaders disk change failure **

This game is fully playable with dynarec, but at some point in the game, you are required to switch disks. If you do this while using dynarec engine, Flycast crashes. You have to change CPU Mode to Interpreter before loading disk 2.

I just came here to report it. If someone encounters the same problem as I did, follow these steps: eject disk 1, switch to the Interpreter, load disk 2, and when Candy appears flying on an inflatable couch, switch back to dynarec.

**_Debugging Steps Tested_** - None

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_** - none available

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Can your upload a savestate before the disk switch is required?
That would help me reproduce the bug.

**Comment by Neckilljo** [comment]
[Stupid Invaders v1.001 (2001)(Ubi Soft)(NTSC)(US)(Disc 1 of 2)[!].gdi_vmu_save_A1.bin.zip](https://github.com/flyinghead/flycast/files/13244965/Stupid.Invaders.v1.001.2001.Ubi.Soft.NTSC.US.Disc.1.of.2.gdi_vmu_save_A1.bin.zip)

Sure, this vmu has 3 of them.

**Comment by flyinghead** [comment]
What version of flycast are you using?
I just tested the disk switching with the latest master build and it didn't crash.

PS: thanks for the vmu!
