### ISSUE TITLE
Unable to switch to full screen mode...[Git - 2020/11/20]

### ISSUE THREAD

**Issue by D-Marshman** [flyinghead/flycast#128]
Platform / OS / Hardware: 
Linux: Ubuntu 20.10, kernel 5.9.8       ASRock B550M Pro 4 / Ryzen 5 5600X / Radeon RX 5700 XT

Github hash: 
47f262a2

**_Description of the Issue_**
Unable to switch to full screen mode...

Pressing "Alt"+"Enter" does not work.

Starting with cli argument "-config window:fullscreen=yes" does not work.

Doesn't work at main menu, or in-game.
Tried multiple games:
Confidential Mission
Daytona USA
Sega Rally 2

**Comment by flyinghead** [comment]
For historical reasons, on linux, the cli argument should be:
`-config x11:fullscreen=yes`

**Comment by D-Marshman** [comment]
> For historical reasons, on linux, the cli argument should be:
> `-config x11:fullscreen=yes`

Thanks.  That worked.

I'm still not able to toggle between windowed and full-screen.  Is "Alt + Enter" supposed to do that, or is there no way?

**Comment by flyinghead** [comment]
There's a hardcoded binding on `F11` to toggle fullscreen on/off.

**Comment by D-Marshman** [comment]
> There's a hardcoded binding on `F11` to toggle fullscreen on/off.

That's great.  Thanks again.  
And apologies if that was documented and I missed it.. I searched but didn't find anything...

**Comment by flyinghead** [comment]
I don't think it's documented and it's obviously inconsistent between platforms...
