### ISSUE TITLE
Ducati World Racing Challenge - Temporary graphic glitch

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1280]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 3e047a6

The bike temporarily disappears along with the rider, and the line on the right side becomes wavy.

https://github.com/flyinghead/flycast/assets/14366233/641bb17d-8c7a-4963-af03-b467f8772802

**Comment by flyinghead** [comment]
The wavy right side of the track is clearly visible on real hardware. The disappearing rider is more rare but also happens.
See https://www.youtube.com/watch?v=PLlssHoVOSo
(disappearing rider at 6:04)

Given the poor quality of this game it's likely to have even more game bugs.

**Comment by kihato** [comment]
Thanks for providing the reference video link.
I didn't even know it was a game like this.
