### ISSUE TITLE
"Giant Knuckle" skill in Evolution 2 renders as pure white

### ISSUE THREAD

**Issue by banana3333** [flyinghead/flycast#1284]
Platform / OS / Hardware: 
Powkiddy X28 / Android 11 / T618 (same SoC as Retroid Pocket 3+/Flip, Anbernic 505/405M, etc)

**_Description of the Issue_**

"Giant Knuckle" skill in Evolution 2 renders as pure white. It's supposed to just look like a giant robo arm.

**_Debugging Steps Tested_**

I've tried changing a bunch of the video settings, updating to the latest version of standalone Flycast (v2.2), and rebooting both the app and the device itself.

**_Screenshots_**

![Screenshot_20231102-154957](https://github.com/flyinghead/flycast/assets/66152283/245fada8-b318-4d75-8b82-232e534735c9)
![Screenshot_20231102-154949](https://github.com/flyinghead/flycast/assets/66152283/90642529-9038-4d91-b765-f98523259834)

**Comment by flyinghead** [comment]
Can you post a savestate?

**Comment by banana3333** [comment]
> Can you post a savestate?

[Evolution 2 - Far Off Promise v1.000 (2000)(Ubi Soft)(NTSC)(US)[!]_4.state.zip](https://github.com/flyinghead/flycast/files/13260715/Evolution.2.-.Far.Off.Promise.v1.000.2000.Ubi.Soft.NTSC.US._4.state.zip)

It should bring you right to a battle where you're already highlighting the move in question.

**Comment by flyinghead** [comment]
Thanks for the savestate. This is very helpful.
Now I wonder if the rendering is wrong and how. Clearly it's awfully saturated but I can't find a video of this on original hardware.
I found this but it's on gamecube and possibly on an emulator too: https://www.youtube.com/watch?v=TpqVM0EJuDk&t=108s 
It looks better but not that great.

**Comment by banana3333** [comment]
I found a clip of the move being used in the DC version here and tried to ask the uploader if he was playing on emulator or not (timestamp in the comment). 

https://www.youtube.com/watch?v=zfAVFLAmK3c

Seems I got ignored, but you're insinuation could be right. That might legitimately just be how it looks in the game on real hardware, possibly a dev oversight or something. I remember the move looking totally fine in the first game, so a bit of a bummer if so.

**Comment by flyinghead** [comment]
Yes, I saw these videos and it doesn't look like it's running on original hardware. Here is the Evolution 1 Giant Knuckle effect from the same youtuber: https://youtu.be/8_WHLMCAvvI?si=ntJKZxeKq3VDzjnF&t=565

I've done extensive checks of the rendering pipeline in Flycast and I can't find anything wrong with it. So it could be how it's intended to look, or the problem lies deeper within the game when it's generating these vertices color.

**Comment by kihato** [comment]
I tested it on the real hardware, and the color of the fist was almost white. It's far from the GameCube version mentioned above.

**Comment by flyinghead** [comment]
Thanks for testing. Closing since it's working as it should.
