### ISSUE TITLE
[AMD, Vulkan] Street Fighter Double Impact glitches

### ISSUE THREAD

**Issue by StillPlay2** [flyinghead/flycast#1286]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10

Github hash: 1253e1199

Hardware: AMD Ryzen 7 5800X

**_Description of the Issue_**

When starting the game, the Capcom logo & intro is glitched as seen in the screenshots below. This happens on the Vulkan Renderer. I am using Native resolution with everything at default settings. It is a GDi build of the game aswell.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Screenshot (44)](https://github.com/flyinghead/flycast/assets/116039192/5a1f0d46-721f-4ab3-84b0-c0dcff50db0b)
![Screenshot (45)](https://github.com/flyinghead/flycast/assets/116039192/cde319a0-e05e-4c48-8252-70e2f96aa5aa)

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
I'm not reproducing any of these issues here (GTX 1080, linux).
Does it happen with other graphics APIs (DX11, OpenGL) ?

**Comment by flyinghead** [comment]
It might be an issue with your current AMD Vulkan driver. For now, I suggest you use DX11 for this game at least.

**Comment by Immersion95** [comment]
7800 XT/Win 11 here and it's working great, what's ur card and driver ?

**Comment by TheCoolPup** [comment]
same here, used my amd graphics card and vulkan, game is fine

**Comment by flyinghead** [comment]
assuming it's a driver issue
