### ISSUE TITLE
Discord Rich Presence support 

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1289]
I know discord has demul as a registered game, but im thinking maybe its possible for flycast to have that feature as well?

**Comment by flyinghead** [comment]
That would be a question for Discord. What does it take to be a "registered game"?

**Comment by TheCoolPup** [comment]
I could look into the info and let you know if i find info

**Comment by TheCoolPup** [comment]
So in terms of registered games, on my end you can add them to your library so discord can “detect” it, but im wondering if is possible for like on your profile to show what game you are playing, for example on Yuzu and OpenGOAL, it shows what game you are playing, etc.

**Comment by vanfanel** [comment]
May I ask that this is an option at build time? I would like to avoid Discord as much as possible.

**Comment by flyinghead** [comment]
Discord Presence support in the latest dev build
