### ISSUE TITLE
flycast android not load iso. Help me please!!!

### ISSUE THREAD

**Issue by tee4341** [flyinghead/flycast#129]
flycast android not load iso. Help me please!!!

can load  cd format ,.gdi,.bin.  not load iso format

**Comment by flyinghead** [comment]
flycast supports .CDI, .GDI, .CHD and .CUE only.

What "ISO" are you trying to load?

**Comment by tee4341** [comment]
me download from website in format .7z extract to iso.......T_T

**Comment by flyinghead** [comment]
Assuming the problem is solved. Reopen as needed.
