### ISSUE TITLE
Texture replacement swapping multiple textures for the one

### ISSUE THREAD

**Issue by Danhanado** [flyinghead/flycast#1291]
Platform / OS / Hardware: 
Windows 10

**_Description of the Issue_**

Some texture replacement files will overwrite multiple different textures. In my case a piece of a logo will replace the correct texture but will also replace a random button prompt texture

**_Debugging Steps Tested_**
Using the Texture Dump feature I get the textures I want to replace, however the texture with the issue doesn't initially get dumped like the others, it has to appear multiple different times before it actually gets dumped, where the others get dumped as soon as they appear.
Same goes with the texture that's not meant to be replaced, the original button texture doesn't actually get dumped along with the others.
When the texture I want replaced eventually gets dumped, I copy the file name and paste it into my replacement texture.
[Texture i want replaced](https://github.com/flyinghead/flycast/assets/48228176/914e9e6c-754d-41ef-a1ea-646c0143388e) 
[Texture I want it replaced with](https://github.com/flyinghead/flycast/assets/48228176/d475bbee-add9-4f11-ac9c-39971adf706d)

I also noticed that while textures are being dumped, textures different from the one I want replaced will have the same filename (fd753ee5.png) before eventually being replaced by the logo texture I want to replace
[Different texture, same file name](https://github.com/flyinghead/flycast/assets/48228176/44fcc136-0744-430d-add7-36f48e211c03)

 

**_Screenshots_**
Random button texture replaced
![Random button texture replaced](https://github.com/flyinghead/flycast/assets/48228176/1a6b1891-508c-4f36-85b1-f33c10b6fc73)
Correct logo texture replaced
![Correct logo texture replaced](https://github.com/flyinghead/flycast/assets/48228176/57e64aa5-37ec-4517-b2fa-1f431247ba72)

**Comment by flyinghead** [comment]
This is due to a bug in hash calculation for textures of a certain type, that wasn't fixed to preserve backward-compatibility with older texture packs. Unfortunately this bug makes several textures to have the same hash in this case.

I fixed it on the `dev` branch (hopefully still backward compatible) so it shouldn't happen anymore. Let me know if you still have duplicate hashes. Note that many textures will now have a different hash if dumped with the latest dev build.

**Comment by flyinghead** [comment]
Actually I just found another issue that could affect texture hashes so give me some more time to figure it out.

**Comment by flyinghead** [comment]
All should be fixed now. There should no longer be duplicate hashes.
