### ISSUE TITLE
add support to the Sega Dreamcast's Arcade Stick that is used for fighting games

### ISSUE THREAD

**Issue by Thetouchedjoe** [flyinghead/flycast#1296]
yeah, im want to adding support to other controllers like the Sega Dreamcast's Arcade Stick that used for fighting games
![s-l1200](https://github.com/flyinghead/flycast/assets/147065598/993d2d98-16ca-41f4-adda-4440745e9458)

yeah thats the like for the fighting stick, idk for this but yeah that controller is useful to some fighting games such as =
- Marvel vs Capcom 2
- Capcom vs SNK 2 
and everything about fighting games

its like for the Android versions and others should use arcade stick so the feel of the play is like in the arcade and also it can also use for button mashing stuffs

see this issue! and dont forget the remind me

**Comment by flyinghead** [comment]
It's already supported and it's called Ascii Stick in Flycast.

I agree the name is somewhat confusing since it refers to the ASCII Pad FT, which has the same button layout as the Dreamcast Arcade stick.

**Comment by Thetouchedjoe** [comment]
Ok, thank you very much flying head, idk that ASCII Stick is same as the
Dreamcast's arcade stick! :)
- little thanks for reminding me

**Comment by vkedwardli** [comment]
should we change to `Arcade Stick / ASCII Pad`? (skipped the FT for saving some space)

**Comment by flyinghead** [comment]
yes, I already changed it to `Arcade Stick` on my side. I might leave Ascii Stick as this is what the device identifies as.

**Comment by Thetouchedjoe** [comment]
Ok, thanks.
