### ISSUE TITLE
Shifted image only with Skies of arcadia Pal

### ISSUE THREAD

**Issue by Julinkk** [flyinghead/flycast#1298]
I tested many versions of flycast in development and there is always a problem with image shifting upwards. A hint, when I change the resolution of flycast the image moves, only with this game. It doesn't do this on any other games and no problem on version 2.1. You can see the problem on the screenshots I took and on a screenshot of the flycast tests.

![Capture d’écran (315)](https://github.com/flyinghead/flycast/assets/84175698/d711ba4d-42db-41b4-ab8b-1d4675d1d0e9)
![Capture d’écran (316)](https://github.com/flyinghead/flycast/assets/84175698/b43f7d60-60fa-4c1e-bb00-650820940563)
![Capture d’écran (317)](https://github.com/flyinghead/flycast/assets/84175698/b6622c79-27b9-46c5-ad15-5fd60f8bb6b9)

**Comment by flyinghead** [comment]
This is a consequence of supporting Video output shifting, which is a new feature in v2.2. See #594 for more information.

The PAL version of this game shifts the screen down by 8 pixels and doesn't draw on the full height of the screen.

**Comment by Julinkk** [comment]
Ok thank you, I read the topic but I don't see a solution?  Putting it in composite mode fixes the problem?

**Comment by flyinghead** [comment]
There is no "solution" because that's the way this game is supposed to be rendered.

**Comment by Julinkk** [comment]
I understand, so I prefer when the rendering is bad ^^. Thanks for the answers.
