### ISSUE TITLE
Reel Fishing Wild - Vertical lines appear in the Fish Glossary and Fishing Notebook when using DX9

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1299]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: e60f30b

Happens only in DX9.

![Reel Fishing](https://github.com/flyinghead/flycast/assets/14366233/9537d263-3289-454d-aab4-8c596dae3d56)

**Comment by flyinghead** [comment]
Should be fixed in the next master build

**Comment by kihato** [comment]
I confirmed that it has been fixed. thanks!
