### ISSUE TITLE
msvcrt.dll error when running latest versions

### ISSUE THREAD

**Issue by trstmp** [flyinghead/flycast#13]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Windows x64 | master | f23a3d3 | Downloaded from build site |

**_Description of the Issue_**

When trying to run the latest versions of Flycast I get an error: "Procedure entry point _create_locale could not be located in the dynamic link library msvcrt.dll." As far as I know all Visual C++ redistributable packages are installed and updated.

The latest version that works is the one from 2019-07-02T10:21:28 (a4eb9c2). The next version, 2019-07-30T11:08:19 (f23a3d3), is the first one that doesn't work.

This happens on two different computers with Windows 7. All versions work fine on another computer with Windows 10 so maybe this has something to do with it.

- [ X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
Thanks for reporting!
Hopefully c4ecfe3d9c031e69db206d63c6721d154a602226 fixes the issue.

**Comment by trstmp** [comment]
That did fix it, thank you.

Is it normal that this new version is listing all my .bin files along with the .gdi ones? Is there any way to filter the game list so it only shows .gdi files?

**Comment by flyinghead** [comment]
This is because .bin files are supported Naomi rom names. But I agree that this is inconvenient and unfortunately there's no way to filter them right now.

**Comment by trstmp** [comment]
That's alright, I'll just use the Filter bar until there's a better solution.

Thanks for all your work.

**Comment by flyinghead** [comment]
.bin are now hidden by default: https://github.com/flyinghead/flycast/commit/11c95c41d30073e9da70afc76bb69fdc657a3d1b

**Comment by trstmp** [comment]
I just saw the update, very cool.
