### ISSUE TITLE
flycast is not savestage every games!!!!!

### ISSUE THREAD

**Issue by tee4341** [flyinghead/flycast#130]
flycast is not savestage every games!!!!!

![GifMaker_lowquality8](https://user-images.githubusercontent.com/48321898/99903496-67813f80-2cf7-11eb-9da9-62546be9875d.gif)

and not loadstage (savestage not found)

**Comment by flyinghead** [comment]
Save states are saved to a folder named `data` in Flycast home folder.

Check that this folder exists and that files can be created. Check that there is enough free space.

**Comment by tee4341** [comment]
ok than;kkkkkkkkk it work

**Comment by flyinghead** [comment]
resolved
