### ISSUE TITLE
Virtua Tennis / Tennis 2K2 - Shadows of players and balls are not displayed when using DX9

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1301]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: ab25cc7

This only happens in DX9.

Images on the left: DX11 / Images on the right: DX9
![Virture Tennis_3](https://github.com/flyinghead/flycast/assets/14366233/1435f100-ee1a-4db5-8abb-6c5698d3d77e)
![Tennis2K2_3](https://github.com/flyinghead/flycast/assets/14366233/0fceddd5-d37c-4be8-9a13-c02a56e5ffd8)

**Comment by flyinghead** [comment]
Should be fixed in the next master build

**Comment by kihato** [comment]
Confirmed. Thanks for the quick fix.
