### ISSUE TITLE
(Ninja Assault) there's need 2 credits while already turn on the Naomi Free Play button 

### ISSUE THREAD

**Issue by Thetouchedjoe** [flyinghead/flycast#1302]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android

Github hash: c1f0a5a

Hardware: Snapdragon

**_Description of the Issue_**

Yeah I'm trying Ninja Assault with settled Naomi Free Play option but when I open the rom and to the game it has problem, the game itself says " Insert 2 Coins " while I can't press any button to Insert and already setted Naomi Free Play button

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Screenshot_2023-11-15-14-26-50-01_65c2d17d50e120d19246d3ee50ce680d](https://github.com/flyinghead/flycast/assets/147065598/38bb407a-3043-4daa-b1f1-fb4691d19085)

**Comment by Thetouchedjoe** [comment]
I'm also try other versions of Ninja Assault but result the same with Naomi Free Play option, still need to insert an credit

**Comment by flyinghead** [comment]
This game doesn't use the standard Naomi free play system so it must be set manually in the game test menu:
![image](https://github.com/flyinghead/flycast/assets/16261910/d4fc69c8-b64f-4790-820c-439ab882466b)

**Comment by Thetouchedjoe** [comment]
How to open the coin options? I don't which the button combination is

**Comment by flyinghead** [comment]
The same for all Naomi games: use the Test button (RT + X on the Android virtual gamepad)

**Comment by Thetouchedjoe** [comment]
So how do I navigate the test button I'm literally try all of the buttons like the d pad and all buttons

**Comment by Thetouchedjoe** [comment]
I don't need to ask but I'm already know how to navigate, thanks for the hint
