### ISSUE TITLE
Some WinCE games freeze at launch

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#1303]
Hello,

Super Runabout and KISS Psycho Circus freeze after the bios logo.

Tested with the latest nightly (Win11, default settings) and RA

**Comment by flyinghead** [comment]
Both games boot fine here.
Please indicate the actual flycast core version or git hash.
Any non-default core settings?

**Comment by dukeblooders** [comment]
Sorry, I mean I tried the latest standalone nightly (with default settings).
https://github.com/flyinghead/flycast/commit/665ef86

I tried these versions:
http://redump.org/disc/5628/
http://redump.org/disc/48219/

I tried other WinCE games (Worms Armageddon, Sega Rally 2 and Urban Chaos) and they work fine.

**Comment by flyinghead** [comment]
If you use PAL editions then set Core Options > Video > Broadcast to PAL... particularly with Windows CE games.

**Comment by dukeblooders** [comment]
OK, it works with PAL or Default in the standalone version, but it seems the Default option doesn't work with these games in RA (at least with my config).

But it's OK for me, thanks for your help!

[Flycast.txt](https://github.com/flyinghead/flycast/files/13397591/Flycast.txt)

**Comment by flyinghead** [comment]
Don't use the `Default` option. It just means the last one used which might be anything.
