### ISSUE TITLE
add support to other arcade systems (example : Sega Model 3 and Sega Model 2 also Triforce)

### ISSUE THREAD

**Issue by Thetouchedjoe** [flyinghead/flycast#1306]
**Is your feature request related to a problem? Please describe.**
I'm just kinda need more games to play on the Flycast and im seeing other arcade system emulator and im thinking to be supported by Flycast

**Describe the solution you'd like**
the arcade system that maybe can be supported by Flycast is =
- Sega Model 3
- Sega Model 2
- Triforce

**Describe alternatives you've considered**
Yeah maybe the arcade systems like those maybe possibly supported by Flycast but it need a lots of time to be developed. and yeah im make this to be able to play other nostalgic games

**Additional context**
yeah maybe thats for the issue

**Comment by vkedwardli** [comment]
Use this https://www.supermodel3.com/

**Comment by Thetouchedjoe** [comment]
Yes but I think Supermodel is too complicated to use so I want to add it to Flycast, so I can play easily on Android devices

**Comment by BroKill** [comment]
So your only issue with Supermodel is it doesnt run on Android and you are asking to be added to Flycast just for that without thinking it has nothing in common with Flycast emulation.

**Comment by Thetouchedjoe** [comment]
Ok, I'm already unterstand 🫡
