### ISSUE TITLE
Different rendering on retroarch

### ISSUE THREAD

**Issue by Julinkk** [flyinghead/flycast#1308]
The rendering is worse on retroarch than on standalone flycast, specifically with the widescreen hack activated. I checked all the parameters are the same, no shader or filter activated on retroarch.

![Capture d’écran (329)](https://github.com/flyinghead/flycast/assets/84175698/d7217941-214b-4cfc-ac00-f462a525fcc8)
![Capture d’écran (330)](https://github.com/flyinghead/flycast/assets/84175698/a1b90f32-d57f-460a-a9b9-01bc38935077)

**Comment by flyinghead** [comment]
Are you talking about Widescreen Hack or Widescreen Cheat?
Which graphics api are you using? OpenGL, Vulkan, DX11?
Does it make a difference if you change it (both for standalone and libretro)?

**Comment by Julinkk** [comment]
With Widescreen Cheat.

Retroarch:
GL, DX11, Vulkan with Widescreen Cheat : problem

Flycast:
GL, DX11, Vulkan with Widescreen Cheat : no problem

You are the developer of Flycast ?

**Comment by Nejsplitter** [comment]
hi @Julinkk are you in the flycast discord? i think the issue might be how RA reads cht files

**Comment by Julinkk** [comment]
After several tests I still have the same problem, what is the difference in rendering between Retroarch and Flycast? I'm trying to understand where the problem is coming from.

**Comment by flyinghead** [comment]
Another user reported a similar problem. In his case, enabling Bilinear Filtering in RetroArch (which is the default) mostly fixed the issue.
Disabling Anisotropic Filtering in Flycast made standalone and the core output virtually identical frames.

**Comment by Julinkk** [comment]
Indeed that was it! I was misled because it is not indicated on flycast standalone that it applies a bilinear filter. Thanks for the solution!

**Comment by gouchi** [comment]
@flyinghead This issue could be closed as it is just difference between default parameters on Flycast standalone and RetroArch ?

**Comment by flyinghead** [comment]
You're right
