### ISSUE TITLE
(Extreme Hunting) error blue screen when starting to play

### ISSUE THREAD

**Issue by Thetouchedjoe** [flyinghead/flycast#1309]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android

Github hash: 

Hardware: Adreno 610

**_Description of the Issue_**

I'm was testing the Atomiswave games with the BIOS of it and testing a game, which is Extreme Hunting. I'm kinda excited to play until I shocked that there's a blue screen with a random text coming.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Screenshot_2023-11-17-18-36-49-95_65c2d17d50e120d19246d3ee50ce680d](https://github.com/flyinghead/flycast/assets/147065598/abe0e3d9-ca3a-4ac7-ae47-1a69a65b2235)

**Comment by flyinghead** [comment]
Works fine here:
![image](https://github.com/flyinghead/flycast/assets/16261910/95f0bf5b-070d-4abc-b4a9-d984d95ab796)

Check that your rom is valid and indicate your flycast version/git hash.

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen if not
