### ISSUE TITLE
project justice flycast constant crashes

### ISSUE THREAD

**Issue by crowspaceboy** [flyinghead/flycast#1310]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
fightcade / windows / PC

Github hash: 

Hardware: 

**_Description of the Issue_**

I am getting constant crashes in Project Justice. The game itself runs fine, probably the best running flycast game for me. But it intermittently crashes, and for the past few weeks, it's been crashing a lot, and I have no idea why. I'm not sure what info to provide—it just hangs and then eventually closes. It does not matter how good or bad the connection is: the most recent crash was a Austin TX to Dallas TX 16 ping connection, one that used to perform flawlessly a few flycast builds ago but now crashes pretty regularly after like 10-15 minutes or so

**_Debugging Steps Tested_**

happens when playing with multiple users
tried deleting savestate -> redownloading, issue persists

**_Logs Gathered_**

i would provide logs if I had any idea how to get them.

```


**_Screenshots_**

**Comment by flyinghead** [comment]
This issue should probably be better served on the dojo github: https://github.com/blueminder/flycast-dojo
And flycast version numbers/git hash will be needed.

**Comment by crowspaceboy** [comment]
I will open a ticket over there, sorry.

**Comment by flyinghead** [comment]
No problem.
Moved to https://github.com/blueminder/flycast-dojo/issues/45
