### ISSUE TITLE
(enhancement) add option to " Touch Lightgun mode " for arcade lightgun games

### ISSUE THREAD

**Issue by Thetouchedjoe** [flyinghead/flycast#1311]
**Is your feature request related to a problem? Please describe.**
I'm kinda little frustrated to play Arcade Lightgun games because for Android, I need to drag the crosshair with the Analog and press the A Button to shoot, for some games, it's kinda little difficult for some games so I want to add " Touch Lightgun Mode "

**Describe the solution you'd like**
The Touch Lightgun mode when it's been turn on, It will be only load not much buttons, there's Start, and a button which is an Reload button that's used for Confidential Mission and the main screen is used for the fingers to tap to the enemies to be shorted and simply reload it to the Left Side of the screen. And it's kinda useful for light gun games especially Lupin the 3rd : The Shooting, because it can be useful to complete minigames.

**Describe alternatives you've considered**
Maybe that's for all for the issue

**Additional context**

**Comment by flyinghead** [comment]
While there's no "touch lightgun mode" per se, you can enable the android mouse, which will act as a lightgun when touching the screen: `Settings > Controls > Physical Devices > Android Mouse > Port` set to A.
This setting isn't recommended for non-lightgun games.
Also the virtual gamepad is still visible and active in this mode.

**Comment by Thetouchedjoe** [comment]
Yeah, the touch Lightgun mode is used only for touch screen devices so we dont need a mouse to play Lightgun games just using Touch screen on your phone

**Comment by flyinghead** [comment]
On the `dev` branch, most buttons and controls are now hidden for arcade lightgun games. You just need to assign the `Android Mouse` to port A and you can just shoot by tapping on the screen.
I'll see if I can automatically enable this for lightgun games in a future version.
![image](https://github.com/user-attachments/assets/40dc20f0-2631-43a8-a2ba-f3e1fb837737)
