### ISSUE TITLE
[Nintendo Switch] Skies of Arkadia freezes

### ISSUE THREAD

**Issue by Photon324** [flyinghead/flycast#1312]
Skyes of Arkadia freezes almost at the very beginning when meeting Alfonso. I tried all versions of the emulator (1.2, 2.1, 2.2) and the game in the European and US regions. There is no such problem with the Android and PC versions.
I apologize if I didn’t describe the problem very clearly, I’ll translate it through Google translator.

**Comment by flyinghead** [comment]
Thanks for trying all versions. Since it doesn't happen on other platforms I assume this is a Switch-specific bug. Unfortunately I don't have switch to try to reproduce it. I'll see if I can get some help from a dev that owns one.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by Photon324** [comment]
Thank you very much, it works great now
