### ISSUE TITLE
[mali g72] Low FPS with Naomi 2 games

### ISSUE THREAD

**Issue by Saad0817** [flyinghead/flycast#1315]
**Plecreen andase Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Samsung galaxy note 10 lite Exynos 9810 mali GPU Android 13 One UI 

Github hash: 

Hardware: opengl/ vulkan

**_Description of the Issue_**

Dreamcast and Naomi games if I change the API to opengl  app crashes sometimes full black screen and freezes and some stages from vf4 and vf4 final tuned and vf4 version c if there's too much particles like sunlight water snow  it gets slower these mentioned stages even if I didn't either increase the resolution or upscale it gets slower and audio stutters in auto mode in vulkan, in some stages my Android mali g72 GPU it runs 60 fps in 1440p can you fix that I hope you understand thanks for you emulator I can play games offline games that's older and way better than i thought thanks again  

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

![285249336-537c2bdd-8aac-4c38-b05d-ef84cac0fedc.jpg](https://github.com/flyinghead/flycast/assets/142103645/326d8d9f-4dbe-4ca6-8c2c-d5b3ea5eaf91)

The stage that gets slower in virtual fighter 4 , virtual fighter 4 evo, virtua fighter 4 final tuned, virtua fighter version c all these SEGA NAOMI games

**Comment by flyinghead** [comment]
I don't understand the problem. Can you explain in more details?

**Comment by flyinghead** [comment]
Use Google Translate to explain your issue

**Comment by flyinghead** [comment]
Naomi 2 games are very demanding on the GPU (and also on the CPU in some cases) so it's not surprising to have some slow downs on some mobile phones.

Here are my recommendations:
- Prefer Vulkan to Open GL. Vulkan will usually get better performance than OpenGL but some drivers are slow or have bugs.
- If using Vulkan, try using per-pixel transparent sorting at native resolution (640x480). Again you will need a good Vulkan driver for this.
- With OpenGL, use per-strip transparent sorting. It is glitchy but per-triangle performance with Naomi2 is very bad.

**Comment by Saad0817** [comment]
> Naomi 2 games are very demanding on the GPU (and also on the CPU in some cases) so it's not surprising to have some slow downs on some mobile phones.
> 
> Here are my recommendations:
> 
> * Prefer Vulkan to Open GL. Vulkan will usually get better performance than OpenGL but some drivers are slow or have bugs.
> * If using Vulkan, try using per-pixel transparent sorting at native resolution (640x480). Again you will need a good Vulkan driver for this.
> * With OpenGL, use per-strip transparent sorting. It is glitchy but per-triangle performance with Naomi2 is very bad.
Thank you for the reply 
Can I ask U one question is ther any way to fix this

**Comment by Saad0817** [comment]
> > Naomi 2 games are very demanding on the GPU (and also on the CPU in some cases) so it's not surprising to have some slow downs on some mobile phones.
> > Here are my recommendations:
> > 
> > * Prefer Vulkan to Open GL. Vulkan will usually get better performance than OpenGL but some drivers are slow or have bugs.
> > * If using Vulkan, try using per-pixel transparent sorting at native resolution (640x480). Again you will need a good Vulkan driver for this.
> > * With OpenGL, use per-strip transparent sorting. It is glitchy but per-triangle performance with Naomi2 is very bad.

**Comment by Saad0817** [comment]
Ok by the way thank you for your work I can expect optimisation from the future there's still hope and thank you for the for the time I will play some Dreamcast fighting games again thank you for your wonderful work ❤️‍🔥

**Comment by Saad0817** [comment]
Sorry I forgot to mention even if change the resolution to 640x480 or half native it's running slower I mean getting 40 fps and I have opengl 3.0

**Comment by flyinghead** [comment]
The rendering resolution is critical when using per-pixel transparent sorting. In this case, you should use 640x480.
For other sorting methods it doesn't affect performance that much.
Also I recommend you use per-strip instead of per-triangle for naomi2 games.

Stages containing water surfaces are even more demanding since they do 2 renders per frame: one for the water surface image and one for the normal frame.

**Comment by Saad0817** [comment]
Yeah I'm using per strip for all Naomi games it's all the same thank you for the replies i appreciate it mali GPU are worse i understand now Again thank you Appreciate

**Comment by flyinghead** [comment]
Inactive
