### ISSUE TITLE
Getting slower

### ISSUE THREAD

**Issue by Saad0817** [flyinghead/flycast#1316]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android Note 10 lite exynos 9810

Github hash: 

Hardware: Vulkan /open gl

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(![Screenshot_20231123_204719_Gallery.jpg](https://github.com/flyinghead/flycast/assets/142103645/537c2bdd-8aac-4c38-b05d-ef84cac0fedc)

)

**Comment by flyinghead** [comment]
No need to open a second issue. Keep everything in #1315

**Comment by Saad0817** [comment]
> No need to open a second issue. Keep everything in #1315

Can you check that issue again please #1315
