### ISSUE TITLE
Analog stick not active after hold touchscreen botton....!!

### ISSUE THREAD

**Issue by tee4341** [flyinghead/flycast#132]
Help me please. ...Analog stick (map key)  not active after hold touchscreen botton....!!
![GifMaker_lowquality13](https://user-images.githubusercontent.com/48321898/99918599-85c45b00-2d4a-11eb-9fc6-5f6b241f4507.gif)

**Comment by flyinghead** [comment]
Is this still an issue?

**Comment by flyinghead** [comment]
No answer
