### ISSUE TITLE
Insert card not working

### ISSUE THREAD

**Issue by Taydeon** [flyinghead/flycast#1324]
Im on WIndows 11 and no matter what button i set insert card to nothing happens when i push the corresponding button.. using the latest stable build

**Comment by flyinghead** [comment]
Which game?
Flycast version?

**Comment by Taydeon** [comment]
Mushiking iv

version 2.2
build date 10-28-2023

**Comment by flyinghead** [comment]
you need to pause the game to input a card code, then resume and press insert card:
![image](https://github.com/flyinghead/flycast/assets/16261910/5112816a-2d62-4f1f-866d-1c636c145459)

**Comment by Taydeon** [comment]
Thank You!!!
