### ISSUE TITLE
Standalone version does not detect bios file in Linux Mint. 

### ISSUE THREAD

**Issue by FurtiveDolus** [flyinghead/flycast#133]
I've put a copy the same bios file that works for Flycast in RetroArch in '/home/myhome/.config/reicast/data/'and it simply doesn't detect the dc_boot.bin file. I get a "No BIOS found" error when selecting 'Dreamcast BIOS' in the games menu as well. 

OS is the current latest Linux Mint 64-bit.

**Comment by flyinghead** [comment]
The other place it looks for is `/home/myhome/.reicast/data/`

**Comment by flyinghead** [comment]
and `/home/myhome/.local/share/reicast/data/`

**Comment by FurtiveDolus** [comment]
After trying both locations, the '/home/myhome/.reicast/data/' directory worked, but not the '/home/myhome/.local/share/reicast/data/' dir. Thanks for the reply.

**Comment by flyinghead** [comment]
It's a bit of a mess currently. I'm working on some improvements.

**Comment by flyinghead** [comment]
FYI as of https://github.com/flyinghead/flycast/commit/8f77a5482a1a7f5bd88eff541f65cd94cc135405, flycast will now use
`~/.config/flycast` and `~/.local/share/flycast` by default.

The legacy directories `~/.reicast` and `~/.reicast/data` are still supported, as well as `~/.config/reicast` and `~/.local/share/reicast`.

**Comment by rcampbel3** [comment]
Hi,

I build flycast from source the other day and had this exact problem. Here's what I found:
starting flycast from ~/.config/flycast or ~/.config/flycast/data worked
starting anywhere else failed.
I've symlinked .config/flycast to .reicast now but it seems like this should be fixed. There's a home dir setting in the config that I cannot change and it's not in the .cfg file.

```
ross@rodan:~/.config/flycast $ flycast
00:00:965 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:01:011 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:06:883 hw/naomi/naomi_cart.cpp:366 N[NAOMI]: NAOMI GAME ID [MONKEY BALL JAPAN VERSION]
00:06:883 ./nullDC.cpp:260 N[BOOT]: Game ID is [MONKEY BALL JAPAN VERSION]
ross@rodan:~/.config/flycast $ cd ..
ross@rodan:~/.config $ flycast
00:00:602 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:648 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:725 hw/naomi/naomi_cart.cpp:107 W[NAOMI]: naomi: Cannot open epr-21577h.ic27
00:00:725 hw/naomi/naomi_cart.cpp:186 W[NAOMI]: Warning: Region 1 bios not found in naomi
00:00:725 hw/naomi/naomi_cart.cpp:107 W[NAOMI]: naomi: Cannot open epr-21576h.ic27
00:00:736 rend/gui.cpp:1877 E[BOOT]: Error: cannot load BIOS naomi
```

**Comment by flyinghead** [comment]
Flycast uses two directories: the config directory (emu.cfg, controller mappings) and the data directory (everything else including BIOS files). They are `~/.config/flycast` and `~/.local/share/flycast` respectively.

For backward-compatibility reasons, `~/.reicast` and `~/.reicast/data` will be used instead if they exist.

So put your BIOS files in `~/.local/share/flycast` or `~/.reicast/data`, depending on your choice of installation.
