### ISSUE TITLE
Retroarch version of flycast crashes after dreamcast logo for omikron the nomad soul. works standalone

### ISSUE THREAD

**Issue by aphixe** [flyinghead/flycast#1339]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
windows 11
Github hash: 

Hardware: 
Amd ryzen 5900x, 32gb ram geforce 4080
**_Description of the Issue_**
Retroarch version of flycast crashes after dreamcast logo for omikron the nomad soul usa, as well as europe version. Solution is to use stand alone flycast, however it be nice to have everything work through retroarch.
Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by bslenul** [comment]
It doesn't crash for me, however it closes and re-open the RetroArch window.

It looks like the max framebuffer width is too low for this game as it sometimes seems to double its width. So for example at 640\*480 the core sets a max width and height of 853\*853: https://github.com/flyinghead/flycast/blob/f4f087a6ea83a5483dedf23ad2b38763988eccc5/shell/libretro/libretro.cpp#L635-L636 but then the game decides to double the width (1280 in this case) so the core has to set a new max width and reinitialize the video driver. I'm guessing that reinitialization could cause the crash in some cases?

**Comment by flyinghead** [comment]
No crash here either. It is expected that some games will change video settings such as horizontal pixel doubling. But this shouldn't cause a crash. It looks like a faulty GPU driver.
