### ISSUE TITLE
unable to map L trigger R trigger on Arcade mode

### ISSUE THREAD

**Issue by jvhellraiser** [flyinghead/flycast#134]
Ok, let me see how do explain this....
i have a X-input controller when i use Flycast
when configuring the Dreamcast controller i can configure all my buttons
if i change to arcade mode to play Atomiswave or Naomi roms button 4 & Button 5 appear as N/A
and that not correct since some roms in Atomiswave they either use Button 5 or both 4 & 5 for the same button.
i notice that in Atomiswave Metal slug 6 you use 0,1,2,3,4,5  my config is simple Y= Shot B= Jump A=change X=Special And 5=Bombs in Flycast i can't do this i get Y= Shot B= Jump A=change X=Special Button 5 = N/A Suppose to be Bombs
i guess what i am trying to explain is that some game in arcade do use all the buttons or at least the triggers... 

Question: Is Flycast only campatible with Naomi only what about Naomi2?

**Comment by flyinghead** [comment]
You should be able to map your triggers as button 5 and 6. Enable "Arcade button names" to see buttons 5 and 6.

If your triggers are analog axes, map them using the right column in the Mapping dialog (Analog axes).
If they are buttons, use the left column (Buttons).

**Comment by jvhellraiser** [comment]
I know about Arcade button names, my Issues is that i can't configure the R bumper L Bumper if i am using X-input in Flycast
i can configure L & R triggers but there is a problem cause most of the Atomiswave configurations use the L & R Bumpers and not the R trigger or L trigger you can't configure L trigger as the Bomb button on Metal Slug 6 cause the game use L Bumper always... you can't move that button from there.

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen if not.
