### ISSUE TITLE
Local denial of service of flycast host from dreamcast code.

### ISSUE THREAD

**Issue by buhman** [flyinghead/flycast#1348]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: x86_64 / Linux

Github hash: 5fde889d7

Hardware: AMD Radeon, Mesa 23.1.9, amdgpu

**_Description of the Issue_**

Running [`macaw_cube_render_to_texture.elf.gz`](https://github.com/flyinghead/flycast/files/13696808/macaw_cube_render_to_texture.elf.gz) with OpenGL enabled will make both Flycast and the entire host unresponsive. This reproduces in less than 1 second after flycast launches.

Expected outcome: neither Flycast nor certainly the host operating system environment should become unresponsive.

Actual outcome: a power-cycle of the host computer is necessary.

I suspect this is memory-allocation related.

**_Debugging Steps Tested_**

  * Enable OpenGL
  * `flycast macaw_cube_render_to_texture.elf`

**_Logs Gathered_**

N/A

**_Screenshots_**

N/A

**Comment by flyinghead** [comment]
What is the source of this binary?

**Comment by flyinghead** [comment]
Never mind. I found it

**Comment by flyinghead** [comment]
I can't reproduce the issue here. I had to enable Full Framebuffer Emulation to get something displayed but no freeze of any kind:
![image](https://github.com/flyinghead/flycast/assets/16261910/0ec52117-8095-4e5c-9874-243311ce398b)

Tested per triangle/per strip/per pixel. Vulkan also works fine.
ubuntu 20.04, nvidia GTX 1080

**Comment by buhman** [comment]
This is difficult for me to test because I need to reboot every time I do test this. This reproduces consistently for me when OpenGL is selected.

![video-settings](https://github.com/flyinghead/flycast/assets/728108/a66d64ee-92fe-4162-9b7a-2297209be7cb)

> What is the source of this binary?

Perhaps lost.

Here is another very similar binary that is identical to the source code in https://github.com/buhman/dreamcast/commit/e2a6406a05a8e95af1182c877401e5c88b2e4a15

This one also reproduces the "host is slowed to unusable and flycast can't be terminated via the window manager when OpenGL is selected" (but has a more interesting outcome Vulkan or real Hardware is selected instead).

[macaw_cube_render_to_texture.elf.gz](https://github.com/flyinghead/flycast/files/13698967/macaw_cube_render_to_texture.elf.gz)

**Comment by buhman** [comment]
> Nvidia

This gave me an idea:

I can not reproduce this with:

```
LIBGL_ALWAYS_SOFTWARE=1 flycast macaw_cube_render_to_texture.elf
```

I conclude that this must be a mesa/amdgpu bug, and not a flycast bug.

Thank you very much for your time.
