### ISSUE TITLE
Sakura Wars 3-Conversation text is not displayed correctly

### ISSUE THREAD

**Issue by nemimi2194** [flyinghead/flycast#1349]
Hello. I'm Japanese and I'm not good at English, so I'm using Google Translate to post.

Windows11/RTX4080 i9-13900kf
Github hash: [e057370](https://github.com/flyinghead/flycast/commit/e057370)

In a conversation scene
Text is not displayed correctly
<img width="1920" alt="sakura2" src="https://github.com/flyinghead/flycast/assets/148392391/8974f6fe-9885-4d7f-b623-eb0bba7a5c86">

<img width="1920" alt="sakura3" src="https://github.com/flyinghead/flycast/assets/148392391/c5fdc625-fb74-4478-9897-44f7d55fa653">

<img width="1920" alt="sakura4" src="https://github.com/flyinghead/flycast/assets/148392391/b70c2fa8-e945-4128-99ee-effb3be072f3">
<img width="1920" alt="sakura5" src="https://github.com/flyinghead/flycast/assets/148392391/309a4614-6031-45f6-8103-74a10f71208f">

This phenomenon occurs randomly

I think it may be difficult to understand because it is a Japanese text.
I would like you to fix the problem

for conversation scenes
I have uploaded the save data for the walking part.
[sakura3_save_state.zip](https://github.com/flyinghead/flycast/files/13697129/sakura3_save_state.zip)

**Comment by flyinghead** [comment]
@kihato Can you help me understand the problem here? Thanks!

**Comment by kihato** [comment]
Text is garbled here and there.
The correct display is as follows.
![sakura3_5](https://github.com/flyinghead/flycast/assets/14366233/859d00ed-de24-438b-8e41-d656c1a26c24)

This problem occurs in other games as well, but as usual, single threading solves it.

**Comment by flyinghead** [comment]
Ok so it looks similar to #1268 and perhaps #1273.
