### ISSUE TITLE
Flycast is broken on Android 4.3 and lower

### ISSUE THREAD

**Issue by Raypuia** [flyinghead/flycast#135]
As the title says, Flycast just stays on a black screen on devices with Android 4.3 and lower.
Might be a GLES error, since Reicast also got this issue before and was fixed in 20.02b

**Comment by flyinghead** [comment]
Unfortunately I don't have an Android 4.3 device to test with.

Do you have a pointer to the fix in reicast (issue or commit)?

**Comment by Raypuia** [comment]
I think it was the 090ebc1 commit.
Since i was the one who reported that issue on Discord

**Comment by flyinghead** [comment]
I just ported the fix. Let me know if this helps.

**Comment by Raypuia** [comment]
It works now!
I tested it on a Samsung Galaxy S3 and a Blackberry Z10 and black screen is no more

**Comment by flyinghead** [comment]
Great news
