### ISSUE TITLE
[Windows] Soul Calibur black Screen... loading a save file from old VMU

### ISSUE THREAD

**Issue by Grondoval** [flyinghead/flycast#1350]
Platform / OS / Hardware: 

Win 10 i9-9900 - 32 GB - RTX4060Ti

Github hash: 192838b9c

Hardware: 

**_Description of the Issue_**

When loading old VMU in Soul Calibur, screen turns black but can hear sound/audio and move controls, other emulator show screen perfectly...

**_Debugging Steps Tested_**

I try putting old vmu in port A and B from same and diferrent controller with same results on Soul Calibur... But i can hear audio and move control

Other emulators load perfectly save and can see all fighters unlocked...

**_Logs Gathered_**

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```
Don´t know where obtain that
```

**_Screenshots_**

(Replace this line with any issue screenshots)

No screenshots because black screen!

It´s possible to get a save file flycast compatible? Only if this issue can´t be resolved...

**Comment by flyinghead** [comment]
Please upload the vmu file

**Comment by Grondoval** [comment]
[vmu_save_A1.zip](https://github.com/flyinghead/flycast/files/13703549/vmu_save_A1.zip)


News: When screen turns black after loading VMU inside Soul Calibur (EUR), i can hear audio from intro and can move in menu controls but in black screen...

**Comment by flyinghead** [comment]
Works fine here. Using the EU version, I tested both 50 Hz and 60 Hz and no issue loading the VMU:
![image](https://github.com/flyinghead/flycast/assets/16261910/da9685c6-b9c5-4b94-a30e-50fce2a37e27)

Make sure your settings are correct (choose PAL for the EU version) and that your media is correct (avoid .CDI)

**Comment by Grondoval** [comment]
it´s last version from emu? Any other specific config to take a look?

With 17/12/2023 flycast version occurs the same... But with 1.2 cited works...

**Comment by flyinghead** [comment]
I'm using latest master: 192838b9c1c4036628ed3c042f7f1091726ef1b8

Try using a different graphics API (opengl, vulkan, dx11) although I doubt this has anything to do with the VMU.

**Comment by Grondoval** [comment]
I think i solve it. Using version 2.2 from this github, save load correctly and can see screen, but screen it´s weird. Only need to use adjust display inside game and can see all chararcters!
