### ISSUE TITLE
Custom textures crash with arcade games with Vulkan

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#1351]
Platform / OS / Hardware: PC / Windows 10 / i5-12400F / RTX 3060 Ti

Github hash: e057370e97d5c120bb2185a573ae289b8ffc31f7

**_Description of the Issue_**

When using a custom textures pack on arcade games with Vulkan renderer, Flycast will crash. Only tested with MvC2 (Naomi) and Dolphin Blue (Atomiswave) so far, but could test more games if needed.

No problem with GL and D3D11.

Got this when running with vkconfig:
```
UNASSIGNED-GeneralParameterError-RequiredParameter(ERROR / SPEC): msgNum: -1711571459 - Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object 0: handle = 0x1eaf9597be0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x99fb7dfd | vkCmdPipelineBarrier: required parameter pImageMemoryBarriers[0].image specified as VK_NULL_HANDLE

    Objects: 1

        [0] 0x1eaf9597be0, type: 3, name: NULL

VUID-VkImageMemoryBarrier-image-parameter(ERROR / SPEC): msgNum: -437126924 - Validation Error: [ VUID-VkImageMemoryBarrier-image-parameter ] Object 0: handle = 0x1eaf7b69b90, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xe5f1f8f4 | Invalid VkImage Object 0x0. The Vulkan spec states: image must be a valid VkImage handle (https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier-image-parameter)

    Objects: 1

        [0] 0x1eaf7b69b90, type: 1, name: NULL
```
It also crashes with the Libretro core, idk if it helps but here's what I got by running it with RetroArch built with drmingw: [crash-231221-005028.log](https://github.com/flyinghead/flycast/files/13733887/crash-231221-005028.log)

Easy to reproduce: run an arcade game for a few secs with the "Dump Textures" setting enabled, move the game textures folder from "data/texdump/" to "data/textures/", enable "Load Custom Textures", make sure to use Vulkan and launch the game again.

Or just extract this file in "data/textures/" and run mvsc2.zip: [MARVEL_VS_CAPCOM2__JAPAN.zip](https://github.com/flyinghead/flycast/files/13733843/MARVEL_VS_CAPCOM2__JAPAN.zip)
It should crash as soon as you put your cursor on Cable, I painted him in red just to make sure it was working with the other renderers:

![image](https://github.com/flyinghead/flycast/assets/33353403/4b3672c5-fb60-4e03-980d-a14a1d233bcc)

**Comment by bslenul** [comment]
It was a bit late when I opened this issue, so I didn't bisect, for now I can say it works with 153dbb0 but crashes with d8e6152

For some reason "Load Custom Textures" doesn't seem to work if I built Flycast locally 🤔 Do I need some deps or compilation flags or something?

So for now all I can say is that the regression happened in one of these:

![image](https://github.com/flyinghead/flycast/assets/33353403/4f82fd1d-3bed-41c0-b926-9e67693c96d2)

Looks like only one is VK related, so *maybe* 939e2bc68f9319323f970fde7a2d2cb72de3242d

**Comment by flyinghead** [comment]
Yes, this is due to 939e2bc68f9319323f970fde7a2d2cb72de3242d. Good catch btw since i didn't test custom textures.
Easy fix coming.

**Comment by flyinghead** [comment]
should be fixed in the latest dev build
