### ISSUE TITLE
[Mali-G52] vulkan per-pixel blackscreens and shows strange artefacting on Android

### ISSUE THREAD

**Issue by notimp** [flyinghead/flycast#1356]
Version of Flycast tested: 2.2
But this also affects several retroarch core versions.

Games tested: Shenmue (because it needs per pixel accuracy alpha sorting) (PAL, but should affect both versions and most games, even the bios swirl before the game boots is broken (doesnt show))

Special settings:

Per pixel alpha sorting
Widescreen cheats in Shenmue (but that shouldnt matter)
Anisotropic Filtering 4x (but that shouldnt matter)

tested on both

Retroid Pocket Flip (which internally is the same as a Retroid Pocket 3+)
Ayn Odin 2

It could be an issue with the devices default drivers Vulkan implementation, but if you could look into it and try to suss it out, or even give a little feedback on whats the culprit, it would be very much appreciated. :)

I'm not alone here, many people suffer from this issue on popular Android emulation devices currently. :)

https://old.reddit.com/r/OdinHandheld/comments/18voqm6/aight_how_do_i_fix_the_issue_with_eyes_guys_using/

Thank you,

n.

And a happy new year. ;)

**Comment by flyinghead** [comment]
Unfortunately Mali GPUs don't work well with per-pixel. See #1234 and #1014.
I already tried to work around these issues without success.
