### ISSUE TITLE
[Standalone] Unable to open Pause Menu in Virtual-On Oratorio Tangram (Twin Stick)

### ISSUE THREAD

**Issue by kathyrollo** [flyinghead/flycast#1359]
Platform / OS: Win11 Pro

Github hash: [192838b](https://github.com/flyinghead/flycast/commit/192838b)

Hardware: Ryzen 7 5800H

**_Description of the Issue_**

When Dreamcast Devices are set to Twin Stick, the Start button works on menus (selecting options, skipping replays), but not while in-game. Therefore, user is unable to open the Pause Menu.

**_Debugging Steps Tested_**

![Screenshot 2024-01-02 014150](https://github.com/flyinghead/flycast/assets/28589393/d1f007d9-b6f6-4eef-882a-a925d702dcc6)

[This article](https://www.thedreamcastjunkyard.co.uk/2017/01/a-quick-look-at-dreamcast-twin-stick.html) mentions separate Start and Pause buttons on the base of the Twin Stick.

![DreamcastTwinStick](https://github.com/flyinghead/flycast/assets/28589393/6ca5077c-336b-4610-a88a-104d609a0350)

Pause config under System Buttons in Controller Mapping could be added to accommodate the Twin Stick.

![Screenshot 2024-01-02 014313](https://github.com/flyinghead/flycast/assets/28589393/05f4070c-c352-4af6-a611-819726aa4540)

**Comment by flyinghead** [comment]
The Twin Stick supposedly has 8 buttons: A, B, X, Y, C, D, Z and Start. The triggers and top stick buttons are A, B, X and Y. So I guess the Twin Stick pause button is either C, D or Z, which you can map.

**Comment by kathyrollo** [comment]
Hi @flyinghead , I can confirm the D button maps to the dedicated Pause button on the Twin Stick. Thanks for your speedy support as always.

Posting my full Xbox One S Controller mapping for documentation purposes:

![Screenshot 2024-01-02 094947](https://github.com/flyinghead/flycast/assets/28589393/1b77511c-2c74-4ef9-b765-345f9ee5a321)

![Screenshot 2024-01-02 095007](https://github.com/flyinghead/flycast/assets/28589393/de9385b7-eab2-4109-bc80-b23151060f91)

|Control|Twin Stick|Gamepad|
|---|---|---|
|D-Pad U/D/L/R|L-Lever|L-Stick|
|D-Pad2 U/D/L/R|R-Lever|R-Stick|
|A|R-Trigger|R2|
|B|R-Button (Top)|R1|
|X|L-Trigger|L2|
|Y|L-Button (Top)|L1|
|D|Pause|Select|
|Start|Start|Start|

In game, this makes the L/R Stick as L/R Lever, L1/R1 as L/R Turbo, and L2/R2 as L/R Weapon to mimic the Twin Stick layout on a standard gamepad. Cheers!
