### ISSUE TITLE
Initial D Ver.1 and 2 Game Over snapshot missing

### ISSUE THREAD

**Issue by CarterJBurke** [flyinghead/flycast#1362]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 2H22

Github hash: 

Hardware: Core i7 8750H, GTX 1060, 16 GB RAM

**_Description of the Issue_**

when the game over screen appears, normally, the game shows you a snapshot of your car as a manga panel in B&W, but for some reason, the image is not present when you get to this screen on flycast. However, when you finish a race on flycast, you can see the snapshot for a split second. 

**_Screenshots_**

![image](https://github.com/flyinghead/flycast/assets/54372165/391f187c-152b-45d6-9d38-c0572795f5ef)

**Comment by flyinghead** [comment]
In order to view this end of race snapshot, you need to enable `Full Framebuffer Emulation` and disable `Multi-threaded emulation`. This is due to the "hackish" way this picture is generated. Needless to say these settings have an impact on performance and render quality.

**Comment by CarterJBurke** [comment]
ah. figures, my guess is that the games poke through the replay of the race, and fish a frame out of the actual framebuffer.

**Comment by flyinghead** [comment]
it's a bit more complicated than that and involves mostly renders to texture. However you guessed right: it finishes by doing an (invisible) render to the actual framebuffer and reading back from it.
Not sure why it does so. My guess is it's a cheap way to convert the texture to a different format.
