### ISSUE TITLE
Unexpected crosshairs appear in arcade games

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1363]
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 192838b

Set the light gun on device A and select a color that stands out, such as red, as the crosshair color.
Then, leave the crosshair check as is and change to the Sega controller.
When you launch any arcade game, a crosshair will appear.

**Comment by flyinghead** [comment]
Which renderer are you using? I tried OpenGL and Vulkan but can't reproduce the issue.
I may be missing an important step so any additional detail would be helpful.

**Comment by kihato** [comment]
Sorry. Information was lacking. It seems to be limited to DX.
The same thing happens with device B etc.

![naomi](https://github.com/flyinghead/flycast/assets/14366233/b6e9c914-ad8d-4097-8676-5713072a7a9a)

**Comment by kihato** [comment]
I deleted the settings at that time, so I couldn't reproduce it, but after trial and error, I found that the additional bug condition other than "Using DX9 or DX11" was to check "Show VMU in-game".

**Comment by flyinghead** [comment]
Yep, that was the missing piece. Thanks!
Should be fixed in the next master build.

**Comment by kihato** [comment]
Thanks. It's fixed!
