### ISSUE TITLE
Manpuku Suizokukan - Device Error (Hopper is jammed)

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1365]
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 2a48049

The game works very well. However, the "HOPPER IS JAMMED" error occurs in kingyo, manpuku and shateki.
It seems that the error does not necessarily occur in the same scene.
[manpuku.zip](https://github.com/flyinghead/flycast/files/13910168/manpuku.zip)

https://github.com/flyinghead/flycast/assets/14366233/159a035a-5398-4465-a581-57e3ff0e1cc6

**Comment by flyinghead** [comment]
Should be fixed in the last dev build.
I also fixed a coin chute jam error when pressing the coin button for too long.

**Comment by kihato** [comment]
Thanks for your hard work! The game works fine.
