### ISSUE TITLE
Flycast doesn't apply VMUs to Lightguns, Arcade Sticks or Race Controllers, Only standard controllers.

### ISSUE THREAD

**Issue by Widge-5** [flyinghead/flycast#1366]
**_Platform / OS / Hardware: _**
Raspberry Pi 5, Bookworm 64bit, RetroPie.
Using lr-flycast-dev

Github hash: 
e7d0a5f
195f401

**_Description of the Issue_**
Flycast is not acknowledging VMUs for device types other than the standard controller.
VMUs should also be acceptable for Lightgun, Arcade Stick and Race Controller device types, but they aren't in flycast.
I noticed first in House of the Dead 2, that it would not save to VMU when device types in all 4 ports are set to "Lightgun". Cycling through the device types while on the "Could not find save data" screen, it does not find a VMU unless any one of the devices is set to "Controller".  House of the Dead 2 supports Controllers, Lightguns and Arcade Sticks, and all of those devices have VMU sockets. In fact I can confirm that my real Dreamcast  does save/load to/from a VMU in the Dreamcast lightgun.
A Race Controller also has a VMU slot, but I haven't tested a game that uses it.

**_Debugging Steps Tested_**

  * Tried another game, Confidential Mission also shows the same bug.
  * Updated lr-flycast-dev to the latest commit (from e7d0a5f to 195f401) resulted in no change to the behaviour.
  * Asked a friend to check if they too have the sae behaviour (also using a Pi5) and they confirmed it is the same.
  * Tried the "Per-Game VMUs" setting on "OFF", "VMU A1" and "All VMUs", all resulted in no change to the behaviour.

**_Screenshots_**

This video clip is from HotD2's "Could not find save data" screen.  While on this screen, cycling through the device types, it only changes to acknowledge a VMU when the device type becomes "Controller".

https://github.com/flyinghead/flycast/assets/77170359/fff20b86-eca8-4f60-9771-0620e613fa2d

**Comment by flyinghead** [comment]
Light guns, Arcade Sticks and Race controllers only have one VMU slot. If you enable the Purupuru/Vibration pack, this uses the only available expansion slot and no VMU can be connected.

When the vibration pack is disabled, a VMU is available:
![image](https://github.com/flyinghead/flycast/assets/16261910/b499db43-d30f-4f72-a271-e4535e1ed02e)

**Comment by Widge-5** [comment]
Thanks @flyinghead .  You are absolutely correct.
This is a completely fresh installation and I didn't realise the `Purupuru Pack/Vibration Pack setting` had an impact, or that its default state is `On` (should it be?).  Disabling the setting has resolved the issue.
Thank you for your quick response.
