### ISSUE TITLE
Touch buttons not working on Arcade Mode (Standalone build)

### ISSUE THREAD

**Issue by Raypuia** [flyinghead/flycast#137]
In Arcade Mode, Flycast seems to only receive input from a USB/Bluetooth gamepad and not from the touch buttons.

I don't know if this is intentional or a bug, but this basically makes unplayable NAOMI/Atomiswave games without a gamepad

**Comment by Raypuia** [comment]
I checked again and in Virtual On touch buttons works (however it needs two virtual sticks to be playable), but in others buttons are useless

**Comment by flyinghead** [comment]
The virtual Android gamepad isn't ideal for arcade games. But which game(s) do you have issues with buttons?

**Comment by Raypuia** [comment]
Mostly with Power Stone and Crazy Taxi (this one is basically unplayable because of the brake pedal being mapped to the YAxis of the analog stick).

And the need of a coin button (i needed to use RetroArch to force Free Play on the EEPROM of the games, and use them on the standalone build)

**Comment by flyinghead** [comment]
The lack of a coin button is indeed an issue.

However, Crazy Taxi should be playable: wheel is mapped to the joystick, accelerate to Right trigger and brake to Left trigger. Make sure to use a Mame rom to have correct controls.

Power Stone uses the DPad and 3 buttons (A, B, X) so it should be playable as well.

**Comment by Raypuia** [comment]
I'm using MAME roms (0.220 ones)
Flycast should have options to map both virtual and physical buttons like MAME for Arcade Mode.

**Comment by flyinghead** [comment]
In the latest build, Naomi/AW service buttons can be pressed with the on-screen gamepad:
RT + A -> D (Coin)
RT + B -> C (Service)
RT + X -> Z (Test)
