### ISSUE TITLE
Rumble not working on Xbox One S Controller

### ISSUE THREAD

**Issue by Sandsteamer** [flyinghead/flycast#1376]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: PC/Windows

Github hash: [593b320], [07d6ca6], [552e5b7], [78a874d]

Hardware: i7-6700, GTX1070, 16gb-2133Mhz

**_Description of the Issue_**

Uhm, I don't have rumble and it's activated on the game and the emulator. I tested several more versions that the ones mentioned above but with no avail. 

**_Debugging Steps Tested_**

Don't know much, tried different versions, tried an old 360 controller too.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Did you add a Purupuru to the virtual Dreamcast controller? This is the Dreamcast vibration pack.

**Comment by Sandsteamer** [comment]
> Did you add a Purupuru to the virtual Dreamcast controller? This is the Dreamcast vibration pack.

Where do I do that? ._.

**Comment by Sandsteamer** [comment]
I found it... I'm so so sorry for wasting your time, I couldn't be more dumb. Thank you very much.
