### ISSUE TITLE
10 fps cap on android.

### ISSUE THREAD

**Issue by nexus382** [flyinghead/flycast#1380]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  retroid pocket pro 4

Github hash: 

Hardware: 

**_Description of the Issue_**
All my games run at a capped 10fps... tried ever option for region..... and just about every option I could think is related to fps... v sync... resolution ...and it's not a performance thing... I hit fast fwd... hits over 60 fps easy in 4k rendering... looks so smooth... but for some reason something is hard limiting my fps to 10 using the built in counter.
Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * tried every region.
  * tried every video connection type.
  * both cpu modes
  * all three widescreen settings in every combination.
  * seems I only get the 10 fps cap to go away only when the setting FULL FRAMEBUFFER EMULATION is on... but this makes the img jumpy.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by nexus382** [comment]
EDIT..... turning the above setting on and off over and over seems to have gotten me to perfect img... at 15 fps... not 10.... some times goes  back to ten... but with the setting on the picture is blinky and shakes

**Comment by nexus382** [comment]
Ok so in sonic adventure.... everything's at 15 fps.... except the menu shows 30 fps...again when speedup button is used it goes way over

**Comment by flyinghead** [comment]
Something is really wrong here.
Is this a new install?
Which version of Flycast?
Can you delete everything and restart with default settings?

**Comment by nexus382** [comment]
It was the latest master for android... then I tried latest dev commit. Same issues. I'm gunna try a full reinstall now

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen if you need further assistance.
