### ISSUE TITLE
Sega Extreme Sports - skybox glitch

### ISSUE THREAD

**Issue by KamiLordus** [flyinghead/flycast#1381]
The skybox in the game is still very buggy. Black spots, artifacts, etc.
Many years ago, I remember someone opening a similar report on the libretro flycast website. I can't find it anywhere, so I'm opening it again because it's impossible to play like this. Such nasty skies spoil any enjoyment of the game. I hope this can be fixed.

![Sega Extreme Sports (Europe) (En,Fr,De,Es)-240203-002855](https://github.com/flyinghead/flycast/assets/123302593/770b18a9-c0cb-487e-ab6e-901cd06eae7f)

![Sega Extreme Sports (Europe) (En,Fr,De,Es)-240203-003129](https://github.com/flyinghead/flycast/assets/123302593/7198a1f1-ed3c-40aa-91fb-0c5f81efc6b4)

Retroarch 1.17
Flycast core latest
Windows 11
Rtx 3070 ti

**Comment by flyinghead** [comment]
You need to enable `Full Framebuffer Emulation` for the sun to be displayed correctly.

**Comment by KamiLordus** [comment]
Turning on Full Framebuffer Emulation fixed the sun, but the game runs much slower.
Unfortunately, the sky is still broken.
I am using GL Core video driver.

**Comment by flyinghead** [comment]
Can you post a new screenshot with the sky issues?

**Comment by KamiLordus** [comment]
This screenshot comes from the intro, which shows that half of the sky is invisible.

![Sega Extreme Sports (Europe) (En,Fr,De,Es)-240203-151947](https://github.com/flyinghead/flycast/assets/123302593/04734262-b1a8-48d8-9f7b-1362a05e8f26)

This screenshot is from the very beginning of the first competition (championship). A large black hole in the sky.
![Sega Extreme Sports (Europe) (En,Fr,De,Es)-240203-152037](https://github.com/flyinghead/flycast/assets/123302593/f34a046d-4eaf-4cc2-9ba7-38a08c7fbdb9)

I will also add that this is the Pal (Europe) version called Sega Extreme Sports. The game is in chd format.
I will try to test the ntsc (USA) version called Xtreme Sport and let you know if it has the same problem.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by KamiLordus** [comment]
Has this fix already been implemented in flycast libretro? Because so far I don't see any difference.
However, I noticed something disturbing. Every flycast (libretro) build for windows fails. Could you check this?
https://git.libretro.com/libretro/flycast-upstream/-/pipelines?page=1&scope=all

**Comment by flyinghead** [comment]
it's also fixed on master (and thus on libretro) but their build system is failing. You'll have to wait until they fix it.

**Comment by KamiLordus** [comment]
Ok, thanks for the clarification.
