### ISSUE TITLE
Minor text revision in the graphical interface

### ISSUE THREAD

**Issue by dezraj** [flyinghead/flycast#1383]
Hello! I would like to suggest a minor text revision in the graphical interface.

- In-game menu "Exit" option: at first I thought this option would exit the program, but it actually closes the game. It would be clearer if it was renamed to something like "Exit game" or "Close game" or "Stop emulation", which is what most emulators call such a function as far as I've noticed.

- Texture up-scaling in Video settings: the values are not very clear in this setting. Is 1 for 1x, 2 for 2x xBRZ and so on? If so, maybe the slider could show this information (the "x") or the tool tip could describe what those numbers actually mean.

I'm relatively new to flycast so I believe these little changes would also benefit other users coming to the emulator recently as well.

Thank you so much for your time and work.

**Comment by flyinghead** [comment]
Done on the `dev` branch

**Comment by dezraj** [comment]
> Done on the `dev` branch

Thank you @flyinghead for accepting the suggestion and apologies for the late reply.

I just checked it in the dev branch it is looking good.

Just to be sure, the 1x setting in texture upscaling means no use of xBRZ algorithm at all, right?

Thank you again for your work.

**Comment by vkedwardli** [comment]
thank you for the suggestion

> the 1x setting in texture upscaling means no use of xBRZ algorithm at all, right?

yes, upscaling is enabled whenever the value is greater than 1
