### ISSUE TITLE
Sega SystemSP - Love and Berry: Dress Up and Dance! (1st-2nd Collection)

### ISSUE THREAD

**Issue by LoliJuicy** [flyinghead/flycast#1388]
There's an unusual black overlay bug that occurs in the demo attract mode, after the game logo appeared. Will post a screenshot later.

Tweaking the settings does not seem to change anything.

I'm not sure if it also appears in the 3rd-5th Collection.

**Comment by TheCoolPup** [comment]
what version of flycast are you using?

**Comment by LoliJuicy** [comment]
V.2.2, the latest version. Ah, I forgot to get a screenshot of the issue. I'll get to it when I have the time.

**Comment by TheCoolPup** [comment]
try using one of the latest master builds on the ci builds page, i remember having a bug like that. https://flyinghead.github.io/flycast-builds/

**Comment by LoliJuicy** [comment]
The issue doesn't seems to be fixed.
![Screenshot 2024-02-09 14-54-10](https://github.com/flyinghead/flycast/assets/115810282/76c947f2-104d-4f45-8123-26287bf16f32)

**Comment by flyinghead** [comment]
This game requires `Video > Render to Texture > Copy to VRAM` to be enabled.

**Comment by LoliJuicy** [comment]
Thanks. I would also like to add on two issues related to the game.

1. The card reader function doesn't support spaces. Some barcodes have spaces in them like OHRU4 I-QBJ or OHRU4 I.CCJ.

2. There's also a Chinese version of Love and Berry 3. Game can run but results in a RFID error. If you need a ROM, I could send a email if available.

**Comment by flyinghead** [comment]
The space character issue should be fixed in the next master build. The Copy to VRAM option is also automatically enabled for lovebery and lovebero.

The chinese edition of love & berry 3 uses a totally different RFID card reader, that isn't emulated at the moment.
