### ISSUE TITLE
Lightgun coordinates incorrect when using screen stretching (Ranger Mission)

### ISSUE THREAD

**Issue by jvhellraiser** [flyinghead/flycast#139]
![Screenshot 2020-12-07 224422](https://user-images.githubusercontent.com/16488761/101431716-cb059280-38dd-11eb-93d4-969c3539cf33.jpg)

**Comment by flyinghead** [comment]
Make sure not to switch VGA/non-VGA after calibrating. (Atomiswave games usually use VGA)

Here is a screenshot of the calibration screen (after caliibration). You can see that the crosshair is pretty close to my mouse pointer.
![image](https://user-images.githubusercontent.com/16261910/101505652-dd7edb00-3974-11eb-838e-4f7abacf6dad.png)

**Comment by flyinghead** [comment]
Are you using horizontal stretching? or scaling?

**Comment by jvhellraiser** [comment]
> 
> 
> Are you using horizontal stretching? or scaling?

Yes i am usually i have it in 138 or 139

**Comment by flyinghead** [comment]
Horizontal stretching is the issue here, because it's not taken into account for the computation of mouse coordinates.

Another issue is when the screen/window is taller than 4:3, with black bars on top and bottom. This case also leads to incorrect mouse coordinates.

Set Horizontal Stretching to 100 as a workaround.

**Comment by flyinghead** [comment]
latest build should fix the problem with horizontal stretching, rotation, etc.

**Comment by jvhellraiser** [comment]
> 
> 
> latest build should fix the problem with horizontal stretching, rotation, etc.

I just tested it, Now the calibration is working in Ranger Mission & in Sports Shooting USA
like the are suppose too, thanks for the hard work man that did the difference...

**Comment by flyinghead** [comment]
Fixed
