### ISSUE TITLE
Feature suggestion. Add option to scale game art.

### ISSUE THREAD

**Issue by SegaGameBoyStation** [flyinghead/flycast#1392]
**Is your feature request related to a problem? Please describe.**
Yes, on HiDPI screens with a large library it is really hard to see the game art

**Describe the solution you'd like**
Add a slider in the interface that scales the game art similar to how Duckstation and PCSX2 do.

**Describe alternatives you've considered**
I guess an option for a HiDPI UI would be an alternative.

**Comment by flyinghead** [comment]
![image](https://github.com/flyinghead/flycast/assets/16261910/13cb24c7-8205-427a-be43-c53a0f743c71)
 Perhaps you should upgrade...
