### ISSUE TITLE
new controls ui and menu gui

### ISSUE THREAD

**Issue by YashSoPro** [flyinghead/flycast#1394]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
So basically the controls gui i want you guys to make it better and easier the recast controls gui looks trash it's also make the menu interface easy like redream( i have a gui i will upload it here)

**Describe alternatives you've considered**
Use better ui

**Additional context**
Yes a ui pic for a idea i know its not perfect because im not an artist bruh
![buttons](https://github.com/flyinghead/flycast/assets/105553471/f7f7d81b-fa83-46e3-ade7-1c80d1716973)

**Comment by flyinghead** [comment]
> gui looks trash

Thank you for your kind words. This is very encouraging… 
If you want to make the UI better, the source code is here. I’ll wait for your changes.
