### ISSUE TITLE
[Switch] Flycast wont boot games

### ISSUE THREAD

**Issue by CommicKick69ing** [flyinghead/flycast#1395]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Atmosphere

Github hash: v2.2

Hardware: Nintendo Switch

**_Description of the Issue_**

When selecting a game the game will not load, the bar will not make any progress

**_Debugging Steps Tested_**

*I've tried different dreamcast bios files and placing the game files in different file location, but fuck all happened just infite loading screen

**Comment by flyinghead** [comment]
Try the latest master build. There are been some Switch changes recently.
https://flyinghead.github.io/flycast-builds/

**Comment by CommicKick69ing** [comment]
> Try the latest master build. There are been some Switch changes recently. https://flyinghead.github.io/flycast-builds/

That build also did not work. I don't know why, I did'nt change the defualt setting accept adding the folder with the roms and two working bios files

**Comment by flyinghead** [comment]
Then there is likely an issue with your custom firmware. Try upgrading Atmosphere to the latest version?

**Comment by flyinghead** [comment]
Assuming this is fixed
