### ISSUE TITLE
Overclocking the SH4 CPU does not do anything

### ISSUE THREAD

**Issue by PoloniumRain** [flyinghead/flycast#1398]
OS / Hardware: 

Windows 10  /  AMD Threadripper 3960X + Nvidia RTX 3080

**_Description of the Issue_**

I'm not sure if this is a bug or not, but overclocking the SH4 CPU doesn't seem to do anything? I've tried this with both the RetroArch core and the latest February build of standalone Flycast with multiple games. 100MHz or 500MHz makes no difference (btw standalone Flycast only goes up to 300MHz, is this an oversight?). Everything runs fine even when set to 100MHz, so Quake III with a 60fps cheat applied will still hit a constant 60fps. 

Obviously this is inaccurate compared to real hardware, but if it is intentional then what is the point of the overclocking option?

Tested with DX11 and Vulkan.

**Comment by Nejsplitter1** [comment]
maybe the reason is because of this commit: https://github.com/flyinghead/flycast/commit/e894d4df5c71d19196421b01589c0b4b623dd9e3 which already kind of acts like an overclock, so adjusting the oc values might not seem to do much in some games

**Comment by flyinghead** [comment]
Underclocking Quake 3 (without 60 fps cheat) does reduce the frame rate from 30 to 24 (although it depends on the scene).
However changes in over/underclocking do not take effect immediately if the game is already started. Loading a savestate will take the change into account. Another option is to switch to Interpreter then back to Dynarec.

**Comment by flyinghead** [comment]
Flycast saves cheats in a retroarch-compatible .cht file format. So you can just use this file.
