### ISSUE TITLE
Test Drive Le Mans crashes after 24hr race unable to load fixed-camera objects

### ISSUE THREAD

**Issue by glyner** [flyinghead/flycast#1399]
Hardware: AYN ODIN 2 - Qualcomm Snapdragon 8 Gen 2, running Android 13

After completing a 24hr race a short cut scene is played that fades into a crash with the following error:
FATAL ERROR
Failed to load fixed-camera objects <tracks/lemans\lemans>

Attached save state from a few second before race finishes, will need to race across the line. Save state compressed to zip file to allow upload

Managed to reproduce error with 3 different GDI images and one CDI image
[Test Drive Le Mans.zip](https://github.com/flyinghead/flycast/files/14288525/Test.Drive.Le.Mans.zip)

**Comment by flyinghead** [comment]
Which media did you use to create this savestate?
Is it from a "known good" GDI image like Redump or TOSEC?
Also can you confirm it is the US/NTSC edition?

The savestate you uploaded crashes with the TOSEC US edition.
However I did a full race from scratch and it ended normally without any crash.

**Comment by flyinghead** [comment]
No answer hence closing.
