### ISSUE TITLE
IA retroarch not read viewport 

### ISSUE THREAD

**Issue by PCdasala** [flyinghead/flycast#1404]
Platform / OS / Hardware: flycast retroarch

Github hash: 

Hardware: rog ally

Does anyone know why the AI is not translating only on the Dreamcast? This message appears instead of "could not read viewport"

**_Screenshots_**
![IMG_3905](https://github.com/flyinghead/flycast/assets/127679528/8383a468-2808-4cd3-acfd-3ba2023ade0e)

**Comment by flyinghead** [comment]
I don't know how the retroarch AI works but this could be due to flycast being GPU hardware accelerated.

**Comment by PCdasala** [comment]
> I don't know how the retroarch AI works but this could be due to flycast being GPU hardware accelerated.

So my friend, the problem is that several people can, I imagine there is something that is preventing the AI from seeing the subtitles but I don't know what it is

**Comment by flyinghead** [comment]
This is a RetroArch issue. See #1418 and #1419.
