### ISSUE TITLE
Force Five hangs after character selection on vs. screen

### ISSUE THREAD

**Issue by jvhellraiser** [flyinghead/flycast#141]
I have notice Flycast can actually play decrypted roms (just found out)
and had to try some since the games wont work for me on any other emulator
manage to load Kenju successfully  no error or any freeze is just awesome Flycast surprise
me even more every time, In Force Five the game freezes at the Vs screen is there anyway
to get this game to go further it wont freeze on demul as i hear..

Kenju on Flycast
![Screenshot 2020-12-10 134132](https://user-images.githubusercontent.com/16488761/101809171-9a944300-3aed-11eb-9bc1-342cd8cf3106.jpg)
![Screenshot 2020-12-10 134158](https://user-images.githubusercontent.com/16488761/101809180-9d8f3380-3aed-11eb-96be-dce08a42665e.jpg)

Force Five on Flycast
![Screenshot 2020-12-10 134045](https://user-images.githubusercontent.com/16488761/101809231-ab44b900-3aed-11eb-8441-e2a5a4f58f33.jpg)

Vs screen where it Freezes
![Screenshot 2020-12-10 134005](https://user-images.githubusercontent.com/16488761/101809266-b7c91180-3aed-11eb-900b-8449dea27398.jpg)

I am pretty sure you can fix the freeze issue
thought i am just testing my luck...lol
i hope you can and if you need "anything" ask...

**Comment by flyinghead** [comment]
To get past the Force Five freeze, switch to Interpreter before selecting the character, then switch back to Dynarec when the battle starts.

**Comment by jvhellraiser** [comment]
> 
> 
> To get past the Force Five freeze, switch to Interpreter before selecting the character, then switch back to Dynarec when the battle starts.

That is a really weird issue right there but  i guess it works but changing it every time is annoying
but at least i can play it for a bit until something to fully fix it is found thanks....enjoying the games 
thanks to Flycast & the developers...

**Comment by jvhellraiser** [comment]
Any news of fixes coming out to fix the freeze on Force Five or its still a mystery?

**Comment by fabjef** [comment]
I'm also waiting to fix force five in flycast. Can anyone please fix and debug it ?

**Comment by flyinghead** [comment]
Still a mystery

**Comment by BroKill** [comment]
It freezes with last Demul too if you press buttons between a match and the other. If you don't presso nothing it's ok.

Didn't try it with Flycast.

**Comment by fabjef** [comment]
Update please

**Comment by jvhellraiser** [comment]
I just update to the latest build and it still freezes once it reaches the Vs screen..

**Comment by fabjef** [comment]
any update ?

**Comment by flyinghead** [comment]
@fabjef This is not a discussion forum. Only post information relevant to the resolution of this issue. Thanks

**Comment by kihato** [comment]
In the final stage, if you lose and continue, the BGM will disappear, and regardless of whether you win or lose, when the winner is displayed, the game will freeze 100%.
This seems to be related to the background music disappearing.

BGM may disappear even if you lower the SH4 Clock value to 100, and it seems that this cannot be reliably avoided unless you switch to the interpreter.
[Force Five.zip](https://github.com/flyinghead/flycast/files/13669777/Force.Five.zip)

**Comment by flyinghead** [comment]
It seems to happen much less frequently on the dev branch, presumable a consequence of 7cc77b10ed5e59db42947128d8715ff415bbe8d7. However it still happens randomly.

**Comment by flyinghead** [comment]
Lowering the rom dma transfer rate fixes all issues, including the final boss one.
See latest dev build.

**Comment by BroKill** [comment]
So, is it fixed on dev? ( finally )

**Comment by flyinghead** [comment]
If I'm not working fast enough, don't hesitate to send your own bug fixes.

**Comment by JustSimon23** [comment]
> Lowering the rom dma transfer rate fixes all issues, including the final boss one. See latest dev build.

Dear dev, please I begging, can you describe how actually I should do that? I tried, to find this DMA Transfer but I just can't, please tell me how can I EVEN, enter in these options & lower these rate?

**Comment by flyinghead** [comment]
You have nothing to do. Just download the latest `dev` build.

**Comment by JustSimon23** [comment]
> You have nothing to do. Just download the latest `dev` build.

Okay, I'll try.

**Comment by JustSimon23** [comment]
> You have nothing to do. Just download the latest `dev` build.

Sigh, still crash, I downloaded latest Nightly version of it and still the same? What I do wrong?

**Comment by flyinghead** [comment]
which version number/hash?

**Comment by JustSimon23** [comment]
> which version number/hash?

Not sure, I just push Nightlty version button to download it.

**Comment by JustSimon23** [comment]
> which version number/hash?

Okay wait, I got it, I took the wrong buid, I check it on stable version and now its works, thank you I guess.

**Comment by JustSimon23** [comment]
> which version number/hash?

Sigh, no, still the saame, had one battle and after I won, its crashed or froze no the victory pose, and again, freeze on versus screen

**Comment by BroKill** [comment]
There is no nightly version, just master and dev so i don't know what you are testing here.
Dev said you have toi use latest dev and its not 1.16 but 2.2-etc etc and works great with Force Five, already tested

**Comment by JustSimon23** [comment]
> There is no nightly version, just master and dev so i don't know what you are testing here. Dev said you have to use latest dev and its not 1.16 but 2.2-etc etc and works great with Force Five, already tested
> 
> Grab dev build from here : https://flyinghead.github.io/flycast-builds/

Ooooh, I guess there was misunderstanding from my side, I mistook emulator with flycast in retroarch, my bad, but thank you for the good oportunity finish this game normally, I couldn't beat damn mutant (one of final bosses) because of crash, beat him only after I changed the difficutly, but I want to beat that a**hole in fair fight, so thank you.

**Comment by BroKill** [comment]
For some reason the RetroArch core is still not updated with DMA fix so I suggest to do a manual installation like I did .
Go here https://github.com/flyinghead/flycast/actions/runs/7421450032, ( you need a github account ), download the archive named **flycast-libretro-x86_64-w64-mingw32** , unpack it and put flycast.dll in the RetroArch cores folder. Don't update via RetroArch because of what I said before.

Enjoy

**Comment by JustSimon23** [comment]
> For some reason the RetroArch core is still not updated with DMA fix so I suggest to do a manual installation like I did . Go here https://github.com/flyinghead/flycast/actions/runs/7421450032, ( you need a github account ), download the archive named **flycast-libretro-x86_64-w64-mingw32** , unpack it and put flycast.dll in the RetroArch cores folder. Don't update via RetroArch because of what I said before.
> 
> Enjoy

Thank you very much, you actually helped me out. Finally I can beat this game completelly. Good day to you. 

Thank you very much,
