### ISSUE TITLE
Derby Owners Club World Edition - Cannot set master / slave 

### ISSUE THREAD

**Issue by senion34** [flyinghead/flycast#1411]
Hi, I cannot get the master/slave working on Flycast for Derby Owners Club World Edition
It only runs in slave mode no matter what I try I attempted to set it As server but the game still runs in slave mode.
Also, can the slaves be other machines in the same lan?

Thanks in advance.

**Comment by senion34** [comment]
![image](https://github.com/flyinghead/flycast/assets/62831203/a5e0cd09-992e-47cb-b8c5-722911665793)
![image](https://github.com/flyinghead/flycast/assets/62831203/0b75b2fd-2ec4-42d6-a386-981f53ecc0e2)

**Comment by flyinghead** [comment]
This game isn't supported

**Comment by senion34** [comment]
Ok thanks

**Comment by Tom-Neverwinter** [comment]
after a little digging I think there is a bit in the rom that needs to be set or a dip switch on the hardware to make it a server.
