### ISSUE TITLE
Stuttering / micro freezing on android in quest 3

### ISSUE THREAD

**Issue by Qcenaman** [flyinghead/flycast#1412]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Quest 3, Android

Github hash: 

Hardware: 

**_Description of the Issue_**

Flycast works well on my other android devices.
Today I decided to install it on my Quest 3 headset and every game I try to boot works and seems to be doing  well at 60fps.
HOWEVER, for every 3 seconds there is a micro freeze of half a second. It's periodic and the timing doesn't change.

I do not understand why this happens. The hardware and emulator can clearly handle the games very well, so I do not understand why this happens and it doesn't make sense. 

I have tried changing every setting in the menus, literally everything! Nothing changes.

**_Debugging Steps Tested_**

Tried every setting combo and nothing changes.
Happens in every game I have tried.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This has been reported before. See #1329.
No idea what the cause is and no known workaround.
