### ISSUE TITLE
Nearest neighbour screen upscaling?

### ISSUE THREAD

**Issue by Kurriochi** [flyinghead/flycast#1415]
If I'm trying to run a Dreamcast game at 640x480 on a larger screen, I'd like to be able to use nearest neighbour upscaling for my screen so I can have a sharper image. If someone has a 1440p or monitor, a 640x480 integer upscales to 1440p.

**Comment by smbhax** [comment]
Have you set "Texture Filtering" on Flycast's "Video" tab to "Force Nearest-Neighbor"? It should come out perfectly sharp. And if you're running at a screen resolution above 640x480, many games will also benefit from combining Force Nearest-Neighbor with raising the "Internal Resolution" setting.

**Comment by SpelzR2** [comment]
Texture filtering hasn't anything to do with screen scaling. I second that request by Kurriochi. Emulators like Duckstation or PCSX2 offer different scaling methods (nearest, bilinear, sharp bilinear). Besides nearest upscaling I think there should be an sharp-bilinear scaling option too (to reduce uneven pixels without integer scaling). Here are some examples, taken in native resolution:

Flycast 2.3 (standard):
![linear](https://github.com/flyinghead/flycast/assets/174040074/b6d6df6b-2bd1-4587-855f-56ee79eb0173)

nearest scaling:
![nearest](https://github.com/flyinghead/flycast/assets/174040074/270be9ff-a333-4f03-9be2-9ac439786e21)

sharp bilinear scaling:
![sharp bilinear](https://github.com/flyinghead/flycast/assets/174040074/c6140de2-30d2-48db-966c-ab8f0e380201)

**Comment by flyinghead** [comment]
You can use "Force Nearest-Neighbor" if you like sharp pixels. I don't plan on adding more options.

**Comment by Immersion95** [comment]
Texture filtering isn't the same as screen scaling. Integer is a must imo. At the moment you'll have to use RetroArch for that option. Standalone doesn't allow this unfortunately :(.

**Comment by flyinghead** [comment]
Fixed on the `dev` branch

**Comment by Windows98-1998** [comment]
> Fixed on the `dev` branch

For me it doesn't work :(
