### ISSUE TITLE
NHL2K2 menu rendering issues

### ISSUE THREAD

**Issue by bryanforbes** [flyinghead/flycast#1416]
Platform / OS / Hardware: Apple M1 Pro / macOS Sonoma 14.3

Github hash: 7029e16

Hardware: 

**_Description of the Issue_**

The "Team Select" menus in NHL2K2 do not render the team helmets or team jerseys. The textures also do not dump when "Dump Textures" is on.

**_Debugging Steps Tested_**

  * At the NHL2K2 main menu, select "Exhibition" (this gets you to the team helmet menu)
  * Press L and R (the helmets never change)
  * Press start (this gets you to the team jersey menu)
  * Press A and X (the jerseys never change)

**_Logs Gathered_**

None

**_Screenshots_**

<img width="752" alt="image" src="https://github.com/flyinghead/flycast/assets/204106/cac9252d-aaeb-493e-88b6-a81bebb921cc">
<img width="752" alt="image" src="https://github.com/flyinghead/flycast/assets/204106/5d01b865-f7a2-4b8f-be89-6b8d9d7ee8f9">

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build.

I had to scale down depth significantly to fix the rendering of the helmet. This may cause depth issues in game. Let me know if you spot any regression.

**Comment by kihato** [comment]
The swirl animation will not be visible if you choose anything other than per-pixel in OpenGL or DX11.
Vulkan is unaffected.

![NHL2K2_boot](https://github.com/flyinghead/flycast/assets/14366233/eed7ce84-31cf-4126-bf13-057f781887e2)
