### ISSUE TITLE
[Libretro] AI service (translation) images are received upside down

### ISSUE THREAD

**Issue by Sanaki** [flyinghead/flycast#1419]
Platform / OS / Hardware: x86_64 Linux (Garuda/Arch)

Github hash: 44fa364f36c43bed19b055096600f075c656f78c

Hardware: GTX 1060 6GB

**_Description of the Issue_**

Images received by the AI translation service are flipped vertically, preventing successful translation.

**_Debugging Steps Tested_**

  * Set up RetroArch AI service with ztranslate and bind a key to translate
  * Start any game in the Flycast core (using glcore driver to sidestep #1418)
  * Press the translation key
  * Check ztranslate website for the image received

**_Logs Gathered_**

**_Screenshots_**

![image2](https://github.com/flyinghead/flycast/assets/1374333/4280bc3f-d377-4804-a280-561b02a5f4e6)
![Screenshot_20240223](https://github.com/flyinghead/flycast/assets/1374333/4c6c2eb1-e135-4c3b-b715-37b6d65eae72)

**Comment by flyinghead** [comment]
The image presented by Flycast to RetroArch is correct (not upside down) and screenshots also have the correct orientation.
So it doesn't look like a Flycast issue, nor something that can be fixed in the core.

**Comment by bslenul** [comment]
Hm yeah, just tested with a PS1 Japanese game with Beetle PSX HW and SwanStation cores and in both cases the translation server received the screenshot upside-down. With PCSX ReARMed or Beetle PSX non-HW (SW renderer) or Beetle PSX non-HW no issue, so probably a RetroArch issue with how it sends HW renderer screenshots 🤔

**Comment by PCdasala** [comment]
just to complement, when I use dx11 or another dx the message is "clould not read viewport", with vulcan a meaningless translation attempt occurs and the game continues to bug and close. This only happens on dreamcast and ps2
![Uploading IMG_3905.jpeg…]()

**Comment by Sanaki** [comment]
Given bslenul verifying this is a RetroArch issue, I'm closing this one.
