### ISSUE TITLE
request about SSAA i think

### ISSUE THREAD

**Issue by LuisFellp** [flyinghead/flycast#142]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
android, 10, exynos 7885

Github hash: 
flycast-debug-d960f8e.apk

could you add the option to disable SSAA? it's very heavy even on x1 and it kills the resolution when below 0.9

**Comment by flyinghead** [comment]
SSAA is completely disabled when set to x1. Even if SSAA was removed, it wouldn't be faster than what it is now with x1.

**Comment by LuisFellp** [comment]
then there's something weird happening, because when i use flycast apk it lags, but when i use libretro core it doesn't and both seems to be running at same resolution

**Comment by flyinghead** [comment]
Can you explain "it lags" ? Is it slow fps? bad audio? other?

What are your settings?

**Comment by vkedwardli** [comment]
Could be due to libretro is always using Dreamcast resolution (640 x 480) while Flycast is using device's native resolution?

**Comment by flyinghead** [comment]
Some Android devices with high-resolution screens have a hard time rendering at native resolution. Settings SSAA/Scaling to 0.5 or lower does help in this case.

**Comment by flyinghead** [comment]
Native (640x480) and Half resolutions can now be selected
