### ISSUE TITLE
Shakatto Tambourine Arcade (All 3) do not register 2nd player analog input.

### ISSUE THREAD

**Issue by WarpedPolygon** [flyinghead/flycast#1420]
Standalone Version.

The 2nd player will register every input apart from the analog position of the tambourine.

2 Players is set in System Assignments and I checked every other input and control slot positions to make sure it wasn't hiding.

**Comment by flyinghead** [comment]
Fixed on the dev branch.
I also remapped some buttons so that DPad up and down work as such and `knock` is button 3.

**Comment by WarpedPolygon** [comment]
Boom, and the circle is complete. Thanks mate!

**Comment by WarpedPolygon** [comment]
Closing
