### ISSUE TITLE
Toy Story 2 graphics error

### ISSUE THREAD

**Issue by dantedevo** [flyinghead/flycast#1423]
I'm having a graphics problem with the game Toy Story 2 in which the graphics of the game (some) disappear and when moving the camera to the previous position reappear, I searched the internet for the problem but it says that you have to activate the Video option "Per Pixel" in vulkan as OpenGL is solved, but the game is very slow. I'm playing the game on mobile, I don't know if the same thing happens on PC (Redream doesn't happen the same).

![Screenshot_20240224-181110~2](https://github.com/flyinghead/flycast/assets/95579204/4db54cca-2011-485d-b4ce-38793623f88e)
![Screenshot_20240224-181012~2](https://github.com/flyinghead/flycast/assets/95579204/72a65771-7c59-4708-ade9-f73ae151ca26)
![Screenshot_20240223-180727~2](https://github.com/flyinghead/flycast/assets/95579204/4c02e384-1a0d-4837-9b47-c112fffe1e48)
![Screenshot_20240223-180608~2](https://github.com/flyinghead/flycast/assets/95579204/1e3e00f0-5406-4406-8fe3-24bb4737885b)
![Screenshot_20240221-193531~2](https://github.com/flyinghead/flycast/assets/95579204/1068847d-2dd0-41c7-9bd1-ec08dbdf4155)
![Screenshot_20240221-193434~2](https://github.com/flyinghead/flycast/assets/95579204/72dc2be7-ff01-44d6-96af-5b81989edb7f)

**Comment by flyinghead** [comment]
per pixel is needed for this game
