### ISSUE TITLE
Tokyo Xtreme Racer - Flickering headlights

### ISSUE THREAD

**Issue by Blackbird88** [flyinghead/flycast#1424]
Platform / OS / Hardware: 
Windows 11 Pro x64

Github hash: 67c4e62c5

Hardware: 
Intel Core i7-10700K
Nvidia GeForce RTX 3070 (551.23)

**_Description of the Issue_**

Headlights of the cars flicker constantly. I have tried every setting I could think of and it keeps happening.

**_Logs Gathered_**

**_Screenshots_**

Flycast

https://github.com/flyinghead/flycast/assets/4414625/f8356d34-1578-4dbf-9e1a-e8ab760bcc68

Real HW
https://youtu.be/QWnvKd4wjhU?si=aUnRguLx25G8qJOe&t=137

**Comment by flyinghead** [comment]
I checked on original hardware and the flickering of headlights happens in both NTSC/480i and VGA/480p modes.

**Comment by Blackbird88** [comment]
Interesting. That video I posted is pre-release footage then I guess.
