### ISSUE TITLE
[Xbox Series] Flycast stuttering a lot when game is on external SSD drive

### ISSUE THREAD

**Issue by BTr-RJ** [flyinghead/flycast#1425]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Xbox Series S

Github hash: 

Hardware: Xbox Series S

**_Description of the Issue_**

Flycast is stuttering a lot, in all games i tested (Tennis 2k2, Sonic Adventure 2, Daytona USA) even using native resolution. Tried both standalone and Retroarch's libretro core. Same problem. I´m using more demanding emulators (xbsx2 and dolphin) that do not have this issue.
Tried commits 67c4e62 and ff91d11

**_Debugging Steps Tested_**

**_Logs Gathered_**

```

**_Screenshots_**

**Comment by flyinghead** [comment]
Nobody seems to be having this issue on Series S or X.
Check that Flycast has been deployed as a "Game" and not an "App" (in the DevMode app list).
Delete `emu.cfg` to start with default settings.

**Comment by BTr-RJ** [comment]
> Nobody seems to be having this issue on Series S or X. Check that Flycast has been deployed as a "Game" and not an "App" (in the DevMode app list). Delete `emu.cfg` to start with default settings.

It is deployed as "Game" already like all other emulators i have installed. It had been about 3-4 months since I last messed with emulation on Xbox, and I decided to come back now. I remember there were no stutters before.

I have deleted emu.cfg, everything to default and still stuttering a lot, microstutters that ruins the experience.

I can make a video if it helps. Like i said, others Emulators, even more demanding are running fine

**Comment by BTr-RJ** [comment]
Testing further. I transferred some games to Xbox's internal SSD and apparently the stutters disappeared. I was testing before using my USB 3.0 external hard drive with the games. But still, it doesn't make sense for this hard drive to be the source of the problem, as I also have much larger PS2 and Gamecube/Wii games on it that are not causing stutters in their respective emulators

**Comment by flyinghead** [comment]
A user reported a similar issue when using an external USB SSD hard drive. He had no issue with a cheap 32 GB USB flash drive.

**Comment by BTr-RJ** [comment]
> A user reported a similar issue when using an external USB SSD hard drive. He had no issue with a cheap 32 GB USB flash drive.

I will try later with a flash drive, but it still does not make any sense...a slow drive performs better than a faster

**Comment by BTr-RJ** [comment]
Just tested with a slow 16gigs usb 2.0 SanDisk usb flash drive using a hub and there was no stutter. My USB 3.0 external drive is still stuttering only in Flycast. Any explanation to this?

**Comment by flyinghead** [comment]
No, I don't have any explanation. I checked if there was any unexpected disk access when a game is running and there isn't any.
Flycast keeps the .CHD and cue/gdi track files open but only reads from them when it needs to.
Nothing else.
