### ISSUE TITLE
Unable to assign keyboard controls on Flycast

### ISSUE THREAD

**Issue by Zafuul** [flyinghead/flycast#143]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: PC

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here 
I am unable to assign in particular the coin and start button,  sometimes the entire keyboard don't work

**_Debugging Steps Tested_**
I tryed to change multiple times the controlls, but work only on the controller

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
More information is needed: OS, flycast version
Do the standard keyboard bindings work in games?
Can you navigate the UI with the keyboard?
Is it only when changing keyboard bindings?
What happens when you try to bind a button?
