### ISSUE TITLE
Almost all games default to Korea region is use "Default" for emulator region setting

### ISSUE THREAD

**Issue by EmuShredder** [flyinghead/flycast#1437]
If you set the region to "Default" in the emulator under general settings, most games will end up Korea region.  Many others are hard locked to the wrong region (greyed out when running the game).

NAOMI
| romset     | Default in flycast                                                                             |
| ---------- | ---------------------------------------------------------------------------------------------- |
| 18wheelr   |     KOREA
| 18wheelro  |     KOREA
| 18wheelrt  |     KOREA
| 18wheels   |     KOREA
| 18wheelu   |     KOREA
| alienfnt   |     KOREA
| alienfnta  |     KOREA
| alpilot    |     EXPORT LOCKED (title in flycast clearly reads WORLD)
| alpilotj   |     EXPORT LOCKED (title in flycast clearly reads JAPAN)
| anpanman2  |     JAPAN LOCKED
| anpanman2a |     JAPAN LOCKED
| asndynmt   |     USA LOCKED
| asndynmto  |     USA LOCKED
| ausfache   |     JAPAN LOCKED
| azumanga   |     KOREA
| bdrdown    |     KOREA
| capsnk     |     KOREA
| capsnka    |     KOREA
| capsnkb    |     KOREA
| cfield     |     JAPAN LOCKED
| chocomk    |     KOREA
| cleoftp    |     KOREA
| confmiss   |     KOREA
| crackndj   |     KOREA
| crakndj2   |     JAPAN LOCKED
| crzytaxi   |     JAPAN
| csmash     |     KOREA
| csmasho    |     KOREA
| cspike     |     KOREA
| cvs2       |     KOREA (title in flycast clearly reads USA)
| cvs2mf     |     KOREA (title in flycast clearly reads JAPAN)
| cvsgd      |     JAPAN LOCKED
| deathcox   |     KOREA (title in flycast clearly reads USA)
| deathcoxj  |     KOREA (title in flycast clearly reads JAPAN)
| deathcoxo  |     KOREA (title in flycast clearly reads JAPAN)
| derbyo2k   |     USA LOCKED (title in flycast clearly reads JAPAN)
| derbyoc    |     USA LOCKED (title in flycast clearly reads JAPAN)
| derbyoc2   |     USA LOCKED (title in flycast clearly reads JAPAN)
| derbyocw   |     USA LOCKED (title in flycast clearly reads WORLD EDITION)
| doa2       |     USA LOCKED
| doa2a      |     USA LOCKED
| doa2m      |     USA LOCKED
| dragntr3   |     KOREA
| drbyocwa   |     USA LOCKED (title in flycast clearly reads WORLD EDITION)
| drbyocwb   |     USA LOCKED (title in flycast clearly reads WORLD EDITION)
| drbyocwc   |     USA LOCKED (title in flycast clearly reads WORLD EDITION)
| drbyocwt   |     USA LOCKED (title in flycast clearly reads WORLD EDITION)
| dybb99     |     JAPAN LOCKED
| dybbnao    |     JAPAN LOCKED
| dygolf     |     KOREA
| dygolfp    |     KOREA
| f355       |     EXPORT LOCKED
| ggram2     |     JAPAN LOCKED
| ggx        |     KOREA
| ggxx       |     KOREA
| ggxxac     |     JAPAN LOCKED
| ggxxrl     |     JAPAN LOCKED
| ggxxrlo    |     JAPAN LOCKED
| ggxxsla    |     JAPAN LOCKED
| gram2000   |     KOREA
| gundmct    |     KOREA
| gundmgd    |     KOREA
| gundmxgd   |     USA LOCKED
| gunsur2    |     KOREA (title in flycast clearly reads WORLD)
| gunsur2j   |     KOREA (title in flycast clearly reads JAPAN)
| gwing2     |     KOREA
| hmgeo      |     KOREA
| hotd2      |     EXPORT LOCKED (title in flycast clearly reads USA)
| hotd2e     |     EXPORT LOCKED (correct here)
| hotd2o     |     EXPORT LOCKED
| hotd2p     |     EXPORT LOCKED
| ikaruga    |     KOREA
| illvelo    |     JAPAN LOCKED
| inunoos    |     EXPORT LOCKED
| jambo      |     KOREA
| jingystm   |     JAPAN LOCKED
| karous     |     JAPAN LOCKED
| keyboard   |     KOREA
| kick4csh   |     EXPORT LOCKED (correct here)
| kurucham   |     JAPAN LOCKED
| lupinsho   |     KOREA
| lupinshoo  |     KOREA
| luptype    |     KOREA
| mamonoro   |     JAPAN LOCKED
| manicpnc   |     USA LOCKED
| marstv     |     JAPAN LOCKED
| mazan      |     KOREA (title in flycast clearly reads WORLD)
| mazanj     |     KOREA (title in flycast clearly reads JAPAN)
| mazanu     |     KOREA (title in flycast clearly reads US)
| mbaa       |     JAPAN LOCKED
| mbaao      |     JAPAN LOCKED
| meltyb     |     JAPAN LOCKED
| meltybld   |     JAPAN LOCKED
| meltyblo   |     JAPAN LOCKED
| meltybo    |     JAPAN LOCKED
| mj1        |     JAPAN LOCKED
| moeru      |     JAPAN LOCKED
| mok        |     KOREA
| monkeyba   |     KOREA
| mushi2eo   |     USA LOCKED (title in flycast clearly reads WORLD)
| mushi2k4   |     JAPAN LOCKED (correct here)
| mushi2k5   |     JAPAN LOCKED (correct here)
| mushi2k61  |     JAPAN LOCKED (correct here)
| mushi2k62  |     JAPAN LOCKED (correct here)
| mushik2e   |     USA LOCKED (title in flycast clearly reads WORLD)
| mushik2k   |     KOREA (correct here, but should probably be locked in also)
| mushik4e   |     USA LOCKED (title in flycast clearly reads WORLD)
| mushikc    |     EXPORT LOCKED (correct here since is CHINA region)
| mushike    |     KOREA (title in flycast clearly reads WORLD)
| mushikeo   |     KOREA (title in flycast clearly reads WORLD)
| mushikep   |     KOREA
| mushikk    |     KOREA (correct here, but should probably be locked in also)
| mvsc2      |     KOREA (this is "EXPORT, KOREA" version so should be EXPORT as default)
| mvsc2u     |     KOREA (this should be USA LOCKED)
| ninjaslt   |     KOREA (title in flycast clearly reads WORLD)
| ninjaslta  |     KOREA
| ninjasltj  |     JAPAN (title in flycast clearly reads JAPAN)
| ninjasltu  |     KOREA (title in flycast clearly reads USA)
| ntvmys     |     JAPAN LOCKED
| oinori     |     KOREA
| otrigger   |     KOREA
| pokasuka   |     JAPAN LOCKED
| pstone     |     KOREA
| pstone2    |     KOREA
| psyvar2    |     JAPAN LOCKED
| puyoda     |     JAPAN LOCKED
| puyofev    |     KOREA (title in flycast clearly reads WORLD)
| puyofevj   |     JAPAN LOCKED (correct here)
| puyofevp   |     KOREA
| qmegamis   |     KOREA
| quizqgd    |     KOREA
| radirgy    |     JAPAN LOCKED
| radirgyn   |     JAPAN LOCKED
| radirgyo   |     JAPAN LOCKED
| rhytngk    |     JAPAN LOCKED
| ringout    |     KOREA
| ringouto   |     KOREA
| samba      |     KOREA
| samba2k    |     JAPAN LOCKED (correct here)
| sambaa     |     KOREA
| sambap     |     USA LOCKED (correct here)
| senko      |     JAPAN LOCKED
| senkosp    |     EXPORT LOCKED ???
| sfz3ugd    |     JAPAN LOCKED
| sgtetris   |     KOREA
| shaktam    |     KOREA
| shaktamb   |     KOREA
| shaktmsp   |     KOREA
| shangril   |     KOREA
| shikgam2   |     KOREA
| shootopl   |     KOREA
| shootpl    |     EXPORT LOCKED (this one can be EXPORT or JAPAN actually)
| shootplm   |     EXPORT LOCKED (this one can be EXPORT or JAPAN actually)
| shootplmp  |     EXPORT LOCKED (this one can be EXPORT or JAPAN actually)
| shors2k1   |     KOREA
| shors2k2   |     KOREA (reads EXPORT, TAIWAN)
| shors2k2l  |     KOREA
| shors2k2m  |     KOREA
| shors2k2s  |     KOREA
| shorse     |     KOREA
| shorsem    |     KOREA
| shorsep    |     KOREA
| shorsepb   |     KOREA
| shorsepm   |     KOREA
| shorsepr   |     KOREA
| shorseps   |     KOREA
| sl2007     |     JAPAN LOCKED
| slasho     |     KOREA
| smarinef   |     KOREA
| smlg99     |     KOREA
| spawn      |     KOREA
| spkrbtl    |     KOREA
| sprtjam    |     KOREA
| ss2005     |     JAPAN LOCKED
| ss2005o    |     JAPAN LOCKED
| sstrkfgt   |     KOREA
| sstrkfgta  |     KOREA
| starseek   |     KOREA
| suchie3    |     JAPAN LOCKED
| takoron    |     JAPAN LOCKED
| tduno      |     JAPAN LOCKED
| tduno2     |     JAPAN LOCKED
| tetkiwam   |     JAPAN LOCKED
| tokyobus   |     JAPAN LOCKED
| totd       |     KOREA
| totdo      |     KOREA
| toukon4    |     JAPAN LOCKED
| toyfight   |     KOREA
| trgheart   |     JAPAN LOCKED
| trghearto  |     JAPAN LOCKED
| trizeal    |     JAPAN LOCKED
| undefeat   |     JAPAN LOCKED
| usagiym    |     JAPAN LOCKED
| vathlete   |     KOREA
| virnba     |     KOREA (title in flycast clearly reads USA)
| virnbao    |     KOREA
| virnbap    |     KOREA
| vonot      |     KOREA
| vs2_2k     |     KOREA
| vs2_2ko    |     KOREA
| vtenis2c   |     KOREA
| vtennis    |     KOREA
| vtennis2   |     KOREA
| vtennisg   |     KOREA
| wccf116    |     JAPAN LOCKED
| wccf212e   |     EXPORT LOCKED (correct here)
| wccf234j   |     JAPAN LOCKED (correct here)
| wccf310j   |     JAPAN LOCKED
| wccf322e   |     KOREA (title in flycast clearly reads EXPORT)
| wccf331e   |     KOREA (title in flycast clearly reads EXPORT)
| wccf331j   |     JAPAN LOCKED (correct here)
| wccf341j   |     JAPAN LOCKED (correct here)
| wccf400j   |     JAPAN LOCKED (correct here)
| wccf420e   |     EXPORT LOCKED (correct here)
| wldkicks   |     KOREA (title in flycast clearly reads WORLD)
| wldkicksj  |     KOREA (title in flycast clearly reads JAPAN)
| wldkickspj |     KOREA (title in flycast clearly reads JAPAN)
| wldkickspw |     KOREA (title in flycast clearly reads WORLD)
| wldkicksu  |     KOREA (title in flycast clearly reads US)
| wrungp     |     KOREA
| wrungpo    |     KOREA (title in flycast clearly reads USA)
| wsbbgd     |     KOREA
| wwfroyal   |     KOREA
| zerogu2    |     KOREA
| zombrvn    |     KOREA
| zombrvno   |     KOREA
| zunou      |     JAPAN LOCKED

NAOMI 2
| romset     | Default in flycast                                                                             |
| ---------- | ---------------------------------------------------------------------------------------------- |
| beachspi   | KOREA                                                                                          |
| clubk2k3   | KOREA                                                                                          |
| clubk2kp   | KOREA                                                                                          |
| clubk2kpa  | KOREA                                                                                          |
| clubkcyc   | KOREA                                                                                          |
| clubkcyco  | KOREA                                                                                          |
| clubkprz   | EXPORT LOCKED                                                                                  |
| clubkpzb   | EXPORT LOCKED                                                                                  |
| clubkpzbp  | EXPORT LOCKED                                                                                  |
| clubkrt    | KOREA                                                                                          |
| clubkrta   | KOREA                                                                                          |
| clubkrtc   | KOREA                                                                                          |
| clubkrto   | KOREA                                                                                          |
| inidv3ca   | KOREA                                                                                          |
| inidv3cy   | KOREA                                                                                          |
| initd      | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| initdexp   | KOREA         (title in flycast clearly reads EXPORT)                                          |
| initdexpo  | KOREA         (title in flycast clearly reads EXPORT)                                          |
| initdo     | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| initdv2e   | KOREA         (title in flycast clearly reads EXPORT)                                          |
| initdv2j   | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| initdv2ja  | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| initdv2jo  | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| initdv3e   | KOREA         (title in flycast clearly reads EXPORT)                                          |
| initdv3j   | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| initdv3jb  | EXPORT LOCKED (title in flycast clearly reads JAPAN)                                           |
| kingrt66   | KOREA                                                                                          |
| kingrt66p  | KOREA                                                                                          |
| sgdrvsim   | KOREA (causes ERROR 01, should default to JAPAN https://segaretro.org/Sega_Driving_Simulator ) |
| soulsurf   | KOREA                                                                                          |
| vf4        | KOREA                                                                                          |
| vf4b       | KOREA                                                                                          |
| vf4cart    | KOREA (title in flycast clearly reads WORLD)                                                   |
| vf4evo     | JAPAN LOCKED                                                                                   |
| vf4evoa    | JAPAN LOCKED                                                                                   |
| vf4evob    | JAPAN LOCKED                                                                                   |
| vf4evoct   | KOREA (title in flycast clearly reads WORLD)                                                   |
| vf4o       | KOREA                                                                                          |
| vf4tuned   | KOREA                                                                                          |
| vf4tuneda  | KOREA                                                                                          |
| vf4tunedd  | KOREA                                                                                          |
| vstrik3    | KOREA                                                                                          |
| vstrik3c   | KOREA (title in flycast clearly reads WORLD)                                                   |
| vstrik3co  | KOREA (title in flycast clearly reads WORLD)                                                   |
| wldrider   | KOREA                                                                                          |

**Comment by flyinghead** [comment]
For Naomi games, the region setting means the following:
Japan: Japan
USA: USA
Europe: Export
Default: Korea

In most cases the ROM indicates which regions it supports. So Flycast will switch to a supported region if the selected one isn't supported. It will select the first supported region in this order: USA, Export, Japan, Korea.

It looks like this isn't working for sgdrvsim but it's not even a game so it's not surprising. Use Japan for this one.

**Comment by EmuShredder** [comment]
To add to my last comment, the entire Initial D series is messed up too.  Japan games default to Export, and the actual Export editions default to Korea.  Do you understand what I am getting at?

**Comment by EmuShredder** [comment]
I dunno, not for nothing, but you seem like a lazy asshole full of excuses why you can't fix obviously broken shit yet the masses sing your praises and well I get it.  They're too stupid to care enough.  Thanks for blocking my last 4 legit bug reports for no reason.  Now I actually gave you a real reason to ban me you slimy little prick.  Bye.
