### ISSUE TITLE
Update of CHD to support ZSTD

### ISSUE THREAD

**Issue by Papermanzero** [flyinghead/flycast#1438]
https://docs.mamedev.org/tools/chdman.html#createraw

Mame 0.262 introduced zstd as data compression. It would be good to update to the newest chd version to use the benefits from zstd over zlib.

this mist be updated also for the libretro core

**Comment by flyinghead** [comment]
Flycast relies on [libchdr](https://github.com/rtissera/libchdr) to read CHD disks.

**Comment by archerallstars** [comment]
For a reference, [libchdr](https://github.com/rtissera/libchdr) has already [added zstd support](https://github.com/rtissera/libchdr/pull/106).

**Comment by flyinghead** [comment]
Flycast already ugraded to the latest libchdr version, and now also supports zstd in zip files.
