### ISSUE TITLE
Fist Of The North Star Atomiswave Error

### ISSUE THREAD

**Issue by Julcello692** [flyinghead/flycast#1439]
Platform / OS / Hardware: MacBook Pro 16-inch 2019 2.6 GHz 6-Core Intel Core i7, AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB, MacOS 14.3.1

Github hash: f63a82afc

I have the correct bios "awbios.zip"for Atomiswave in both the directory of ~/Library/Application Support/Flycast/data and in the folder of "fotns", which includes "awbios.zip" and "fotns.zip". No matter how many different version of ROMs I try of this game, and I've tried many at this point from different sets and version numbers, I keep getting this error. As you can see in the screenshots, the file clearly has ax1901p01.ic18 and it obviously stays when I compress it, but it still always gives me this error. I even tried it with the bios files included in the folder before compression and it still doesn't work. I also checked and it looks like the file size of ax1901p01.ic18 is exactly what it should be. Would you please help me with how to fix this? Somehow I've gotten Dolphin Blue and Demolish Fist to work, but this and some other ROMs have the same issue. 

Thank you so much! Please let me know if you need any more information, I'll be happy to give it to you.

<img width="726" alt="Proof 1" src="https://github.com/flyinghead/flycast/assets/10580888/0721b8ff-cdd2-4118-9b16-ab7b2aa8d9eb">
<img width="725" alt="Proof 2" src="https://github.com/flyinghead/flycast/assets/10580888/648ac8b0-9ad1-40a3-9ebd-36c29db5b702">
<img width="289" alt="Proof 3" src="https://github.com/flyinghead/flycast/assets/10580888/d4ccb044-c7fb-453c-9fa5-295c668e6a2e">

**Comment by flyinghead** [comment]
Everything looks correct from what you posted.
What could happen is the wrong fotns.zip could be opened (if you have multiple versions available to flycast) and that one may be missing this or all files. ax1901p01.ic18 is the first file loaded and will be the first one to fail is no file can be found.

Also make sure you don't put zip file within zip files. fotns.zip should be a flat zip file located in a directory.

I just did a sanity check on macOS and fotns starts without issue with the latest master build.

**Comment by Julcello692** [comment]
Understood, thank you. I have double checked all of my directories and searched my entire Macintosh HD with Find Any File. The only instance of fotns.zip is in the directory I sent you. I also double checked that awbios.zip and fotns.zip don't have any zip files in them, and they do not. For some reason. I'm still getting the same error.

When I checked the ~/Library/Application Support/Flycast/data directory, I noticed the two Atomiswave games that worked for me have "zip.nvmem"and "zip.nvmem2" files (ex. "dolphin.zip.nvmem" and "dolphin.zip.nvmem2") It seems that fotns does not have any of those files. I don't know anything about these type of files, but could that have something to do with the problem?

May I have any other suggestions to solve this? I'm honestly confused about why this error keeps happening. I really appreciate your help!

**Comment by Julcello692** [comment]
I’m happy to provide anything else to help, such as log files, etc. Please just let me know. Thank you!

**Comment by Julcello692** [comment]
I have closed this issue because I have finally found a rom that works for fotns.zip. I'm hoping this topic can help other people realize that if the rom doesn't work, keep trying to find one that does work. Don't give up!

I appreciate your trying to help me with everything!
