### ISSUE TITLE
Missing texture during "Dump Textures" (always) and "Load Custom Textures" (randomly) 

### ISSUE THREAD

**Issue by vkedwardli** [flyinghead/flycast#144]
When enabled "Dump Textures"

Missing texture is always reproducible, regression caused by https://github.com/flyinghead/flycast/commit/03f096384b43f2880e5a1d3d9ee07784a602f7a8
![6b3293f6-2d85-49b6-95b7-71f0db49b89e](https://user-images.githubusercontent.com/602245/102820820-df36ad00-4410-11eb-90c2-f12ae2efd455.jpg)

The above issue has no importance since this only occurs during "Dump Textures", my main concern is the "Load Custom Textures" below:

**With texture replacement enabled, some texture (to be replaced or not to be replaced) will be missing.**

Only the head is missing (this model is using custom texture, the head and the body are from 2 separate png)
<img width="645" alt="Screenshot 2020-12-22 at 5 17 46 AM" src="https://user-images.githubusercontent.com/602245/102823015-0e4f1d80-4415-11eb-8c3c-c9ae6cb53aa2.png">

Background is missing (not custom texture)
<img width="644" alt="Screenshot 2020-12-22 at 5 18 50 AM" src="https://user-images.githubusercontent.com/602245/102823101-3474bd80-4415-11eb-839b-bf4d31d27fda.png">

Laser beam is missing (not custom texture, hard to notice by static screencap, please refer to video posted in Discord)
<img width="640" alt="Screenshot 2020-12-22 at 5 22 22 AM" src="https://user-images.githubusercontent.com/602245/102823343-aea54200-4415-11eb-87ca-27913716b404.png">

I have no idea if the missing texture for texdump and texreplace has the same root cause.
Thank you for your time.

**Comment by flyinghead** [comment]
The black textures during dumping should be fixed. I also fixed an issue where some textures were deleted when the custom version was loaded, resulting in GL errors.

However these problems probably don't explain why a given texture (custom or not) would stay black as mentioned in the issue description.

Could you confirm which renderer is used (Open GL or Vulkan) and which setting (per-triangle or per-pixel)?

**Comment by vkedwardli** [comment]
From bug producer:

![280b82fd-18d4-463c-8e45-4d78135db0dc](https://user-images.githubusercontent.com/602245/103171597-82137f00-4888-11eb-8127-ad564d10703b.jpg)
![6b081d49-8868-479a-9cf9-b62305e5f949](https://user-images.githubusercontent.com/602245/103171599-8344ac00-4888-11eb-926d-5b23a9706d41.jpg)

**Comment by vkedwardli** [comment]
Verified fixed, thanks a lot!
