### ISSUE TITLE
18 Wheeler: American Pro Trucker - Regression

### ISSUE THREAD

**Issue by antoniodesousa** [flyinghead/flycast#1445]
Platform / OS / Hardware: 
Dreamcast, Windows 11 23H2, Ryzen 9 6900HX, Radeon RX 6600M, 64 GB RAM

Github hash: 
https://github.com/flyinghead/flycast/commit/c146a92

**_Description of the Issue_**

The screws from the plate in the title screen are missing. You can see the animation but they become missing afterwards. Every build after the one I mentioned (including that build) has the same issue.

**_Debugging Steps Tested_**

Just wait until the title screen appears and the animation finishes.

**_Logs Gathered_**

**_Screenshots_**

![Screenshot 08_03_2024 14_41_02](https://github.com/flyinghead/flycast/assets/10920974/f083d8cb-0fc1-45cf-8481-b9275095f37a)

**Comment by flyinghead** [comment]
I can't reproduce the issue with a Nvidia GTX 1080. I tried both OpenGL and Vulkan, per triangle and per pixel, and the screws are always visible.
Do you have Native Depth Interpolation enabled? Can you test other graphics APIs?

**Comment by antoniodesousa** [comment]
- Enabling/disabling "Native Depth Interpolation" makes no difference
- I tried all APIs OpenGL, Vulkan, DirectX 9 and DirectX 11. All have the same issue
- I also tried from a clean setup, it made no difference

Maybe, the change only affects AMD GPUs and possible Intel GPUs?
Latest build without the issue is [57c88e0](https://github.com/flyinghead/flycast/commit/57c88e0)

**Comment by flyinghead** [comment]
Yes, it's possibly a GPU or GPU driver issue.
Unfortunately, the commit you reference is a merge commit from the dev branch, so it's actually 121 commits.
Can you try some builds (before 2024/2/3) on the dev branch?

**Comment by antoniodesousa** [comment]
This commit broke it [9f9b29b](https://github.com/flyinghead/flycast/commit/9f9b29b)
It makes sense, I had issues before with that setting enabled on my GPU. That's why I always have it disabled.
But it seems like it's been forced to be enabled by default now. So, that option does nothing now 😞

**Comment by antoniodesousa** [comment]
Cool thanks! I will close the issue once I test the new build with the fix.

**Comment by flyinghead** [comment]
Fixed on latest `master`

**Comment by antoniodesousa** [comment]
I just tested it and it's fixed in the latest master release! Thanks
