### ISSUE TITLE
Can't find "pointer type" input in Flycast on RetroArch android.

### ISSUE THREAD

**Issue by Jonathan7299** [flyinghead/flycast#1446]
I once made a post asking to add touchscreen light gun support to the Flycast core on RetroArch android. One of the devs said that it would be added in the next update as "pointer type" input with one finger touch to fire and two finger touches to reload. However I have the latest version of the core and still can't find the "pointer type" input anywhere. Can someone please help?

**Comment by flyinghead** [comment]
You should set your controller to "light gun" and the core will use the pointer coordinates sent by retroarch. It usually uses the mouse coordinates on desktop, but it should work with finger touches as well if retroarch supports it now.

**Comment by Jonathan7299** [comment]
I did that and although a crosshair shows up it doesn't move no matter how much I touch the phone screen.

**Comment by flyinghead** [comment]
That was issue #604.
Set the controller to "pointer" as mentioned in the original issue.

**Comment by Jonathan7299** [comment]
I figured it out! I installed the Google Play store version which hasn't been updated for years due to "restrictions". So I deleted it and installed the latest version from the official website and found the "pointer" input.
