### ISSUE TITLE
Request: 2.25x resolution for 1080p

### ISSUE THREAD

**Issue by banana3333** [flyinghead/flycast#1447]
Exactly as title says, a 2.25x resolution option for the standalone version in Android would be nice for 1080p screens.

**Comment by flyinghead** [comment]
This is a common misconception that rendering at the screen native resolution will give the best results.
Upscaling from the native 640x480 resolution can introduce artifacts, texture seaming, glitches, etc. And using non-multiples of 640x480 makes it worse. 

So use x2 resolution instead.
