### ISSUE TITLE
NAOMI 2, DirectX 9 and Per Game Configuration

### ISSUE THREAD

**Issue by hegyak** [flyinghead/flycast#1448]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 11
AMD Radeon RX 5700 XT

Github hash: 
464DEFE0D

**_Description of the Issue_**
Having a NAOMI 2 Game with Per Game Configuration and enabling DirectX 9 will cause a Loop where Flycast says:
"DirectX 9 does not Support NAOMI 2 games.  Select a different Graphics API"

**_Debugging Steps Tested_**

*Ensure that the Default Graphics API is not set to DirectX 9.
*Start a NAOMI 2 game.  Doesn't matter which one.  I chose Initial D Arcade Stage.  But any NAOMI 2 game will work.
*Enable Per Game Settings.
*Check the box
"Per Game VMU A1"
The above step is done to ensure that Per Game settings, are enabled.
*Save the settings by selecting "Close Game"
*Rerun the same game.
*Go into Settings and set the Graphics API to DirectX 9
*Attempt to Return to the game.
*Warning/Error message appears and you are sent to the Game List.
*Attempt to run the same NAOMI 2 game again.
*Warning/Error Message appears and you are sent to the Game List.  And you are unable to change the Graphics API for that game.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

This is not a Priority issue.  But something I found when trying to fix some Graphical Bugs with my AMD Video Card.

**Comment by flyinghead** [comment]
Fixed in the lastest `dev` build
