### ISSUE TITLE
Add a "per-game VMUs" option to the standalone Android version

### ISSUE THREAD

**Issue by DatGrey** [flyinghead/flycast#1449]
As the title says, it would be useful to have the option to create per-game VMUs in the Android version in the same way you can in the libretro version of Flycast.
This would even make syncing save files between different versions easier.
Thank you for all your effort and hard work.

**Comment by flyinghead** [comment]
The "per game VMU A1" option is available on all platforms, including Android, although it only affects VMU A1.
Are you requesting to have per game VMUs for all gamepads and ports?

**Comment by DatGrey** [comment]
I'm sorry but I've looked for it in the settings menu again and again before submitting this issue, I just can't seem to find it... can you please point me to it?

**Comment by DatGrey** [comment]
Nevermind, I think I've found the issue... I'm using an older version because I was under the impression that Flycast was available through the Play Store (and thus, updated automatically).

I'm gonna install the latest version now. Sorry for the confusion.
Thanks again for all your great work!

**Comment by DatGrey** [comment]
I've update the installed version and found the option, I can confirm it works correctly! Just a small issue, looks like the standalone version and the libretro one use a different naming convention (one appens the string ".A1.bin" to the game name, the other uses ".chd._vmu_save_A1.bin").
Is this correct or am I doing something else wrong?
Thank you.

**Comment by flyinghead** [comment]
This is correct: the naming convention is different

**Comment by DatGrey** [comment]
Thank you for confirming this. Would it make sense to make it so the names of the save files match across versions in order to be able to sync them between devices?

**Comment by flyinghead** [comment]
It would make sense but would break backward-compatibility

**Comment by DatGrey** [comment]
That would be bad. No problem, I've worked around the issue using a script that moves save files between directories, renames them and creates a symlink with the original name in the original location. Works like a charm :)

Thanks again!
