### ISSUE TITLE
Wild Riders, no rear brake for Standalone

### ISSUE THREAD

**Issue by WarpedPolygon** [flyinghead/flycast#1450]
The RA version has the rear brake mappable but standalone does not seem to have it.

Tried every input in the list to no avail. I know it's an analog input so made sure to try every analog and digital input to be extra sure.

**Comment by flyinghead** [comment]
Should be fixed in the latest `master` build.
Note that rear brake isn't available in RA due to a lack of available retropad buttons.

**Comment by WarpedPolygon** [comment]
Cheers mate. I think the rear brake is actually available in RA as I was messing with it today, although on an older version of the core. I'll double check and let you know
