### ISSUE TITLE
Soul Surfer, 'left button' is permanently on.

### ISSUE THREAD

**Issue by WarpedPolygon** [flyinghead/flycast#1451]
The 'left button' for menu navigation is permanently ON. Un mapped it and tried to at least get it to register as off but no luck. Think this may be causing clashing inputs with the 'roll left' input also.

Standalone version. RA version not tested.

**Comment by flyinghead** [comment]
For convenience, button 1 is mapped to Left, and button 2 is mapped to Right.
Button 4 is always on as it is a sensor that should always be on.
So button 1 and DPad Left both activate Left, but it's not always on.
I ran the Naomi BIOS JVS test and the game input test and got the expected results.

**Comment by WarpedPolygon** [comment]
Sorry mate, this was a wild goose chase for a random thing unrelated to Flycast.
It's working as it should, my controller isn't.

Closing
