### ISSUE TITLE
Reload doesn't work with RetroArch Flycast (Android) for House of the Dead 2 and Confidential Mission.

### ISSUE THREAD

**Issue by Jonathan7299** [flyinghead/flycast#1454]
Reloading (two finger touches) doesn't work with House of the Dead 2 nor Confidential Mission. Works fine with Maze of Kings and Ninja Assault though.

**Comment by flyinghead** [comment]
I tested with house of the dead 2 and reloading with 2 fingers does work.
Make sure you properly calibrate the light gun as it is tricky to get right with hotd2.
See this issue for reference: #1406

**Comment by flyinghead** [comment]
assuming this is fixed
