### ISSUE TITLE
Abysmal frame pacing

### ISSUE THREAD

**Issue by Zeromus24** [flyinghead/flycast#1459]
Platform / OS / Hardware: Windows 11, Intel i5-11300H, RTX 3050

Github hash: https://github.com/flyinghead/flycast/commit/c1f0a5a15f07ba82ccb974e5c7dc82206324b0a3

Issue description
Frame pacing is absolutely abysmal on every game that I have tested. Instead of hitting a stable 33.3ms or 16.6, it just throws a frame whenever it wants. As a result, gameplay is never smooth. 

**_Debugging Steps Tested_**
- Disabling VRR completely
- Adjusting internal resolution
- Toggling vsync on/off
- Switching between OpenGL and Vulkan
- Turning on "duplicate frames"

**_Screenshots_**

![image](https://github.com/flyinghead/flycast/assets/49614982/98f8c206-2796-453f-86c4-ef2c004af3cb)
_60FPS game, Crazy Taxi_

![image](https://github.com/flyinghead/flycast/assets/49614982/f33f1d1a-b54c-42da-904c-86f9b4598fd2)
_30FPS game, Skies of Archadia_

As reference, this is how the frame times look on another emulator running the same game:
![image](https://github.com/flyinghead/flycast/assets/49614982/7f240c7b-f46b-4c6a-8cfc-9bf057e95b43)

**Comment by flyinghead** [comment]
Use another emulator

**Comment by Zeromus24** [comment]
> Use another emulator
That was just for a point of reference on how the histogram should look like, I mean no offense! I simply noticed an issue, and I reported it.

**Comment by flyinghead** [comment]
I'd be interested in knowing which other Dreamcast emulator has a vulkan renderer.

**Comment by Zeromus24** [comment]
It was actually Dolphin, not a Dreamcast emulator. Perhaps I shouldn't have mentioned an emulator there. It wasn't a direct comparison, I just wanted to show what a frame time graph should look like.

**Comment by Zeromus24** [comment]
Also it's not ideal, but a workaround to this problem is to enable both frame duplication and VRR. G-Sync smoothes out the judders pretty well. But this still isn't ideal as VRR displays aren't very commonplace.

**Comment by blueminder** [comment]
You can also use something like RTSS or Special K to set the frame pacing in Windows. Just be sure to disable Audio Sync (or Fixed Frequency if you're using Dojo) so that they don't conflict.

**Comment by Zeromus24** [comment]
Yeah, frame pacing seems to work correctly on your fork.
![image](https://github.com/flyinghead/flycast/assets/49614982/9528c897-1fc6-40f7-8a8d-b3a64b8750fd)
