### ISSUE TITLE
Unreal Tournament (PAL) corrupts its own save files

### ISSUE THREAD

**Issue by Scr34mik** [flyinghead/flycast#146]
**_Platform / OS / Hardware:_**
Windows 10 20H2
8700K
RTX 2060
32Gb RAM
Retroarch and game is located on HDD

Github hash: 
ca2fa42

**_Description of the Issue_**
Since last update, Unreal Tournament (PAL) corrupts its own save files

**_Add a short, concise description of the issue here_**
Just playing one match in practice mode then closing-launching game enough to get "save data corrupt" error

**_Debugging Steps Tested_**
* tried deleting UT save file via BIOS VMU manager
* tried using different (VMU1/Both/disabled) "per-content VMU" setting setups. Nothing helps.
* i was constantly deleting coprrupted VMUs, and it didnt help.

**_Logs Gathered_**
- none

**_Screenshots_**
![image](https://user-images.githubusercontent.com/10966059/102956393-b8e04280-44e0-11eb-8ead-4b54100ac4e2.png)

**Comment by flyinghead** [comment]
Issues related to the libretro core should be opened on the corresponding github repository:
https://github.com/libretro/flycast
Unless you can reproduce it with the standalone version of course.

**Comment by Scr34mik** [comment]
> 
> 
> Issues related to the libretro core should be opened on the corresponding github repository:
> https://github.com/libretro/flycast
> Unless you can reproduce it with the standalone version of course.

thanks. submitted issue there.
