### ISSUE TITLE
SUN Games Club Kart (NAOMI2) 

### ISSUE THREAD

**Issue by CCCP1982** [flyinghead/flycast#1460]
**_Screenshots_**
ARCADA 
![Снимок экрана (93)](https://github.com/flyinghead/flycast/assets/142115581/0f1f1579-decc-4903-811a-5d4d254d7685)
![Снимок экрана (94)](https://github.com/flyinghead/flycast/assets/142115581/a4bcbca8-887b-48fd-ad4f-3839e366a005)

Flycast  056a023  WINDOWS 10-11 Any render 

![6](https://github.com/flyinghead/flycast/assets/142115581/43e6df83-025b-4d24-b0a2-1924bbdfea0a)
![Снимок экрана (97)](https://github.com/flyinghead/flycast/assets/142115581/c927b446-4fed-4117-9e6f-301e7dcb6f8c)

There are no rays of the sun in the episodes!)

**Comment by flyinghead** [comment]
Слава Україні
