### ISSUE TITLE
CPU overclock limit

### ISSUE THREAD

**Issue by MaLDox77** [flyinghead/flycast#1462]
Currently the oc limit is 500 mhz from original 200 mhz.

Using games with variable framerate, sometimes 500 is not enough. 

Omikron The Nomad Soul is one of them. In real hardware the framerate moves between 60 and 15 fps. This means 600 mhz is the minimum to achieve locked 60 fps. Tested with 500 mhz the game goes to 30 fps sometimes (it is double buffered synced) 

Please  increase the oc limit. 

Thank you

**Comment by Nejsplitter1** [comment]
for standalone flycast you can edit the overclock value by looking for the sh4 clock line in the emu.cfg

**Comment by MaLDox77** [comment]
> for standalone flycast you can edit the overclock value by looking for the sh4 clock line in the emu.cfg

Thanks, I tried that in the libreto core and the value reseted to 200 at loading the core.

**Comment by flyinghead** [comment]
500 MHz is already waaaaaay more than original hardware. I'm not going to increase it anymore.
Having all games run at a locked 60 FPS, provided it's even possible, isn't on the roadmap.
