### ISSUE TITLE
Per gameconfigs not loading due to the naming

### ISSUE THREAD

**Issue by Boppyman** [flyinghead/flycast#1464]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10

Github hash: 

Hardware: 
RTX 3060ti

**_Description of the Issue_**
Any controller configs created before 2.3 aren't loading anymore.

Add a short, concise description of the issue here
When Raw input is enabled per game configs aren't loading in the newest version due to the .cfg file name now having the device ID in it.  Before 2.3 they just had the title of the game.

**_Debugging Steps Tested_**

  * Tried loading old configs and they didn't work
  * Saved a new config on 2.3 and saw they are now saved with the device ID

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)
![Pool](https://github.com/flyinghead/flycast/assets/125120538/0670da2f-f156-4c83-a2c9-f36eae5116d7)
![Pool ID](https://github.com/flyinghead/flycast/assets/125120538/98581014-6a84-4fc7-a38d-613aaa366cc2)
![Keyboard](https://github.com/flyinghead/flycast/assets/125120538/df7d5ac3-ad78-48ec-beee-ce2cac12803a)
![Keyboard ID](https://github.com/flyinghead/flycast/assets/125120538/a2e7a9fb-13e9-46c9-82c1-38e97dbac4b6)

**Comment by Boppyman** [comment]
I didn't know if I should add this to report as well but the controller naming is also a bit of a problem.

I have 2 controllers an Xbox Elite controller and an Xbox One S controller.  I saved all my configs, which show up as SDL_Xbox One Elite Controller_XXXXX_arcade.cfg.  So if I want to use my other controller as player 1 the configs won't load as they don't have any configs for them because I presume it's looking for SDL_Xbox One S Controller_XXXXX_arcade.cfg.

**Comment by flyinghead** [comment]
This change was made in response to #664 and #835. I usually try to be backward-compatible but didn't realize this would affect per-game configs so yes, controller configuration needs to be redone, or .cfg mapping files need to be renamed.

Regarding your other comment, this is normal and hasn't changed in 2.3: controller configuration is done for a given controller type, and you have 2 distinct controller types. So you need to map each of them individually.

**Comment by Boppyman** [comment]
> This change was made in response to #664 and #835. I usually try to be backward-compatible but didn't realize this would affect per-game configs so yes, controller configuration needs to be redone, or .cfg mapping files need to be renamed.
> 
> Regarding your other comment, this is normal and hasn't changed in 2.3: controller configuration is done for a given controller type, and you have 2 distinct controller types. So you need to map each of them individually.

Sorry, so are you saying that it is something your end you your redoing or something I have to do regarding the mouse and keyboard device IDs?

With the controllers side of things, as they are both Xbox controllers would it not be possible to just to output the configs as SDL_Xbox Controller_XXXXX_arcade.cfg so any Xbox controller would be picked up rather than having to make all new configs for each pad?

Thanks for the quick reply btw.

**Comment by flyinghead** [comment]
> Sorry, so are you saying that it is something your end you your redoing or something I have to do regarding the mouse and keyboard device IDs?

you need to reconfigure your mouse and keyboard

**Comment by Boppyman** [comment]
> > Sorry, so are you saying that it is something your end you your redoing or something I have to do regarding the mouse and keyboard device IDs?
> 
> you need to reconfigure your mouse and keyboard

Ok no worries.

Is the controller thing i mentioned anything you may change down the line?

**Comment by flyinghead** [comment]
No. This is quite difficult to get right and of limited value for most users. I mean, it's not like configuring a controller takes hours.

**Comment by Boppyman** [comment]
> No. This is quite difficult to get right and of limited value for most users. I mean, it's not like configuring a controller takes hours.

I understand.  It's just that there are 200-odd arcade games to do but it's nothing a bulk text editor can't fix once they have all been set up for the first time to change the ID or controller names.
