### ISSUE TITLE
Flycast reads only L2, R2 from wireless DualSense controller when run from Steam Library

### ISSUE THREAD

**Issue by smbhax** [flyinghead/flycast#1465]
Platform / OS / Hardware: Windows 11

Github hash: [40cdef6](https://github.com/flyinghead/flycast/commit/40cdef6)

Hardware:
wireless DualSense controller
Intel Core i7-10750H CPU @ 2.69GHz (12 CPUs)
16 GB RAM
NVIDIA GeForce GTX 1660 Ti
S271HL NVIDIA High Definition Audio

**_Description of the Issue_**

When Flycast is added to the Steam Library and run as a non-Steam game, Flycast detects only the L2 and R2 inputs from the DualSense wireless controller; the DualSense shows up in Flycast's Controls - Physical Devices list as "Controller (XBOX 360 For Windows," but on the controller's Controller Mapping page, attempting to map a control to anything other than L2 or R2 times out.

**_Debugging Steps Tested_**

* With the DualSense bound to Windows in wireless mode, started Flycast normally and mapped buttons to the "DualSense Wireless Controller" physical device in Flycast's Settings with no problems
* Closed Flycast
* Ran Steam, went to Steam Library, clicked "Add a Game" in the lower left and added Flycast
* Launched Flycast from Steam Library
* Went to Flycast's Settings - Controls, clicked Map next to the "Controller (XBOX 360 For Windows" Physical Device that is now there in place of "DualSense Wireless Controller," clicked A Button's "Map" button and attempted to map a button to it by pressing inputs on the controller--but it would only map to L2 and R2; when I tried activating any of the other inputs on the DualSense, the Map Control window timed out with no mapping added.
* Additionally, when closing Flycast and running it again, L2 and R2 mappings or a Reset to default controls made in the previous Steam Library-launched session do not usually seem to have saved--the mappings are back to what they were prior to the previous session. I've got them to save twice out of about 20 tries; not sure what the difference was.

**_Logs Gathered_**

[flycast - Copy.log](https://github.com/flyinghead/flycast/files/14706785/flycast.-.Copy.log)

**_Screenshots_**: None

**Comment by flyinghead** [comment]
I don't know what's going on here but it's obvious that Steam is interfering with Flycast access to input devices. Flycast relies on SDL to access controllers so Steam might be using its own version, or this is done at a lower level.
In any case, this is beyond Flycast's control.

**Comment by smbhax** [comment]
That's understandable. I suppose I brought it up because I've been able to map controls just fine with the DualSense in PCSX2, when launching that emulator through Steam in order to take advantage of advanced Steam Input functions. Those are being handled through SDL, according to PCSX2's input labels.
