### ISSUE TITLE
Sonic Adventure 2 is stuttering at 60 fps

### ISSUE THREAD

**Issue by CommicKick69ing** [flyinghead/flycast#1466]
Platform / OS / Hardware: Android / 13 / pixel 6

**_Description of the Issue_**

The game itself keeps stuttering in cutscenes, game play, and menus despite before running smoothly 

**_Debugging Steps Tested_**

  * Play game unil the third knuckles level. 
  * Get second key 
  * 'Few mintes later' violent shaking

**Comment by flyinghead** [comment]
> The game itself keeps stuttering [...] despite before running smoothly

before what?

**Comment by CommicKick69ing** [comment]
> > The game itself keeps stuttering [...] despite before running smoothly
> 
> before what?

Before the third knuckles level

**Comment by flyinghead** [comment]
Inactive
