### ISSUE TITLE
Question: how to insert coin with virtual pad

### ISSUE THREAD

**Issue by th0rig** [flyinghead/flycast#147]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here
I apolgize if i post in wrong place but i need some help i try to play metal slug 6 atomiswe but i dont see insert coin button in virtual pad.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
The Android virtual gamepad doesn't have a coin button. You can set the game to free play on a PC or with a gamepad.
For your convenience, here is a nvmem save for mslug6 set to free play. Exit the game, unzip this file and copy its content into flycast's `data`directory:
[mslug6.zip](https://github.com/flyinghead/flycast/files/5739304/mslug6.zip)

**Comment by th0rig** [comment]
Sorry for the late reply i try your method now i can play MSLUG6 without the need to insert coin so tanks for that and for your hardwork i'll close this issue now.
