### ISSUE TITLE
there is connection error after dialed up Outtrigger network game

### ISSUE THREAD

**Issue by cloudslsw** [flyinghead/flycast#1475]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
windows 10

Github hash: 
https://github.com/flyinghead/flycast/commit/966ff3767dc6c7a8c84b123fcaa94b4bddced48a

Hardware: 
i5 9400+1050ti

**_Description of the Issue_**
when disable BBA emulation game can dialed up to network game via default flycast account but there is just an empty background then shows connection error, i tried ggpo/naomi/battle cable, none of them can bypass this

**_Debugging Steps Tested_**

**_Logs Gathered_**
[flycast.log](https://github.com/flyinghead/flycast/files/14896950/flycast.log)

**_Screenshots_**
![QQ截图20240407184423](https://github.com/flyinghead/flycast/assets/11231847/fa02379c-d635-4beb-bad4-1c91547158ef)
![QQ截图20240407191323](https://github.com/flyinghead/flycast/assets/11231847/560ca660-40fb-41ca-80ac-c68362c315bb)

**Comment by flyinghead** [comment]
The server for this game have been shut down long ago and haven't been revived so native online play isn't possible.

You can use split screen vs. mode with GGPO although you should probably look at [Flycast Dojo](https://github.com/blueminder/flycast-dojo) in this case.

Or you can use the Naomi version that has native LAN networking, which is emulated by Flycast.

**Comment by cloudslsw** [comment]
> The server for this game have been shut down long ago and haven't been revived so native online play isn't possible.
> 
> You can use split screen vs. mode with GGPO although you should probably look at [Flycast Dojo](https://github.com/blueminder/flycast-dojo) in this case.
> 
> Or you can use the Naomi version that has native LAN networking, which is emulated by Flycast.

thanks for info, im gonna check it out
