### ISSUE TITLE
RGB30 ArkOS Dreamcast Sega Rally won’t load

### ISSUE THREAD

**Issue by Mika73** [flyinghead/flycast#1479]
I am using Powkiddy RGB30 with ArkOS. Dreamcast Sega rally won’t load. It stuck to screen that says Sega and Windows CE. I have try two different GDI images and it didn’t make difference. 

Also Lonely Toons Space Race has sound problem. 
First no sound and then sound loop. 

Other games I try work very nice.

**Comment by flyinghead** [comment]
Flycast version?

**Comment by Mika73** [comment]
I have latest RGB30 ArkOS version. But I don’t know what Flycast version it has. Lähetetty iPhonestaflyinghead ***@***.***> kirjoitti 13.4.2024 kello 23.48:﻿
Flycast version?

**Comment by flyinghead** [comment]
Settings > About

**Comment by Mika73** [comment]
1.18.0 Flycast Lähetetty iPhonestaflyinghead ***@***.***> kirjoitti 14.4.2024 kello 18.12:﻿
Settings > About

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen with the requested information if not.
