### ISSUE TITLE
Star Wars: Episode 1: Racer freezes on start screen

### ISSUE THREAD

**Issue by sciencefrixion** [flyinghead/flycast#148]
It doesn't work anymore on the latest Lakka nightly, but did so on an older release.

**Comment by flyinghead** [comment]
This is a known issue. A work-around is to spam the Start button right before this screen appears.
See https://github.com/libretro/flycast/issues/877

**Comment by coldspark29** [comment]
Yes it works. Thank your for the advice

**Comment by flyinghead** [comment]
Fixed in build https://github.com/flyinghead/flycast/commit/2b41d9684f40052030b9af9d97710b2f34e352ff
