### ISSUE TITLE
[Xbox Dev Mode] MSR - Metropolis Street Racer (USA) (Rev A) - Flycast LibRetro Core crashes after intro

### ISSUE THREAD

**Issue by boktai1000** [flyinghead/flycast#1480]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Xbox Series X - Dev Mode

Github hash: 

Hardware: 

Xbox Series X - Dev Mode

**_Description of the Issue_**

Hello all,

I wanted to try to formally report this issue as well as my troubleshooting regarding it in hopes of either better understanding it, or identifying a possible issue to get a resolution pushed to upstream. I documented and asked about this issue on the libretro Discord server, and my posts can be referenced here:
https://discord.com/channels/184109094070779904/469974542299955210/1228773751164768256
https://discord.com/channels/184109094070779904/469974542299955210/1228756504757272626

To summarize and make this convenient, I'll copy paste the results here below:

----

Hey everyone! :slight_smile:

I've been trying to load **MSR - Metropolis Street Racer (USA) (Rev A)** through RetroArch's Flycast core to no avail. It's very strange, a dozen or so other DreamCast games I've played work without issue.

I've tried to load the game both with and without the HLE bios, and I do have a DC bios with proper MD5 in the system/dc folder present and can confirm that it loads the BIOS.

I've found similar issues on GitHub around this issue but mostly they mention trying the real DC bios, which I am - but it doesn't seem to make a difference here.
<https://github.com/libretro/flycast/issues/838>
<https://github.com/libretro/flycast/issues/63>

Has anyone else had any luck loading this game  under any circumstances? I'd be very curious to know what's different here.

I've also tried the following formats: Redump bin/cue, CHD, gdi, and cdi - all with the same issues.

----

I just wanted to follow up on this and say that I tried the following older LibRetro Flycast Cores, and found one that worked!

Pre-packaged flycast_libretro.dll included with RetroArch downloads - Test
1.14.0 - Did not work
1.13.0 - Worked
I'm not sure if this is something that needs to be more formally reported or documented somewhere.

**_Logs Gathered_**

**_Screenshots_**

Working cores / configurations are able to make it to this screen, problem cores crash before this loads - just as some others have described in some of the other linked issues.
![image](https://github.com/flyinghead/flycast/assets/9054563/e9bae7cb-1fb3-4155-b2a3-9d0d6ab5a60c)

**Comment by flyinghead** [comment]
The Flycast libretro core isn't supported on xbox/uwp. See  #865 for details.
Standalone Flycast works fine.

**Comment by boktai1000** [comment]
Hmm I see, is there any where else I should report this issue to? Standalone Flycast works, but I don't believe it has RetroAchievement support which is something I'm looking for.

It should also be noted that many other games I do have work just fine in my library, this one is a bit of an outlier, and it does work just fine when using Flycast Libretro core version pre-packaged with 1.13.0.

**Comment by flyinghead** [comment]
RetroAchievements is now available in standalone Flycast
