### ISSUE TITLE
Flycast 2.3 on Nintendo. Switch stuck on Loading screen (no progress)

### ISSUE THREAD

**Issue by Aalec77** [flyinghead/flycast#1485]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Nintendo switch Fw 17.01 - atmosphere updated to the latest version

Github hash: 

Hardware: 

**_Description of the Issue_**

‘I can launch Flycast successfully but when I try to start any game, the screen remains stuck on “Loading Game” screen with no progress on the progress bar

**_Debugging Steps Tested_**

  * 
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**Comment by flyinghead** [comment]
I just tested the release build 2.3 on a Switch with firmware 17.0.1 without any issue.
Did it work before?
Have you tested other emulators or homebrew games?

**Comment by Aalec77** [comment]
Hi,I have managed to play Retroarch without any issue (SNES and Sega Genesis core) for quite some times.This was my first attempt of running Flycast on the Dreamcast.If this helps, I use the same .CDIs and Bios files on Flycast 2.3 on my M3 Pro Mac flawlessly.Attached please find a picture of the “stuck screen”.BestAlexAm 17.04.2024 um 09:13 schrieb flyinghead ***@***.***>:﻿
I just tested the release build 2.3 on a Switch with firmware 17.0.1 without any issue.
Did it work before?
Have you tested other emulators or homebrew games?

**Comment by flyinghead** [comment]
There's no screenshot attached to your comment.

SNES and Genesis are 8/16-bit emulators so they don't use any JIT recompiler or virtual memory, which may explain why they work and Flycast doesn't.

Also make sure to run Flycast as a game and not as an app (don't use the album for the homebrew menu).
