### ISSUE TITLE
Sonic Adventure crashes: Nintendo Switch

### ISSUE THREAD

**Issue by OldFashiondDino** [flyinghead/flycast#1486]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Nintendo Switch

Github hash: ?

Hardware: Nintendo Switch

**_Description of the Issue_**

Sonic Adventure (International Version) crashes during Tails at Casinopolis (Stage 2 of Tails), sometimes it does immediately when the level starts, when tails touches the water or after beating the level by avoiding to touch the water. Someone on reddit mentioned frame-skipping but that doesn't seem to work on me.

**_Debugging Steps Tested_**

  * Tried messing with frames skipping, nothing.
  
**_Logs Gathered_**

[INFO] [Config]: Loading config: "/retroarch/retroarch.cfg".
[INFO] [Overrides]: Saved: "/retroarch/config/Flycast/Sonic Adventure International.cfg".
[INFO] [Overrides]: Overrides saved successfully.
[libretro ERROR] libretro/common.cpp:359 E[COMMON]: SIGSEGV @ 411be10fc ... 0x5b0815db5 -> was not in vram (dyna code 0)
[libretro ERROR] libretro/common.cpp:364 E[COMMON]: .text base: 0x4106d5000
[libretro ERROR] libretro/libretro.cpp:3272 E[COMMON]: DEBUGBREAK!

**_Screenshots_**

![image](https://github.com/flyinghead/flycast/assets/167569876/0c80073b-c2e9-40df-b3e5-5f8fc27319df)

**Comment by flyinghead** [comment]
The retroarch core on Switch hasn't been updated for years and isn't supported. Use standalone Flycast instead.
