### ISSUE TITLE
Would it be possible to release the iOS version on the app store?

### ISSUE THREAD

**Issue by cornflakes6374** [flyinghead/flycast#1487]
**Is your feature request related to a problem? Please describe.**

Hmmm, maybe people who is not wanting to jailbreak their iphone/ipad/ipodtouch wants to use this emulator without sideloading.

**Describe the solution you'd like**

Now that the app store is now fine with emulators such as delta being released few days ago (https://apps.apple.com/us/app/delta-game-emulator/id1048524688), maybe you could release the IPA version of flycast to the app store as long it follows the app store guidelines like delta!

**Describe alternatives you've considered**
...

**Additional context**
Iphones and ipads would have a good performance in this emulator, A12 bionic (including A12X and A12Z in early face id ipad pros) or higher could be recommended while a minimum could be A8,A8X or A9.

**Comment by flyinghead** [comment]
Yes, Flycast definitely requires JIT capabilities to be usable.

**Comment by flyinghead** [comment]
So not possible until Apple allows JIT to be used

**Comment by maplemilesalt-byte** [comment]
No jit version would be cool
