### ISSUE TITLE
"Filter" field label overlaps Settings button at top of a narrow Game List window

### ISSUE THREAD

**Issue by smbhax** [flyinghead/flycast#1488]
Platform / OS / Hardware: Windows 11

Github hash: [47b6a90](https://github.com/flyinghead/flycast/commit/47b6a90)

Hardware: 

Intel Core i7-10750H CPU @ 2.69GHz (12 CPUs)
16 GB RAM
NVIDIA GeForce GTX 1660 Ti
S271HL NVIDIA High Definition Audio

**_Description of the Issue_**

When the Game List is set to a small window width, the "Filter" field label above the game list thumbnails overlaps the "Settings" button to its right.

**_Debugging Steps Tested_**

- Open the Game List
- Drag the window edges to narrow the window past the point where the "Filter" text is butting into the "Settings" button (at 3 thumbnails wide, for instance)
== The "Filter" text overlaps the "Settings" button, making both hard to read

**_Screenshots_**

![Untitled-1 copy](https://github.com/flyinghead/flycast/assets/91744319/0a7191b1-c21c-4864-939d-3bb89c00cfbf)

![Untitled-2 copy](https://github.com/flyinghead/flycast/assets/91744319/38cd762f-74e1-44a6-9ef3-14a060572572)

**Comment by flyinghead** [comment]
Fixed in the latest master build
