### ISSUE TITLE
Game List cycles thumbnail size when window height set just under lowest thumbnails

### ISSUE THREAD

**Issue by smbhax** [flyinghead/flycast#1489]
Platform / OS / Hardware: Windows 11

Github hash: [47b6a90](https://github.com/flyinghead/flycast/commit/47b6a90)

Hardware:

Intel Core i7-10750H CPU @ 2.69GHz (12 CPUs)
16 GB RAM
NVIDIA GeForce GTX 1660 Ti
S271HL NVIDIA High Definition Audio

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

- Drag the height of the Game List window to just under the bottom row of thumbnails
== The list display keeps "bouncing" as a vertical scroll bar appears and disappears on the right hand side, causing the thumbnails to keep adjusting their size.

**_Screenshots_**

![1](https://github.com/flyinghead/flycast/assets/91744319/a6820af6-3e89-4fa8-85d3-40305f463d01)
![2](https://github.com/flyinghead/flycast/assets/91744319/9844bcd1-0436-474e-bcb6-19352524dffd)

Video:

https://youtu.be/p5ag2y_jsAs

**Comment by flyinghead** [comment]
Fixed in the latest master build
