### ISSUE TITLE
Crashes in Omikron - The Nomad Soul

### ISSUE THREAD

**Issue by BacklogChallenger** [flyinghead/flycast#149]
On the Retroarch-Discord they told me to tell you this here: Omikron - The Nomad Soul crashes on the Flycast-core in Retroarch right after the intro cutscene, doesnt even display the main menu. Most of the time it just hangs, sometimes (rarely) it crashes the whole application.
To be fair, not a single emulator out there plays this game all the way through. Would be nice to have at least one working.

**Comment by flyinghead** [comment]
Could you try this game with the standalone flycast version? I just played for a couple of minutes and it didn't crash. I was able to get to Kayl's appartment without issue.
