### ISSUE TITLE
Flycast IOS is crashing when I’m starting the game 

### ISSUE THREAD

**Issue by Rayman1995** [flyinghead/flycast#1490]
Hello, when I’m starting the game on Flycast, it’s crashing, even when I’m starting BIOS, can you please fix this???

**Comment by flyinghead** [comment]
Are you using AltServer, or another utility to allow JIT code generation?

This is required for iOS.
You can check if JIT is enabled in Settings > About.

**Comment by Rayman1995** [comment]
Oh, I’m not using AltServer

**Comment by Rayman1995** [comment]
Flycast needs a JitStreamer??

**Comment by flyinghead** [comment]
I haven't used JitStreamer personally but it looks like an alternative to AltServer so it should work.

**Comment by Rayman1995** [comment]
Oh ok
