### ISSUE TITLE
Rumble not working in  slot A

### ISSUE THREAD

**Issue by nexus382** [flyinghead/flycast#1491]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  windows and android this was tested on.

Github hash: 

Hardware:  dell g7 7700 win 11, and retroid pocket 4 pro

**_Description of the Issue_**

Vibrate pack dosnt work in slot 1.

**_Debugging Steps Tested_**

  * put rumble pack in slot 1.. vmu in slot 2 [NOTE* even when vmu is in slot 2, you can see the vmu on screen as I always run vmu on screen, and this was my set up for a few months, non working vibrate pack in slot 1, vmu in slot 2.]
  * open crazy taxi 2 in game pause menu/ 4 wheel thunder options menu[these were just 2 games I tested as they had vibration on both platforms]
  * verify vibrations greyed out
  * swap vibrate to slot 2 and vmu to slot 1
  * go back and cerify vibrate function is not greyed out any more and works.

**_Logs Gathered_**

```


Sorry...no


```

**_Screenshots_**

![20240425_005724](https://github.com/flyinghead/flycast/assets/81545086/beaab11b-c36e-4b98-bd29-5458ce4d59bc)

![20240425_005653](https://github.com/flyinghead/flycast/assets/81545086/09933752-0138-4508-ab74-abf9fd5bae19)

**Comment by flyinghead** [comment]
As previously said, this is a game limitation
