### ISSUE TITLE
FPS counter inconsistent - Ecco The Dolphin - Defender Of The Future 

### ISSUE THREAD

**Issue by user18081972** [flyinghead/flycast#1495]
_Platform / OS / Hardware:_ 
Windows 11

_Github hash:_ 
966ff3767

_Hardware:_ 
nvidia 3080
intel i9 11900kf

**_Description of the Issue_**
The FPS counter in Flycast reports 33.3fps for the game when Full Frame Buffer emulation is off, and 60fps when Full Frame Buffer Emulation is on.

**_Debugging Steps Tested_**
Either OpenGL or Vulkan, vsync either on or off. Seems to make no difference.
Enable native framerate counter in emulator settings
enable Full Frame Buffer emulation, notice 60fps.
disable Full Frame Buffer emulation, notice 33.3fps

**_Logs Gathered_**

**_Screenshots_**
video
https://github.com/flyinghead/flycast/assets/124319511/0e17e758-fd6e-4de6-8f9c-f9f6dfd78abf

**Comment by flyinghead** [comment]
This is a 30 FPS game.
When Full Framebuffer Emulation is disabled, the FPS counter reports the number of renders per second, which corresponds to the real frame rate of the emulator.
When Full Framebuffer Emulation is enabled, the FPS counter reports the number of VBlank per second (which is always 60). This is also the actual frame rate of the emulator in this mode.
