### ISSUE TITLE
South Park: Chefs Luv Shack Keeps Flickering

### ISSUE THREAD

**Issue by zuppardi86** [flyinghead/flycast#1496]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: RetroArch, Windows 11, GTX 1660 Super with i7-12700K Processor

Github hash: 

Hardware: 

**_Description of the Issue_**

When the game is loaded after the BIOS screen the game works but it flickers non stop.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

I tried to take a screenshot but RetroArch and/or Launhbox will not provide a screenshot of this issue.

**Comment by flyinghead** [comment]
Enable `Video > Delay Frame Swapping`

**Comment by zuppardi86** [comment]
Can you do this in RetroArch?

**Comment by zuppardi86** [comment]
Nevermind I got it. Thank you so much!
