### ISSUE TITLE
[Mali G68] Sonic Adventure(US) corrupted texture flickering when running on per-pixel transparency

### ISSUE THREAD

**Issue by Hotate90** [flyinghead/flycast#1497]
OS: Android 14, One UI 6.0

Github hash: https://github.com/flyinghead/flycast/commit/d46b181

Hardware: Samsung Galaxy Tab S9 FE (Exynos 1380, Mali G68 MP5, 8GBs RAM)

**_Description of the Issue_**

(VULKAN) When running on per-pixel transparency, there's a lot of corrupted texture flickering. This doesn't happen with the other two transparency modes and per-strip is the most stable, however it breaks a bit of the game's geometry, including Sonic himself. Game runs at full speed with no other graphic glitches to speak of otherwise. This issue is more apparent when running the game with the 60FPS mod - vanilla version flickers on menus but normalizes during gameplay. 60FPS version flickers everywhere.

Haven't tested other games to check if these issues are game-specific or widespread throughout.

**_Debugging Steps Tested_**

  * Ran the game with and without widescreen patches, glitch still occurs at native aspect ratio.
  * Tried resolutions ranging from half to 1.5 upscaled. Half native resolution seems to help mitigate the issue.
  * Ran the game with Native Depth Interpolation on and off. No difference.
  * Adding/removing texture layers and dumping textures to VRAM made no difference.

**_Screenshots_**

![Screenshot_20240428_014143_Flycast](https://github.com/flyinghead/flycast/assets/138707516/9d381737-74e2-4710-9885-37315954e629)
![Screenshot_20240428_014621_Flycast](https://github.com/flyinghead/flycast/assets/138707516/22352d25-2921-4ee0-86ba-f0aa80410c07)

**Comment by flyinghead** [comment]
This is an issue with your GPU or GPU driver. There are many issues in per-pixel on mobile devices in general, and with Mali GPUs in particular.
See #1234, #1014 and #1356.

**Comment by dantesquivel** [comment]
> OS: Android 14, One UI 6.0
> 
> Github hash: [d46b181](https://github.com/flyinghead/flycast/commit/d46b181)
> 
> Hardware: Samsung Galaxy Tab S9 FE (Exynos 1380, Mali G68 MP5, 8GBs RAM)
> 
> **_Description of the Issue_**
> 
> (VULKAN) When running on per-pixel transparency, there's a lot of corrupted texture flickering. This doesn't happen with the other two transparency modes and per-strip is the most stable, however it breaks a bit of the game's geometry, including Sonic himself. Game runs at full speed with no other graphic glitches to speak of otherwise. This issue is more apparent when running the game with the 60FPS mod - vanilla version flickers on menus but normalizes during gameplay. 60FPS version flickers everywhere.
> 
> Haven't tested other games to check if these issues are game-specific or widespread throughout.
> 
> **_Debugging Steps Tested_**
> 
> * Ran the game with and without widescreen patches, glitch still occurs at native aspect ratio.
> * Tried resolutions ranging from half to 1.5 upscaled. Half native resolution seems to help mitigate the issue.
> * Ran the game with Native Depth Interpolation on and off. No difference.
> * Adding/removing texture layers and dumping textures to VRAM made no difference.
> 
> **_Screenshots_**
> 
> ![Screenshot_20240428_014143_Flycast](https://private-user-images.githubusercontent.com/138707516/327019254-9d381737-74e2-4710-9885-37315954e629.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDcyMTksIm5iZiI6MTczMzM0NjkxOSwicGF0aCI6Ii8xMzg3MDc1MTYvMzI3MDE5MjU0LTlkMzgxNzM3LTc0ZTItNDcxMC05ODg1LTM3MzE1OTU0ZTYyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQyMTE1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDc2NzY5MDRhNDJmYmM4YTE0MGFmYzViNzVmM2MzMDZjZjA3MzI2MTMwMzhmN2IzNjE3OTVjZWRmY2Y1NDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l9cna5mFi8LL_lTO1GEYdinkY3qCQuq1xCN_Y6c6YhY) ![Screenshot_20240428_014621_Flycast](https://private-user-images.githubusercontent.com/138707516/327019257-22352d25-2921-4ee0-86ba-f0aa80410c07.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDcyMTksIm5iZiI6MTczMzM0NjkxOSwicGF0aCI6Ii8xMzg3MDc1MTYvMzI3MDE5MjU3LTIyMzUyZDI1LTI5MjEtNGVlMC04NmJhLWYwYWE4MDQxMGMwNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQyMTE1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzJiZTFkN2M1NjNiYTRkODMyMTk2NGZlNTU2Zjc4MjQyZWNmOTNhM2JhMjMxZmJmNGFkMTY2NjE3OTM1ZTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iyTaLxqhmCzPEcNKzDMmw0kM6BEo02ouADWF1GpVuzM)

I have this exact same issue on a Mali G55 - did you ever find a solution?
