### ISSUE TITLE
System options not saved to VMU in Gauntlet Legends

### ISSUE THREAD

**Issue by wiesshund** [flyinghead/flycast#150]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  PC / Windows 10 / Ryzen 5 1500x, RX 580x, 32gb RAM

Github hash: flycast-win_x64-fast-62a1e296700a75fdb758662959baa8b8f5e0a642

Hardware: 

**_Description of the Issue_**
System options not saved to VMU in Gauntlet Legends
(may possibly be other games as well)

Checked against demul and nullDC to make sure i was not mistaken
that the prefs were saved to the VMU

**_Debugging Steps Tested_**
Start game
Pick options, set options
create and save a player
exit flycast
relaunch flycast
player is saved to VMU, system options are not
They would normally be saved to the VMU
sound, music, controller, vibration, screen scan not being saved

**_Logs Gathered_**
0:00:000 sdl/sdl.cpp:69 N[INPUT]: Disabling XInput, using DirectInput
00:00:384 rend/gles/imgui_impl_opengl3.cpp:309 W[RENDERER]: 
00:00:385 rend/gles/imgui_impl_opengl3.cpp:309 W[RENDERER]: 
00:00:386 rend/gles/imgui_impl_opengl3.cpp:327 W[RENDERER]: 
00:07:079 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:07:103 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:07:134 ./nullDC.cpp:106 N[BOOT]: Game ID is [T9710N]

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
I haven't been able to reproduce this problem, using the exact same steps.
I set sound to mono and screen scan to super overscan, then create/save a new character.
In a new flycast session I load this character and my sound and screen scan settings are correctly restored.

**Comment by wiesshund** [comment]
hmm
Was not working
So, i created a new character, made a new save, saved it on the 2nd VMU
it worked
So i copied the original save to the 2nd VMU, reformatted VMU 1, then copied the save back
now it works

So i guess something glitched when it made the VMU or the save the 1st time around, or something you improved or what not between the time the VMU was made and now
Sorry for the bug report
