### ISSUE TITLE
Should we wait for the Flycast version 1.2 update? In the future, will it be possible to run Windows ME programs on the Flycast lite version?

### ISSUE THREAD

**Issue by Temixson** [flyinghead/flycast#1501]
There are no analogues to the Flycast program version 1.2, and the presence of emulation for running Windows programs will turn the TV box into a full-fledged PC

**Comment by Temixson** [comment]
Flycast version 1.2 has two main problems.
1. Poor gamepad support.
2. Dark screen if you have root rights.
All these problems were solved in older versions of Flycast.

**Comment by flyinghead** [comment]
The current version of Flycast is 2.3.
Version 1.2 is more than 3 years old.
I don't understand your request.

**Comment by Temixson** [comment]
Minimum system requirements for World of Warcraft: Windows 98/ME/2000/XP, Intel Pentium III or AMD Athlon 800 MG c; 256 MB RAM; 32 MB 3D graphics accelerator with gr. NVIDIA GeForse 2 class coprocessor or higher; 4 GB free hard disk space; sound card compatible with DirectX 9.0c; 4-disk CD-ROM drive; Internet connection (at least 56 kbit/s).

Theoretically, World Of Warcraft can be run on Flycast 1.2 using Vulkan?

**Comment by CarterJBurke** [comment]
this does not make sense at all. you assume flycast is a type of winulator from the fact that some games use a custom windows CE OS, but it isnt. what is programmed to do is run NAOMI1/2 Dreamcast, anything with a SH4 and a PVR2 GPU. so no, unless it was ported to dreamcast, i do not see this happening at all.

**Comment by flyinghead** [comment]
As CarterJBurke rightly said, Flycast emulates the Dreamcast/Naomi architecture and nothing else.

**Comment by Temixson** [comment]
In the Emuelec environment, we could see not just console emulators, but also some kind of operating systems using their software.

**Comment by CarterJBurke** [comment]
you realize flycast is not like MAME or retroarch at all, it is a emulator for sega naomi and dreamcast based systems. and for developing drivers for other systems takes ALOT of work, the reason flycast even emulates NAOMI 2 at all is the fact the SDK for it got leaked. i do not believe you sincerely know how emulators are created. its not like you could wave a magic wand and you have a flawless working program, it requires you to study game code and BIOS code to see what writes where, and hopefully, some documentation in the form of an SDK or ref sheet pops up to help with how the machine works.
