### ISSUE TITLE
The XBOX console can be called Dreamcast 2, since SEGA participated in its creation, is it possible to create an emulator for this console in the future?

### ISSUE THREAD

**Issue by Temixson** [flyinghead/flycast#1502]
XBOX is a Pentium III computer and a console, one system will allow you to run Portable Windows programs on one emulator?
Everyone will forget about the Dreamcast as soon as mobile devices can emulate the PS2 with a game base exceeding 4000. XBOX is interesting precisely as a personal PC, this is a kind of analogy with Steam.
World Of Warcraft is already being played on mobile devices through emulation.

**Comment by cinnamonmatexfce** [comment]
Why on Earth you keep insist on requesting Flycast to perform Windows emulation??? 😅

**Comment by CarterJBurke** [comment]
i do not think you see to understand how emulation works. it not just a simple thing to do, the XBOX is a much more complicated beast than a DC or naomi, and does not share anything with it. sega hikaru emulation is more possible than this.

**Comment by flyinghead** [comment]
Not planned. This is ridiculous.
