### ISSUE TITLE
Flycast crashes immediately after the window appears

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1503]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: ff33ff2
2d4684a: Cannot reproduce.

For some reason flycast crashes in my environment.
Use 2d4684a's emu.cfg to get the logs. Send the crash log at the same time.
The following error was recorded in the log.

windows/fault_handler.cpp:146 E[COMMON]: [GPF] PC 00007ff700e85c3c unhandled access to 00000204215ccd93

After building and examining the source code, I found that an assertion error occurred at line 2483 of imgui_draw.cpp.

**Comment by flyinghead** [comment]
I think I know why this crash happens. I suppose you are on a Japanese or Korean system and Flycast then loads additional Asian glyphs from local Windows fonts.
However the `FontNo` index isn't reset to 0 when loading the new Font Awesome symbols.

**Comment by flyinghead** [comment]
Should be fixed in the latest dev build

**Comment by kihato** [comment]
Thanks! It now starts without crashing.
