### ISSUE TITLE
Flycast crashes on Pi 5 when using AI Service Translation Feature

### ISSUE THREAD

**Issue by mrobss** [flyinghead/flycast#1504]
Platform / OS / Hardware: 
Pi 5 - RetroPie
using lr-flycast-dev

Grabbed the latest update from source on 5/5/2024.
RetroPie Setup Script: 4.8.7

Hardware: 
Raspberry Pi 5

This is what I'm using in my retroarch.cfg:
ai_service_enable = "true"
ai_service_mode = "0"
ai_service_pause = "true"
ai_service_source_lang = "0"
ai_service_target_lang = "1"
ai_service_url = "http://ztranslate.net/service?api_key=HEREISMYKEY"
input_ai_service = "t"
input_ai_service_axis = "+5"
input_ai_service_btn = "7"
input_ai_service_mbtn = "nul"
settings_show_ai_service = "true"

As soon as I trigger the translation feature, the game crashes back to emulationstation. 

This worked just fine on the Pi 4 with lr-flycast

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

**Comment by flyinghead** [comment]
Might be a duplicate #1418 or #1419. A number of issues have been reported when using the AI translation service, and they all were retroarch issues. You didn't mention which version of RA you're using.
Can you check other gpu-accelerated cores?

**Comment by mrobss** [comment]
Seems to crash on N64 and PSP emulators also.

**Comment by flyinghead** [comment]
Then it points to a problem with RetroArch itself, not the cores.
