### ISSUE TITLE
Sega Strike Fighter (NAOMI) skybox is red during instructions, more likely a regression 

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1506]
Github hash: c53a1c4

Hardware: Windows 11, AMD Ryzen 5600H @3.3GHz, Nvidia RTX 3050ti Laptop GPU

During the flght instructions, the skybox should be black instead its completely red 

![Flycast - Sega Strike Fighter 5_8_2024 2_25_45 PM](https://github.com/flyinghead/flycast/assets/91135037/a58d8a6d-03b1-4f3c-a116-b8ad53628ff7)

**Comment by flyinghead** [comment]
No issue with OpenGL or Vulkan here. Which API are you using? Have you tried others?

**Comment by TheCoolPup** [comment]
Using vulkan with per pixel

**Comment by flyinghead** [comment]
can't reproduce
