### ISSUE TITLE
Mars TV (Naomi) - freeze for a certain amount of time

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1508]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: c53a1c4

It seems to freeze every time the TV station producer starts speaking.
It doesn't freeze completely, but it freezes for about 35 seconds and then unfreezes.
This bug also seems to have existed for a long time.

![MarsTV](https://github.com/flyinghead/flycast/assets/14366233/b9f2e52c-30a9-42bf-843f-2da8a1a88379)

**Comment by flyinghead** [comment]
Yes, this is a very old bug.

**Comment by TheCoolPup** [comment]
I wonder if it’s something to do with a bad dump

**Comment by flyinghead** [comment]
I think i remember this game being marked as a bad dump but I don't see it mentioned in mame anymore?
The rom I'm using is the same as the one referenced in mame (same CRC).

**Comment by kihato** [comment]
This bug may be the same as the one in the OP of #1058 where the image does not update for a certain period of time.
I don't know why, but it seems that in both games, `msg.type` becomes `NoMessage` on line 139 of `Render_if.cpp`.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build.

The game is writing to the BIOS rom, and presumably also erroneously reading from it. So I tried various naomi bios versions and it looks like version D is working fine. So it could be a game bug, triggered by an unexpected bios version. Several other console and arcade games have similar bugs.

**Comment by kihato** [comment]
Thanks for your great work!

**Comment by cdmn1** [comment]
randomly stumbled onto this, just wanted to mention that this happens on real hardware as well using the common H/multi bios

**Comment by flyinghead** [comment]
Thanks for your feedback. All this points to a game bug, and I assume it would be fixed by using BIOS revision D on real hardware as well.
