### ISSUE TITLE
Neogeo Battle coliseum Atomiswave port crashing

### ISSUE THREAD

**Issue by jvhellraiser** [flyinghead/flycast#151]
Neogeo Battle coliseum Atomiswave port crashing in the latest build
i notice while playing the game that the game has issues with texture
in stages not only that it keeps crashing while playing it, just start the 
game and play a couple of times Flycast will close automatically when
crash happens..flycast.log is empty after crash not sure if there's another
way to get a log on this error..not sure if this happens with all the atomiswave
port's since for now i have only tested this game...

**Comment by MagnusPrime12** [comment]
I can confirm this. But mine crashes when a battle ends. 3/3/21 build

**Comment by flyinghead** [comment]
I fixed a race condition crash related to texture updating, which might be the issue here: https://github.com/flyinghead/flycast/commit/0e20d5976bcb75b2cb69307e3e872b16c645be50

Check with the next build.

**Comment by MagnusPrime12** [comment]
@flyinghead , I checked, ran it for 30 minutes without crash. Looks like you solved the issue :)

**Comment by flyinghead** [comment]
That's great news! Thanks for testing.
