### ISSUE TITLE
Metropolis Street Racer partly freezed screen when mirror is set to true (vulkan only) 

### ISSUE THREAD

**Issue by OriginalBootZ** [flyinghead/flycast#1511]
Platform / OS / Hardware: 

Hardware: 
Lenovo Legion 5 Slim, AMD Ryzen 7 7840HS w/ Radeon 780M Graphics, NVIDIA GeForce RTX 4070 (used by Retroarch and Flycast)

Description:
After changing the graphics driver to Vulkan on both Retroarch and Flycast (Windows Executable), when changing the game settings to show the rear mirror and then push the dpad up arrow to change the view to front chasing camera in a race, the main screen stalls while the mirror gets updated normally. 

**_Debugging Steps Tested_**
  * Setting graphics driver to Vulkan
  * Adjusting settings for mirror to on
  * Start any type of race
  
**_Screenshots_**

<img width="475" alt="msr-screen" src="https://github.com/flyinghead/flycast/assets/9661278/5ba9aab3-f310-4447-9a66-c1b7574d30b9">
<img width="257" alt="msr-setting" src="https://github.com/flyinghead/flycast/assets/9661278/92f74657-d87c-434a-b887-ad02001d539e">

**Comment by flyinghead** [comment]
This is a known current limitation of the Vulkan driver regarding partial renders. A fix is being worked on but it's not ready yet.

**Comment by OriginalBootZ** [comment]
Allright, of that is available I will give it a spin and let you know

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OriginalBootZ** [comment]
Confirmed working in latest DEV build!
________________________________
