### ISSUE TITLE
NEW UI like duckstation or Lime3DS 

### ISSUE THREAD

**Issue by Dwisantosobk** [flyinghead/flycast#1512]
Sorry bad English but i m always confused with flycast ui. And I hope this emu get simple ui like duckstation or lime3ds/citra.
![Screenshot_20240514_073201_Lime3DS](https://github.com/flyinghead/flycast/assets/86861327/976faa71-4f23-41a8-9635-a1626ba5c967)
![Screenshot_20240514_073147_DuckStation](https://github.com/flyinghead/flycast/assets/86861327/a5acb761-4f51-4a33-8185-18087107b35b)

**Comment by flyinghead** [comment]
Improving Flycast, including its UI, is a general goal. Issues are for bug reports and specific enhancement requests.
