### ISSUE TITLE
Hikaru emulation support

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [flyinghead/flycast#1515]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hikaru hardware is similar to Naomi, and I’d like to play planet harrier, which runs on Hikaru hardware/

**Describe alternatives you've considered**
do you know how to scan cards for love and berry on retroarch?

**Additional context**

**Comment by TheCoolPup** [comment]
https://github.com/flyinghead/flycast/issues/110 
same feature has been asked multiple times over, just PLEASE, learn patience

**Comment by flyinghead** [comment]
Duplicate of #110
