### ISSUE TITLE
Smlg99 and wsbbgd axis mapping issue

### ISSUE THREAD

**Issue by CaptainKoloth554** [flyinghead/flycast#152]
On the standalone Android app, latest nightly, both World Series Baseball and Super Major League 99 have their analog axes inverted and there is no way to remap them properly. That is to say, x and y are correct, but up goes down, left goes right, etc.

**Comment by flyinghead** [comment]
This should be fixed in the latest build

**Comment by CaptainKoloth554** [comment]
Thank you!
