### ISSUE TITLE
Shenmue not starting 

### ISSUE THREAD

**Issue by YouteeM** [flyinghead/flycast#1520]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: android 13

Github hash: 

Hardware: Xiaomi pad 5 

**_Description of the Issue_**
The game not starting 
Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Screenshot_2024-05-19-17-45-11-094_com.flycast.emulator.jpg](https://github.com/flyinghead/flycast/assets/97440514/cb0093c0-29c0-4eb5-a306-714dad60ee5d)

**Comment by flyinghead** [comment]
This looks like an issue with your GPU driver.

**Comment by YouteeM** [comment]
> This looks like an issue with your GPU driver.

I fixed by disabling wide-screen cheat and just enabling wide-screen mod

**Comment by flyinghead** [comment]
Thanks for the information.
This is very likely due to using .CDI instead of GDI/CUE/CHD. The widescreen cheat only works with the latter and will crash when using a CDI.
For this reason and others, I highly recommend NOT to use CDI.
