### ISSUE TITLE
Scrolling in graphical interface does not keep the page position

### ISSUE THREAD

**Issue by dezraj** [flyinghead/flycast#1522]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10

Github hash: [1256680](https://github.com/flyinghead/flycast/commit/1256680)

Hardware: i5-10400, GTX 1660Ti

**_Description of the Issue_**

The scroll position is not kept in the graphical interface. It always resets to the top, which makes it very difficult to see and set up the configurations in the settings menu. You can picture this issue in the short video clip below:

https://github.com/flyinghead/flycast/assets/27839354/a61b3955-8f20-41a3-aac9-33c5c715c333

It also works like this in full-screen mode.

It would be better if the program could keep the scrolling position to help us browse the graphical interface.

Thank you in advance for for your attention.

**Comment by flyinghead** [comment]
This is probably due to your gamepad analog stick, which can be used to scroll up and down.
Try to increase the gamepad deadzone to avoid scrolling when at rest.

**Comment by dezraj** [comment]
> This is probably due to your gamepad analog stick, which can be used to scroll up and down. Try to increase the gamepad deadzone to avoid scrolling when at rest.

Thank you so much for the fast reply.

You are correct, it was an issue with my left analog stick deadzone. I'm sorry for opening an issue without better checking the devices. It's just that I never thought the controller deadzone could interfere in that, and I am also lacking another controller for testing.

Anyway, it's an Xbox 360 wireless controller. I adjusted its deadzone to 20% and now the analog stick no longer hinders the mouse scrolling in the interface. I just hope it doesn't jeopardize the movement in the games.

By the way, changing the deadzone setting does not take effect immediately. I have to restart the program in order to have the change applied. I'm not sure if this is intended or if it could be changed though.

Thank you again for your help. If you think the issue is resolved you can close it at your will.
