### ISSUE TITLE
World Series Baseball and Super Major League 99 crashes in Retroarch core

### ISSUE THREAD

**Issue by CaptainKoloth554** [flyinghead/flycast#153]
These both load in the Android Retroarch core but then crash almost instantly. The post-Naomi splash screen loading screen will come up so the rom is getting properly recognized, but it will then crash. Once I got to 3D graphics for an instant on smlg99.

**Comment by flyinghead** [comment]
If this issue is specific to the libretro core, it should be open on the corresponding github: https://github.com/libretro/flycast/issues
