### ISSUE TITLE
Hopper is not connected (kingyo)

### ISSUE THREAD

**Issue by jolumatro** [flyinghead/flycast#1530]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Windows 10 / Sega SP

Github hash: 

Hardware: AMD Radeon(TM) RX Vega 10 Graphics

**_Description of the Issue_**

Hopper games report hopper not connected, no related documentation found anywhere. Tested with kingyo

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

**_Screenshots_**
![image](https://github.com/flyinghead/flycast/assets/82586766/c8f1834b-fd5b-4204-bfe7-698675da9bca)

**Comment by TheCoolPup** [comment]
It’s working fine for me, what version of Flycast are you using?

**Comment by jolumatro** [comment]
Hello,

Just tried with 2.3 first
![image](https://github.com/flyinghead/flycast/assets/82586766/2e44d226-52d1-4137-b6de-0a7516ed2ca7)
and now same result with 
![image](https://github.com/flyinghead/flycast/assets/82586766/91267b61-8327-4a35-b3a9-87d2eb3fc1fc)

**Comment by TheCoolPup** [comment]
Seems you most likely missing the hopper.zip file

**Comment by jolumatro** [comment]
Yes, I do not have the hopper.zip file

Sorry, the documentation is very limited for this topic, I am looking for it now.

Thank you

**Comment by flyinghead** [comment]
hopper.zip isn't needed

**Comment by TheCoolPup** [comment]
Strange, thought Flycast needed that file

**Comment by jolumatro** [comment]
Yes, same result with hopper.zip
![image](https://github.com/flyinghead/flycast/assets/82586766/59faf619-de5e-414d-8a2b-eb8fb9d89a14)

**Comment by flyinghead** [comment]
I just did a quick test and it works fine for me too.
Try deleting the files `kingyo.zip.nvmem` and `kingyo.zip-jp.eeprom` from the data directory

**Comment by jolumatro** [comment]
That did the trick
![image](https://github.com/flyinghead/flycast/assets/82586766/d589f057-48cd-4d0b-8d13-4358f66304cd)
Thank you so much!

**Comment by TheCoolPup** [comment]
You should try out Puyo Puyo the medal as well, pretty cool game

**Comment by jolumatro** [comment]
Also, deleting all the data files fixed the rest of the hopper titles (They were stuck in the settings screen)
![image](https://github.com/flyinghead/flycast/assets/82586766/2a49a9d4-691d-4d08-b42c-90ec9644c4d1)
