### ISSUE TITLE
Disable upscaling for 2D sprites and backgrounds

### ISSUE THREAD

**Issue by Rex000** [flyinghead/flycast#1537]
2D sprites appear really botched with big square pixels upon increasing the internal resolution. There should be an option to disable their upscaling when internal resolution is increased above native.

**Comment by flyinghead** [comment]
Can you post a screenshot or picture showing the issue?
And detail what should be done to fix it?

**Comment by Rex000** [comment]
It's a known thing. When you upscale 2D sprites they look super pixelated. If I knew how to fix it I'd have already done it.

Btw, PCSX2 has this feature so you can look into it.

**Comment by Rex000** [comment]
It's a known thing. When you upscale, 2D sprites or backgrounds look super pixelated. Idk if what I'm asking is possible, but if not then perhaps an option to turn off upscaling as a whole for any game that has 2D sprites? Because it's a constant chore to switch between upscaled and native resolution when switching between 2D and 3D games.

**Comment by flyinghead** [comment]
I'm assuming 2D sprites means pixel art textures displayed in 2D. But I don't see why they would be more pixelated when upscaling. They should look exactly the same.
Native (640x480):
![SFA3-640x480](https://github.com/flyinghead/flycast/assets/16261910/2c1890c4-e424-49f0-be6f-663e8d0b985d)
Upscaled x3 (2560x1440):
![SFA3-2560x1440](https://github.com/flyinghead/flycast/assets/16261910/e6a87b2e-93de-4281-a731-1af3453ea71a)
