### ISSUE TITLE
zstd-1.5.5 is presented in latest commit instead of zstd-1.5.6 as expected

### ISSUE THREAD

**Issue by Kelvfimer** [flyinghead/flycast#1538]
Platform / OS / Hardware: Emuelec 4.8 Linux odroid n2+ 4GB

Github hash: 

https://github.com/flyinghead/flycast/commit/95de83431b9a9a1a3cc3dd042e72a3c10154480c

Hardware: Emuelec 4.8 odroid n2+ 4GB

**_Description of the Issue_**
When building cmake is looking for zstd-1.5.6 but the source files provides zstd-1.5.5

**_Debugging Steps Tested_**
Checking the source files, the one downloaded by the toolchain using commit https://github.com/flyinghead/flycast/commit/95de83431b9a9a1a3cc3dd042e72a3c10154480c is zstd-1.5.5

**_Logs Gathered_**

CMake Error at CMakeLists.txt:624 (get_target_property):
  get_target_property() called with non-existent target "libzstd_static".

CMake Error at core/deps/libzip/cmake/Findzstd.cmake:123 (file):
  file STRINGS file
  "/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycast-95de83431b9a9a1a3cc3dd042e72a3c10154480c/core/deps/libchdr/deps/zstd-1.5.6/lib/zstd.h"
  cannot be read.
Call Stack (most recent call first):
  core/deps/libzip/CMakeLists.txt:242 (find_package)

CMake Error at core/deps/libzip/cmake/Findzstd.cmake:128 (file):
  file STRINGS file
  "/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycast-95de83431b9a9a1a3cc3dd042e72a3c10154480c/core/deps/libchdr/deps/zstd-1.5.6/lib/zstd.h"
  cannot be read.
Call Stack (most recent call first):
  core/deps/libzip/CMakeLists.txt:242 (find_package)

CMake Error at core/deps/libzip/cmake/Findzstd.cmake:133 (file):
  file STRINGS file
  "/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycast-95de83431b9a9a1a3cc3dd042e72a3c10154480c/core/deps/libchdr/deps/zstd-1.5.6/lib/zstd.h"
  cannot be read.
Call Stack (most recent call first):
  core/deps/libzip/CMakeLists.txt:242 (find_package)

**Comment by flyinghead** [comment]
The libchdr dependency does provide zstd-1.5.6 in the commit you mention. You probably need to do a `git submodule update` to update all dependencies including libchdr.

**Comment by Kelvfimer** [comment]
Strange, submodule was there. I deleted everything and it seems to work. thx so much.
