### ISSUE TITLE
Sega Strike Fighter mapping 

### ISSUE THREAD

**Issue by CaptainKoloth554** [flyinghead/flycast#154]
In sstrkfgt on the Android nightly, the axes work properly when mapped to a controller, but the analog control axes for touch control are incorrect for gameplay and cannot be remapped.

**Comment by flyinghead** [comment]
This should be fixed in the latest build

**Comment by CaptainKoloth554** [comment]
Thanks!

**Comment by flyinghead** [comment]
Note that Sega Strike Fighter uses 4 analog axes:

- Aileron: left joystick X axis
- Elevator: left joystick Y axis
- Rudder: right joystick X axis
- Thrust: right trigger

So the Rudder axis will not be available on the virtual gamepad.

**Comment by CaptainKoloth554** [comment]
Right. It's playable without rudder though.
