### ISSUE TITLE
Vulkan/Per-Pixel support for iOS app

### ISSUE THREAD

**Issue by justing6** [flyinghead/flycast#1541]
**Is your feature request related to a problem? Please describe.**
Some games like Sonic Adventure require Per-Pixel transparent sorting to avoid graphical issues. Newer iOS devices (especially iPads) should be powerful enough to run Per-Pixel, at least at native Dreamcast resolution.

**Describe the solution you'd like**
As far as I know Per-Pixel is limited to Vulkan, so either integrating Vulkan into the iOS client as an alternative to Metal or implementing Per-Pixel into the Metal renderer would solve this issue.

**Describe alternatives you've considered**
I can’t think of any way to work around this.

**Additional context**

**Comment by flyinghead** [comment]
Unfortunately Vulkan on iOS doesn't support stores and atomic operations in the fragment shader, which is required for per-pixel.
The alternative is to develop yet another renderer using the proprietary Metal API but I don't have any such plan in the foreseeable future. Contributions are welcome of course.

**Comment by justing6** [comment]
Closing as this level of effort is not currently on the roadmap.
