### ISSUE TITLE
Microphone not detected

### ISSUE THREAD

**Issue by Redged1989** [flyinghead/flycast#1548]
Checked the ini file, but can't see any way to set a device for my mic. Not sure what one Flycast is picking, only that whatever it is is not working as it does not detect my voice.

Would appreciate any guidance that can be offered, would love to be able to continue playing Seaman but it is impossible without being able to converse

**Comment by flyinghead** [comment]
Re-open if you're still having this issue but more information is needed about your setup, what you've tried, any error message, etc.
