### ISSUE TITLE
FPS always Cap at half (30fps) on switchroot LineageOS 17.1

### ISSUE THREAD

**Issue by tabnk** [flyinghead/flycast#155]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
switchroot LineageOS 17.1

Github hash: 

1ce40ff (Latest android native app)
Hardware: 

NSW

**_Description of the Issue_**

FPS always Cap at half (30fps). If will return to 60fps, ONLY if I manually touch the LCD screen.

**_Debugging Steps Tested_**

Just any game.

**Comment by flyinghead** [comment]
Open GL or Vulkan?
Any non-default video setting?
Setting Broadcast to NTSC or cable to VGA makes any difference?
What's your hardware?

**Comment by tabnk** [comment]
Both Vulkan and OpenGL. Broadcast setting was NTSC.  Other all default. 

Nintendo Switch with Lineage OS 17.1 (Android Q) installed in handheld mode.

Only temporary solution was to touch the LCD screen or move the controller. However it will cap the framerate back to 30fps again after loading new stage or changing game scene.

Btw, haven't try to change cable to VGA yet.

**Comment by tabnk** [comment]
Tried cable to VGA but same problem.

https://user-images.githubusercontent.com/10874582/104172526-663eda00-543f-11eb-92b1-6cd5ced4934a.mp4

Attached a video. 

Notice the framerate change from 30fps to 60fps at around 28sec onward.

**Comment by flyinghead** [comment]
For some reason, although you mentioned Switch twice, that didn't register. Sorry about that.

I don't have a switch but I can't reproduce the issue on an android device. Is it a regression? Do you know in which build the problem started?

**Comment by tabnk** [comment]
Found the builds http://flycast-builds.s3.amazonaws.com/android/heads/master-34d8650/flycast-debug-34d8650.apk which cap framerate started. 

Last build without issue was this http://flycast-builds.s3.amazonaws.com/android/heads/master-d960f8e/flycast-debug-d960f8e.apk

I'm don't had build between this d960f8e to this 34d8650 so not sure exactly which commit it happened.

**Comment by tabnk** [comment]
Tried **fh/multi-render** build from http://flycast-builds.s3.amazonaws.com/android/heads/fh/multi-render-c03cf8e/flycast-debug-c03cf8e.apk

This c03cf8e commit also CAP the framerate too.

It's narrow down between d960f8e and c03cf8e commits.

**Comment by flyinghead** [comment]
Thanks for testing. I suspect https://github.com/flyinghead/flycast/commit/c03cf8eb455925150aad5782ee190d2cceae9b0a to be the culprit.

There are new/changed Video settings with the latter builds: Automatic Frame Skipping and Delay Frame Swapping.

Does playing with these options change the frame rate issue?

**Comment by tabnk** [comment]
Using this build http://flycast-builds.s3.amazonaws.com/android/heads/fh/multi-render-c03cf8e/flycast-debug-c03cf8e.apk with Delay Frame Swapping enabled. Same Cap framerate issue.

This build http://flycast-builds.s3.amazonaws.com/android/heads/master-34d8650/flycast-debug-34d8650.apk with Delay Frame Swapping enabled. Same Cap framerate issue.

This build http://flycast-builds.s3.amazonaws.com/android/heads/master-1727413/flycast-debug-1727413.apk with Delay Frame Swapping Enabled and Automatic Frame Skipping (All 3 Options). Same Cap framerate issue.

This build http://flycast-builds.s3.amazonaws.com/android/heads/master-1727413/flycast-debug-1727413.apk with Delay Frame Swapping Disabled and Automatic Frame Skipping (All 3 Options). Same Cap framerate issue.

**Comment by tabnk** [comment]
My current workaround is press a button or move analog stick whenever it started to CAP to 30fps.  Not sure why press a button will temporary fix the issue but at least it doable.

**Comment by tabnk** [comment]
Actually the CAP issue only happen on **Vulkan Renderer** and OpenGL is fine. 

Previously , It was because I changed the renderer from Vulkan to OpenGL without restarting the app. Now I'm using OpenGL as main Renderer even though is much slower (45-60fps) compare to Vulkan . 

Anyway, I think the issue should limit to **Vulkan code path**....

**Comment by flyinghead** [comment]
That clears things up and I think I know what the problem is. It's been reported by other users as well.

**Comment by tabnk** [comment]
Just tested an android 10 phone with snapdragon 855. Same setting and same games with Vulkan Renderer. Game Cap at 30fps too.

Based on others comment (Vulkan Drivers broken on Android 10 (S10) Snapdragon 855) https://www.reddit.com/r/EmulationOnAndroid/comments/ehp9o6/vulkan_drivers_broken_on_android_10_s10/

Maybe even on Android 11 https://www.reddit.com/r/EmulationOnAndroid/comments/j19pgi/android_11/
 
Btw, OpenGL is fine.

**Comment by flyinghead** [comment]
I made some changes regarding Vulkan in this commit: https://github.com/flyinghead/flycast/commit/1a8b25cc34bcb1409b4c8fc8ab18bd8ae40745ae

Notably I went back to using 3 swap chain images instead of 2, which may help performance. Thanks in advance for your feedback.

**Comment by tabnk** [comment]
Android build 1a8b25c not available at https://flyinghead.github.io/flycast-builds/

![image](https://user-images.githubusercontent.com/10874582/106454381-9c62fd00-64c5-11eb-89bb-0cf781bca69d.png)

**Comment by flyinghead** [comment]
It should be available in less than an hour from now

**Comment by tabnk** [comment]
Tested on Nintendo Switch (Android Q), it ran Buttery-Smooth at 60fps with Vulkan renderer.  **No more Cap issue**.  Thank

Also try it on Android Q Phone (with Snapdragon 855), it fixed the same issue too.

**Comment by flyinghead** [comment]
That's great news! Thanks for testing.

**Comment by tabnk** [comment]
Tested a few more days and everything seems fine. Thank.
