### ISSUE TITLE
Spider-Man 2000: is it possible to disable black borders in widescreen mode?

### ISSUE THREAD

**Issue by legluondunet** [flyinghead/flycast#1550]
Platform / OS / Hardware: 
My config:
Manjaro 24.0.0 Wynsdey
Kernel: x86_64 Linux 6.6.30-2-MANJARO
Proc: AMD Ryzen 9 5900HX
GPU: AMD Radeon RX 6600M
Drivers: Mesa 24.0.6
Resolution: 1920x1080
32 Go RAM
DE: Xfce4

**_Description of the Issue_**
When I play Spider-Man 2000 in widescreen mode, there are black borders during 3D cinematics:

![image](https://github.com/flyinghead/flycast/assets/325405/61d1dbee-7f54-46ef-a1b8-0b1519b037a7)

![image](https://github.com/flyinghead/flycast/assets/325405/e61334d0-8689-41b4-b013-39e93452e93e)

Is it possible to inactivate this borders with Flycast?

**Comment by flyinghead** [comment]
No, this isn't possible. This widescreen mode just shows the sides of the screen, which would normally be hidden, but it doesn't do anything else.
