### ISSUE TITLE
Crashes on Startup in MacOS

### ISSUE THREAD

**Issue by PunkBureaucrat** [flyinghead/flycast#1553]
Platform / OS / Hardware: 
macOS 14.4.1 / Macbook Pro M3

Github hash: 95de834

Starting with 95de834 from the master branch Flycast crashes at startup

**_Debugging Steps Tested_**

Checked previous versions and they load fine. Every version after 95de834 crashes

Here is the macOS crash log,

```

Process:               Flycast [87005]
Path:                  /private/var/folders/*/Flycast.app/Contents/MacOS/Flycast
Identifier:            com.flyinghead.Flycast
Version:               v2.3.2 (95de83431)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-06-23 03:27:18.0639 -0400
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        B419DFC3-5E55-5F74-9063-9FDAC5710B67

Sleep/Wake UUID:       8D18AB42-9E15-4A9C-B5E6-58355B2D8BF3

Time Awake Since Boot: 3600000 seconds
Time Since Wake:       1241 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libzstd.1.dylib
Referenced from: <DAA97C60-56DE-3C1A-A5EB-90CB9896172F> /private/var/folders/*/Flycast.app/Contents/MacOS/Flycast
Reason: tried: '/opt/homebrew/*/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libzstd.1.dylib' (no such file), '/opt/homebrew/*/libzstd.1.dylib' (no such file)
(terminated at launch; ignore backtrace)

```

**Comment by scribam** [comment]
Likely a regression from https://github.com/flyinghead/flycast/commit/112e05ed5df03f7655017808051ef8b0e82c66ea

The path looks wrong here:
https://github.com/flyinghead/flycast/actions/runs/9582602306/job/26421937302#step:11:749
> -- Found zstd: /opt/homebrew/opt/zstd/lib/libzstd.dylib (Required is at least version "1.3.6")

**Comment by scribam** [comment]
@PunkBureaucrat does this build work? https://github.com/scribam/flycast/actions/runs/9631852599/artifacts/1628750286 (commit https://github.com/flyinghead/flycast/commit/03ffed98be7e02e2aaa2c960427b4b1c02ef8a05). It uninstalls homebrew's zstd before the build so the correct path is found

**Comment by PunkBureaucrat** [comment]
> @PunkBureaucrat does this build work? https://github.com/scribam/flycast/actions/runs/9631852599/artifacts/1628750286 (commit [03ffed9](https://github.com/flyinghead/flycast/commit/03ffed98be7e02e2aaa2c960427b4b1c02ef8a05)). It uninstalls homebrew's zstd before the build so the correct path is found

No unfortunately it just says "The application “Flycast” can’t be opened." It doesn't say why it can't, but it isn't crashing.

**Comment by flyinghead** [comment]
There's an issue with build artifacts on macOS: the Flycast executable in the app bundle doesn't have execute permissions.
It can be fixed with:
`chmod +x ~/Downloads/Flycast.app/Contents/MacOS/Flycast`

**Comment by PunkBureaucrat** [comment]
> There's an issue with build artifacts on macOS: the Flycast executable in the app bundle doesn't have execute permissions. It can be fixed with: `chmod +x ~/Downloads/Flycast.app/Contents/MacOS/Flycast`

Yep, after I did that, @scribam 's build runs fine. Thanks!

**Comment by flyinghead** [comment]
Should be fixed in the latest `master` build.
Thanks @scribam!

**Comment by PunkBureaucrat** [comment]
Works perfect, thanks!
