### ISSUE TITLE
[Feature Request] per game ID vmu A1

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#1556]
would it be possible to implement a per game ID vmu A1 save option similar to how texture dump folders are created, the standard option for per game vmu A1 doesnt work well for multidisc games as it renames the save to the disc name, so for example in shenmue when you finish disc 1 it asks you to save but you have to rename the save to disc 2 manually to detect it on disc 2, i think if we had the ability for per game ID vmu A1 saves similar to how texture dump folders are created it would bypass this and also ensure a vmu would never get full with various games like the default vmu setting

**Comment by flyinghead** [comment]
Fixed on the `dev` branch
