### ISSUE TITLE
Can I play Dreamcast games on iOS 18b2

### ISSUE THREAD

**Issue by Samuel525432** [flyinghead/flycast#1559]

**Comment by Samuel525432** [comment]
Loaded my game now it crashed for some reason how I can fix that?

https://github.com/user-attachments/assets/b3f402cf-207f-468e-86f5-4bc92420ea33

**Comment by Samuel525432** [comment]
Is there a option I can enable interpreter on the settings?

**Comment by flyinghead** [comment]
Flycast requires JIT to be enabled. This can be done with AltServer or other methods.

**Comment by Samuel525432** [comment]
Well can’t I use TrollStoreJitEnabler or smth?

**Comment by flyinghead** [comment]
> ... or other methods.

Yes
