### ISSUE TITLE
Analog stick disabled on kaillera netplay.  Triggers affect analog stick when on kaillera netplay.  Video included.

### ISSUE THREAD

**Issue by Justase64** [flyinghead/flycast#1560]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Retroarch Kaillera 1.16.0K0
Windows 11 
HP zBook G1 i7 4700 quadro k610
Github hash: 
 

**_Description of the Issue_**

Flycast core works wonderfully on the Retroarch Kaillera netplay fork.  Unfortunately , when in an online game, the analog stick is completely disabled.  And if you press L or R triggers, it will affect the analog stick.  D-pad and face buttons work just fine on netplay.  Here is a quick video of the issue.  When offline, everything functions as it should.  The problem only happens when playing online.
https://www.youtube.com/watch?v=txycjpYDG60

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
https://www.youtube.com/watch?v=txycjpYDG60

**Comment by flyinghead** [comment]
What makes you think that this is a Flycast issue?

**Comment by Justase64** [comment]
We think it may be a general retroarch issue.  I'm sorry.  I am new to this.  I will post to retroarch github.  We are just so hungry for Rush 2049 netplay that doesn't involve Parsec or GGPO rolback lag (when using analog set to full).  We all prefer to play with a set input delay on kaillera.

**Comment by flyinghead** [comment]
I've never heard of this "Retroarch Kaillera netplay fork" but you should probably talk to the author(s).

**Comment by Justase64** [comment]
Yup, last time we spoke with him, he said it was a general RA issue most likely but we will keep the pressure on.  Feel free to delete this thread.  Or do I have to close it?
