### ISSUE TITLE
MK Gold not properly loaded?

### ISSUE THREAD

**Issue by Kiroshi** [flyinghead/flycast#1565]
Platform / OS / Hardware: 
PC/Windows10/I7-7700k GTX970
Github hash: 
7d64554

**_Description of the Issue_**
The first screenshot is from redream emulator, the second one is from flycast.
If you look at the attached screenshots, in the tournament menu, in flycast, you cannot change the characters controller as CPU or HUMAN.
Part of the message on the right of the screen is missing("PRESS PUNCH TO TOGGLE BETWEEN HUMAN OR CPU").

**_Debugging Steps Tested_**

  * Launch MK Gold.
  * Go to TOURNAMENT.
  * Select 4 player tournament.

**_Screenshots_**
Redream:
![1redream](https://github.com/flyinghead/flycast/assets/19382448/7305ccaa-e51b-4906-9acf-a897288121eb)

Flycast:
![2flycast](https://github.com/flyinghead/flycast/assets/19382448/2524050a-772c-49ef-bd79-768c25a315fc)

**Comment by flyinghead** [comment]
Human players need a controller to play with. Try adding more Dreamcast controllers.

**Comment by Kiroshi** [comment]
Indeed, the redream emulator has by default 4 controllers connected, flycast only 1.
Worked after I added a new controller.
