### ISSUE TITLE
If you eject and then insert without registering game content, you will only be able to quit

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1566]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 7d64554

On real hardware, if you close the lid without inserting a disc, you will be taken to the BIOS screen,
but on flycast, there is no game content, so there is nothing to select and you have no choice but to exit.

So as an experiment I tried registering cs.gdi (test_gdis) as game content and setting it to NODISK when selected
and it took me to the BIOS screen.
And when I did this when changing discs, the message below, the same as on the real machine, appeared.

![NODISK](https://github.com/flyinghead/flycast/assets/14366233/400f8587-24bb-40a6-81cc-47fd3cad80e1)

However, since there is probably no opportunity to use this function, would it be better to make it unavailable for insertion?

**Comment by flyinghead** [comment]
Added a Cancel button (`dev` branch)

**Comment by kihato** [comment]
Thanks for adding the cancel button!
