### ISSUE TITLE
Emulator slows down the PC and itself runs slow

### ISSUE THREAD

**Issue by Rex000** [flyinghead/flycast#1567]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Win 10 x64

Github hash: 

Hardware: Core i5 3570k, 8gb ram, Gtx 1080

**_Description of the Issue_**

The emulator slows the PC down. The games running in the emulator are affected too and run slow (fps drops).

**_Debugging Steps Tested_**

Start the emulator
Use the emulator for a bit. Play a game.
After a bit of usage the emulator will feel sluggish, and the games fps will drop as well. 
Even after closing the emulator the PC remains sluggish and slow until a restart is done.

**Comment by Al666v** [comment]
Apply new paste or check your fan if its still spinning. Today i'm also got this issue. And it was actually my Fan has stopped spinning, cleaned it and it runs at full speed again. Its not the Emulator's fault, it was the windows decided to go Power Save mode everytime you open apps.

**Comment by Rex000** [comment]
Pretty sure that's not the issue. All other emulators are running fine.

**Comment by flyinghead** [comment]
Flycast cannot slow your PC down if it's not running!
This is probably an overheating issue (CPU and/or GPU) and power is being limited to prevent damage to the hardware until temperature drops to an acceptable level.

**Comment by Rex000** [comment]
I have already explained above that it happens after running flycast for a bit and continues to happen even after closing it. There is no way to "fix" it other than restarting the system.

And again, how come other emulators like epsxe, duckstation, and even second gen emulators like pcsx2, dolphin don't have this issue? Nor do I have this issue in any native PC games, so far.

**Comment by Rex000** [comment]
I have already explained above that it happens after running flycast for a bit and continues to happen even after closing it. There is no way to "fix" it other than restarting the system.

And again, how come other emulators like epsxe, duckstation, and even second gen emulators like pcsx2, dolphin don't have this issue? Nor do I have this issue in any native PC games, so far.

The only thing I can think of is that it has something to do with how it handles CPU core operations. I'm not a technical person though, I just recall that I read about it somewhere.
