### ISSUE TITLE
Running a game made the CPU slowdown

### ISSUE THREAD

**Issue by Al666v** [flyinghead/flycast#1569]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 IoT Enterprise x64

Github hash: 7d64554

Hardware: Intel i3 1005G1, Intel UHD G1, 12GB RAM

**_Description of the Issue_**

My Laptop can run flycast just fine, but recently the emu seems slowdown the CPU. I can run other emu like PCSX2 just fine but this one is just lowering the clockspeed and cant find out why.

**_Debugging Steps Tested_**

CPU already fullspeed (3,37Ghz), changing to vulkan didnt solve the problem.
Even changing to OpenGL still slowdown the CPU.
Lowering all settings back to native also still gives issues.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```
**_Screenshots_**

![Screenshot (483)](https://github.com/flyinghead/flycast/assets/123358574/88ad26e1-f651-4fe5-9bef-06f13dbd5b6f)

**Comment by flyinghead** [comment]
Flycast isn't lowering the CPU frequency. Windows is doing this, presumably because it doesn't need the full power of your CPU to run Flycast.
This is a good thing.

**Comment by Al666v** [comment]
> Flycast isn't lowering the CPU frequency. Windows is doing this, presumably because it doesn't need the full power of your CPU to run Flycast. This is a good thing.

Yeah but the game run slower than it should.

**Comment by flyinghead** [comment]
Can you check previous Flycast builds to see if they have the issue?
If it's a regression it would be very helpful to know when it started.

**Comment by Al666v** [comment]
> Can you check previous Flycast builds to see if they have the issue? If it's a regression it would be very helpful to know when it started.

I have tried using v2.0, and its still give me the same issue.

**Comment by flyinghead** [comment]
> Yeah but the game run slower than it should.

What are the symptoms?

**Comment by Al666v** [comment]
> > Yeah but the game run slower than it should.
> 
> What are the symptoms?

Audio is choppy
average FPS is 40

That's when i run it with Vulkan enabled.

**Comment by flyinghead** [comment]
DirectX 11 is probably the best choice for your GPU. DirectX 9 might be worth a try too.
This is a very slow GPU so don't expect miracles, but it should run at decent speed with default settings.

**Comment by Al666v** [comment]
> DirectX 11 is probably the best choice for your GPU. DirectX 9 might be worth a try too. This is a very slow GPU so don't expect miracles, but it should run at decent speed with default settings.

Also have tried both DX11 and 9 last minutes, still have issues.

**Comment by Al666v** [comment]
> DirectX 11 is probably the best choice for your GPU. DirectX 9 might be worth a try too. This is a very slow GPU so don't expect miracles, but it should run at decent speed with default settings.

It runs great again! Actually it was my laptop's fault, the fan has stopped spinning, i though at first it was the cooling paste though i just change the paste few weeks ago. I just clean it last minute and it runs at full speed again. So yeah it was my human error not checking a little deeper while cleaning.

**Comment by nexus382** [comment]
What was happening, Was Flycast was using  ALOT of power from your device, which is very low end, 2 cores, 4 threads, at 1.2 ghz, so the chipset was heating up being used to its limits, which your lack of fan, your CPU would thermal throttle almost instantly. Glad you got it working. That is why the clock speeds went down, your pc was trying to not burn its self alive lolol
