### ISSUE TITLE
Quake 3 arena mouse support

### ISSUE THREAD

**Issue by Mech56k** [flyinghead/flycast#157]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: win 10 desktop

Github hash: 

Hardware: 

**_Description of the Issue_**  Mouse doesnt lock in game nor is it responsive , any fixes coming? Thanks for the bba support

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
The latest build supports mouse capture.
Toggle with L-ALT + L-CTRL

**Comment by Mech56k** [comment]
Thanks

**Comment by Mech56k** [comment]
Mouse lock works great ! .Anyway to smoothin mouse control. Feels like the mouse has a dead spot when aiming. Sort of like a old school ball mouse with dirt in it Tried adjusting sensitivety.
Thanks again !

**Comment by flyinghead** [comment]
I had the same feeling as well when playing. It seemed like I had a hard spot at 180° horizontally.

**Comment by Mech56k** [comment]
Yeah, i noticed the flycast core for retroarch doesnt have that issue but retroarch doesnt have bba
