### ISSUE TITLE
Flycast on Wii U

### ISSUE THREAD

**Issue by seatrann** [flyinghead/flycast#1570]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Flycast to be ported to the Wii U

**Describe alternatives you've considered**
Nil

**Additional context**
I think that Flycast would be excellent on the Wii U. I humbly request the devs look into this one. Psvita is currently supported and i feel that the Wii U is a stronger console (performance wise).

**Comment by nexus382** [comment]
Steam deck, Switch, Ps Vita, Oculus Quest, Xbox 1.... they can all run Flycast, this might be a good addition, but the WII U was a VERY terriable seller... and most people do not use/own one.

**Comment by seatrann** [comment]
> Steam deck, Switch, Ps Vita, Oculus Quest, Xbox 1.... they can all run Flycast, this might be a good addition, but the WII U was a VERY terriable seller... and most people do not use/own one.

You are literally sleeping on the wii u like people did for the dreamcast. Its a great homebrew system which plays every single nintendo console except for switch and 3ds.

**Comment by flyinghead** [comment]
I don't plan on porting flycast to the wii U. Reasons include not owning one, it using a non supported cpu, in a non supported endianness mode, etc.
If someone is willing to do the port and maintain it, I'll be glad to include it.
