### ISSUE TITLE
Initial D Ver.3 Unable to connect PVP

### ISSUE THREAD

**Issue by nyanpasunyan** [flyinghead/flycast#1579]
Stuck on this interface
![Screenshot_20240713-160248](https://github.com/user-attachments/assets/7ddca088-8dba-4970-8c53-3479347cf081)

**Comment by flyinghead** [comment]
More information is needed:
- flycast version
- network settings for both instances
- LAN configuration
- etc.

**Comment by nyanpasunyan** [comment]
> More information is needed:
> 
> * flycast version
> * network settings for both instances
> * LAN configuration
> * etc.
Thank you for your reply.
flycast 2.3
network type naomi
Both connected devices are in the local area network, and one of them is enabled to act as server.
Agreed to the settings, I used the Google Play version and was able to connect normally.
![Screenshot_20240713-215858](https://github.com/user-attachments/assets/359ea851-01b6-43d3-a70b-2bdcda8a718b)

**Comment by flyinghead** [comment]
Can you clarify if you got this working or not?
