### ISSUE TITLE
Sonic Mania Non-rendered Text in Debug Menu

### ISSUE THREAD

**Issue by godreborn** [flyinghead/flycast#1581]
Platform = Windows
Game = the Sonic Mania Decompilation

I encountered a bug with the flycast emulator while running sonic mania.  it doesn't render the debug menu.  actually, the debug menu looks like this:

![image](https://github.com/user-attachments/assets/6581224e-fbcb-4d69-ac94-566a7425bcf7)

since the main menu doesn't work currently (requires too much vRAM), you have to load a stage through the debug menu.  it's incredibly difficult doing so blindly.

**Comment by gyrovorbis** [comment]
Some extra info from the developer: the text that isn't displaying is being drawn directly to VRAM from the SH4 without going through the PVR...

**Comment by flyinghead** [comment]
Enable `Full Framebuffer Emulation`

**Comment by godreborn** [comment]
Thanks.  That fixed it
