### ISSUE TITLE
Naomi2 Initial D 3rd stage some screen ratio is not 4:3 ratio

### ISSUE THREAD

**Issue by nevmind** [flyinghead/flycast#1585]
Platform / OS / Hardware: Android

Precondition : 
- Flycast 2.3 version apk is installed.

Issue : 
Following screen is not 4:3 screen ratio
![image](https://github.com/user-attachments/assets/3874ad0a-9d7f-4b3a-ab7b-8b7a5b8d2696)

Expected Result : 
Like following screen , this should be 4:3 ratio
![image](https://github.com/user-attachments/assets/b626b243-8f76-4d8e-ba8b-29be63b64c6a)

**Comment by flyinghead** [comment]
I cannot reproduce this issue.

What it your android device?
Which flycast video settings do you use?
Switching to vulkan or opengl makes a difference?

**Comment by nevmind** [comment]
Resolved. 
I've cleared all nvdata in data folder. and then it works good.

Previously I did uninstall & install various Flycast version . This could be cause of this bug I think.

Thanks.
