### ISSUE TITLE
Build Issue: MSYS2 CLANG64 Builds on Windows need -pthread as C++ option for clock.c

### ISSUE THREAD

**Issue by JWatersMeet** [flyinghead/flycast#1588]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11 Dev Virtual Machine

Github hash: Latest Master

Hardware: 16GB RAM

**_Description of the Issue_**

I currently compile Flycast for Win64 using the LLVM 18.1.3 toolchain in the MSYS2 CLANG64 environment. Since the introduction of clock.c on https://github.com/flyinghead/flycast/commit/24954ec59930845ac0217eb46c8ac2ce379730ed, I now need to pass `-pthread` to my C++ compiler flags, per the below:

`cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=artifact -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-pthread -march=znver3" -DCMAKE_C_FLAGS="-march=znver3" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DUSE_VULKAN=OFF -DUSE_DX9=OFF -DUSE_OPENGL=OFF`

If I don't, I get the following error:

![Nanosleep Error](https://github.com/user-attachments/assets/11d3487e-a79b-477f-b837-319424d5aa37)

Not a significant issue and easy to work around, but though you might like to know.

**_Debugging Steps Tested_**

Already have a workaround.

**Comment by flyinghead** [comment]
You probably don't need `clock.c` with clang. This file is a workaround for a regression in winpthreads. Not sure if clang uses it.

**Comment by flyinghead** [comment]
Fixed in latest master
