### ISSUE TITLE
[Soul Calibur] Combat opening animation is garbled if Full Framebuffer Emulation is active

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#1591]
Platform / OS / Hardware:  Libretro / GNU-Linux (Debian 12)  with latest stable MESA 24.1.4 

Github hash: Latest GIT code

Hardware:  Intel XE graphics (i5-1235U) 

**_Description of the Issue_**

Combat opening animation (growing window) is broken if Full Framebuffer Emulation is activated:

**_Debugging Steps Tested_**

  * Deactivating Full Framebuffer Emulation, which "works around" the issue.
  
**_Screenshots_**

https://github.com/user-attachments/assets/92af38f3-db10-4415-9f0e-167932174e45

**Comment by vanfanel** [comment]
Standalone is also affected.

**Comment by flyinghead** [comment]
Fixed in latest master
