### ISSUE TITLE
Added games to thegamesdb.net but still arent loading art in Flycast 

### ISSUE THREAD

**Issue by Airwalk16** [flyinghead/flycast#1599]
Hey flyinghead! Love the emulator. 
  I got the latest APK and installed it. Most games boxart loaded up just fine. But a select few did not. I added these games to thegamesdb.net website but still, they aren't pulling up. I noticed that in flycast>data>boxart folder, the games image is named with a number usually 6-8 digits long.

I'm not sure what or where this comes from, but I'm thinking this might be the UID that gamesdb asks for at the bottom of "genre"? Not sure.. 

Any advice on how I can get these games to load boxart?

Chaos filed v3
Animal Basket
Block Pong-Pong
Brick People
GIant Gram 2000
Illmatic Envelooe
Mamoru-Kun Wa Norowarete Shimatta!
Mushiking Of The Beetles 2005
Rhythm Tengoku(heaven)
Shooting Love 2007
& Touch De Uno 2

As I said, I added all these to thegamesdb, but im just not having any luck pulling the art in flycast and I don't know what NUMBER they need to be renamed to as to just have them in the Flycast>data>boxart folder.

Any help would be so appreciated!!!

**Comment by Airwalk16** [comment]
Also, is there REALLY no way to use a tablets touch screen as a lightgun as a lightgun like you can do so easily with RetroArch? 
  Maze of the Kings is a LOT more fun to play when you touch to kill the enemies rather than joystick. Same with HOTD2.

Could you explain to me how to do it?

**Comment by flyinghead** [comment]
I just tested and almost all the arcade games you added to TGDB show up properly. The only ones missing are:
Mushiking Of The Beetles 2005
Touch De Uno! 2

There's unfortunately no unique identifier for arcade games, so Flycast has to rely on searching by name. I fixed Touch de Uno! 2 by adding the missing exclamation point and it now works fine.
It's much harder to make the Mushiking series work since there are so many versions/editions.

You should delete your boxart folder so that all new games are re-downloaded next time you start Flycast.

**Comment by flyinghead** [comment]
You can use the touchscreen for lightgun games by assigning the Android Mouse to port A.
Set it back to None when playing other games or tapping anywhere on the screen will register as a press on button A.

**Comment by Airwalk16** [comment]
Thank you! I fixed the mushiking. I needed to add First at the end of it

**Comment by Airwalk16** [comment]
I really appreciate you getting back to me! Bow my Flycast looks nice and clean with no missing boxart.

**Comment by Airwalk16** [comment]
Also, I found a guide version that's ENGLISH TRANSLATED for animal basket and a few others. They work in retroarch adtwt extracting the 7z to a folder and booting with the .gdi so would flycast be able to run this dreamcast port? I un 7z then re zipped it but it said nvmem2001 or something like that wasn't present. I can see it in the original files of anmlbskt.zip but these are track01.bin track02.raw track03.bin and disc.gdi or something like that.

But just let me k ow if you can any Info on using translated 7z gdi roms.

**Comment by Airwalk16** [comment]
I actually figured it out. You just extract them to I dividual folders with the co tents within, then rename disc.gdi to the games name.gdi "animal basket.gdi" within the folder of the same name and it comes up with box art.
