### ISSUE TITLE
Bad Graphics with Sort by Pixel

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#16]
| Platform | Branch | Hash | CIDL |
| Windows 10-x64 | master | ed90bce | Downloaded from build site |

Description of the Issue

When using per pixel sorting rendering is so bad but its good with per strip and triangle.
my VGA is AMD RX 570 8GB

Screenshots

![Flycast git_mmu (built Sep 12 2019@21_53_59) 9_13_2019 10_12_33 AM](https://user-images.githubusercontent.com/32609205/64840304-1ca66b00-d610-11e9-8443-68ae5f172ea3.png)
![Flycast git_mmu (built Sep 12 2019@21_53_59) 9_13_2019 10_21_16 AM](https://user-images.githubusercontent.com/32609205/64840328-419ade00-d610-11e9-98d2-3f3669bc8394.png)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
Tested with a Radeon 550 on linux (Mesa 19.0.8) without problem. I'll test on Windows when I get a chance.

Make sure you use the latest drivers.

**Comment by mohsinous** [comment]
I tested flycast on linux too, it was OK but on Windows its glitchy

**Comment by mohsinous** [comment]
@flyinghead have you had this chance to test it on Windows 10?

**Comment by flyinghead** [comment]
Please test build 732e685 and let me know. Thanks

**Comment by mohsinous** [comment]
![Flycast git_mmu (built Sep 15 2019@16_35_58) 9_15_2019 9_18_29 PM](https://user-images.githubusercontent.com/32609205/64924869-6785d580-d7fe-11e9-8f5f-a3717bc7302d.png)
you are amazing man ...
thank you so much

**Comment by mohsinous** [comment]
btw reicast has dxd11 backend but it does not work, can you add dxd11 or vulkan backend to flycast??

**Comment by flyinghead** [comment]
Glad it worked!
Rezgarding other renderers, it's not an easy task but it may happen in the future.

**Comment by mohsinous** [comment]
thanks for your hard working
