### ISSUE TITLE
Tokyo Bus Guide: Game displays motor network error

### ISSUE THREAD

**Issue by JimCarlTay** [flyinghead/flycast#1601]
Platform / OS: NAOMI / Windows 10

Github hash: https://github.com/flyinghead/flycast/commit/6061d40

Hardware: 12th Gen Intel Core i5-12400 (CPU), Intel UHD Graphics 730 (GPU)

**_Description of the Issue_**

In the game, the notice "MOTOR NETWORK ERROR IN:f0 OUT:ff" is displayed, shortly after the attract mode starts. It still appears even during a gameplay session. It is expected that the error notice should not appear.

**_Debugging Steps Tested_**

  * Load the game, then wait until the game boots up to the attract mode.
  * The error notice appears, both during the attract mode and gameplay.

**_Logs Gathered_**

None needed.

**_Screenshots_**

![Flycast-2024-08-20 13-43-53](https://github.com/user-attachments/assets/547605a8-5a80-49fd-99f3-0e0276424603)

![Flycast-2024-08-20 13-45-49](https://github.com/user-attachments/assets/cd6bcad5-267a-416c-b9e1-b6bc1d173742)

**Comment by flyinghead** [comment]
Go to the game test menu: `Game assignments > Motor Power` and set it to `No Power`

**Comment by JimCarlTay** [comment]
> Go to the game test menu: `Game assignments > Motor Power` and set it to `No Power`

This fixes the bug. Usually, it's set to "Normal" by default.

**Comment by flyinghead** [comment]
This game apparently uses the same force-feedback drive board as F355 and 18 Wheeler so I'll add support for it.

**Comment by flyinghead** [comment]
Fixed on master
