### ISSUE TITLE
Time Stalkers - Final boss attack graphical glitches

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1604]
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 6061d40

https://github.com/user-attachments/assets/c1b92119-08e4-4d79-9799-d719d8e4e42a

[TimeStalkers v1.002 (2000)(Sega)(NTSC)(US)[!].state.zip](https://github.com/user-attachments/files/16678136/TimeStalkers.v1.002.2000.Sega.NTSC.US.state.zip)

This seems to happen when using per-pixel.

**Comment by flyinghead** [comment]
Did you try increasing Maximum Layers in Per Pixel Settings?

**Comment by kihato** [comment]
When I increased the maximum number of layers to 72, the black block in the center of the yellow color no longer appeared.
Thanks for your advice!

**Comment by flyinghead** [comment]
Fixed on master
