### ISSUE TITLE
Tomb Raider - The Last Revelation sound issues

### ISSUE THREAD

**Issue by ewertonpires2** [flyinghead/flycast#1605]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Windows / Windows 11/ AMD Ryzen 5600x / Nvidia Geforce GTX 1060 6 gb 
Flycast CI Build Version: v2.3.2-177-gb99b3450c

--

Github hash: ec3ad9b
Hardware: AMD Ryzen 5600x / Nvidia Geforce GTX 1060 6 gb 

**_Description of the Issue_**
There is a sound problem when Lara shoots with the pistols, where the sound of the pistol is choppy. The cover art isn't displaying.

When Lara shoots with the pistols the sound effect get choppy.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

https://youtu.be/-gsdWdu9gdg

**Comment by flyinghead** [comment]
I don't hear anything special with the sound of the pistols. It sounds the same on real hardware.
And the youtube video isn't available anymore.

**Comment by kihato** [comment]
Here is a video of the pistol firing sound glitch.
[Tomb Raider - The Last Revelation.zip](https://github.com/user-attachments/files/17594144/Tomb.Raider.-.The.Last.Revelation.zip)

https://github.com/user-attachments/assets/0748b9f0-5678-4180-a8bf-f97fca179643

There is also a similar issue with Tomb Raider Chronicles.

https://github.com/user-attachments/assets/b0ddc478-2aba-4b69-9ac1-026b976cbe18

**Comment by flyinghead** [comment]
Should be fixed on master
