### ISSUE TITLE
The display shifts due to video shift and does not fit within the 640x480 screen

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1606]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: b99b345

Examples of screen misalignment include "Rippin' Riders Snowboarding" and "Ohgami Ichirou Funtouki."

![Rippin](https://github.com/user-attachments/assets/db982e34-1843-4e87-8a70-de0adab911d6)
![Oogami](https://github.com/user-attachments/assets/62b54cc5-bcd2-4aaa-9049-dc77ff1b9e7e)

In most games, VO_STARTX.HStart=164 and VO_STARTY.VStart_field1=18, so both the x and y shift values ​​are 0, but the above games use values ​​that are different from the standard, so the screen will be displayed out of alignment.

**Comment by flyinghead** [comment]
Yes, some games use non-standard values for VO_STARTX and VO_STARTY in order to shift the screen. In some cases it results in an non centered screen. See #594.

Some games allow the screen to be manually centered in their settings. In order for this to be emulated, VO_STARTX and VO_STARTY must be taken into account when drawing the frame.

**Comment by flyinghead** [comment]
Note: in my tests the Rippin's Riders Snowboarding screen is centered horizontally (OpenGL and Vulkan on macOS). Not sure why I have a different result. I'll check on linux/windows when I get a chance.

**Comment by kihato** [comment]
Thanks for checking.

I was curious, so I checked it using the monitor's VGA mode and the actual hardware.
In Cool Boarders Burnnn, I was able to confirm that there was a gap at the top and right side of the screen.

Also, with the screen adjustment of Virtual-On, the white frame disappears if you move 12 pixels up or 25 pixels down on the actual hardware, but I found that you can make almost the same movements on the Flycast.

So since it's not a problem with flycast or anything, I would like to close this issue.

**Comment by kihato** [comment]
I'll post it here since it's somewhat related.
flycast-x86_64-pc-windows-msvc has problems with some games.

https://github.com/user-attachments/assets/fda6581e-dfaf-4963-a8aa-80773b5f9f6e

In Visual Studio, if an expression such as
`x = VO_STARTX.HStart - (vga ? 0xa8 : 0xa4)` or
`y = VO_STARTY.VStart_field1 - (vga ? 0x28 : 0x12)` becomes a negative value,
it will be treated as `4.29496730e+09`, and nothing will be displayed on the screen.
