### ISSUE TITLE
Compiling for raspberry failed

### ISSUE THREAD

**Issue by BiobaTiry** [flyinghead/flycast#1608]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Raspberry pi 4 - Retropie 

Hardware: Raspberry Pi 4

**_Description of the Issue_**

I've tried to compiling an update from source but i've got some error and compilling task was stopped. Anyone can get to me a newer version of flycast_libretro.so ??

**_Logs Gathered_**

[rps_2024-08-22_174220.log](https://github.com/user-attachments/files/16717089/rps_2024-08-22_174220.log)

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This is due to a GNU C++ compiler bug:
```
/home/pi/RetroPie-Setup/tmp/build/lr-flycast-flyinghead/core/hw/sh4/sh4_interrupts.cpp:264:1: internal compiler error: in gen_reg_rtx, at emit-rtl.c:1187
 }
 ^
```

**Comment by BiobaTiry** [comment]
Thanks!! but how i can fix this problem?
