### ISSUE TITLE
Alone In the Dark - The New Nightmare cutscene artifacts

### ISSUE THREAD

**Issue by mfigueirido** [flyinghead/flycast#1609]
**_Platform / OS / Hardware_**
Windows 11 x64

**_Github hash_**
b99b3450c8791bf46fa4866255c1347041fe372e (RetroArch core)

**_Hardware_**
AMD Ryzen 2600, Radeon RX 570, 16GB RAM

**_Description_**
Game: "Alone in the Dark - The New Nightmare (USA) (Disc 1)" GDI version.
Green artifacts show up in the background while the game displays a cutscene.

**_Debugging steps and info_**
- Used Vulkan as API.
- Tried with default settings, then tried per-pixel sorting and raised the number of layers to 128 but the issue persisted.
- Also tried enabling Full Framebuffer Emulation, same result.
- I've played Carnby's story last year and the cutscenes reproduced perfectly, so this looks like a regression. I can try to pinpoint the commit if it's needed.

Here is a save state, just load it and walk over the ledge to the left until the cutscene plays.
[Alone in the Dark - The New Nightmare (USA).zip](https://github.com/user-attachments/files/16726738/Alone.in.the.Dark.-.The.New.Nightmare.USA.zip)

**_Screenshots_**
![Alone in the Dark - The New Nightmare (USA)-240823-001510](https://github.com/user-attachments/assets/843547a5-78ea-4378-a3d0-abf1e7838b73)
![Alone in the Dark - The New Nightmare (USA)-240823-111911](https://github.com/user-attachments/assets/f22de323-8236-4687-b245-504586571d53)

**Comment by bslenul** [comment]
Can reproduce, although for me I get a black screen instead of the artifacts with my 3060 Ti:

![image](https://github.com/user-attachments/assets/dd2c4a58-846a-4a1c-97ca-2d6cee66d5c2)


Bisected to cc56b0fbaef0a818a2f9a361fc1f59e3c5d68abf

**Comment by mfigueirido** [comment]
Thanks for locating the commit!

**Comment by flyinghead** [comment]
Fixed on master

**Comment by mfigueirido** [comment]
Fix confirmed.
Thanks!
