### ISSUE TITLE
Flycast crash with error [libretro ERROR] core/windows/fault_handler.cpp:146 E[COMMON]: [GPF] PC 00007ff94b8bba91 unhandled access to 0000000000000000

### ISSUE THREAD

**Issue by jafar-it** [flyinghead/flycast#1611]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows / Windows 11/ AMD Ryzen 3600 / Nvidia Geforce RTX 3060TI 8 gb

Github hash: b99b345

Hardware: AMD Ryzen 3600 / Nvidia Geforce RTX 3060TI 8 gb

**_Description of the Issue_**

Launching through RetroArch. Flycast crash whenever I try to launch any game.  Games are in CHD format.  I topen into a white window and then crash without any warning. This is the last line of error in the log files just before crashing.
**[libretro ERROR] core/windows/fault_handler.cpp:146 E[COMMON]: [GPF] PC 00007ff94b8bba91 unhandled access to 0000000000000000**

**_Debugging Steps Tested_**

*Just launch any game from retroArch*

**_Logs Gathered_**

[INFO] RetroArch 1.19.1 (Git 427e3fa6f6)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.19.1
[INFO] Git: 427e3fa6f6
[INFO] Built: Jun  5 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: Xbox One Controller configured in port 1.
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Requesting 1 maximum frame latency, using 1.
[INFO] [D3D11]: Found GPU at index 0: "NVIDIA GeForce RTX 3060 Ti".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[INFO] [WASAPI]: Client initialized (shared, PCM, 48000Hz, 64.0ms).
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "d3d11".
[INFO] [MIDI]: Output device: "Microsoft GS Wavetable Synth".
[INFO] [Playlist]: Loading history file: "I:\RetroArch-Win64\content_history.lpl".
[INFO] [Playlist]: Loading history file: "I:\RetroArch-Win64\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "I:\RetroArch-Win64\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "I:\RetroArch-Win64\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "I:\RetroArch-Win64\content_favorites.lpl".
[INFO] [Core]: Using content: "I:\RG35XX-H\Roms\DREAMCAST\Marvel vs. Capcom 2 - New Age of Heroes (USA).chd".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] RetroArch 1.19.1 (Git 427e3fa6f6)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 3600 6-Core Processor              
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.19.1
[INFO] Git: 427e3fa6f6
[INFO] Built: Jun  5 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "I:\RetroArch-Win64\cores\flycast_libretro.dll"
[INFO] [Overrides]: Redirecting save file to "I:\RetroArch-Win64\saves\Flycast\Marvel vs. Capcom 2 - New Age of Heroes (USA).srm".
[INFO] [Overrides]: Redirecting save state to "I:\RetroArch-Win64\states\Flycast\Marvel vs. Capcom 2 - New Age of Heroes (USA).state".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] shell/libretro/libretro.cpp:323 N[BOOT]: retro_init
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[libretro INFO] core/hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/addrspace.cpp:463 N[VMEM]: BASE 00007ff4dd4a0000 RAM(16 MB) 00007ff4e94a0000 VRAM64(8 MB) 00007ff4e14a0000 ARAM(2 MB) 00007ff4fd4a0000
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] shell/libretro/libretro.cpp:2039 N[BOOT]: retro_load_game: I:\RG35XX-H\Roms\DREAMCAST\Marvel vs. Capcom 2 - New Age of Heroes (USA).chd
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "I:\RG35XX-H\system".
[INFO] [Environ]: SAVE_DIRECTORY: "I:\RetroArch-Win64\saves\Flycast".
[INFO] [Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
[libretro INFO] File extension is: .chd
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: d3d11.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_D3D11.
[INFO] [Environ]: SET_HW_RENDER, context type: d3d11.
[INFO] Requesting D3D11 context.
[libretro INFO] core/hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/addrspace.cpp:463 N[VMEM]: BASE 00007ff4dd4a0000 RAM(16 MB) 00007ff4e94a0000 VRAM64(8 MB) 00007ff4e14a0000 ARAM(2 MB) 00007ff4fd4a0000
[libretro INFO] core/emulator.cpp:56 N[BOOT]: Game ID is [T1212N]
[libretro INFO] core/emulator.cpp:56 N[BOOT]: Game ID is [T1212N]
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[libretro INFO] shell/libretro/libretro.cpp:2382 N[RENDERER]: retro_get_system_av_info: Res=480
[INFO] [Core]: Geometry: 640x480, Aspect: 1.333, FPS: 60.00, Sample rate: 44100.00 Hz.
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Set video size to: 1440x1080.
[INFO] [Video]: Using HW render, d3d11 driver forced.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: Xbox One Controller configured in port 1.
[libretro ERROR] core/windows/fault_handler.cpp:146 E[COMMON]: [GPF] PC 00007ff94b8bba91 unhandled access to 0000000000000000

```

**Comment by jafar-it** [comment]
[retroarch__2024_08_23__18_57_41.log](https://github.com/user-attachments/files/16729307/retroarch__2024_08_23__18_57_41.log)
Attaching detailed log

**Comment by flyinghead** [comment]
Try using different drivers for video (dx11, OpenGL, Vulkan), audio and input. That might give us an idea of what's going on.

**Comment by flyinghead** [comment]
Assuming it's fixed. Reopen if not.
