### ISSUE TITLE
[Libretro] Alone in the Dark - "Delay Frame Swapping" breaks cutscenes with the D3D11 renderer

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#1616]
Platform / OS / Hardware: PC / Windows 10 / i5-12400F / RTX 3060 Ti

Github hash: 308d9fc1acee55a58be5a21471680d4694ba983c

**_Description of the Issue_**

When using the Libretro core with "Delay Frame Swapping" enabled and with the D3D11 renderer, there are a lot of graphical glitches during cutscenes:

https://github.com/user-attachments/assets/82748c12-f72f-4f53-a41b-03e53aef1c05

At some point I switch to per-pixel to show a different graphical glitch (head and torso disappearing), then I disable "Delay Frame Swapping" and it looks normal.

I'm not able to reproduce in standalone so I'm guessing it's exclusive to the Libretro core.

**_Debugging Steps Tested_**

Tried an old 2022 version of the core but the issue is already present.

**Comment by Immersion95** [comment]
Same issue in Street Fighter Double Impact https://github.com/flyinghead/flycast/issues/1619

**Comment by flyinghead** [comment]
Should be fixed in the next core update

**Comment by bslenul** [comment]
Yep working fine now, thank you for the fix! 👍
