### ISSUE TITLE
[Win/Libretro/D3D11] Street Fighter III - Double Impact - Black square appearing with Delay Frame Swapping

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#1619]
A black square is appearing with default settings.

![Street Fighter III - W Impact (Japan)-240827-001503](https://github.com/user-attachments/assets/37dbc0d5-b6e3-4072-8b4d-48ffd3562a8b)
![Street Fighter III - W Impact (Japan)-240827-001445](https://github.com/user-attachments/assets/4c84565f-60b4-4496-87c9-8cae87dd93ec)

This is caused by the combinaison of Delay Frame Swapping + D3D11 which are the default settings in RetroArch at the moment.

Here is a log.
[retroarch.log](https://github.com/user-attachments/files/16754472/retroarch.log)

**Comment by flyinghead** [comment]
Should be fixed in the next core update
