### ISSUE TITLE
Legacy of Kain: Soul Reaver - Left/Right Stereo Channels Are Reversed

### ISSUE THREAD

**Issue by ACiDxCHRiST** [flyinghead/flycast#1621]
Platform / OS / Hardware: (Flatpak) Flycast v2.3.2 - SteamOS / Steam Deck

Github hash: f13d7ad

As the title says, the audio channels in Legacy of Kain: Soul Reaver are reversed.

Set the audio to Stereo in the game options and then find a directional sound source like an enemy or a floating soul. As you pan the camera around, you can hear the sound is always coming from the opposite speaker.

**Comment by ACiDxCHRiST** [comment]
Yeah I know, it's weird right? 240p Test Suite is correct. Soul Reaver is obviously reversed. I am out of town for a couple weeks, so I can't check Soul Reaver on my Dreamcast right now, but it is obviously backwards.

My mind would be blown if the game has this issue on real hardware as this is a classic game that tons of people have played and there is no way nobody has talked about this anywhere on the internet. It is super obvious with headphones but readily apparent on stereo speakers as well. I have checked and checked again and have pretty much ruled out a hardware or config issue in my situation.

**Comment by ACiDxCHRiST** [comment]
[Soul Reaver reversed stereo save state.tar.gz](https://github.com/user-attachments/files/16787019/Soul.Reaver.reversed.stereo.save.state.tar.gz)
I have attached a save state. You are on a ledge with some enemies in the room in front of you. You don't even have to move. Just pan the camera around and you can hear when the enemies are off screen to the right, their sounds are coming from the left and vice versa.

**Comment by flyinghead** [comment]
Yes, this is pretty obvious. No clue what could be the cause though.
It would still be nice to check this on real hardware to be sure.

**Comment by kihato** [comment]
Is this a mistake made during porting?
I was able to confirm that the left and right channels are inverted on the real hardware as well.

**Comment by flyinghead** [comment]
Thanks for the quick confirmation!

**Comment by ACiDxCHRiST** [comment]
> Is this a mistake made during porting?

That is amazing. It is really puzzling that I couldn't find any discussion of this issue. The DC port is the only one with Stereo sound. Well, I guess since this is confirmed on original hardware, you can go ahead and close this issue. I setup a an audio sink that mirrors the L/R channels and I just map Flycast to that while I am playing Soul Reaver.

```
pactl load-module module-remap-sink \                                                            
    sink_name=reverse-stereo \
    master=0 \
    channels=2 \
    master_channel_map=front-right,front-left \
    channel_map=front-left,front-right```

**Comment by Nejsplitter** [comment]
maybe this issue should be kept open until we figure out a solution within flycast for this particular game

**Comment by ACiDxCHRiST** [comment]
I don't think an emulator should be expected to fix or improve things that exist on the native hardware. If @flyinghead wanted to implement a feature to handle reversing the stereo channels inside of Flycast, then that would be his prerogative. It would need to be a configurable/optional feature, as even though we all know it is wrong, that's how the game exists on the native hardware and an emulators' highest priority should be to accurately reproduce original behavior, bugs and all.

**Comment by flyinghead** [comment]
I agree with @ACiDxCHRiST. Reversing the channels for this game in Flycast would undoubtedly make some people complain that Flycast doesn't sound like original hardware. And I don't want to add yet another audio option just for this particular case.

**Comment by Nejsplitter** [comment]
what i meant was, the devs obviously made a mistake during porting, maybe we could force this particular game to use the correct audio channels without the user ever knowing they are actually getting the correct behaviour, no exposed settings etc
