### ISSUE TITLE
Mushiking‘s ROM Bug

### ISSUE THREAD

**Issue by 456213** [flyinghead/flycast#1626]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
windows 10 R5 3600 32G 3060ti，flycast ver:v2.2-149-g36684bf82
Github hash: 36684bf82

Hardware: 

**_Description of the Issue_**
issue with the following ROMs: mushik2e, mushi2eo, and mushik4e. 
When playing the third round, the game gets stuck on the loading screen. 

**_Debugging Steps Tested_**

Choose any of the ROMs mentioned above (I have only tested these three so far, but there may be others), and play it three times to reproduce the issue.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![image](https://github.com/user-attachments/assets/c7e6b028-ca9e-4f15-afbd-0fea91a09ff4)

**Comment by flyinghead** [comment]
Tried with mushik4e and I could reach the 4th round.
![image](https://github.com/user-attachments/assets/26a88a12-b95d-4423-a3d0-dee83c8246d3)
Also I don't see a loading screen.

Can you upload a savestate when finishing the 3rd round so I can reproduce it?

**Comment by 456213** [comment]
ok
Here are the savestate and recordings.
[savestate1.zip](https://github.com/user-attachments/files/16836791/savestate1.zip)
[savestate2.zip](https://github.com/user-attachments/files/16836792/savestate2.zip)
[https://drive.google.com/file/d/1ONdF63Wz_j1yod9KYmuV4JMZTfI3E03b/view?usp=sharing](url)

**Comment by 456213** [comment]
The following ROMs have the issue which I jsut test:
mushi2eo, mushik2e, mushik4e, mushik2k, mushik4t, mushikc, mushike, mushikeo, mushikk. 
this includes all versions except the Japanese version

**Comment by flyinghead** [comment]
Should be fixed on master.
Make sure to delete all the savestates and `.card` files for these games from Flycast's `data` folder.
