### ISSUE TITLE
Issue with joystick calibration for Crazy Taxi (Naomi)

### ISSUE THREAD

**Issue by helloyanis** [flyinghead/flycast#1627]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 14

Github hash: Idk if that's it but the app version is v2.3.2-173-g8ea12443d

Hardware: Samsung Galaxy A52s 5G

**_Description of the Issue_**

When pulling the joystick all the way to the left, the car goes to the right. The joystick works fine when pulling all the way to the right, or to the left but not all the way

**_Debugging Steps Tested_**

  * Reinstall app
  * Restore settings to default
  * See in service menu, issue also happens
  * Check other game (Wild Riders), issue does not occur.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

https://github.com/user-attachments/assets/1c8195ae-e136-4208-8ec5-aa91f3220386

**Comment by flyinghead** [comment]
Fixed on master

**Comment by helloyanis** [comment]
I can confirm it works fine with the latest master binary. Thank you for the fix!
