### ISSUE TITLE
Building with pipewire fail.

### ISSUE THREAD

**Issue by ioamero** [flyinghead/flycast#1632]
Compiler: clang 19-git
Operating System: Arch Linux                      
Kernel: Linux 6.10.5-zen1-1-zen
Architecture: x86-64
Hardware Vendor: Gigabyte Technology Co., Ltd.
Hardware Model: X470 AORUS GAMING 7 WIFI
Firmware Version: F63c
Firmware Date: Wed 2022-07-20
Firmware Age: 2y 1month 2w 5d
Brand Raw: AMD Ryzen 7 2700X Eight-Core Processor
git hash: 5393235c4023e21bdfdb3c0dfe8ae6c553b86b1c

[ 27%] Building C object core/deps/SDL/CMakeFiles/SDL2-static.dir/src/audio/pipewire/SDL_pipewire.c.o
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.c:29:
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.h:28:
In file included from /usr/include/pipewire-0.3/pipewire/pipewire.h:14:
/usr/include/pipewire-0.3/pipewire/array.h:134:39: error: expected expression
  134 |         p = SPA_PTROFF(arr->data, arr->size, void);
      |                                              ^
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.c:29:
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.h:28:
In file included from /usr/include/pipewire-0.3/pipewire/pipewire.h:15:
In file included from /usr/include/pipewire-0.3/pipewire/client.h:15:
In file included from /usr/include/pipewire-0.3/pipewire/proxy.h:90:
In file included from /usr/include/pipewire-0.3/pipewire/protocol.h:26:
In file included from /usr/include/pipewire-0.3/pipewire/context.h:48:
/usr/include/pipewire-0.3/pipewire/core.h:361:9: error: expected expression
  361 |         return pw_core_error(core, id, seq, res, buffer);
      |                ^
/usr/include/pipewire-0.3/pipewire/core.h:350:31: note: expanded from macro 'pw_core_error'
  350 | #define pw_core_error(c,...)            pw_core_method(c,error,0,__VA_ARGS__)
      |                                         ^
/usr/include/pipewire-0.3/pipewire/core.h:341:4: note: expanded from macro 'pw_core_method'
  341 |                         struct pw_core_methods, _res,           \
      |                         ^
/usr/include/pipewire-0.3/pipewire/core.h:361:9: error: use of undeclared identifier 'error'
/usr/include/pipewire-0.3/pipewire/core.h:350:48: note: expanded from macro 'pw_core_error'
  350 | #define pw_core_error(c,...)            pw_core_method(c,error,0,__VA_ARGS__)
      |                                                          ^
/usr/include/pipewire-0.3/pipewire/core.h:382:4: error: expected expression
  382 |                         struct pw_core_methods, res,
      |                         ^
/usr/include/pipewire-0.3/pipewire/core.h:383:4: error: use of undeclared identifier 'get_registry'
  383 |                         get_registry, 0, version, user_data_size);
      |                         ^
/usr/include/pipewire-0.3/pipewire/core.h:397:4: error: expected expression
  397 |                         struct pw_core_methods, res,
      |                         ^
/usr/include/pipewire-0.3/pipewire/core.h:398:4: error: use of undeclared identifier 'create_object'
  398 |                         create_object, 0, factory_name,
      |                         ^
/usr/include/pipewire-0.3/pipewire/core.h:538:4: error: expected expression
  538 |                         struct pw_registry_methods, res,
      |                         ^
/usr/include/pipewire-0.3/pipewire/core.h:539:4: error: use of undeclared identifier 'bind'
  539 |                         bind, 0, id, type, version, user_data_size);
      |                         ^
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.c:29:
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.h:28:
In file included from /usr/include/pipewire-0.3/pipewire/pipewire.h:15:
In file included from /usr/include/pipewire-0.3/pipewire/client.h:15:
In file included from /usr/include/pipewire-0.3/pipewire/proxy.h:90:
In file included from /usr/include/pipewire-0.3/pipewire/protocol.h:28:
/usr/include/pipewire-0.3/pipewire/utils.h:84:1: error: unknown type name 'SPA_WARN_UNUSED_RESULT'
   84 | SPA_WARN_UNUSED_RESULT
      | ^
/usr/include/pipewire-0.3/pipewire/utils.h:85:8: error: expected ';' after top level declarator
   85 | ssize_t pw_getrandom(void *buf, size_t buflen, unsigned int flags);
      |        ^
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.c:29:
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.h:28:
In file included from /usr/include/pipewire-0.3/pipewire/pipewire.h:27:
/usr/include/pipewire-0.3/pipewire/map.h:165:10: error: expected expression
  165 |                 item = pw_map_get_item(map, id);
      |                        ^
/usr/include/pipewire-0.3/pipewire/map.h:77:77: note: expanded from macro 'pw_map_get_item'
   77 | #define pw_map_get_item(m,id)         pw_array_get_unchecked(&(m)->items,id,union pw_map_item)
      |                                                                             ^
/usr/include/pipewire-0.3/pipewire/map.h:180:6: error: expected expression
  180 |         if (pw_map_id_is_free(map, id))
      |             ^
/usr/include/pipewire-0.3/pipewire/map.h:79:60: note: expanded from macro 'pw_map_id_is_free'
   79 | #define pw_map_id_is_free(m,id)       (pw_map_item_is_free(pw_map_get_item(m,id)))
      |                                                            ^
/usr/include/pipewire-0.3/pipewire/map.h:77:77: note: expanded from macro 'pw_map_get_item'
   77 | #define pw_map_get_item(m,id)         pw_array_get_unchecked(&(m)->items,id,union pw_map_item)
      |                                                                             ^
/usr/include/pipewire-0.3/pipewire/map.h:183:2: error: expected expression
  183 |         pw_map_get_item(map, id)->next = map->free_list;
      |         ^
/usr/include/pipewire-0.3/pipewire/map.h:77:77: note: expanded from macro 'pw_map_get_item'
   77 | #define pw_map_get_item(m,id)         pw_array_get_unchecked(&(m)->items,id,union pw_map_item)
      |                                                                             ^
/usr/include/pipewire-0.3/pipewire/map.h:195:29: error: expected expression
  195 |                 union pw_map_item *item = pw_map_get_item(map, id);
      |                                           ^
/usr/include/pipewire-0.3/pipewire/map.h:77:77: note: expanded from macro 'pw_map_get_item'
   77 | #define pw_map_get_item(m,id)         pw_array_get_unchecked(&(m)->items,id,union pw_map_item)
      |                                                                             ^
/usr/include/pipewire-0.3/pipewire/map.h:216:2: error: expected expression
  216 |         pw_array_for_each(item, &map->items) {
      |         ^
/usr/include/pipewire-0.3/pipewire/array.h:57:7: note: expanded from macro 'pw_array_for_each'
   57 |              pw_array_check(array, pos);                                \
      |              ^
/usr/include/pipewire-0.3/pipewire/array.h:53:56: note: expanded from macro 'pw_array_check'
   53 | #define pw_array_check(a,p)     (SPA_PTROFF(p,sizeof(*(p)),void) <= pw_array_end(a))
      |                                                            ^
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.c:29:
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.h:28:
In file included from /usr/include/pipewire-0.3/pipewire/pipewire.h:27:
/usr/include/pipewire-0.3/pipewire/map.h:216:2: error: expected expression
/usr/include/pipewire-0.3/pipewire/array.h:57:7: note: expanded from macro 'pw_array_for_each'
   57 |              pw_array_check(array, pos);                                \
      |              ^
/usr/include/pipewire-0.3/pipewire/array.h:53:65: note: expanded from macro 'pw_array_check'
   53 | #define pw_array_check(a,p)     (SPA_PTROFF(p,sizeof(*(p)),void) <= pw_array_end(a))
      |                                                                     ^
/usr/include/pipewire-0.3/pipewire/array.h:52:59: note: expanded from macro 'pw_array_end'
   52 | #define pw_array_end(a)         SPA_PTROFF((a)->data, (a)->size, void)
      |                                                                  ^
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.c:29:
In file included from /home/ioamero/flycast/core/deps/SDL/src/audio/pipewire/SDL_pipewire.h:28:
In file included from /usr/include/pipewire-0.3/pipewire/pipewire.h:39:
In file included from /usr/include/pipewire-0.3/pipewire/data-loop.h:13:
/usr/include/spa-0.2/spa/support/thread.h:36:48: error: field has incomplete type 'struct spa_interface'
   36 | struct spa_thread_utils { struct spa_interface iface; };
      |                                                ^
/usr/include/spa-0.2/spa/support/thread.h:36:34: note: forward declaration of 'struct spa_interface'
   36 | struct spa_thread_utils { struct spa_interface iface; };
      |                                  ^
/usr/include/spa-0.2/spa/support/thread.h:66:4: error: expected expression
   66 |                         struct spa_thread_utils_methods, res, create, 0,
      |                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by flyinghead** [comment]
It looks like SDL has issues compiling with pipewire, not Flycast.
