### ISSUE TITLE
FIX: Ferrari F355 Challenge (stick shifter)

### ISSUE THREAD

**Issue by CO-Windler** [flyinghead/flycast#1635]
The simulator mode of the Deluxe cabinet employs a H-style stick shifter. It needs to be assigned to the digital joystick of Port B and expects a locking mechanism; in center position it shifts back to neutral. Please add this to the controller settings.

1 3 5
2 4 6

gear 1 = up + left
gear 2 = down + left
gear 3 = up
gear 4 = down
gear 5 = up + right
gear 6 = down + right
gear N = released (neutral)

**Comment by flyinghead** [comment]
This has been fixed on the master branch. See e270621a03853d63c4176c8269cd4e8eac1e2a5c.
