### ISSUE TITLE
Maybe a release for iOS (App Store)

### ISSUE THREAD

**Issue by Smoodie7** [flyinghead/flycast#1638]
**Is your feature request related to a problem? Please describe.**
Actually there is flycast on google playstore, and now emulators on iOS are authorized, so why not?

**Describe the solution you'd like**
A simple working and user-friendly release to the App Store.

**Comment by Smoodie7** [comment]
Nvm, i just got into the subject further and JIT recompilers are generally not allowed or limited on iOS by apple, but idk still worth a try maybe?

**Comment by flyinghead** [comment]
Flycast needs JIT, which isn't allowed on the AppStore. Duplicate of #1487
