### ISSUE TITLE
Red Dog Superior Firepower - Graphic glitches when using the Vulkan

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1642]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 38de286

[Red Dog Superior Firepower.zip](https://github.com/user-attachments/files/17029225/Red.Dog.Superior.Firepower.zip)

This issue only occurs when using Vulkan.
We have confirmed that it is reproducible in builds from early 2020.
Also, at first glance in OpenGL and DX, the area around the player appears completely white, which may seem like a bug, but this is normal as it is displayed the same way on real hardware.

https://github.com/user-attachments/assets/1968df54-aa50-4da5-8497-17d90bcbbba5

https://github.com/user-attachments/assets/9ac7cbd6-36ab-4005-bad7-47db01f9ec35

**Comment by flyinghead** [comment]
Fixed on master.
