### ISSUE TITLE
AICA/SH4/ARM emulation is too slow on Debug builds

### ISSUE THREAD

**Issue by buhman** [flyinghead/flycast#1646]
Platform / OS / Hardware: Linux / AMD Ryzen 5 4500U / Radeon RX Vega 6

Github hash: 92555c68c6b2934cc1ad7f8930a443c600782565

**_Description of the Issue_**

I primarily use `-DCMAKE_BUILD_TYPE=Debug` to be able to use the `gui_debug_tab` feature. I found that for certain types of loops, Flycast performance is unreasonably poor.

Specifically, on a SH4 loop such as:

```c
{
    while ((system_bus.ISTEXT & (1 << 1)) == 0) {
#if 0
      for (int i = 0; i < 1000; i++) {
	asm volatile ("nop;");
      }
#endif
    };
}
```

Enabling the `#if` appears to dramatically improve Flycast performance on Debug builds.

**_Debugging Steps Tested_**

Note that this is an audio-only test case. The display is not modified.

Release:

  * build Flycast with `cmake -DCMAKE_BUILD_TYPE=Release`
  * flycast [aica_gdrom.without_nop_loop.cdi](https://github.com/user-attachments/files/17094555/aica_gdrom.without_nop_loop.zip)
  * observe that the PCM playback is correct, with no dropped samples

Debug:

  * build Flycast with `cmake -DCMAKE_BUILD_TYPE=Debug`
  * flycast [aica_gdrom.without_nop_loop.cdi](https://github.com/user-attachments/files/17094555/aica_gdrom.without_nop_loop.zip)
  * observe that the PCM playback is noticeably incorrect, with regular periods of missing samples
  * flycast [aica_gdrom.with_nop_loop.cdi](https://github.com/user-attachments/files/17094584/aica_gdrom.with_nop_loop.zip)
  * observe that the PCM playback is mostly/entirely correct, with no dropped samples

The difference between `with_nop_loop` and `without_nop_loop` is changing `#if 1` to `#if 0`, respectively.

On real Dreamcast hardware, there is no audible difference between with_nop_loop and without_nop_loop.

**_Logs Gathered_**

**_Screenshots_**

None

**Comment by flyinghead** [comment]
I haven't tested it but I believe you're seeing the cost of emulating a read of the ISTEXT register vs. the cost of emulating 1000x NOP. Obviously the latter is much cheaper.
Debug builds are slow: no compiler optimization, functions not inlined, etc. Too slow to emulate a tight loop reading from ISTEXT, but fast enough if you do a read every 1000 cycles or so.

I would suggest you don't use Debug builds. I rarely use them when developing.

**Comment by buhman** [comment]
I tested a Release build with debug logging enabled, and it was also too slow. I suppose I'll need to recompile Flycast whenever I want the debugging features.
