### ISSUE TITLE
The King of Fighters Neowave (Atomiswave) - Most stages have flickering backgrounds

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1650]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 7907100

[kofnw_DX11.zip](https://github.com/user-attachments/files/17165074/kofnw_DX11.zip)

This happens when using DX11 per-pixel.
Enabling Native Depth Interpolation improves it considerably, but slight flickering remains.
Similarly, flickering also occurs in the sushi bar opening.
Native Depth Interpolation did not help here.

https://github.com/user-attachments/assets/9bbb4ae6-64ce-4c67-9bae-a80fee494d83

**Comment by flyinghead** [comment]
I don't see this issue on an Intel Iris+ 640, even without Native Depth Interpolation. So I assume it depends on the GPU and/or driver.
The missing geometry are transparent polygons drawn at the same depth as the background (sky + sea) with depth function greater or equal. Any loss of precision in depth calculation can result in the former being less than the latter, and the pixel is discarded. Per pixel rendering is more complex, including manually checking depth against a depth buffer, so it's more likely to happen there.

**Comment by kihato** [comment]
I see, that's what it was.
Thanks for the detailed explanation.
Closing this issue.
