### ISSUE TITLE
Beach Spikers (Naomi2) - Shadow glitch

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1651]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 7907100

The shadows flicker.
Changing the settings doesn't seem to have any effect.

https://github.com/user-attachments/assets/26a4e3a4-693c-49f8-a8fb-ff9ebe5d83a4

**Comment by flyinghead** [comment]
Should be fixed on master. There is a risk of regression in other Naomi 2 games using shadows.
