### ISSUE TITLE
Fighting Force 2 - Window background glitches in certain scenes

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1652]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 7907100

[Fighting Force 2 v1.000 (1999)(EIDOS)(NTSC)(US)[!].state.zip](https://github.com/user-attachments/files/17165243/Fighting.Force.2.v1.000.1999.EIDOS.NTSC.US.state.zip)

This happens when you launch flycast while your settings are set to Vulkan per-pixel, or when you switch to Vulkan per-pixel from another rendering.

https://github.com/user-attachments/assets/da6a3e7f-ad29-40dc-843d-b27aca06445f

**Comment by flyinghead** [comment]
Should be fixed on master
