### ISSUE TITLE
Android File Picker on Android TV Devices

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#1657]
Will standalone Android v2.3 and higher always use the Android file picker on "Content Location"? My Amazon Fire Cube, Fire OS 7, Android 9 doesn't work for this on v2.3 (v2.2 = worked). Their picker is made for touchscreen. Or could you add to use the old method if using Android 9 or earlier?

**Comment by flyinghead** [comment]
Unfortunately, Google forces us to use Android Scoped Storage to be listed in Google Play. However this is the same mechanism used by all Android apps to access external files and folders.
How come the Amazon Fire Cube file/folder picker is made for touchscreen since it's an Android TV device?

**Comment by MoeFoh** [comment]
> Unfortunately, Google forces us to use Android Scoped Storage to be listed in Google Play. However this is the same mechanism used by all Android apps to access external files and folders. How come the Amazon Fire Cube file/folder picker is made for touchscreen since it's an Android TV device?

It's from their tablet line. They don't seem interested in updating it. Fire OS is based on regular Android and not TV Android, I think.
A sample of the situation:
https://m.youtube.com/watch?v=T1hW2my9Y6k

**Comment by MoeFoh** [comment]
Tested on my ONN 4k Pro Streamer - Android TV 12
v2.2 & v2.3 - Error message: No file exist to do this
v2.1 and below - Works

**Comment by flyinghead** [comment]
Interestingly this doesn't seem limited to Amazon TV devices. I just tested on Nvidia Shield (Android 9) and the same problem happens: no way to navigate the UI with the shield remote or a gamepad.

This is just insane.

**Comment by flyinghead** [comment]
That doesn't stop here!
While Android TV 9 had a non-functional File Picker, Google simply decided to remove it from later Android TV versions. So Android TV 12 doesn't even have a native file picker (hence the message "No file exist to do this"), and the user must choose and install one.

I'm sure you'll appreciate Google's answer to this issue:
> GTV is for watching TV first and foremost, not managing files outside of adding or removing services or other apps designed to work with the interface. :)

source: https://support.google.com/googletv/thread/185340949/no-native-file-manager-app-for-google-tv-on-android-12?hl=en

**Comment by MoeFoh** [comment]
Yep. Sounds like we need a special version for Android that would not be part of the Play Store that would file/dir pick the old way.

On October 17, 2024, at 4:31 AM, flyinghead ***@***.***> wrote:

That doesn't stop here!
While Android TV 9 had a non-functional File Picker, Google simply decided to remove it from later Android TV versions. So Android TV 12 doesn't even have a native file picker (hence the message "No file exist to do this"), and the user must choose and install one.

I'm sure you'll appreciate Google's answer to this issue:

GTV is for watching TV first and foremost, not managing files outside of adding or removing services or other apps designed to work with the interface. :)

source: https://support.google.com/googletv/thread/185340949/no-native-file-manager-app-for-google-tv-on-android-12?hl=en

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419033921">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419033921</a>", "url": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419033921">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419033921</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by flyinghead** [comment]
I don't have the luxury to be able to maintain multiple versions for the android platform.

However I added a new option to use the legacy file browser instead of the (broken) system one. This option only works on Android 9 and earlier, since Android 10+ requires the use of a SAF file picker. This should hopefully fix the issue on Android TV 9 although I would appreciate some feedback. Also, some external storage locations won't be accessible using the legacy file browser. (This was the initial motivation to use SAF.)

I have no solution for Android TV 12 and the only one in this case is to install a 3rd party file manager that provides a SAF file picker. I saw references to  https://f-droid.org/en/packages/me.zhanghai.android.files/ which is an open source one but I'm sure there are dozens to choose from.

Let me know how this works for you.

**Comment by MoeFoh** [comment]
Will test out today. I'll install the recommended alternate file picker and
see if that works. I use Total Commander, but that was never identified as
a valid file picker with GTV12+.

**Comment by MoeFoh** [comment]
Amazon Fire TV Cube (2nd Gen) (FireOS 7 which is Android 9) - OK, for Games Dir selection with SAF turned off. NOT OK for Import, Export for Home folder - uses the built-in file picker still. Ooops!

ONN 4k Streamer Pro (GTV 12) - Again, get message "You don't have an app to do this" with Material Files app installed. I don't see a working solution here for the Standalone Flycast. Retroarch works.

Amazon Fire TV Cube (3rd Gen) uses FireOS 8 which is Android 11, so they will be out of luck.



On October 17, 2024, at 9:44 AM, flyinghead ***@***.***> wrote:

I don't have the luxury to be able to maintain multiple versions for the android platform.

However I added a new option to use the legacy file browser instead of the (broken) system one. This option only works on Android 9 and earlier, since Android 10+ requires the use of a SAF file picker. This should hopefully fix the issue on Android TV 9 although I would appreciate some feedback. Also, some external storage locations won't be accessible using the legacy file browser. (This was the initial motivation to use SAF.)

I have no solution for Android TV 12 and the only one in this case is to install a 3rd party file manager that provides a SAF file picker. I saw references to https://f-droid.org/en/packages/me.zhanghai.android.files/ which is an open source one but I'm sure there are dozens to choose from.

Let me know how this works for you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419750861">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419750861</a>", "url": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419750861">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2419750861</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by flyinghead** [comment]
FWIW I upgraded my Shield TV to Android 11. As expected disabling the SAF file picker doesn't work anymore (and access to legacy folders from an existing install also stops working). However the built-in SAF file picker is usable with a gamepad or the Shield remote so I was able to set my rom folders with it.

For Android 12, there has to be a way to install a 3rd party SAF file picker but I don't have any android TV 12 device to test and experiment with.

**Comment by flyinghead** [comment]
Also note that retroarch last update on google play was 3 years ago (!). The reason is they don't support Android Scoped Storage at all, and this is now a Google requirement for any new app or update.

**Comment by MoeFoh** [comment]
Yeah, I'd sure like to know if Google lets you use a third-party picker. I suspect not because of all the ongoing complaining.

On October 17, 2024, at 12:06 PM, flyinghead ***@***.***> wrote:

FWIW I upgraded my Shield TV to Android 11. As expected disabling the SAF file picker doesn't work anymore (and access to legacy folders from an existing install also stops working). However the built-in SAF file picker is usable with a gamepad or the Shield remote so I was able to set my rom folders with it.

For Android 12, there has to be a way to install a 3rd party SAF file picker but I don't have any android TV 12 device to test and experiment with.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2420064806">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2420064806</a>", "url": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2420064806">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2420064806</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by flyinghead** [comment]
I tested on Android TV 12 using an android virtual device and I couldn't get any file manager to function as a file picker. I keep getting the message "You don't have an app that can do this."
I assume that Google really doesn't want emulators to run on android TV 12+. So I'll declare it unsupported.

I was thinking about targeting android TV devices on Google Play but unless a solution to this problem exists, it's not worth the trouble.

**Comment by flyinghead** [comment]
Same situation on Android TV 14 as expected.
it seems the "Access All Files" special app permission is back. But it doesn't help.

**Comment by MoeFoh** [comment]
On my Cube (Android 9) with SAF on and Cheats,Add it gives me a choice of a file picker smh. Are you doing something different here?

Are you going to update import,export when saf is off?

**Comment by flyinghead** [comment]
> On my Cube (Android 9) with SAF on and Cheats,Load it gives me a choice of a file picker (smh). Are you doing something different here?

No, but opening a single file (cheat file) and opening a folder tree (content folder) is a bit different so that's what you may be seeing there.

> Are you going to update import,export when saf is off?

No, I'll just hide them when saf is off. They are only necessary on Android 12+ or 13+ where access to app private folders is restricted. And they weren't designed to use anything but SAF anyway.

**Comment by MoeFoh** [comment]
So with saf off, the flycast home dir is fixed at android/data/app and can't be changed?

On October 18, 2024, at 9:49 AM, flyinghead ***@***.***> wrote:

On my Cube (Android 9) with SAF on and Cheats,Load it gives me a choice of a file picker (smh). Are you doing something different here?

No, but opening a single file (cheat file) and opening a folder tree (content folder) is a bit different so that's what you may be seeing there.

Are you going to update import,export when saf is off?

No, I'll just hide them when saf is off. They are only necessary on Android 12+ or 13+ where access to app private folders is restricted. And they weren't designed to use anything but SAF anyway.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2422654236">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2422654236</a>", "url": "<a href="https://github.com/flyinghead/flycast/issues/1657#issuecomment-2422654236">https://github.com/flyinghead/flycast/issues/1657#issuecomment-2422654236</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by flyinghead** [comment]
correct

**Comment by Yoshi1981** [comment]
Mmh i Test with kihang g1 and shizuku mtmanager rs iadb and so on but 2.5 No Work on Android TV 

I Test more i have on my kihang g1 termux with Ubuntu and Neutrino Installed and Work i Test later with Ubuntu on kihang with Android TV and give Feedback

**Comment by Yoshi1981** [comment]
Alternativ retro arch Work on Android TV with flaycast 

![Image](https://github.com/user-attachments/assets/fc1b928f-d331-4d2d-acfa-23b81547b944)

https://howtoretro.com/emulation/how-to-set-up-retroarch-for-sega-dreamcast/

Mfg
