### ISSUE TITLE
Option to change gpu driver (Libretro)

### ISSUE THREAD

**Issue by ToniBC** [flyinghead/flycast#1659]
Hi, many people report errors and problems that are related to the video driver and incompatibilities. There are devices that fail with Vulkan, others work better with GL or DX, etc...

In the standalone version we can configure the driver, but in Retroarch/Libretro we don't have that option in the core options.

The core uses the driver you have configured, but it would be nice to be able to select the driver in the core options. This way, we can have a game that works better with one driver or another, without having to change that globally.

For example, Vulkan is the best driver for almost all of those that support it, but if it fails on our device, we have to change it for all of them and not just for Flycast. With the option, we can configure the driver for one game or for all of them, without modifying the global behavior.

I think implementing that is simple, just one variable, instead of using the general one, the one from the list of options is used, like Auto which uses the general one and then the others.

Thanks.

**Comment by flyinghead** [comment]
This is something that must be done in the front end (retroarch). A libretro core doesn't establish the graphics instance/context and doesn't get to choose which GPU to use, or which driver to load.
Also note that this feature is very limited (and somewhat hackish) as it only handles custom Vulkan drivers with Adreno GPUs on arm64 android platforms.

**Comment by ToniBC** [comment]
The PS2 core (LRPS2) has the option to change Render to DX11 or OpenGL and the PS1 core (Swanstation) has the same.

I don't know if this has any limitations, but when a core or emulator is loaded, it reads the video driver in the options to be able to put one or the other, in the standalone cfg and in Retroarch, I suppose, from a variable, from the established Global driver, but you can pass that option to the core options and thus avoid certain problems.

For example, in Android, the PSP core, if you have the driver in Vulkan, many people get an error, but if you have it in GL, it starts fine. If you put an option in the core options, it would start with the driver that gives the least problems, in Flycast the DX11 and then the user can change the one they want within the options.

In Retroarch you can force the use of other drivers by saving customizations, but that complicates things more.

But as I said, I know it is possible, but I don't know if it is more complex than it seems or if it has certain limitations.

**Comment by flyinghead** [comment]
Sorry I misunderstood your initial request.

I believe you can do this with RetroArch already by using a core override with the selected graphics driver. Source: https://www.reddit.com/r/RetroArch/comments/o7am6i/can_retroarch_automatically_change_graphics/

**Comment by ToniBC** [comment]
Yes, it is an option as I was telling you, but it is easier for the user if that option is in the core options, so it makes things easier for them.

But well, if it can be implemented, fine, if not, then we continue using the other method.

Thanks.
