### ISSUE TITLE
Cannot run the .exe on Win10 64-bit

### ISSUE THREAD

**Issue by DJRM2021** [flyinghead/flycast#166]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 ver. 10.0.19041.746

Github hash: 

Hardware: Intel i5, 

**_Description of the Issue_**
![image](https://user-images.githubusercontent.com/77593544/106536009-7de71b00-6532-11eb-9a29-af95f7c371d8.png)

Add a short, concise description of the issue here

**_Debugging Steps Tested_**
Download the latest Windows x64 build and run the .exe file.

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This build runs fine on my Windows 10 machine.

Is it a new problem? Can you try some previous builds?

**Comment by DJRM2021** [comment]
I downloaded the next latest build and it worked, probably a corrupted download.
