### ISSUE TITLE
[Feature Request] Support for HDR Output

### ISSUE THREAD

**Issue by SaltyBet** [flyinghead/flycast#1661]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Support for HDR Output.

Would benefit anyone gaming using:

- An HDR-capable display, like an HDR monitor or HDR TV.
- An HDR-capable mobile gaming device, like a Steam Deck OLED.

**Describe alternatives you've considered**

N/A

**Additional context**

Emulators with support for HDR Output:
- Dolphin.
- RetroArch.

**Comment by flyinghead** [comment]
Supporting HDR output requires a HDR source, and Dreamcast games aren't HDR.
If I'm not mistaken Dolphin implements HDR in two ways: the first uses HDR to reduce the color space to accurately match NTSC/PAL, which "results in slightly reduced brightness and saturation it could be considered undesirable, hence it being off by default." Not worth it IMHO.
The second one uses a shader and game lighting information, which isn't available in dreamcast and arcade games (except Naomi 2).
