### ISSUE TITLE
[Mali G68-MP4] Dynamite Cop polygons exploding/sorting issues w/ Native Depth Interpolation

### ISSUE THREAD

**Issue by SeongGino** [flyinghead/flycast#1663]
Platform / OS / Hardware: Android 11, Retroid Pocket 4 (Dimensity 900 w/ Mali G68-MP4)

Github hash: Release 2.3 [966ff37] (standalone) / 5d719e0 (libretro)

**_Description of the Issue_**

Dynamite Cop in particular seems to exhibit some severe sorting issues when NDI is enabled, which resembles polygon explosions, making things like the stage/section select completely illegible and some corrupted graphics on the character select and certain sections. There also seems to be instances of texture "shaking".

This is observed in both standalone (hence the report here) and libretro core, in both rendering backends (GL/Vulkan), **with Per-Triangle or Per-Strip sorting.** (Understanding that Per-Pixel isn't really a 'thing' on mobile)

**_Debugging Steps Tested_**

  * Play the game/watch the attract demos.

**_Logs Gathered_**

See screenshots (unless logs are needed in this case)

**_Screenshots_**

(Or in this case, video.)

[Full video on an offsite host,](https://drive.google.com/file/d/1ZkK0SbDy3frR0wZseDd4velk4oAax6aX/view?usp=sharing) recorded directly off the device, but I've trimmed down/compressed the essential example clip here:

https://github.com/user-attachments/assets/b84540c0-d4c3-4f21-9648-7bcd989afb3c

**Comment by flyinghead** [comment]
Why are you enabling `Native Depth Interpolation`?
It's off by default because it is mostly for AMD GPUs, and sometimes Intel. I don't know of any mobile GPU that needs it.

**Comment by pantomm** [comment]
You can use Per-Pixel with vulkan

**Comment by SeongGino** [comment]
> Why are you enabling `Native Depth Interpolation`? It's off by default because it is mostly for AMD GPUs, and sometimes Intel. I don't know of any mobile GPU that needs it.

With this hardware, it is needed at least for this game (without it, water and some other texture has visual corruption issues) and *Zombie Revenge* (without it, some areas exhibit other severe sorting issues, like the small warehouse after opening the shutter in the first level).

If that constitutes a separate issue then fair, but it would be lengthier/have to be spread across multiple issues.

> You can use Per-Pixel with vulkan

It does technically *work* but does not resolve the issue - it in fact creates slightly more graphical corruption issues that are less consistent than using Per-Strip/Triangle on this hardware.

**Comment by flyinghead** [comment]
Dynamite Cop is known to use very high depth values, which cause precision loss on some hardware. Unfortunately there's nothing I can do to fix it as this is a GPU issue.

**Comment by SeongGino** [comment]
For what it's worth, Redream on the same hardware doesn't seem to exhibit any of the same problems as Flycast for this game. Without an open source to reference for that, it probably doesn't do much help (as I prefer using Flycast whenever possible), but just speaking as an alternative from a user's point of view.

**Comment by pantomm** [comment]
Doesn't happen on adreno 725 with Native Depth Interpolation enabled 
![Screenshot_2024-10-08-12-17-32-486_com flycast emulator](https://github.com/user-attachments/assets/9e74dcc8-cc6a-4eed-8a27-0ce5853f3fa5)
