### ISSUE TITLE
[Android] Virtua Tennis crashes with Vulkan driver

### ISSUE THREAD

**Issue by DJM75** [flyinghead/flycast#1664]
The games crashes after the menu, it doesn't happen with the GL driver.

**Comment by flyinghead** [comment]
Dreamcast or Naomi version?

**Comment by DJM75** [comment]
> Dreamcast or Naomi version?

Dreamcast, Naomi works.

**Comment by flyinghead** [comment]
Thanks for testing.
It's not crashing for me but I do see a Vulkan validation error on the player selection screen.
A fix is coming.

**Comment by flyinghead** [comment]
Fixed on master

**Comment by DJM75** [comment]
> Fixed on master

Just tested it and works fine! Thank you ;)
