### ISSUE TITLE
Soulcalibur graphical glitches

### ISSUE THREAD

**Issue by mfigueirido** [flyinghead/flycast#1668]
Platform / OS / Hardware: 
Windows 11 x64

Github hash: 
56fe3b9c9d0ce44fb54fdf28cbcd1a984346fa30

Hardware: 
AMD Ryzen 2600, Radeon RX 570, 16GB RAM

**_Description of the Issue_**

Two issues were perceived while playing the game Soulcalibur (USA region, GDI):

1- **Battle loading screen flickers while transitioning to gameplay**.
Save state: [Soulcalibur save state issue 1.zip](https://github.com/user-attachments/files/17284298/Soulcalibur.save.state.issue.1.zip)

Happens in both standalone and Libretro.
Only happens with Vulkan and per-pixel sorting.

2- **The flag and the sail flicker in the harbour scenario**.
Save state: [Soulcalibur save state issue 2.zip](https://github.com/user-attachments/files/17284374/Soulcalibur.save.state.issue.2.zip)

Happens in both standalone and Libretro.
Happens with Vulkan and DirectX 11.
Delay Frame Swapping disabled does not fix it.

**_Screenshots_**
![imaxe](https://github.com/user-attachments/assets/3f528522-409f-4145-9613-deb3369343bf)
![imaxe](https://github.com/user-attachments/assets/d0cc7b67-d810-43ec-85b3-c37fda89abac)
![imaxe](https://github.com/user-attachments/assets/054ae3b2-b0ef-417b-acb9-91beb4a7af97)

**Comment by flyinghead** [comment]
Issue 1 is confirmed and specific to Vulkan per pixel.

However issue 2 seems to also happen on original hardware: https://youtu.be/taqjLybaffM?si=wZp0vy0zpO3e1TYy&t=1020

**Comment by mfigueirido** [comment]
Played this game on my old Dreamcast long ago but didn't remember this. I should have checked it. Thanks @flyinghead.

**Comment by flyinghead** [comment]
Should be fixed on master

**Comment by mfigueirido** [comment]
The glitch is gone. Closing this.
