### ISSUE TITLE
NAOMI1 BIOS required for NAOMI2 system

### ISSUE THREAD

**Issue by pizzzza19** [flyinghead/flycast#1676]
**Is your feature request related to a problem? Please describe.**
An original SEGA NAOMI2 system can operate both NAOMI1 and NAOMI2 however Flycast requires both BIOS.

**Describe the solution you'd like**
NAOMI2 BIOS will allow booting up NAOMI1 games (cart and GDROM).

**Comment by flyinghead** [comment]
Even if it works, what's the point of using Naomi 2 BIOS for Naomi 1 games?
Naomi 1 cabinets use a Naomi 1 BIOS, and this is what Flycast requires.

**Comment by pizzzza19** [comment]
Sometimes not all the people have NAOMI1 cab but only NAOMI2. It’s me. So i thought it would be  convenient if it works with NAOMI 2 BIOS “naomi2.zip” only.

**Comment by flyinghead** [comment]
The easiest way is to do what you just did: copy naomi2.zip to naomi.zip and rename the bios files inside it. This should work.
Flycast already falls back to older versions of the BIOS file, both for naomi 1 and 2. However it doesn't look for a different zip file, which would be complex to implement.

**Comment by pizzzza19** [comment]
Thanks. I see older version of NAOMI1 BIOS (rev. A B C D E) fall back already. It seems my request is already done while renamed NAOMI2 BIOS file works with NAOMI1 games.
