### ISSUE TITLE
2 games run too fast

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#1682]
Platform / OS / Hardware: Windows 10

Flycast version: 2.3.2-220-g5b343562b

Hardware: geforce gtx 1070

**_Description of the Issue_**

The games jambo! safari and zombie revenge run way too fast. They run so fast you can't play them, especially jambo! safari 

**_Debugging Steps Tested_**

I'm not a programmer

**_Logs Gathered_**

no logs

**_Screenshots_**

not applicable

**Comment by flyinghead** [comment]
Both games run at normal speed here.
Try enabling VSync and check your audio driver/settings.
