### ISSUE TITLE
Build crash => libretro_core_options_intl.h:28506:53: warning: unknown escape sequence: '\302'

### ISSUE THREAD

**Issue by Kelvfimer** [flyinghead/flycast#1688]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Linux Libretro odroid n2 plus

Flycast version: 
[d3916f13d72cd9908e72dfd7936ca159c52bc61e](https://github.com/flyinghead/flycast/commit/d3916f13d72cd9908e72dfd7936ca159c52bc61e)

Latest working version https://github.com/flyinghead/flycast/commit/b2c6159b10ef9e662c55edf850b7b61c9d85fd31

Hardware: 

**_Description of the Issue_**

Building latest commit libretro.cpp fialed it seems there is something with libretro_core_options I'm using latest retroarch 228426880babb529fae8f01598a6d34698ad3b18

**_Debugging Steps Tested_**

  

**_Logs Gathered_**

[Flycastlog.txt](https://github.com/user-attachments/files/17348862/Flycastlog.txt)

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
These warnings are caused by the automatic translation system used by libretro. However they shouldn't make the build fail since they're just warnings. The file `libretro_core_options_intl.h` hasn't been updated recently so it's not a recent issue.

**Comment by Kelvfimer** [comment]
The thing is that my build crashes due to the lastest commit. So what could be the issue?

**Comment by flyinghead** [comment]
I was wrong: this file has been automatically updated yesterday, hence the new error:
```
libretro_core_options_intl.h:58701:53: error: incomplete universal character name \U
```
And I get the same error when building.

**Comment by Kelvfimer** [comment]
Thx for fixing it!!

**Comment by jonian** [comment]
I think this error is still occurring. Full build log can be found [here](https://github.com/jonian/game.retroarch/actions/runs/11532080340/job/32104060818).

```
2024-10-26T14:19:50.6826948Z #18 1268.3 /root/LibRetro/flycast/shell/libretro/libretro_core_options_intl.h:58701:53: error: incomplete universal character name \U
2024-10-26T14:19:50.6831897Z #18 1268.3 58701 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL "Gdy wyłączone, wszystkie gry udostępniają do 8 plików zapisów VMU (A1/A2/B1/B2/C1/C2/D1/D2) znajdujących się w folderze systemowym RetroArch.\n\Ustawienie 'VMU A1' tworzy unikalny plik VMU 'A1' w folderze zapisów RetroArcha dla każdej uruchomionej gry.\n\Ustawienie 'Wszystkie VMU' tworzy do 8 unikalnych plików VMU (A1/A2/B1/B2/C1/C2/D1/D2/D2) dla każdej uruchomionej gry."
2024-10-26T14:19:50.6836235Z #18 1268.3       |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jonian** [comment]
This is the automated commit that might caused the issue https://github.com/flyinghead/flycast/commit/760813e45a8ca885ec4442c98894dfc5239427c9

**Comment by flyinghead** [comment]
@DisasterMo Can I ask you for help here?
I tried to fix the issue by changing the english text, which helped, but some translations still result in syntax errors.
Thanks!

**Comment by flyinghead** [comment]
fixed temporarily but it will likely break again on friday

**Comment by DisasterMo** [comment]
Hi, I removed the stray backslashes from the translation text. That should fix this issue. I cannot guarantee, however, that there are, or will be, no more.

**Comment by flyinghead** [comment]
Thanks @DisasterMo!
Some texts were previously using adjacent string literals (like `"blah\n" "blah"`) and it looks like this was confusing the scripts and/or crowdin.
I fixed all of them but it looks like crowdin was still using the previous version in some cases/translations. Not 100% sure though (is that even possible?).

**Comment by DisasterMo** [comment]
Unfortunately, yes. Crowdin has a "Translation Memory". So, if a source text is changed, but still remains similar enough, the old translation is filled in automatically, instead of deleting it. Helpful for translators, troublesome for issues like this.
