### ISSUE TITLE
Online multiplayer not working, even with custom DNS

### ISSUE THREAD

**Issue by gizmo4487** [flyinghead/flycast#169]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 64-bit, Dell Inspiron 7548

Github hash: 30b54694aaacbe9ee50747a6f8137fcc23161013

Hardware: Intel Core i7-5500U 2.4 GHz, 8 GB RAM, Intel Dual Band Wireless-AC 3160

**_Description of the Issue_**

When attempting to play various online games (such as The Next Tetris - Online Edition and Phantasy Star Online v2) using the Dreamcast Live servers, Flycast is unable to connect to the server. In the case of The Next Tetris - Online Edition, the emulator freezes several times before the game indicates an unsuccessful connection attempt. In the case of Phantasy Star Online v2, shortly after the "Welcome to the world of PSO" text disappears, the emulator freezes for approximately 60 seconds before saying "the line was disconnected due to network errors". Quake III Arena and web browsers work fine.

**_Debugging Steps Tested_**

  * Ensured usage of GDI instead of CDI
  * Tried an older Flycast build
  * Tried the LibRetro core instead of the standalone version
  * Ensured that all necessary ports were open
  * Answered "allow" to all Windows firewall prompts
  * Tried using the broadband adapter for PSO v2

**_Logs Gathered_**

The Next Tetris - Online Edition:
```

00:00:000 rend/gles/imgui_impl_opengl3.cpp:309 W[RENDERER]: 
00:00:001 rend/gles/imgui_impl_opengl3.cpp:309 W[RENDERER]: 
00:00:003 rend/gles/imgui_impl_opengl3.cpp:327 W[RENDERER]: 
00:04:891 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:04:918 hw/mem/_vmem.cpp:496 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:04:950 imgread/common.cpp:125 W[GDROM]: Warning: CDI Image Loaded! Many CDI images are known to be defective, GDI, CUE or CHD format is preferred. Please only file bug reports when using images known to be good (GDI, CUE or CHD).
00:04:950 ./nullDC.cpp:106 N[BOOT]: Game ID is [T40214N]
00:19:918 hw/sh4/modules/mmu.cpp:653 N[SH4]: Enabling Full MMU support
01:32:825 network/picoppp.cpp:849 N[MODEM]: Found network ports for game T40214N
01:40:847 network/picoppp.cpp:867 W[MODEM]: UPNP Init failed

```

PSO v2:
```

00:00:000 rend/gles/imgui_impl_opengl3.cpp:309 W[RENDERER]: 
00:00:000 rend/gles/imgui_impl_opengl3.cpp:309 W[RENDERER]: 
00:00:002 rend/gles/imgui_impl_opengl3.cpp:327 W[RENDERER]: 
00:26:916 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:26:939 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:26:962 ./nullDC.cpp:104 N[BOOT]: Game ID is [MK-51193  ]

```

**_Screenshots_**
PSO v2 freezes here...
![pso2_stuck](https://user-images.githubusercontent.com/38299798/106706829-41610100-65be-11eb-9f91-e508d2fc44e7.png)

One minute later, this error appears:
![error](https://user-images.githubusercontent.com/38299798/106705981-eb3f8e00-65bc-11eb-9765-3f9deafa2c3e.png)

Tetris fails to connect after about 15 seconds:
![tetonline_error](https://user-images.githubusercontent.com/38299798/106707172-cfd58280-65be-11eb-86fc-f77ad6cec5b6.png)

Browsers function as normal:
![dc_browser](https://user-images.githubusercontent.com/38299798/106708035-39a25c00-65c0-11eb-8b2c-ddf20ad11f1d.png)

**Comment by flyinghead** [comment]
The Next Tetris connection problem is a known issue. Unfortunately there's no workaround at the moment.

Phantasy Star Online v2 US and Japan editions cannot use online features because they need an additional server that hasn't been revived. In Japan and US a paid "Hunter's License" subscription was needed. There are ways to patch the PSOv2 US/J media so it can be used. Otherwise use PSOv1, or PSOv2 EU.
