### ISSUE TITLE
Capcom vs SNK, bug

### ISSUE THREAD

**Issue by melek8014** [flyinghead/flycast#1697]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: MS Windows 7 64-bit SP1, AMD Athlon X4 880K Quad Core Processor, 12GB RAM, GeForce 8800 GT

Flycast version: latest master version

Hardware: 

**_Description of the Issue_**
In the game Capcom vs Snk, the 'KO' inscription is incorrectly displayed, I circled it in blue
Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.



```

**_Screenshots_**
![Bez tytułu](https://github.com/user-attachments/assets/af55655a-1db5-4933-8530-c2fc2ce11eb4)

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This is due to per triangle/per strip sorting. Enabling per pixel fixes it.

**Comment by melek8014** [comment]
> This is due to per triangle/per strip sorting. Enabling per pixel fixes it.

I understand, but I just checked on the Redream emulator, it is not available on HLE per-strip

**Comment by flyinghead** [comment]
I suggest you use redream then.

**Comment by melek8014** [comment]
> I suggest you use redream then.

flycast is better overall, but it has worse graphics in per strip mode, I thought it could be improved

**Comment by flyinghead** [comment]
Propose an algorithm. I'll implement it.

**Comment by melek8014** [comment]
> Propose an algorithm. I'll implement it.
I don't know anything about this, you are a specialist here, can't you get the solution from Redream?
