### ISSUE TITLE
(F355 and Clones) Countdown is missing during race start

### ISSUE THREAD

**Issue by CarterJBurke** [flyinghead/flycast#1698]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11 23H2/ Intel i9 14900HX/ Nvidia Geforce RTX 4060

Flycast version: fd475bd

**_Description of the Issue_**

When a race or practice mode begins, the countdown numbers do not display on screen.

**_Debugging Steps Tested_**

clearing cache, switching to per pixel, and switching to other renderers like DX11 and OpenGL

**Comment by flyinghead** [comment]
Fixed on master
