### ISSUE TITLE
Xbox / DirectX Support

### ISSUE THREAD

**Issue by TreeBranches** [flyinghead/flycast#170]
As RetroArch is now playable on Xbox One/Series consoles without needing any modification, I was hoping that DirectX support could be implemented for better performance.

Whilst ANGLE is supported in FlyCast, it is slow, and the result being nothing, not even 2D games, ever reaching 60fps. Even the BIOS hovers around the 40-50fps mark.

**Comment by flyinghead** [comment]
A DirectX 9 renderer is available in branch `fh/directx`. It is now feature-complete so you're welcome to give it a try.
