### ISSUE TITLE
Cannot access my bios folder 

### ISSUE THREAD

**Issue by chrisleigh-stack** [flyinghead/flycast#1700]
The new update was crazy can access the bios due to changes of the new update please bring back the easy one. Can't play any Naomi, atomiswave games. Because of that folder access

**Comment by flyinghead** [comment]
Please describe your issue, flycast version(s), platform, OS, etc.

**Comment by ForeskinJohn** [comment]
why did we remove the bug label from this? my bios is not being detected either. its all in the data folder.

**Comment by flyinghead** [comment]
Please describe your issue, flycast version(s), platform, OS, etc.

**Comment by flyinghead** [comment]
You can put the bios files in the roms folder.

**Comment by ForeskinJohn** [comment]
so i was missing a piece of my bios, as to not breach any legal grounds on this project ill elaborate no further than that i have things working! just specify for flycast in a google search if you dont know which files go where, my bad!
