### ISSUE TITLE
Silent Scope: Error with displaying the VMU image

### ISSUE THREAD

**Issue by melek8014** [flyinghead/flycast#1703]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: MS Windows 7 64-bit SP1, AMD Athlon X4 880K Quad Core Processor, 12GB RAM, GeForce 8800 GT

Flycast version: latest master version

Hardware: 

**_Description of the Issue_**
In the game Silent Scope, the image in the VMU card is displayed incorrectly during the game, I circled it in blue...
Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Bez tytułu](https://github.com/user-attachments/assets/88d89b6b-07b3-48ec-824e-639e6a56b684)

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
You can fix the VMU display issue by enabling `Video > Advanced > Copy Rendered Textures to VRAM`.
I will enable this option automatically for this game.

**Comment by melek8014** [comment]
> Copy Rendered Textures to VRAM

Thanks :)

**Comment by flyinghead** [comment]
Fixed on master

**Comment by melek8014** [comment]
> Fixed on master

Thanks again
