### ISSUE TITLE
initial d arcade ver 3 cycraft: smcp initialized dimm flag error occured

### ISSUE THREAD

**Issue by danwraith03** [flyinghead/flycast#1706]
![Screenshot_20241020_103412_com flycast emulator](https://github.com/user-attachments/assets/715bc946-37f3-41d8-bfaf-2092768047a3)

I want to play the initial d arcade ver 3 cycraft edition but always appears smcp initialized dimm flag error occured.
Please how to run this game? By the way i am running in andriod version.

**Comment by flyinghead** [comment]
The cycraft editions are not supported (initial d, club kart). But you can play the regular ones.
