### ISSUE TITLE
How i can use the right analog for racing games?

### ISSUE THREAD

**Issue by reignerdeustcher** [flyinghead/flycast#1709]
Is there some way to map the up and down analog movement to the right thumbstick of my xbox one controller? i want to play racing games like in ps2, left analog for steering and right analog for accelerate and brake

**Comment by flyinghead** [comment]
Yes: map the left trigger to right stick Down, and the right trigger to right stick Up:
![image](https://github.com/user-attachments/assets/5f4e1459-feaf-4f0c-b0f1-956d8b35bd98)
