### ISSUE TITLE
Jambo safari force feedback

### ISSUE THREAD

**Issue by cybercuate** [flyinghead/flycast#1711]
**Is your feature request related to a problem? Please describe.**
Jambo safari has no feedback and if it is possible please add it

**Describe the solution you'd like**
Force feedback

**Describe alternatives you've considered**
"centering spring in non force feedback games" option in logitech's drivers menu

**Additional context**
Please

**Comment by flyinghead** [comment]
Jambo Safari doesn't support Force Feedback
