### ISSUE TITLE
with G29 connected, GUI keeps scrolling down or up

### ISSUE THREAD

**Issue by cybercuate** [flyinghead/flycast#1712]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
PC Windows 11 23H2 AMD Ryzen 5 3600 + Nvidia 4060Ti

Flycast version: 
2.4
Hardware: 
Logitech G29
**_Description of the Issue_**

when the G29 is connected to the PC, flycast's menu keeps scrolling down or up

**_Debugging Steps Tested_**

  * disconnecting and connecting the wheel from the PC
  * If I press the pedals to keep them in the center this fixes it
  * Maybe is because it detects the pedals' values (+ or - , center is 0)

**Comment by flyinghead** [comment]
Scrolling up and down is controlled by the (left) Thumbstick Up/Down position on a normal gamepad.

When using a wheel, it's normally bound to the (left) Thumbstick X position, while the Y axis is unbound. Pedals are normally mapped to left and right triggers.

It's possible that the default SDL mapping for the G29 isn't correct. Does the problem also occur with a correct binding? Do you have anything bound to Thumbstick Up or Down?

**Comment by cybercuate** [comment]
> It's possible that the default SDL mapping for the G29 isn't correct. Does the problem also occur with a correct binding? Do you have anything bound to Thumbstick Up or Down?

nope. This problem is present in old games too like the need for speeds.

Asseto corsa competizione, mudrunner, city car driving, nfs heat, etc. work perfect, also emulators like sega model 3 UI, teknoparrot,Mame have no problem with the wheel connected.

**Comment by flyinghead** [comment]
Can you post a screenshot of your bindings for the G29? Particularly the Thumbstick.

The fact that other games or emulator work fine isn't going to help figure out the issue with Flycast.

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen if not.
