### ISSUE TITLE
[Android] Exit controller hotkey freezes the emulator

### ISSUE THREAD

**Issue by Ari3l97** [flyinghead/flycast#1713]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Android 13 / Ayn Odin 2 Handheld console 

Flycast version: 

2.4, but it has been a thing for a long time, no idea which was the build that introduced the bug.

**_Description of the Issue_**

Attempting to use whichever hotkey has been mapped to exit the emu makes it freeze, requiring force closing it manually. 

**_Debugging Steps Tested_**

  * Tried mapping it to different buttons.
  * Tried an external controller (DS4) instead of the built in one, same outcome.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

Video shared in the Discord: the https://discord.com/channels/627187835945877505/1252287562643537961/1298999489041793026

**Comment by flyinghead** [comment]
Fixed on master
