### ISSUE TITLE
VF4 Evo - Frame drops - World rom.

### ISSUE THREAD

**Issue by TTurbo23** [flyinghead/flycast#1717]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11, RTX 2070 Super, Processor	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 8 Logical Processor(s)

Flycast version: 2.4

Hardware: 

**_VF4 Evo frame drops_**

Add a short, concise description of the issue here
During the intro video there are noticeable frame drops with audio breaks. It happens at multiple times

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Tested multiple api options and used lowest graphical settings for best performance.
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Fixed on the `dev` branch
