### ISSUE TITLE
Quarter Screen with 2.0 (2xSSAA) or above on Android with Vulkan Renderer

### ISSUE THREAD

**Issue by tabnk** [flyinghead/flycast#172]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

**Android/Q/Phone**

Github hash: 

30b5469 (Latest android native app)

Hardware: 

Android Phone with Snapdragon 855

**_Description of the Issue_**

Quarter Screen with 2.0 (2xSSAA) or above. Only on Vulkan Renderer. 
OpenGL is fine.

**_Video_**

https://user-images.githubusercontent.com/10874582/106976062-b127e500-6792-11eb-8f24-e88e3543e476.mp4

**Comment by flyinghead** [comment]
I haven't been able to reproduce this issue. I tried both per-triangle and per-pixel sorting, and also tried to change the SSAA setting after starting a game to no avail.

Can you share your emu.cfg file? Anything else that would help me reproduce the issue?

**Comment by tabnk** [comment]
Attached the emu.cfg.

[emu.zip](https://github.com/flyinghead/flycast/files/6016897/emu.zip)

**Comment by tabnk** [comment]
Found the possible issue. 

Enabled Widescreen Hack will cause Quarter Screen with Vulkan Renderer. Widescreen Games Cheat is fine.

**Comment by flyinghead** [comment]
Confirmed. I can now reproduce the problem.

**Comment by flyinghead** [comment]
Should be fixed in the latest build

**Comment by tabnk** [comment]
Tested on latest build, it's working correctly and graphic look great with 2xSSAA. Thank.
