### ISSUE TITLE
LOAD STATE PARAMETER

### ISSUE THREAD

**Issue by CiTrON-AwP** [flyinghead/flycast#173]
Hello everybody
add a parameter to load in state when starting the game...
is a very good feature in the MAME emulator that would be super welcome in **Flycast**

_ex:_
`flycast.exe kofxi.zip -state 1`

pls

**Comment by flyinghead** [comment]
There is now an option to automatically load/save a state at start/end.

**Comment by flyinghead** [comment]
Implemented
