### ISSUE TITLE
Mac icon design proposal

### ISSUE THREAD

**Issue by maxtron95** [flyinghead/flycast#1731]
**Is your feature request related to a problem? Please describe.**
Currently, Mac icon looks out of place with other icons on macOS 11 and higher, I decided to design some icons.

**Describe the solution you'd like**
Use a design of the icons below as an official Mac icon.

**Describe alternatives you've considered**
Setting the icon myself

**Additional context**
There are three variants, one based on the Dreamcast's boot screen, regular menu, and secret menu respectively.
iOS versions and SVG source of icons are included.
![dc-preview](https://github.com/user-attachments/assets/eec3b37c-e274-4d1a-b938-0f01ed8f2001)
[Flycast designs.zip](https://github.com/user-attachments/files/17689131/Flycast.designs.zip)

**Comment by flyinghead** [comment]
Thank you!
I will include them as soon as I can

**Comment by vkedwardli** [comment]
Really love the idea to use BIOS screen as background, but the contrast of the boot screen (white and purple) looks better to me.

Would it be possible to use a lighter background for the BIOS background?

<img width="517" alt="image" src="https://github.com/user-attachments/assets/55cb57bb-7e94-4a26-9253-4218909c0cc3">

**Comment by vkedwardli** [comment]
<img width="507" alt="image" src="https://github.com/user-attachments/assets/d42348d1-9ee3-4fe5-8fd2-ecf1aa1de00b">

May be something like this

**Comment by maxtron95** [comment]
Brightened the bg of the Menu variant.
![flycast-menu-light](https://github.com/user-attachments/assets/c6b299e8-6f61-4c2d-bce9-ceb57187d598)
[Flycast Light.zip](https://github.com/user-attachments/files/17689591/Flycast.Light.zip)

**Comment by vkedwardli** [comment]
This looks fabulous!

**Comment by vkedwardli** [comment]
<img width="435" alt="image" src="https://github.com/user-attachments/assets/83a27284-4764-4b3e-94a4-c8d6b2ce7b0e">
<img width="446" alt="image" src="https://github.com/user-attachments/assets/7e0f691d-9846-40ef-803b-90ade085eb96">

I am testing it in my dock, but the spiral looks a bit small when putting together with other icons?

**Comment by maxtron95** [comment]
Modified the spiral to be larger.
![new-flycast-mac-icons](https://github.com/user-attachments/assets/fb965873-1f20-474c-a2a1-4dd47c604de6)
[Modified-Flycast-Icons.zip](https://github.com/user-attachments/files/17702576/Modified-Flycast-Icons.zip)

**Comment by vkedwardli** [comment]
<img width="259" alt="image" src="https://github.com/user-attachments/assets/eb725e60-edda-4d60-afc4-e675578a9ad1">.
<img width="261" alt="image" src="https://github.com/user-attachments/assets/37624bb9-0372-45dd-acfe-c13f9277979b">.
<img width="261" alt="image" src="https://github.com/user-attachments/assets/d786f6f0-51ed-4633-9ab8-23d7c1c82a8c">.

Thanks a lot!! and sorry for the endless requests above lol. But the spiral has similar size to Quicktime's Q now!!!

**Comment by flyinghead** [comment]
Added the latest menu variant as app icon on macOS in the last master build (still building).
I missed the iOS one but will use it as well when I get a chance.

**Comment by maxtron95** [comment]
> <img alt="image" width="259" src="https://private-user-images.githubusercontent.com/602245/385064917-eb725e60-edda-4d60-afc4-e675578a9ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTI2MDMsIm5iZiI6MTczMTM5MjMwMywicGF0aCI6Ii82MDIyNDUvMzg1MDY0OTE3LWViNzI1ZTYwLWVkZGEtNGQ2MC1hZmM0LWU2NzU1NzhhOWFkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNjE4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWEyMzY3ZmZjYTFjYjczYWJiNTk4Nzk0NGQ4ZTI4MDdkNjRmNjlhOTljNzRmNGNiNTFkNTA0MzA0YWJlYjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.be-066B6aGoOrbUMuxn3VLeg7ysl8KjI8XY5_LZqBJs">. <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/602245/385065048-37624bb9-0372-45dd-acfe-c13f9277979b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTI2MDMsIm5iZiI6MTczMTM5MjMwMywicGF0aCI6Ii82MDIyNDUvMzg1MDY1MDQ4LTM3NjI0YmI5LTAzNzItNDVkZC1hY2ZlLWMxM2Y5Mjc3OTc5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNjE4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGEwYzQ4Y2U2MjdkMmUzNmZkNzgyMDgwZmRhNWNhNGQ4ZTlkNDFhYzUzZDRiMjZlZDQxOGRkZWUzNjllMjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uRzAgNz-iE7d2txYLQs_4DfvHUmYDLEBjaY3VYVFaI8">. <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/602245/385065139-d786f6f0-51ed-4633-9ab8-23d7c1c82a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTI2MDMsIm5iZiI6MTczMTM5MjMwMywicGF0aCI6Ii82MDIyNDUvMzg1MDY1MTM5LWQ3ODZmNmYwLTUxZWQtNDYzMy05YWI4LTIzZDdjMWM4MmE4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNjE4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWU4MTI5MGRiOWJiMTI1OWI1OWI0YWQ5ZTQ2NzliMTdiMzdlZDRlZjllNjlmMGE0ODhkM2Q4OThiYmUyODUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rKVm-T6VYE_idENuGpWaW1AX8Dq3kIK19dIqPu6EHag">.
> 
> Thanks a lot!! and sorry for the endless requests above lol. But the spiral has similar size to Quicktime's Q now!!!

@vkedwardli That's alright, It made a much more improved design than what I started with.

**Comment by flyinghead** [comment]
iOS app icon changed as well. Thank you!

**Comment by XunanCab** [comment]
Thanks! I'm glad I'm not the only one OCD about that. I have been using custom icons I've made for almost a year now for both Flycast and Dolphin because it drove me crazy.

<img width="274" alt="Screenshot 2024-11-19 at 9 08 06 PM" src="https://github.com/user-attachments/assets/d4a4aa41-4d53-4c16-9e5f-95cae345776d">

**Comment by maxtron95** [comment]
![flycast-icon-prototype](https://github.com/user-attachments/assets/8a115c1e-26eb-4776-8b84-194dda4cacce)
This was the first design I was prototyping before I ended up creating the initial icons seen above. I ended up scrapping the design entirely due to the spiral being unreadable at smaller sizes.

**Comment by XunanCab** [comment]
Nice, I like how you used the gradients to give it 3 dimensions
