### ISSUE TITLE
Donald Duck Goin' Quackers - Crash when enabling Full Framebuffer Emulation with Vulkan

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1734]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Flycast version: v2.4-17-gfc3300228

Please forgive me as it may be due to my GPU.

Launch the game with Vulkan.
Flycast crashes with Full Framebuffer Emulation enabled.

![Donald](https://github.com/user-attachments/assets/d6584e71-16f7-42a8-9d97-00c2325b0884)

**Comment by flyinghead** [comment]
It's not crashing here (Nvidia GTX 1080, ubuntu linux). I also enabled the validation layers and no error is reported.
Can you try to install the latest vulkan SDK and enable validation layers? We might get some error report before the crash.

**Comment by kihato** [comment]
It seems like sometimes it doesn't crash.
This is the crash log.
[flycast.txt](https://github.com/user-attachments/files/17693484/flycast.txt)

**Comment by flyinghead** [comment]
That's a lot of errors. I don't see any on my side with this game.
Any other non-default Video setting beside `Full Framebuffer Emulation` (and Vulkan)?
When do the errors start being reported? Around the time of the screenshot above?

**Comment by flyinghead** [comment]
Ok, got it. It happens right when you enable `Full Framebuffer Emulation`. I was able to reproduce the crash on my second try with similar errors. (The first try didn't crash but I got 2 validation errors.)

**Comment by flyinghead** [comment]
Fixed on master

**Comment by kihato** [comment]
I later realized that a verification error had been recorded just by starting up flycast. However, I was able to confirm that all errors, including those, had disappeared.
Thanks a lot!
