### ISSUE TITLE
Android Wait Pop-Up for Virtua Fighter 4 Final Tuned and Beach Spikers

### ISSUE THREAD

**Issue by blisstik** [flyinghead/flycast#1738]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Android 13 (Odin 2 Mini)

Flycast version: 
Latest RetroArch core

Hardware: 

**_Description of the Issue_**

When starting VF4 or Beach Spikers, a pop-up comes up that says "RetroArch ins't responding". There are two options, close the app or wait. If you tap wait, the emulator seems to work but the pop-up comes back again after a few seconds. Not sure what is causing it.

**_Debugging Steps Tested_**

Enabled debug log in RetroArch, pasted below

**_Logs Gathered_**

```

https://pastebin.com/raw/ZgXq1nXL

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by blisstik** [comment]
I'm looking at the log, it seems to set geometry after tapping wait,

**Comment by flyinghead** [comment]
It's a RetroArch limitation/bug. See #1457

**Comment by blisstik** [comment]
Interesting. Other Naomi2 games seem to work just fine like Wild Riders. I saw something about turning off Threaded Rendering, that didn't fix it.

**Comment by flyinghead** [comment]
This usually only happens with GD-ROM games, since the entire GD-ROM is loaded and decrypted before starting the game. Having a slow storage media or running on a low end device is likely to make it worse.

Wild Riders is a rom cartridge game so it's unlikely to happen.

**Comment by blisstik** [comment]
That makes sense, somewhat, those 2 are CHD files. Virtua Striker 3 is also CHD and has no issues, and has a greater file size than Beach Spikers.

I'll talk to the RA guys to see if anyone has an idea of what may be happening. Thank you for looking into this.
