### ISSUE TITLE
Mouse Cursor/Pointer

### ISSUE THREAD

**Issue by DJRM2021** [flyinghead/flycast#174]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 64bit build 1909, Intel UHD 630, 8GB RAM

FEATURE REQUEST:
COULD YOU PLEASE MAKE THE MOUSE POINTER TO AUTOMATICALLY DISAPPEAR AS SOON AS I START A ROM IN FULLSCREEN? THANKS!

**Comment by flyinghead** [comment]
As a workaround, you can capture the mouse with Left-Ctrl + Left-Alt. This will make the mouse cursor disappear.

**Comment by flyinghead** [comment]
The mouse cursor is now hidden in full screen when a game is running.

**Comment by DJRM2021** [comment]
Thank you.
