### ISSUE TITLE
Sonic Shuffle - Title screen graphical glitch

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1743]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Flycast version: v2.4-23-gd259a2e2f

A hatched-like band appears near the bottom of the screen.
It disappears if you enable full framebuffer emulation.
For some reason, it doesn't seem to be displayed when booting with HLE BIOS.

![Sonic Shuffle](https://github.com/user-attachments/assets/011c9e6e-a944-48e1-ac92-98694e717712)

**Comment by flyinghead** [comment]
You need to enable Full Framebuffer Emulation to see this opening animation in all its glory. This game reads back from the framebuffer to create this motion blur effect.
When Full Framebuffer Emulation isn't enabled, it just displays what happens to be in the framebuffer location in vram, mostly garbage from the bios boot sequence I suppose.

**Comment by kihato** [comment]
Thanks for the detailed explanation!

Is it correct to enable Full Framebuffer Emulation in cases where extra images are displayed or flickering on the screen, such as Ikaruga (#1189), July (gray bars on the left and right of the screen), Flag to Flag (Menu Selection), and Monaco Grand Prix (sofdec logo)?

As far as I can count, there are over 40 games (including forced use) where you must enable Full Framebuffer Emulation, but if you start a game without enabling it, you will immediately notice cases such as the lack of transitions in Rayman 2 or the disappearance of the loading screen background in Tomb Raider 4, but in cases where it is only used in specific scenes in Sakura Taisen 3 and Virtua Athlete 2K, the user will need to notice it in that scene.

**Comment by flyinghead** [comment]
I have no problem forcing Full FBE for games that are unplayable without it (Densha de Go! 2, Worms Pinball, etc.)

For other games it's usually a temporary glitch in loading screens or transitions, which doesn't affect gameplay. Forcing Full FBE has drawbacks: no upscaling, no widescreen and needs a reasonably fast platform. So I'd rather not force it for these games.
But let me know if you think some games should have it forced.

**Comment by kihato** [comment]
I agree that it's better not to force it in those games.
I don't think there are any new games that would cause significant disruption to gameplay and require forcing Full Framebuffer Emulation.
If I had to pick one, it would be that the pause menu in Spirit of Speed ​​1937 doesn't appear, but even that's not that important.

For now, I'm closing this issue. Thanks again!
