### ISSUE TITLE
Virtua Fighter 3tb is stuck loading if Widescreen Game Cheats is checked

### ISSUE THREAD

**Issue by TheShiv14** [flyinghead/flycast#1746]
Platform / OS / Hardware:  Windows 11, Android

Flycast version:  2.4

Hardware:  AMD Ryzen 8840u/ Radeon 780m iGPU, Snapdragon 8 Gen 2/ Adreno 730, Dymensity 1200/ Mali GPU

![Screenshot (2)](https://github.com/user-attachments/assets/0faaa1a1-3ee6-4f8d-a33d-2a3271968696)
![Screenshot (3)](https://github.com/user-attachments/assets/491ac618-169e-4073-9c22-cd457365db92)

If widescreen game cheats is turned on when booting, Virtua Fighter 3tb will hang when trying to load the game.

Turning off Widescreen Game Cheats makes the game load like normal.
Problem also persist on Snapdragon hardware on android (Tested with 8 gen 2). 
Mali GPUs don't experience the issue (tested with Dymensity 1200)

**Comment by flyinghead** [comment]
I can't reproduce the issue. On Android you should use version 2.4-1 (current on Google Play) since 2.4 has a serious freeze/ANR issue. It shouldn't happen on Windows however.

Which edition of VF3tb are you using (JP, US, EU)?
What type of media (GDI, CDI, CHD, ...)?
What are your settings in General regarding Broadcast and Cable?
Any other non-default setting?

**Comment by TheShiv14** [comment]
On android I ended up trying 2.4.1 and I used one of the master builds as well. Problem persisted

It's the CHD format

I kept the broadcast on TV composite, but switching from anything else doesn't fix it.

The only other time I've seen it work is when I switched HLE Bios on.

**Comment by TheShiv14** [comment]
I was using the US version of the game and I was using the standard Bios

**Comment by flyinghead** [comment]
I definitely cannot reproduce the problem on my side. I have tried almost all combinations of settings 

The fact that the problem isn't happening with your Mali phone is very suspicious. There is no way the type of GPU or the platform (Windows vs. Android) could have an impact on such an issue.
I suspect the BIOS used might be different on this device. Or some Flycast setting is different on this phone.

**Comment by TheShiv14** [comment]
I think it was a bad bios. I just used the bios from the Mali Device on the snapdragon device and it worked just fine on the Snapdragon device. It's probably a bad bios on my end.

**Comment by TheShiv14** [comment]
Update to one more thing: @flyinghead I was using the DevKit bios and it wasn't Playing nice with it. (For some weird reason the Mali GPU plays nice with it)

If I use a retail bios, it works like normal with widescreen cheat on.

**Comment by flyinghead** [comment]
Widescreen cheats are applied as soon as the bios starts. All the ones included in Flycast are tested and known not to affect the standard bios. But this is not true with other bios flavors like the devkit one.

**Comment by TheShiv14** [comment]
Well that makes sense why it didn't work. Again I thank you
