### ISSUE TITLE
Golf Shiyouyo 2 Multiplayer Online Mode

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#1747]
Golf Shiyouyo 2 online mode has been resurrected! Using standalone Android v2.3, I can get to the lobby, but when the other player starts the game, it stops at "gathering information, please wait". The game dial-up uses a private server with a patched version of the iso. I've added port fowards of udp 20675 & 12079. Any ideas?

**Comment by flyinghead** [comment]
You need to use a recent master build (on or after [fc33002](https://github.com/flyinghead/flycast/commit/fc33002))
