### ISSUE TITLE
Special Settings overrides are not applied when swapping discs for different games

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1748]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Flycast version: v2.4-25-gd618abc32

If you launch a game and then switch discs to a completely different game without exiting,
if the game you switch discs to has any settings in Special Settings, the override will not be applied.

This is the same result if you try to do the same thing after booting into the BIOS.
The same goes for Game Config.

These operations are commonly performed on a real hardware, but with flycast it is more common to exit by clicking "Close Game", so this is unlikely to happen.

**Comment by flyinghead** [comment]
It's a larger problem than just the special settings. There are many things that aren't updated when swapping disks:
- special settings
- per-game VMU file path
- per-game user settings
- per-game input mapping
- network ports
- custom textures path
- cheats (including widescreen)
- save state filename (!)

I plan on fixing these, in particular the save state file name, but not everything. The per-game VMU files are now using the game id (dev branch) but a trick that I often use to get a vmu save for a game is to start the game, eject the disk and replace it with VMU_CD_DREAM_ON, then copy a vmu save to the game VMU I originally started.
I'd rather keep this "feature", not to mention that I can't really change the VMU content without notifying the game.

**Comment by flyinghead** [comment]
Fixed on the `dev` branch.
Everything should now be updated when swapping disk, with the exception of VMUs (which will still points to the previous game id, unless you [re]connect it.)

**Comment by kihato** [comment]
I've confirmed the fix. Thanks!
I found one problem.
It seems that you cannot change the language by overriding it on the BIOS main menu screen. Therefore, TrickStyle is launched in the language before the override, even though flycast specifies English.

**Comment by kihato** [comment]
I finally understand now. Thanks again!
