### ISSUE TITLE
Analog triggers on Xbox controller detected as always pressed

### ISSUE THREAD

**Issue by XunanCab** [flyinghead/flycast#1749]
Platform / OS / Hardware:  MacOS 15.1.1 (24B91)

Flycast version: v2.4-23-gd259a2e2f

Hardware: MacBook Pro 2023; Xbox Controller

In Resident Evil 2, the analog triggers are detected as always pressed as soon as you use them the first time, causing the character to be frozen in the aim position.

I tried multiple xbox controllers all the same result. Resident Evil 3 and Code Veronica work fine. I couldn't find an any dev builds that didn't have this issue, but earlier release builds v2.1 and earlier work fine. I reset the controller mappings and even deleted out the mappings from home directory same result.

**Comment by flyinghead** [comment]
I tested RE2 with a Xbox Series X controller and an old MacBook Pro (intel) and triggers work fine.
Can you try a controller test such as ControllerTest-DJ.cdi or controller_test_2.cdi? You should be able to check if the analog triggers are working or if they get stuck somewhat.
There is no game-specific handling of inputs so the same issue should happen with all games and utilities. Although they might react differently.

Flycast relies on SDL to get controller inputs and it has lots of issues on recent Macs.

**Comment by XunanCab** [comment]
I tested the three xbox controllers using ControllerTest on two Macs running 10.15. On both, release versions 2.2 and earlier worked fine, but starting with release version 2.3 and later after pushing a trigger, it would continue to detect a slight input remaining, but only on versions 2.3 or later. I dug out of a closet an old Mac intel running 10.13 and all the release versions worked correctly. Not sure if it's related to the macOS version or Arm vs Intel, but it does the same behavior consistently based off of the release versions and the macOS versions.

**Comment by flyinghead** [comment]
I doubt this is due to Intel vs Arm, more likely linked to the macOS version (I'm running 10.15.7).

But this is clearly an SDL issue so I suggest you take a look at recent issues there (https://github.com/libsdl-org/SDL) and open a new one if needed.

**Comment by uVSthem** [comment]
I’m having this issue with my Xbox controllers on Windows 11. The controllers appear to work as expected in other emulators, PC games, and the Windows Control Panel, so the issue seems to be specific to this Flycast.
