### ISSUE TITLE
World Series Baseball 2K2 - shadows + freezing issue

### ISSUE THREAD

**Issue by tapperp** [flyinghead/flycast#1757]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Tested on Windows 10, Windows 11, Android 10

Flycast version: 7531f5d	2024-11-22

Hardware: Windows 10 - Intel 6700k + nvidia 3060; Android 10 - Retroid Pocket Mini with SD 865

**_Description of the Issue_**

 1)  Shadows are incorrect, and no combination of settings fixes them. Note, I do have the shadows setting checked. They appear as solid black without transparency. In other Sega Sports games the shadows do render correctly with transparent shadows, i.e. NFL 2K2 (USA), NBA 2K2 (USA).

2)  If I let the game run its demo, it will often freeze at the beginning. Attached is a screenshot where it freezes, and you can also see the solid black shadows issue as well. 

**_Debugging Steps Tested_**

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Flycast - World Series Baseball 2K2 freeze + shadows issue](https://github.com/user-attachments/assets/e84ba886-879e-457e-beae-2d2922741895)

**Comment by flyinghead** [comment]
1. You need to use Per Pixel transparent sorting for correct shadows.

**Comment by flyinghead** [comment]
2. Duplicate of #1038

**Comment by tapperp** [comment]
Ah, sorry. I will close the thread.

**Comment by joepogo** [comment]
Hey @flyinghead , quick question. 

I'm running this on Xbox series x and every time I try to load an exhibition game it freezes as soon as the field loads. 

I have per pixel set and the only game mode that works is home run Derby. Am i missing something?

Edit**

Now I can't even play that lol. I reinstalled even and set the option to per pixel and it still freezes on any field loading screen. 😞

**Comment by flyinghead** [comment]
Flycast version?

**Comment by joepogo** [comment]
I'm using the latest release v2.5. 

Thanks for getting back to me. 👍

**Comment by joepogo** [comment]
I also meant to add I'm using redump chd if that helps. 

I've tried multiple dumps all with the same result. 👍

I even grabbed the 7-22 build and when it loads the stadium it just skips and freezes on per pixel setting.

**Comment by flyinghead** [comment]
I tested on MacOS, both 2.5 and latest dev, without issue. I can't test on xbox at the moment.
Does it work when not using per-pixel? That is, not freezing? (obviously shadows will be wrong)

**Comment by joepogo** [comment]
No, it freezes no matter what setting you have. 

The only mode you can play is home run Derby. 

I just tested the windows 64 version with the same CHD and it does the exact same thing. 👍

**Comment by flyinghead** [comment]
A user has tested this game on xbox without issue: no freeze with per pixel on or off.
It's likely due to your settings or a bad dump.

**Comment by joepogo** [comment]
Thanks @flyinghead, I'm extremely confused. 😊

Is there a way to point me to the tester so I can confirm some info?

I've tested this with a fresh install on windows 64 and Xbox with the only change being per pixel setting and trying to play exhibition, quick start or season always freezes as soon as the field loads. 

I'm also only using verified redump images. Have tested multiple images of this game all with the same result. 

Just to make sure, it's world series 2k2 and not 2k1 we're taking about..

Would it help to create a log file? 

Regardless I appreciate your time with this. 👍

**Comment by flyinghead** [comment]
Here is the comment from the tester. I don't think he has a github account:
> its working on xbox, went into exhibition and played a bit with no issues
> im on latest dev
> per pixel on and off
> they mentioned it also crashed for them with the windows build so i assume it could be their dump or settings

**Comment by flyinghead** [comment]
Creating a log may help.
Any other change to settings beside selecting per pixel? (Including in the General or Controls tabs)
Are you using a real BIOS? Can you try with one if not?

**Comment by Nejsplitter** [comment]
> Here is the comment from the tester. I don't think he has a github account:
> 
> > its working on xbox, went into exhibition and played a bit with no issues
> > im on latest dev
> > per pixel on and off
> > they mentioned it also crashed for them with the windows build so i assume it could be their dump or settings

hey flyinghead, im on github 😄, btw @joepogo are you on the flycast discord? can you join us there as its easier to discuss issues

**Comment by flyinghead** [comment]
@Nejsplitter sorry, my bad. I thought you closed your gh account.

**Comment by joepogo** [comment]
Thanks everyone. I'll hop on the discord chat and go from there. I appreciate everyone's help. 

It's certainly a confusing issue. 

Is there a link to the discord for flycast? 😊

**Comment by Nejsplitter** [comment]
> Thanks everyone. I'll hop on the discord chat and go from there. I appreciate everyone's help.
> 
> It's certainly a confusing issue.
> 
> Is there a link to the discord for flycast? 😊

yep its on the main page of flycast github

**Comment by joepogo** [comment]
Thanks guys!

I made a thorough post today in the general section of the flycast discord. I didn't want it to get completely buried. 👍

I tried to pm you @Nejsplitter on there but it says you aren't allowing messages do hit me up if you want. 

I'm still ripping hair out trying to figure this out lol. 🤣😊

**Comment by joepogo** [comment]
I figured it out! 👍 

Needs to be with bios and not hle. 

Thanks for putting up with a noob. 😄
