### ISSUE TITLE
Feature Request: FPS counter positions

### ISSUE THREAD

**Issue by AgentWho007** [flyinghead/flycast#1758]
My bad if that sounds weird, but I would like to suggest adding an options or settings for the FPS counter to be displayed at either the top left or right since something else is blocking the FPS counter view
![Ikaruga](https://github.com/user-attachments/assets/6f4793b1-8259-4cbc-b012-0303f1126e62)

I don't know what it is? The Retroachievements leaderboard? Or something else
However, if the FPS counter can be moved elsewhere, it might just fix this small (or big?) issue.

**Comment by flyinghead** [comment]
This is an achievement challenge indicator.
When any achievement, notification message or pop up is displayed, the FPS counter is hidden. This is by design since the FPS counter has low priority.
I don't plan on changing this behavior.
