### ISSUE TITLE
Ikaruga: No sound during NAOMI logo on bootup

### ISSUE THREAD

**Issue by JimCarlTay** [flyinghead/flycast#1760]
Platform / OS: NAOMI GD-ROM / Windows 10

Flycast version: 2.4-23-gd259a2e2f (Hash: d259a2e)

Hardware: 12th Gen Intel Core i5-12400 (CPU), Intel UHD Graphics 730 (GPU)

**_Description of the Issue_**

When loading the NAOMI arcade version of Ikaruga, there is no sound during the NAOMI logo.

**_Debugging Steps Tested_**

  * Load the game.
  * While most NAOMI games have sound during the logo, this game does not have it.

**_Logs Gathered_**

None needed.

**_Screenshots_**

None needed.

**Comment by flyinghead** [comment]
The boot logo is drawn by the NAOMI BIOS before it loads the game so it's always shown.
![image](https://github.com/user-attachments/assets/56eaef2b-4225-44d0-80f1-963d9300dc0c)

However this game is rotated by default (vertical screen orientation) so this might confuse your graphic card for some reason?

**Comment by flyinghead** [comment]
Can you try other graphics APIs (OpenGL, DirectX 11, Vulkan)?

**Comment by JimCarlTay** [comment]
This is a sound issue, not a graphics issue. I should have specified this earlier.

**Comment by flyinghead** [comment]
Check the service menu / system assignments if advertise audio is off:
![image](https://github.com/user-attachments/assets/55997ea3-4a39-4480-91e1-028ec70ba120)

**Comment by flyinghead** [comment]
For some reason the EEPROM included in Flycast for this game has Advertise Sound set to OFF.
I guess I made a mistake when I configured this eeprom.

**Comment by JimCarlTay** [comment]
Enabled Advertise Sound in the service menu, which has fixed the issue.

**Comment by flyinghead** [comment]
I found and fixed a bug when creating the EEPROM on first boot. I also removed the default ikaruga EEPROM (most of them aren't needed anymore anyway.) And I ignore this disable audio flag so ikaruga and shangril have sound on by default.

**Comment by JimCarlTay** [comment]
You may change the tag to "sound" and close it as completed.
