### ISSUE TITLE
Suggestion: Allow screenshot folder paths to be specified in emulator settings

### ISSUE THREAD

**Issue by JimCarlTay** [flyinghead/flycast#1761]
**Is your feature request related to a problem? Please describe.**
Yes. When saving a screenshot with a hotkey (I mapped mine to F12), the resulting screenshot goes into the emulator folder's root area (the same area as the .cfg, .exe, and .log files) instead of a folder I can specify to save screenshots in.

**Describe the solution you'd like**
A new setting in the General section that allows folder paths to be specified. When clicking on it, you can set the path to be what you want, like a dedicated folder for screenshots in the emulator folder. This can be handled similarly to the content location folder settings, but you can pick only one folder. If none is set, screenshots will be saved to the emulator folder's root area by default.

**Describe alternatives you've considered**
I have no other solutions that count as alternatives to the main one.

**Additional context**
None needed.

**Comment by flyinghead** [comment]
Screenshots are now saved in the Windows [Known Folder](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid#FOLDERID_Screenshots)  for screenshots. By default `%USERPROFILE%\Pictures\Screenshots`.
Only if this folder cannot be determined, the screenshot is saved in flycast's folder.

I just did a quick test and the screenshot is saved in the expected location (windows 10).

**Comment by JimCarlTay** [comment]
So, do I need to delete and recreate the .cfg file to make that work?

**Comment by flyinghead** [comment]
No, the emu.cfg file is not used for this. This has to do with Windows configuration. Flycast asks windows where this folder is but gets an error. It could be that Flycast isn't allowed to access this folder, or the folder isn't accessible for some reason.

**Comment by JimCarlTay** [comment]
The emulator folder in my case is outside the system partition and in the data partition of my SSD. So, it ends up saving to the root area of the emulator folder.

**Comment by flyinghead** [comment]
Windows should now automatically create the Screenshots folder if it doesn't exist.

**Comment by JimCarlTay** [comment]
Changed status to Completed.
