### ISSUE TITLE
Nightmare Creatures II widescreen cheat is broken

### ISSUE THREAD

**Issue by duke912** [flyinghead/flycast#1763]
Played Nightmare creatures 2 earlier today with widescreen cheat on and it worked fine, then when I played it again 1 hour later it does not work anymore, it just stretches the image instead of true 16:9 widescreen, and widescreen hack has a lot of issues on the sides of the screen. 

I tried deleting the config files, redownloaded flycast core, etc. And none of them worked, only way to play with widescreen is to reload the save state that I have before it stopped working. 

Also, some games have weird bugs, like D2 where widescreen cheat shifts the character to the left side of the screen instead of being on the center.

**Comment by flyinghead** [comment]
I'm surprised there are remaining widescreen cheats for Windows CE games in Flycast, and this is the last one. It's a miracle that it worked fine in the first place. Cheats usually don't work with windows CE games because memory locations aren't fixed, and there's no easy way to get around this.
