### ISSUE TITLE
System SP Love & Berry Input Issue

### ISSUE THREAD

**Issue by Kdash4** [flyinghead/flycast#1768]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 13

Flycast version: 2.4

Hardware: Sony Xperia 1 V

Hello. Sega system sp game called Love & Berry. I can't play this game both with dual shock 4 controller and touch screen virtual gamepad. Any input doesn't work with this game.

Another system sp game Tetris giant works flawlessly. And the rest of Dreamcast, Naomi games works great with my gamepad and touchscreen. Only love & berry doesn't read input.

Is this an issue or am I doing something wrong with contoller settings?

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Love & Berry is a bit special because each player only has one button, but you need to use both buttons to navigate the menus. However P1 button should work (button A) both with the virtual gamepad and a normal gamepad.

I recently did some improvements regarding this on the `dev` branch. First, player 2 button is mapped to P1 button 2, so both can be used with any gamepad. And the Android virtual gamepad now has an arcade layout, where unused buttons are hidden and now features an Insert Card button and Service Mode switch. I strongly recommend you test the latest build on the `dev` branch.
![image](https://github.com/user-attachments/assets/0781c225-099b-4ca8-9392-6c8a7a09f56e)

**Comment by Kdash4** [comment]
> Love & Berry is a bit special because each player only has one button, but you need to use both buttons to navigate the menus. However P1 button should work (button A) both with the virtual gamepad and a normal gamepad.
> 
> I recently did some improvements regarding this on the `dev` branch. First, player 2 button is mapped to P1 button 2, so both can be used with any gamepad. And the Android virtual gamepad now has an arcade layout, where unused buttons are hidden and now features an Insert Card button and Service Mode switch. I strongly recommend you test the latest build on the `dev` branch. ![image](https://private-user-images.githubusercontent.com/16261910/392876886-0781c225-099b-4ca8-9392-6c8a7a09f56e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MjQ3OTEsIm5iZiI6MTczMzQyNDQ5MSwicGF0aCI6Ii8xNjI2MTkxMC8zOTI4NzY4ODYtMDc4MWMyMjUtMDk5Yi00Y2E4LTkzOTItNmM4YTdhMDlmNTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE4NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Y2ZhYmExNGIzMDMzYjM5NTk3YjQ3YWQzMmRhYTIxYmRhOTIwYTA0N2IxMmJkMTJlODE0ZjE1NzQ4ODBiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IDHxch6bnSjEoSE8w8HO2ntrtQjYcYvjokK8We6AXiM)

Thank you so much for your explanation. I did what you said and i can play the game now :)
By the way flycast is great emulator, you are doing amazing job. Thanks again, have a nice day.
