### ISSUE TITLE
Racing Wheel & Arcade stick support (X-Arcade)

### ISSUE THREAD

**Issue by Arcadeguy781** [flyinghead/flycast#1777]
As the title states, we only have XBOX controller support right now, but I'd love to see Logitech racing wheel support for games like Crazy Taxi and arcade stick support for games that use arcade sticks on real hardware.

**Comment by flyinghead** [comment]
> we only have XBOX controller support right now

Are you sure this is a flycast enhancement request?

**Comment by Arcadeguy781** [comment]
> > we only have XBOX controller support right now
> 
> Are you sure this is a flycast enhancement request?

Additional input options
