### ISSUE TITLE
SA2 Render issue

### ISSUE THREAD

**Issue by JC306010** [flyinghead/flycast#1778]
Platform / OS / Hardware: Tested on Both MacOS Sonoma 14.6.1 and Windows 11 24H2

Flycast version: v2.4 (8108e6390)

Hardware: 
Windows: AMD Ryzen 5 5600h, Nvidia RTX 3050 ti, 16GB RAM
MacOS: Apple M1, 8GB RAM

**_Description of the Issue_**

In Sonic Adventure 2 while gliding as Knuckles, his eyes appear to be floating in front of his face

**_Debugging Steps Tested_**

  * I tried changing almost all of the video settings, but none of them fixed this issue

**_Logs Gathered_**
00:00:000 sdl/sdl.cpp:734 N[RENDERER]: Monitor refresh rate: 60 Hz (1440 x 900)
00:00:000 rend/vulkan/vulkan_context.cpp:269 N[RENDERER]: Vulkan API 1.1. Device Apple M1
00:00:001 rend/vulkan/vulkan_context.cpp:423 N[RENDERER]: Device extension enabled: VK_KHR_swapchain
00:00:001 rend/vulkan/vulkan_context.cpp:423 N[RENDERER]: Device extension enabled: VK_KHR_portability_subset
00:00:001 rend/vulkan/vulkan_context.cpp:423 N[RENDERER]: Device extension enabled: VK_EXT_metal_objects
00:00:001 rend/vulkan/vulkan_context.cpp:426 N[RENDERER]: Device extension unavailable: VK_EXT_provoking_vertex
00:00:015 rend/vulkan/vulkan_context.h:326 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:017 ui/gui.cpp:330 N[RENDERER]: Screen DPI is 227, size 2880 x 1582. Scaling by 1.70
00:00:141 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
00:00:182 rend/vulkan/vulkan_context.h:326 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:01:426 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:01:435 hw/mem/addrspace.cpp:467 N[VMEM]: BASE 0x308010000 RAM(16 MB) 0x314010000 VRAM64(8 MB) 0x30c010000 ARAM(2 MB) 0x328010000
00:01:441 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:01:445 hw/mem/addrspace.cpp:467 N[VMEM]: BASE 0x308010000 RAM(16 MB) 0x314010000 VRAM64(8 MB) 0x30c010000 ARAM(2 MB) 0x328010000
00:01:448 emulator.cpp:56 N[BOOT]: Game ID is [MK-51117]
00:01:450 emulator.cpp:56 N[BOOT]: Game ID is [MK-51117]

**_Screenshots_**

<img width="1440" alt="glitch front view" src="https://github.com/user-attachments/assets/b31958b0-d303-4ef9-9e83-4f6840e03dc7" />
<img width="1440" alt="glitch side view" src="https://github.com/user-attachments/assets/edbe0372-9e72-41c5-8240-35890aeee848" />

**Comment by flyinghead** [comment]
Can you upload a savestate?

**Comment by JC306010** [comment]
[Sonic Adventure 2 v1.008 (2001)(Sega)(NTSC)(US)(M5)[!].state.txt](https://github.com/user-attachments/files/18142060/Sonic.Adventure.2.v1.008.2001.Sega.NTSC.US.M5.state.txt)

**Comment by flyinghead** [comment]
Thank you. I can reproduce it here.
Now the main question: does it happen on real hardware?
It doesn't seem to be a GPU glitch (depth issue, loss of precision, ...) but I couldn't find any real console game footage that shows this effect. (He's usually gliding away from the player's PoV.)
