### ISSUE TITLE
Shenmue 1 (USA) hang IF Widescreen Game Cheats is enabled

### ISSUE THREAD

**Issue by tabnk** [flyinghead/flycast#180]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Android/Q/Phone

Github hash: 
https://github.com/flyinghead/flycast/commit/db910b3

Hardware: 
Android Phone with Snapdragon 855

**_Description of the Issue_**

If **Widescreen Game Cheats** is enabled, it will hang/stuck at "Starting ....". 

Disable Widescreen Game Cheats fixed this Issue. Normal widescreen hack work fine too. Tested on both Vulkan and OpenGL renderer.

**Comment by flyinghead** [comment]
I confirm that the BIOS boot hangs when this cheat is activated. A work-around is to use HLE BIOS.

**Comment by tabnk** [comment]
It's playable now. Thank.

**Comment by flyinghead** [comment]
Should be fixed in the latest master build: the cheat now also works with regular BIOS.

**Comment by tabnk** [comment]
Tested. It playable now. Thank.
