### ISSUE TITLE
Windows CE doesn't work on Android?

### ISSUE THREAD

**Issue by BeF1990** [flyinghead/flycast#185]
Platform / OS / Hardware:
Android 10
Samsung Galaxy TAB S6 8/256GB

I tried RetroArch and standalone versions of Flycast, but on both I have the same problem.
I tested Tomb Raider 4 and Urban Chaos games and in both cases game crashes after few minutes. No errors, no freezes just throwing to the desktop.

I tried all options:
- with bios
- with HLE bios
- force Windows CE

and more, but no changes.

**Comment by flyinghead** [comment]
Windows CE is supported on Android (64 bits only).

There might be an issue with these games.

**Comment by flyinghead** [comment]
I can confirm a crash after a few minutes of playing with some games, namely Armada and 4X4 Evolution.

**Comment by BeF1990** [comment]
My device is one of the flagship tablet from last year and 64 bits of course.

What do you mean "issue with these game"? Wrong/broken copies or games are not supported by the emulator?

Is there a compatibility game list or something?

**Comment by flyinghead** [comment]
The latest build fixes a crash that was happening for some Windows CE games on arm64. Hopefully this is the one you reported.

**Comment by BeF1990** [comment]
I downloaded the latest build and it looks like everything is fine. TR 4 works without crashes. Good job devs!
I haven't tested another games yet, but I'll let you know later.

The only one issue with TR 4 now is sound. It doesn't work fluently and sometimes you can hear glitchy sound. I'll try to make video with the issue.
