### ISSUE TITLE
Apple M1's page size differs, causing crash.

### ISSUE THREAD

**Issue by MaddTheSane** [flyinghead/flycast#186]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
macOS/ Apple M1
Github hash: 
06ca9c205f689d9cb0ac449d4652e2ce8f5be8c0 (#184), based off of 859a8dc8fbf55574c8b76d07d7274b4b2660c766
Hardware: 

**_Description of the Issue_**

Apple Silicon's `PAGE_SIZE`, at least on the M1, is 16384. As it is set up, Flycast always assumes the page size on non-Android devices to be 4096.

Digging around, on macOS versions targeting 11 or later (Including all ARM Macs), the macros `PAGE_SIZE`, `PAGE_SHIFT`, and `PAGE_MASK` are defined to `vm_page_size`, `vm_page_shift`, and `vm_page_mask`, respectively. And the `vm_` values are declared as `extern` symbols:
```
extern  vm_size_t       vm_page_size;
extern  vm_size_t       vm_page_mask;
extern  int             vm_page_shift;
```

The Best way is  to make values that relies on `PAGE_SIZE` or `PAGE_MASK`, such as `unprotected_pages` and `blocks_per_page` in blockmanager.cpp, to be allocated as soon as possible instead of being a fixed-size array. A quick-and-dirty fix would be to set the `PAGE_SIZE` macro to 16384 only for Apple Silicon machines.
**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Fixed
