### ISSUE TITLE
Crash when opening games with texture Packs on Windows

### ISSUE THREAD

**Issue by rkimbal45** [flyinghead/flycast#187]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Windows 10

Github hash: 

Hardware:  i7-7820HK, 16Gb ram, Nvidia GTX 1080 8Gb DDR 5

**_Description of the Issue_**

When Starting games with a texture pack it crashes immediately at the logo screen.   Tried with 2 games.  Mortal Kombat and Soul Reaver.  Same behavior in both.  

**_Debugging Steps Tested_**

 Only occurs with the texture pack enabled.  Tried with default settings and with vulkan settings.
I tried multiple builds.  It worked with older builds until I reached

a23c895 | 2021-01-19T17:36:38.000Z

After which no build I try works with the texture pack enabled.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

It goes to this screen and then the app just closes.
![image](https://user-images.githubusercontent.com/20320485/109174734-1bf58c00-7753-11eb-9ea7-cb41c8e1d11a.png)

**Comment by flyinghead** [comment]
The crash should be fixed in the latest build
