### ISSUE TITLE
Soul Reaver Gameplay Crash when encountering humans

### ISSUE THREAD

**Issue by rkimbal45** [flyinghead/flycast#188]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Windows 10 

Github hash: 

Hardware: i7-7820HK, 16Gb ram, Nvidia GTX 1080 8Gb DDR 5

Add a short, concise description of the issue here

at several points in the game, Raziel comes accross humans who either worship him or try to kill him.  The game repeatedly randomly crashes when humans are around.  The game plays stably for long stretches, but crashes often and repeatedly during these encounters.  I have found that if I kill the humans quick or get past them quick enough or looking the right way or something the crash won't occur.  but I can repeat it if I load the save state and approach the humans the same way.

**_Debugging Steps Tested_**

Tried in a few locations.   results the same in each area where humans are encountered.   Basically load the save state, walk around without killing the human and it crashes.  if I switch to spectral realm (the humans disappear) or kill the human quickly and no crash occurs.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

Here is the save state in the location where the crash occurs

[legacy.zip](https://github.com/flyinghead/flycast/files/6044186/legacy.zip)

**Comment by rkimbal45** [comment]
I did try with a few build versions.  I did try on the latest build as well.  Same issue.

**Comment by flyinghead** [comment]
It looks like this crash is caused by the widescreen cheat for this game.

Try with Widescreen Game Cheats disabled.

**Comment by rkimbal45** [comment]
Crashes were still happening some of the time until I switched to a GDI file.  CDI file may have been an issue as well.
