### ISSUE TITLE
Turbo Mode and Save State

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#19]
| Platform | Branch | Hash | CIDL |
| Windows 10-x64 | master | 6904191 | Downloaded from build site |

Description of the Issue

1. Would you add Turbo Mode to flycast? (like redream, when press desire button the emulator runs so fast like 5x or 6x)
2. Would you add Save State to flycast?

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
Saving and loading a Save State is already possible. Am I missing something?

**Comment by mohsinous** [comment]
oh, actually i cant find it!!!
what about Turbo Mode!!?

**Comment by mohsinous** [comment]
@flyinghead i am sorry!!! i found it. my apologize!!!

**Comment by flyinghead** [comment]
Fast-forward a.k.a. turbo is here: https://github.com/flyinghead/flycast/commit/ae4f378747104ef2ba5fa19738e7df6a46be12ea

**Comment by mohsinous** [comment]
thanks @flyinghead!

**Comment by flyinghead** [comment]
Make sure to delete your `data/buttons.png`

**Comment by mohsinous** [comment]
thanks @flyinghead
