### ISSUE TITLE
[Vulkan] "blocky" corrupted blocks running many games (Mslug 6, mvc2, etc)

### ISSUE THREAD

**Issue by MagnusPrime12** [flyinghead/flycast#194]
Platform / OS / Hardware:  Windows 10 latest version, RX 480 8GB, Ryzen 2600, Radeon Adrenaline 21.2.3 (latest AMD driver)
Flycast Version: Flycast Dojo for FightCade version : dojo-0.3.2 (settings screenshot)

**_Description of the Issue_**

Games run at full speed for me only with Vulkan. But games like MvC2 and Mslug 6 has screen corruption in form of blockiness. Mslug 6 is the worst (attached) and is unplayable. I assume many 2D games will have similar issues. But MVC2 would have lines on the characters, still playable, but annoying "blocky" lines corruption. Like missing a layer of emulation almost.

**_Debugging Steps Tested_**

1. I tried various settings like in the graphics areas. doesn't seem to help. Still "blocky" and "corrupted". Attached is what i have latest.
2. If I use OGL, everything is normal, but input lag and general lag is horrendous.

**_Screenshots_**
<img width="468" alt="Setting1" src="https://user-images.githubusercontent.com/79935256/109697534-5a78b580-7b5c-11eb-8c27-0eb936bf880b.PNG">
<img width="464" alt="Setting2" src="https://user-images.githubusercontent.com/79935256/109697536-5a78b580-7b5c-11eb-82b2-bc71bf78b8fc.PNG">
<img width="471" alt="Capture" src="https://user-images.githubusercontent.com/79935256/109697537-5b114c00-7b5c-11eb-9908-85ab35463532.PNG">
<img width="454" alt="Image1" src="https://user-images.githubusercontent.com/79935256/109697538-5b114c00-7b5c-11eb-9c1d-ed0dfb2700e8.PNG">
<img width="472" alt="Capture" src="https://user-images.githubusercontent.com/79935256/109699582-bcd2b580-7b5e-11eb-908f-f99c0c570632.PNG">

**Comment by flyinghead** [comment]
Set  `Texture Upscaling` to 1. Only use this option after verifying that it works fine with the game.

**Comment by MagnusPrime12** [comment]
@flyinghead , didn't work. Still had the same issue. Here is another screen shot...more obvious.

<img width="525" alt="Capture" src="https://user-images.githubusercontent.com/79935256/109703742-d32f4000-7b63-11eb-83ee-355a6c16c0c8.PNG">

**Comment by flyinghead** [comment]
Any change when setting `Transparent Sorting` to 'Per Triangle`?

**Comment by MagnusPrime12** [comment]
@flyinghead , nope, still the same thing.

**Comment by flyinghead** [comment]
Can you try the latest Flycast standalone build?

I'm using an RX550 at the moment (ubuntu 20) and no issue with mslug6 or any other game.

**Comment by MagnusPrime12** [comment]
> Can you try the latest Flycast standalone build?
> 
> I'm using an RX550 at the moment (ubuntu 20) and no issue with mslug6 or any other game.

Where can I find it? Not too familiar with Github in general.

**Comment by flyinghead** [comment]
Latest master: https://flyinghead.github.io/flycast-builds/

**Comment by MagnusPrime12** [comment]
> Latest master: https://flyinghead.github.io/flycast-builds/

Will do so later and reply back. TIA!

**Comment by MagnusPrime12** [comment]
@flyinghead , how very strange. I tried the latest standalone. I would check "vulcan" box, save it, close the emu. Restart it, I see vulkan still check. Then I would load any game, game would load, but I felt it was laggy...then I restart the emu and the vulkan box is unchecked...almost like it's not allow me to play with Vulkan...so strange.

**Comment by MagnusPrime12** [comment]
@flyinghead , just reporting back. I took an older 2/18 master build (flycast-win_x64-fast-17e46a1d8f9a3c40b132280eb72abc9db4ec98fe)  and that one saved vulkan settings fine. And roms runs crisp. So whatever you guys did on later builds messed up the vulkan saving/settings saving option. Please regress latest build on why settings are not being saved...

**Comment by flyinghead** [comment]
The Vulkan setting regression should be fixed in the next build: https://github.com/flyinghead/flycast/commit/ca107953fe2d4495740ac77598a60c82c7420492

**Comment by MagnusPrime12** [comment]
@flyinghead , I just test it. It works now!!! You guys are quick and awesome. Thanks for everything you have done to bring back my childhood.
