### ISSUE TITLE
fullscreen on linux not actually full screen

### ISSUE THREAD

**Issue by rcampbel3** [flyinghead/flycast#196]
Platform / OS / Hardware:  Linux Ubuntu 20.04

Github hash:  03/02/2021

Hardware:  Core 2 quad, Nvidia 1030

Fullscreen on Ubuntu isn't really fullscreen

Hi, I would like to request a simple UI toggle for fullscreen as well as a commandline flag. I would expect '-f' or '--fullscreen' to work

I read the other bug report about needing to do this:
flycast -config x11:fullscreen=yes

I also read about how F11 toggled fullscreen...
However, when I start it, it's not actually fullscreen. It leaves the ubuntu dock on the left side and the status bar on the top.
WHen I edit the emu.cfg file, I see:

```
[window]
fullscreen = no
height = 1016
width = 1838
```

I can manually edit it to say:

```
[window]
fullscreen = yes
height = 1080
width = 1920
```
and then flycast will start fullscreen, until I hit F11 twice and then it goes back to not being full screen.

Also... how do I exit?!? I would like to be able to use escape to exit emulation or at least have an exit menu item instead of needing to get out of fullscreen mode to close flycast or kill it from the console.

Thanks!

**Comment by flyinghead** [comment]
Using Ubuntu 20.04 as well, I don't have the same behavior. Pressing F11 does make the window full screen, without dock or title bar. This is true for all windows, not only Flycast.

The actual command-line option to use is: `-config window:fullscreen=yes`, which is strictly equivalent to enabling the `fullscreen` emu.cfg entry:
```
[window]
fullscreen = yes
```

You can bind Exit to a keyboard key or gamepad button in the settings. It is not bound by default.

**Comment by j8r** [comment]
`-config window:fullscreen=yes` works for me too. What driver are you using, nouveau or the proprietary driver?

For the exit issue, I got the same struggle too. It would be a simple and user-friendly solution to add an Exit button on the main menu, next to `Settings`, compared to configure and remember a key binding. That's how some other emulators do (like PPSSPP)

**Comment by rcampbel3** [comment]
I'm running the nvidia driver.

```
vendor   : NVIDIA Corporation
model    : GP108 [GeForce GT 1030]
driver   : nvidia-driver-460 - distro non-free recommended
```

**Comment by flyinghead** [comment]
FYI the fullscreen key binding is now Alt+Enter.
Assuming this is resolved.
