### ISSUE TITLE
No CZ onscreen buttons

### ISSUE THREAD

**Issue by ZiNuKa** [flyinghead/flycast#204]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
In the latest build, Naomi/AW service buttons can be pressed with the on-screen gamepad:
RT + A -> D (Coin)
RT + B -> C (Service)
RT + X -> Z (Test)
