### ISSUE TITLE
(Android) Regardless of settings there is no smooth scrolling in Atomiswave-to-DC ports

### ISSUE THREAD

**Issue by RaduNastase** [flyinghead/flycast#207]
Easily observable in KOF XI character select screen:
The round writing around higlighted character portraits, should animate/scroll perfectly smooth, but it has a constant micro-stutter every half second.

Tried Retroarch 32, both GL and Vulkan and Retroarch 64, both GL and Vulkan. No setting, audio or video mitigates that, neither inside the Core or Retroarch itself.
In Core settings, if Framerate is set to Full Speed, the frame counter shows constant 60 fps, but the micro stutter persists.
If Framerate is set to Normal, it shows average 59.3 but it behaves EXACTLY the same, so there's a problem here.
Showing 59.3 should result in exacy that king of stuttering, but synching to 60 should be perfectly smooth, not behave the same.

Internally, the game simply doesn't sync to Retroarch's video settings as it should.

With the exact settings, DC games and normal Atomiswave games have smooth scrolling (though Atomiswave native roms are more demanding on resources compared to the ports, which is why it'd be amazing to have them work with perfect sync).

Thanks so much!

**Comment by MojoJojoDojo** [comment]
You know this issue tracker is for standalone and not the Retroarch core right lol.

**Comment by RaduNastase** [comment]
Standalone has the same issue. A bit worse even.

**Comment by RaduNastase** [comment]
I Retroarch, this is fixed by disabling Audi Sync, for anyone facing the same issue.
