### ISSUE TITLE
Widescreen Mode for Android Phone with wider than 16:9 aspect ratio

### ISSUE THREAD

**Issue by tabnk** [flyinghead/flycast#209]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Android/Q/Phone

Github hash: 
https://github.com/flyinghead/flycast/commit/06be0d927b69fdc97efb121f17fff7668087bc87

Hardware: 
Any Phone with wider than 16:9 aspect ratio.

**_Description of the Issue_**

Enabled widescreen mode:

Before https://github.com/flyinghead/flycast/commit/06be0d927b69fdc97efb121f17fff7668087bc87 it can fully utilize the whole aspect ratio of a phone however after this https://github.com/flyinghead/flycast/commit/06be0d927b69fdc97efb121f17fff7668087bc87 it will fixed at 16:9 only.

**Comment by Gonckzilla** [comment]
Not sure if it's right to comment on here, I don't use GitHub often, but this feature would be awesome to have, seeing as Reicast has it. Maybe there's some line we could add on the emu.cfg file to change the horizontal pixel count? 

Either way, to add something to the suggestion: draw over phone notch would be orgasmic. Not that the emulator already isn't; thx for all the marvellous work!

**Comment by flyinghead** [comment]
New `Super Widescreen` option available

**Comment by tabnk** [comment]
It's beautifully displayed on my 18.9:9 Phone. Thank

**Comment by flyinghead** [comment]
Build https://github.com/flyinghead/flycast/commit/d20fc971c953e326ed55ec8084bb88f0e4a116ad now renders over phone notches / display cutouts.

**Comment by tabnk** [comment]
Tried this https://github.com/flyinghead/flycast/commit/d20fc97 build. Unable to reach 60fps even at native resolution.  

Whether native, 2x or 3x graphic look like at max out resolution.

**Comment by flyinghead** [comment]
Yes, confirmed. This is apparently due to https://github.com/flyinghead/flycast/commit/1ddb82f334a327823efa601119ff63295343967a, so not related to android notches.

More investigation needed.
