### ISSUE TITLE
Underclock option

### ISSUE THREAD

**Issue by RaduNastase** [flyinghead/flycast#210]
Is underclocking the Dreamcast CPU clock possible?

**Comment by flyinghead** [comment]
Yes, it is.

For example, the interpreter is a /8 underclocked CPU.

**Comment by MojoJojoDojo** [comment]
Should have been "overclocking support"
That one is more important for things ie getting 60 fps instead of 30 fps in games.

**Comment by RaduNastase** [comment]
Could such an option be available in Gui/Core, similar to, for example, Mame Slider?

Thanks!

**Comment by flyinghead** [comment]
available on the dev branch
