### ISSUE TITLE
Feature request: multiple keyboard support, possibly through raw input

### ISSUE THREAD

**Issue by n1ghttrap** [flyinghead/flycast#214]
Obvious use case being Typing of the Dead's 2 player mode.  Thanks for your consideration.

**Comment by flyinghead** [comment]
Check the `fh/directx` branch that has a new RawInput driver supporting multiple keyboards. Tested with Typing of the Deads 2.

**Comment by n1ghttrap** [comment]
> Check the `fh/directx` branch that has a new RawInput driver supporting multiple keyboards. Tested with Typing of the Deads 2.

That's awesome.  Confirmed it works as well.  Thank you.
