### ISSUE TITLE
black screen in full screen and video card stopped responding

### ISSUE THREAD

**Issue by JaegerFox** [flyinghead/flycast#217]
Platform / OS / Hardware: Windows 8.1 Intel HD Graphics 2500

Github hash: 

Hardware: Integrated Video Card

**_Description of the Issue_**

When I start Flycast in fullscreen the screen looks black and the video card stopped responding
the last functional build is the 0b6420d

**_Debugging Steps Tested_**

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

https://user-images.githubusercontent.com/29095345/113567008-5fa1a800-95d3-11eb-8e4c-3261ee32ab87.mp4

**Comment by flyinghead** [comment]
I tested on Windows 10 and Intel HD+ 640 and no issue when switching to full-screen and back. I don't see any Open GL error either.

Do you have the same result when using ALT+ENTER to switch to full-screen?

**Comment by JaegerFox** [comment]
When I start Flycast Windowed and I press Alt+Enter I dont have issues, just happen when i start in fullscreen

**Comment by flyinghead** [comment]
Please upgrade to latest master and reopen if the issue persists.
