### ISSUE TITLE
Provide a Flatpak

### ISSUE THREAD

**Issue by j8r** [flyinghead/flycast#218]
First of all, thanks you for this project!

Using a Flatpak would ease the installation, but more importantly the process to keep it up-to-date.
Several other emulators have one, like [PPSSPP](https://github.com/flathub/org.ppsspp.PPSSPP) and [Citra](https://github.com/flathub/org.citra_emu.citra).

Other Flatpak example: https://github.com/flathub/org.pegasus_frontend.Pegasus

I can help on this if wanted.

**Comment by flyinghead** [comment]
Any and all help appreciated!

**Comment by j8r** [comment]
Ok, I'll do it and [follow the procedure](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app). Could it be possible to have a simple `Development` section how to build? I can read https://github.com/flyinghead/flycast/blob/master/.github/workflows/c-cpp.yml, but that's not ideal.

I see there are already a desktop file and an icon image at https://github.com/flyinghead/flycast/blob/master/shell/linux. Can be better to also put the appstream metadata file in the same place too? Will I need to use/tweak this Makefile? I don't see it used in the CI.

As far as I know, we need to put this 4 things in the flatpak at given paths:
- the binary (to build)
- an icon image
- a desktop file
- an appstream file (todo)

**Comment by flyinghead** [comment]
We are migrating from Makefile to cmake so both are available but cmake is the preferred way. All github CI builds use it.
It will use SDL2 if found, otherwise fall back to using evdev, x11 and alsa.

**Comment by j8r** [comment]
@flyinghead I got the Flatpak working :). #221 ready for review.
I'll also mention you in the PR I'll make against https://github.com/flathub/flathub afterward.

**Comment by j8r** [comment]
Is MiniUPnPc important? I didn't include it in the build.

**Comment by flyinghead** [comment]
Not sure what you mean by important. Currently MiniUPnpc is required to build. But it could be made optional if needed.

**Comment by j8r** [comment]
I said that because I got this this message when building:
`-- Could NOT find MiniUPnPc (missing: MINIUPNP_INCLUDE_DIR MINIUPNP_LIBRARY)`

This didn't prevent the build to succeed.

**Comment by flyinghead** [comment]
Flycast includes the source of Miniupnpc so it will compile and link against it if not available on the build system.

**Comment by j8r** [comment]
For reference, I asked in https://github.com/flathub/flathub/issues/1582. I guess we'll have to modify manually until we got an answer.

**Comment by j8r** [comment]
I got the auto update of the repository commit working - nothing to care about anymore :slightly_smiling_face:

**Comment by flyinghead** [comment]
Good job. Thanks a lot for your help on this!
