### ISSUE TITLE
Texture replacements looking weird

### ISSUE THREAD

**Issue by Kupo91** [flyinghead/flycast#219]
Hi,

I couldn't find a lot of information about the texture replacement feature. So I don't know what is wrong here.
I just tested the replacement with textures, which I've dumped before and it looks like this:

![Grandia_II_E-210408-021335](https://user-images.githubusercontent.com/41426906/114466135-57a3c280-9be8-11eb-9c56-aaf2be51cb53.png)
![Grandia_II_E-210408-021414](https://user-images.githubusercontent.com/41426906/114466196-6be7bf80-9be8-11eb-983b-62bbb098e17d.png)

Tested it with opengl and vulkan, libretro core and standalone, windows and lubuntu.

But textures look like this or similar. Are there any specific requirements for the replacement textures?

Oh and the game is Grandia II (EU)

**Comment by flyinghead** [comment]
Some textures have an alpha channel and some don't. The main requirement is to keep the alpha channel when present.

Pictures can be .PNG or .JPG. (JPEG can only be used for textures without alpha channel.)

**Comment by flyinghead** [comment]
If you use the dumped textures as replacement textures, does the game display correctly?

**Comment by Kupo91** [comment]
> 
> 
> If you use the dumped textures as replacement textures, does the game display correctly?

No, that's what I tried to say. I tried with dumped textures as replacement and the result looked similar to this. Not exactly like this, because I was too lazy to take new screenshots. But it also has the weird colors in Screenshot 1 and the compass isn't white but isn't displayed correctly too

**Comment by flyinghead** [comment]
I identified the problem and it happens with some palette textures. These textures are normally handled on the GPU side but the custom textures that replace them should not.

Unfortunately the fix isn't trivial.

**Comment by Kupo91** [comment]
I understand. Thank you anyway, maybe sometime in the future then

**Comment by flyinghead** [comment]
This should be fixed in the latest build

**Comment by Kupo91** [comment]
Sorry, for the late response, I can confirm, it works for me, too. Thanks a lot for your work! :)
