### ISSUE TITLE
Unable to map arcade sticks buttons/lever under Apple M1

### ISSUE THREAD

**Issue by Neirene** [flyinghead/flycast#220]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
OSX / macOS Big Sur 11.2.3 / MacBook Air M1 512GB/16GB RAM

**_Description of the Issue_**

Under MacOS BigSur 11.2.3 Is not possible to use arcade sticks with Flycast, once you plug it, the emulator detects the device but won't let you map any buttons or the lever. Only XboxOne or PS4 controllers are working.

This was tested with a Qanba Drone compatible with PS3/PS4/PC 

**_Debugging Steps Tested_**

  * Connect your fighting stick set the switches to PS4 mode and start Flycast.
  * Go to Settings > Controls and under "Physical Devices" you should see your arcade stick on port A
  * Click on the "MAP" button to begin the button mapping setup, you will notice you will be unable to map anything as none of the buttons or the lever inputs are detected.
  * Repeated the same steps from above with the arcade stick switch set to PS3 mode and the stick doesn't even appears under physical devices anymore. 

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

Arcade Stick Switch set to PS3 mode 
![image](https://user-images.githubusercontent.com/5244595/114468751-43fa5b00-9bec-11eb-8aee-9ef90a387e90.png)

Arcade Stick Switch set to PS4/PC mode 
![image](https://user-images.githubusercontent.com/5244595/114468799-54123a80-9bec-11eb-8263-eb244a496572.png)

**Comment by flyinghead** [comment]
I believe this is a Rosetta bug. So the fix is in Apple's hands (or SDL perhaps).

**Comment by Neirene** [comment]
The guys at OpenEmu which is an emulator frontend for Mac allows to use the fighting stick and it works with all their emulators correctly(sadly they haven't implemented Flycast yet but working on it it seems) over there the stick is working without issues so I don't think it's an OS limitation at this point. 

[https://github.com/OpenEmu](url)

**Comment by Neirene** [comment]
Waiting for macOS 11.3 to be released next week to give it a final try before we can close this ticket.

**Comment by Neirene** [comment]
Testing with macOS 11.3 build 20E232 can confirm, the issue with the fighting stick button mapping is fixed.

Everyone running macOS and specially people with M1 machines are encouraged to upgrade to 11.3 to avoid any issues with Flycast using fighting sticks or other non-standard controllers. 

Closing this ticket!
