### ISSUE TITLE
Exit the application when games are opened from the CLI

### ISSUE THREAD

**Issue by j8r** [flyinghead/flycast#222]
Dedicated issue from a previous discussion n https://github.com/flyinghead/flycast/issues/196.

## Context

I made a game library with [Pegasus Frontend](https://pegasus-frontend.org/). All can be controlled by the gamepad, and of course the keyboard.
When clicking on a Dreamcast game, it is opened by invoking the `flycast` command, and works great.

## Issue

Running the games in fullscreen works fine, but there are several issues when wanting to exit the game:
- no way to exit Flycast using the gamepad; having to plug a keyboard is not practical
- most people who have directly opened a game through the command line would want to exit the Flycast application when doing in-game menu => `Exit` button on a game, not going to the Flycast main menu.

## Solutions

- Make `Exit` in the in-game menu exit Flycast instead of closing the game, if the game was opened directly through the command line.
- Have also an `Exit` button in the Flycast main menu.

I don't really see a use case to go back to the main menu from a game, because the in-game menu has already a `Settings` button, the change should be fine.

**Comment by flyinghead** [comment]
There is an Exit button, not bound by default, that can be used to quickly exit the emulator.

**Comment by j8r** [comment]
But that's not intuitive. It would be so much simpler to have this feature, which is common which is common with other emulators/applications.

And what would be this "button"? Some gamepads have not as many buttons.

I don't see any disadvantage to have this simple button, only one advantage to have a 0 setup exit possibility.

I don't see myself or others having to setup an exit button for each emulator in the library... Hopefully, this is not the case.

**Comment by j8r** [comment]
But that's not intuitive. It would be so much simpler to have this feature, which is common with other emulators/applications.

And what would be this "button"? Some gamepads have not as many buttons.

I don't see any disadvantage to have this simple button, only one advantage to have a 0 setup exit possibility.

I don't see myself or others having to setup an exit button for each emulator in the library... Hopefully, this is not the case.

**Comment by flyinghead** [comment]
Done: the Exit button now exits the emulator if it was started with a game/content in the command line.

**Comment by j8r** [comment]
We can consider this issue closed for me. Maybe one may want to have an Exit button on the main menu, but this change is fine for my case.

Another topic, for https://github.com/flathub/org.flycast.Flycast, I'm not sure if @flathubbot is supposed to submit a PR to bump the hash - can we wait a day if it will do it by itself? I also asked to in an issue to know more about this.

**Comment by flyinghead** [comment]
I didn't know the flatpak update was automated. I'll leave it alone and see what happens.
