### ISSUE TITLE
Cannot display Chinese.

### ISSUE THREAD

**Issue by dreamboyn81** [flyinghead/flycast#225]
Platform / OS / Hardware: 
Android

Github hash: 
flycast-debug-8909368

**_Description of the Issue_**
The Chinese display is garbled, which is really uncomfortable to look at.
Can you add an option to support reading third-party fonts?

**_Screenshots_**
![Screenshot_20210419_174929](https://user-images.githubusercontent.com/15012771/115217612-443cae00-a138-11eb-842e-3fc07fc9b72b.jpg)
![Screenshot_20210420_034342_com flycast emulator](https://user-images.githubusercontent.com/15012771/115294445-2fd5d100-a18b-11eb-9842-c9e67b086cbe.jpg)

**Comment by flyinghead** [comment]
Chinese characters are correctly displayed on Windows and MacOS, by loading system TTF fonts from known locations.

This is currently not implemented on Android and I don't know how feasible it is.

**Comment by dreamboyn81** [comment]
> 通过从已知位置加载系统TTF字体，可以在Windows和MacOS上正确显示汉字。
> 
> 目前尚未在Android上实现此功能，我不知道它的可行性。

Thanks Reply. I look forward to one day that the Android version will also be able to achieve this function😄.

**Comment by flyinghead** [comment]
Implemented in build https://github.com/flyinghead/flycast/commit/92ccd6eb26e71c609ee23ff5c91540a3c5601bd9

**Comment by dreamboyn81** [comment]
> 在build [92ccd6e中](https://github.com/flyinghead/flycast/commit/92ccd6eb26e71c609ee23ff5c91540a3c5601bd9)实现[](https://github.com/flyinghead/flycast/commit/92ccd6eb26e71c609ee23ff5c91540a3c5601bd9)

![Screenshot_20210423_071959_com flycast emulator](https://user-images.githubusercontent.com/15012771/115796480-771ac680-a404-11eb-8efc-08a667fcd85f.jpg)
![Screenshot_20210423_072214_com flycast emulator](https://user-images.githubusercontent.com/15012771/115796606-b34e2700-a404-11eb-8816-2dd9b9dca89a.jpg)
This update is really great, it can display Chinese, thank you.😃
