### ISSUE TITLE
Version 3474901 Android Build Multiple Crashes

### ISSUE THREAD

**Issue by samosaphile** [flyinghead/flycast#228]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Android 11 / StockOS / Pixel 4a.
Github hash: 

Hardware: 
Pixel 4a.
**_Description of the Issue_**
Whenever I switch windows on android, like from Emu to another app, say discord and then back to Emu. Flycast instantly crashes / force closes. You don't even need to switch windows. Just doing the gesture to enable multitasking, where it puts the app / Emu slightly in background but still visible, as soon as you select Emu again to go back into it, the Emu is no longer running the game and just shows game folder directory like you just first booted the Emu or ram of this app was completely wiped. It also does this when device is rotated.
Add a short, concise description of the issue here
Android build unstable due to constant force closing / crashing triggered by whenever multitasking gesture done or app put in background. Changing device orientation from landscape to portrait and vice versa causes similar crashes.
**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by Meowlithius** [comment]
Can confirm on a Pixel 4a 5G **most** likely the emulation threads aren't playing nice with android's app management and when it requests various android specific things like rotation and it doesn't know how to handle it.

Basically the *tiny* but **heavy** pause of rotation causes instability in the applications threads. And memory being changed around in the system when it's out of focus and not the current app. It's trying to emulate in the background with the previously allotted memory that's already been swapped around for other apps and simply crashes from the strange data.

But really all of that's a theory, without a log can't conclude alot. Though I try to get one in a second.

**Comment by flyinghead** [comment]
Should be fixed in build https://github.com/flyinghead/flycast/commit/92ccd6eb26e71c609ee23ff5c91540a3c5601bd9

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen if not.

**Comment by Gamemulatorer** [comment]
@samosaphile your issue is fixed right?

**Comment by samosaphile** [comment]
> @samosaphile your issue is fixed right?

Yes.
