### ISSUE TITLE
RE: Code Veronica X widescreen cheat doesn't work - use regular RECV cheat

### ISSUE THREAD

**Issue by momoids** [flyinghead/flycast#229]
How to use Widescreen Cheats?

**Comment by flyinghead** [comment]
Settings > Video > Widescreen Game Cheats

**Comment by momoids** [comment]
Don't work for me!
![flycast](https://user-images.githubusercontent.com/70231770/115802161-bae5df80-a3b4-11eb-9ad7-c7bf8250329c.jpg)
![interface](https://user-images.githubusercontent.com/70231770/115802178-c6d1a180-a3b4-11eb-83d2-c98439db5d4a.jpg)
![Resident Evil CV](https://user-images.githubusercontent.com/70231770/115802187-ccc78280-a3b4-11eb-9b19-4043e650d4e7.jpg)
RE Code veronica gets stretched!

**Comment by flyinghead** [comment]
It works fine here, at least for the NTSC-US edition. You didn't mention which one you're using.

Also, don't use a CDI but prefer GDI, CHD or CUE formats.

**Comment by momoids** [comment]
![gdi](https://user-images.githubusercontent.com/70231770/115944009-bccda280-a489-11eb-8c9b-d55270675297.jpg)
I think I need to use retroarch for it to work!

**Comment by flyinghead** [comment]
This is Code Veronica X, not the regular Code Veronica. There is no widescreen cheat code for Code Veronica X.
Unfortunately, they use the same game ID so the wrong cheat code is used, hence the stretch.

You have to disable Widescreen Game Cheats for this game.

**Comment by momoids** [comment]
Thank You!

**Comment by bslenul** [comment]
CVX is a hack (only released in JP and called "Kanzenban"), so it makes sense that it uses the same serial, can this really be considered as a bug? :p 

As a workaround however, I've found this online:

> I still don't understand how to convert the adress of codebreaker to a hex code.
>
> But I try this hex code for RECVX or kazenban import from classic RECV version and it's just fabulous :
RESIDENT EVIL CODE VERONICA X
WIDESCREEN HEX PATCH
1ST_READ.BIN or track03.bin
Code:
Find
C8A60200 A245963F 6436148C 6836148C
Replace
C8A60200 7368613F 6436148C 6836148C

And it seems to work:

![image](https://user-images.githubusercontent.com/33353403/116780970-1fbdcb80-aa80-11eb-85db-6d639dbc622f.png)

**Comment by flyinghead** [comment]
I didn't know CVX was a hack. But thanks for the information!

The remaining problem is know to identify it. The only difference is the name of the title: `RESIDENT EVIL CODE VERONICA X` vs. `RESIDENT EVIL CODE VERONICA`. A new special case I guess...

**Comment by Foxlum** [comment]
@flyinghead maybe checksum checking?

**Comment by flyinghead** [comment]
Fixed in the last build

**Comment by keefged4** [comment]
I have found the code for the Kanzeban English translation rom. There is some clipping issues however, I'm still working on it.

Raw Hex :
2C344AB0 - 43F00000 ZOOM
2C344AE4 - 3FB00000 VERTICAL STRETCH

To use this as a cheat code e.g. codebreaker or gameshark input the following:

02C344AB0
43F00000
2C344AE4
3FB00000

For Retroarch:

Address - 36981424, Value 1139802112
Address - 36981476, Value 106849894

Apologies, I'm not too clued up on this so not sure how to translate these for use directly with Flycast Standalone, if anyone can help with this or suggest any improvements, please do so. Just thought I'd post my findings here.

**Comment by keefged4** [comment]
FINAL UPDATE.

After many hours of trying I have found the correct code which matches the hex edit, no clipping as far as I can see, this code directly affects the horizontal axis without any zoom involved, which I reckon the hex edit is doing anyway.

Raw Hex :
2C344AE1 003F6000

To use this as a cheat code e.g. codebreaker or gameshark input the following:

02344AE1
003F6000

For Retroarch:

Address 36981473 - Value 4153344

I'll attach the Retroarch cheat file too.

Enjoy :)
[Resident Evil - Code Veronica X (English)(Disc 1)(Clone GDEMU Item Bug Fix)WIDESCREEN CODE FINAL.txt](https://github.com/flyinghead/flycast/files/10426199/Resident.Evil.-.Code.Veronica.X.English.Disc.1.Clone.GDEMU.Item.Bug.Fix.WIDESCREEN.CODE.FINAL.txt)
