### ISSUE TITLE
Most controllers do not work

### ISSUE THREAD

**Issue by BigheadSMZ** [flyinghead/flycast#23]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
This affects all builds using Windows 10 x64. I tried multiple builds with random dates from random branches.

**_Description of the Issue_**

Most controllers don't work. 8Bitdo in xinput mode fails, official xbox 360 controller fails, and any directinput controller fails. The xbox one controller does work and shows up in the list.

**_Debugging Steps Tested_**

  * Tried several controllers. Only XBO controller works.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)
![image](https://user-images.githubusercontent.com/9309452/67262241-1064c780-f472-11e9-9f52-5e070a13ea17.png)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by mohsinous** [comment]
i had this problem too!! i just change usb port and booom, worked!!

**Comment by flyinghead** [comment]
Flycast uses XInput to manage controllers so DirectInput controllers are not supported. Other than that I don't know why some XInput controllers aren't working. All XInput devices that return some state should appear in the UI.

**Comment by BigheadSMZ** [comment]
To work around this, I decided to bite the bullet and use RetroArch. Maybe "unofficial" Microsoft controllers are doing something different. I thought my xb360 controller was official but it's not. The only two controllers that use XInput that I can test are the 8BitDo SF30 and an XBox 360 controller by some company called "PowerA". Official XBox One controller does work, but it's not the controller that I want to use.

![image](https://user-images.githubusercontent.com/9309452/67634493-22d86a00-f893-11e9-837b-5bd514e73195.png)

**Comment by flyinghead** [comment]
It's possible that these controllers don't work with XInput but do work with DirectInput. Applications can support both XInput and DirectInput at the same time (but Flycast currently doesn't).

Is your test with RetroArch consistent with what you see in Flycast? (I believe RA has separate DirectInput and XInput drivers)

**Comment by BigheadSMZ** [comment]
I've done some pretty extensive testing now, and it seems Flycast is the only program having issues detecting the controllers. RetroArch is working fine with XInput as the joypad driver with both xb360 controllers. DInput works as well as XInput, but for the SF30 Pro I have to put the controller itself in DInput mode to use DInput as a driver. I can use Flycast through RetroArch without having to force the input to DInput.

![image](https://user-images.githubusercontent.com/9309452/67637244-cbe08e00-f8ae-11e9-9cb0-ab2988757a55.png)

I've tested multiple PC games and all correctly detect the xb360 controllers as valid input, including: Fallout IV, Killer is Dead, Bloodstained: RoTN, etc. I've tried other emulators such as Dolphin (which correctly detects them as XInput and allows me to configure buttons for them). I can only assume the problem is somehow on my end if nobody else is having this issue.

**Comment by flyinghead** [comment]
I'll have a look at RA's source to see if they do anything differently regarding XInput. Thanks for your testing and  feedback.

**Comment by barolo** [comment]
On the other hand I have no issues under RA with DualShock v2 whatsoever, but standalone is a mess, controller is detected but buttons are detected as being pressed repeatedly can't map d-pad [ doesn't detect input ] after mapping stick it goes crazy

**Comment by flyinghead** [comment]
What about using SDL for input on windows? That would probably take care of these issues.

Any objection?

**Comment by flyinghead** [comment]
We are now using SDL on Windows and XInput and DirectInput controllers should work fine.

**Comment by flyinghead** [comment]
I believe this is resolved. Re-open if needed.
