### ISSUE TITLE
Alpha texture seems to cancel out each other

### ISSUE THREAD

**Issue by vkedwardli** [flyinghead/flycast#230]
In Gundam, user reports that there is a minor graphic glitch, seems the 2 alpha textures from rifle beam has an unusual gap

![IMAGE 2021-04-25 04:58:29](https://user-images.githubusercontent.com/602245/115972760-e0c0df00-a582-11eb-9f2d-37e7196360d9.jpg)

https://user-images.githubusercontent.com/602245/115972764-e4546600-a582-11eb-967b-92b0a5fbb558.MP4

Normal graphics from arcade:
![image](https://user-images.githubusercontent.com/602245/115972871-a146c280-a583-11eb-9865-10f9019aa4ca.png)
![image](https://user-images.githubusercontent.com/602245/115972989-6ee99500-a584-11eb-84a3-e05d3bdddbdd.png)

The related texture (e5094b1e):
![e5094b1e](https://user-images.githubusercontent.com/602245/115972750-d6064a00-a582-11eb-9299-4f455cbd33c0.png)

This is not happening on my Mac, seems only happen to some Windows user, I am still gathering more hardware information to find out what kind of hardware can reproduce this issue

**Comment by flyinghead** [comment]
I would also like to know the `Transparent Sorting` setting: per-triangle, per-strip or per-pixel. And if it makes any difference to change it.

**Comment by vkedwardli** [comment]
after deleting the emu.cfg and restart from scratch, the glitch is gone 😳
the user cannot provide further insight

**Comment by vkedwardli** [comment]
Confirmed using `per-strip` would cause this glitch, there isn't any issue with `per-triangle`
