### ISSUE TITLE
Controller rumble mapping.

### ISSUE THREAD

**Issue by Foxlum** [flyinghead/flycast#233]
I want to be able to map rumble to compatible controllers, as a phone rumbling ruins the point of rumble if you have a controller that can rumble itself.

**Comment by flyinghead** [comment]
You can set the `Android Virtual Gamepad` port to `None` to disable the phone rumble when using a gamepad.

**Comment by Foxlum** [comment]
@flyinghead what I mean is mapping rumble from the emulated puru puru pack to physical controllers.

**Comment by flyinghead** [comment]
Adding a purupuru module on a controller port will trigger rumble on physical controllers bound to this port (if supported by the OS and controller).

You can now also set the rumble strength for each physical controller and even set it to 0 to disable it completely.
