### ISSUE TITLE
Flycast does not recognize neiher the dpad nor the analog left stick but it DOES  recognize the buttons.

### ISSUE THREAD

**Issue by Matias-Barrios** [flyinghead/flycast#235]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Ubuntu 20.04

Github hash: *** ALL I HAVE TESTED FROM BUILDS

Hardware: I3 - 8GB RAM - Radeon RX570

**_Description of the Issue_**

I have a generic gamepad. It works flawlessly with Steam but Flycast only recognizes the buttons, it does not react at all neither to the DPAD nor the analog left stick **but it does** recognize all the buttons with no issues and they work perfectly in game. ( But i cant move :( )

**_Debugging Steps Tested_**

  * Tried different builds from your builds sections
** SCREENSHOTS:

![image](https://user-images.githubusercontent.com/30472800/117243855-5e4fdf00-ae0e-11eb-83ad-21e6068199ff.png)
![image](https://user-images.githubusercontent.com/30472800/117243873-6871dd80-ae0e-11eb-8604-7364f7142b8d.png)
![image](https://user-images.githubusercontent.com/30472800/117243984-96efb880-ae0e-11eb-873b-4f73a1333b28.png)

Can someone help me?

**Comment by flyinghead** [comment]
It might be a limitation of the evdev driver. Can you try our Flatpak? It uses SDL for input, which is more advanced in this regard.
```
flatpak install -y org.flycast.Flycast
```

You can also compile with SDL support using cmake or with `make USE_SDL=1` (provided SDL dev libs are installed.)

**Comment by Matias-Barrios** [comment]
Thanks. Ill give a try. Specially to build it from source

**Comment by Matias-Barrios** [comment]
I am trying to build but it fails with this error :

```
/home/matias/Projects/flycast/shell/linux/../../core/archive/ZipArchive.h:24:10: fatal error: zip.h: No such file or directory
   24 | #include <zip.h>
   
```
   
Do you know what exactly should I do to get this dependency? I already tried everything from here : https://stackoverflow.com/questions/36374267/how-to-fix-fatal-error-zlib-h-no-such-file-or-directory

**Comment by flyinghead** [comment]
Try libzip-dev

**Comment by Matias-Barrios** [comment]
Thanks so much!! I was able to build it and now my gamepad is recognized entirely. I only have one more question. I want to play CVS 2 through Fightcade with this binary, but for some reason the left analog stick is only recognized in the UI, not in the game. For instance, pressing the DPAD UP and the Analog Axis Y UP have the same effect but ONLY in the UI. In game, the left analog is dead. 
Is it possible to enable some flag while building so they are mapped the same same way as I used SDL to build with support for it?

**Comment by flyinghead** [comment]
It shouldn't be the case: the analog stick only allows scrolling up and down in UI lists. It is distinct from the DPad controls.

You can map your left analog stick to the DPad by mapping `DPad X` and `DPad Y` in the right column (`Analog Axes`) of the mapping dialog.

**Comment by Matias-Barrios** [comment]
Thanks so much. This can be closed I think. I appreciate all the help
