### ISSUE TITLE
[Bug]Super Street Fighter II X for Matching Service (Japan) - Character Menu is really slow

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#239]
Hi Flyinghead, thanks a lot for this standalone flycast as the libretro doesn't even work with the latest AMD 6700/6800/6900 cards and Redream is laggy as hell.

I was getting desperate and thought of the standalone and wow it's perfect :).

Small problem : SSF2X has this old issue that you already fixed on the libretro core : [Bug](https://github.com/libretro/flycast/issues/888) 

Thanks !

**Comment by flyinghead** [comment]
Should be fixed in build 00a74d81c2b29280054a63946be07dab49f6586e
