### ISSUE TITLE
Fast Forward Does not Past 60 FPS

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#24]
| Platform | Branch | Hash | CIDL |
| Windows 10-x64 | master | 4ca5d4f | Downloaded from build site |

when i use FF, it cant past 60 FPS!!!!

![Flycast git_mmu (built Oct 23 2019@18_05_02) 10_25_2019 8_47_50 PM](https://user-images.githubusercontent.com/32609205/67590813-cc432280-f710-11e9-94ae-dcbdb61f0fae.png)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
You need to disable V-Sync to get past your monitor refresh rate.

**Comment by mohsinous** [comment]
where can i find v-sync??

**Comment by flyinghead** [comment]
It depends on your graphics card and it may not be possible on Windows. This is not a flycast option. Check your GPU documentation and utilities.

**Comment by mohsinous** [comment]
thanks man, i found it and it goes up to 95 FPS

**Comment by flyinghead** [comment]
closing as resolved
