### ISSUE TITLE
Textures are dumped in incorrect orientation

### ISSUE THREAD

**Issue by Arctiiq** [flyinghead/flycast#243]
Platform / OS / Hardware: 
Windows 10
AMD Ryzen 3700x CPU, RX 480 GPU

Git Hash: d7fd6658

**_Description of the Issue_**

Whenever textures are dumped, they appear rotated 180 degrees and mirrored

**_Debugging Steps Tested_**

1) Enable texture dumping
2) Go into any game and wait for textures to start appearing (tried it with both Sonic Shuffle and Elemental Gimmick Gear)
3) The textures will appear rotated and mirrored in the file explorer

**_Screenshots_**
You can see the font image is rotated, and when I rotated it back with explorer, it also was mirrored.
![image](https://user-images.githubusercontent.com/3587580/118550969-59066480-b72b-11eb-91d5-ed90f5398a51.png)

**Comment by flyinghead** [comment]
This is a consequence of texture origin being the bottom-left corner in Open GL, instead of the more common top-left.

The problem is: changing it will break all existing texture packs. So I'd rather not do it.
