### ISSUE TITLE
GFX Issue on The King of Fighters - Dream Match 1999

### ISSUE THREAD

**Issue by Gamemulatorer** [flyinghead/flycast#244]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Android/10/Mediatek
Github hash: 9d4711a

Hardware: 

**_Description of the Issue_**
![Screenshot_2021-05-21-18-07-14-017_com flycast emulator](https://user-images.githubusercontent.com/37603562/119121232-c124b580-ba5f-11eb-881d-369210e221db.jpg)
![Screenshot_2021-05-21-18-07-51-943_com flycast emulator](https://user-images.githubusercontent.com/37603562/119121236-c255e280-ba5f-11eb-880e-012b3edc9b57.jpg)

Add a short, concise description of the issue here
Black and white during boot of the game but I can hear the sound tried and tested both OGL and VK backend
**_Debugging Steps Tested_**
Using the default settings this game has a lot gfx Issue on android
  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
This game is perfectly working on Redream
![Screenshot_2021-05-21-18-11-39-085_io recompiled redream](https://user-images.githubusercontent.com/37603562/119121545-211b5c00-ba60-11eb-947c-814d47fe3737.jpg)
![Screenshot_2021-05-21-18-11-46-162_io recompiled redream](https://user-images.githubusercontent.com/37603562/119121554-224c8900-ba60-11eb-959c-a6a2eb4685d0.jpg)

**Comment by flyinghead** [comment]
This game works fine on the two devices I tested: Mali 400 (android 4.4) and Adreno 630 (android 10).

I suspect there is an issue with your GPU or its drivers. Is it specific to this game or does it happen with others?
What's your phone model and GPU?

**Comment by Gamemulatorer** [comment]
My phone is Redmi Note 9 Mediatek Helio G85 Mali G52 MC2 GPU

**Comment by Gamemulatorer** [comment]
I can also experience some minor gfx glitch on MVC2 using flycast but doesn't happen on Redream

**Comment by flyinghead** [comment]
I just tested on a Mali G51 MP4 (Kirin 710) device running Android 10 and no issue either. This is as close as I can get to your configuration. I tested both Open GL and Vulkan.

Is this a new issue? If yes, any idea at which build it started?

**Comment by Gamemulatorer** [comment]
Deleting emu.cfg file solve this issue 🤔
![Screenshot_2021-05-22-00-50-49-971_com flycast emulator](https://user-images.githubusercontent.com/37603562/119173065-4bd5d680-ba99-11eb-9e3f-2aa60cc89b76.jpg)
![Screenshot_2021-05-22-00-50-37-204_com flycast emulator](https://user-images.githubusercontent.com/37603562/119173073-509a8a80-ba99-11eb-8e8a-ea9ef93210b4.jpg)
