### ISSUE TITLE
Bitrise : make logs public

### ISSUE THREAD

**Issue by scribam** [flyinghead/flycast#247]
For some reason, I can't see the logs on Bitrise (e.g. https://app.bitrise.io/build/7aa2e3fd3d0fbfd1#?tab=log). Is there a way to fix this?

![image](https://user-images.githubusercontent.com/25406440/119222248-a6038580-baf3-11eb-98fd-b1982271b2fc.png)

**Comment by flyinghead** [comment]
Not sure if and how this can be done. In the meantime, here are the bitrise logs:
[7aa2e3fd3d0fbfd1.log](https://github.com/flyinghead/flycast/files/6526204/7aa2e3fd3d0fbfd1.log)
[718bf24251005bd4.log](https://github.com/flyinghead/flycast/files/6526205/718bf24251005bd4.log)

**Comment by flyinghead** [comment]
The SDL build step isn't executed although it's in bitrise.yml.
It could be a misconfiguration of bitrise when building pull request. It doesn't seem related to your changes.

**Comment by scribam** [comment]
Looks like there is no way to view the logs unless one have an Bitrise's account linked to the project.
