### ISSUE TITLE
[Regression/Vulkan] Graphical corruption at native res

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#263]
[flycast.log](https://github.com/flyinghead/flycast/files/6566266/flycast.log)
The build from May, 26th exhibits graphical corruption (only at native res).

I'm using AMD 6800 which is really not doing great with Flycast (libretro core crashing).

Standalone was working great with Vulkan/per pixel (other options like per triangle or gl are crashing :( ).

Since this build, native res isn't working as it should.

![IMG_2021-05-30-11-54-10-917](https://user-images.githubusercontent.com/47425204/120100008-c0b2ab80-c13e-11eb-8788-b420230d28d6.jpg)
![IMG_2021-05-30-11-51-30-248](https://user-images.githubusercontent.com/47425204/120100014-c6a88c80-c13e-11eb-9846-14ad735c75e8.jpg)
![IMG_2021-05-30-11-51-06-939](https://user-images.githubusercontent.com/47425204/120100016-c8725000-c13e-11eb-83d3-bcb5c49aa95f.jpg)
[flycast native working.zip](https://github.com/flyinghead/flycast/files/6566008/flycast.native.working.zip)
[flycast native bug.zip](https://github.com/flyinghead/flycast/files/6566009/flycast.native.bug.zip)

**Comment by backgamon** [comment]
The bios render issue happen with upscaling too.

**Comment by flyinghead** [comment]
This commit https://github.com/flyinghead/flycast/commit/c3bc5cfc3b5f143842a463cfc5d8d0bead671be8 may help.

However it seems this graphics card has serious issues with flycast.
If someone with this hardware can help debug these issues, let me know.

**Comment by Immersion95** [comment]
> This commit [c3bc5cf](https://github.com/flyinghead/flycast/commit/c3bc5cfc3b5f143842a463cfc5d8d0bead671be8) may help.
> 
> However it seems this graphics card has serious issues with flycast.
> If someone with this hardware can help debug these issues, let me know.

The bug isn't here anymore.

There are still many problem with the new RDNA2 cards though.

Do you think I can help with that ? I'm not a programmer but I can test anything you'd like.

Should I close this issue or rename it ?

**Comment by MojoJojoDojo** [comment]
I got a corruption issue on flycast but on Linux and with another AMD GPU.
Dunno if it got fixed since I last saw it though.

**Comment by flyinghead** [comment]
Good news!

Can you try to run this utility in the background?
https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
This might give us more logging information.
I'd be interested in logs when flycast crashes (Open GL, Vulkan per-triangle)

**Comment by Immersion95** [comment]
Before trying anything, I updated everything to the latest drivers/software/etc... and everything seems to work great now !
OpenGL or Per Triangle don't crash the emulator now. SFA3 &  KOF99 were also crashing a lot but the bugs are gone now ! I'm closing the issue then.

PS : I'm adding the logs to the RA Flycast core, it is the same bug that is happening on Parallel RDP. I know it's not the place but I didn't have any luck with the issue opened there.
