### ISSUE TITLE
4GB option for "Accumulation Pixel Buffer Size" appears to be broken/bugged with Vulkan.

### ISSUE THREAD

**Issue by FatedCourage** [flyinghead/flycast#268]
When selecting the 4GB option for the Pixel Buffer Size, it seems to break certain graphical aspects of the games I've tried. From the UI to textures that have some form of transparency to them. 2GB, 1GB, and 512MB appear to be working correctly though. I've fiddled with all other settings, but it seems to come down to the 4GB option when selected. I'm also using an RTX 3080...just in case the graphics card matters.

I'll use Grandia 2 as an example.
<img width="1920" alt="RetroArch Screenshot 2021 06 05 - 15 59 40 40" src="https://user-images.githubusercontent.com/67807999/120906889-62903780-c61a-11eb-83d1-385813a4b05c.png">

![RetroArch Screenshot 2021 06 05 - 16 00 31 14](https://user-images.githubusercontent.com/67807999/120906902-7e93d900-c61a-11eb-9c62-586d4a98ac52.png)

**Comment by flyinghead** [comment]
This option is specific to the libretro core and doesn't exist in standalone. You should open an issue on the corresponding github:
https://github.com/libretro/flycast/issues

**Comment by flyinghead** [comment]
I just checked with the latest version of the core on a GTX 1080 and the 4GB option works fine (actual max Vulkan buffer size for this GPU is 4,292,870,144 bytes).

Reopen if this issue persists.
