### ISSUE TITLE
Crash After Maximizing Window

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#27]
| Platform | Branch | Hash | CIDL |
| Windows 10-x64 | master | b9970fc | Downloaded from build site |

when select vulkan as backend, after playing game flycast crashed when maximize window

- [X] Place an X in the box to confirm you have filled in this form

**Comment by mohsinous** [comment]
So lonely here ...

**Comment by flyinghead** [comment]
Vulkan is still a work in progress. Resizing the window or maximizing it can cause a crash. This is a known issue.

**Comment by mohsinous** [comment]
i can confirm the latest build 09f5d25 fix window resizing!!
thank you @flyinghead

**Comment by flyinghead** [comment]
resolved
