### ISSUE TITLE
I want to fix the position of the window

### ISSUE THREAD

**Issue by kyudaindo** [flyinghead/flycast#270]
Platform / OS / Hardware: 
Windows10 home

The position of the window is fixed to the center of the screen in flycast, but it should be able to remember the position even if it is moved to any position.

**Comment by flyinghead** [comment]
The position of the window is now remembered between sessions.

See https://github.com/flyinghead/flycast/commit/da3ed74c4ea6ae2f6c625076c5b4807732753349 on the `net-rollback` branch
