### ISSUE TITLE
NavBar and NotiBar can't drag on android 5 lollipop inside flycast

### ISSUE THREAD

**Issue by Gamemulatorer** [flyinghead/flycast#273]
Platform / OS / Hardware: 
Mobile / Android / Mediatek
Github hash: 
https://github.com/flyinghead/flycast/commit/b3ad0a6

**_Description of the Issue_**

I cannot drag the navigation bar and notification inside flycast this video tell the issue https://www117.zippyshare.com/v/EsIhbQ7a/file.html

**Comment by Gamemulatorer** [comment]
### Phone Specs
Mediatek MT6592
Mali-450 GPU
2gb RAM

**Comment by Gamemulatorer** [comment]
Issue started https://github.com/flyinghead/flycast/commit/c0b57219206e27f297cabcee5f665774e1f8bdaf

**Comment by Gamemulatorer** [comment]
Also on latest debug build the game sometimes run too fast

**Comment by flyinghead** [comment]
https://github.com/flyinghead/flycast/commit/c0b57219206e27f297cabcee5f665774e1f8bdaf exists but there's no build with this hash. Did you compile the app yourself to identify this commit?

I don't see how this commit could break things if you're not using Super Widescreen.
