### ISSUE TITLE
vigilante 8 second offense - several menus going black

### ISSUE THREAD

**Issue by overlordchaos** [flyinghead/flycast#275]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10 x64
Github hash: b3ad0a62

Hardware: 
intel I7 @ 2.93 GHZ
16 gbs ram DDR3
AMD Radeon RX 570x series 8 gbs ram DDR3
**_Description of the Issue_**
when the game boots, the main menu, and options black out. options and animated cursor can be seen just the static backround goes black. usually loads for a second or two then goes away. dumping and enhacing the texture wont fix it. loading levels screens usually have graphics and stuff written on it. as well appears for one or two seconds then goes away. the loading bar does appear as press A to start...

  * Fill in any steps already tried here
  * dumped textures and enhaced it. (upscaled and sharpened/restored) no fix.
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**Comment by flyinghead** [comment]
This game reads from the framebuffer after rendering to make various effects in menus. However Flycast doesn't emulate the framebuffer, or more precisely, never writes to it. So the menu background and effects are invisible.

**Comment by flyinghead** [comment]
There's a new option to fix this issue on the `dev` branch: `Full Framebuffer Emulation`
Enabling it should fix the effects on menus with this game.
