### ISSUE TITLE
[Request] allow for BIOS textures to be dumped/customized

### ISSUE THREAD

**Issue by overlordchaos** [flyinghead/flycast#277]
Platform / OS / Hardware:
Windows 10 x64
Github hash: b3ad0a6

Hardware:
intel I7 @ 2.93 GHZ
16 gbs ram DDR3
AMD Radeon RX 570x series 8 gbs ram DDR3
**_Description of the Issue_**

Add a short, concise description of the issue here
it would be lovely to be able to dump then upscale ALL the BIOS images. if it is an issue that the bios has no game ID, it could be invented a game ID for each bios:
Bios-01 (the japanese version since it was the first released)
Bios-02 (the USA one since was the second one released)
Bios-03 (Europe since was the final one released, this one specially because the logo is on blue, since an organization already was using the same spiral logo in red on australia. so for the PAL/Europe version they needed to change the logo color)
it would be amazing to be able to get the original textures from the bios, upscale them so the emu can load them so when you need to load the bios for any reason, you get an upscaled/HD bios look.

**Comment by overlordchaos** [comment]
why wont fix? cause you dont want to?

**Comment by flyinghead** [comment]
I don't think this is useful and I have a lot of other enhancement requests. But if somebody wants to do it, I'll merge the changes.

**Comment by overlordchaos** [comment]
> I don't think this is useful and I have a lot of other enhancement requests. But if somebody wants to do it, I'll merge the changes.

you are just a little bastard that is butthurt because i stop assisting in the debugging of your emulator because you could not add a single line to a bot in a discord server to ping me when a new build is made... good luck making this emulator the main one to be used if anyone that comes along and offends you, you are going to drop the entire thing cause you got bored of working on it.
