### ISSUE TITLE
Sonic Adventure 2: deformed shadows/layer corruption

### ISSUE THREAD

**Issue by overlordchaos** [flyinghead/flycast#278]
Platform / OS / Hardware:
Windows 10 x64
Github hash: b3ad0a6

Hardware:
intel I7 @ 2.93 GHZ
16 gbs ram DDR3
AMD Radeon RX 570x series 8 gbs ram DDR3

**_Description of the Issue_**
ALL the shadows from Sonic Adventure 2 are corrupted. when using ingame models (for actual gameplay or cutscenes) most of the characters shadows seems in a way corrupted. most of the characters its a big circle bigger than the body with invisible pixelation. in the case of shadow the hedgehog, in the cutscenes that is the case (its known the cutscenes has a different model than the one used on the actual levels, a cutscene ingame extra model we can say) and ingame the shadow of, shadow the hedgehog appears as it should, but like a layer with invisible pixels that covers and blurs the character model. it causes like a heatwave effect (similar to super mario sunshine in delfino plaza heatwaves) over the character model making it look like if it where made of wobbling jello. specially his rocket shoes. not sure if this happens with the game only OR is the enhaced textures i am working. the texture pack i am doing has NO edition on my side, the format and alpha channels are sustained. only upscaled x4 and detail recovered. nothing else. so its not like if i edited the shadows files. my guess its a base problem that in high res its more noticeable.

**_Screenshots_**
cutscene with eggman and damaged shadow (apparently its using the shadow he uses when its on his mech thats why its a big black circle)
![SA2 ex1](https://user-images.githubusercontent.com/18064513/122969622-3b986c00-d363-11eb-929b-9941f6714a2e.png)
this is the shadow of the "cutscene" shadow model. do notice as well his shadow is a big black circle on the floor with pixels on it.
![SA2 ex2](https://user-images.githubusercontent.com/18064513/122969626-3cc99900-d363-11eb-8c99-ef8e193ae292.png)
this is ingame shadow model, do notice on the floor his proper shadow "pierced" by invicible pixels, and that his shadow seems to be a fabric veil covering his model, not a proper shadow caused by light effects. in motion it makes his shoes look like if they where melting off, like wabling jello
![SA2 shadow ex](https://user-images.githubusercontent.com/18064513/122969630-3cc99900-d363-11eb-9cb0-2dd9a35e7300.png)

**Comment by flyinghead** [comment]
Are you using per-pixel transparent sorting? Any difference with per-triangle sorting?
Any difference with Vulkan vs. Open GL?

Please disable custom textures when testing to avoid mixing problems.

**Comment by overlordchaos** [comment]
> Are you using per-pixel transparent sorting? Any difference with per-triangle sorting?
> Any difference with Vulkan vs. Open GL?
> 
> Please disable custom textures when testing to avoid mixing problems.

yeah disabled custom textures. the per pixel transparent sorting is messing original game. per strip the problem goes away.
here is with per pixel original textures on opengl:
![notextripix](https://user-images.githubusercontent.com/18064513/123015182-2d1b7600-d39e-11eb-8464-5ead65ee0da1.png)
and here it is, same example but per-triangle sorting
![perstrip](https://user-images.githubusercontent.com/18064513/123015214-3d335580-d39e-11eb-84bd-4eb3eeaa4ee2.png)
so per pixel breaks sonic adventure 2 shadows

**Comment by flyinghead** [comment]
I have an AMD Radeon RX 550 (Ubuntu 20) and I can't reproduce this issue, per-pixel or not.

Make sure to upgrade your GPU drivers to the latest version. Also you didn't reply about Vulkan.

**Comment by overlordchaos** [comment]
> I have an AMD Radeon RX 550 (Ubuntu 20) and I can't reproduce this issue, per-pixel or not.
> 
> Make sure to upgrade your GPU drivers to the latest version. Also you didn't reply about Vulkan.

i am using windows not ubuntu. maybe its related to the drivers texture optimizations that has embedded into it for all software. did not tested vulkan since i am hardcore playing games to dump the textures and upscale them. i would suggest to try to reproduce on your pc using windows 10 since you have a similar gpu than mine.

**Comment by overlordchaos** [comment]
> I have an AMD Radeon RX 550 (Ubuntu 20) and I can't reproduce this issue, per-pixel or not.
> 
> Make sure to upgrade your GPU drivers to the latest version. Also you didn't reply about Vulkan.

i do a 2 reply to clarify: on opengl the custom textures are showing errors on sonic adventure 2: first error: shadow model from cutscenes, when the camera goes near his face, his retinas goes under his white eyes texture. as well from the ARK space station, when the cutscenes are on, we can see trough the window the earth (since we are far away but still close enough to stablish orbit) on the cutscenes the planet goes under the blue layer that gives the atmoshphere a "blue glow" appereance. when the camera goes away, almost out of focus the textures (that are in chunks apparently) they all appear. maybe a camera bug/or fix is needed. in the case of shadow that the textures are displayed like when the camera is far away, and for the cutscene earth as well, to "tell" the camera code its far away so the textures are displayed properly.
