### ISSUE TITLE
[CHEATS] Questions regarding manually creating and adding "cht", also infos about cheats discs (CodeBreaker / GameShark)

### ISSUE THREAD

**Issue by cinnamonmatexfce** [flyinghead/flycast#279]
**TL;TR**: cheats on Code Veronica (USA) works only via GameShark [CDI].

All screenshots and logs are attached: these files are all named accordingly relatively by their corresponding issue.

- dc_boot.bin
```
bytes	=	2097152
sha1	=	8951D1BB219AB2FF8583033D2119C899CC81F18C
```
- dc_flash.bin
```
bytes	=	131072
sha1	=	94D44D7F9529EC1642BA3771ED3C5F756D5BC872
```
- CodeBreaker [CDI] (hacked: NeuroAcid's loader injected)
```
bytes	=	809338564
sha1	=	87A196EA2BB5F01B5A031CB9B26E67A37CE55B5F
```
- CodeBreaker [CDI] (no dummy)
```
bytes	=	2570477
sha1	=	C4D2CBC93F0DA8F49563D7322F44AF35B4E4E8B4
```
- CodeBreaker [CDI] (hacked? / dumped from original?)
```
bytes	=	735588605 
sha1	=	2580EAEC3D90C4E13FDF1B60E70C7F92D026C661
```
- Gameshark CDX Version 3.3 [CDI] (dumped from original?)
```
bytes	=	2829503 
sha1	=	CCFDC179DDC86ECCACB65449785A4C4C9F0B796C
```
- Resident Evil - Code Veronica (USA) [GDI]
```
Resident Evil - Code Veronica v1.000 (2000)(Capcom)(US)(Disc 1 of 2)[!].gdi
	bytes	=	87
	sha1	=	9D50B816D3F69AD192F5986AB487769965C2E082
track01.bin
	bytes	=	705600
	sha1	=	4AC87551F8476A889E127705E22E0C51E07D1817
track02.raw
	bytes	=	1237152
	sha1	=	B0D28980A64765C022B4B3E47244AAD32A345270
track03.bin
	bytes	=	1185760800
	sha1	=	662126F7BAEF6BAFC0B7B4FD4A1AA59C16634A51
```

- OS / HW
```
Windows 10 Pro
2004
19041.985
Intel i5-7500
```

- build
```
master/b3ad0a6/Windows x64
https://flycast-builds.s3.amazonaws.com/win/heads/master-b3ad0a62c15825da0ba5d62a7e5f08b814eb5dd1/flycast.zip
```

- Settings
```
Language: Default
Broadcast: Default
Region: Default
Cable: TV Composite
HLE BIOS: no
Log to file: yes
```

- emu.cfg
```
[audio]
backend = auto
disable = 0

[config]
Debug.SerialConsoleEnabled = no
Debug.SerialPTY = no
Dreamcast.AutoLoadState = no
Dreamcast.AutoSaveState = no
Dreamcast.Broadcast = 4
Dreamcast.Cable = 3
Dreamcast.ContentPath = C:\my\custom\path\to\roms\sega\dreamcast\games\
Dreamcast.ForceWindowsCE = no
Dreamcast.FullMMU = no
Dreamcast.HideLegacyNaomiRoms = yes
Dreamcast.Language = 6
Dreamcast.Region = 3
Dreamcast.SavestateSlot = 0
Dynarec.Enabled = yes
Dynarec.idleskip = yes
Dynarec.safe-mode = no
UseReios = no
aica.AutoLatency = no
aica.BufferSize = 1676
aica.DSPEnabled = yes
aica.NoSound = no
pvr.AutoSkipFrame = 0
pvr.MaxThreads = 3
pvr.rend = 0
rend.CrossHairColor1 = 0
rend.CrossHairColor2 = 0
rend.CrossHairColor3 = 0
rend.CrossHairColor4 = 0
rend.CustomTextures = no
rend.DelayFrameSwapping = yes
rend.DumpTextures = no
rend.ExtraDepthScale = 1.000000
rend.FloatVMUs = yes
rend.Fog = yes
rend.MaxFilteredTextureSize = 1024
rend.ModifierVolumes = yes
rend.PerStripSorting = no
rend.RenderToTextureBuffer = yes
rend.Resolution = 960
rend.Rotate90 = no
rend.ScreenStretching = 100
rend.ShowFPS = yes
rend.SuperWideScreen = no
rend.TextureUpscale = 3
rend.TranslucentPolygonDepthMask = no
rend.UseMipmaps = yes
rend.WideScreen = no
rend.WidescreenGameHacks = no
rend.vsync = yes
ta.skip = 0

[input]
MouseSensitivity = 100
VirtualGamepadVibration = 20
device1 = 0
device1.1 = 1
device1.2 = 1
device2 = 10
device2.1 = 10
device2.2 = 10
device3 = 10
device3.1 = 10
device3.2 = 10
device4 = 10
device4.1 = 10
device4.2 = 10
maple_sdl_keyboard = 0
maple_sdl_mouse = 0
maple_sdl_mouse_\\?\foo = 1

[log]
LogToFile = yes

[network]
ActAsServer = no
DNS = foo
EmulateBBA = no
Enable = no
server = 

[validate]
OpenGlChecks = no

[window]
fullscreen = no
height = 960
maximized = no
width = 1280
```
____________________________________________________________________________________________________________________________________

_CODEBREAKER_
Using any of the CodeBreaker images causes Flycast to crash (no response).
Only difference is that NeuroAcid's version loads fine and recognize swapped disc, but then leads however to Flycast crashing (no response) once you press STAR to boot the loaded disk.
![flycast CodeBreaker NO RESPONSE](https://user-images.githubusercontent.com/65762930/123245063-c48ae100-d4e4-11eb-9c7b-3b54781fcade.png)
[flycast CodeBreaker NO RESPONSE.log](https://github.com/flyinghead/flycast/files/6708285/flycast.CodeBreaker.NO.RESPONSE.log)
![flycast CodeBreaker (NeuroAcid) booting OK](https://user-images.githubusercontent.com/65762930/123245122-d1a7d000-d4e4-11eb-835e-f2aaecd2fa38.png)
![flycast CodeBreaker (NeuroAcid) loading game NO RESPONSE](https://user-images.githubusercontent.com/65762930/123245164-da000b00-d4e4-11eb-86dd-6743be37a916.png)
[flycast CodeBreaker (NeuroAcid) loading game NO RESPONSE.log](https://github.com/flyinghead/flycast/files/6708286/flycast.CodeBreaker.NeuroAcid.loading.game.NO.RESPONSE.log)

_GAMESHARK_
With GameShark everything's fine (also VMU saving works good) and game is loaded with cheats enabled.
Also: creating savestate (boot GameShark, load cheats, swap disk, start game) and then loading when direct booting games, keeps cheats loaded. Cool! ;)
![flycast GameShark WORKING 001](https://user-images.githubusercontent.com/65762930/123245269-f4d27f80-d4e4-11eb-93ee-340d48b301df.png)
![flycast GameShark WORKING 002](https://user-images.githubusercontent.com/65762930/123245284-f8660680-d4e4-11eb-909f-92d7e180ade8.png)
[flycast GameShark WORKING.log](https://github.com/flyinghead/flycast/files/6708297/flycast.GameShark.WORKING.log)

_MANUAL CHEATS_
How one should handle manually adding cheats? Is there a guide on how to convert CodeBreaker (or GameShark) codes into `cht` readable by Flycast?

**Comment by overlordchaos** [comment]
> **TL;TR**: cheats on Code Veronica (USA) works only via GameShark [CDI].
> 
> All screenshots and logs are attached: these files are all named accordingly relatively by their corresponding issue.
> 
> * dc_boot.bin
> 
> ```
> bytes	=	2097152
> sha1	=	8951D1BB219AB2FF8583033D2119C899CC81F18C
> ```
> 
> * dc_flash.bin
> 
> ```
> bytes	=	131072
> sha1	=	94D44D7F9529EC1642BA3771ED3C5F756D5BC872
> ```
> 
> * CodeBreaker [CDI] (hacked: NeuroAcid's loader injected)
> 
> ```
> bytes	=	809338564
> sha1	=	87A196EA2BB5F01B5A031CB9B26E67A37CE55B5F
> ```
> 
> * CodeBreaker [CDI] (no dummy)
> 
> ```
> bytes	=	2570477
> sha1	=	C4D2CBC93F0DA8F49563D7322F44AF35B4E4E8B4
> ```
> 
> * CodeBreaker [CDI] (hacked? / dumped from original?)
> 
> ```
> bytes	=	735588605 
> sha1	=	2580EAEC3D90C4E13FDF1B60E70C7F92D026C661
> ```
> 
> * Gameshark CDX Version 3.3 [CDI] (dumped from original?)
> 
> ```
> bytes	=	2829503 
> sha1	=	CCFDC179DDC86ECCACB65449785A4C4C9F0B796C
> ```
> 
> * Resident Evil - Code Veronica (USA) [GDI]
> 
> ```
> Resident Evil - Code Veronica v1.000 (2000)(Capcom)(US)(Disc 1 of 2)[!].gdi
> 	bytes	=	87
> 	sha1	=	9D50B816D3F69AD192F5986AB487769965C2E082
> track01.bin
> 	bytes	=	705600
> 	sha1	=	4AC87551F8476A889E127705E22E0C51E07D1817
> track02.raw
> 	bytes	=	1237152
> 	sha1	=	B0D28980A64765C022B4B3E47244AAD32A345270
> track03.bin
> 	bytes	=	1185760800
> 	sha1	=	662126F7BAEF6BAFC0B7B4FD4A1AA59C16634A51
> ```
> 
> * OS / HW
> 
> ```
> Windows 10 Pro
> 2004
> 19041.985
> Intel i5-7500
> ```
> 
> * build
> 
> ```
> master/b3ad0a6/Windows x64
> https://flycast-builds.s3.amazonaws.com/win/heads/master-b3ad0a62c15825da0ba5d62a7e5f08b814eb5dd1/flycast.zip
> ```
> 
> * Settings
> 
> ```
> Language: Default
> Broadcast: Default
> Region: Default
> Cable: TV Composite
> HLE BIOS: no
> Log to file: yes
> ```
> 
> * emu.cfg
> 
> ```
> [audio]
> backend = auto
> disable = 0
> 
> [config]
> Debug.SerialConsoleEnabled = no
> Debug.SerialPTY = no
> Dreamcast.AutoLoadState = no
> Dreamcast.AutoSaveState = no
> Dreamcast.Broadcast = 4
> Dreamcast.Cable = 3
> Dreamcast.ContentPath = C:\my\custom\path\to\roms\sega\dreamcast\games\
> Dreamcast.ForceWindowsCE = no
> Dreamcast.FullMMU = no
> Dreamcast.HideLegacyNaomiRoms = yes
> Dreamcast.Language = 6
> Dreamcast.Region = 3
> Dreamcast.SavestateSlot = 0
> Dynarec.Enabled = yes
> Dynarec.idleskip = yes
> Dynarec.safe-mode = no
> UseReios = no
> aica.AutoLatency = no
> aica.BufferSize = 1676
> aica.DSPEnabled = yes
> aica.NoSound = no
> pvr.AutoSkipFrame = 0
> pvr.MaxThreads = 3
> pvr.rend = 0
> rend.CrossHairColor1 = 0
> rend.CrossHairColor2 = 0
> rend.CrossHairColor3 = 0
> rend.CrossHairColor4 = 0
> rend.CustomTextures = no
> rend.DelayFrameSwapping = yes
> rend.DumpTextures = no
> rend.ExtraDepthScale = 1.000000
> rend.FloatVMUs = yes
> rend.Fog = yes
> rend.MaxFilteredTextureSize = 1024
> rend.ModifierVolumes = yes
> rend.PerStripSorting = no
> rend.RenderToTextureBuffer = yes
> rend.Resolution = 960
> rend.Rotate90 = no
> rend.ScreenStretching = 100
> rend.ShowFPS = yes
> rend.SuperWideScreen = no
> rend.TextureUpscale = 3
> rend.TranslucentPolygonDepthMask = no
> rend.UseMipmaps = yes
> rend.WideScreen = no
> rend.WidescreenGameHacks = no
> rend.vsync = yes
> ta.skip = 0
> 
> [input]
> MouseSensitivity = 100
> VirtualGamepadVibration = 20
> device1 = 0
> device1.1 = 1
> device1.2 = 1
> device2 = 10
> device2.1 = 10
> device2.2 = 10
> device3 = 10
> device3.1 = 10
> device3.2 = 10
> device4 = 10
> device4.1 = 10
> device4.2 = 10
> maple_sdl_keyboard = 0
> maple_sdl_mouse = 0
> maple_sdl_mouse_\\?\foo = 1
> 
> [log]
> LogToFile = yes
> 
> [network]
> ActAsServer = no
> DNS = foo
> EmulateBBA = no
> Enable = no
> server = 
> 
> [validate]
> OpenGlChecks = no
> 
> [window]
> fullscreen = no
> height = 960
> maximized = no
> width = 1280
> ```
> 
> _CODEBREAKER_
> Using any of the CodeBreaker images causes Flycast to crash (no response).
> Only difference is that NeuroAcid's version loads fine and recognize swapped disc, but then leads however to Flycast crashing (no response) once you press STAR to boot the loaded disk.
> ![flycast CodeBreaker NO RESPONSE](https://user-images.githubusercontent.com/65762930/123245063-c48ae100-d4e4-11eb-9c7b-3b54781fcade.png)
> [flycast CodeBreaker NO RESPONSE.log](https://github.com/flyinghead/flycast/files/6708285/flycast.CodeBreaker.NO.RESPONSE.log)
> ![flycast CodeBreaker (NeuroAcid) booting OK](https://user-images.githubusercontent.com/65762930/123245122-d1a7d000-d4e4-11eb-835e-f2aaecd2fa38.png)
> ![flycast CodeBreaker (NeuroAcid) loading game NO RESPONSE](https://user-images.githubusercontent.com/65762930/123245164-da000b00-d4e4-11eb-86dd-6743be37a916.png)
> [flycast CodeBreaker (NeuroAcid) loading game NO RESPONSE.log](https://github.com/flyinghead/flycast/files/6708286/flycast.CodeBreaker.NeuroAcid.loading.game.NO.RESPONSE.log)
> 
> _GAMESHARK_
> With GameShark everything's fine (also VMU saving works good) and game is loaded with cheats enabled.
> Also: creating savestate (boot GameShark, load cheats, swap disk, start game) and then loading when direct booting games, keeps cheats loaded. Cool! ;)
> ![flycast GameShark WORKING 001](https://user-images.githubusercontent.com/65762930/123245269-f4d27f80-d4e4-11eb-93ee-340d48b301df.png)
> ![flycast GameShark WORKING 002](https://user-images.githubusercontent.com/65762930/123245284-f8660680-d4e4-11eb-909f-92d7e180ade8.png)
> [flycast GameShark WORKING.log](https://github.com/flyinghead/flycast/files/6708297/flycast.GameShark.WORKING.log)
> 
> _MANUAL CHEATS_
> How one should handle manually adding cheats? Is there a guide on how to convert CodeBreaker (or GameShark) codes into `cht` readable by Flycast?

you dont need a boot loader or a program to inject codes. the codes can be directly input into the game code. you just need to load the game then manually add the codes in the cheat list.
the boot loader was to overcome DC real console hardware protections. in an emulator that is not an issue.

**Comment by cinnamonmatexfce** [comment]
@overlordchaos  
> you dont need a boot loader or a program to inject codes. the codes can be directly input into the game code. you just need to load the game then manually add the codes in the cheat list.
> the boot loader was to overcome DC real console hardware protections. in an emulator that is not an issue.

Yup, I know.
<br />
> if you want cheats for a game look them on internet. for example:
> sonic adventure 2 pal DC gs codes or codebreaker codes. its important you choose the correct region of the game version you have since the codes are usually totally different for the NTSC version than then PAL version. even the JP versions the codes are different. 

Yup, I know.
No problem looking for cheats codes on the interenet (GameShark and/or CodeBreaker).
<br />
>then copy and paste the codes into the code list. 

What is this "code list"? Where can I find it?
I have to simply paste 'em as they are into a `file.cht`?
<br />
>with the emu menu with the game loaded you can acess the cheat list to add/remove codes.

If I open Flycast _menu_ I see no cheats list: it's empty.
Also, there are no cheats in `cht` format available for Code Veronica, see [here](https://github.com/libretro/libretro-database/blob/master/cht/Sega%20-%20Dreamcast/Resident%20Evil-Code%20Veronica.cht)

**Comment by flyinghead** [comment]
Here are some information about the `.cht` file format:
```
cheat0_address = "122176"          Address in RAM (decimal)
cheat0_address_bit_position = "0"  Ignored
cheat0_big_endian = "false"        Fixed to false
cheat0_cheat_type = "1"            Fixed to 1
cheat0_code = ""                   Ignored
cheat0_desc = "Description of the cheat"
cheat0_enable = "false"            Set to true to enable the cheat by default, or false to manually enable the cheat in the UI
cheat0_handler = "1"               Fixed to 1
cheat0_memory_search_size = "4"    Size of the memory access: 3 for 8 bits, 4 for 16 bits, 5 for 32 bits
cheat0_rumble_port = "0"           Ignored
cheat0_rumble_primary_duration = "0" Ignored
cheat0_rumble_primary_strength = "0" Ignored
cheat0_rumble_secondary_duration = "0" Ignored
cheat0_rumble_secondary_strength = "0" Ignored
cheat0_rumble_type = "0"           Ignored
cheat0_rumble_value = "0"          Ignored
cheat0_value = "9"                 Value to set at the given address
cheat0_repeat_count = "1"          How many memory accesses
cheat0_repeat_add_to_value = "0"   Delta to add to value between each access
cheat0_repeat_add_to_address = "0" Delta to add to address between each access
```

Say you have a typical GameShark code such as `00123456 00000080`. This code says "set 8-bit value 80h at address 123456h". This would be converted to:
```
cheat0_address = "1193046"
cheat0_big_endian = "false"
cheat0_cheat_type = "1"
cheat0_desc = "Infinite Life or whatever"
cheat0_enable = "false"
cheat0_handler = "1"
cheat0_memory_search_size = "3"
cheat0_value = "128"
cheat0_repeat_count = "1"
cheat0_repeat_add_to_value = "0"
cheat0_repeat_add_to_address = "0"
```

**Comment by overlordchaos** [comment]
> Here is some information about the `.cht` file format:
> 
> ```
> cheat0_address = "122176"          Address in RAM (decimal)
> cheat0_address_bit_position = "0"  Ignored
> cheat0_big_endian = "false"        Fixed to false
> cheat0_cheat_type = "1"            Fixed to 1
> cheat0_code = ""                   Ignored
> cheat0_desc = "Description of the cheat"
> cheat0_enable = "false"            Set to true to enable the cheat by default, or false to manually enable the cheat in the UI
> cheat0_handler = "1"               Fixed to 1
> cheat0_memory_search_size = "4"    Size of the memory access: 3 for 8 bits, 4 for 16 bits, 5 for 32 bits
> cheat0_rumble_port = "0"           Ignored
> cheat0_rumble_primary_duration = "0" Ignored
> cheat0_rumble_primary_strength = "0" Ignored
> cheat0_rumble_secondary_duration = "0" Ignored
> cheat0_rumble_secondary_strength = "0" Ignored
> cheat0_rumble_type = "0"           Ignored
> cheat0_rumble_value = "0"          Ignored
> cheat0_value = "9"                 Value to set at the given address
> cheat0_repeat_count = "1"          How many memory accesses
> cheat0_repeat_add_to_value = "0"   Delta to add to value between each access
> cheat0_repeat_add_to_address = "0" Delta to add to address between each access
> ```
> 
> Say you have a typical GameShark code such as `00123456 00000080`. This code says "set 8-bit value 80h at address 123456h". This would be converted to:
> 
> ```
> cheat0_address = "1193046"
> cheat0_big_endian = "false"
> cheat0_cheat_type = "1"
> cheat0_desc = "Infinite Life or whatever"
> cheat0_enable = "false"
> cheat0_handler = "1"
> cheat0_memory_search_size = "3"
> cheat0_value = "128"
> cheat0_repeat_count = "1"
> cheat0_repeat_add_to_value = "0"
> cheat0_repeat_add_to_address = "0"
> ```

what about if you make a tiny window that generates all this data in the .cht file? so we only need to add the code/codes, a name and tick/untick to enable/disable? this is basic on most emulators btw.

**Comment by cinnamonmatexfce** [comment]
@flyinghead many thanks taking your time explaining to us how cheat engine work.

**Comment by antipirgos** [comment]
[Head_Hunter_dreamcast.txt](https://github.com/user-attachments/files/24756761/Head_Hunter_dreamcast.txt)
I can't add cheats for Headhunter flycast android emulator 
version wrong format error
1500 Skill Points
DE46798A
00641B83
FE4657FE
BCA9A05F

**Comment by flyinghead** [comment]
@antipirgos This cheat is encrypted by a hardware device with a proprietary encryption algorithm (GameShark v2+). It is not supported.
When a cheat needs a master code like this one, it usually means it's not supported.
