### ISSUE TITLE
DeadZone and Game Name

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#28]
please ...

1. add an option to flycast that dead zone of analog stick can be adjusted.
![Durazno 10_30_2019 7_43_38 PM](https://user-images.githubusercontent.com/32609205/67876805-bb017800-fb4d-11e9-8304-54d36c77be93.png)

2. add game name to the window instead of flycast with build number.
![Flycast git_mmu (built Oct 27 2019@11_17_20) 10_30_2019 7_42_47 PM](https://user-images.githubusercontent.com/32609205/67876972-06b42180-fb4e-11e9-8235-5fec9c4ad477.png)

3. play games when we are in BIOS (when run bios load an iso and select play to start the game like real dreamcast).
![Flycast git_mmu (built Oct 27 2019@11_17_20) 10_30_2019 7_42_47 PM](https://user-images.githubusercontent.com/32609205/67877280-87731d80-fb4e-11e9-91e0-710b72ff065b.png)

4. show real game name in game list instead of file name.
![Flycast git_mmu (built Oct 27 2019@11_17_20) 10_30_2019 7_54_33 PM](https://user-images.githubusercontent.com/32609205/67877770-7545af00-fb4f-11e9-98a5-f9588530cdcc.png)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by mohsinous** [comment]
is there any new news @flyinghead !?

**Comment by flyinghead** [comment]
I just realized that there is a 10% deadzone applied by default on analog axes.

**Comment by mohsinous** [comment]
of course, but can add a menu for adjusting the dead zone?

**Comment by mohsinous** [comment]
and thanks for adding inser disk to the menu!!

**Comment by flyinghead** [comment]
There's a dead zone option but it's not exposed in the UI.

You can set it in the `.cfg` mapping file of the controller:
```
[emulator]
dead_zone = 10
```

The default is 10%. Valid values range from 0 to 100%.

**Comment by psennermann** [comment]
> There's a dead zone option but it's not exposed in the UI.
> 
> You can set it in the `.cfg` mapping file of the controller:
> 
> ```
> [emulator]
> dead_zone = 10
> ```
> 
> The default is 10%. Valid values range from 0 to 100%.

It doesn't work, at leat with my Xbox one S controller (X-input problem?)...even setting 50% nothing changes and the left analog stick still has almost 0% dead zone

**Comment by corvusd** [comment]
Same here with a Xbox Wired USB gamepad.

**Comment by legendarysnake0** [comment]
a deadzone would be nice, i keep going to the left on Walt Disney World Quest: Magical Racing Tour

**Comment by PrFaL9** [comment]
Had the same issue with an xinput controller. I found flyinghead's solution to work but not directly in the emu.cfg. You start the game, go to menu > settings > controls > map menu. Before making any changes, click 'Create Game Config.' This is confusing, but you have to do this before changing controls. Then pick a random key like 'D-Pad Up' and change it. Then map it back to 'D-Pad Up' again. Then select 'Done' and 'Done' and 'Resume' gameplay. Minimize the game window and look at the Flycast directory to see if a new folder named 'mappings' has been created. Inside it, you'll get something like 'SDL-XBox_One_Controller*Game-Unique-ID*.cfg.' This file will have the deadzone setting. This works 100% for me.

**Comment by flyinghead** [comment]
Game name is now displayed in the window title (`dev` branch).
