### ISSUE TITLE
32M RAM is required to run the game

### ISSUE THREAD

**Issue by android-1995** [flyinghead/flycast#280]
Platform / OS / Hardware: android

Github hash: d6e1554

Hardware: 

**_Description of the Issue_**

32M RAM is required to run the game

sorry, the game file is too big to upload

**_Screenshots_**

![Screenshot_2021-06-25-16-03-57-421_com flycast em](https://user-images.githubusercontent.com/35674533/123391868-0728e800-d5cf-11eb-916f-9c808dd8c69e.jpg)

**Comment by overlordchaos** [comment]
how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?

**Comment by android-1995** [comment]
> how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?

My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html

**Comment by overlordchaos** [comment]
> > how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?
> 
> My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html

are you SURE you got 12 GBS of RAM nor storage? yeah i read the description and clarifies this game requires a hack to use 32 mbs of RAM on the console. i am not sure this can be implemented into a emulator since i am not sure how many games needs hardware hacks to run.

**Comment by android-1995** [comment]
> > > how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?
> > 
> > 
> > My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html
> 
> are you SURE you got 12 GBS of RAM nor storage? yeah i read the description and clarifies this game requires a hack to use 32 mbs of RAM on the console. i am not sure this can be implemented into a emulator since i am not sure how many games needs hardware hacks to run.

my mobile phone running memory size is 12GB, but I think "32M" is worth the memory allocated by the emulator, not the RAM of the mobile phone.But I did not find where the emulator sets the memory size

**Comment by overlordchaos** [comment]
> > > > how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?
> > > 
> > > 
> > > My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html
> > 
> > 
> > are you SURE you got 12 GBS of RAM nor storage? yeah i read the description and clarifies this game requires a hack to use 32 mbs of RAM on the console. i am not sure this can be implemented into a emulator since i am not sure how many games needs hardware hacks to run.
> 
> my mobile phone running memory size is 12GB, but I think "32M" is worth the memory allocated by the emulator, not the RAM of the mobile phone.But I did not find where the emulator sets the memory size

upt o my understanding, you cannot change the ram settings, since the console did not had 32 mbs of ram to use. its a hardware hack that unlocks the extra ram. there for the emulator does not have that setting on since its only used on custom games not retail games.

its like try to change the ram on a emulated ps1 from 2 mbs to 2 gbs... the emulator or game would crash on the single attempt to boot.

**Comment by android-1995** [comment]
> > > > > how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?
> > > > 
> > > > 
> > > > My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html
> > > 
> > > 
> > > are you SURE you got 12 GBS of RAM nor storage? yeah i read the description and clarifies this game requires a hack to use 32 mbs of RAM on the console. i am not sure this can be implemented into a emulator since i am not sure how many games needs hardware hacks to run.
> > 
> > 
> > my mobile phone running memory size is 12GB, but I think "32M" is worth the memory allocated by the emulator, not the RAM of the mobile phone.But I did not find where the emulator sets the memory size
> 
> upt o my understanding, you cannot change the ram settings, since the console did not had 32 mbs of ram to use. its a hardware hack that unlocks the extra ram. there for the emulator does not have that setting on since its only used on custom games not retail games.
> 
> its like try to change the ram on a emulated ps1 from 2 mbs to 2 gbs... the emulator or game would crash on the single attempt to boot.

I don't know, it might be better to provide several options, such as 8MB, 32MB. [Sega Saturn Simulator](https://play.google.com/store/apps/details?id=org.devmiyax.yabasanshioro2&hl=en&gl=US) has similar options

**Comment by overlordchaos** [comment]
> > > > > > how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?
> > > > > 
> > > > > 
> > > > > My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html
> > > > 
> > > > 
> > > > are you SURE you got 12 GBS of RAM nor storage? yeah i read the description and clarifies this game requires a hack to use 32 mbs of RAM on the console. i am not sure this can be implemented into a emulator since i am not sure how many games needs hardware hacks to run.
> > > 
> > > 
> > > my mobile phone running memory size is 12GB, but I think "32M" is worth the memory allocated by the emulator, not the RAM of the mobile phone.But I did not find where the emulator sets the memory size
> > 
> > 
> > upt o my understanding, you cannot change the ram settings, since the console did not had 32 mbs of ram to use. its a hardware hack that unlocks the extra ram. there for the emulator does not have that setting on since its only used on custom games not retail games.
> > its like try to change the ram on a emulated ps1 from 2 mbs to 2 gbs... the emulator or game would crash on the single attempt to boot.
> 
> I don't know, it might be better to provide several options, such as 8MB, 32MB. [Sega Saturn Simulator](https://play.google.com/store/apps/details?id=org.devmiyax.yabasanshioro2&hl=en&gl=US) has similar options

it can be added as a feature, but its not a bug/error on the emulator side. btw the saturn is pretty much a prototype of the dreamcast. and the saturn had a slot to add a extra RAM cartridge for selected games. like the nintendo 64 and the expansion pak. the dreamcast did not had that, there for truly making it a hardware hack to be able to push extra ram from the 22 years old hardware. but sure i like the idea to tweak the console emulated hardware.

**Comment by android-1995** [comment]
> > > > > > > how much ram does your phone/tablet has? can you load any other game? this is the only one with this issue? is a custom game or official release?
> > > > > > 
> > > > > > 
> > > > > > My phone has 12GB RAM, other games can run normally, this game is a custom game。game modified by Chinese players. This is the link:http://bbs.chinaemu.org/read-htm-tid-128766-fpage-5.html
> > > > > 
> > > > > 
> > > > > are you SURE you got 12 GBS of RAM nor storage? yeah i read the description and clarifies this game requires a hack to use 32 mbs of RAM on the console. i am not sure this can be implemented into a emulator since i am not sure how many games needs hardware hacks to run.
> > > > 
> > > > 
> > > > my mobile phone running memory size is 12GB, but I think "32M" is worth the memory allocated by the emulator, not the RAM of the mobile phone.But I did not find where the emulator sets the memory size
> > > 
> > > 
> > > upt o my understanding, you cannot change the ram settings, since the console did not had 32 mbs of ram to use. its a hardware hack that unlocks the extra ram. there for the emulator does not have that setting on since its only used on custom games not retail games.
> > > its like try to change the ram on a emulated ps1 from 2 mbs to 2 gbs... the emulator or game would crash on the single attempt to boot.
> > 
> > 
> > I don't know, it might be better to provide several options, such as 8MB, 32MB. [Sega Saturn Simulator](https://play.google.com/store/apps/details?id=org.devmiyax.yabasanshioro2&hl=en&gl=US) has similar options
> 
> it can be added as a feature, but its not a bug/error on the emulator side. btw the saturn is pretty much a prototype of the dreamcast. and the saturn had a slot to add a extra RAM cartridge for selected games. like the nintendo 64 and the expansion pak. the dreamcast did not had that, there for truly making it a hardware hack to be able to push extra ram from the 22 years old hardware. but sure i like the idea to tweak the console emulated hardware.

Thanks and i agree with you

**Comment by flyinghead** [comment]
From what I understand, this is an Atomiswave to Dreamcast port of King of Fighters XI that was posted on, dreamcast-talk.com. Since Atomiswave only has 16MB of RAM, why would a port to Dreamcast require 32MB to run?

**Comment by android-1995** [comment]
> From what I understand, this is an Atomiswave to Dreamcast port of King of Fighters XI that was posted on, dreamcast-talk.com. Since Atomiswave only has 16MB of RAM, why would a port to Dreamcast require 32MB to run?

This stumps me, I only found this 32M game file that fixes random crashes

**Comment by flyinghead** [comment]
Flycast has native support for Atomiswave games. I suggest you use the original Atomiswave game (`kofxi.zip`) instead of this port.

**Comment by android-1995** [comment]
> Flycast has native support for Atomiswave games. I suggest you use the original Atomiswave game (`kofxi.zip`) instead of this port.

ok. thanks
