### ISSUE TITLE
GD-ROM stuck on reset?

### ISSUE THREAD

**Issue by vkedwardli** [flyinghead/flycast#281]
Platform / OS / Hardware: Windows & macOS

Github hash: b3ad0a62 

**_Description of the Issue_**

The GDROM seems to be stuck after reset?

**_Debugging Steps Tested_**

Video demonstration: (video is captured on Flycast-gdxsv, but I just checked it is also happening on the original Flycast b3ad0a62)
https://youtu.be/w16fCFZANh4

- Load the game
- Once it is loaded, Exit immediately
- Load the game again
- The GDROM is in limbo
- Ejecting / Reinserting any GDROM cannot fix, the BIOS will report "Please insert Game Disc"

**_Logs Gathered_**

Normal loading: [nomal_full.txt](https://github.com/flyinghead/flycast/files/6719125/nomal_full.txt)
```
hw/gdrom/gdromv3.cpp:1161 I[GDROM]: Invalid GD-DMA start, SB_GDEN=0. Ignoring it.
hw/gdrom/gdromv3.cpp:1004 I[GDROM]: GDROM: Write GD_DEVCTRL (Not implemented on Dreamcast)
hw/gdrom/gdromv3.cpp:1025 D[GDROM]: GDROM: Write to SecCount = B
hw/gdrom/gdromv3.cpp:1020 D[GDROM]: GDROM: Write to GD_FEATURES
hw/gdrom/gdromv3.cpp:421 D[GDROM]: ATA_SET_FEATURES
hw/gdrom/gdromv3.cpp:890 D[GDROM]: GDROM: STATUS [cancel int](v=40)
hw/gdrom/gdromv3.cpp:1025 D[GDROM]: GDROM: Write to SecCount = 22
hw/gdrom/gdromv3.cpp:1020 D[GDROM]: GDROM: Write to GD_FEATURES
hw/gdrom/gdromv3.cpp:410 D[GDROM]: ATA_SPI_PACKET
```

Stucked: [stuck_full.txt](https://github.com/flyinghead/flycast/files/6719127/stuck_full.txt)
```
hw/gdrom/gdromv3.cpp:1161 I[GDROM]: Invalid GD-DMA start, SB_GDEN=0. Ignoring it.
hw/gdrom/gdromv3.cpp:366 D[GDROM]: ATA_NOP
hw/gdrom/gdromv3.cpp:890 D[GDROM]: GDROM: STATUS [cancel int](v=49)
```

49(hex) = 01001001 (binary)
```c++
struct GD_StatusT
{
	union
	{
		struct 
		{
			u32 CHECK:1;    //Bit 0 (CHECK) : Becomes "1" when an error has occurred during execution of the command the previous time.
			u32 res :1;     //Bit 1         : Reserved
			u32 CORR:1;     //Bit 2 (CORR)  : Indicates that a correctable error has occurred. 
			u32 DRQ:1;      //Bit 3 (DRQ)   : Becomes "1" when preparations for data transfer between drive and host are completed. Information held in the Interrupt Reason Register becomes valid in the packet command when DRQ is set.
			u32 DSC:1;      //Bit 4 (DSC)   : Becomes "1" when seek processing is completed. 
			u32 DF:1;       //Bit 5 (DF)    : Returns drive fault information. 
			u32 DRDY:1;     //Bit 6 (DRDY)  : Set to "1" when the drive is able to respond to an ATA command. 
			u32 BSY:1;      //Bit 7 (BSY)   : BSY is always set to "1" when the drive accesses the command block. 
		};
		u8 full;
	};
};
```

**_Background story_**
I received a bug report from a gundam player, he is using Windows 7 or Windows 10, whenever he first load the game (without my weird Exit->Reloading game tricks), he will be booted to the BIOS screen directly, and the BIOS also reports "Please insert Game Disc"

By reading his log (from https://github.com/inada-s/gdxsv/issues/132), it is confirmed that the GDROM should be "loaded" since it shows `nullDC.cpp:97 N[BOOT]: Game ID is [T13306M]`.

I suspect his issue and my issue has the same root cause, although I cannot reproduce his problem without a precise timing "Exit->Reloading" reset

His original message:
DCの起動画面が表示されて、プレイを選択してもディスクが入ってないとなります。
The DC startup screen appears, and when I select play, it says that the disc is not in.

![DC](https://user-images.githubusercontent.com/602245/123493066-f3709680-d64d-11eb-9e73-b6708495ce93.jpg)
![DC2](https://user-images.githubusercontent.com/602245/123493072-f8354a80-d64d-11eb-9ce3-0fb6a85913fc.jpg)

**Comment by flyinghead** [comment]
Confirmed: many GD-Rom registers and state variables aren't reset when exiting the game. This can lead to the GD-Rom being in an invalid state when the game is restarted (or another game is started).

**Comment by flyinghead** [comment]
Should be fixed in the latest build

**Comment by vkedwardli** [comment]
Thanks!

**Comment by overlordchaos** [comment]
> Should be fixed in the latest build

my games that are pal wont boot or crash with this commit. will try this new one but your fix broken my games.
