### ISSUE TITLE
Fur Fighters missing texture on per pixel

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#282]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android, SD765g, Adreno620 on latest CI flycast standalone build

Github hash: 

Hardware: 

**_Description of the Issue_**
On per triangle and per strip rendering, the dark dialogue background is displayed correctly but other game assets and textures are negatively affected, using vulkan per pixel rendering fixes every issue except the dialogue box background doesn't render correctly, the screenshot is using vulkan per pixel, perfect except no background on dialogues text

**_Debugging Steps Tested_**
Tested each setting on opengl and vulkan

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Screenshot_2021-06-26-06-56-21-096](https://user-images.githubusercontent.com/85600282/123503874-a5f42980-d64d-11eb-8d32-3192ba2c1d21.jpg)

**Comment by flyinghead** [comment]
Testing on an Adreno 630, I can't reproduce the issue. The black background is displayed correctly in per-pixel.

Can you post your settings (or your emu.cfg) and your GPU driver version (Settings > About)?

**Comment by Nejsplitter** [comment]
[audio]
backend = Oboe
disable = 0

[config]
Debug.SerialConsoleEnabled = no
Debug.SerialPTY = no
Dreamcast.AutoLoadState = no
Dreamcast.AutoSaveState = no
Dreamcast.Broadcast = 0
Dreamcast.Cable = 3
Dreamcast.ContentPath = /storage/emulated/0/roms
Dreamcast.ForceWindowsCE = no
Dreamcast.FullMMU = no
Dreamcast.HideLegacyNaomiRoms = yes
Dreamcast.Language = 1
Dreamcast.Region = 1
Dreamcast.SavestateSlot = 0
Dynarec.Enabled = yes
Dynarec.idleskip = yes
Dynarec.safe-mode = no
UseReios = no
aica.AutoLatency = yes
aica.BufferSize = 1411
aica.DSPEnabled = yes
aica.NoSound = no
pvr.AutoSkipFrame = 0
pvr.MaxThreads = 3
pvr.rend = 4
rend.CrossHairColor1 = 0
rend.CrossHairColor2 = 0
rend.CrossHairColor3 = 0
rend.CrossHairColor4 = 0
rend.CustomTextures = no
rend.DelayFrameSwapping = yes
rend.DumpTextures = no
rend.ExtraDepthScale = 1.000000
rend.FloatVMUs = no
rend.Fog = yes
rend.MaxFilteredTextureSize = 256
rend.ModifierVolumes = yes
rend.PerStripSorting = yes
rend.RenderToTextureBuffer = no
rend.Resolution = 480
rend.Rotate90 = no
rend.ScreenStretching = 163
rend.ShowFPS = no
rend.SuperWideScreen = yes
rend.TextureUpscale = 1
rend.TranslucentPolygonDepthMask = no
rend.UseMipmaps = yes
rend.WideScreen = no
rend.WidescreenGameHacks = no
rend.vsync = no
ta.skip = 0

[input]
MouseSensitivity = 100
VirtualGamepadVibration = 20
device1 = 0
device1.1 = 1
device1.2 = 1
device2 = 10
device2.1 = 10
device2.2 = 10
device3 = 10
device3.1 = 10
device3.2 = 10
device4 = 10
device4.1 = 10
device4.2 = 10
maple_485d69228e24f5e46da1598745890b214130dbc4 = 0
maple_8e1f0bb5c24db3a3de8727d7afd2193534979920 = 0
maple_a1cc21cba608c55d28d6dd2b1939004df0e0c756 = 0
maple_a28e1570a076c59f7051b45df81a15761bd98727 = 0
maple_a718a782d34bc767f4689c232d64d527998ea7fd = 0
maple_c9ec57252de46ef361b85c7da9ef5ad58f853763 = 0
maple_fb60d4f4370f5dbe8267b63d38dea852987571ab = 0
maple_virtual_gamepad_uid = 0

[network]
ActAsServer = no
DNS = 46.101.91.123
EmulateBBA = no
Enable = no
server = 

[validate]
OpenGlChecks = no

![Screenshot_2021-06-26-16-09-41-876](https://user-images.githubusercontent.com/85600282/123517465-fcd32080-d698-11eb-9ce6-2aff0f6bb308.jpg)

**Comment by flyinghead** [comment]
Which fork are you using? I can't find commit `a0c17979` and there was no build on 2021/6/21.

Still can't reproduce the issue when using the same settings. But I can't find the build you're using.

**Comment by Nejsplitter** [comment]
I'm using the "gl: fix multiple rendering with GLES 2" artifact download, 

![Screenshot_2021-06-26-19-09-55-283](https://user-images.githubusercontent.com/85600282/123522015-53008d80-d6b2-11eb-8227-e8c219710a78.jpg)

Can you link me to the version you are using ?

**Comment by Nejsplitter** [comment]
Maybe the adreno 620 doesn't have certain vulkan extensions that the 630 does have, it's so strange because I just deleted the whole thing including the cfg from my device and reinstalled a completely fresh build from your Android CI builds and the only options I changed on the fresh install where to use vulkan, per pixel and changed the audio driver, that's it and still the same error, redream does not have this texture issue using per pixel on there. This is annoying the hell out of me because I'm thinking it couldn't be a revision difference from adreno 620 to 630 that a simple texture doesn't show in per pixel Could it ?

**Comment by Nejsplitter** [comment]
@flyinghead could you send me the build and cfg that you are using where you can't replicate the issue

**Comment by flyinghead** [comment]
I was using the same build (b3ad0a62) and tried various settings, including the ones you posted.
Flycast doesn't use any Vulkan extension so I don't think that would be the cause.

**Comment by flyinghead** [comment]
I just tested on an Adreno 615 (driver 512.331) and no issue either.

**Comment by Nejsplitter** [comment]
I'm thinking of just factory reset my device and try afresh, is there any way to update drivers on an adreno 620 ? I have every Android update installed

**Comment by flyinghead** [comment]
Yes, vulkan and per-pixel. An Android, Flycast only supports per-pixel with vulkan anyway.

You're using more recent drivers than me and probably a more recent Android version (I tested on 9 and 10). It might be the reason you're having this issue, although I have no idea why.

**Comment by Nejsplitter** [comment]
Hmm understood, yes I'm on Android 11, but why do you think the issue would persist on a higher driver/Android version than yours ?

**Comment by Nejsplitter** [comment]
I just read that the update from Android 9 to 10 and 10 to 11 hurt vulkan performance on a lot of devices, maybe my update to 11 hurt something needed for per pixel on your awesome flycast core . 
![Screenshot_2021-06-29-21-12-53-677~2](https://user-images.githubusercontent.com/85600282/123861454-19808a00-d91f-11eb-9d5b-c179ae2caac7.jpg)

**Comment by overlordchaos** [comment]
> I just tested on an Adreno 615 (driver 512.331) and no issue either.

maybe this is a similar issue i experienced with corrupted textures on sonic adventure 2 with per pixel option. when returned to default the issue was fixed.

**Comment by Nejsplitter** [comment]
Fur Fighters needs per pixel to correctly display things without issues, the problem is as @flyinghead and mentioned, it may be an issue with the Android 11 update affecting vulkan on my device because he tried to replicate my error on a similar GPU but on Android 9 and 10 but it was displaying correctly for him using vulkan per pixel on every occasion .

**Comment by Nejsplitter** [comment]
Issue solved in latest flycast for my device.
