### ISSUE TITLE
[Control] Bind special key to combo

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#283]
Hi, it would be great to bind some keys (like menu) to combo (L3+ R3 for example).

Other problem : The confirm and cancel buttons are linked to the button 1 & 2, this causes issues when alternating between DC & Arcade layout.

I think the special keys should be shared between DC/Arcade and apart from those control mappings.

**Comment by blueminder** [comment]
Flycast Dojo already has this feature bundled with Controller Mapping and is mostly at parity with Flycast when it comes to offline play: https://github.com/blueminder/flycast-dojo

That said, a bug was recently found when Axis controls were used for the button macros, releasing the direction when the macro is released, Button assignments work just fine though. Once I fix this issue, I'll try to make another pull request to the main Flycast project, just like the Dreamcast/Arcade controls beforehand.

**Comment by blueminder** [comment]
> The confirm and cancel buttons are linked to the button 1 & 2, this causes issues when alternating between DC & Arcade layout.

You should be able to reassign these yourself in the Controller Mapping menu.

**Comment by Immersion95** [comment]
> > The confirm and cancel buttons are linked to the button 1 & 2, this causes issues when alternating between DC & Arcade layout.
> 
> You should be able to reassign these yourself in the Controller Mapping menu.

The problem is that : 
Button 1 is confirm
Button 2 is cancel

If the buttons are different between DC & Arcade (which should be) then the confirm/cancel buttons change when playing a DC game and an Arcade game.

**Comment by blueminder** [comment]
> If the buttons are different between DC & Arcade (which should be) then the confirm/cancel buttons change when playing a DC game and an Arcade game.

That should be the case now, yes. Button mappings are an all or nothing deal. There's no system-independent mappings right now. It depends on what game you are playing.

Just assigning the same buttons to both should work right now.

**Comment by Immersion95** [comment]
Should I close the issue ?

**Comment by Immersion95** [comment]
Closing this as the distinct control layout is there :)

**Comment by leoxxx** [comment]
@flyinghead 
Can you add marco like dojo?
