### ISSUE TITLE
[Bug]Samurai Spirits 6 not working well with AMD 6000 cards

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#285]
I have an AMD 6800 card and Samurai Spirits 6 backgrounds aren't showing, I think it's due to Extra Depth Scale problems.

[flycast.log](https://github.com/flyinghead/flycast/files/6748278/flycast.log)

**Comment by flyinghead** [comment]
`Native Depth Interpolation` should help AMD cards but this game is hard to emulate properly on some GPUs.
