### ISSUE TITLE
Android 11 scoped storage restriction on sdcard

### ISSUE THREAD

**Issue by Gamemulatorer** [flyinghead/flycast#286]
Any plan to support android scoped storage framework so that we can still play our dc games on sdcard on android 11?

https://github.com/libretro/RetroArch/issues/12181

**Comment by flyinghead** [comment]
Can you describe the issue?
I don't have any problem accessing an SD card on Android 11 with flycast, at least in the device simulator.

**Comment by Gamemulatorer** [comment]
It's ok now after updating my Redmi Note 9 to MIUI 12.5.1 android 11
