### ISSUE TITLE
 arcade / dreamcast mapping Button problems 

### ISSUE THREAD

**Issue by darwink777** [flyinghead/flycast#289]
Hardware: xioami mi11 sd888

**_Description of the Issue_**
The emulador reads two inputs at the same time , Button 5 and 6 in arcade configuration are directional inputs in dreamcast configuration. 
The control just go crazy .
Thanks you very much for you effort.

**Comment by flyinghead** [comment]
Arcade buttons 5 and 6 are assigned to the right DPad in dreamcast mode. But the right DPad isn't used by the UI so it shouldn't be an issue.

Can you provide more details about the problem? (steps to reproduce, screenshots, etc.)

**Comment by darwink777** [comment]
I'm using a PS4 controller , (Game Capcom vs snk2  arcade Naomi versión )even when navigating in emulator menú i'm having problems , you can replicate this by just holding a input after and move sequence in Game , the input Will continue being pressed or Wont detect an input at all .  
. For example when you make rápid moves like hadoukens or 360 comand grabs, sometimes the directional input right de pad Up or down keeps being pressed down . 
After using the triggers can provoke this too . 
Also  Is not necessary to enter a Game to replicate this , right after you map your wireless controller try doing the inputs of a circule or hadoukens inputs then keep holding the direction Up or down to navigate the menú you'll notice the dpad Up or down Will sometimes read the input and sometimes not like if It was triying to read more than one input or if It was being cancel by another  . 
I tried to unmap the left and right stick since the Game cvs2 don't need this  axis but It didn't  help , its like somehow the input from the dreamcast configuration is getting mixed or intermiting with the arcade inputs . 
I tried reicast from the PlayStore and the problem doesnt happen , i suppose because there is just one configuration control .
Sorry for my english but i Hope you understand . 
Sincerely mi respect for you all .

**Comment by flyinghead** [comment]
I don't have the same hardware but I haven't been able to reproduce the issue on NVidia Shield TV with a PS3 controller. I haven't experienced keys being stuck or anything unusual with the controls (tested with cvsgd). I tried both wired and wireless configurations.

Can you test with the controller wired into your device instead of using bluetooth?

**Comment by blisstik** [comment]
I have an EmuElec user that is exhibiting this issue in RetroArch on the Odroid N2+.

An example game is Ikaruga where P1 controls both P1 and P2, unless you go into System Assignments and set to P1 only. But Ikaruga is a 2 player game.

**Comment by flyinghead** [comment]
Inactive
