### ISSUE TITLE
Microstutter on Windows using vulkan

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#290]
Platform / OS / Hardware: 
Windows 10 64 bit latest updates, Nvidia latest drivers
Github hash: 

Hardware: amd a8 7410 Apu, gtx 1050 ti

**_Description of the Issue_**
When using open GL or direct X, frame rate is smooth 60fps, when set to vulkan ther is very slight microstuttering only in video , audio is fine and occasionally the video will fluctuate from microstutter to smooth and back to microstutter. Game tested : virtua tennis 2 pal

**Comment by Nejsplitter** [comment]
@flyinghead it almost looks like a frame pacing issue but only on vulkan , so strange , or maybe it's something else but I have tried with a few games now and same result

**Comment by flyinghead** [comment]
I would make sense to test the NTSC version of this game to check if the problem also happens. Also, try to disable VSync.

It could a sync issue due to the game ouputting at 50 FPS and your screen being at 60 FPS.

**Comment by Nejsplitter** [comment]
Yes I have tested both NTSC and pal region and enable/disable vsync, same issue, also the issue does not happen when selecting open GL or direct X, it's definitely to do with vulkan although I'm not sure, it's almost like when using vulkan the games go from 60 Hertz to 50 Hertz or from 60 FPS to 30 FPS, very strange and only when selecting vulkan.

**Comment by flyinghead** [comment]
The easiest way to chat is our Discord server: https://discord.gg/X8YWP8w

**Comment by Nejsplitter** [comment]
@flyinghead you can close this now, what i did was use nvidia control panel to optimize settings to make full use of my hardware, also i used nvidia control fps limiter to 30 or 60 depending on what the game used and it seemed to help too, thank you.
