### ISSUE TITLE
vigilante 8 2nd offense: custom textures damages the menus/ingame text

### ISSUE THREAD

**Issue by overlordchaos** [flyinghead/flycast#291]
Platform / OS / Hardware: 
windows 10 x64 processor
Github hash: 
b3ad0a62
Hardware: 
intel core I7 @ 2.93 ghz
16 gbs ram DDR3
graphics card: radeon RX 570 series 8 gbs DDR3 ram
**_Description of the Issue_**
the custom textures makes all the ingame menu's textures damaged and unreadable. even the weapon quantity you are carring is messed up.
Add a short, concise description of the issue here
some menus (like the level select screen) like the big map is always in black, with or without custom textures. the spinning menus are never shown with or without custom textures. the rest is because custom textures. are saved in the same format as they are dumped with same transparency, etc.
**_Debugging Steps Tested_**
disabling the custom textures fixes the damaged text. thats all.

**_Screenshots_**

video from duckstation - playstation - port 100% exact game (just the buttons are different) i would say 100% visual perfect emulation:
https://youtu.be/3yM8ZGr6QU8
video from flycast. you can see all the differences are quite easy to see.
https://youtu.be/axcz6bvtHho

**Comment by flyinghead** [comment]
There is a known issue with this game's menus. See Issue #275 .

Can you post some sample custom textures to help reproduce the problem?

**Comment by overlordchaos** [comment]
> There is a known issue with this game's menus. See Issue #275 .
> 
> Can you post some sample custom textures to help reproduce the problem?

the issue with black menus yes. not with the text that is only with custom textures.
i will give you the texture folder. you just need to rename it. i am using the PAL version but the textures are the same even named. just do a small dump to see the name of your gd-rom (is quite similar a letter changes only on the folder name i think)
do please remember to TURN OFF texture dump before testing it or else the emu will load the original textures instead of the custom ones in order to dump them  https://www.mediafire.com/file/gpsh5fiwisys92n/T13002D.7z/file

**Comment by flyinghead** [comment]
No issue here:
![Screenshot from 2021-07-10 18-34-52](https://user-images.githubusercontent.com/16261910/125170135-a80dca80-e1ad-11eb-9930-aa01e9848d77.png)

**Comment by overlordchaos** [comment]
> No issue here:
> ![Screenshot from 2021-07-10 18-34-52](https://user-images.githubusercontent.com/16261910/125170135-a80dca80-e1ad-11eb-9930-aa01e9848d77.png)

the backround of the menu is missing. it can be part of the previous issue that animations are missing and NOT custom textures. but i do remember having the menu working without custom textures. let me see if i can show you how the menu looks on ps1 (same game and port) if you check the custom textures folder you will find the missing images. specially the one with the logo witch is big. something like 1024xppp so its not hard to find.
https://ibb.co/34VT7yP

**Comment by flyinghead** [comment]
Same menu, without custom textures. The background is missing because of #275

![Screenshot from 2021-07-10 19-06-23](https://user-images.githubusercontent.com/16261910/125170965-f02eec00-e1b1-11eb-8d8e-c516bc2a856b.png)

**Comment by overlordchaos** [comment]
> Same menu, without custom textures. The background is missing because of #275
> 
> ![Screenshot from 2021-07-10 19-06-23](https://user-images.githubusercontent.com/16261910/125170965-f02eec00-e1b1-11eb-8d8e-c516bc2a856b.png)

still the menu is dumped. would you boot the game AND turn on the "dump textures" option to see if the original textures are loaded?
