### ISSUE TITLE
Crash After Selecting Vulkan as Backend

### ISSUE THREAD

**Issue by galahadhiryu** [flyinghead/flycast#30]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
 Installed OS and version (Android 9.0) |Vulkan| 76b7970 | Downloaded from build site?|

Hi @flyinghead
When select vulkan as backend, the emulator crashes.
The last working version was 4730da3

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
What phone/gpu are you using?

**Comment by galahadhiryu** [comment]
I'm using a Galaxy A20. Exynos 7884 with a mali-g71.
It used to work until the build 4730da3, but after that it crashs after selecting vulkan as a backend.
Selecting vulkan while using your core on retroarch works just fine, but on flycast it crashs.

**Comment by flyinghead** [comment]
Can you check if the latest build fixes the crash? Thanks

**Comment by galahadhiryu** [comment]
Hi @flyinghead
Tested, but still crashing.

**Comment by galahadhiryu** [comment]
Hi
I don't know if related to the last problem, but reporting that since the build "3b83a4e" from "2020-01-16T", the emulator will crash at the moment of launch. The last working build was "8cadf0a" from "2020-01-09".

**Comment by flyinghead** [comment]
This is crazy. Nothing that could cause a crash between these two builds, and nobody has reported any issue. Are you sure nothing has changed on your side? Can you still run `8cadf0a` and is `3b83a4e` still crashing?

**Comment by galahadhiryu** [comment]
> This is crazy. Nothing that could cause a crash between these two builds, and nobody has reported any issue. Are you sure nothing has changed on your side? Can you still run `8cadf0a` and is `3b83a4e` still crashing?
It's really weird, but i just tested again and in fact the last one that works for me is 8cadf0a. After that all the new ones simply crash at launch.

**Comment by flyinghead** [comment]
Thanks for testing again.

When you say it crashes at launch, does it crashes immediately when starting the app or only when starting a game?

**Comment by galahadhiryu** [comment]
Crashes immediately when starting the app.

**Comment by flyinghead** [comment]
Which is even weirder: none of the changes from 8cadf0a to 3b83a4e are executed at startup.
Try deleting your emu.cfg file from your home folder.

**Comment by galahadhiryu** [comment]
Even after deleting this file, it crashs when starting the app.

**Comment by flyinghead** [comment]
The startup crash should be fixed in the last build.

Let me know if the Vulkan crash still happens. Thanks.

**Comment by galahadhiryu** [comment]
Oh, you are right, the startup crash is fixed, thank you =D.
Vulkan is still crashing.

**Comment by flyinghead** [comment]
The last build (ef223bb) hopefully fixes the vulkan crash.

**Comment by galahadhiryu** [comment]
It's fixed =D Thank you hehe, i usually test every build, really happy to see it fixed.

Before you close this thread, could i ask about a detail?

When using "Per pixel" the image looks kind of corrupted, probrably something off with the transparency. Is there some hope that android could render it correctly? Or it is some bug related to the mali gpu  that is on the exynos?

**Comment by flyinghead** [comment]
It's probably related to the mali gpu or its driver. I also have issues with mali-G51. It works fine on recent Adreno GPUs.
If you can, update your rom to get new drivers. Upgrading to Android 10 on Mali G51 did fix a number of driver bugs for me.

**Comment by galahadhiryu** [comment]
Oh, my phone will only get android 10 by may or june, but happy to know that they  made some progress with the drivers.
But thank you again for taking your time to fix the crashes, usually most devs don't really care for exynos.

**Comment by crazyrexz** [comment]
sorry if interrupting, my phone redmi note 8 on pie, build 23 march on master, virtual touchscreen is missing, something wrong fh?

**Comment by flyinghead** [comment]
This is unrelated. Please open a new issue.

**Comment by flyinghead** [comment]
@galahadhiryu I just made a change to Vulkan initialization on Android. I hope it's correct this time but if you get a crash at init time, let me know and I'll revert it.

**Comment by galahadhiryu** [comment]
Hi flyinghead 
From what i've tested (build d1b29a5, right?), it's working perfectly by using vulkan or opengl.

**Comment by flyinghead** [comment]
Fantastic! Thanks for testing so quickly. I guess this issue can now be closed.
