### ISSUE TITLE
cannot browse my rooms (room gallery doesn't slide)

### ISSUE THREAD

**Issue by neofeo** [flyinghead/flycast#304]
Platform / OS / Hardware: 

android 9 

Github hash:   147bd83

Hardware:  tv box s905y2

**_Description of the Issue_**

Hi, I have a bt controller and keyboard/mouse. with the controller doesnt allow me to pick anything, and with the mouse/keyboard I am constrained to the rooms I can display on my screen...bc I cant go down, no matter what I do.
the left side slide bar doesn't move at all.

**Comment by flyinghead** [comment]
Yes, I conform there is an issue with the mouse on Android. Scrolling should be possible by dragging the content list, or the left slide bar but it doesn't an Android.

You should also be able to scroll the list by using the left analog stick of your controller.

**Comment by flyinghead** [comment]
This should be fixed in the last build. I also added support for mouse scroll wheel, which was missing on android.

**Comment by neofeo** [comment]
Thanks for your effort!! Closing then... if it persist I will reopen.
