### ISSUE TITLE
Default Coin button?

### ISSUE THREAD

**Issue by j8r** [flyinghead/flycast#309]
By starting an Atomiswave or NAOMI arcade, a Coin is required. Most would want to play directly, but as for now no default mapping is set to put a coin.
I think it is quite important to have one, instead of having ones for the Test and Service, which is not used much (perhaps when debugging)?

Trigger buttons are not mapped for me (Dualshock 3 controller).

As a side note, it would be very practical to be able to assign a same button for multiple purposes: the same one for Start and Coin for instance.

**Comment by samosaphile** [comment]
Or another thing, which could be done if someone disagrees with having start button for coin, is maybe pressing start + A button, at same time.

**Comment by flyinghead** [comment]
The Coin button isn't mapped by default because you can use the Service button to insert coins as well. And the Service button is needed to navigate the service menu.

**Comment by j8r** [comment]
I don't have any service, test or coin default mapping anymore. I think it is quite recent.

**Comment by j8r** [comment]
In Controller Mapping, I see in the `Buttons` category: `Button 5` has `R1` and `Button 6` has `L1` :thinking:

**Comment by flyinghead** [comment]
yes, there's still no default mapping for the service, test and coin buttons. Many games are now configured in free play by default but not all of them. A default mapping for coin, at least, would be nice.

**Comment by j8r** [comment]
What's Button 5 and 6 by the way?

**Comment by flyinghead** [comment]
Arcade buttons 5 and 6 (Atomiswave has 5 buttons and Naomi 6 or more). They are mapped to triggers or shoulders by default on gamepads.
