### ISSUE TITLE
Geometry Correction Implementation

### ISSUE THREAD

**Issue by momoids** [flyinghead/flycast#310]
Is there some way implementation of geometry correction like PGXP in games like Dino Crisis (for example!) I'm not native English!

**Comment by flyinghead** [comment]
Can you be more specific? Post a screenshot?

Contrary to the PS1, the Dreamcast does perspective-correct texture mapping so there's no need for any correction.

**Comment by momoids** [comment]
I made a video showing the problem! Look how Regina has her body shaking all the time!
https://www.youtube.com/watch?v=5gavXj2t_54

**Comment by flyinghead** [comment]
The effect is clearly visible on the video but I don't know the cause. Also it's probably made even more obvious by rendering at a high resolution. It could be due to the 3D models used by the game, or a lack of precision in 3D calculations.

Do you know of other games that exhibit the same or similar issue?

**Comment by blisstik** [comment]
This issue sounds similar to the Tekken 7 on PPSSPP.

https://github.com/hrydgard/ppsspp/issues/5399

**Comment by momoids** [comment]
The problem also appeared in PSX version, but is fixed with PGXP in PSX emulators!

**Comment by B-Nerd** [comment]
was that not a psx thing i never see it on a crt but on higher resolutions you can see it

**Comment by B-Nerd** [comment]
the wobble is that not what the psx is famous for maybe not this kind but it made me think of that

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 12 aug. 2021 20:56, B-Nerd schreef:

**Comment by momoids** [comment]
PGXP in Duckstation: ON/OFF
![Dino Crisis PSX 1](https://user-images.githubusercontent.com/70231770/129316506-4d43c263-baf7-4b67-8cbf-fa49e60ba840.jpg)
![Dino Crisis PSX 2](https://user-images.githubusercontent.com/70231770/129316518-88d5853e-11e8-458c-94de-c9a8dead06c1.jpg)

**Comment by flyinghead** [comment]
This effect is due to the PS1 using affine texture projection. Again, Dreamcast uses perspective-correct projection so this fix is not applicable.
