### ISSUE TITLE
Closing the software 

### ISSUE THREAD

**Issue by B-Nerd** [flyinghead/flycast#316]
i have a question for a addition for this app is it possible to ad a close button or a option to close the program in the place where you select your roms

**Comment by Gamemulatorer** [comment]
Just like Redream there's a exit button.
![Screenshot_2021-08-13-14-03-45-207_io recompiled redream](https://user-images.githubusercontent.com/37603562/129312164-fc7668dd-64cb-4069-bc50-d95e91c31ce0.jpg)

**Comment by B-Nerd** [comment]
yep

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 13 aug. 2021 08:04, Angelo Burgos schreef:

**Comment by flyinghead** [comment]
Duplicate of #242
