### ISSUE TITLE
dot by dot aspect ratio?

### ISSUE THREAD

**Issue by Mr-Beacon00** [flyinghead/flycast#318]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10

Github hash: this? "c27180fb3278520788fe4086c891565e68aa99d6"

Hardware: CPU: AMD Athlon(tm) X4 840
GPU: GTX 750 Ti 2GB
RAM: 8GB

**_Description of the Issue_**
graphics looks not that sharp.
but using RetroArch+Flycast core is look pretty good.
Probably because aspect ratio?

**_Debugging Steps Tested_**
Change "Transparent Sorting" didn't look better
increase "Internal Resolution" still not good

**_Logs Gathered_**

```

```

**_Screenshots_**
![RA](https://user-images.githubusercontent.com/73895438/129475775-574066c1-b638-4fca-9848-79430570faba.png)

![Fly](https://user-images.githubusercontent.com/73895438/129475772-198cbbb2-e850-4a70-a75b-92c46c76bea2.png)

**Comment by flyinghead** [comment]
What is the rendering resolution and the resolution of your window?

**Comment by Mr-Beacon00** [comment]
> What is the rendering resolution and the resolution of your window?

rendering resolution is native.
I was using fullscreen. aspect ratio of retroarch is original.
My desktop resolution is 1920x1080.

**Comment by flyinghead** [comment]
1080 isn't a multiple of the native vertical resolution (480) so each dreamcast pixel will occupy 2.25 screen pixels.

Set your window height to 960 for example, to avoid such issue.

**Comment by Mr-Beacon00** [comment]
> 1080 isn't a multiple of the native vertical resolution (480) so each dreamcast pixel will occupy 2.25 screen pixels.
> 
> Set your window height to 960 for example, to avoid such issue.

ah... okay. if there have fullscreen ratio option will be better.
like retroarch, filled with black border.
thanks
