### ISSUE TITLE
Flycast works, but is too fast

### ISSUE THREAD

**Issue by a7150607** [flyinghead/flycast#320]
Hi,
I used Flycast Libretro port in my own project, It's works ,but is too fast.
I saw it call RETRO_ENVIRONMENT_GET_FASTFORWARDING on retro_run , and i alwasy retrun false. but this has no effect, it still runs very fast.
What can I do to make it run at normal speed, please help me

**Comment by flyinghead** [comment]
You probably need to wait when outputting audio. This is what regulates the emulator's speed.

**Comment by a7150607** [comment]
@flyinghead Thank you gotta reply.
 I tried your way to wait when outputting audio . and it's run  at normal speed, but when I do some gamepad input, it's running fast again.

**Comment by a7150607** [comment]
@flyinghead Thank you for your help, I have solved this problem
