### ISSUE TITLE
Project Justice: Rival Schools 2 Bug (PC Retroarch)

### ISSUE THREAD

**Issue by XxFran8234xX** [flyinghead/flycast#323]
Parts of the body, appear and disappear.

Preview: https://www.youtube.com/watch?v=C8wluMoofV8

**Comment by bslenul** [comment]
Use the core from this repo instead of the one from the online updater, the issue is fixed. Assuming you're on Windows: https://github.com/flyinghead/flycast/suites/3517922519/artifacts/83985157

**Comment by XxFran8234xX** [comment]
it works, thanks.
