### ISSUE TITLE
[Libretro] Saving/Loading a state sometimes close content

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#326]
Platform / OS / Hardware: PC / Windows 10 / i5-4670K / GTX 970

Github hash: 7fb83f4

Hardware: Dreamcast and Arcade

**_Description of the Issue_**

Since 951e70328fc7218a298dbf75f0325a54eca50dd9, when "Threaded Renderer" core option is ON, saving or loading a state randomly closes content, the core itself stays loaded in RetroArch.

The logs always have this line when it happens: `[INFO] [Environ]: SHUTDOWN.`.

Happening on Windows 10, on my Linux Mint VM for some reason I can't reproduce while loading a state, however it closes content too when saving.

**_Logs Gathered_**

* The House of the Dead 2 (arcade), logs for a failed save state (shutdown line 435): https://pastebin.com/d5LcmnEe
* Crazy Taxi (DC), logs for a failed load state (shutdown line 413): https://pastebin.com/8JzfyAn5
* Capcom vs. SNK 2 (Naomi), logs when trying to load a non-existent state multiple times in a row (line 1391 you can see it doesn't close 4 times in a row): https://pastebin.com/Msr8FENv

**Comment by flyinghead** [comment]
Hopefully the latest build should fix the issue.

**Comment by bslenul** [comment]
Seems to be fixed this time, couldn't get it to close content on both Windows and Linux!

Thank you! ❤️
