### ISSUE TITLE
[SWITCH] Flycast Standalone with SXOS 3.1.0

### ISSUE THREAD

**Issue by SL57** [flyinghead/flycast#331]
Hi ! 

I'm trying to use Flycast standalone for Switch and when i launch a game (Sonic Adventure PAL) the following message comes :

LOADING... Fatal error : segfault in fault_handler -> /_w/flycast/fly... (i don't see the end of message).

I have launched the game with Full memory (R).

My config : 
- Switch Mariko
- SXOS 3.1.0
- Emunand
- Bios DC in DATA folder

Do you have an idea for this issue ?

Regards,

SL57

**Comment by flyinghead** [comment]
I don't own a Switch so I can't help here. But if you know how to fix this issue, let me know.

**Comment by SL57** [comment]
Yes, so it's working fine now.

We just need to convert .nro to .xci :

https://mega.nz/file/PCgyxIaS#WfFmnN9Smy2zWETLhEGDNe35yRRGjX5Rs5JekAikRtw

Thx !

Le sam. 28 août 2021 à 11:38, flyinghead ***@***.***> a
écrit :
