### ISSUE TITLE
[macOS] [Request] Use the Application Support folder for data and emu.cfg

### ISSUE THREAD

**Issue by shinra-electric** [flyinghead/flycast#336]
Platform / OS / Hardware: 
macOS 

Github hash: 
N/A

Hardware: 
N/A

**_Description of the Issue_**

Currently Flycast uses a folder located at: ~/.flycast to store the data folder and emu.cfg 
(note that all folders starting with `.` on macOS are invisible by default, so it may be difficult for regular users to locate)

It is standard for apps on macOS to create a folder in the Application Support folder in the user's Library. 
I would suggest that Flycast should use this location instead: 

~/Library/Application Support/Flycast

**_Debugging Steps Tested_**
N/A

**_Logs Gathered_**
N/A

**_Screenshots_**
N/A

**Comment by vkedwardli** [comment]
Agree, also may be we should add a “Open Folder” button for platform with hard to access path like Mac?

**Comment by shinra-electric** [comment]
Yes, that's probably a good idea too
