### ISSUE TITLE
Vibration not working

### ISSUE THREAD

**Issue by MrTiVN** [flyinghead/flycast#341]
Tried Dualshock 4 & Xbox360 controllers. None got vibration working.

**Comment by bslenul** [comment]
Not many info :p 

Do you have the rumble thing plugged in port 2?

![image](https://user-images.githubusercontent.com/33353403/132090701-71e2c0c1-952f-484b-931a-0d45f5859b23.png)

**Comment by MrTiVN** [comment]
> Not many info :p
> 
> Do you have the rumble thing plugged in slot 2 of your emulated controller?
> 
> ![image](https://user-images.githubusercontent.com/33353403/132090701-71e2c0c1-952f-484b-931a-0d45f5859b23.png)

Thank you for your reply. I did have Purupuru plugged in. I tried to reinstall Flycast and now vibration works. :)
