### ISSUE TITLE
[Feature Request] Easy access to DC memory with Cheat Engine

### ISSUE THREAD

**Issue by PiKeyAr** [flyinghead/flycast#349]
Hello, and thank you for fixing the issue I reported previously.

One feature I really miss after switching to flycast is being able to inspect and alter the emulated console's memory in Cheat Engine easily. In Demul, the Dreamcast's memory starts at 2C000000 in the emulator's process memory, so it's easy to convert real DC addresses and pointers because you simply have to replace 8C with 2C to get the same address on the emulator.

I was wondering if something like that could be done for the standalone Windows version of flycast? This would greatly improve the workflow for making codes if flycast could be used in the same way as Demul with an easy to use address layout.

**Comment by flyinghead** [comment]
The Dreamcast RAM isn't at a fixed location in Flycast. It runs on so many different platforms that I don't think it's even possible.

The starting address of the RAM could be logged when the game starts it that helps.

**Comment by PiKeyAr** [comment]
Is it different every time a game starts on the same platform? Logging it would be good, and if the address remains the same between iterations it would be still useful with a simple calculator.

**Comment by flyinghead** [comment]
This is now on the master branch as well
