### ISSUE TITLE
Glitch on re-entering fullscreen mode

### ISSUE THREAD

**Issue by PiKeyAr** [flyinghead/flycast#350]
Platform / OS / Hardware: x86 / Windows 10

Github hash: 599874c9

Hardware: i7 9700K / GTX 1660 Super / 16GB RAM

**_Description of the Issue_**

There's a small glitch involving switching to/from fullscreen. If you exit fullscreen mode by pressing Alt+Enter, and then re-enter fullscreen mode by pressing the combination again, the image will be displayed as a rectangle at the bottom left corner of the screen, and mouse controls in the UI would not respond correctly to the mouse cursor. The problem resolves itself if you switch to another window with Alt+Tab and go back to the emulator, which then refreshes the screen and the picture takes the whole screen again.

**_Debugging Steps Tested_**

  * Run the emulator in windowed mode and load a game.
  * Press Alt+Enter to enter fullscreen.
  * Press Alt+Enter again to exit fullscreen.
  * Repeat the previous two steps if necessary.

**_Logs Gathered_**

I don't have logs but I think `emu.cfg` might help:
```
[audio]
backend = directsound
disable = 0

[config]
Debug.SerialConsoleEnabled = no
Debug.SerialPTY = no
Dreamcast.AutoLoadState = no
Dreamcast.AutoSaveState = no
Dreamcast.AutoSavestate = no
Dreamcast.Broadcast = 0
Dreamcast.Cable = 0
Dreamcast.ContentPath = D:\ISO\Dreamcast
Dreamcast.ForceWindowsCE = no
Dreamcast.FullMMU = no
Dreamcast.HideLegacyNaomiRoms = yes
Dreamcast.Language = 1
Dreamcast.Region = 0
Dreamcast.SavestateSlot = 0
Dynarec.DisableVmem32 = no
Dynarec.Enabled = yes
Dynarec.SmcCheckLevel = 0
Dynarec.idleskip = yes
Dynarec.safe-mode = no
Dynarec.unstable-opt = no
FastGDRomLoad = no
Social.HideCallToAction = no
UseReios = no
aica.AutoLatency = no
aica.BufferSize = 1764
aica.DSPEnabled = yes
aica.LimitFPS = yes
aica.NoBatch = yes
aica.NoSound = no
aica.Volume = 80
bios.UseReios = no
pvr.AutoSkipFrame = 0
pvr.MaxThreads = 3
pvr.SynchronousRendering = yes
pvr.backend = gl41
pvr.rend = 3
rend.AnisotropicFiltering = 1
rend.Clipping = yes
rend.CrossHairColor1 = 0
rend.CrossHairColor2 = 0
rend.CrossHairColor3 = 0
rend.CrossHairColor4 = 0
rend.CustomTextures = no
rend.DelayFrameSwapping = yes
rend.DumpTextures = no
rend.ExtraDepthScale = 1.000000
rend.FloatVMUs = no
rend.Fog = yes
rend.MaxFilteredTextureSize = 256
rend.ModifierVolumes = yes
rend.PerStripSorting = no
rend.PixelBufferSize = 536870912
rend.RenderToTextureBuffer = yes
rend.RenderToTextureUpscale = 1
rend.Resolution = 1440
rend.Rotate90 = no
rend.ScreenScaling = 100
rend.ScreenStretching = 100
rend.ShowFPS = no
rend.SuperWideScreen = no
rend.TextureUpscale = 1
rend.ThreadedRendering = yes
rend.TranslucentPolygonDepthMask = no
rend.UseMipmaps = yes
rend.WideScreen = yes
rend.WidescreenGameHacks = no
rend.vsync = yes
ta.skip = 0

[input]
MouseSensitivity = 100
RawInput = no
VirtualGamepadVibration = 20
device1 = 0
device1.1 = 1
device1.2 = 3
device2 = 10
device2.1 = 8
device2.2 = 8
device3 = 10
device3.1 = 8
device3.2 = 8
device4 = 10
device4.1 = 8
device4.2 = 8
maple_raw_keyboard_VID_258A&PID_000C&MI_00#9&14d0bfcd&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd} = 0
maple_raw_mouse_VID_046D&PID_C52F&MI_00#8&34075241&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 1
maple_raw_mouse_VID_258A&PID_000C&MI_01&Col01#9&2800dc0b&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 0
maple_sdl_joystick_0 = 0
maple_sdl_keyboard = 0
maple_sdl_mouse = 0
maple_sdl_mouse_\\?\HID#VID_046D&PID_C52F&MI_00#8&34075241&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 2
maple_sdl_mouse_\\?\HID#VID_046D&PID_C52F&MI_00#8&3849d5d1&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 2
maple_sdl_mouse_\\?\HID#VID_046D&PID_C52F&MI_00#8&f181a2c&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 2
maple_sdl_mouse_\\?\HID#VID_258A&PID_000C&MI_01&Col01#9&23519c3e&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 1
maple_sdl_mouse_\\?\HID#VID_258A&PID_000C&MI_01&Col01#9&2800dc0b&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 1
maple_sdl_mouse_\\?\HID#VID_258A&PID_000C&MI_01&Col01#9&2852c5e8&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 1
maple_win_keyboard = 0
maple_win_mouse = -1
maple_xinput-1 = 0

[log]
LogToFile = no

[network]
ActAsServer = no
DNS = 46.101.91.123
EmulateBBA = no
Enable = no
server = 

[validate]
OpenGlChecks = no

[window]
fullscreen = yes
height = 720
maximized = no
width = 1280

[windows]
height = 720
maximized = no
width = 1280
```

**_Screenshots_**
It's difficult to capture because it auto-corrects whenever you alt-tab from the emulator, but I managed to snap one screenshot. This is on a 1440p screen:
![image](https://user-images.githubusercontent.com/23312549/132995888-54bdb539-bd1d-4c75-9105-245127e993c7.png)
Most of the time a full picture is captured without the black part, and the resolution is reduced (1707x960 instead of 2560x1440). On the actual screen it took the bottom left corner like in the previous screenshot.
![image](https://user-images.githubusercontent.com/23312549/132995942-360cd4bc-d0f0-42f1-beeb-cb0184729cc8.png)

**Comment by flyinghead** [comment]
I haven't been able to reproduce it on ubuntu (GTX 1080) but it may be platform-specific.

Do you have the same issue with Vulkan or DirectX?

**Comment by PiKeyAr** [comment]
From a quick test it only seems to happen with OpenGL.

**Comment by PiKeyAr** [comment]
I'm not sure. My GTX 1660 S had a driver that was last updated in June. I updated to the most recent 472.12 today and was able to reproduce it.

**Comment by flyinghead** [comment]
Please reopen if the problem still happens with latest flycast and GPU drivers versions
