### ISSUE TITLE
Stupid Invaders gets stuck at the "SEGA" screen

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#354]
Platform / OS / Hardware: PC / Windows 10 / i5-4670K / GTX 970

Github hash: f7abe3bb34455c1683dd9a02c1563e1e18abf291

Hardware: DC

**_Description of the Issue_**

Stupid Invaders doesn't start (only tried the US version, tested with TOSEC and Redump versions), it gets stuck at the "SEGA" screen. Tried with GL and Vulkan, tried with interpreter, tried the RetroArch core as well, same issue.

**edit:** Oh interesting, it boots with the HLE BIOS 🤔 

**_Logs Gathered_**

Nothing useful, it doesn't print anything after `00:04:518 emulator.cpp:91 N[BOOT]: Game ID is [T17708N]` :/ I wanted to build debug build to maybe get better logs, but I'm getting a ton of include errors with "breakpad", and even after fixing them I got a linker error so I gave up :p I should be able to build the RetroArch core however, I'll do that tomorrow if it can help.

**Comment by bslenul** [comment]
No idea if it helps, but here's the RA log with debug (~150k for only a few seconds spent on the SEGA logo 😅 ): [retroarch_debug_logs.zip](https://github.com/flyinghead/flycast/files/7160538/retroarch_debug_logs.zip)

Unrelated but the game is playable with a mouse and to send a Start press ingame you have to press Right + Middle mouse, in standalone it works fine but in RA the middle click seems to be completely ignored. I double checked in Quake III and impossible to map middle click in the ingame setup menu, the wheel up/down is recognized but not the click.

I could open another issue for this if you prefer.

**Comment by flyinghead** [comment]
It's a known issue with this game. For some unknown reason it will only start with HLE BIOS.

Regarding the middle mouse button issue in libretro, there's indeed an error in the input code: the middle button is mapped to bit 0 (button C, unused) instead of bit 3.

**Comment by bslenul** [comment]
Ah my bad I wasn't aware, I searched "Stupid Invaders" in the issue tab before opening the issue but couldn't find anything.

**Comment by flyinghead** [comment]
Well, it was known ... to me ;) I don't recall anybody reporting this issue.

**Comment by scribam** [comment]
Using latest master (e8e382372a181c5ec085d9e4c6075dca74fb32de), it boots fine without the HLE BIOS.

@bslenul can you check again if you still have the issue?

**Comment by bslenul** [comment]
Hm nope, it still hangs on the SEGA screen for me with latest commit without HLE. Tested with GL/VK/D3D11 (tried D3D9 as well but it switches to GL automatically), only tested on Windows 10 tho.

**Comment by scribam** [comment]
My bad, I did not test correctly, I still have the issue as well.

**Comment by flyinghead** [comment]
HLE BIOS is now forced for this game
