### ISSUE TITLE
Vulkan Rendering Issues AMD

### ISSUE THREAD

**Issue by RinMaru** [flyinghead/flycast#358]
**Platform / OS / Hardware:**  
OS- Windows 11 x64
GPY- RX 480 4GB
CPU- Ryzen 5 5600X
RAM- 20GB DDR4

**_Description of the Issue_**
Vulkan has rendering issues with per pixel OIT
Flycast Build- 17348da

**_Screenshots_**
Vulkan
![Screenshot 2021-09-15 165923](https://user-images.githubusercontent.com/15071652/133508751-626f0066-5d6a-49a9-bacd-b064a3a99202.png)
OpenGL
![Screenshot 2021-09-15 164434](https://user-images.githubusercontent.com/15071652/133507739-5c11e43d-f48c-4e6d-8816-771f836dad7e.png)
Vulkan
![Screenshot 2021-09-15 165424](https://user-images.githubusercontent.com/15071652/133508448-d554dea3-af17-4670-ab5e-4deb4050d3c2.png)
OpenGL
![Screenshot 2021-09-15 165506](https://user-images.githubusercontent.com/15071652/133508469-fc2cf16c-952f-4a6f-8cd2-b5611c756595.png)

**Comment by MojoJojoDojo** [comment]
There are some other issues I noticed with while using the AMD mesa driver too.
Some garbled graphics in 2D games.
Curiously when you disable ACO and use LLVM it improves by a lot but you can still notice minor issues.

**Comment by RinMaru** [comment]
> There are some other issues I noticed with while using the AMD mesa driver too.
> Some garbled graphics in 2D games.
> Curiously when you disable ACO and use LLVM it improves by a lot but you can still notice minor issues.

It's got room to improve compared to redream but Flycast is deffinately moving along. Hope VK can outperform GL on Redream one day x3

**Comment by MojoJojoDojo** [comment]
I dont think comparing emulators gonna help this issue.
But I think there are certain issues with AMD GPUs here.
