### ISSUE TITLE
flycast refuses to run for the 1st time

### ISSUE THREAD

**Issue by DJRM2021** [flyinghead/flycast#359]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Windows 10, intel i5, nvidia mx330

Github hash: 17348da

**_Description of the Issue_**
flycast refuses to run at all because it is looking for a DX9 DLL. 
I think that at first launch of the program, it should not look for a specific DX9 DLL. It should only start looking for the dll when I set the renderer to DX9. What if I wanted to use Vulkan? I may never be able to because upon opening flycast it crashes and displays an error message.

It would be much easier for novice users to be able to run flycast.exe for 1st time without any DLL dependency problems. The ideal scenario is for 1st time launch of the app, the renderer should be openGL. Then, if user sets the renderer to DX9, that would be the only time for the app to look for DX9 DLLs on the system.

**_Debugging Steps Tested_**
I tried launching from command line: flycast.exe -config config:pvr.rend=0.
I also tried copying emu.cfg file from a previous version (pre-DX9 renderer builds)
None worked so far.

**_Screenshots_**

![image](https://user-images.githubusercontent.com/77593544/133712803-e1df4c58-8a41-43af-a4da-2bebf276686d.png)

**Comment by flyinghead** [comment]
DirectX 9 is now the default on Windows because some GPUs don't support Open GL and many GPUs don't support Vulkan.

Installing the DirectX9 June 2010 package should fix your issue: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by cinnamonmatexfce** [comment]
Same exact problem as you.
I simply solved downloading the _standalone_ dll: `d3dx9_43.dll` (`sha1: 2BF450850A522A09E8D1CE0F1E443D86D934F4AD`).
Put that dll inside the folder where reside you `flycast.exe` also.
Then, before starting up the emulator for the first time set manually thi string `pvr.rend = 0` inside the file `emu.cfg`

**Comment by DJRM2021** [comment]
Here's an update to this issue. I installed the DX9 runtime, downloaded d750723 build, and upon running flycast.exe for the 1st time, the error is gone but flycast crashes instantly. It just opens a bare win32 window and closes in an instant.

**Comment by cinnamonmatexfce** [comment]
> Here's an update to this issue. I installed the DX9 runtime, downloaded d750723 build, and upon running flycast.exe for the 1st time, the error is gone but flycast crashes instantly. It just opens a bare win32 window and closes in an instant.
> 
> ![image](https://user-images.githubusercontent.com/77593544/134099386-634da465-0a50-413d-8578-22640b6324f5.png)
> 
> It was able to create the "data" folder and the emu.cfg file, both are blank though.

Same as me. See my previous post. Dunno if this issue is expected or it's actually a bug. BTW... Copy and use a working `emu.cfg` and, **before starting flycast**, modify this string as it is written: `pvr.rend = 0 `

**Comment by flyinghead** [comment]
I suspect there is an issue with DirectX 9 on both your systems.
@cinnamonmatexfce: obviously manually installing a single dll will not make a valid installation. What gpu do you have?

Can you install and run this utility?
https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
There might be some useful information in the log.

Also check for minidump .dmp files in your temporary directory: `%USERPROFILE%\AppData\Local\Temp`
Please attach the most recent `.dmp` file that you find.

You can also force flycast to use Open GL by manually editing the emu.cfg file:
```
[config]
pvr.rend = 0
```

**Comment by cinnamonmatexfce** [comment]
> I suspect there is an issue with DirectX 9 on both your systems.
> @cinnamonmatexfce: obviously manually installing a single dll will not make a valid installation. What gpu do you have?
> 
> Can you install and run this utility?
> https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
> There might be some useful information in the log.
> 

Yup, manually putting the single `dll` is not valid. I know. Mine is only a workaround.
Unfortunately I cannot provide you logs because I cannot install anything in my PC `cause installation is locked by the administrator.

**Comment by cinnamonmatexfce** [comment]
> @cinnamonmatexfce What gpu do you have?
> 
Intel HD Graphics 630 (i5-7500).



> PS: DebugView is a single .exe file. If you can run flycast you should be able to run it.

I'll give it a try ASAP and I'll let you know.

**Comment by TheCoolPup** [comment]
I think they might be using a laptop, also i have a github account now, cool i guess

**Comment by cinnamonmatexfce** [comment]
> Also check for minidump .dmp files in your temporary directory: `%USERPROFILE%\AppData\Local\Temp`
> Please attach the most recent `.dmp` file that you find.
> 
I have no `.dmp` files at all.

Here's `.log` output gathered via `dbgview64.exe`:
```
[\\WINDOWSCOMPUTER]
00000001	0.00000000	[18296] 00:00:000 rend\dx9\d3d_renderer.cpp:148 W[RENDERER]: DirectX9 renderer initialization failed
00000002	0.00010640	[18296] 00:00:000 rend\gui.cpp:2252 E[COMMON]: Fatal error : Renderer initialization failed
00000003	0.00010640	[18296] 
00000004	0.00010640	[18296]  in rend_init_renderer -> D:\a\flycast\flycast\core\hw\pvr\Renderer_if.cpp : 296
```

**Comment by DJRM2021** [comment]
The emu.cfg workaround did not work for me. I will try on my other PC and some VMs to see how will it roll out.
![image](https://user-images.githubusercontent.com/77593544/134180495-29aeef0e-5547-4073-994b-f523b7b872df.png)

**Comment by cinnamonmatexfce** [comment]
> The emu.cfg workaround did not work for me. I will try on my other PC and some VMs to see how will it roll out.
> ![image](https://user-images.githubusercontent.com/77593544/134180495-29aeef0e-5547-4073-994b-f523b7b872df.png)
> 

I suppose Flycast needs a valid `emu.cfg`, not an empty one with just the only `pvr` string manually written.

**Comment by flyinghead** [comment]
Any .dmp file found? I need this in order to find and fix this bug.

**Comment by DJRM2021** [comment]
> Any .dmp file found? I need this in order to find and fix this bug.
[67a1f8b9-e452-4d7a-b2fd-e65637a410f0.zip](https://github.com/flyinghead/flycast/files/7206863/67a1f8b9-e452-4d7a-b2fd-e65637a410f0.zip)

**Comment by DJRM2021** [comment]
Hi, @flyinghead did you have the chance to check on the dump file?

**Comment by flyinghead** [comment]
The .dmp file corresponds to the crash when then DirectX9 renderer initialization fails above.

You might want to try the new DirectX 11 renderer:
```
[config]
pvr.rend = 2
```

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen if not.

**Comment by kathyrollo** [comment]
If anyone lands on this page facing the same d3dx9_43.dll not found error, running the DirectX End-User Runtime Web Installer](https://www.microsoft.com/en-gb/download/details.aspx?id=35) fixed it for me.

Relevant Microsoft Support topic - https://answers.microsoft.com/en-us/windows/forum/all/missing-d3dx943dll/a9fdf0d1-3b87-4fdd-a655-a526b4c90dbd
