### ISSUE TITLE
[AMD] Rayman 2 - Crash at the game's intro when using Vulkan per-pixel

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#368]
Platform / OS / Hardware: 
Windows 10
Intel i7 8550U
Radeon 530/Intel UHD 620
Github hash: 
Flycast 1.1 version
**_Description of the Issue_**
Game will crash after seeing the Rayman 2 logo at the intro.
Weirdly enough this will happen regardless of which GPU I use for flycast.
Per triangle and per strip works fine.
I also dual boot into a Linux distro and it works fine there.

**_Debugging Steps Tested_**

* Go to the Video tab.
* Choose Vulkan from the Graphics API.
* Choose Per-Pixel from Transpernt Sorting

**Comment by MojoJojoDojo** [comment]
At least it somewhat renders the logo correctly:
![image](https://user-images.githubusercontent.com/33392696/134309510-a192074b-0a88-4504-8dab-f04e6b9b350c.png)

Unlike issue #358

**Comment by flyinghead** [comment]
I tested this on Windows 10 with an Intel Iris+ 640 gpu and couldn't reproduce the crash. I also checked with the Vulkan validation layers enabled and didn't spot any error or warning.

Can you confirm the crash happens on the title screen above before pressing Start?
Can you attach your emu.cfg?

**Comment by MojoJojoDojo** [comment]
Yeah before pressing start.
I run the game as CHD btw if it matters (tried USA and Europe versions as well).
emu config here:
[emu.zip](https://github.com/flyinghead/flycast/files/7231746/emu.zip)

**Comment by MojoJojoDojo** [comment]
After updating Windows the issue seems to happen only on the Intel GPU side now.
While the AMD side will show the graphics not being shown correctly like in issue #358 after the menu loads properly.

**Comment by flyinghead** [comment]
Can you try the latest build on master?

I fixed a Vulkan issue recently

**Comment by MojoJojoDojo** [comment]
Nope still crashes for both GPUs.

**Comment by MojoJojoDojo** [comment]
Directx 11 also seems fine with using Vulkan now that I tried it with per-pixel.
Something is off only with Vulkan then.
