### ISSUE TITLE
about panthera ps4 mode

### ISSUE THREAD

**Issue by MuangChickeN** [flyinghead/flycast#369]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: 

Hardware: Windows nulldcbear,fightcade 2

**_Description of the Issue_**

can't setting key R2,L1,L2 key on panthera arcade contorller

ps4,ps3 all not working

**_Debugging Steps Tested_**

setting-key mapping

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by blueminder** [comment]
Did you try this?

http://flycast.dojo.ooo/faq.html#button-6

R2 buttons are typically triggers, which would be assigned on the "Analog Axes" side of the screen.

Controller mapping has also been overhauled to be simplified in recent Flycast CI builds, as well as in the latest Flycast Dojo GGPO test builds. The version on Fightcade is currently an older pre-GGPO release, but will see an upgrade as soon as the integration is ready.

**Comment by MuangChickeN** [comment]
corrections, both ps3 and ps4 version are R2,L2,L1 key are jammed

**Comment by blueminder** [comment]
Either way, give the answer to that FAQ response a shot. 

An easy way to compare what input type you should be assigning (Buttons vs Axes) is to look at the Windows Control Panel and comparing the two: https://twitter.com/blueminder/status/1436321524970106891

You can also try out the newer controller mapping in the latest net-rollback or Dojo releases, if you want.

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen if not.
