### ISSUE TITLE
mvsc2: Last boss Abyss character too thin with widescreen cheat

### ISSUE THREAD

**Issue by DreaMBlazeR** [flyinghead/flycast#370]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Lenovo A7-3300-GV Android kitkat 4.4.2
Github hash: ad80184e

**_Description of the Issue_**
Last boss of Marvel vs Capcom 2 (Abyss) becomes too thin for widescreen.
You know, the big monstrous red guy, that traverses the whole screen.

Add a short, concise description of the issue here

Not sure if he went on a diet, but Abyss' last transformation glitch can affect vertical hit boxes if he appears thin, but can still be hit with horizontal attacks, meaning horizontal hitboxes is still alright. This can be a problem though, specially if you try jumping pounce super moves like Hulk's Meteor Smash (though it rarely misses), or other similar super moves.

**_Debugging Steps Tested_**

  *Happens on any widescreen cheats
  *Disable any widescreen cheats to solve issue.
  *Use internal resolution changer, max I can get is 853x488
  *Also only happens on current Retroarch core build (NAOMI FLYCAST).
  *Other problems like windowed/resume app causes graphical corruption glitches on overlay touchscreen buttons (doesn't happen on standalone fllycast app)*
   *Preventive fix for touchscreen glitch is either don't use other app when windowing it, or don't disable touchscreen button when windowing. If glitches happen, you can fix it by toggling hide/show overlay touchscreen button, or use internal retroarch button combination  audio volume changer (rather than Android native vol+, vol-) whenever you want to change the volume You may fix the graphic corruption by toggling Bilenear Filterring. though it may cause the emulator to crash if the graphic bugs doesn't disappear and just randomly spreads.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Marvel vs  Capcom 2 v1 001 (2000)(Capcom)(NTSC)(US) ! -210922-190519](https://user-images.githubusercontent.com/89394472/134512973-ebaf098e-56d7-43da-9459-47172ff43151.png)

![Marvel vs  Capcom 2 v1 001 (2000)(Capcom)(NTSC)(US) ! -210922-190553](https://user-images.githubusercontent.com/89394472/134521694-664931d7-5e67-4b3c-a708-8dd107dd3a72.png)

![Screenshot_2021-09-23-21-33-44](https://user-images.githubusercontent.com/89394472/134515571-aaf5e630-0ef0-4f5f-b36f-ba9a3f5e0052.png)

**Comment by flyinghead** [comment]
I suppose this is a problem with the widescreen cheat for this game. Widescreen cheats sometimes have unintended side effects, which seems to be the case here.

The RA core should be updated soon and most other issues should be fixed by then.
