### ISSUE TITLE
There is a problem with the FlyCast core of libretro

### ISSUE THREAD

**Issue by clondy999** [flyinghead/flycast#375]
I'm using retroarch and the FlyCast core

My device is Xiaomi 4 and Android 4.4.4

Problems encountered now:

When I load soul power or death or life 2, it is normal at first, but when I go to some specific screen, it will be directly black or gray screen, but the game is still running, because I can hear the sound and press the key (the fight takes effect)

Maybe I need to be more specific:

For example:

Soul power, after selecting the character, the vs screen appears, which is normal, and then the screen that can't start the battle normally appears, which is always black / gray.

Death or life 2: when the mode is selected, the screen of selecting the role cannot be entered, and the black / gray screen also appears

**Comment by flyinghead** [comment]
Can you post a screenshot of Settings > About?

**Comment by clondy999** [comment]
Of course, I'll reproduce the operation now

**Comment by clondy999** [comment]
![IMG_4399](https://user-images.githubusercontent.com/73311186/134880140-ee970b1d-454f-43c3-859e-bdf308e7308f.JPG)

Before that, the black screen also appeared. Press the OK key to pass.

![IMG_4400](https://user-images.githubusercontent.com/73311186/134880169-5b6cc024-121c-453e-871c-92af32d56d94.JPG)

Then it appears here, you can't enter the battle picture. The sound is still running. You can hear the fight sound effect

**Comment by flyinghead** [comment]
What version of the Flycast core are you using?

**Comment by clondy999** [comment]
0.1 beb9a61

**Comment by flyinghead** [comment]
The libretro Flycast core hasn't been updated for while. It should be updated soon (hopefully this week). I suggest you test again with the new version when it's available.

**Comment by clondy999** [comment]
Will the old core also have problems? I want to play now
