### ISSUE TITLE
Metropolis Street Racer freezes after the intro video on android

### ISSUE THREAD

**Issue by QrTa** [flyinghead/flycast#376]
I'm using a Pocophone F1 android 10 miui 12
Flycast 1.1 stable version

After the intro video the game freezes. Not matters which region or version or file type. Every freezes after intro video. 
When I go to home screen and back to Flycast the app is crashing. 

**_Debugging Steps Tested_**

I tried EU
tried USA
Tried different revision (idk what is the differences between revA or revB)
Tried to skip by pressing start
Tried fast forwarding. 
I tried different file types (cdi, gdi, chd)
Tried latest master build.
Tried latest net-rollback build
Tried to change backend to vulkan

**_Logs Gathered_**

```



```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This game needs a real BIOS. It doesn't support the HLE BIOS.

**Comment by QrTa** [comment]
> This game needs a real BIOS. It doesn't support the HLE BIOS.

I'm using. I tried 2 different bios one from 2009 and one from 2014.

**Comment by QrTa** [comment]
There was probably something in the settings what I broke. Now it's working with a fresh reinstall.
