### ISSUE TITLE
Judder with scrolling in games

### ISSUE THREAD

**Issue by Harineto** [flyinghead/flycast#380]
OS: Windows and Mac

While playing games that scroll you can see judder (frame skipping) happen this does not happen in NullDC. So a fix for Flycast would be amazing.

Can test this using the 240p scroll test to confirm the frame skipping. No fix has been found not even River Tuner in Windows works.

https://artemiourbina.itch.io/240p-test-suite?download

**Comment by flyinghead** [comment]
This is likely due to your platform and/or settings.

Here is a scroll test with the latest Flycast master build:
https://youtu.be/6n1ZEO9abDU

Make sure to enable VSync and Delay Frame Swapping for best accuracy.
