### ISSUE TITLE
Monkey ball controls android

### ISSUE THREAD

**Issue by Monkemanguy** [flyinghead/flycast#381]
Platform / OS / Hardware:Android

Github hash: 

Hardware: Android A10e

**_Description of the Issue_**
So whenever I use the touchscreen controls in monkey ball the Naomi game the controls don't work as they should for example when i go left on the analog I go up and when I press down I go right so and so

**Comment by flyinghead** [comment]
Which version of Flycast are you using?

I can't reproduce this issue: the touchscreen stick is working correctly for this game here.

**Comment by flyinghead** [comment]
Delete your `emu.cfg` file and the `mappings` directory and restart the app.

**Comment by Monkemanguy** [comment]
Sorry for the wait time I was busy but I deleted emu.cfg and mappings and still the same thing

**Comment by flyinghead** [comment]
Are you using the correct MAME rom? It should be named `monkeyba.zip` and should have a corresponding GD-ROM named `monkeyba/gds-0008.chd`.

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen if not.
