### ISSUE TITLE
Flycast suddenly doesn't start properly (grey screen)

### ISSUE THREAD

**Issue by Jenmet-cy** [flyinghead/flycast#387]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Samsung Galaxy A21s - Android 11

Github hash: 

**_Description of the Issue_**

After playing some titles normally and without issues, Flycast now only starts with a grey/black screen.

**_Debugging Steps Tested_**

  * Install Flycast 
  * Play some titles on the phone
  * Test other DC emulators, like Redream and Reicast (this could have caused the issues, as they share the same codebase, which I didn't realize at the time.) The latter app was uninstalled after the issue, but it didn't change anything. 
  * Deleting everything related to Flycast/reicast (emu.cfg and mappings, and everything in /data/user/0) didn't have any effect.

**_Logs Gathered_**

```
https://www.dropbox.com/s/0uxsw7rw4ye71vk/2021-10-15-02-07-59.txt?dl=0
```

**_Screenshots_**

![Screenshot_20211015-020614_Flycast](https://user-images.githubusercontent.com/52474680/137438166-33be6574-5836-4ac6-b6ef-056b57044273.jpg)

**Comment by flyinghead** [comment]
Thank you for the logs. Unfortunately they aren't very verbose. I added some init logs to the app that should help us identify the problem.
Please check the latest build on the `net-rollback` branch.

Is your phone rooted?
I had several reports of similar issues on rooted phones. Solutions included hiding root and deinstalling some "modules".

**Comment by Jenmet-cy** [comment]
Mount (no su):
[mount-nosu.txt](https://github.com/flyinghead/flycast/files/7354885/mount-nosu.txt)
Mount (su):
[mount-su.txt](https://github.com/flyinghead/flycast/files/7354886/mount-su.txt)

I didn't run into any problems using the command

> Flycast doesn't care about the phone being rooted or not. However it requires a reliable OS that has a predictable behavior.

Well, it's Samsung's stock ROM. Nothing's been changed about it, aside from root. 

This is a shot in the dark, but could busybox be interfering with the way Flycast uses the `mount` command?

**Comment by flyinghead** [comment]
The latest build on the net-rollback branch should fix the issue.

**Comment by Jenmet-cy** [comment]
Yep. I can confirm the latest net-rollback build starts properly, with no issues. Thanks flyinghead.
