### ISSUE TITLE
Coin button on on-screen controls? (Atomiswave / Naomi roms only)

### ISSUE THREAD

**Issue by cssobral2013** [flyinghead/flycast#396]
**Is your feature request related to a problem? Please describe.**
Because there are no Coin button when running Atomiswave / Naomi roms, these games are virtually unplayable.

**Describe the solution you'd like**
As per title, please place a Coin button on Atomiswave / Naomi roms.

**Comment by flyinghead** [comment]
The Naomi/AW service buttons can be pressed with the on-screen gamepad:
RT + A -> D (Coin)
RT + B -> C (Service)
RT + X -> Z (Test)
