### ISSUE TITLE
Linux screensaver inhibiting

### ISSUE THREAD

**Issue by Pobega** [flyinghead/flycast#398]
**Is your feature request related to a problem? Please describe.**
Currently (at least on Linux) when playing Flycast the screensaver will activate like normal interrupting gameplay.

**Describe the solution you'd like**
Talk to `org.freedesktop.ScreenSaver` over `Dbus` to tell it to inhibit the screensaver while a game is actively being played.

[org.freedesktop.ScreenSaver.{Un,}Inhibit spec](https://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html)
[example of inhibiting screensaver (in Python, sorry)](https://gist.githubusercontent.com/fxthomas/9bdfadd972eaf7100b374042faac28c2/raw/94590f2ff10cfb59492c0995fba9a44ec9179691/gnome-inhibit.py)

**Describe alternatives you've considered**
None, though a wrapper could be made to support this. But it'd be better if it was supported at the emulator level itself.

**Additional context**

**Comment by flyinghead** [comment]
`SDL_DisableScreenSaver()` should do the trick

**Comment by Pobega** [comment]
I'm not sure if this works. According to `src/video/SDL_video.c` in SDL_VideoInit() it seems to be [called by default when initializing video](https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L558-L566), but it doesn't appear to have an affect on Linux.

I did a bit of Googling and mgba (which I believe uses SDL as well) has an open bug for screensaver inhibiting not working on modern Linux (https://github.com/mgba-emu/mgba/issues/2228)
