### ISSUE TITLE
No Button 5/6 for NAOMI/Atomiswave games.

### ISSUE THREAD

**Issue by TheArcadeStriker** [flyinghead/flycast#40]
| Windows x64 | master | 93bedb9 | Yes |

**_Description of the Issue_**

There is no support for NAOMI/Atomiswave 5th and 6th buttons. While Buttons 1-4, Coin, Service and Test are mapped to Dreamcast controls, there is no way to use Button 5 and 6.

**Comment by flyinghead** [comment]
resolved
