### ISSUE TITLE
Analog not working in Naomi/AW roms (but they do work in DC roms)

### ISSUE THREAD

**Issue by cssobral2013** [flyinghead/flycast#401]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 11 on Galaxy A01, OneUI 3.0

Version: Latest, as per Github repo

**_Description of the Issue_**

Load any Naomi or AW fighting game, and try to move joystick in quarter-/half-circle (as described below). As the joystick is not working, this emulator is useless to run them.

**_Debugging Steps Tested_**

  * Load any Naomi or AW fighting game (you own, of course)
  * Wait till it loads
  * Proceed to char select, etc.
  * On battle: 
        -   Try to move the joystick in quarter-circle from down to left/right, or:
        -   Try to move it in half-circle from left to right or vice-versa
  * You'll see that you cannot enter the commands properly

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Fighting games don't use the analog joystick. They only use the DPad buttons.

**Comment by flyinghead** [comment]
There might be some misunderstanding here. I have no control over the type of inputs a game uses. All arcade fighting games exclusively use DPad buttons and not analog sticks.

With an external gamepad, it is possible to configure an analog stick to act as the DPad. This is not possible with the Android on-screen gamepad. However you can do quarter-circles and half circles with the DPad without problem.

**Comment by cssobral2013** [comment]
@flyinghead - See, I'll open another issue for better clarifying.
