### ISSUE TITLE
Games using SDL_DREAMHAL, such as OpenTyrian, crash when booting using CPU Dynarec

### ISSUE THREAD

**Issue by Wellyxc** [flyinghead/flycast#403]
Platform / OS / Hardware: 
Windows 10 X64

**_Description of the Issue_**

Some homebrew game ports (I've tested on game ports that use SDL_DREAMHAL, such as OpenTyrian) have problems using the Dynarec dynamic recompiler when starting. These games crash the emulator when booting using the CPU Dynarec option. 

This is fixed by starting the game using the CPU interpreter and switching to Dynarec once the game starts. (For better performance)

An easy fix/hack would be adding an option to "Use the interpreter only at boot" and then switch to Dynarec automatically later.

**_Debugging Steps Tested_**

  * Start OpenTyrian DreamHal (https://dreamcast-talk.com/forum/viewtopic.php?t=14422) using the Dynarec dynamic recompiler

**Comment by flyinghead** [comment]
Even easier is to fix the dynarec. I just pushed a fix on the `net-rollback` branch.

**Comment by flyinghead** [comment]
Closing as fixed
