### ISSUE TITLE
[ANDROID] Make the D-Pad bigger (or make a setting to allow to do so)

### ISSUE THREAD

**Issue by cssobral2013** [flyinghead/flycast#406]
**Is your feature request related to a problem? Please describe.**
Unfortunately, the D-Pad in Naomi/AW roms is sometimes inneficient to insert quarter-/half-circles, so increasing the size of D-Pad (or a setting for allowing to do so) would be a good idea.

**Comment by flyinghead** [comment]
You can edit the layout of the on-screen gamepad and the size of the DPad is customizable.

`Settings >Controls > Android Virtual Gamepad > Edit`

**Comment by cssobral2013** [comment]
@flyinghead - Thank you for information! Could you close this issue, then?
Thank you once more!

Em qua., 17 de nov. de 2021 6:18 PM, flyinghead ***@***.***>
escreveu:
