### ISSUE TITLE
deathcox roms verification failed to synchronize with the current version of mame

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#409]
The naomi game ,deathcox defined by flycast is a combination of deathcox and deathcoxj. flycast1.1 does not recognize deathcoxj.
since version 0.227 of mame, deathcox has been renamed deathcoxj

mameinfo:
- 0.227: Fabrice Arzeno added Death Crimson OX (USA). Note: Possible location test or limited release. Changed (Rev A) to clone 'Death Crimson OX (Japan, Rev A)' and clone Death Crimson OX to 'Death Crimson OX (Japan)'. Renamed (deathcox) to (deathcoxj).

**Comment by flyinghead** [comment]
should be fixed on master
