### ISSUE TITLE
Crash on unload if RETRO_ENVIRONMENT_GET_CLEAR_ALL_THREAD_WAITS_CB not implemented by frontend

### ISSUE THREAD

**Issue by Jamiras** [flyinghead/flycast#418]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: any

Github hash 465499f

Hardware: any

**_Description of the Issue_**

If the frontend doesn't implement `RETRO_ENVIRONMENT_GET_CLEAR_ALL_THREAD_WAITS_CB`, then the  `frontend_clear_thread_waits_cb` variable doesn't get initialized and attempting to use it in `retro_unload_game` causes the frontend to crash.

`RETRO_ENVIRONMENT_GET_CLEAR_ALL_THREAD_WAITS_CB` is not part of the libretro.h interface and as such, the frontend will not know to support it.

flycast should check the return value of `environ_cb` here: https://github.com/flyinghead/flycast/blob/465499f6c322267f2ef246465070f7eb7223a190/shell/libretro/libretro.cpp#L265
and set the variable to null or a dummy function.

**_Debugging Steps Tested_**

  * Added dummy handler for `RETRO_ENVIRONMENT_GET_CLEAR_ALL_THREAD_WAITS_CB` to alternate frontend. Crash no longer occurs when calling `retro_unload_game`.

**_Logs Gathered_**

**_Screenshots_**

**Comment by flyinghead** [comment]
confirmed

**Comment by flyinghead** [comment]
This should be fixed

**Comment by Jamiras** [comment]
I think the fix is incomplete. There's nothing explicitly setting the variable to null, so your check is looking at uninitialized memory, which will usually be not-null.

**Comment by flyinghead** [comment]
Static variables are default-initialized, so the variable is null.

**Comment by Jamiras** [comment]
Ok, then it hasn't made it to the buildbot yet. I'll try again tomorrow.

**Comment by flyinghead** [comment]
Yes, it doesn't look like it's been built on the libretro side.

You can grab it from this repo if you want: https://github.com/flyinghead/flycast/actions/runs/1510229587
(linux and windows only)

**Comment by Jamiras** [comment]
Fix confirmed on latest buildbot build.
