### ISSUE TITLE
The arm platform cannot load fonts. I need your help

### ISSUE THREAD

**Issue by asdone7** [flyinghead/flycast#426]
hello，

I can load fonts well under Ubuntu, but I can't load fonts when I use cross compilation to generate binary files for arm platform. I need your help

Thanks in advance.

**Comment by flyinghead** [comment]
I suppose you mean TTF fonts for ImGui?
What happens when you try to load fonts?
Which fonts are you trying to load?
Can you add some logs to help troubleshoot the problem?

**Comment by asdone7** [comment]
Sorry for the delay.

Yes, I mean imgui TTF。I added regular.ttf font in the way of "ImFont* font = io.Fonts->AddFontFromFileTTF". After the construction is completed, open the binary file, all the symbols displayed are "？"。
I checked the construction log and prompted me whether "void gui_init()': unused variable 'font'" is related to this. However, I also have this prompt when building under ubuntu, and it does not display abnormity

**Comment by flyinghead** [comment]
This is probably not related to Flycast. I believe normal font loading works on arm.

Make sure the font you are trying to load has the glyph range you want to use. You will find more help on ImGui site: https://github.com/ocornut/imgui.

**Comment by asdone7** [comment]
Thank you for your reply，I went to ImGui site for help，Thank you again.
