### ISSUE TITLE
Drawing is not smooth on my new pc Gigabyte G7 (i7-11800H 3050Ti)

### ISSUE THREAD

**Issue by Kiminari-Suzuki** [flyinghead/flycast#427]
Hello. I am not a good English speaker, but I am in trouble.

I bought a new pc Gigabyte G7 (i7-11800H 3050Ti), then flycast's drawing become not smooth.

For example, Soulcalibur, especially when background picture pans, drawing is not smooth.

I selected vga intel and nVidia both, but both are not good. nVidia is better, but not perfect as my old pc which has not extra vga.

Is it flycast's problem? or my pc?

**Comment by flyinghead** [comment]
Enable VSync for smooth pans and better frame pacing. If you have a 120 Hz or more monitor, disable VSync and use an external FPS limiter.
If that doesn't help, try switching graphics API: DirectX 9, Open GL and Vulkan. Vulkan should give you the best results but it depends on the platform so try them all.

**Comment by Kiminari-Suzuki** [comment]
Oh Thank you. My monitor's refresh rate was 144 Hz, and I set it 60 Hz on nVidia control panel, then it worked. Thanks.
