### ISSUE TITLE
hmgeo, at startup，the game will continue to check for network again and again

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#431]
When use Retroarch + flycast core, after the game is started, the network will be checked again and again, an error will be reported, and a 60-second countdown will occur. . . But flycast 1.1 works good. Copy flycast\data\hmgeo.zip.eeprom hmgeo.zip.nvmem to the RetroArch\saves\reicast directory, the problem is not solved.So I think this has nothing to do with the specific setup of the game
![hmgeo-211203-190233](https://user-images.githubusercontent.com/80488411/144634637-6da30677-ed08-493b-83bf-c57df7c8f067.png)
The versions of all programs are up to date

**Comment by flyinghead** [comment]
You can disable networking in the Service Menu > Game Test Mode > Game Configuration.

**Comment by crashGG** [comment]
Thank you, the problem is solved perfectly，I also found an option to maximize the violence of the game :)
