### ISSUE TITLE
kofxi,ngbc,character sprites broken

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#432]
kofxi,ngbc,character sprites are cuted into strips.
![kofxi-211203-195519](https://user-images.githubusercontent.com/80488411/144642220-9d5ae6b4-8c04-4242-88d7-5a1db163fca1.png)
![ngbc-211203-195038](https://user-images.githubusercontent.com/80488411/144642240-43785719-4598-4838-b683-7381528afd18.png)

But this problem is not exist in similar games, that is, fighting games with 2d characters and 3D background,like kofnw,samsptk,cvs2... 
why ?

**Comment by flyinghead** [comment]
What do you mean by "cut into strips"?

PS: don't use Texture Upscaling. It won't work with this game.

**Comment by crashGG** [comment]
<img width="110" alt="1" src="https://user-images.githubusercontent.com/80488411/144648173-84a9394b-95a4-4db5-ab8d-25a6829d29e7.png"
<img width="75" alt="2" src="https://user-images.githubusercontent.com/80488411/144648180-5962e4ad-0224-4a3d-b101-0a4c09626dc2.png">
<img width="64" alt="3" src="https://user-images.githubusercontent.com/80488411/144648186-d621d6e5-3f2e-4bd4-8398-20a8d8dbc289.png">
>
<img width="50" alt="4" src="https://user-images.githubusercontent.com/80488411/144648196-5eb5574f-f0d9-4850-88c5-742b6966a9c9.png">

Can't you see any abnormalities? In fact, it is especially obvious when the characters are moving. I didn't use any options to upscaling the texture. I have tried various attempts and can't get any normal images.

**Comment by flyinghead** [comment]
Yes, this is likely due to this game using texture filtering on partial character textures. Texture filtering doesn't work between two adjacent textures, so the edge is visible.

**Comment by crashGG** [comment]
Can it be fixed?

**Comment by flyinghead** [comment]
Not easily but textures can now be forced to point sampling/nearest-neighbor.

**Comment by Immersion95** [comment]
Forcing Nearest in texture filtering finally allows us to solve this. Thanks flyinghead :).
