### ISSUE TITLE
Naomi - Bios selection

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#452]
Hi,

Unless I'm mistalken, by default, some Noami games are in japanese, but it could be changed by selecting the good bios in the naomi.zip file.

For example, with "another old DC emulator I'm currently using for lightgun games", if I choose the file **epr-21578d.ic27** (which is an Export version), I can play these games in english (and even Maze of the Kings in french !).

Could it be possible to add this option in the settings ? 
And a command-line parameter (for frontends, some games need different bioses, ex. Hotd2) ?

**Comment by flyinghead** [comment]
You can choose the Naomi BIOS with the Region setting (Settings > General). Europe selects the Export BIOS.

**Comment by dukeblooders** [comment]
Thanks, my region was set on USA, but games are still in Japanese... I don't know if it's normal or not, but it's good for me.

**Comment by flyinghead** [comment]
Some games will not start with an Export or US BIOS. So for these games the BIOS is forced to one supported by the game.
