### ISSUE TITLE
Arcade Virtual Gamepad

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#459]
Is there no arcade virtual gamepad so we can play Atomiswave dumps on a touchscreen tablet? Is only good with a controller?

**Comment by flyinghead** [comment]
The on-screen gamepad can be used for both Dreamcast and arcade games. Missing buttons can be accessed with the following combinations:
RT + A -> D (Coin)
RT + B -> C (Service)
RT + X -> Z (Test)

**Comment by MoeFoh** [comment]
Sweet! Thanks.
