### ISSUE TITLE
D-PAD can not be defined and did not work 

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#46]
| Platform | Branch | Hash | CIDL |
| Windows 10-x64 | Master | 09c439bb | Website |

**_Description of the Issue_**

Xbox 360 Controller did not work after adding SDL

**_Screenshots_**

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
As discussed on Discord, this sems resolved
