### ISSUE TITLE
Naomi - HotD2 and Confidential Mission, reload not working

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#460]
Hi, 

Reload works fine on other Naomi games, but not on these two (and their Dreamcast versions work too). 
Using the reload button works like the trigger and fires on the upper-left corner.

My config : Flycast standalone, Windows 10, Raw input, Device A is lightgun with reload button mapped on mouse right button (also tried a key).

**Comment by flyinghead** [comment]
Confidential Mission (arcade) has a native reload button (button 2) so it doesn't need/use the Flycast reload button.
The console version uses off-screen reloading, which works fine with Flycast reload in my test.

Both versions of HotD use off-screen reloading and they seem to work fine with the Flycast reload button.
However I remember the arcade version needs gun calibration for reload to work properly.

**Comment by dukeblooders** [comment]
Ok thanks.

confmiss:
- I tried with Button 2 and it works. However, I noticed an issue with the reload sound when you reach the "homo sapiens" room (on both versions). The sound is not always played. Hard to know if you reload correctly your gun or not :)

hotd2:
- Button 2 works too, but not Reload, even with calibration.

Could it be possible to have the Reload button to work like the Button 2 for these two games (or at least confmiss if I missed something for hotd2, to have the same config for all Naomi ligthgun games) ?

**Comment by dukeblooders** [comment]
I didn't mention it, but I'm using a Sinden lightgun with the Sinden offscreen reload enabled.

Results of my tests:
Some games work with Button 2 (+confmiss +hotd2 +mok +rangermsn  / -deathcox -ninjaslt -sprtshot)
Some games work with Reload (+deathcox +ninjaslt +mok +rangermsn / -confmiss -hotd2 -sprtshot)

I can't get sprtshot reload to work, not a big deal since there's an auto-reload option by default.
And the confmiss sound bug is not only for reload, other sounds are also skipped (like screams, ...)

But I managed to have a setup that works with two flycast configurations. So it's OK for me.
So thanks for your explanation, and for your work. It's great to have a up-to-date DC/Naomi emulator with lightguns support.

**Comment by dukeblooders** [comment]
I created a new issue for confmiss, I close this one.
