### ISSUE TITLE
Cable setting question.

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#461]
VGA vs Composite.
Does the setting make any difference in the way Flycast outputs video?

Why is it even needed?

**Comment by flyinghead** [comment]
There's usually no difference between VGA and TV composite video output. However the game can detect the current video connection and may produce different outputs in VGA vs. TV. For example, it might produce 480p in VGA and switch to 240p in TV Composite.

On the other hand, some games don't support VGA and won't even start. And some games don't support TV (RGB) and will crash or hang. This is why TV (Composite) is the default and you probably never need to change it.

**Comment by MoeFoh** [comment]
Does this mean in VGA do we get true 60fps? In TV composite, with the video output at 480i do we get 30fps and Flycast duplicates each frame because the fps counter shows 60fps. If that's the case then why wouldn't VGA be the better choice, except for games that are not VGA compatible?

Keep up the great work!

**Comment by flyinghead** [comment]
You can get true 60 FPS both in VGA and TV Composite.

With TV Composite (480i) the original hardware would only display half the lines of each frame. Flycast displays a full frame every time (in effect outputting 480p.) There is no frame duplication. If it wasn't the case, VGA would be preferred over TV Composite.
