### ISSUE TITLE
Arcade Virtual Gamepad Issue.

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#468]
Android v1.2-202 CI - fresh install. 

It looks to me like RT and X Button are backwards. rumblf2, for example, RT = high kick X = charge.  Should be the other way around.

With a real controller, the mapping looks correct.

I just played Rumble Fish 2 at 60fps on a 6 year old tablet, using a Rockchip rk3188! Did not expect that! Really excellent work being done with this emulator.

**Comment by flyinghead** [comment]
The default mapping of external gamepads on Android is different than on other platforms. (I suppose it's a bug).
For Arcade games, the default mapping is:
A: button 1
B: button 2
X: button 3
Y: button 4
RT: button 5
LT: button 6

For Android gamepads, RT and LT are swapped. But the virtual gamepad uses the correct mapping.

**Comment by MoeFoh** [comment]
From my experience the default sram configuration usually, not always, has 3 mapped to the 'special' action of the game. It's a shame we can't remap buttons on the virtual arcade gamepad.
