### ISSUE TITLE
Vibration not working in recent CI master and net-rollback Windows x64 builds?

### ISSUE THREAD

**Issue by Azurfel** [flyinghead/flycast#469]
bf87f7b 2021-12-20T13:32:18.000Z is the most recent master build with working vibration for me.
And 325cd9a 2021-12-17T12:52:15.000Z is the most recent net-rollback build.

OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Processor	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 8 Logical Processor(s)
GPU	NVIDIA GeForce GTX 1660
Driver Version	27.21.14.5206

Controller is a DualShock 4 hooked up via USB using DS4Windows version 2.1.19 to appear as an Xbox 360 controller.

**Comment by flyinghead** [comment]
It looks like yet another SDL regression.
Does unplugging the controller and plugging it back while flycast is running fix the issue?

**Comment by Azurfel** [comment]
DS4Windows keeps the proxy 360 controller active when the DS4 is unplugged.

But stopping, then restarting DS4Windows *should* be functionally equivalent based on it's effect on Flycast's Control menu, and that does not fix the issue.

**Comment by flyinghead** [comment]
For reference, this might be related: https://github.com/libsdl-org/SDL/issues/4911
