### ISSUE TITLE
Frame pacing/timing issue in 30fps games

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#479]
tested on windows 10 64 bit, android, xbox series x, nvidia shield, all powerful enough devices, tested latest Flycast standalone emulator and latest libretro flycast core, both have the same issue. 60 fps games appear to be unaffected, however 30fps games have a frame pacing/timing issue even while the fps states constant 30. you can notice it when you play a game like fur fighters or shenmue and move the camera slowly around you will see the slight random judders every few seconds.

interestingly on android standalone flycast sometimes after a few seconds of bad frame pacing it randomly fixes itself and 30fps frame pacing becomes smooth

redream has no such issues on any platform i have tested

**Comment by cinnamonmatexfce** [comment]
What if you enable "VSync" and "Delay Frame Swapping" in "Video" settings?

**Comment by Nejsplitter** [comment]
i have tried every combination of settings, @cinnamonmatexfce  i would be interested to see can you replicate my issue and compare it to redream, also im interested in seeing if @flyinghead  can reproduce the issue when he has time and compare it to redream

**Comment by cinnamonmatexfce** [comment]
> i have tried every combination of settings, @cinnamonmatexfce  i would be interested to see can you replicate my issue and compare it to redream, also im interested in seeing if @flyinghead  can reproduce the issue when he has time and compare it to redream

I'll give it a try as soon as I can.
BTW, I never had (or never noticed) the problem you're having. My OS /HW: ArchLinux with official binary drivers GTX 1660 SUPER (Vulkan render). I'm on 4K TV @60Hz with NO FreeSync.

Also please check out issue #380

**Comment by Nejsplitter** [comment]
understood thank you, for me i found fur fighters the best game to test for 30fps frame pacing as you can slowly spin the camera in a circle and really notice the judders compared to redream which is smooth

**Comment by Nejsplitter** [comment]
@twinaphex does the framerate setting still exist for flycast for retroarch, i remember there being a setting to set framerate to "fullspeed" or "normal", i want to do some testing but cant find this setting

**Comment by cinnamonmatexfce** [comment]
> @twinaphex does the framerate setting still exist for flycast in retroarch? i remember there being a setting to set framerate to "fullspeed" or "normal", i want to do some testing but cant find this setting

It will popup when you disable threaded rendering, if I remember well...

**Comment by Nejsplitter** [comment]
No i cant find it even after disabling that, do you have the framerate setting in your one ?

also, please let me know if you or anyone can reproduce the issue as it is driving me insane lol

**Comment by cinnamonmatexfce** [comment]
> i have tried every combination of settings, @cinnamonmatexfce  i would be interested to see can you replicate my issue and compare it to redream, also im interested in seeing if @flyinghead  can reproduce the issue when he has time and compare it to redream, i have managed to reproduce the issue on many platforms as stated in my initial post

Tested on Linux (and Android also) standalone `flycast`. Moving the camera around is fine and really smooth. No graphic stuttering / judders at all...

**Comment by Nejsplitter** [comment]
have you tried with 30fps games ? also can you try retroarch android and compare it to redream android, fur fighters is the best game iv found for testing, after the intro, run back out into the open grass and spin the camera slowly you should notice subtle frame pacing jitters compared to readream, its strange how i can replicate the issue on multiple hardware

**Comment by Nejsplitter** [comment]
have you tried with 30fps games ? also can you try retroarch android and compare it to redream android, fur fighters is the best game iv found for testing, after the intro, run back out into the open grass and spin the camera slowly you should notice subtle frame pacing jitters compared to readream, its strange how i can replicate the issue on multiple hardware. Android standalone latest flycast is smooth for me but android libretro flycast latest has the issue along with xbox series x and nvidia shield and my pc

**Comment by Nejsplitter** [comment]
understood, can you try retroarch android and compare it to redream android, fur fighters is the best game iv found for testing, after the intro, run back out into the open grass and spin the camera slowly you should notice subtle frame pacing jitters compared to readream, its strange how i can replicate the issue on multiple hardware. Android standalone latest flycast is smooth for me but android libretro flycast latest has the issue along with xbox series x and nvidia shield and my pc

i have also tested on my brothers tv and issue persists, both our tvs are 60hz, the issue is so subtle i think not everyone would notice it unless they knew exactly what to look for

**Comment by Nejsplitter** [comment]
i think i may have narrowed it down, on android flycast standalone latest i can reproduce and remove the issue randomly by toggling the audio drivers back and forth (null, oboe etc randomly), @flyinghead any idea what this could be ? some kind of audio video syncing timing issue for 30fps games on a 60hz monitor

**Comment by Nejsplitter** [comment]
i think i may have narrowed it down, on android flycast standalone latest i can reproduce and remove the issue randomly by toggling the audio drivers back and forth (null, oboe etc randomly), @flyinghead any idea what this could be ? some kind of audio video syncing maybe? that only shows up as subtle inconsistant judders on 30fps content on a 60hz monitor, interestingly anytime i get the issue on flycast android latest standalone and then put the audio driver to "null" the frame pacing is butter smooth using "null" audio driver

also i found some info regarding syncing on the redream site : 
https://redream.io/posts/improving-audio-video-synchronization-multi-sync

**Comment by Nejsplitter** [comment]
i think i may have narrowed it down, on android flycast standalone latest i can reproduce and remove the issue randomly by toggling the audio drivers back and forth (null, oboe etc randomly), interestingly the issue is only present when i initially open the emulator and launch a game @flyinghead any idea what this could be ? some kind of audio video syncing maybe? that only shows up as subtle inconsistant judders on 30fps content on a 60hz monitor, interestingly anytime i get the issue on flycast android latest standalone and then put the audio driver to "null" the frame pacing becomes butter smooth using "null" audio driver, this method only works on android standalone for some reason, on all other platforms trying this makes the game double speed (interestingly the frame pacing becomes smooth even on double speed on the other platforms i mentioned using "null" audio driver)

also i found some info regarding syncing on the redream site :
https://redream.io/posts/improving-audio-video-synchronization-multi-sync

**Comment by Nejsplitter** [comment]
i think i may have narrowed it down, on android flycast standalone latest i can reproduce and remove the issue randomly by toggling the audio drivers back and forth (null, oboe etc randomly), interestingly the issue is only present when i initially open the emulator and launch a game @flyinghead any idea what this could be ? some kind of audio video syncing maybe that only shows up as subtle inconsistant judders on 30fps content on a 60hz monitor? interestingly anytime i get the issue on flycast android latest standalone and then put the audio driver to "null" the frame pacing becomes butter smooth using "null" audio driver, this method only works on android standalone for some reason, on all other platforms trying this makes the game double speed (interestingly the frame pacing becomes smooth even on double speed on the other platforms i mentioned using "null" audio driver)

redream has smooth frame pacing, also i found some info regarding syncing on the redream site :
https://redream.io/posts/improving-audio-video-synchronization-multi-sync

**Comment by Nejsplitter** [comment]
@flyinghead is it possible that currently flycast does not display every second frame in 25/30 fps games which run to vsync? maybe a commit would help with an option to force every frame generated by the console to be displayed to the host, which may improve pacing for these games

**Comment by flyinghead** [comment]
Flycast currently doesn't duplicate frames, meaning a 30 FPS game will display 30 frames per seconds.

**Comment by Nejsplitter** [comment]
understood thanks, not sure if you could reproduce the main problem im having in this main issue or if you have time to but iv tested many platforms all with the same result except flycast android which i can fix by changing audio drivers around back and forth, not sure if you have any idea what may be going on

**Comment by flyinghead** [comment]
It's likely due to Flycast rendering frames too rapidly then having to wait (audio output or display). So for example, with a 30 FPS game, instead of generating frames like this:
```
vsync : * * * * * * *
render: *   *   *   *
```
It might do something like this:
```
vsync : * * * * * * *
render: * *     * *
```

**Comment by Nejsplitter** [comment]
understood thanks, so is there anything one could do to bypass the disorderly rendering? on android standalone latest i have somewhat fixed it by toggling the audio drivers from null to oboe, on windows using rtss helps but on series x neither can be done, also i have tested alongside redream and that emu has perfect 30 fps rendering sync to my eyes, do you think flycast could be updated to do similar ?

**Comment by 71knight** [comment]
> i have tried every combination of settings, cinnamonmatexfce i would be interested to see can you replicate my issue and compare it to redream, also im interested in seeing if flyinghead can reproduce the issue when he has time and compare it to redream, i have managed to reproduce the issue on many platforms as stated in my initial post

Dolphin emulator on Android also has this problem.  And at 60 FPS on Metroid prime it's really annoying and makes the game go from playable to unplayable!

**Comment by Nejsplitter** [comment]
Duplicate of #520
