### ISSUE TITLE
The Maze of the Kings (NAOMI GD-ROM): Frame-pacing issues (mostly with the DX renderer)

### ISSUE THREAD

**Issue by RavenMacDaddy** [flyinghead/flycast#484]
Platform / OS / Hardware: 

Windows 11 - 22000.376
Ryzen 3600
GTX 1080 - driver 497.29

Monitors:

ASUS TUF Gaming VG279QM
Philips PUS7555

Github hash: 7555263 (v1.2)

**_Description of the Issue_**

Despite always being locked to 60 (with almost perfect frame-times thanks to RTSS), which as described below in the debugging-section seems to be the native framerate of the game, the game the majority of the time looks like it's stuttering - aka, some form of frame-pacing issue.

EDIT: After some more testing, I noticed that the issue is most present when using the DX renderer, hence the change of the title - which also coincides with the other issues for the renderer, like what's described in issue #485.

Vulkan and OpenGL so far produces perfectly acceptable frame-pacing most of the time, as long as I'm running the game on my TV monitor.

**_Debugging Steps Tested_**

  * Playing with OpenGL, Vulkan, or DX9 as the graphics API.
  * Playing without frame limiting in RTSS to confirm that the game is capped to 60 FPS and not something higher.
  * Playing the game on both my main monitor with G-Sync and my TV which has 60 Hz as its native max refresh rate and which always has better frame-pacing for all 60 FPS games - though the same issue is present on both monitors, at least with the DX renderer.

**_Logs Gathered_**

```
00:00:003 rend\gles\gles.cpp:512 N[RENDERER]: Open GL version 4.3
00:02:172 hw\mem\_vmem.cpp:505 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:02:190 hw\mem\_vmem.cpp:505 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:07:391 hw\naomi\naomi_cart.cpp:367 N[NAOMI]: NAOMI GAME ID [THE MAZE OF THE KINGS]
00:07:391 emulator.cpp:227 N[BOOT]: Game ID is [THE MAZE OF THE KINGS]
```

**_Screenshots_**

![image](https://user-images.githubusercontent.com/67732686/148179397-780decc0-afad-44b1-ae7e-f3a8c8e8388f.png)

**Comment by flyinghead** [comment]
Please upgrade to the latest master build. There is now a new DirectX 11 renderer and there's been fixes to the DX9 one.

Make sure to enable VSync to avoid frames being dropped (if your monitor is 60 Hz). You can also try single-threaded mode (disable `Advanced > Multi-threaded emulation`).

**Comment by RavenMacDaddy** [comment]
Confirmed to be working even with multi-threading enabled it seems.

V-Sync is forced through the GPU control panel and disabled in the app.

Closing as working with the new DX11 renderer.
