### ISSUE TITLE
Rayman 2 (Dreamcast): Broken GFX with custom textures (most severely with Vulkan) - sparkles as a clear example

### ISSUE THREAD

**Issue by RavenMacDaddy** [flyinghead/flycast#486]
Platform / OS / Hardware: 

Windows 11 - 22000.376
Ryzen 3600
GTX 1080 - driver 497.29

Github hash: 7555263 (v1.2)

**_Description of the Issue_**

Especially the Vulkan renderer has issues with certain GFX.

The most clear example of this is sparkles, as can be seen in the images below.

In fact, when using DX9 or OpenGL, seemingly only the "source" sparkle(s) produces the same visual glitch - and only for a single frame.

I'd to limit the app to 1 FPS with the help of RTSS in order to actually capture it.

It's also why I probably never noticed the issue as I was playing through the game since I always used OpenGL then.

EDIT: Later noticed that the issue is not present if custom textures are not used.

The texture pack is found [here](https://raymanpc.com/forum/viewtopic.php?f=89&t=74260).

**_Debugging Steps Tested_**

  * Playing with OpenGL, Vulkan, or DX9 as the graphics API.
  * Playing with and without custom textures.

**_Logs Gathered_**

Contents that might be of interest:

```
00:00:002 rend\gles\gles.cpp:512 N[RENDERER]: Open GL version 4.3
00:03:464 hw\mem\_vmem.cpp:505 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:03:481 hw\mem\_vmem.cpp:505 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:03:504 emulator.cpp:91 N[BOOT]: Game ID is [17707N]
00:04:787 rend\CustomTexture.cpp:112 N[RENDERER]: Found custom textures directory: F:\Backup\Scoop\apps\flycast\current\data\textures/17707N/
01:46:575 rend\vulkan\vulkan_context.cpp:228 N[RENDERER]: Vulkan API 1.1. Device NVIDIA GeForce GTX 1080
01:46:575 rend\vulkan\vulkan_context.cpp:236 N[RENDERER]: eR5G5B5A1UnormPack16 not supported for optimal tiling
01:46:575 rend\vulkan\vulkan_context.cpp:250 N[RENDERER]: eR4G4B4A4UnormPack16 not supported for optimal tiling
01:47:112 rend\vulkan\vulkan_context.h:264 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
01:47:125 rend\vulkan\vulkan_renderer.cpp:31 N[RENDERER]: VulkanRenderer::Init
01:47:230 rend\vulkan\vulkan_context.h:264 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
```

I also noticed that the DX renderer seemingly never shows up in the log.

**_Screenshots_**

With the Vulkan renderer: 

![Rayman 2 - Vulkan](https://user-images.githubusercontent.com/67732686/148185601-9b8fe536-92ee-486f-942d-e68ee454f0cc.png)

With OpenGL/DX9:

![Rayman 2 - OpenGL and DX9](https://user-images.githubusercontent.com/67732686/148185591-68b0f6e6-0134-40eb-9ef0-5854f31d5943.png)

**Comment by flyinghead** [comment]
I believe your custom texture is incorrect (922d72e2.png)
![922d72e2](https://user-images.githubusercontent.com/16261910/166112250-8ad4037f-8762-41da-9b65-9f5d08fba9ae.png)

The original texture doesn't have an alpha channel (in the dumped texture the alpha channel is constant 1.0):
![image](https://user-images.githubusercontent.com/16261910/166112298-6919f733-7045-492d-a5b5-07200fece0d7.png)

It works in Open GL because luckily it uses the alpha channel it shouldn't be using. It's not the case with Vulkan.

**Comment by RavenMacDaddy** [comment]
Ah, I see.

Thanks for the investigation.
