### ISSUE TITLE
Add internal resolution output to the corresponding widescreen hack for libretro flycast

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#502]
retroarch core version: 1.2-54
retroarch video driver: gl

<img width="724" alt="1" src="https://user-images.githubusercontent.com/80488411/148653398-c7e39c16-d7f4-4c67-beda-691a527983ca.png">
<img width="660" alt="2" src="https://user-images.githubusercontent.com/80488411/148653405-ce87b1f4-f8ca-4ded-bda6-4c82fb8fcec0.png">
Please add internal resolution output to the corresponding widescreen hack for libretro flycast,just like the stand alone flycast.

**Comment by flyinghead** [comment]
The list of rendering resolutions in the Retroarch UI is fixed but the widescreen hack is supported. So an actual resolution of 1706x960 will be used if 1280x960 is selected and Widescreen Hacks is enabled.
