### ISSUE TITLE
Slowdown with 60 fps codes (possible virtual overclock option?)

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#504]
Using 60 fps codes for games like tony hawks pro skater 2 works great but at some moments there is still virtual slowdowns that break the 60fps smoothness (because its running at native dreamcast cpu speed ? ) that i think a virtual cpu overclock option might fix, @flyinghead  is there any way to do this already or any plans ?

**Comment by PiKeyAr** [comment]
Are you sure the slowdown is coming from the emulator? I made a 60 FPS code for Sonic Adventure, and reicast and flycast are the only two DC emulators where it doesn't slow down, while in other emulators there are moments where it enters slow motion due to lack of CPU speed.

**Comment by Nejsplitter** [comment]
@PiKeyAr  thanks for your comment :) i will try somic adventure using your code, could you tell me where i can get your most up to date 60 fps code for sa1 dc ? and will i have to patch particular things one by one individually ? cheers

**Comment by Nejsplitter** [comment]
realised its a game specific issue that needs more analysis
