### ISSUE TITLE
Bilinear / Bicubic Texture Filtering

### ISSUE THREAD

**Issue by Papermanzero** [flyinghead/flycast#506]
**Describe the solution you'd like**

Currently the dreamcast supports texture filtering only as XBR  or unfiltered. It would be great to have bilinear and bicubic filtering as well. In come cases the XBR filtering looks not very matching to the style of the game. Therefore bilinear/bicubic would much more fit

**Describe alternatives you've considered**

An option to filter all textures or just the dreamcast foreseen textures together with an option about the filtering (unfiltered, xbr, bilinear, bicubic)

**Comment by shinslash** [comment]
Really want that

**Comment by Calinou** [comment]
Bilinear texture filtering is already available in Flycast – it's the default if the game does not request nearest-neighbor filtering. However, https://github.com/flyinghead/flycast/pull/574 makes it possible to force bilinear filtering on all textures if you wish. It also exposes the anisotropic filtering option to the GUI, which improves texture appearance when viewed at oblique angles.

**Comment by Papermanzero** [comment]
Actually I thought that Bicubic has a crispier look than bilinear because the transition from one color to another is not so broad. Means the sharpness is more given than with bilinear. However the calculation is more intensive than bilinear

Here an example:
![](https://www.360s.com/wp-content/uploads/2009/07/bilinear-vs-bicubic.jpg)

**Comment by flyinghead** [comment]
Bilinear and point sampling can now be forced (#574). Bicubic filtering isn't worth the effort IMHO.
