### ISSUE TITLE
Shield Tablet GL ES shader compilation error

### ISSUE THREAD

**Issue by master1274** [flyinghead/flycast#510]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: MODEL: SHIELD Tablet

DEVICE: shieldtablet

BOARD: unknown
Nougat (24)

Native Interface Output

--------- beginning of system
--------- beginning of main
Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)
Any build above Flycast_v1.2-6-gbf87f7ba crashes on startup, no error message. Black screen and crash.
[flycast.log](https://github.com/flyinghead/flycast/files/7900628/flycast.log)
[flycast (1).log](https://github.com/flyinghead/flycast/files/7900632/flycast.1.log)

**Comment by flyinghead** [comment]
Should be fixed in the next build

**Comment by master1274** [comment]
Thank you. Fixed.
