### ISSUE TITLE
rhythm tengoku naomi desynchronization

### ISSUE THREAD

**Issue by juan200213** [flyinghead/flycast#514]
Rhythm Tengoku video game doesn't sync with the music during the minigames please fix it
windows lenovo ideapad

**Comment by daFourch** [comment]
I can confirm this, on Retroarch or Stand Alone Windows. Music synchro is slighty off. Double checked with GBA version

**Comment by juan200213** [comment]
the bug is in Stand Alone Windows

**Comment by daFourch** [comment]
and in the RetroArch core as well

**Comment by JomSpoons** [comment]
Just checked for myself and this issue is still present in v2.0 (aa97a6d6)

**Comment by flyinghead** [comment]
Can someone test a recent dev branch build?
I made some changes to cpu timing that may affect this game.

**Comment by flyinghead** [comment]
Closing as inactive. Reopen as needed.
