### ISSUE TITLE
[Android] Fast-Forward doesn't work with Vulkan

### ISSUE THREAD

**Issue by waspennator** [flyinghead/flycast#517]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:
Android 10
Galaxy Note 9

Github hash: 
https://github.com/flyinghead/flycast/commit/58f05f7

Hardware: 
Snapdragon 845, Ardeno 630

**_Description of the Issue_**

For some reason, fast forwarding only works with the OpenGL backend and not the Vulkan one

**_Debugging Steps Tested_**

  * Switched to the OpenGL backend and confirmed it works there.

**_Logs Gathered_**

N/A

**_Screenshots_**

**Comment by flyinghead** [comment]
This is because most phones don't support Vulkan "immediate present mode." This mode is required to disable VSync wait and properly implement fast-forward.
