### ISSUE TITLE
Multiple Vulkan ICD causes failure

### ISSUE THREAD

**Issue by dmanlfc** [flyinghead/flycast#518]
Platform / OS / Hardware: x86_64 / Linux (Manjaro)

Github hash: 9ab4bb9

Hardware: Multi-GPU - i.e. laptop or iGPU & eGPU desktop.

Add a short, concise description of the issue here:

If multiple vulkan drivers are loaded under linux in `usr/share/vulkan/icd.d/` flycast will fail with - "Couldn't create window: Installed Vulkan doesn't implement the VK_KHR_surface extension"
Note: libretro-flycast does not have this issue.

**_Debugging Steps Tested_**

  * remove & leave 1 json file - works
  * add an environment variable like VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json - works

**_Logs Gathered_**

**_Screenshots_**

**Comment by flyinghead** [comment]
I don't think there's anything I can do in Flycast to work around this. Flycast uses SDL to create the window and this error message comes from SDL. It might be an SDL issue or some Vulkan driver is invalid.

**Comment by dmanlfc** [comment]
@flyinghead I solved it. Problem was on our side with the default Vulkan path.
