### ISSUE TITLE
Exiting out of (EmuELEC) FlycastSA generates a segfault error.

### ISSUE THREAD

**Issue by Langerz82** [flyinghead/flycast#522]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
EmuELEC 4.3

Github hash: 
4e21391f8cfd481ac1e0ac6b2bf54e0d81f59a1f

Hardware: 
S095M Chip I think

**_Description of the Issue_**
When exiting out of Flycast standalone properly via the menu or with the exit button assigned it generates a false error.

**_Debugging Steps Tested_**
Launch Game
Exit out normally.
Causes a "segfault".

OUTPUT IS:
```
SIGSEGV @ nil -> nil was not in vram, dynacode: 0
```

This is the code affected:
```
	ERROR_LOG(COMMON, "SIGSEGV @ %p -> %p was not in vram, dynacode:%d", (void *)ctx.pc, si->si_addr, dyna_cde);
#ifdef __SWITCH__
	MemoryInfo meminfo;
	u32 pageinfo;
	svcQueryMemory(&meminfo, &pageinfo, (u64)&__start__);
	ERROR_LOG(COMMON, ".text base: %p", (void*)meminfo.addr);
#else
	if (next_segv_handler.sa_sigaction != nullptr)
		next_segv_handler.sa_sigaction(sn, si, segfault_ctx);
	else
#endif // !__SWITCH__
		die("segfault");
```
I have no idea whats raising it but I just added a bit of code to detect nil pointer values and exit normally.
so before that code I added the following check:
```
long int i1 = (long int)((void *)ctx.pc);
long int i2 = (long int) si->si_addr;
if (i1 == i2 && i1 == 0)
  exit(0);
```

**Comment by flyinghead** [comment]
Do you have a way to debug and get a stacktrace?

**Comment by flyinghead** [comment]
Assuming this is solved. Reopen if not.
