### ISSUE TITLE
Flycast Dojo on Android?

### ISSUE THREAD

**Issue by chrisleigh-stack** [flyinghead/flycast#523]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Its there possible Flycast dojo is coming to android there so many powerful device than can emulate this emulator hopefully gonna coming. Keep up the good work

**Comment by vkedwardli** [comment]
Duplicate of https://github.com/blueminder/flycast-dojo/issues/11
