### ISSUE TITLE
Radirgy Noa - Partial Music Support

### ISSUE THREAD

**Issue by QuakedoomNukem** [flyinghead/flycast#527]
Platform / OS / Hardware: Windows 10

Github hash: Flycast 1.2

Hardware: 
CPU: i5-6500
GPU: NVIDIA GTX 1650
RAM: 16GB

Radirgy Noa has a partial music support/working. Intro, Boss and High Score tracks seem to work, but not the stage tracks. I don't know if the final boss tracks and ending work, because of the game having good and bad endings, so I can't see if one works and one doesn't or both work/don't work.

[https://www.youtube.com/watch?v=ziEm0DQSWhY](url)

**Comment by flyinghead** [comment]
This looks like a game bug and it is due to setting the game to Free Play.

Disable `Naomi Free Play` in `Settings > General` then change the coin settings in the BIOS service menu for this game. Then all audio tracks seem to play normally.

**Comment by flyinghead** [comment]
Naomi Free Play is now automatically disabled for this game

**Comment by kihato** [comment]
This bug can be avoided by simply setting 1 credit and then switching to free play in test mode.
However, to automate this, you would need to change to freeplay and rewrite part of the nvmem at the same time, so this may not be the desired method.
If the radirgyn.zip.nvmem file exists, you can rewrite it as follows and it will work. (After setting it to free play)

```
0008: C8 C9
0010: 01
0020: 01
0048: 01
004C: 01
```
Any other value between 0008-00FF must be 0x00.
