### ISSUE TITLE
iOS menu button

### ISSUE THREAD

**Issue by eat-sleep-audi** [flyinghead/flycast#528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
emulator runs great on iOS, however I can only activate the menu to stop emulation while backing out of app, then going back in and "swiping up" continuously on both sides of  virtual gamepad. Non-jailbroken with iOS 15.3. Emulator would be perfect with a swipe down menu option like in DolphiniOS.

**Describe alternatives you've considered**
swipe down option from top of screen to bring up a menu option to close emulation and switch games without having to force close app ( as you may know if non jailbroken, JIT only remains enabled while app stays open in background).
**Additional context**

**Comment by flyinghead** [comment]
You can pause the game and open the menu by pressing UP+DOWN or LEFT+RIGHT on the virtual DPad.

**Comment by eat-sleep-audi** [comment]
Thanks flyinghead! I was confused of why it was working so randomly
sometimes lol keep up the amazing work. I hope to improve my coding.
