### ISSUE TITLE
Cannot run MIL-CD CHD files

### ISSUE THREAD

**Issue by Sanaki** [flyinghead/flycast#529]
Platform / OS / Hardware: 
Linux Mint 19.3 x86_64, libretro core

Github hash: 
3929fe64a3212bf7c8b457482f531bd93bbc5ecb

**_Description of the Issue_**

When loading a chd generated from a Redump-validated MIL-CD dump that runs fine as bin+cue, I get the following error:
`[libretro ERROR] shell/libretro/libretro.cpp:1034 E[BOOT]: chd: track type MODE2_RAW is not supported`

The game used for the test was [Alice Sisters](http://redump.org/disc/87758/). CHD generated using chdman 0.240.

**Comment by flyinghead** [comment]
Support for MIL-CD CHD files should be available in the next build.

**Comment by Sanaki** [comment]
Looks good to me. Thanks!
