### ISSUE TITLE
[Libretro] Ninja Assault, stutter with vulkan

### ISSUE THREAD

**Issue by F0xH0L3** [flyinghead/flycast#530]
Platform / OS / Hardware: Win 10 x64, RTX 3080, I9-10900kf, 32GB Ram

Hi.
Using the latest version of the core (13/02/2022) the inputs for ninja assault seem to be fixed and p2 even works now,
but it seems to have introduce a new issue... stutter.
Specifically it stutters every time you shoot or reload, easy to reproduce just by spamming the trigger or offscreen reload.
Tested on 2 setups,
Win 10 With RTX3080 and I9-10900kf
and Win 7 with HD7850 and I7-7700K (using for crt 15khz).
It happens only when the video driver is Vulkan.
With GL it works just fine.
Basically what's happening is with Vulkan there's no white flash when shooting as opposed to GL driver, so instead there's a hiccup when there's supposed to be a white flash frame.
after using frame advance i was able to see exactly what's happening.
what is supposed to happen is that after pressing the trigger, three frames afterwards there should be a white flash, with GL that is the case and that is how it's supposed to be.
But with vulkan, on the third frame after pressing the trigger, instead of showing the white flash frame it instead goes back to first frame after pressing the trigger, causing the stutter/hiccup.

**Comment by StormedBubbles** [comment]
Hey, I experience a similar issue (#474) with the two Dreamcast versions of Virtua Cop 2. I use a Raspberry Pi 4B with the GL video driver and do not get any stutter at all in Ninja Assault. Do you get that stutter with Virtua Cop 2 if you use Vulkan?

The issue with Virtua Cop 2 has been known since the summer, but I don't think the exact issue causing the stutter was ever identified.

**Comment by flyinghead** [comment]
I was wondering too is the two issues are linked but the Virtua Cop 2 one also happens with Open GL.

**Comment by F0xH0L3** [comment]
Just tried Virtua cop 2 with both Vulkan and GL, same stutter with both video drivers, but it's not the same behavior as ninja assault on vulkan.

**Comment by flyinghead** [comment]
I haven't been able to reproduce this issue with the latest flycast core (2ed4b4a9)
Also there's no white flash frame when shooting in ninja assault. I've tested both OpenGL and Vulkan.

Reopen if this is still an issue.

**Comment by BroKill** [comment]
I can confirm Ninja Assault with latest Flycast core version runs good, no white flash while shooting and no stutter.
Tested with Vulkan render.

GREETs
