### ISSUE TITLE
No BGM V-Rally 2 Expert Edition.

### ISSUE THREAD

**Issue by backgamon** [flyinghead/flycast#534]
Platform / OS / Hardware: 
Flycast stand alone/Windows 10 Pro x64

Github hash: 20571c5

Hardware: 
I9 10850k@4.8/4.9Ghz
Asus Maximus XII Formula
64Go DDR4 GSkill Trident Z 3600Mhz[XMPII]
Gigabyte 2070 RTX 8G OC
Windows 10 Pro x64

**_Description of the Issue_**
No music play on V-Rally 2 ingame, only ambient sound.

**Comment by flyinghead** [comment]
Known issue: https://github.com/libretro/flycast/issues/831
No known fix or work-around

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` branch build.
