### ISSUE TITLE
Unfork Flycast to be able to add it to Homebrew on MacOS

### ISSUE THREAD

**Issue by Depal1** [flyinghead/flycast#542]
**Is your feature request related to a problem? Please describe.**
I aim to add Flycast to Homebrew as a cask. Homebrew requires new casks to be canonical repositories.

**Describe the solution you'd like**
 Therefore I am asking if it would be possible to unfork Flycast from reicast-emulator.

**Describe alternatives you've considered**

**Additional context**
Homebrew is a very popular and stablished app manager for macOS. I am linking the corresponding pull request to the Homebrew casks repository. https://github.com/Homebrew/homebrew-cask/pull/119571

**Comment by flyinghead** [comment]
Repository detached from fork as requested
