### ISSUE TITLE
Missing Typing of the Dead widescreen cheat

### ISSUE THREAD

**Issue by PimpUigi** [flyinghead/flycast#544]
![image](https://user-images.githubusercontent.com/7344271/155522849-56da1501-da3f-4834-abad-ac84147057ea.png)
There's also apparently a cheat out there for MDK 2 widescreen, but I can't find it. RetroArch supposedly applies it to MDK 2 v1.002 (2000)(Interplay)(PAL)(M5) and Redream correctly applies a Widescreen cheat to it as well.

I thought I was just naming my Typing Of The Dead the wrong name or something.
Edit: testing the Widescreen cheat that Redream has for Typing of the Dead just stretches the screen, I guess that code I posted should be tested first cause maybe it's just someone got confused.

**Comment by flyinghead** [comment]
I tried the TotD cheat and it doesn't seem to work.
There's no widescreen cheat for MDK2 in Flycast currently.

**Comment by flyinghead** [comment]
I tried the TotD cheat and it doesn't seem to work.
There's no widescreen cheat for MDK2 in Flycast currently.

**Comment by flyinghead** [comment]
I tried the TotD cheat and it doesn't seem to work.
There's no widescreen cheat for MDK2 in Flycast currently.
