### ISSUE TITLE
There is no video after the dreamcast logo on Moto E5 (XT1920DL)

### ISSUE THREAD

**Issue by Krauser30x** [flyinghead/flycast#547]
![Screenshot_20220226-011814](https://user-images.githubusercontent.com/100462461/155834135-0c5c4134-2517-45d8-acc1-990ef1b3c086.png)

currently on my android system of a moto e5 (XT1920DL) it does not show video and stays with the dark screen and the screenshot shows the game marvel vs capcom 2 on its main logo screen before pressing start There is sound but it is not seen, in another emulator if it is seen and heard but it has not been updated Playing on this emulator is a very good experience and because of this error I can't play as expected

this time i tried it in the house of the dead 2 and including the others none is seen after passing the dreamcast logo

![Screenshot_20220226-012737](https://user-images.githubusercontent.com/100462461/155834384-b67e130a-6103-4136-aa51-d5b268435c72.png)
![Screenshot_20220226-012750](https://user-images.githubusercontent.com/100462461/155834387-a689bd21-9ebc-40f2-a0e2-d511128c6611.png)

If you can solve it I would appreciate it very much since this emulator is very good and I would like to continue using it thank you very much

**Comment by flyinghead** [comment]
Which version of Flycast are you running?
Can you enable Log to File and post the resulting log?

**Comment by Krauser30x** [comment]
![Screenshot_20220226-022342](https://user-images.githubusercontent.com/100462461/155836177-d6e1e054-2d0a-45db-91dd-0a5f327b0190.png)
That's the version I have, I think I had an old version and I looked for the latest version that was uploaded and apparently the video problem was solved but apparently there is a game called resident evil:Code veronica that after selecting a new game the emulator when the narrator comes out telling what happened it comes out by itself and I can't continue

**Comment by inada-s** [comment]
I'm not sure if this issue and the cause are the same.
I've seen in the OpenGL renderer on Windows build that the screen disappears when I resize the window.

![image](https://user-images.githubusercontent.com/1726079/155877846-bfa07e67-e798-4da2-b685-11fb68d1ffb0.png)

**Comment by flyinghead** [comment]
Assuming this is solved. Reopen if not.
