### ISSUE TITLE
Some games Work 30fps not 60fps

### ISSUE THREAD

**Issue by SpeedemoN1** [flyinghead/flycast#548]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: andriod vulkan/opengl3.2 

Github hash: 

Hardware:
PvrGE8320 helio g25 32bits 2gb ram 32gbrom

**_Description of the Issue_**
Some game dont work 60fps so weird redream is 60fps flycast 30fps and reicast 30fps 
and buggy animation in sword of berserk

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Screenshot_2022-02-25-16-44-51-070_com flycast emulator](https://user-images.githubusercontent.com/100472534/155842392-d6377c82-e798-4226-94b6-147ba0fe4fee.jpg)

![Screenshot_2022-02-25-16-41-27-321_io recompiled redream](https://user-images.githubusercontent.com/100472534/155842405-be990051-941b-440a-952f-7197da46ff09.jpg)

(Replace this line with any issue screenshots)

**Comment by stf999** [comment]
Maybe SpeedemoN1 encounters the problem seen here: #479 (30 fps games not smooth, the weak point of Flycast)

**Comment by SpeedemoN1** [comment]
Umm ok i thought the game is 60fps but the game is buggy animation ? Or a hack 60fps cheat?
