### ISSUE TITLE
[Request] Add support for the Analog Stick in the Keyboard

### ISSUE THREAD

**Issue by xZabuzax** [flyinghead/flycast#55]
We are unable to control the ship in "Skies of Arcadia" because the ship can only move with the Analog Stick, unfortunately this isn't working on a keyboard.

**Comment by flyinghead** [comment]
This is fixed in the latest master build

**Comment by xZabuzax** [comment]
> This is fixed in the latest master build

Awesome!, I'll test it up a bit later. Keep up the good work my man.
