### ISSUE TITLE
Maximum Speed networking support

### ISSUE THREAD

**Issue by Hydreigon223** [flyinghead/flycast#552]
Two Atomiswave games, Faster than Speed and Maximum Speed, can link another unit for multiplay. The way they network with another unit differs per game.

- Maximum Speed uses the Dreamcast's serial port as from this link, [](https://dreamcast-talk.com/forum/viewtopic.php?f=74&t=13614&start=50#p159359). Getting this to work (along with the Dreamcast system link feature) would require converting the serial port to a TCP more or less.
- Faster than Speed uses the Dreamcast's BBA and is the only known game to use the BBA for networking offline instead of online. Didn't know that in itself works but can't be networked on the same machine due to both flycast instances sharing the same IP address.

**Comment by flyinghead** [comment]
The latest build on the dev branch supports maxspeed networking.
