### ISSUE TITLE
dev 3a62e432 GLES2 Shader: failed to compile

### ISSUE THREAD

**Issue by unassumingbadger** [flyinghead/flycast#553]
Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz
VGA Kernel driver in use: i915

Branch: dev 3a62e432
option(USE_GLES "Use GLES[3] API" ON)
option(USE_HOST_LIBZIP "Use host libzip" ON)
option(USE_OPENMP "Use OpenMP if available" ON)
option(USE_OPENGL "Use Open GL API" ON)

Flycast dev changes resolution then fails to start.

00:00:195 sdl/sdl.cpp:566 N[RENDERER]: Monitor refresh rate: 60 Hz (1600 x 900)
00:00:233 rend/gui.cpp:256 N[RENDERER]: Screen DPI is 106, size 640 x 480. Scaling by 1.00
00:00:302 rend/gles/gles.cpp:537 N[RENDERER]: Open GLES version 2.0
00:00:405 rend/gles/gles.cpp:562 W[RENDERER]: Shader: failed to compile 
0:90(1): error: illegal use of reserved word `flat'
0:90(1): error: syntax error, unexpected ERROR_TOK, expecting end of file

00:00:406 rend/gles/gles.cpp:613 W[RENDERER]: Shader linking: failed to link 
 (51 bytes), - error: linking with uncompiled/unspecialized shader -
00:00:406 rend/gui.cpp:2577 E[COMMON]: Fatal error : shader compile fail

 in gl_CompileAndLink -> /home/tosh/Build/flycast-dev/core/rend/gles/gles.cpp : 620
Minidump saved to '/tmp/350641b3-f7c9-4937-d70736aa-26557977.dmp'
Trace/breakpoint trap

[350641b3-f7c9-4937-d70736aa-26557977.zip](https://github.com/flyinghead/flycast/files/8155516/350641b3-f7c9-4937-d70736aa-26557977.zip)

**Comment by flyinghead** [comment]
Any reason why you enable GLES?
USE_OPENGL should be enough.

**Comment by unassumingbadger** [comment]
> Any reason why you enable GLES? USE_OPENGL should be enough.

Branch: master e6676c7d
option(USE_HOST_LIBZIP "Use host libzip" ON)
option(USE_OPENMP "Use OpenMP if available" ON)
option(USE_OPENGL "Use Open GL API" ON)

00:00:764 wsi/sdl.cpp:72 E[RENDERER]: Error creating SDL GL context
00:00:764 rend/gui.cpp:2574 E[COMMON]: Fatal error : Cannot initialize the graphics API
 in initRenderApi -> /home/tosh/Build/flycast/core/wsi/switcher.cpp : 78

[106d64b9-51f2-4e25-79693184-30c38091.zip](https://github.com/flyinghead/flycast/files/8155708/106d64b9-51f2-4e25-79693184-30c38091.zip)

The hardware is 1st gen i3 with Intel GPU. I don't think it meets the minimum OpenGL requirements. Current master is happy with OpenGL ES though.

**Comment by flyinghead** [comment]
I see.

The error is due to a new shader used for Naomi 2 games. I'll push a fix as soon as I can test it.

**Comment by flyinghead** [comment]
should be fixed in the last build

**Comment by unassumingbadger** [comment]
I'll let you decide if this should be closed out since the initial issue has been fixed. If you want to leave it open for GLES2 graphical glitches, that's fine too.
