### ISSUE TITLE
Make RetroArch's per_content_vmus variable accessible in standalone App

### ISSUE THREAD

**Issue by GregoireLD** [flyinghead/flycast#555]
Hi,

Maybe I'm missing something here, but after trying to read the code I think the "per_content_vmus" is only accessible in parts of the code loaded from RetroArch.

Do you think it would be a good idea to change the RetroArch-only "per_content_vmus" variable to a global config::PerContentVmus accessible through emu.cfg file ? and later on, using the built-in UI

**Comment by flyinghead** [comment]
Available on the dev branch
