### ISSUE TITLE
Dynamic Golf / Virtua Golf no trackball on RetroArch but works on Windows

### ISSUE THREAD

**Issue by NebularNerd** [flyinghead/flycast#557]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Win 10, Core i7 32GB Ram, GTX 2060
Github hash: 

Hardware: 

**_Description of the Issue_**

As per title, no trackball input with dygolf on Retroarch, cannot see how to set it to accept mouse input (if needed)
Windows standalone accepts mouse as trackball without any issue or setup requirements, just loads and plays.

**_Debugging Steps Tested_**

  * Using latest Retroarch + Flycast plugin
  * Using Win Flycast 1.2
  * dygolf.zip and .chd match MAME 0.261 requirements

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Should be fixed in the next build

**Comment by NebularNerd** [comment]
Awesome 🙂🏌️‍♀️
