### ISSUE TITLE
Borderless fullscreen on windows

### ISSUE THREAD

**Issue by shaanmalik** [flyinghead/flycast#558]
**Is your feature request related to a problem? Please describe.**
There doesn't look like there's any way to go borderless fullscreen/exclusive fullscreen on Windows?

**Describe the solution you'd like**
A keyboard shortcut, command line flag, or config value in `emu.cfg` to run in fullscreen, or borderless fullscreen.

**Describe alternatives you've considered**

You can edit `emu.cfg` and add:
```
[window]
fullscreen = yes
```

This runs the emulator in bordered fullscreen (a window the size of the whole screen).

**Additional context**

Found that you could add a config value to have it run in 'fullscreen' (bordered), which makes me assume there's no way to enable a fullscreen mode via the GUI.
https://github.com/flyinghead/flycast/issues/196

**Comment by flyinghead** [comment]
Flycast doesn't support exclusive fullscreen but it does support borderless fullscreen.
Borderless fullscreen is enabled by pressing Alt+Enter or setting `fullscreen = yes` in emu.cfg.

**Comment by sboukortt** [comment]
A UI setting for this would be useful. I couldn’t find one, but maybe I just didn’t look properly?

**Comment by TradeDraft** [comment]
I also like to see this Option Added to Flycast
