### ISSUE TITLE
Naomi Hotd2 not loading

### ISSUE THREAD

**Issue by Somechump** [flyinghead/flycast#560]
Platform / OS / Hardware: Windows 10

Github hash. 1f61f80

Trying to load Naomi House of the dead 2 results in the loading screen followed by black screen. 
Sometimes the game screen will flash up momentarily for less than a second before crashing to black screen.

**Comment by flyinghead** [comment]
hotd2 should work fine. Your rom or BIOS might be corrupted. Do you have both hotd2.zip and hod2bios.zip?
Do other Naomi games work?

**Comment by Somechump** [comment]
You are correct. Tried a different rom and bios and it loaded.
