### ISSUE TITLE
[Build Error][error=array-bounds]EmuELEC

### ISSUE THREAD

**Issue by Langerz82** [flyinghead/flycast#561]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
EmuELEC 4.4 (dev latest) / Linux Kernel (amlogic-4.9-19)

Github hash: 
Flycast Standalone,
Commit: e6676c7d090fda457cf3a452d3cbf150eb74773f

Hardware: 
Beelink GT-King Pro (Android smart TV box)

**_Description of the Issue_**
Build Compile Error:
```
/EE-joycommon-fix/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycastsa-e6676c7d090fda457cf3a452d3cbf150eb74773f/core/deps/breakpad/src/common/string_conversion.cc:104:16: error: array subscript 2 is outside array bounds of 'wchar_t [1]' [-Werror=array-bounds]
  104 |   const UTF32* source_end_ptr = source_ptr + 1;
      |                ^~~~~~~~~~~~~~
```

Using that commit and later generates the above error. Using:
export CXXFLAGS="${CXXFLAGS} -O1 "
on the pre-build flags the error is bypassed and it compiles ok. The build runs games fine from what I've tested.

**Comment by flyinghead** [comment]
I guess breakpad is being built with the `-Werror` or `-Werror=array-bounds` gcc option or something similar, which treats warnings as errors.

**Comment by Langerz82** [comment]
Ah ok cool, just thought Id mention it, in case it was a bug. I used " -Wno-error=array-bounds" in CXXFLAGS instead of -O1 and it compiles fine.

**Comment by Langerz82** [comment]
Hey, there is another issue, not sure if you are aware of it or not. In libretro build when you go to the retroarch menu, if you try to resume it does a hard freeze in EmuELEC and you cannot exit.
I looked around on the net and if you disable threaded rendering it should not have this issue.

**Comment by Langerz82** [comment]
hey, I tested with a different emulator and it has the same issue. Looks like its not reicast and is something else, apologies.

**Comment by Kelvfimer** [comment]
@Langerz82 pls how do you fix it? pls,Can you detail how to fix it? I'm getting same error.

**Comment by Langerz82** [comment]
Hello,
I solved it by updating to the latest flycast and by deleting the retroarch.cfg file, and opening retroarch again so it auto generates the a new config file.

**Comment by Kelvfimer** [comment]
Not for me, it gets hung... :( I will roll back to previous version
