### ISSUE TITLE
Vertex explosions on intel mesa vulkan

### ISSUE THREAD

**Issue by toccata10** [flyinghead/flycast#575]
Mesa 22.0 on Intel N4200 (HD Graphics 505 Gpu), Archlinux.
I have a few vertex explosions with Vulkan (see screenshot). With openGl, it's perfect. Changing internal resolution doesn't change anything.
I tried the flycast's flatpak version and the libretro version: same behaviour.
Games tested (console versions): Marvel vs Capcom 2 (ntsc) and Dead Or Alive 2 (ntsc).
I don't know what kind of log would be useful to you.
![Marvel vs  Capcom 2 v1 001 (2000)(Capcom)(NTSC)(US) ! -220330-154420](https://user-images.githubusercontent.com/7478580/161341605-7c76f57a-c75e-4f0f-accc-f8fcc549f875.png)
On another computer with Amd, vulkan renders perfectly.

**Comment by flyinghead** [comment]
It's likely a GPU driver bug, or a hardware bug. The best is probably to use OpenGL instead of Vulkan, especially with Intel GPUs.

**Comment by toccata10** [comment]
I opened an issue on mesa:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6250
