### ISSUE TITLE
[libretro] street fighter zero3 Graphical has vertical stripe

### ISSUE THREAD

**Issue by XieTieqiang** [flyinghead/flycast#580]
[libretro] street fighter zero3 Graphical has vertical stripe

Sega Dreamcast           Street Fighter Zero 3 - Saikyo-ryu Dojo for Matching Service (Japan)
Sega Naomi GD-ROM  Street Fighter Zero 3 Upper (Japan)(GDL-0002)

**Comment by Immersion95** [comment]
Every 2d games have stripes at any resolution in Vulkan/libretro. I had to switch to d3d11 for the meantime.

**Comment by Immersion95** [comment]
Could you please help with this issue, all 2d games are broken and it is unplayable.

![IMG_2022-04-08-22-26-08-617](https://user-images.githubusercontent.com/47425204/162525384-e0a21da2-e665-4b07-8985-9216e7810b8f.jpg)

The commits from April, 1st are responsible for that. Fortunately d3d11 isn't affected.

**Comment by XieTieqiang** [comment]
Disable Anisotropic Filtering and Texture Filtering

**Comment by flyinghead** [comment]
Are you forcing Texture Filtering to Linear?

**Comment by XieTieqiang** [comment]
![{%6 X@C(} 93I6GD7U1QUX](https://user-images.githubusercontent.com/95056895/162595331-d87a38fd-125a-438c-9b74-817de6dcf390.png)

**Comment by flyinghead** [comment]
Don't use Force Linear or you'll get these bad results.

**Comment by Immersion95** [comment]
It works if Anisotropic is off. Is it intended ? It was working great before and also works correctly with d3d11 with 4x.

**Comment by flyinghead** [comment]
Yes, a bug has been introduced in the vulkan renderer that uses anisotropic filtering for nearest-neighbour samplers. Disabling anisotropic filtering and restarting should work-around the issue for now. This doesn't affect open gl or dx11.
