### ISSUE TITLE
Vertical arcade games rendering outside the window

### ISSUE THREAD

**Issue by pjagiello** [flyinghead/flycast#584]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Linux

Github hash: 20302cd3

Hardware: n/a

**_Description of the Issue_**

NAOMI games in vertical mode don't fit inside the window/rendering area if it's too narrow. Attached a sample screenshot from one of the first screens in Under Defeat but this presumably happens to any vertical game.

What I would expect is black bars at the top and the bottom, instead it seems like the rendering area spans from top to bottom but the sides are cut off.

Screenshot is just a very pronounced example, but a realistic scenario when this happens is e.g. fullscreen on a 16:9 display in portrait mode.

**_Screenshots_**

![2022-04-08-21:00:30-screenshot](https://user-images.githubusercontent.com/8558288/162508083-4961fb11-fa51-4500-9518-d627a43d0b3a.png)

**Comment by pjagiello** [comment]
Well, maybe worth pointing out it's not actually specific to vertical games (here's Metal Slug 6 as an example), it's just not very likely someone will want to play these games like this - vertical games are just a realistic use case.
![2022-04-08-21:23:52-screenshot](https://user-images.githubusercontent.com/8558288/162510610-adfac05f-f5a2-4939-87dd-8d310d244f1d.png)

**Comment by flyinghead** [comment]
Should be fixed in the last `dev` branch build

**Comment by pjagiello** [comment]
Thanks! Just tried it out and it indeed works like I would expect now.
