### ISSUE TITLE
Dreamcast running on Naomi [Libretro]

### ISSUE THREAD

**Issue by LasagnaPie** [flyinghead/flycast#589]
Hardware - Xbox Series X
Game - Sonic Adventure
Core version - 20302cd

Whenever i attempt to run a Dreamcast GDI, the Naomi bios shows up "This game is not acceptable by main board".   Even though Retroarch lists it as a Dreamcast game. 

![16495969112447108712388102177706](https://user-images.githubusercontent.com/7449866/162620223-44889304-a9c7-485e-8448-7919fe7b77a5.jpg)

**Comment by flyinghead** [comment]
Something is really wrong with your installation. Sonic Adventure is a dreamcast game, not a Naomi one.
Have you renamed the BIOS file or something like that?

I recommend a fresh install.

**Comment by LasagnaPie** [comment]
I figured it out, it assumes .bin files are Naomi roms.  there is only 'track01.bin track02.raw track03.bin'. 

I originally had the game in the Retroarch folder which worked, then moved to the Flycast Xbox app folder then into Retroarch folder again.  For whatever reason the .gdi file disappeared.

**Comment by LasagnaPie** [comment]
It would be highly beneficial if a new file format specifically for Dreamcast games was developed, for example Powerstone.sdc.  Always have issues with CDI and CHD and there is limited allocated space on Xbox.
