### ISSUE TITLE
18 Wheel American Trucker - Gears

### ISSUE THREAD

**Issue by Riddler1** [flyinghead/flycast#591]
Hi all,

i found that when changing the Hi/Low gears, they seem to switch back on the "key up" event. This means you have to keep the button pressed to stay in the next chosen gear. I think the Reverse gear is also affected. 

This issue occurs on both keyboard and direct input controller mappings.

I tested this with the lastest Windows 1.3 and 1.2 master versions and also on the latest dev build.

if this is already known please close or cancel this post.

**Comment by flyinghead** [comment]
The original arcade game uses a 3-state lever as gear selector, which stays in position unlike gamepad buttons.
So yes, this is known and working as designed.
![image](https://user-images.githubusercontent.com/16261910/163145814-e99a038c-aa00-40ad-99dc-aabfa12bb9e4.png)

**Comment by Riddler1** [comment]
great, yes that makes sense. So this rules out playing the game with any common control pad. Even my racing wheel gear sticks have a double press event. I can't think of many controllers it would work with.
i even tried mapping it by holding the gear stick in then mapping it and releasing the gear stick again so it maps against the key release but that doesn't work. 

seems it needs a single switch controller.
Thanks for confirming 👍

**Comment by flyinghead** [comment]
Fixed on master. See #693

**Comment by mmarino4** [comment]
Is there a way to have an option for the old way the gears were handled? If you are using a fixed position shifter, it doesn't work correctly with the change made.
