### ISSUE TITLE
Sega Dreamcast Street Fighter III - 3rd Strike - Fight for the Future (Japan) screen position adjust invalid

### ISSUE THREAD

**Issue by XieTieqiang** [flyinghead/flycast#594]
Sega Dreamcast Street Fighter III - 3rd Strike - Fight for the Future (Japan) screen position adjust invalid

**Comment by Immersion95** [comment]
Hold Start + Y before the Capcom Logo and the game will launch in 240p mode correctly centered. You have to be on TV (composite) and not VGA.

**Comment by benjis8888** [comment]
It affects quite a few games, I'll try and compile a list, San Francisco Rush 2049 is another one:

![SAVE_20230223_112911](https://user-images.githubusercontent.com/126162906/221572729-c8e080db-1b99-423a-a6e2-b5a98e00d915.jpg)
![SAVE_20230223_112905](https://user-images.githubusercontent.com/126162906/221572743-de026688-0cb4-4fc0-8464-f55d3952698a.jpg)

**Comment by benjis8888** [comment]
> Hold Start + Y before the Capcom Logo and the game will launch in 240p mode correctly centered. You have to be on TV (composite) and not VGA.
> 
> Unfortunately a lot of Capcom 2d games have black borders on Flycast. It would be great if there were a way to have full scaling.

It is still not centred correctly when you launch in 240p, it has a much bigger border at the bottom and a small border on the right too

**Comment by flyinghead** [comment]
Naomi Street Fighter Zero 3 Upper is another one

**Comment by flyinghead** [comment]
Other game affected:
Street Fighter III - 3rd Strike (US)

Games that have a Screen Center option:
Street Fighter Alpha 3 (US)
Street Fighter III (US)
Street Fighter III - 2nd Impact (US)
Street Fighter III - 3rd Strike
Street Fighter Zero 3 (JP)
Super Street Fighter IIX for Matching Service (JP)
Metropolis Street Racer
San Francisco Rush 2049

**Comment by benjis8888** [comment]
> This should be fixed on the dev branch

Well done 👏🏻
When will this arrive in Retroarch do you know?
