### ISSUE TITLE
How do I save my progress in a game?

### ISSUE THREAD

**Issue by mrwallace888** [flyinghead/flycast#596]
I was playing Vanishing Point and unlocked a few cars and tracks. After restarting the emulator, however, my progress was lost. Does Flycast save your progress, and how can I do this?

**Comment by cinnamonmatexfce** [comment]
You can save Dreamcast games inside VMU. Or you can Save/Load states via Flycast.

**Comment by mrwallace888** [comment]
What is VMU?

**Comment by bslenul** [comment]
"Visual Memory Unit", the Dreamcast memory card. As often in old games the auto-save feature is disabled in the game options so make sure to save manually in-game before exiting the game, or enable the auto-save option in-game.
