### ISSUE TITLE
[macOS] Release 1.3 can't be opened

### ISSUE THREAD

**Issue by shinra-electric** [flyinghead/flycast#597]
Platform / OS / Hardware: 
macOS / Monterey 12.3.1 / M1

**_Description of the Issue_**

Release 1.3 can't be opened

**_Screenshots_**

![Screenshot 2022-04-16 at 11 27 25](https://user-images.githubusercontent.com/50119606/163671547-b9eb81d8-29a1-4d58-bac4-ce9feb339667.png)

This is likely a codesigning issue. 

Note that release 1.2 works fine.

**Comment by shinra-electric** [comment]
I have tried self-signing with `codesign --force --deep --sign - ` and cleared the extended attributes with `xattr -cr ` but neither of these steps helped. (So the issue might not be codesigning related).

**Comment by flyinghead** [comment]
It appears to be a permission issue on the executable. I have updated the v1.3 binary download for macOS. Could you download it again and test it?

**Comment by shinra-electric** [comment]
Yes, it is working now. 

Closing issue, thanks.
