### ISSUE TITLE
vf4cart this game is not acceptable by main borad.

### ISSUE THREAD

**Issue by XieTieqiang** [flyinghead/flycast#600]
vf4cart this game is not acceptable by main borad.
 d732140 Commit
![ede6c4d295b1968a28f409f26af216a](https://user-images.githubusercontent.com/95056895/163677230-9e16bb6f-e01f-4a0e-96dd-13c0455685b7.png)

**Comment by flyinghead** [comment]
This is probably a consequence of your naomi2 BIOS being too old, and missing the US BIOS that Flycast uses. Get a newer BIOS file or set Region to Japan or Europe.

**Comment by Tasosgemah** [comment]
> This is probably a consequence of your naomi2 BIOS being too old, and missing the US BIOS that Flycast uses. Get a newer BIOS file or set Region to Japan or Europe.

I had a similar issue with Virtua Striker 3 and i fixed it by changing the region to "Europe" in the core options.

Could the emulator detect the correct regional settings automatically?

**Comment by flyinghead** [comment]
> This is probably a consequence of your naomi2 BIOS being too old, and missing the US BIOS that Flycast uses. Get a newer BIOS file or set Region to Japan or Europe.

Flycast detects the correct region, except when it cannot find it. Although this has also been fixed recently. But the message remains: *your BIOS is too old*
