### ISSUE TITLE
Add built in cheats for Dreamcast Games

### ISSUE THREAD

**Issue by chrisleigh-stack** [flyinghead/flycast#601]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add built in cheats we don't need to add cuz it's hard to find cheats.

**Describe alternatives you've considered**

**Additional context**

**Comment by blueminder** [comment]
FWIW, you can find Dreamcast cheats here: https://github.com/libretro/libretro-database/tree/master/cht/Sega%20-%20Dreamcast

**Comment by chrisleigh-stack** [comment]
Sorry didn't work

**Comment by ani917** [comment]
[CodeBreaker all cheats save file 2.6.zip](https://github.com/user-attachments/files/21131329/CodeBreaker.all.cheats.save.file.2.6.zip)
cheats work from the file "fcdcheats (openMenu).txt"

**Comment by antipirgos** [comment]
> FWIW, you can find Dreamcast cheats here: https://github.com/libretro/libretro-database/tree/master/cht/Sega%20-%20Dreamcast

No Head Hunter Flycast cheats 😢
