### ISSUE TITLE
Wild Riders - Input issue ?

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#602]
Hi,

With a pad and the default configuration, the right stick is used for Rear Brake (- / +) which means you have to keep the stick on the left and use the right trigger (Accelerator) to accelerate (because the value is at 80 instead of 00, which prevents acceleration).

On the cabinet, Rear Brake is a pedal, so it should work like the Accelerator or the Front Brake, no ?

Config : Windows 10, Libretro

**Comment by flyinghead** [comment]
The problem is SDL, and most input APIs, only support 2 triggers (half axis).

**Comment by dukeblooders** [comment]
An idea of workaround would be to invert Rear Brake (full>half) and Accelerator (half>full).
Since we have to accelerate anyway, we just have to push the right stick in the good direction and the triggers are used to brake.

But I don't know if it's possible without breaking other input devices.

**Comment by superblobster** [comment]
> An idea of workaround would be to invert Rear Brake (full>half) and Accelerator (half>full). Since we have to accelerate anyway, we just have to push the right stick in the good direction and the triggers are used to brake.
> 
> But I don't know if it's possible without breaking other input devices.

Unbind your rear brake inputs in the emulator.
Then go into Service Mode and select Game Test Mode.
Select Volume Adjustments. This option is oddly named, because it is in fact Input Calibration.
Calibrate all inputs except Rear Brake which should say 80H for min, max and neutral.
It should now be off all the time without having to hold the stick.
There is no reason to use the rear brake in this game, at least I haven't found one. The front brake does the job.

**Comment by dukeblooders** [comment]
>Then go into Service Mode and select Game Test Mode. Select Volume Adjustments. This option is oddly named, because it is in fact Input Calibration. Calibrate all inputs except Rear Brake which should say 80H for min, max and neutral.

Yes, that's totally does the job !
I think Rear Brake is useful to negotiate the turns, but I let people judge its usefulness. Anyway, thanks.

**Comment by ConversusW-Vans** [comment]
Yeah I was having the same problem.  There IS a workaround to mapping the rear brake, and personally, I think it is essential for the turns and skipping the tutorials. My solution is using X360CE and I map my gas pedal for one of the triggers and then map the brake pedal to just a single directional axis. It is easy to use. Then map your brake pedal axis to the rear brake and it should now play perfectly fine.  If you use just the triggers the brake will just stay centered.

(Circled inputs from top to bottom; gas and brakes)
![My mapping for Flycast](https://user-images.githubusercontent.com/65821346/174682233-434ab77b-1e75-440b-a962-32ccd0572f78.PNG)

FYI, I'm using an Ultimarc A-PAC (an encoder for arcade cabinets) with pots-based console steering wheels, plus a Harley-Davidson LA Riders handlebar setup wired to a DB15 connector. Use on both my Model 3 boards and my PC; works like a chocolate ice cream cone.

**Comment by superblobster** [comment]
> I think it is essential for the turns

No it isn't. I've mastered the game and have not once needed the rear brake. It's only useful for skipping the tutorials which you can just ignore.
Besides, if you're braking a lot in this game you're playing it wrong. You have to go fast :)
