### ISSUE TITLE
0x7fb7d504a083 was not in vram, dynacode

### ISSUE THREAD

**Issue by telanus** [flyinghead/flycast#603]
Platform / OS / Hardware: 
Linux 64bit. Kubuntu 20.04.4 i3-2100 GT630 using RetroArch 1.10.3 (Git da5d135a9f)

Github hash: 
https://github.com/libretro/flycast/commit/4c293f306bc16a265c2d768af5d0cea138426054

**_Description of the Issue_**

When playing the first selectable option, once you beat the Skyline, Flycast (using the retroarch core), retroarch will crash. I was using the Subaru WRX with this shader (my own compilation) https://pastebin.com/0G3LqGRG

**_Logs Gathered_**

```

[libretro ERROR] core/linux/common.cpp:70 E[COMMON]: SIGSEGV @ 0x7fb82c1d96db -> 0x7fb7d504a083 was not in vram, dynacode:0
[libretro ERROR] Fatal error : segfault
 in fault_handler -> /builds/libretro/flycast-upstream/core/linux/common.cpp : 81
[libretro ERROR] shell/libretro/libretro.cpp:2935 E[COMMON]: DEBUGBREAK!
Illegal instruction (core dumped)


```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Which game is this?
What renderer are you using?
Does the crash happen without any shader and with default settings?

**Comment by telanus** [comment]
> Which game is this? 

initdv2j - Initial D Arcade Stage Ver. 2

>What renderer are you using? 

GL

>Does the crash happen without any shader and with default settings?

I'll try after work :D

**Comment by telanus** [comment]
Update: 

Played without the shader, and no crash. So me think me close bug.
