### ISSUE TITLE
Support higher horizontal stretch values for super-resolution (output to CRT)

### ISSUE THREAD

**Issue by njz3** [flyinghead/flycast#609]
There is a known technique called "super-resolution" that can be used to output 240p vertical lines (low-res 15khz), 384p (med-res 24khz) or 480p (hi-res 31khz) analog signals with modern graphics adapter such as NVIDIA, AMD or intel. The analog signals will then be sent to an old CRT monitor supporting only those vertical frequencies to display the final picture. 
This is what is used with GroovyMAME or retroarch for example to output CRT compatible signals.
In this case, the image is volontary distorded with an horizontal strecht to fit a screen such as 2048x240p or 2560x240p that is converted to analog signal for monitor in 4/3 aspect ratio.
The current horizontal stretch parameter that can be tuned between 100 and 150 (change x1.5), can it be possible to extend it? Or have a "full-screen" fit/stretch option that does not maintain a fixed aspect ratio?

**Comment by njz3** [comment]
Ok, I finally tested with latest flycast dev branch, on a 1280x240p screen resolution with a stretch parameter of 200 or 400, and found an issue with F355 (twin) rom :
1) when using windowed mode the stretch is correctly applied horizontally.
2) when I go fullscreeen with Alt+Enter, the stretch goes vertically !
3) I then tested with 50 (in case it would half the vertically), but no it halfs the horizontal again ...
Seems like there is something wrong when going fullscreen.

**Comment by njz3** [comment]
As a complement : I use 2 monitor, one regular LCD with standard aspect ratio, and one is a CRT using 1280x240p resolution (4:1 aspect ratio).
I noticed that if I move the window back to the regulare monitor, then image becomes stretch again horizontally.
So I guess it is something related to the aspect ratio of the monitor when going full screen.

**Comment by flyinghead** [comment]
It looks like it could be using the aspect ratio/resolution of the wrong monitor when doing the stretching.
Can you post some log?

**Comment by flyinghead** [comment]
The UI now allows horizontal stretching up to 250%
