### ISSUE TITLE
[Libretro] Ninja Assault: reloading fails after gun calibration

### ISSUE THREAD

**Issue by StormedBubbles** [flyinghead/flycast#610]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: RetroPie with RetroArch 1.9.14

Github hash: 15ca7e82bd0b6c9ef5e100541dddbf6435e906a1

Hardware: Raspberry Pi 4B

**_Description of the Issue_**

Delete any existing Ninja Assault nvmem and eeprom files. Lightgun inputs work (including reloading), but shots are offset from the cursor. Go to service menu and calibrate. Once you re-enter the game, reloading no longer works.

**_Debugging Steps Tested_**

  * Deleted configuration files associated with the game
  * Tried calibration multiple times
  * Shared nvmem and eeprom files with friend who also experiences the same issue
  * Made sure emulator is up to date

**Comment by StormedBubbles** [comment]
Just for some more detail:

Some of the NAOMI lightgun games (e.g., Lupin III) have calibration screens with targets at the top, left, right, bottom, and center of the screen. The targets on the sides of the screen are touching the edge of the screen.

It is very easy to mistakenly calibrate one of the non-center targets to "00," which is the Flycast reload zone. If that happens for a particular side, then onscreen shooting and offscreen shooting get mixed up on that side of the screen. 

Unfortunately, Ninja Assault's calibration screen isn't set up the same way. It just has two targets that are not close to the edges of the screen, so that particular user error doesn't appear to be the issue here. What I did was turn on the Flycast cursors and use standard mice to align the cursors as closely as possible to the centers of the calibration targets. This led to near-perfect alignment between the Flycast cursors and the in-game cursors. However, for some reason, reload gets lost in the process.

**Comment by Widge-5** [comment]
I am having the same issue.   This is what I find:

- Calibrating p1 gun causes the issue
- Only p1 is affected, p2 is unaffected.
- After calibration of p1, the p1 gun can no longer reload and  p1 start cannot skip cutscenes.
- No other service menu options appear to cause any issues.
- The problem can be resolved by deleting the nvmem and eeprom files, restoring all service options to default, this means it is not possible to play with p1 gun calibrated.

**Comment by flyinghead** [comment]
RetroArch is supposed to tell the core when the lightgun is off screen. Unfortunately it doesn't seem to work.

First, moving the mouse quickly outside the window will not be reported as off screen. In fact the lightgun coordinates stay the same until the cursor moves back into the window.

Off screen seems to only be reported when the x or y coordinate of the lightgun is precisely 0 or max (639/479), which are valid coordinates.

**Comment by Widge-5** [comment]
The might make more sense if both players were affected in the same way.  But only player 1 has the issue.

**Comment by flyinghead** [comment]
I have no explanation as to why P1 and P2 lightguns would behave differently. All players input are treated in exactly the same way in the core.

I'll investigate possible solutions (like avoiding 0 and max values for x and y when shooting). Bypassing the game calibration is another possibility but it requires per-game settings/hacks, which adds a lot of complexity.

**Comment by StormedBubbles** [comment]
@Widge-5 's experience may be different, but I just checked again on my end and found that BOTH players lose the ability to reload in Ninja Assault after calibrating in the service menu in the Libretro version of Flycast.

The standalone Windows Flycast did not exhibit this issue for me when I tested with 1 player in both windowed and fullscreen modes. 

It is strange that reload is affected after calibration with this game. This game's calibration menu doesn't force you to shoot anywhere near the edges of the screen. 

Can anyone else using Libretro Flycast on a non-Pi platform confirm this issue?



Aside:
I noticed that the Windows standalone Flycast allows the lightgun cursor to travel into the blank space surrounding the game, even in fullscreen mode. Perhaps, in the Libretro version, the game screen could be shrunk a single length unit on all 4 sides, with the lost space still accessible to the lightgun cursor as an out-of-bounds region.

**Comment by flyinghead** [comment]
Standalone Flycast does allow the lightgun coordinates to do beyond the limits of the screen or window. This is done to ease offscreen reloading. Unfortunately this isn't possible with RA and rescaling coordinates would make the mouse cursor and its actual location differ.

Flycast was previously scaling lightgun coordinates for Ninja Assault so that it would work more or less out of the box (without forcing users to do a calibration in the game test menu). But it looks like this wasn't a good idea. After removing this scaling, and recalibrating, the problem doesn't seem to happen anymore.

This change should be in the next core build. Let me know if it fixes the issue.

**Comment by StormedBubbles** [comment]
Thank you! The issue does appear to be resolved.

I understand with the lightgun coordinates. I have seen that functionality from Libretro grow over the years, so maybe some development in the future will help with the offscreen stuff.
