### ISSUE TITLE
Resident Evil - Code Veronica. Sometimes cropped textures

### ISSUE THREAD

**Issue by anzipex** [flyinghead/flycast#611]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: PC / Windows 7 (x64)

Github hash:  3d5fd61

Hardware: Intel Core i5-4690; NVIDIA GeForce GTX 750 Ti; 24 GB RAM

**_Description of the Issue_**

Resident Evil - Code Veronica (USA) Disc 2. The texture on the right picture is not fully displayed. It should be fully visible: https://youtu.be/4hRf9i7V0Y0?t=2539

**_Debugging Steps Tested_**

  * Tried to run Flycast (v1.3) on default settings, still see only half of texture
  * Tried to use every graphics API (OpenGL, Vulkan, DirectX 9, DirectX 11), still see only half of texture
  * On disc 1 I've seen 2-3 textures with same problem: visible triangle left-bottom and not visible part top-right

**_VMU Save_**

[vmu_save_A1.zip](https://github.com/flyinghead/flycast/files/8575584/vmu_save_A1.zip)

**_Screenshots_**

![bug](https://user-images.githubusercontent.com/13317644/165595549-ac5febb5-d684-4884-81c0-73b1095e62bf.png)

**Comment by flyinghead** [comment]
Thank you for this detailed bug report. I wish they were all like that!

Are you using per-pixel transparent sorting? If not, can you try it?

**Comment by anzipex** [comment]
Per-Strip - texture fully displayed
Per-Triangle - cropped texture displayed
Per-Pixel - texture fully displayed

**Comment by flyinghead** [comment]
Per-pixel is the most accurate render mode and should be identical to the original hardware. However per-strip and per-triangle are approximations and visual glitches are expected. Per-triangle usually performs better overall, but per-strip can be better for some scenes.

Use per-pixel if you want the best accuracy.
