### ISSUE TITLE
Stopping game in map

### ISSUE THREAD

**Issue by Gazambor** [flyinghead/flycast#613]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: android

Github hash: 

Hardware: Snapdragon 845

**_Description of the Issue_**

Add a short, concise description of the issue here : when i pressed x button the game has been stopped

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)
![Screenshot_2022-04-29-18-01-51-274_com flycast emulator](https://user-images.githubusercontent.com/101413570/165954655-5d7bf9c0-94e9-43a9-b180-848c6586bafd.jpg)

**Comment by flyinghead** [comment]
no answer
