### ISSUE TITLE
broken smoke in Panzer Front

### ISSUE THREAD

**Issue by superblobster** [flyinghead/flycast#616]
Platform / OS / Hardware:  Windows 10, 3570k, 1060 gtx.
Version: 1.3.90
Git hash: 77a2bbbb

In per pixel mode, thick black smoke is rendered around tank while driving.
There should be thin white smoke instead.
Per triangle corrects the smoke, but removes shadows and track marks.
Other settings don't seem to matter.
This happens in both standalone Flycast and with the Retroarch core.
As a side note, this bug is not present in Redream.

Flycast:
![flycast_2022_05_01_09_42_19_015](https://user-images.githubusercontent.com/60817163/166135815-a22a530e-7426-4e75-bc2b-4ffc98932825.png)

Real hardware:
![Screenshot 2022-05-01 094638](https://user-images.githubusercontent.com/60817163/166135825-508929bc-9e46-4510-9c0d-5eec3829f519.png)

**Comment by flyinghead** [comment]
Should be fixed in the latest build.

**Comment by superblobster** [comment]
Can confirm, problem is fixed now.
