### ISSUE TITLE
[DX11] Tony Hawk 2 - Per-Pixel issues

### ISSUE THREAD

**Issue by LasagnaPie** [flyinghead/flycast#618]
Retroarch 1.10
Flycast (v1.3)
Xbox Series X

On the Hanger level, the glass in the middle of the level disappears and also the glow around letters when using Per-Pixel Alpha Sorting.

Per-Strip (fast, least accurate)
![97f6edde-43e0-49a3-b302-4cdaa50eb2c2](https://user-images.githubusercontent.com/7449866/166408529-d1ba3c2a-9a32-4510-84a7-d65b16e6d078.png)
![70f0ac92-1ee8-4de6-9a0f-a6bd7f13f0cd](https://user-images.githubusercontent.com/7449866/166409204-8f06cf9f-8deb-477d-9f05-7ab4061d1331.png)

Per-Pixel (accurate, but slowest)  
![f52cfad9-3dbf-49aa-9a0a-dc26972f657b](https://user-images.githubusercontent.com/7449866/166408598-d5705f75-4c5f-42ef-89b8-f4a09c95570d.png)
![3abacfce-7ca1-4d0d-84ec-4efba038cc37](https://user-images.githubusercontent.com/7449866/166409289-fb965e5f-3a7b-40dd-a2c0-fa01336ddf8c.png)

**Comment by flyinghead** [comment]
Should be fixed in the next build.
