### ISSUE TITLE
Soldier of Fortune - texture issue

### ISSUE THREAD

**Issue by LasagnaPie** [flyinghead/flycast#620]
Flycast v1.3
Xbox Series X

The textures on the walls distort and flicker as you move around the level.  None of the video settings makes a difference. 

![48521bc8-1d4a-4141-8630-7f4427547849 (1)](https://user-images.githubusercontent.com/7449866/166516395-0816df4d-4003-4823-8a7d-75e470c1c5aa.png)
![43d3cc54-d653-416a-b89c-f75c4b9bb43e](https://user-images.githubusercontent.com/7449866/166515670-e30b4327-71df-4cfb-936c-c27758efe709.png)

**Comment by flyinghead** [comment]
Same AMD issue as #570
