### ISSUE TITLE
Cheat issue with Dreamcast using.cht files

### ISSUE THREAD

**Issue by chrisleigh-stack** [flyinghead/flycast#621]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)
Game cheats doesn't work using custom .cht for Dreamcast on Flycast android

**Comment by flyinghead** [comment]
Please post the .cht file and the name of the game it is used for.

**Comment by flyinghead** [comment]
no answer
