### ISSUE TITLE
Blue Stinger graphical issue with Per Pixel sorting.

### ISSUE THREAD

**Issue by superblobster** [flyinghead/flycast#622]
Platform / OS / Hardware: Hardware: Windows 10, 3570k, 1060 gtx
Github hash: a0d1dbf8 (standalone)

With Per Pixel sorting, smoke is being rendered through the headlight at the beginning of the game.
Does not occur with Per Strip or Triangle.

Flycast:
![flycast_2022_05_05_07_46_11_884](https://user-images.githubusercontent.com/60817163/166872046-4463197a-f221-49d7-aed6-e067b7a54510.png)

![flycast_2022_05_05_07_46_10_676](https://user-images.githubusercontent.com/60817163/166872048-53e18a76-b930-4829-8b38-bb49b69e6313.png)

Real:
![Screenshot 2022-05-05 091803](https://user-images.githubusercontent.com/60817163/166872070-1904311e-86d7-4912-b118-f71c6feefff6.png)

![Screenshot 2022-05-05 091829](https://user-images.githubusercontent.com/60817163/166872069-44c367bf-2f9c-4a22-afbd-e38bc969362f.png)

**Comment by flyinghead** [comment]
This is due to the number of transparent layers in this region exceeding 32, which is the current limit in Flycast. At 64 layers, there is still a minor glitch at the center of the spotlight. 80 fixes it completely.

I could make the number of layers configurable.

**Comment by superblobster** [comment]
I suppose it would be useful for the few games that might need it, for the sake of accuracy, though I'm not against playing in Per Strip mode.

**Comment by flyinghead** [comment]
The same issue happens with ECCO the dolphin:
![image](https://user-images.githubusercontent.com/16261910/166880809-390180b7-c498-45ba-b94b-fbba513b2a65.png)

**Comment by superblobster** [comment]
Come to think of it, I think I spotted the same thing in Panzer Front, although it's more obvious in motion:

![flycast_2022_05_05_10_48_26_122](https://user-images.githubusercontent.com/60817163/166882910-5b837995-0ebb-4dc4-ab27-58dbc818d508.png)

**Comment by flyinghead** [comment]
New option available in last build:
![image](https://user-images.githubusercontent.com/16261910/166968672-74201428-6dc3-43e2-9c82-a0e40641b5e0.png)

**Comment by superblobster** [comment]
Works nicely. 64 layers does the trick for Panzer Front, 80 for Blue Stinger.
