### ISSUE TITLE
Dead or Alive 2: Limited Edition (JP) - display error when using Widescreen Cheat

### ISSUE THREAD

**Issue by rdeleonp** [flyinghead/flycast#625]
Platform / OS / Hardware: x64 / Windows 10 / 6700K + RX 480

Github hash: 6c6b447ea1d2d251e5f7b96d57b0e243cdbd236d

Hardware: 6700K + RX 480

**_Description of the Issue_**

Dead or Alive 2: Limited Edition (JP) - display error when using Widescreen Cheat.

It appears to zoom in, cutting part of the screen's content.

See screenshots below comparing with DOA 2 USA release, using Widescreen Cheat.

**_Debugging Steps Tested_**

_N/A._

**_Logs Gathered_**

_N/A._

**_Screenshots_**

_USA menu:_

![usa 1 menu](https://user-images.githubusercontent.com/20749249/167315113-0ff066eb-a738-44ea-a6bf-79a4f115e8b6.jpg)

_JP LE menu:_

![jp le 1 menu](https://user-images.githubusercontent.com/20749249/167315152-864d12e9-21a8-4791-b614-67406f4872c1.jpg)

_USA character select:_

![usa 2 select](https://user-images.githubusercontent.com/20749249/167315134-498e7794-269b-43ee-b7dc-a1d71d917c45.jpg)

_JP LE character select:_

![jp le 2 select](https://user-images.githubusercontent.com/20749249/167315191-37a252a4-9f89-4abc-928e-9e04d11ec151.jpg)

_USA gameplay:_

![usa 3 gameplay](https://user-images.githubusercontent.com/20749249/167315140-a04e07c5-facf-4dd9-a8a3-e99e82510cef.jpg)

_JP LE gameplay:_

![jp le 3 gameplay](https://user-images.githubusercontent.com/20749249/167315207-82c24833-a949-44cf-bef7-bd40513e6b6f.jpg)

**Comment by rdeleonp** [comment]
It also affect cut scenes (the dialogue subtitles get cut-off).

**Comment by flyinghead** [comment]
The widescreen cheat for doa2 LE had 2 codes, the second one supposedly to "Fix the HUD". It was stretching the screen vertically and shifting it down so I disabled it.

**Comment by rdeleonp** [comment]
Thanks a lot.
