### ISSUE TITLE
[Libretro core] Flycast segfaults when run from TTY, but not from SSH

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#626]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
GNU/Linux Debian 11

Github hash: 
commit 6c6b447ea1d2d251e5f7b96d57b0e243cdbd236d
(Latest Github code)

Hardware: 
Very different hardware: 
X86_64, aarch64 CPUs
VC4, IRIS, AMDGPU GPUs
All of the graphics run on the latest MESA code (but has happened with every MESA version).

**_Description of the Issue_**

Running the RetroArch core directly on the TTY causes a segfault.
Running the RetroArch core from an SSH session does NOT cause any segfaults, and things seem to work right.

So, doing this on a TTY will cause a segfault:

`retroarch -L ~/.config/retroarch/cores/flycast_libretro.so games/ctaxi/ctaxi.cue`

...BUT doing the same thing over SSH will run the core and content nicely.

**Note I am talking about a real TTY here, no X11 or wayland server is running.**

**_Debugging Steps Tested_**

No way to attach gdb to running retroarch with this core for some reason, sorry.
I can't find the PID for retroarch when this core is loaded.
But issue is very easy to reproduce.

I build the flycast core like this:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON -DUSE_VULKAN=ON -DUSE_OPENGL=OFF`

Only this core causes the segfault when run on the TTY: Any other cores run fine.

**Comment by flyinghead** [comment]
This looks similar to #578 and https://github.com/libretro/flycast/issues/1118. I can't reproduce it on ubuntu 20 (with x11) and I doubt this has anything to do with the Flycast core.

Flycast doesn't read the standard input and uses the libretro API to poll input devices.

**Comment by vanfanel** [comment]
@flyinghead It is never going to happen with X11.
In Ubuntu, you can change to a TTY with CTRL+ALT+F1, or F2, etc... and try from there.

**Comment by flyinghead** [comment]
I tried compiling RA to run without X11 but it crashes in the vulkan driver. Open GL also crashes.

**Comment by vanfanel** [comment]
@flyinghead Maybe we should open an issue on the RetroArch tracker?

**Comment by flyinghead** [comment]
https://github.com/libretro/RetroArch/issues/13844
There's some "ping-pong" going on between here and there ;)

Did you check if using the SDL input driver fixes the problem on your end?
Also, you can try to run retroarch as `retroarch < /dev/null`, which detaches it from the current TTY.

**Comment by vanfanel** [comment]
@flyinghead Yes, setting input driver to SDL avoids the segfault, and doing that detaching via `retroarch < /dev/null` avoids it too...
So it seems something related to udev on TTY?

**Comment by flyinghead** [comment]
Yes, it looks like an issue linked with udev when using a console TTY.

The fact that the crash only happens with Flycast doesn't prove (nor disprove) that Flycast is at fault. All cores are different and Flycast is quite a complex one. RetroArch is responsible for interacting with the input driver and the core only deals with virtual controllers that are immutable and defined by the libretro API. So this points to an issue with RA but I can't rule out the alternative. I just don't see what it could be.
