### ISSUE TITLE
Android compilation error

### ISSUE THREAD

**Issue by clondy999** [flyinghead/flycast#627]
I compiled using Linux and got the following error reports. Can you help me
The version used is 48e3a3eb68d7d70ffc4721aab55fd10944b5d7f3
Compiled by Android

FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flycast:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /home/shell/Desktop/flycast/flycast/CMakeLists.txt: Build command failed.
  Error while executing process /home/shell/Android/Sdk/cmake/3.18.1/bin/cmake with arguments {-H/home/shell/Desktop/flycast/flycast -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=16 -DANDROID_PLATFORM=android-16 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_ANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_TOOLCHAIN_FILE=/home/shell/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/shell/Android/Sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/prefab/arm64-v8a/prefab -B/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/arm64-v8a -GNinja -DANDROID_ARM_MODE=arm}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Git: /usr/bin/git (found version "2.17.1") 
  -- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP: TRUE (found version "3.1")  
  -- xxHash build type: Debug
  -- Performing Test CFLAG_Wall
  -- Performing Test CFLAG_Wall - Success
  -- Performing Test CFLAG_Wextra
  -- Performing Test CFLAG_Wextra - Success
  -- Performing Test CFLAG_Wcast_qual
  -- Performing Test CFLAG_Wcast_qual - Success
  -- Performing Test CFLAG_Wcast_align
  -- Performing Test CFLAG_Wcast_align - Success
  -- Performing Test CFLAG_Wshadow
  -- Performing Test CFLAG_Wshadow - Success
  -- Performing Test CFLAG_Wstrict_aliasing_1
  -- Performing Test CFLAG_Wstrict_aliasing_1 - Success
  -- Performing Test CFLAG_Wswitch_enum
  -- Performing Test CFLAG_Wswitch_enum - Success
  -- Performing Test CFLAG_Wdeclaration_after_statement
  -- Performing Test CFLAG_Wdeclaration_after_statement - Success
  -- Performing Test CFLAG_Wstrict_prototypes
  -- Performing Test CFLAG_Wstrict_prototypes - Success
  -- Performing Test CFLAG_Wundef
  -- Performing Test CFLAG_Wundef - Success
  -- spirv-tools not linked - illegal SPIRV may be generated for HLSL
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE  
  -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
  -- Found ZLIB: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libz.a (found version "1.2.7") 
  -- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
  -- Could NOT find oboe (missing: oboe_DIR)
  -- Configuring incomplete, errors occurred!
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/arm64-v8a/CMakeFiles/CMakeOutput.log".
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/arm64-v8a/CMakeFiles/CMakeError.log".
  
  CMake Error at CMakeLists.txt:195 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/breakpad
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at CMakeLists.txt:291 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/libchdr
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Deprecation Warning at CMakeLists.txt:301 (cmake_policy):
    The OLD behavior for policy CMP0026 will be removed from a future version
    of CMake.
  
    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.
  
  
  CMake Error at CMakeLists.txt:302 (get_target_property):
    get_target_property() called with non-existent target "zlib".
  
  
  CMake Error at core/deps/oboe/gamesdk.cmake:117 (message):
    Can't find any library in
    "core/deps/oboe/libs/arm64-v8a_API28_NDK21_cpp_static_Debug".  Are you sure
    you are using a supported Android SDK/NDK and STL variant?
  Call Stack (most recent call first):
    CMakeLists.txt:418 (add_gamesdk_target)
  
  

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flycast:configureCMakeDebug[armeabi-v7a]'.
> [CXX1405] error when building with cmake using /home/shell/Desktop/flycast/flycast/CMakeLists.txt: Build command failed.
  Error while executing process /home/shell/Android/Sdk/cmake/3.18.1/bin/cmake with arguments {-H/home/shell/Desktop/flycast/flycast -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=16 -DANDROID_PLATFORM=android-16 -DANDROID_ABI=armeabi-v7a -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_ANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_TOOLCHAIN_FILE=/home/shell/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/shell/Android/Sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/armeabi-v7a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/prefab/armeabi-v7a/prefab -B/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/armeabi-v7a -GNinja -DANDROID_ARM_MODE=arm}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Git: /usr/bin/git (found version "2.17.1") 
  -- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP: TRUE (found version "3.1")  
  -- xxHash build type: Debug
  -- Performing Test CFLAG_Wall
  -- Performing Test CFLAG_Wall - Success
  -- Performing Test CFLAG_Wextra
  -- Performing Test CFLAG_Wextra - Success
  -- Performing Test CFLAG_Wcast_qual
  -- Performing Test CFLAG_Wcast_qual - Success
  -- Performing Test CFLAG_Wcast_align
  -- Performing Test CFLAG_Wcast_align - Success
  -- Performing Test CFLAG_Wshadow
  -- Performing Test CFLAG_Wshadow - Success
  -- Performing Test CFLAG_Wstrict_aliasing_1
  -- Performing Test CFLAG_Wstrict_aliasing_1 - Success
  -- Performing Test CFLAG_Wswitch_enum
  -- Performing Test CFLAG_Wswitch_enum - Success
  -- Performing Test CFLAG_Wdeclaration_after_statement
  -- Performing Test CFLAG_Wdeclaration_after_statement - Success
  -- Performing Test CFLAG_Wstrict_prototypes
  -- Performing Test CFLAG_Wstrict_prototypes - Success
  -- Performing Test CFLAG_Wundef
  -- Performing Test CFLAG_Wundef - Success
  -- spirv-tools not linked - illegal SPIRV may be generated for HLSL
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE  
  -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
  -- Found ZLIB: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a (found version "1.2.7") 
  -- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
  -- Could NOT find oboe (missing: oboe_DIR)
  -- Configuring incomplete, errors occurred!
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/armeabi-v7a/CMakeFiles/CMakeOutput.log".
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/armeabi-v7a/CMakeFiles/CMakeError.log".
  
  CMake Error at CMakeLists.txt:195 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/breakpad
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at CMakeLists.txt:291 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/libchdr
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Deprecation Warning at CMakeLists.txt:301 (cmake_policy):
    The OLD behavior for policy CMP0026 will be removed from a future version
    of CMake.
  
    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.
  
  
  CMake Error at CMakeLists.txt:302 (get_target_property):
    get_target_property() called with non-existent target "zlib".
  
  
  CMake Error at core/deps/oboe/gamesdk.cmake:117 (message):
    Can't find any library in
    "core/deps/oboe/libs/armeabi-v7a_API28_NDK21_cpp_static_Debug".  Are you
    sure you are using a supported Android SDK/NDK and STL variant?
  Call Stack (most recent call first):
    CMakeLists.txt:418 (add_gamesdk_target)
  
  

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flycast:configureCMakeDebug[x86]'.
> [CXX1405] error when building with cmake using /home/shell/Desktop/flycast/flycast/CMakeLists.txt: Build command failed.
  Error while executing process /home/shell/Android/Sdk/cmake/3.18.1/bin/cmake with arguments {-H/home/shell/Desktop/flycast/flycast -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=16 -DANDROID_PLATFORM=android-16 -DANDROID_ABI=x86 -DCMAKE_ANDROID_ARCH_ABI=x86 -DANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_ANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_TOOLCHAIN_FILE=/home/shell/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/shell/Android/Sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/x86 -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/x86 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/prefab/x86/prefab -B/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/x86 -GNinja -DANDROID_ARM_MODE=arm}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Git: /usr/bin/git (found version "2.17.1") 
  -- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP: TRUE (found version "3.1")  
  -- xxHash build type: Debug
  -- Performing Test CFLAG_Wall
  -- Performing Test CFLAG_Wall - Success
  -- Performing Test CFLAG_Wextra
  -- Performing Test CFLAG_Wextra - Success
  -- Performing Test CFLAG_Wcast_qual
  -- Performing Test CFLAG_Wcast_qual - Success
  -- Performing Test CFLAG_Wcast_align
  -- Performing Test CFLAG_Wcast_align - Success
  -- Performing Test CFLAG_Wshadow
  -- Performing Test CFLAG_Wshadow - Success
  -- Performing Test CFLAG_Wstrict_aliasing_1
  -- Performing Test CFLAG_Wstrict_aliasing_1 - Success
  -- Performing Test CFLAG_Wswitch_enum
  -- Performing Test CFLAG_Wswitch_enum - Success
  -- Performing Test CFLAG_Wdeclaration_after_statement
  -- Performing Test CFLAG_Wdeclaration_after_statement - Success
  -- Performing Test CFLAG_Wstrict_prototypes
  -- Performing Test CFLAG_Wstrict_prototypes - Success
  -- Performing Test CFLAG_Wundef
  -- Performing Test CFLAG_Wundef - Success
  -- spirv-tools not linked - illegal SPIRV may be generated for HLSL
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE  
  -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
  -- Found ZLIB: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/libz.a (found version "1.2.7") 
  -- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
  -- Could NOT find oboe (missing: oboe_DIR)
  -- Configuring incomplete, errors occurred!
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/x86/CMakeFiles/CMakeOutput.log".
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/x86/CMakeFiles/CMakeError.log".
  
  CMake Error at CMakeLists.txt:195 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/breakpad
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at CMakeLists.txt:291 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/libchdr
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Deprecation Warning at CMakeLists.txt:301 (cmake_policy):
    The OLD behavior for policy CMP0026 will be removed from a future version
    of CMake.
  
    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.
  
  
  CMake Error at CMakeLists.txt:302 (get_target_property):
    get_target_property() called with non-existent target "zlib".
  
  
  CMake Error at core/deps/oboe/gamesdk.cmake:117 (message):
    Can't find any library in
    "core/deps/oboe/libs/x86_API28_NDK21_cpp_static_Debug".  Are you sure you
    are using a supported Android SDK/NDK and STL variant?
  Call Stack (most recent call first):
    CMakeLists.txt:418 (add_gamesdk_target)
  
  

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flycast:configureCMakeDebug[x86_64]'.
> [CXX1405] error when building with cmake using /home/shell/Desktop/flycast/flycast/CMakeLists.txt: Build command failed.
  Error while executing process /home/shell/Android/Sdk/cmake/3.18.1/bin/cmake with arguments {-H/home/shell/Desktop/flycast/flycast -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=16 -DANDROID_PLATFORM=android-16 -DANDROID_ABI=x86_64 -DCMAKE_ANDROID_ARCH_ABI=x86_64 -DANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_ANDROID_NDK=/home/shell/Android/Sdk/ndk/21.1.6352462 -DCMAKE_TOOLCHAIN_FILE=/home/shell/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/shell/Android/Sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/x86_64 -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/build/intermediates/cxx/Debug/6b2n4c1q/obj/x86_64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/prefab/x86_64/prefab -B/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/x86_64 -GNinja -DANDROID_ARM_MODE=arm}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Git: /usr/bin/git (found version "2.17.1") 
  -- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
  -- Found OpenMP: TRUE (found version "3.1")  
  -- xxHash build type: Debug
  -- Performing Test CFLAG_Wall
  -- Performing Test CFLAG_Wall - Success
  -- Performing Test CFLAG_Wextra
  -- Performing Test CFLAG_Wextra - Success
  -- Performing Test CFLAG_Wcast_qual
  -- Performing Test CFLAG_Wcast_qual - Success
  -- Performing Test CFLAG_Wcast_align
  -- Performing Test CFLAG_Wcast_align - Success
  -- Performing Test CFLAG_Wshadow
  -- Performing Test CFLAG_Wshadow - Success
  -- Performing Test CFLAG_Wstrict_aliasing_1
  -- Performing Test CFLAG_Wstrict_aliasing_1 - Success
  -- Performing Test CFLAG_Wswitch_enum
  -- Performing Test CFLAG_Wswitch_enum - Success
  -- Performing Test CFLAG_Wdeclaration_after_statement
  -- Performing Test CFLAG_Wdeclaration_after_statement - Success
  -- Performing Test CFLAG_Wstrict_prototypes
  -- Performing Test CFLAG_Wstrict_prototypes - Success
  -- Performing Test CFLAG_Wundef
  -- Performing Test CFLAG_Wundef - Success
  -- spirv-tools not linked - illegal SPIRV may be generated for HLSL
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - yes
  -- Found Threads: TRUE  
  -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
  -- Found ZLIB: /home/shell/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/libz.a (found version "1.2.7") 
  -- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
  -- Could NOT find oboe (missing: oboe_DIR)
  -- Configuring incomplete, errors occurred!
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/x86_64/CMakeFiles/CMakeOutput.log".
  See also "/home/shell/Desktop/flycast/flycast/shell/android-studio/flycast/.cxx/Debug/6b2n4c1q/x86_64/CMakeFiles/CMakeError.log".
  
  CMake Error at CMakeLists.txt:195 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/breakpad
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at CMakeLists.txt:291 (add_subdirectory):
    The source directory
  
      /home/shell/Desktop/flycast/flycast/core/deps/libchdr
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Deprecation Warning at CMakeLists.txt:301 (cmake_policy):
    The OLD behavior for policy CMP0026 will be removed from a future version
    of CMake.
  
    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.
  
  
  CMake Error at CMakeLists.txt:302 (get_target_property):
    get_target_property() called with non-existent target "zlib".
  
  
  CMake Error at core/deps/oboe/gamesdk.cmake:117 (message):
    Can't find any library in
    "core/deps/oboe/libs/x86_64_API28_NDK21_cpp_static_Debug".  Are you sure
    you are using a supported Android SDK/NDK and STL variant?
  Call Stack (most recent call first):
    CMakeLists.txt:418 (add_gamesdk_target)
  
  

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
29 actionable tasks: 4 executed, 25 up-to-date

**Comment by flyinghead** [comment]
`git submodule update --init`

**Comment by clondy999** [comment]
Thank you for your reply. The problem has been solved
I have another question. FlyCast does not support ROM in Bin format?
Because when I use the FlyCast kernel of retroarch, it is supported by bin ROM

**Comment by clondy999** [comment]
So what should I do with the ROM using bin? Can you teach me?

**Comment by cinnamonmatexfce** [comment]
> So what should I do with the ROM using bin? Can you teach me?

I don't think here's rhe right place were ti ask for this kind of support... Anyway... Grab another ROM or convert to CHD (or `.gdi`)

**Comment by clondy999** [comment]
谢谢你的回答。问题已经解决了
