### ISSUE TITLE
[DX11][Windows]Texture Filtering option not working

### ISSUE THREAD

**Issue by Immersion95** [flyinghead/flycast#628]
The texture filtering option is a great feature, it works with Vulkan but noes dothing in DX11.

Choosing Nearest, Bilinear always resullts in the Default option.

I tested it on Libretro but not on standalone, It should be the same though.

**Comment by flyinghead** [comment]
Should be fixed in the latest build

**Comment by Immersion95** [comment]
Works perfectly :)
