### ISSUE TITLE
[Libretro core] [naomi2 games] player 2 start button do not work

### ISSUE THREAD

**Issue by skysix2** [flyinghead/flycast#629]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Batocera.plus, with core built and downloaded from https://buildbot.libretro.com/nightly/linux/x86_64/latest/flycast_libretro.so.zip
date 01/05/2022

Hardware: 
AMD x86_64

**_Description of the Issue_**

hi, I have tried various naomi2 games such as "virtua fighter 4" and others, and in none of these the player2 start button works
 (no challenges in short)
it works great in naomi games instead

i haven't tried it on standalone flycast

thanks for naomi2 , great job !!

**Comment by flyinghead** [comment]
Service Menu > System Assignments > Cabinet Type

**Comment by skysix2** [comment]
perfect !! thanks, sorry for the inconvenience I ignored this setting
