### ISSUE TITLE
Vulkan crash when "per pixel" option is selected.

### ISSUE THREAD

**Issue by LuismaSP89** [flyinghead/flycast#63]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
OS: Windows 10 x64, stand-alone build dowloaded from Emucr. Using windows only, not integrated with Retroarch.

**_Description of the Issue_**

When using "per pixel" option under video settings, and then trying to run a game. The emulator just crashes. This doesn't happen with other options, only with "per pixel" under vulkan.

This option is working fine in opengl with no problems.

My specs:

Windows 10 x64
16GB DDR3
i7 4790k
GTX 970

**_Debugging Steps Tested_**

  - Select vulkan backend and "per pixel" option under "video"
  - Try to open a game, then crash. "In my case the testing was done with Shenmue I"
  

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by LuismaSP89** [comment]
Note: Tested with latest flycast build.

Version: r7-rc1-2890-g7109377d
Git hash: 7109377d

**Comment by xZabuzax** [comment]
That's interesting, I also have a i7 4790k, GTX 970 and 16GB of Ram, however, I'm still using Windows 7 (SP1).

In my case it doesn't crash but the GPU gets extremely hot in just the menu with no games loaded.

**Comment by LuismaSP89** [comment]
@xZabuzax Then maybe the difference is in the OS... also, can you tell me what Nvidia driver version are you using? Mine is 441.264

**Comment by xZabuzax** [comment]
>Then maybe the difference is in the OS... also, can you tell me what Nvidia driver version are you using? Mine is 441.264

That's also interesting, our driver versions aren't too far behind either, my version is: 441.41. Maybe the issue is related with the driver 441?

My issue with the GPU getting extremely hot with Vulkan and Per Pixel enabled started happening in the master build "8482b91", in other words the last 2 versions have the issue for me. Try to see if you have the same issue in a version prior "8482b91".

**Comment by LuismaSP89** [comment]
@xZabuzax In my case also crashes using a build from 5 days ago "320d0a5c"

**Comment by xZabuzax** [comment]
> In my case also crashes using a build from 5 days ago "320d0a5c"
Hmmm, our issues are not related then but still, something must be wrong in our system. The developer already tested it in Windows 7 with the same 441 driver and he's not experiencing any of our issues.

**Comment by LuismaSP89** [comment]
@xZabuzax I think its too coincidence to be an error of our systems, maybe it's related with the GTX 970. Do you know what are the PC specs of the developer?

**Comment by xZabuzax** [comment]
> I think its too coincidence to be an error of our systems, maybe it's related with the GTX 970. Do you know what are the PC specs of the developer?

Hmm maybe, it's indeed a coincidence that we are both using a GTX 970 and we both happen to be on the driver 441.

The developer is using a GTX 1080.

**Comment by LuismaSP89** [comment]
@xZabuzax I can confirm that the problem is not related with the driver version we're using. Downloaded and installed 445.75 and the issue persists.

**Comment by xZabuzax** [comment]
> I can confirm that the problem is not related with the driver version we're using. Downloaded and installed 445.75 and the issue persists.

Damn I don't know what could be causing our issues then, what I know is that our system are very similar so maybe the combination of a i7 4790k and a GTX 970 is the one causing it?

My CPU is not even overclocked, the only weird setup that I have in my system is that I changed the power setting of the CPU from 100% to 99% and I did it for a good reason, if it's in 100% the CPU tends to get hot when I'm converting videos or using the RPCS3 emulator, those 2 programs strains the CPU and will get it above 70c, changing it to 99% makes the CPU a bit slower but at least it will keep it below 70c and I'm fine with that.

**Comment by flyinghead** [comment]
Can you try to get a log file? Enable Settings > Advanced > Log to File and it should create a flycast.log file in the current folder.
I've been unable to reproduce your crash or the issue xZabuzax is having.

**Comment by xZabuzax** [comment]
> Can you try to get a log file? Enable Settings > Advanced > Log to File and it should create a flycast.log file in the current folder.
> I've been unable to reproduce your crash or the issue xZabuzax is having.

Should I also provide you a log file of my GPU overheating issue or is it only the log file of the crashing issue?

**Comment by flyinghead** [comment]
It certainly won't hurt

**Comment by xZabuzax** [comment]
> It certainly won't hurt

Alright, this log file was only in the Menu with no games loaded, I did the steps that causes the issue and once the GPU reached 70c I closed the emulator.

If you need another log file with a game running let me know.

Here's the log file:

> 00:00:000 rend/vulkan/vulkan_context.cpp:220 N[RENDERER]: Vulkan API 1.1. Device GeForce GTX 970
> 00:00:000 rend/vulkan/vulkan_context.cpp:228 N[RENDERER]: eR5G5B5A1UnormPack16 not supported for optimal tiling
> 00:00:000 rend/vulkan/vulkan_context.cpp:242 N[RENDERER]: eR4G4B4A4UnormPack16 not supported for optimal tiling
> 00:00:025 rend/vulkan/vulkan_context.cpp:296 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
> 00:10:205 rend/vulkan/vulkan_context.cpp:220 N[RENDERER]: Vulkan API 1.1. Device GeForce GTX 970
> 00:10:206 rend/vulkan/vulkan_context.cpp:228 N[RENDERER]: eR5G5B5A1UnormPack16 not supported for optimal tiling
> 00:10:206 rend/vulkan/vulkan_context.cpp:242 N[RENDERER]: eR4G4B4A4UnormPack16 not supported for optimal tiling
> 00:10:232 rend/vulkan/vulkan_context.cpp:296 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
>

**Comment by LuismaSP89** [comment]
@flyinghead First of all, thanks a lot for your help and you work with this emulator : )

Here's my log for Fly cast:

[flycast.log](https://github.com/flyinghead/flycast/files/4438175/flycast.log)

Seems to be a continuous "unhandled access" error.

**Comment by LuismaSP89** [comment]
Finally solved it. It was reshade program, because I had enabled the option "Enable for all vulkan games"

Strange that reshade works perfect with fly cast, but crashes immediately if "per pixel" option is selected.

Closing...
