### ISSUE TITLE
Graphical bug + controller issue

### ISSUE THREAD

**Issue by dragonasia** [flyinghead/flycast#632]
Platform / OS / Hardware: X86_64 / Batocera V34 / Amd Ryzen 5700G 

Github hash: https://github.com/batocera-linux/batocera.linux/issues/6006

Hardware: Amd Ryzen 5700G

**_Description of the Issue_**

Hello there,

I met a lot of issues with the last version of flycast through Batocera. 

==> Dreamcast, issue with controller, the controller is not correctly set, impossible to play, even when I am resetting the controler, massive bug.

A,B,X,Y are not correctly set, impossible to change it.

For example in RE3 on dreamcast, A and X are now the same bouton, L2 and R2 are not working properly, as soon as I pushed L2 or R2 to fire, my player stays blocked on fire mode, so I can't move. I have to press L2 and R2 in same time and holding them to be able to move, the running bouton is now the same bouton as action, etc.

+ Graphic Bug in Alone in the Dark Start Screen, etc. Not present in the last build. 

**_Debugging Steps Tested_**

My controller buttons don't work correctly in evdev mode as well.

Thanks a lot and thanks for the hard work.

**Comment by flyinghead** [comment]
Nothing has changed recently regarding controllers and nobody reported any major issue in this area. I would assume your mapping files are incorrect, or the ones provided/generated by Batocera. Also I have no idea what versions V33 and V34 are and how they relate to Flycast code.

evdev is deprecated in Flycast and no longer maintained. Only SDL2 is supported.

The graphic bug in Alone in the Dark has been fixed already: See #612

**Comment by flyinghead** [comment]
I think I understand the issue: there was a major change in controllers mapping between Batocera V33 (Flycast v1.1 2021/8/21) and the current version (Flycast master on 2022/4/21).
I suggest you delete everything in the `mapping` directory to start with the default.

**Comment by dragonasia** [comment]
Thanks.

I deleted all the mapping in the directory... and still the same issue. I will share this with the Batocera Dev + Bump of the version to correct the graphical bug as well. Thanks.

**Comment by dmanlfc** [comment]
@dragonasia don't run under ES, use f1 -> applications to launch flycast.
as per @flyinghead's suggestion, delete your mappings first.
then configure your controller using sdl2 - do you still have the issue?

**Comment by dragonasia** [comment]
@dmanlfc Hello, quick heads up, I have deleted the mapping many time, then used F1, configured many time the controls through flycast... and I still have the issue... Dunno why...

**Comment by dragonasia** [comment]
@flyinghead Hello mate, not sure if you have read, any ideas about this? 

Yesterday, I tried again, deleted all the mapping, directly configured the controler in sdl then launch a game through flycast (not in Batocera) and it is not working.

As soon as I pushed a trigger on the controller, I can't move anymore and the touch are not set correctly. If I am not using a trigger like in Blue Stinger for example, this is working.

So, the bug is coming from there I guess...

@dmanlfc Fyi, here above.

**Comment by flyinghead** [comment]
Can you install the latest Flycast build from this github and test with it?
That way, we'll put Batocera out of the picture.

**Comment by dragonasia** [comment]
@flyinghead Sure, I will.

**Comment by dragonasia** [comment]
@flyinghead @dmanlfc Back again, I tried, it is working on flycast 1.3, no bug or controller issue with Flycast 1.3, under windows, on Alone in the dark. 

I also tried with the last build, 2022-05-15T11:45:24.000Z, crash of Alone in the Dark just before the start screen. 

So, any idea about the issue? Is it Batocera or Flycast in my case?

**Comment by dmanlfc** [comment]
You need to test a Linux binary, not the Windows one...

**Comment by dragonasia** [comment]
I will see if I can install Linux somewhere, not sure. I don't want to have a dual boot on primary ssd. That will be a mess to delete after.

**Comment by flyinghead** [comment]
There's an issue with yesterday's build so use the previous one if you need to.

You can try the flycast-x86_64-pc-linux-gnu build from https://github.com/flyinghead/flycast/actions/runs/2323631906
but you might run into dependency issues since it's build for ubuntu 20.

**Comment by dmanlfc** [comment]
@dragonasia - i have updated batocera with SDL controller configuration.
RE3 has been tested, there are no trigger issues in the current release candidate.
Give it a try.

**Comment by dragonasia** [comment]
@dmanlfc Top mate. I will try this soon and I will keep you updated :) 

Fyi, the trigger issue I met was in different game, basically where the trigger was required to play. Other ex, in alone in the dark, same issue. As soon as I pushed the trigger ==> Bug controller not working correctly. Cannot move if I am not pushing the trigger. Have to keep the trigger pushed to move. Very weird. As said, in the last version of flycast in Batocera (V33 or B34 up to early april) I had no issue. When Flycast has been bumped to 1.3, issues started.

**Comment by dragonasia** [comment]
@dmanlfc @flyinghead  I just tried. Still have the triggers issue with RE3 OR Alone in the Dark or any game using a trigger. 

In V33 or the last version of flycast no issue at all. 

What is wrong?
