### ISSUE TITLE
Some games have map error with some grahics API 

### ISSUE THREAD

**Issue by leoxxx** [flyinghead/flycast#635]
https://github.com/blueminder/flycast-dojo/issues/19

**Comment by flyinghead** [comment]
https://github.com/flyinghead/flycast/issues/570#issuecomment-1124905524

**Comment by flyinghead** [comment]
Duplicate of #570

**Comment by leoxxx** [comment]
https://github.com/flyinghead/flycast/issues/570#issuecomment-1242650190
Still error.
I think it's not a Duplicate of https://github.com/flyinghead/flycast/issues/570
