### ISSUE TITLE
Request: Savestate feature

### ISSUE THREAD

**Issue by LuismaSP89** [flyinghead/flycast#64]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
Windows 10 x64
Version: r7-rc1-2890-g7109377d
Git hash: 7109377

**_Description of the Issue_**

I think fly cast and reicast already have a savestate feature. But this feature can't be seen in the stand-alone version for windows. I think is a good idea to bring an option to enable this feature for all users for this version without retroarch.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
Savestates can be saved and loaded in the menu by pressing TAB:
![image](https://user-images.githubusercontent.com/16261910/78534658-10bc0980-77eb-11ea-9106-23c0e2ca2ee8.png)

**Comment by LuismaSP89** [comment]
@flyinghead No menu appears when I press the tab key, using stand-alone version. And OpenGL backend.

**Comment by xZabuzax** [comment]
Go to controls and make sure the button for "Menu" is mapped to a key in your keyboard or a pad. If it doesn't work with the that key mapped then I don't know what's causing the issue for you.

**Comment by LuismaSP89** [comment]
Sorry, that was my fault. Solved by following your instructions.

Closing.
