### ISSUE TITLE
initdv3j hangs during boot

### ISSUE THREAD

**Issue by leoxxx** [flyinghead/flycast#647]
Tested in 22ad95c.
WINDOWS 7 X64
initdv3j: black screen after checking completely, can't playing.
initdv3e: audio somtimes have lag and error. (lack some channels?)
vf4tuned: only dx11 no map error, but sometimes have lag.

**Comment by lim2222** [comment]
initdv3jb with gds-0032b.chd in folder able to play but will crash after conquered an area which means when you win all the racers in one area the game will crash.

**Comment by flyinghead** [comment]
@lim2222 Can you post a savestate right before the end of the last race of an area? That would help me diagnose the issue.

Initd version 1 and 2 are known to send garbage data to the gpu at the end of each race, and particularly at the end of each area. I suppose this hasn't been fixed in this version of initdv3.

**Comment by flyinghead** [comment]
I just pushed a fix to the initdv3jb crash for this savestate. If may still crash when finishing other areas so if that happens, posting the same kind of savestate would be greatly appreciated.

**Comment by leoxxx** [comment]
initdv3j=gds-0032c
It's not initdv3jb.

**Comment by flyinghead** [comment]
Yes. I changed the title of the issue to reflect this.

If you have problems with vf4tuned or initdv3e, please open other issue(s) with details to reproduce them.

**Comment by dreamaster1658** [comment]
user flycast v2.2 to run initdv3j still black screen after checking completely.
user flycast v2.2 to run initdv3jb when i win the racers in one area the game will crash, only the third area will crash, other area is perfect.

**Comment by flyinghead** [comment]
Can you upload a savestate of the game before the crash?

**Comment by dreamaster1658** [comment]
[data.zip](https://github.com/flyinghead/flycast/files/13545069/data.zip)
this is my savestate, thank you.

**Comment by dreamaster1658** [comment]
[Uploading savestate.zip…]()
this is the savestate before the flycast crash

**Comment by dreamaster1658** [comment]
[Uploading savestate.zip…]()
this is the savestate before the flycast crash

**Comment by flyinghead** [comment]
I can reproduce the crash. Thank you

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build
