### ISSUE TITLE
[Request] Add option to stretch image

### ISSUE THREAD

**Issue by LuismaSP89** [flyinghead/flycast#65]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

**_Description of the Issue_**

The current "widescreen" option draws geometry outside of the normal 4:3 aspect ratio. This leads to some graphical bugs in a lot of games. This is very annoying specially in 2D games such as Metal Slug 6, because the enemies are drawn outside of the screen and can be a horror to play games like this.

So, it would be perfect an option to stretch the 4:3 image to fill the screen without drawing geometry, just resize the 4:3 image to fit in the 16:9 format. Some users doesn't like this since it shows a deformed image. But there a lot of users too that ignores this problem in order to play games without graphical bugs or black bars.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
This option already exists and can be found in Video > Horizontal Stretching.
The default value (100) is the normal aspect ratio.

To stretch from 4:3 to 16:9, you can set it to 133.

**Comment by LuismaSP89** [comment]
@flyinghead So... basically I'm a dumbass... closing. And sorry for the inconvenience.
