### ISSUE TITLE
Cannot reset per-game setting to default value

### ISSUE THREAD

**Issue by 3lc3z4r** [flyinghead/flycast#653]
the latest update of the dev version (which is the best for its graphics correction option especially for the house of the dead 2) has a minor but annoying bug, simply after you create a specific game configuration it cannot be changed again unless you clear your settings for the game and do it again.

**Comment by flyinghead** [comment]
Do you have a reproducible scenario?
I did a quick test and I can modify an existing game-specific config without issue.

**Comment by 3lc3z4r** [comment]
I just tried it in 2 different games, in metal slug 6 and the house of the dead 2. I thought for a moment that the new graphics correction option had something to do with it, but it turns out that even with that it cannot be overwritten again a configuration of a specific game)

**Comment by flyinghead** [comment]
I did fix an issue with per-game settings when changing a setting back to its normal value. Can you test again?

If it still doesn't work please describe the exact steps so I can reproduce the issue. Thanks.
