### ISSUE TITLE
Controller is not detected by other programs after quitting Flycast

### ISSUE THREAD

**Issue by RainaAudron** [flyinghead/flycast#654]
**_Description of the Issue_**
Flycast uses SDL to handle controllers but it doesn't call SDL_Quit on exit.

**_Debugging Steps Tested_**
*Connect a controller.
*Open Flycast, then close it.
*Controller sometimes does not get detected by other emulators or controller programs (Xpadder for example) after this.

Thanks for looking into this!

**Comment by flyinghead** [comment]
I pushed a tentative fix on master. Let me know if it fixes the issue.

**Comment by flyinghead** [comment]
any feedback? is the issue fixed?

**Comment by flyinghead** [comment]
no problem. yes, you can use the latest master build.

**Comment by RainaAudron** [comment]
Success! I just tested it many times in a row and my controller worked fine after closing Flycast. Thank you!

**Comment by flyinghead** [comment]
thanks for testing
