### ISSUE TITLE
[Windows standalone] Fast Forward not working properly with DirectX11

### ISSUE THREAD

**Issue by PiKeyAr** [flyinghead/flycast#660]
Platform / OS / Hardware: 
Windows x64 / Windows 10 21H2 / i7 9700K, GTX 1660 Super, 16GB RAM

Github hash: [2327e73](https://github.com/flyinghead/flycast/commit/2327e73)

When the DirectX 11 renderer is selected, the Fast Forward feature cannot be used reliably. It seems to work in some places (FMVs, gameplay at 30 FPS) but not others (Dreamcast BIOS intro, menus, gameplay at 60 FPS). Tested in Sonic Adventure 1 and 2. With Vulkan and OpenGL renderers the feature works as expected. Other options in the Video tab don't seem to have any impact on the issue. I also tried disabling VSync in the emulator and nVIDIA Control panel and it didn't help.

**_Debugging Steps Tested_**

  * Switch to the DirectX 11 renderer.
  * Load Sonic Adventure or Sonic Adventure 2 and enable Fast Forward.
  * In SA1, Fast Forward will not work in the menus and Twinkle Circuit. In SA2 it doesn't seem to work almost anywhere.
  * Switch to Vulkan or OpenGL: Fast Forward behaves as expected.

Apart from this minor issue, the Direct3D 11 renderer appears to have the smoothest performance on my system. Thanks for adding it!

**Comment by flyinghead** [comment]
I just tested with an Intel HD gpu and fast forwarding works fine with DirectX 11, reaching 200 FPS and more. Something on your system is probably forcing VSync on with Flycast when it shouldn't (VSync is disabled when fast forwarding) so it's stuck at 60 FPS.

**Comment by hey-big** [comment]
I'm having this on Windows 10 21H2 x64 / AMD RX580 Git Hash: g552e5b7d7

**Comment by hey-big** [comment]
It doesn't happen when Flycast is windowed or unfocused

**Comment by flyinghead** [comment]
Looks similar to this issue: https://github.com/flyinghead/flycast/issues/970
