### ISSUE TITLE
flycast not running CSDC-Final_v1.0.cdi

### ISSUE THREAD

**Issue by rodrigoandrigo** [flyinghead/flycast#661]
Flycast has stopped
Fatal: SH4 branch instruction in Delay slot

Hardware: Xbox series s

![IMG_20220603_173436](https://user-images.githubusercontent.com/31012059/171949592-27c39d53-ae6f-4570-ad4e-6ef358a1e29c.jpg)

**Comment by flyinghead** [comment]
Enable `Settings > Advanced > Force Windows CE`

**Comment by rodrigoandrigo** [comment]
It worked
