### ISSUE TITLE
Reorganize some options in the Video settings tab, especially Graphics API and Internal Resolution

### ISSUE THREAD

**Issue by EdHerdman** [flyinghead/flycast#665]
Issue: Users have to scroll past options for enhancements and performance in order to find basic settings. I believe the most important and likely-to-be-changed options in the Video settings tab include Graphics API, Internal Resolution, Render To Texture, and Transparent Sorting, and would like to see them presented in roughly that order. The first two options have a large impact on emulation performance and the next two are important accuracy settings.

Suggestion: In reference to the current standalone build, I would like to see "Graphics API" moved to the top of the "Video" settings tab, followed by "Internal Resolution," "Transparent Sorting" and "Render to Texture."

Additionally, it might be good to re-arrange the options under headings for "basic settings," "performance / troubleshooting," and "enhancements." Perhaps "accuracy settings" would be needed too. In my view, added clutter would be minimal but readability would be improved.

I am also uncertain about the Per Pixel Settings "Pixel Buffer Size" option. Does "upscaling" in the ? tooltip description refer to a large Internal Resolution, or Texture Upscaling? Changing the location of this option and altering the text could clarify this for users.

**Comment by flyinghead** [comment]
Done on the `dev` branch

**Comment by EdHerdman** [comment]
Thanks for that - I'll close this as completed now.
