### ISSUE TITLE
Special Windows system folders interfere with directory selection in Windows standalone

### ISSUE THREAD

**Issue by EdHerdman** [flyinghead/flycast#666]
In Windows, the dialog for Adding a Content Location under the General settings tab represents the option for moving to the parent directory with ".." which is standard - but obscure for many users.

Unfortunately, in Windows (11, probably 10 and earlier as well) common system-related folders are sorted ahead of the ".." option in the dialog. These folders shouldn't be ahead of the ".." option and users shouldn't be able to see or select them.

These folders may have names like $GetCurrent, $SysReset, $WinREAgent, $Recycle.Bin, or $RECYCLE.BIN. $WINDOWS.~BT or $WINDOWS.~WS may appear left over from system upgrades.

Possible solutions: Always pin the ".." option to the top of the list, or hide folders that: start with a $ character, are marked as hidden (regardless of "show hidden folders" option in the OS), or have certain names.

Additionally, because ".." is so terse, perhaps consider adding some text to the parent directory selection option, like ".. (move to parent directory)"? I believe some other programs might do something like that.

**Comment by flyinghead** [comment]
Should be fixed in the latest master build

**Comment by EdHerdman** [comment]
Works great, thanks!
