### ISSUE TITLE
Analog stick input also causes dpad input, regardless of bindings/config

### ISSUE THREAD

**Issue by OctopusButtons** [flyinghead/flycast#667]
Platform / OS / Hardware: RetroArch 1.10.12 with Flycast core 22ad95c on MacOS 10.15.7 

Github hash: 22ad95c

Hardware: 2.5 GHZ core i5

**_Description of the Issue_**

Analog stick left/right/up/down (emulated Dreamcast controller) will always wrongly cause dpad left/right/up/down input no matter what you set your bindings configuration to, unless you unbind (emulated) dpad left/right/up/down so that it’s not assigned.

Same as this issue which someone reported for Lakka: https://github.com/libretro/Lakka-LibreELEC/issues/899

**_Debugging Steps Tested_**

* Set Analog to Digital Type = None. Didn’t help
* Unbound and rebound everything, issue remained
* Deleted core and game remap files, issue remained
* Tested stand-alone Redream emulator and the controls are normal, no issue
* Tested multiple games to rule out a game-specific bug.  (Examples are that in Metropolis Street Racer your steering inputs will always cause a horn honk, and in Daytona USA analog stick up/down (while steering) will cause camera change.)
* Used computer OS-level input testing app, confirmed that controller itself doesn’t have input issue, everything looks fine, no spurious inputs to dpad when using analog stick.
* Tried assigning (real-world in-hand) Dpad Left/Right to Dreamcast (emulated) controller buttons dpad UP and DOWN in RetroArch to see if Analog stick left right would still cause dpad left right inputs. Issue remained.
* Tried binding Dpad left/right to nothing (“- -“), this stopped the spurious inputs, with drawback of losing the assigned in-game functions for dpad
* Ran a ControllerTest-DJ.cdi file in RetroArch Flycast, confirmed that indeed analog stick is causing corresponding dpad inputs.  It’s a one-way issue: analog stick does dpad input, but dpad input itself is OK and doesn’t affect analog stick input.
* **EDIT/UPDATE** I've tested in stand-alone Flycast (I didn't find a Mac build to test this when I first posted, but now I found it) both the latest stable version and also the 22ad95c build that matches RetroArch, and there is NO ISSUE there, analog stick doesn't cause dpad inputs.

**_Logs Gathered_**

I turned on verbose logging, repeated the problem inputs inside a game, but the log doesn’t contain anything about inputs, buttons, etc, even if I unbound and rebind the inputs.

**Comment by flyinghead** [comment]
I doubt this is a core issue since it’s completely isolated from the physical controllers and driver (and bindings). RetroArch does all the work and exposes a well-defined virtual gamepad to the cores.

Can you try standalone Flycast to check if it has the same issue?

**Comment by OctopusButtons** [comment]
Thanks for taking a look.  (I'm unclear on which compartment of github is the right one for posting this issue, I had used the link from the RetroArch page of repositories so I thought this was for the core.)

I've now tried standalone Flycast, the latest stable as well as the standalone 22ad95c build that matches the build in RetroArch, and there is NO ISSUE there.  (I will update original post in a moment.)  I would have tried this sooner, but when I had looked up Flycast at the time I wasn't seeing any Mac builds.  I'll look for the right place to post again.

**Comment by flyinghead** [comment]
Standalone Flycast uses SDL to handle inputs. If this driver is available in RetroArch on macOS, it would be worth a try.

**Comment by OctopusButtons** [comment]
Darn, only driver in Mac version of Retroarch is hid

I've updated issue on Retroarch https://github.com/libretro/RetroArch/issues/14063 , because I found that same bug is present in PS1 and N64 emulation.  I just never noticed it before because the dpad is either inactive or redundant with analog stick on those, usually, so the bug doesn't affect anything.  Dreamcast is where games started to put totally separate functions on dpad, so I noticed the bug right away in gameplay.

**Comment by crashGG** [comment]
I have been using the win64 version of retroarch+flycast core to play games for a long time and have not found this problem. You can try the windows version, or upgrade to the latest retroarch to see if the problem persists.
