### ISSUE TITLE
Mouse issues

### ISSUE THREAD

**Issue by blubaustin** [flyinghead/flycast#670]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Ryzen 1700, 32gb ram, vega 56, Win 10 x64
Flycast version 1.3

When mouse is enabled in unreal tournment, even in full screen, the mouse works but then if you play for a bit you realize it'll act like it's at the edge of the screen, then the camera won't move anymore. So you have to do like a 360 or 180 to get the mouse like more center, it's pretty annoying. Is there a way of fixing this issue? 

Also even if in full screen if on dual monitors my mouse will go outside the window.

**Comment by flyinghead** [comment]
You need to capture the mouse. You can do so by pressing Left-ALT and Left-CTRL simultaneously.
Use the same key combination to return to normal mouse mode.

**Comment by flyinghead** [comment]
Closing as resolved
