### ISSUE TITLE
Maximum Speed network mode not working

### ISSUE THREAD

**Issue by anchounio** [flyinghead/flycast#671]
Platform / OS / Hardware:  Win10
Hardware:  PC1: i5, 16gb of RAM, PC2: i7, 8gb of RAM
Tested in the newest dev version [1523faf](https://github.com/flyinghead/flycast/commit/1523faf) (17th june) and in the newest master version [afd07c2](https://github.com/flyinghead/flycast/commit/afd07c2) (11th june) compatible with Windows

After having configured both games for server in one PC and client on the second pc,   Flycast will load the game as if it wasn't configured to network play, I mean, just load the game files, no waiting players screen. 

Furthermore, Maximum Speed doesn't save any communication config change done inside the test menu. After setting one PC for master and the second to slave, the game shows a red triangle error (lower left of the screen) in both PC's and they won't sync at all:
![20220618_200314](https://user-images.githubusercontent.com/55632087/174451182-a10b4854-7abb-436e-a1c2-7bb06f63f8fe.jpg)

If you close and open the game again, communication settings will be automatically set to OFF. 

The game was supposed to be ready to be played in network in flycast, according to this previous closed request:
https://github.com/flyinghead/flycast/issues/552

**Comment by flyinghead** [comment]
What settings are you using on the server and client PCs?
You should have:
- on both server & client: Enable Naomi Networking
- on server: Act As Server
- on client: Server: (server IP address)

Leave the local port to default (37391) if server and client are on different machines

You normally don't need to use the service menu as this is configured automatically when enabling networking.

**Comment by anchounio** [comment]
emu.cfg for server PC:

[MAXIMUM SPEED]
config.Dreamcast.Region = 1
network.ActAsServer = yes
network.EmulateBBA = yes
network.Enable = yes


emu.cfg  in client PC:
[MAXIMUM SPEED]
config.Dreamcast.Region = 1
network.EmulateBBA = yes
network.Enable = yes
network.server = 192.168.0.1


Anyway, FLYCAST will always load this game as if no network settings were applied, ignoring them.  The "waiting for players" or "waiting for server " screens on both computers will not even appear. The emulator just loads the game as if no network options were configured.

I know how to configure network games in flycast, I've had no problems in loading setting up alient front, faster than speed, wave runner, inid D 3......

**Comment by flyinghead** [comment]
EmulateBBA isn't needed for maximum speed as it uses the serial port.
The rest should be fine unless there's an issue with per-game settings. It would be good to test without them just in case.

There's no waiting screen at startup because it's not needed for Atomiswave games (ftspeed and maxspeed): they can synchronize long after boot and can recover from disconnections.

**Comment by anchounio** [comment]
I've tested it without network.EmulateBBA=yes. The result is the same.

**Comment by flyinghead** [comment]
It could be due to Windows Firewall or some other network protection utility. Make sure to give flycast permissions to act as a server. Or even better: temporarily disable all protection when playing.

**Comment by anchounio** [comment]
Done. I don't have this problem with other games in flycast. I'm connecting the same 2 computers where I've had no problems in linking alient front, faster than speed, wave runner, inid D 3 or the king of route 66. 

By the way, for faster than speed I've had to change the test menu, configure one as Master, other as Slave. The emulator was not setting this up automatically. Could it be related?

**Comment by flyinghead** [comment]
You shouldn't have to change anything in the service menu as this is done automatically. The only requirement is to enter the service menu at least once and save to create the initial .nvmem file. If it's not done automatically then either the .nvmem doesn't exist (unlikely) or flycast isn't enabling networking. Have you tried not using per-game config in case there's a bug there?
Anything in the logs on the client or server?

**Comment by flyinghead** [comment]
Another thing to try: set the server IP also on the server PC but use the client IP.
client:
```
[network]
server = 192.168.0.1
ActAsServer = no
Enable = yes
```

server:
```
[network]
server = 192.168.0.2
ActAsServer = yes
Enable = yes
```

**Comment by flyinghead** [comment]
I confirm that the per-game network settings for maximum speed were ignored.

It should be fixed in the latest master build.
