### ISSUE TITLE
Controls in the king of route 66 don't work in network mode.

### ISSUE THREAD

**Issue by anchounio** [flyinghead/flycast#673]
Platform / OS / Hardware: Win10
Hardware: PC1: i5, 16gb of RAM, PC2: i7, 8gb of RAM
Tested in the dev version [1523faf](https://github.com/flyinghead/flycast/commit/1523faf) (17th june).

Controls in the king of route 66 don't work in network mode.
No problem with the controls in single mode, but they won't work in network for both server PC and client.

Logs in serve PC:

00:00:000 rend/dx11/dx11context.cpp:38 N[RENDERER]: DX11 Context initializing
00:00:025 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (2560 x 1080)
00:00:125 rend/dx11/dx11context.cpp:156 N[RENDERER]: No system-provided shader cache
00:00:125 rend/gui.cpp:272 N[RENDERER]: Screen DPI is 96, size 2560 x 1080. Scaling by 1.00
00:00:127 rend/dx11/dx11context.cpp:286 N[RENDERER]: Swapchain resized: 2560 x 1080
00:00:128 rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 271 shaders from C:\Master1\FLYCAST\data\dx11_shader_cache.bin
00:00:161 rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
00:00:169 rend/dx11/dx11context.cpp:286 N[RENDERER]: Swapchain resized: 2560 x 1080
00:01:912 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:01:926 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff4184a0000 RAM(16 MB) 00007ff4244a0000 VRAM64(8 MB) 00007ff41c4a0000 ARAM(2 MB) 00007ff4384a0000
00:01:935 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:01:962 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff4184a0000 RAM(32 MB) 00007ff4244a0000 VRAM64(16 MB) 00007ff41c4a0000 ARAM(8 MB) 00007ff4384a0000
00:03:061 hw/naomi/naomi_cart.cpp:584 N[NAOMI]: NAOMI GAME ID [THE KING OF ROUTE66] region ff players 0 vertical 1
00:03:061 emulator.cpp:212 N[BOOT]: Game ID is [THE KING OF ROUTE66]
00:03:070 hw/naomi/naomi_flashrom.cpp:206 N[NAOMI]: EEPROM: horizontal monitor orientation
00:03:086 network/naomi_network.cpp:96 N[NETWORK]: Waiting for slave connections
00:23:117 network/naomi_network.cpp:117 N[NETWORK]: Master starting: 1 slaves
03:25:770 rend/dx11/dx11_renderer.cpp:167 N[RENDERER]: DX11 renderer terminating
03:25:776 rend/dx11/dx11context.cpp:169 N[RENDERER]: DX11 Context terminating
03:25:779 rend/dx11/dx11_shaders.cpp:681 N[RENDERER]: Saved 271 shaders to C:\Master1\FLYCAST\data\dx11_shader_cache.bin

Logs in client:

00:00:000 rend/dx11/dx11context.cpp:38 N[RENDERER]: DX11 Context initializing
00:00:036 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1536 x 864)
00:01:133 rend/dx11/dx11context.cpp:156 N[RENDERER]: No system-provided shader cache
00:01:134 rend/gui.cpp:272 N[RENDERER]: Screen DPI is 120, size 1536 x 864. Scaling by 1.00
00:01:136 rend/dx11/dx11context.cpp:286 N[RENDERER]: Swapchain resized: 1920 x 1080
00:01:137 rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 271 shaders from C:\Slave2\FLYCAST\data\dx11_shader_cache.bin
00:01:197 rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
00:01:204 rend/dx11/dx11context.cpp:286 N[RENDERER]: Swapchain resized: 1920 x 1080
00:02:422 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:02:435 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff492dd0000 RAM(16 MB) 00007ff49edd0000 VRAM64(8 MB) 00007ff496dd0000 ARAM(2 MB) 00007ff4b2dd0000
00:02:444 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:02:469 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff492dd0000 RAM(32 MB) 00007ff49edd0000 VRAM64(16 MB) 00007ff496dd0000 ARAM(8 MB) 00007ff4b2dd0000
00:03:409 hw/naomi/naomi_cart.cpp:584 N[NAOMI]: NAOMI GAME ID [THE KING OF ROUTE66] region ff players 0 vertical 1
00:03:409 emulator.cpp:212 N[BOOT]: Game ID is [THE KING OF ROUTE66]
00:03:416 hw/naomi/naomi_flashrom.cpp:206 N[NAOMI]: EEPROM: horizontal monitor orientation
00:03:423 network/naomi_network.cpp:165 N[NETWORK]: Connecting to server
03:30:890 rend/dx11/dx11_renderer.cpp:167 N[RENDERER]: DX11 renderer terminating
03:30:894 rend/dx11/dx11context.cpp:169 N[RENDERER]: DX11 Context terminating
03:30:895 rend/dx11/dx11_shaders.cpp:681 N[RENDERER]: Saved 271 shaders to C:\Slave2\FLYCAST\data\dx11_shader_cache.bin

**Comment by anchounio** [comment]
The curious thing is that controls work in the input test menu of each instance of the game, server and client... but once the game is linked and playing in both PC's, you cannot even press start.

**Comment by flyinghead** [comment]
Yes, it's a known issue.

**Comment by anchounio** [comment]
So cool. 
Thank you !!!  :)
