### ISSUE TITLE
[REQUEST / NAOMI / INPUT] Analog Axes Saturation (example: too fast steering in initdexp)

### ISSUE THREAD

**Issue by cinnamonmatexfce** [flyinghead/flycast#675]
Heya @flyinghead!
Ingame steering wheel in `Initial D Arcade Stage (Export, Rev A) (GDS-0025A)` turns left/right **too fast**! 
Is there some sort of settings to calibrate / adjust the saturation of analog axes?
I know there's an option you can adjust in _Supermodel_ (_SEGA MODEL3 emulator_), here's some infos:

```
InputJoy**Saturation:

The saturation of a joystick axis is the point at which
the axis is considered to be at its most extreme position.  It can be thought
of as a measure of the sensivity of the axis.  Like the dead zone, it is 
expressed as a percentage of the axis range but its value may be larger than 
100, up to a maximum of 200.  A value of 50 means that the joystick only needs 
to be moved halfway in order for Supermodel to see it as fully extended.  
Conversely a value of 200 means that when the joystick is at its extreme 
position Supermodel will see it as only halfway.  The default sensitivity is
100%, which corresponds to a 1-to-1 mapping.  For playing driving games with a
game pad, it is sometimes a good idea to use a value larger than 100% so that 
the steering feels less sensitive on a thumbstick.
```

I'm reporting you _Supermodel_ 'cause it also implement input system via `SDL` too.
Here's the code: https://github.com/trzy/Supermodel

Could this feature be implemented into Flycast also?

**Comment by flyinghead** [comment]
available on the `dev` branch:
![image](https://github.com/flyinghead/flycast/assets/16261910/f8c1ab97-c62b-444d-969d-ed0becf6f338)

**Comment by flyinghead** [comment]
available on the `dev` branch:

**Comment by blisstik** [comment]
@flyinghead - is it possible to add this to RetroArch build?

**Comment by flyinghead** [comment]
This is only available (and needed) for standalone.
RetroArch already has settings to adjust dead zone and sensitivity of analog sticks.

**Comment by noisebombherrera-web** [comment]
If i use keyboard how to set this?
