### ISSUE TITLE
Switch: Emulator freezes after switching between dock to portable mode and vice versa.

### ISSUE THREAD

**Issue by Mark-Shun** [flyinghead/flycast#676]
Platform / OS / Hardware: Nintendo Switch (First version) (Atmosphere firmware)

Github hash: 3d5fd612

Hardware: ARM64, Open GL NV120

**_Description of the Issue_**

While playing Flycast on the switch, switching between docked and portable mode (and vice versa) results in the emulator freezing up. The emulator doesn't respond to any inputs, resulting in you having to close the software in Switch's home menu.

**_Debugging Steps Tested_**

  * All steps were done with different games.
  * Switched from portable mode to docked mode without pausing Flycast (results in a black screen and a frozen state).
  * Switched from docked mode to portable mode with pausing Flycast (results in the screen being scaled a bit and a frozen state).
  * Switched from portable mode to docked mode with pausing Flycast (results in the screen being downsized and a frozen state).
  * Switched from portable mode to docked mode with pausing Flycast (results in the screen being scaled a bit and a frozen state). 
  * Switched from docked mode to portable mode without pausing Flycast but first returning to Switch's home screen. (results in the screen being downsized a bit and a frozen state)

**_Logs Gathered_**

```
```

**_Screenshots_**
_From portable mode to docked mode without pausing._
![PSO Portable](https://user-images.githubusercontent.com/57092443/175765730-bfa459c6-5e02-48aa-bcee-ffb4ca8f679f.jpg)
![PSO Docked](https://user-images.githubusercontent.com/57092443/175765736-a575c7e4-937e-443e-96f8-7fcae25951a6.jpg)

_From docked mode to portable mode with pausing._
![SA Docked](https://user-images.githubusercontent.com/57092443/175765748-6a01c1bd-7788-40c2-bd64-b33a6ffe8b1e.jpg)
![SA Portable](https://user-images.githubusercontent.com/57092443/175765750-358296fe-1397-4ad3-9541-d6f0bdda94e5.jpg)

_From portable mode to docked mode with pausing._
![Tokyo Portable](https://user-images.githubusercontent.com/57092443/175765796-b81167c4-617e-4f73-b654-5126d0619257.jpg)
![Tokyo Docked](https://user-images.githubusercontent.com/57092443/175765798-280559c8-571d-4aa6-a24b-39a5ebd22fd7.jpg)

_From docked mode to portable mode without pausing but first returning to Switch's home screen and then returning to the application._
![SA2 Docked with home](https://user-images.githubusercontent.com/57092443/175765815-a8fbdac1-76cf-46a9-b6ab-62ab3f3105f2.jpg)
![SA2 Portable with home](https://user-images.githubusercontent.com/57092443/175765817-55228866-6378-4a04-8ed3-80bf95c9d527.jpg)

**Comment by flyinghead** [comment]
Does it work if you switch when no game is started?

**Comment by Mark-Shun** [comment]
> Does it work if you switch when no game is started?

Yes the same issue happens when switching with no game started (a.k.a in the Flycast menu)

**Comment by flyinghead** [comment]
I pushed a fix for the UI scaling issue after switching mode. Let me know if it's fixed or not. Thanks.

**Comment by Mark-Shun** [comment]
> I pushed a fix for the UI scaling issue after switching mode. Let me know if it's fixed or not. Thanks.

Both the freezing and wrong UI scaling during mode switching, seem to have been fixed.
Thank you.
