### ISSUE TITLE
Add support for more controllers: maracas (Samba de Amigo), Pop'n Music, ...

### ISSUE THREAD

**Issue by AltoRetrato** [flyinghead/flycast#681]
Hi there!

On a quick glance at the source of flycast, it seems to support several Dreamcast peripherals (even lightguns!), but it doesn't seem to support maracas for _Samba de Amigo_ and _Samba de Amigo: Ver. 2000_ or the Pop'n Music controller.

<a href="https://user-images.githubusercontent.com/22997468/177024275-449c6b3f-9942-49ac-adcb-9c5b56785a9b.png"><img src="https://user-images.githubusercontent.com/22997468/177024275-449c6b3f-9942-49ac-adcb-9c5b56785a9b.png" width="400" height="300"></a> <a href="https://user-images.githubusercontent.com/22997468/177024487-e913ae84-2424-4b10-b77e-994030853d57.png"><img src="https://user-images.githubusercontent.com/22997468/177024487-e913ae84-2424-4b10-b77e-994030853d57.png" width="400" height="300"></a>
(Images from https://bordersdown.net/content/400-Dreamcast-Peripherals-and-Hardware-List-with-photos&new_comment)

Would it be possible to add support for at least the maracas controllers in flycast?

Of course, there is also the issue of connecting those peripherals to the computer running flycast, but they can also be emulated with other devices (e.g., VR controllers).

**Comment by AltoRetrato** [comment]
If possible, I would like to get some guidance about how I could implement maracas support in Flycast.

I read the [Samba de Amigo US Dreamcast US manual](https://segaretro.org/File:Samba_De_Amigo_Dreamcast_US_Manual.pdf) and the maracas [US Patent US 7331856 B1](https://segaretro.org/File:Patent_US7331856.pdf). Each maraca has (patent pg 31, pg. 60 col 18 line 37, pg 62 col 22 line 16):
- 1 button
- 1 internal vibration switch
- Y & X (height and lateral positions)

This [DC Emulation post](https://dcemulation.org/phpBB/viewtopic.php?p=757029) gives more details:
- left maraca position shows up as 1st analog stick, right maraca is 2nd
- maracas position range from 0, 0 (bottom left) to 255, 255 (top right)
- right maraca shake = A button
- left maraca shake = B button
- right maraca button = Start
- left maraca button = ?

I'm new to Libretro, so I read all the [Libretro Docs for Developers](https://docs.libretro.com/development/libretro-overview/). From that, I think maracas can be implemented as an _Analog RetroPad_ (RETRO_DEVICE_ANALOG).

Now I'm reading the files in https://github.com/flyinghead/flycast/tree/master/core/hw/maple , and I'm wondering how much low level information I need to know / get from the maple bus about the maracas - and how to get it.

Could / should I write a program using [DreamSDK](https://www.dreamsdk.org/) / [KallistiOS](http://gamedev.allusion.net/softprj/kos/index.php) to get that info? What exactly would I need to get? (maple function ID, device name, capabilities, ...)

Any comments or suggestions are welcome. Thanks!

**Comment by AltoRetrato** [comment]
And I think I've found another GPL project that might have most (or all) the information needed to support maracas and fishing rod: [240p Test Suite](https://github.com/ArtemioUrbina/240pTestSuite) - e.g., see https://github.com/ArtemioUrbina/240pTestSuite/blob/master/240psuite/Dreamcast/PVR/controller.c

**Comment by flyinghead** [comment]
This is the document you need for this task:
https://github.com/Kochise/dreamcast-docs/blob/master/CONTROLR/DOCS/14_marah099e.doc

Some suggestions:
- Maracas will need to be supported in both standalone and libretro, so it might be easier to first make it work with standalone first, then add support and button/axes mapping for libretro.
- Please fork the `dev`branch and make a PR for this branch.
- The tasks to do this implementation are:
  - Add a new maple device type for maracas in hw/maple/maple_cfg.h (Do NOT change existing types, so add it between MDT_None and MDT_Count)
  - Add a new device class in maple_dev.cpp for the maracas. Derive from `maple_base` or perhaps even `maple_sega_controller` (after all maracas is just a controller with analog axes and buttons)
  - Add a new savestate version in `serialize.h` (which should be `V36` and update `Current` to point to it). This is required to avoid older flycast versions to crash if they load a savestate with a maracas attached.
  - Add maracas to the list of maple devices available in `rend/gui.cpp`

At this point maracas should work in standalone. Then for libretro you need to add maracas to the list of controller available (shell/libretro.cpp) probably as a subtype of retropad (like twin stick and ascii stick), and do the button and axes mapping (RETRO_DEVICE_ANALOG and RETRO_DEVICE_JOYPAD)

**Comment by AltoRetrato** [comment]
I got the Pop'n Music functioning properly (I guess), and I'm trying to implement other controllers as well.

I just could not understand one part so far. In `core\hw\maple\maple_devs.cpp`, how did you get the value `0xF901`?
```C++
struct maple_sega_controller: maple_base
{
	virtual u32 transform_kcode(u32 kcode)
	{
		mutualExclusion(kcode, DC_DPAD_UP | DC_DPAD_DOWN);
		mutualExclusion(kcode, DC_DPAD_LEFT | DC_DPAD_RIGHT);
		return kcode | 0xF901;		// mask off DPad2, C, D and Z;
	}
```

**Comment by AltoRetrato** [comment]
The Maracas have four analog axes (two for each maraca)... I can map two axes (Thumbstick U/D & &L/R) to a controller, and they seem to be working. Is there any way to map the other two axes?

**Comment by flyinghead** [comment]
You need to make changes to the UI in order for the Right Thumbstick to appear in console mode and be able to bind it. Right now it doesn't appear because none of the supported Dreamcast controllers has a right joystick, until now.
SImply copy the `DC_AXIS2_*` entries from `arcadeButtons` to `dcButtons` in rend/gui.cpp.

**Comment by AltoRetrato** [comment]
Maracas are working! I haven't tested them extensively (yet!), but the only "issue" I've seem so far is that they are only detected / recognized in _Samba de Amigo_ and _Samba de Amigo Ver. 2000_ when connected to ports A or B (even though they work in the 240p Test Suite on ports C & D).

Now I'm trying to implement support for the fishing controller, but it has built-in vibration. Do you have any tips on how I can do it?

**Comment by flyinghead** [comment]
This is the spec document for the fishing controller: https://github.com/Kochise/dreamcast-docs/blob/master/CONTROLR/DOCS/10_tsurih080e.doc
It includes a vibration function which should similar to the purupuru/vibration pack (see `maple_sega_purupuru` in maple_devs.cpp)

**Comment by AltoRetrato** [comment]
I've seen the document and the `maple_sega_purupuru` before, but the fishing controller have two device IDs, type FT0 (the "device", that I've already implemented) and FT8 ("expansion device"), and the `dma` function in the structure seems to be relative to a single device.

So one way to solve it (I guess) would be creating a purupuru in `createDreamcastDevices()`  (`maple_cfg.cpp`):

```C++
		case MDT_FishingController:
			mcfg_Create(MDT_FishingController, bus, 5);
			mcfg_Create(MDT_PurupuruPack, bus, 0);
			break;
```

... but I'm not sure if that is the correct way.

**Comment by flyinghead** [comment]
I added support for vibration to the fishing controller. Contrary to what I wrote above, the vibration device is distinct from the input controller and has its own maple bus address.  So it was just a matter of adding a vibration pack at this address along with the fishing controller. See 231a1b624ff5dc14243f24dd49553e0d1a89093c

**Comment by AltoRetrato** [comment]
Awesome! Thank you! :D

Now I'll soon take a look at the libretro interface.

**Comment by AltoRetrato** [comment]
Thank you SO MUCH for your help and patience! Thanks to you, today I played Samba de Amigo in VR (my first VR project as well) and it felt just like old days (_really_ old, almost 20 years ago)! 😄 I'll give it some polish and publish it later for anyone who wants to give it a try.

And with #1123 , I think we can close this!

**Comment by flyinghead** [comment]
Thanks a million for your help!
