### ISSUE TITLE
Doom for naomi: black screen

### ISSUE THREAD

**Issue by telanus** [flyinghead/flycast#682]
Could flycast support this.  https://github.com/DragonMinded/naomidoom

**Comment by flyinghead** [comment]
Note: Doom does direct framebuffer writes but the current detection mechanism doesn't work.

**Comment by flyinghead** [comment]
Actually I was wrong: it's a different issue. A fix is coming.

**Comment by flyinghead** [comment]
This should be fixed on the dev branch
