### ISSUE TITLE
Publish Flycast on Google Play

### ISSUE THREAD

**Issue by kalessive** [flyinghead/flycast#685]
Issue:
It is difficult to update Flycast on Android as there is no built in updater and manually updating via APK files isn't ideal for the average person.

Solution:
I would like the standalone version to get published on Google Play. It will ensure that Flycast is available from an official source and make it easy to update.

**Comment by WingofaGriffin** [comment]
Agreed. Even a F-Droid repo will be a nice way to keep updated.

**Comment by flyinghead** [comment]
Flycast is available as a closed beta on Google Play.
![image](https://github.com/flyinghead/flycast/assets/16261910/c2fc5e93-64c6-4fd2-8ce4-be27a74e6bcf)
Join our Discord if you want to participate

**Comment by flyinghead** [comment]
Flycast is now available on Google Play
https://play.google.com/store/apps/details?id=com.flycast.emulator
