### ISSUE TITLE
Wild Riders - Custom Controller Mappings

### ISSUE THREAD

**Issue by kathyrollo** [flyinghead/flycast#689]
**Is your feature request related to a problem? Please describe.**
The default mapping on the Xbox One controller is clunky. I'm using Flycast standalone without RetroArch.

**Describe the solution you'd like**
I'd like to map a custom config:
Handlebar = L-Stick
Accelerator = R-Trigger
Front Brake = L-Trigger
Rear Brake = L-Bumper
Push/Slide = R-Stick UP
Pull/Jump = R-Stick DOWN
Start/View = Menu Button

Thanks!

**Comment by kathyrollo** [comment]
The controls are pre-designated in this game. You can't map the right-stick to jump/slide and it has to be the dpad. 

What's wrong with the rear brake of this game?

**Comment by superblobster** [comment]
> You can't map the right-stick to jump/slide and it has to be the dpad.

Yes you can. I've got it mapped pretty much like you said, except for the rear brake which was causing the problems mentioned in https://github.com/flyinghead/flycast/issues/602 and isn't necessary. 

Here are my mappings:
![Screenshot 2022-07-21 135341](https://user-images.githubusercontent.com/60817163/180197875-514778cc-689c-402a-9af6-86f23282d6a1.png)

**Comment by kathyrollo** [comment]
Hi @superblobster , your screenshot appears different from mine. Are you using standalone or core? I am using standalone and this is what it looks like:

![Screenshot_1](https://user-images.githubusercontent.com/28589393/180358254-eff667bb-b328-48e0-ac5a-38c9f0c2485a.jpg)

It doesn't have the "Make Game Config" button at the top and no per-game button config like "Front Brake" and "Accelerator" shown in yours.

I found #115 and @flyinghead mentioned no per-game button support yet for standalone. Is this still the case?

**Comment by superblobster** [comment]
Seems like you might be on a really old build then. I've got the latest one from here: https://flyinghead.github.io/flycast-builds/

**Comment by kathyrollo** [comment]
Hi @superblobster , I am on build 30-Jun actually so it's pretty new. I update standalones every month. I'll get the latest July build and see if that's implemented there. 

What standalone version are you using? If you're using the RetroArch core, I think it's always been there.

**Comment by kathyrollo** [comment]
Hey @superblobster , I'm on the latest standalone 15-Jul devbuild but no juice for the per-game button config. How do you get to it?

I just go: Settings > Controls > Xbox One Controller > Map

**Comment by flyinghead** [comment]
You need to start a game first.

**Comment by kathyrollo** [comment]
Dude @superblobster I got it! Now it's perfect!

![Screenshot_1](https://user-images.githubusercontent.com/28589393/180422291-1eb526d1-e340-4d43-885f-ad17972321d2.jpg)

Didn't notice the per-game settings because I was just doing save/load states, so I just assume that was global. Thanks, it's what I wanted.
