### ISSUE TITLE
Cabinet config not loading when using external frontend

### ISSUE THREAD

**Issue by LuismaSP89** [flyinghead/flycast#69]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Windows 10 x64
16GB DDR3
GTX 970
i7 4790k

**_Description of the Issue_**

Some problems with .zip games from naomi "Such as metal slug 6" the games works fine when the're opened in flycast, if you change the rom settings in the cabine config menu, it creates 2 nvmem files, and this is correct. 

The problem begins if you use an external frontend to load games "such as launchbox" the games are running well, but this config stored in the nvmem files are not loaded, and every time you open a game its like the first time, no config of the nvmem is loaded. Also you can see the "Notice: All backup data was cleared".

I don't know if this can be a clue, but if you enter to the cabinet config, made some changes, and then exit. The emulator just crashes. This doesn't happen when the emulator is used by itself, without a frontend.

I don't know if this is expected because flycast uses a command line parameter to load these nvmem files since there's no more info or file showing the command line options/parameters of flycast.

**_Debugging Steps Tested_**

 -Use a frontend such as lauchbox to load an arcade game "Mslug 6 in my case"
-Open the cabinet config and do some changes "For example set freeplay mode"
-Exit and run again the game. The changes are not saved/loaded in the next run. Also when you exit after the changes in the cabinet filesystem, the emulator crashes. 
-All this steps are working fine, without external frontend, the emulator saves the cabinet changes, restarts, and load the changes as it should.

**Comment by flyinghead** [comment]
On windows, flycast will use the current directory as home directory (where the `data` folder is).

I suppose the current directory is different when started directly and when started by a front-end. One way around this is to create a .BAT file that changes to the correct directory and starts flycast from there.

Something like:
```
@echo off
cd C:\path\to\flycast
.\flycast.exe %1
```
then instruct your front-end to run this batch file instead of flycast.exe.

**Comment by LuismaSP89** [comment]
@flyinghead Tested, and the result is the same. When I enter in the cabinet config, do some changes, and then exit. Game crashes. Using flycast.exe standalone reboots after the changes and these changes are loaded everytime you enter again ingame.

Could you please tell me, what is the parameters or command line to load a naomi game? Maybe I can add to the launchbox. Because all other megadrive games are working fine. This problem only happens with arcade cabinet games with nvmem.

**Comment by flyinghead** [comment]
Sorry for the delay. Can you try the latest build? https://github.com/flyinghead/flycast/commit/d75d4400f0d86dd9d7c933900cace8ceed8b57bb
This might fix your issue

**Comment by LuismaSP89** [comment]
@flyinghead Don't worry, I assume you're busy, you don't have to apologize.

Works like a charm, thanks a lot for your work man, closing the issue. ; )

**Comment by flipperlaci** [comment]
Hello Members!
Can I make a .bat file for flycast to run a specified rom instatly and silently?
I have a pc in an old vintage arcade cabinet, and my goal is to run its original game only. I managed to run and configured well, I just hete the thing to i had to have a mouse near by to start the app and the game from the list every time.
I just want to switch on my pc let the win boots, and start flycast with the selected app. 
I think a good old bat should solve my issue, just did not find command and exaple for this.
Is it possible to get some help?

**Comment by cinnamonmatexfce** [comment]
> Hello Members!
> Can I make a .bat file for flycast to run a specified rom instatly and silently?
> I have a pc in an old vintage arcade cabinet, and my goal is to run its original game only. I managed to run and configured well, I just hete the thing to i had to have a mouse near by to start the app and the game from the list every time.
> I just want to switch on my pc let the win boots, and start flycast with the selected app. 
> I think a good old bat should solve my issue, just did not find command and exaple for this.
> Is it possible to get some help?

https://github.com/TheArcadeStriker/flycast-wiki/wiki/Configuration-files-and-command-line-parameters

**Comment by flipperlaci** [comment]
Success! Thanks!
