### ISSUE TITLE
18wheelr: wheel unresponsive in game when fully deflected left or right

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#693]
Platform / OS / Hardware: win10 1809

Github hash: с77с3ab

Hardware: intel i3 + hd 5300 + dx11

Issue:

18wheelr left and right handle is invalid。the same also 18wheelrt 18wheels exept 18wheelu

**Comment by flyinghead** [comment]
Not sure what you mean exactly by "invalid".

There's a known issue affecting all arcade versions of this game except `18wheelu` (upright):
When the wheel is turned past a certain point, to the left or to the right, the wheel stops reacting as if it was centered.

**Comment by crashGG** [comment]
it means the steering wheel left and right of the truck cannot be controlled in the game

**Comment by flyinghead** [comment]
Apart from the issue I mentioned above, this game's input are working fine. Check the input tests in the game test menu.

**Comment by crashGG** [comment]
In the test menu, there is feedback on the left and right of the steering wheel
![1](https://user-images.githubusercontent.com/80488411/178923122-c0708099-f5d1-45de-a96f-70be653b2f97.png)
In the character selection menu, other characters and trucks can be selected from the left and right of the steering wheel.,
<img width="587" alt="2" src="https://user-images.githubusercontent.com/80488411/178923311-b1683653-6512-46a3-b8a6-1b70c5f0c81c.png">
but...
 steering wheel left and right of the truck cannot be controlled in the game

**Comment by crashGG** [comment]
I have tested 18wheelu, this clone works fine!

**Comment by crashGG** [comment]
> Have you calibrated controls? I think you can do it inside the volume settings in the test menu.

this game's volume settings in the test menu can only set the center of the handle.
Yes, I can see number feedback on the screen when I flip the joystick, but I think it's best not to change the centering. Otherwise, the truck will be offset to one side in the game.

**Comment by Hydreigon223** [comment]
It's because all versions but upright use a rotary encoder for the wheel instead of analog. Worked on one of these back in the day and was blown away when I looked at the inside of the control panel.

**Comment by flyinghead** [comment]
Wheel range is now limited to avoid the issue.

In addition the drive motor board is emulated enough to avoid the on screen error message with the deluxe version.

Finally the tri-state gear lever is simulated with 2 buttons: low/high and reverse/low.
