### ISSUE TITLE
Texture issue on nearest neighbor (regression from v1.3)

### ISSUE THREAD

**Issue by Riccardoman** [flyinghead/flycast#695]
dev build commit 9d17fc1 | 2022-07-14T14:52:35.000Z
![Screenshot_1468](https://user-images.githubusercontent.com/74624503/179257168-e9de456c-eb3c-4951-bd15-90a92eb88136.jpg)

vs the 1.3 release
![Screenshot_1467](https://user-images.githubusercontent.com/74624503/179257273-ba411771-e04f-433d-9e8f-43d7c37d8173.jpg)

notice the square lines and the character portraits

**Comment by flyinghead** [comment]
Do you have the `Texture Filtering` setting set to `Force Nearest Neighbor`?

**Comment by Riccardoman** [comment]
Yes
anisotropic 16x and internal resolution x3, OpenGL
It worked perfectly in v1.3

**Comment by flyinghead** [comment]
There was a change since 1.3 to disable anisotropic filtering with nearest, but it should have the opposite effect...

**Comment by Riccardoman** [comment]
It changed for the better but only slightly, there are still artifacts
![Screenshot (1469)](https://user-images.githubusercontent.com/74624503/179261511-12fa185b-8f95-4495-a5d8-b136ba059e6c.jpg)

**Comment by flyinghead** [comment]
The change is due to cf36384481a165c6c1c609dbb38caa7ea9de4543: If texture filtering is forced to nearest then the final framebuffer itself is drawn with nearest filtering. The idea being that people who force filtering to nearest want crispy clear pixels without any filtering whatsoever.

Anisotropic filtering should also automatically be disabled when using nearest as is already the case for Vulkan.

**Comment by Riccardoman** [comment]
would it be possible to make it a toggable option? some source ports like vkquake support that because not everybody likes unfiltered nearest, if I remember correctly supersample should be the way to go

**Comment by Riccardoman** [comment]
It was just a suggestion, sorry if I sounded as if I was complaining, thank you for your contribution
Hope to see more advanced video settings in the future

**Comment by flyinghead** [comment]
I didn't hear any complaint and my response wasn't personal in any way. Thank you for reporting this issue since it helped fix the problem at least partially.
