### ISSUE TITLE
Spawn (Naomi) EEprom not saving or being overridden with defaults on a fresh boot

### ISSUE THREAD

**Issue by normchomsky** [flyinghead/flycast#696]
Platform / OS / Hardware: Windows 10

Github hash: 

Hardware: AMD 1850 GTX960

**_Description of the Issue_**
When booting this game you need to change Network to OFF in the test menu otherwise it'll just be checking the network constantly and not boot. I save and exit after changing this, booting into the game from the test/service the game and it plays just fine. However on a fresh boot it has reverted back to Network = Slave. So the EEprom is not saving correctly or it is being overridden on a fresh boot.

This causes the user to select Network = Off on every play session as it doesn't play in Slaver or Master

**Comment by flyinghead** [comment]
Using retroarch?

**Comment by normchomsky** [comment]
Sorry yeah RA, will make sure to mention that in the future

**Comment by flyinghead** [comment]
Flycast overrides the EEPROM network settings for this game. Since Naomi networking isn't supported on RA it should always sets Network to OFF at boot, which it does on my machine but not on yours for some reason.

Try to locate and delete any `spawn.zip.eeprom` file you can find in retroarch config/saves files.

**Comment by normchomsky** [comment]
It does the same thing. RA Enables Network automatically on this game as notification pops up. Could be an RA issue. Just trying to think why mine wont auto set network to off

**Comment by flyinghead** [comment]
Another basic question I shouldn't have to ask: what's the version of the core you're using?

**Comment by flyinghead** [comment]
Thank you very much for your contribution! You don't deserve a fine though ;) Most people omit crucial information when reporting issues.

Your Flycast version dates from May 1, so it's not that recent. I would suggest you upgrade Flycast with RA core updater.

**Comment by normchomsky** [comment]
Updated to c77c3ab and still the same issue. Tried disabling free play toggle as thought that may be causing a clash with the NVMEM/EEPROM, but alas no change

**Comment by flyinghead** [comment]
As far I know there's only one version of this game so that shouldn't be an issue. Can you confirm you are using the `spawn.zip` MAME rom?

**Comment by normchomsky** [comment]
yes confirmed, I am using that rom

**Comment by flyinghead** [comment]
Are you loading any savestate, manually or automatically? A savestate contains the eeprom data so it would override Flycast's settings.

Can you try Flycast standalone and check if the issue is there as well?

**Comment by normchomsky** [comment]
This is now fixed with the core and standalone. Thanks for the updates.

**Comment by kihato** [comment]
It seems that a regression issue occurred due to commit fa1c62d.
This only occurs when the EEPROM is missing.

<img width="642" height="512" alt="Image" src="https://github.com/user-attachments/assets/ca080300-2224-49ea-8482-150d1ea6a78b" />

**Comment by flyinghead** [comment]
This game needs the correct region number set in the eeprom. If it doesn't match the current region, the eeprom is reset to default, which is network enabled as slave.
This should be fixed on the `dev` branch.
