### ISSUE TITLE
Canon Spike (Naomi) controls not present and strangeness

### ISSUE THREAD

**Issue by normchomsky** [flyinghead/flycast#697]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: RetroArch Windows 10

Github hash: 

Hardware: AMD 1850 GTX960

**_Description of the Issue_**
There are only 3 inputs labeled Mark, Attack, Shoot. There are 4 buttons in the input test menu. However when in game L2 is Heavy Attack is and R2 is Special Attack despite not being present in the controller config screen. What's even more strange is that the total number of buttons is 5 with the input test menu showing 4, with no inputs at all triggering Button 4 in the test menu. Despite having access to these buttons on L2 and R2 and working in game. 

This is prohibiting remapping Mark to R2 and Heavy Attack to a face button as per the console release.

**Comment by flyinghead** [comment]
The arcade version of this game only uses 3 buttons: Shoot (btn 1), Attack (btn 2) and Mark (btn 3).
On my RA install, they are mapped to A, B, X resp. and button 4 in on Y.

The test mode indeed shows 4 buttons. I assume it's a generic test menu. When in game, button 4 is the same as button 3 (Mark).

However I don't have anything mapped on L2 or R2. Special attacks are done with key combos:
> Special attack (unleashed by pressing Shoot and Attack simultaneously), a close-range Special (Mark and Attack simultaneously), and a Super Special (all three buttons simultaneously)

**Comment by normchomsky** [comment]
Thanks for the explanation. Well that's awesome really as the button combos are mapped to R2 and L2 despite not showing in the controller config screen.

**Comment by crashGG** [comment]
I usually bind key 3 to R1, which corresponds to RB for the xbox controller
