### ISSUE TITLE
Rayman 2 menu screen flash blue

### ISSUE THREAD

**Issue by ualaa1** [flyinghead/flycast#703]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10
Github hash: 
Flycast 1.2
Hardware: 

**_Description of the Issue_**

The menu screen flashes. I paused the menu during the first level and it flashed
Does not flash when going into menu subsections as it changes backgrounds

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

[emu.zip](https://github.com/flyinghead/flycast/files/9175107/emu.zip) - Config File
https://imgur.com/a/PgKdFqY - Video Proof

**Comment by flyinghead** [comment]
I can't reproduce this issue on my platform with the same settings.

Version 1.2 is rather old. Please upgrade to latest master build: https://flyinghead.github.io/flycast-builds/

What's your GPU?

**Comment by ualaa1** [comment]
I have 2 GPUs on my laptop, but it seems that Flycast is using intel uhd graphics 630
I upgraded to 1.3 and the issue still presists.

https://imgur.com/a/7mDCYky

**Comment by flyinghead** [comment]
Using an Intel HD 640 I notice a slight flash every second or so although it's not as pronounced as in your video. It doesn't happen with DirectX 11 or with non-Intel GPUs so I suspect a driver bug.

You should probably use DX11 with Intel GPUs as it's the most reliable driver on Windows in my experience.

**Comment by ualaa1** [comment]
Tried changing to DX11. Same problem, using same GPU as DX9.
Settings for DX11:
[emu.zip](https://github.com/flyinghead/flycast/files/9186194/emu.zip)

Renders fine on Vulkan using my other GPU GTX 1650, but makes game very laggy
And trying OpenGL causes graphical glitches everywhere, using the same GPU as DX9

**Comment by flyinghead** [comment]
Make sure your GPU drivers are up to date. I would recommend using the NVidia GPU over the Intel one, and then choosing the renderer that works best (DX11, GL, VK)

All these issues look like driver/hardware problems.
