### ISSUE TITLE
Separate/Combined pedals axis

### ISSUE THREAD

**Issue by baritonomarchetto** [flyinghead/flycast#718]
Hello,

it's not a lot of time I have started toying with Flycast, so sorry if this request is already implemented.
Accelerator and brake pedals can actually be assigned to a single axis (so called combined pedals), one to one half axis, the other to the other (e.g. accel Y+, brake Y-). It would be great if separate axis for accel and brake could be assignable (a full axis for accel, another for brake). This would let the user assign them to the left and right triggers of the gamepad, a feature already available in the other two most favourite emulators of mine: supermodel and MAME :)

Thanks for all the efforts already put in the development this gem of an emulator!

**Comment by flyinghead** [comment]
Dreamcast triggers (and arcade accel/brake) are mapped to gamepad triggers (L2, R2) by default. So they can be mapped to different axes.

**Comment by baritonomarchetto** [comment]
Thanks fornyour answer . Yes, I noticed that, but from the behaviour I am experiencing I was assuming they where coded as combined axis. This is what I have mapping accel to a trigger, brake to the other (arcade map) in NAOMI Crazy Taxi
- if I have both triggers released, the car brake lights are lit (sonot is breaking). I can hear a looped sound of brakes, like it accelerate for an instant and then brakes. Forever.
- If I press  brake trigger makes the car accelerate.
- If I press accel nothing happens (but the aforementioned looped sound is no more there)
This happens to me with both a PS4 compatible gamepad and a custom made arduino interface installed in my CT.
Can anyone help me figure out what I am doing wrong? Thanks for the help so far :)

**Comment by flyinghead** [comment]
Something is wrong with your controller or your controller driver. What OS are you on?

Normally the default mapping should work. No change needed.

**Comment by baritonomarchetto** [comment]
I have made a test: I have deleted all my control mappins and tested my two controllers default settings. 
For both (ps4 compatible gamepad and arduino custom controller) the two triggers are not mapped by default.
Are there evidences of compatibility issues in windows 10?

**Comment by baritonomarchetto** [comment]
Anyone? :)

**Comment by baritonomarchetto** [comment]
Good news! 
The issue was not a combined pedals begaviour, as I thought, but an inverse axis attribution. In other words, both axis were seen as "negative" (1-, 2-). This made the car accel and brake with pedals released.
I could not find a solution through the mapping GUI, but it was possible to edit the mapping file, so it was a breeze to solve.
Hopes this helps, thanks for the kind help

**Comment by baritonomarchetto** [comment]
Made some additional tests (having success gave me the confidence to configure some additional game) and have noticed that Flycast does not always set triggers as negative (incorrect), but sometimes positive (correct). By mapping twice the same trigger, the first attempt will end negative, the next positive.
No need to modify files by hand, then: you can do it via GUI (but eventually...)
