### ISSUE TITLE
Blue Stinger (Japan) another graphical issue with Per Pixel sorting

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#721]
Platform / OS / Hardware: win10 1809

flycast: newest master and dev

Hardware: intel i3 + hd 5300 + dx11

<img width="480" alt="2022-08-25_201309" src="https://user-images.githubusercontent.com/80488411/186732859-a9ad3baa-9e9d-4022-b67e-f5168d760bf6.png">

Note: This issue looks like https://github.com/flyinghead/flycast/issues/622, but it's not.
There is a huge black hole in the sky，Per Pixel sorting and 128 layers have been set. and the US version is ok.

Sorry for submitting this issue again, because the previous submission was closed, I think some issue may have been ignored by preconceived ideas

**Comment by flyinghead** [comment]
You could have reopened the previous issue but it's fine.

**Comment by flyinghead** [comment]
Yes, different issue and only happens with the JPN release.

For some reason the sky background is drawn at a farther depth in the JPN release and it gets partially clipped by the framebuffer background depth value.
![image](https://user-images.githubusercontent.com/16261910/186745558-45727213-6424-4f60-ad9d-f2e06c1c868d.png)

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build
