### ISSUE TITLE
Virtua Tennis Naomi Do Not display black & white slow motion during attract

### ISSUE THREAD

**Issue by ledstorm** [flyinghead/flycast#729]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11x64

Github hash: https://github.com/flyinghead/flycast/releases/tag/v2.0

Hardware: 
Intel i5-4590
16 RAM DDR3
Radeon RX480

**_Description of the Issue_**

Virtua Tennis Naomi Do Not display black & white slow motion during attract. Only black screen appear

**_Debugging Steps Tested_**

Every renderer tested, same thing

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
You need to enable `Video > Render to Texture > Copy to VRAM` for the black and white texture to appear properly. However performance is then seriously affected so it's not enabled by default.

**Comment by ledstorm** [comment]
Thanks, it fix the problem, do not seem to slow down performance too much
