### ISSUE TITLE
Naomi House of the Dead Prototype Hotd2p controls are not working

### ISSUE THREAD

**Issue by ledstorm** [flyinghead/flycast#731]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: PC Windows11x64

Github hash: https://github.com/flyinghead/flycast/releases/tag/v2.0

Hardware: 
Intel i5-4590
16 RAM DDR3
Radeon RX480

**_Description of the Issue_**

Naomi House of the Dead Prototype Hotd2p controls are not working

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Should be fixed on the latest dev build
