### ISSUE TITLE
8bitdo Pro 2 X-input: Wrong Name + No Rumble

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#734]
Platform / OS : macOS Monterey

Hardware: 16" M1 Pro (10CPU/16GPU)

Controller: 8Bitdo Pro 2 Bluetooth Controller

Description:

7457db8 shows the correct name for X-input Pro 2. Both 72136c2 and aa97a6d show the generic "Xbox One S Controller" naming.

1. X-input on 8Bitdo Pro 2 is now showing as "Xbox One S Controller" under Controls.

Existing issue, regardless of commit:

2. Rumble does not work on X-input. Changing the setting from 100 to a different number does not result in any difference.

Steps Tested:

Reconfigued controllers on latest install. Did not change behavior.
All testing done via Bluetooth (macOS does not recognize X-input via wire anyway, so these issues are all on wireless).

Expected Result:

1. X-input should show the name of the actual Bluetooth controller as defined by macOS. https://github.com/flyinghead/flycast/commit/7457db8bba3277dcc9b4ec0c3556847f5082a455 did not have this issue.

2. Rumble feedback on standalone flycast via X-input (RetroArch already has this on flycast core, so maybe a similiar implementation?)

**Comment by vkedwardli** [comment]
So after updating to SDL from 2.22.0 to 2.24.0, the name being displayed is changed

What is the Product ID and Vendor ID for the 8Bitdo Pro 2 when it is on Bluetooth X-Input mode?

Could be related to https://github.com/libsdl-org/SDL/commit/be3a945a8b9ff12e78f4b0d4634d38cc89d4c418#diff-bce2446f1952efee9da1abe943d6cc1636bd219deabf59164f8c9ee3e5b700e2

**Comment by vkedwardli** [comment]
But according to the manual (https://download.8bitdo.com/Manual/Controller/Pro2/Pro2_Manual.pdf?20220513)
It is recommended to use Mode A (Apple mode) for both bluetooth and wired connection

Is there any problem for Mode A? Did you try Switch mode (I guess rumble won't work on this mode) and DInput mode also?

**Comment by rapego9596** [comment]
I don't know how to check the Product/Vendor ID. Mode A has the most latency out of the 4 modes on the Pro 2 as well as not compatible with 8bitdo Ultimate Software, so it's essentially useless. Switch mode loses analog triggers. D-input shows the correct name, but it has no rumble on any OS. X-input should have rumble, but it does not work on standalone Flycast.
