### ISSUE TITLE
[NAOMI 2] Sega Driving Simulator support

### ISSUE THREAD

**Issue by Shoegzer** [flyinghead/flycast#737]
Platform / OS / Hardware:  Linux Mint 21 / kernel 5.15

Github hash: aa97a6d64fb47d3ce0febaa575b26d975dd916e4

Hardware: Intel i7-10870H / Nvidia GTX 3070 / driver 515.65

**_Description of the Issue_**

~~A few issues observed with several NAOMI 2 sets:~~
**sgdrvsim** (Driving Simulator): Flycast reports unknown game, although this is a valid NAOMI 2 game and "supported" in MAME
~~* **clubkrt** and clones (Club Kart): Flycast cannot go ingame with most sets due to various BIOS issues such as "steering drive board is not connected" reported at startup.~~
~~* **clubk2k3** and clones (Club Kart 2003): Steering controls are reversed, and turning free play mode off does not work~~

**Comment by flyinghead** [comment]
Sega Driving Simulator isn't supported yet.

clubkrt needs "Steering Power" to be set to the minimum in the game test mode > game settings.

clubk2k3 steering direction seems to be chosen at random so invert if needed in the game test mode.
Turning free play off will not rewrite the eeprom. So after disabling it, you need to enter the service menu and change coin settings.

**Comment by Shoegzer** [comment]
Thanks, that helps. I'm happy to close this issue or we can keep it open for whenever there's time to support Sega Driving Simulator, your call.

**Comment by flyinghead** [comment]
Let's keep it open for Driving Simulator. I changed the title to reflect it.

**Comment by flyinghead** [comment]
Sega Driving Simulator now supported on the dev branch

**Comment by Shoegzer** [comment]
Great, thanks!  I see it with f186046c985fcf750d02331ff4155bc7fdd083c7. 

I assume by "partially supported" that you're still working on it before merging to master?  If so I'll hold from closing this until then.
