### ISSUE TITLE
Bug: Identical named devices control the same port despite being setup with separate ports.

### ISSUE THREAD

**Issue by adamgp** [flyinghead/flycast#74]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Win 10 Pro (Current)
Intel i5
nVidia GT740 (Current)

Github hash: 
N/A

Hardware: 
2x ZeroDelay USB JoyPad Encoders

**_Description of the Issue_**
When using devices which report with an identical name, both seem to control the same port despite being setup with different ports. On reopening Flycast both devices now show that they are mapped to the same port.

![1](https://user-images.githubusercontent.com/2965239/79454662-88581880-7fe3-11ea-87d7-c8081ae1730c.png)

Whereas the emu.cfg correctly maps the joypad device GUIDs to different ports (0 and 1).

![2](https://user-images.githubusercontent.com/2965239/79454555-59da3d80-7fe3-11ea-8af4-6d3ffdfc39fe.png)

Furthermore, the mapping cfg file is saved with the device name, meaning if it would be impossible to have two identical named devices with different button combinations.

![image](https://user-images.githubusercontent.com/2965239/79454778-b63d5d00-7fe3-11ea-8a84-13a51300f6e3.png)

Can mappings instead or also be stored with their GUIDs in the filename? Thus matching what is defined in the emu.cfg, e.g:

SDL_03000000790000000600000000000000.cfg

**_Debugging Steps Tested_**

Obtain two of the same devices and check they report to Windows with the same name, attempt to map one to port A and one to port B and load a two player game, both will either control port A or port B, whichever (I believe) I was set last.

**Comment by flyinghead** [comment]
The commit above should fix the first part of the issue.

The mapping cfg file naming is another issue because the SDL GUID are not unique. If you plug the two exact same USB devices in your machine, they'll have the same GUID. At least that's the case on Linux. So using the GUID as file name wouldn't help.

One way to solve this would be to first try to open `SDL_Generic USB Joystick-1.cfg`, then fallback to `SDL_Generic USB Joystick.cfg` if it cannot be found. This preserves backward-compatibility but there's some manual config involved for advanced usage.

**Comment by adamgp** [comment]
Confirmed, the fix fixes the inability to split identical devices between ports, thank you for resolving that.

I can also see some new mappings in the emu.cfg that I do not believe were there before:
I assume these now replace the config entries immediately above with the GUIDs which are now redundant?

![image](https://user-images.githubusercontent.com/2965239/79541231-5a291600-8081-11ea-8d32-b08b185ee612.png)

Whilst this fixes the issue, I can see it perhaps causing other knock on affects if the device order switches for anyone. But that's one for another day.

Regarding the second issue with the ability to load an override cfg file (e.g. SDL_Generic USB Joystick-1.cfg) and then falling back, that sounds like a good idea to maintain backwards compatibility. Again, the assumption is that the suffixed -X.cfg where X matches the index of the joystick_X = from the emu.cfg?

Thanks again.

**Comment by flyinghead** [comment]
>I assume these now replace the config entries immediately above with the GUIDs which are now redundant?

The GUIDs are not used anymore so these lines are ignored

>Again, the assumption is that the suffixed -X.cfg where X matches the index of the joystick_X = from the emu.cfg?

Correct

**Comment by adamgp** [comment]
Excellent, I have a test case ready for the override cfg.

![image](https://user-images.githubusercontent.com/2965239/79547106-59957d00-808b-11ea-83d8-d7f178488461.png)

![image](https://user-images.githubusercontent.com/2965239/79547133-66b26c00-808b-11ea-8133-846bb4ef5be1.png)

**Comment by flyinghead** [comment]
The latest build has the per-controller-instance mapping fix. If the regular mapping file is `SDL_USB Gamepad.cfg`, the per-instance mapping is named: `SDL_USB Gamepad-sdl_joystick_1.cfg` for the first joystick, and so on.

**Comment by adamgp** [comment]
Thank you
