### ISSUE TITLE
Problem playing Atomiswave Roms on Android

### ISSUE THREAD

**Issue by joelos1111** [flyinghead/flycast#740]
![Screenshot_2022-09-10-15-42-38](https://user-images.githubusercontent.com/113259459/189499433-e7f1d1d3-8251-44b0-90b8-278f189563e2.png)
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 8.0

Github hash: 

Hardware: 

**_Description of the Issue_**

*I can't play any Atomiswave Roms simply because there's still No option for "Free Play" with Atomiswave Roms, please flyinghead try to add that button to the options on your next update of the apk

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Use the following key combinations on the visual gamepad:
```
RT + A -> Coin
RT + B -> Service
RT + X -> Test
```

**Comment by joelos1111** [comment]
Thanks a lot bro😊👍, now i can finally play my Atomiswave Roms without any problem but please Flyinghead try to add the "Free Play" option for Atomiswave Roms on the next update of the Flycast app, i mean there's already a "Free Play" option for Naomi Roms why not have also one for Atomiswave Roms?. Anyway loving your app, no major issues on my Android Device so far, thank you for all the hard work and efforts you are giving in order to improve this emulator day by, thanks Flyinghead👏👍
