### ISSUE TITLE
Bleemcast! CDI images does not open on Android

### ISSUE THREAD

**Issue by joelos1111** [flyinghead/flycast#741]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 8.0

Github hash: 

Hardware: 

**_Description of the Issue_**

I tried Every single Combination of options within the Flycast Android Emulator but as of now i am not able to open any Bleemcast! CDI images, it only stay in the introduction screen but then it automatically crashes never goes beyond that, for example i have the CDI image of the Bleemcast for Tekken 3 and everytime i insert that game or any of the other 2 Retail CD's it always crashes and it doesn't matter whether i'm using the "dynarec" or the "interpreter" mode. Please Flyinghead try to add support for these type games on a further update. Thanks in advance
![Screenshot_2022-09-10-15-27-19](https://user-images.githubusercontent.com/113259459/189499239-084703b7-9f88-469e-9534-4805b9dfd8ce.png)
![Screenshot_2022-09-10-15-34-44](https://user-images.githubusercontent.com/113259459/189499252-38f5d5ad-fa32-405c-9014-fefb6c5492c4.png)

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Bleemcast games aren't supported and there's no plan to support them. Use a PS1 emulator instead.

**Comment by crashGG** [comment]
imbNES on bleemcast on flycast android on BlueStacks,,,like a matryoshka doll :)

**Comment by joelos1111** [comment]
I understand but why not support other consoles emulators inside flyinghead's dreamcast emulator?, it's the experience what matters in my opinion, is not like i'm trying to only play PS1 or SEGA Megadrive/Genesis SNES or NES games on my device, i of course know there is a bunch of these consoles emulators specifically dedicated to play on Android Devices but i just want to feel whether is on my phone or Tablet what it was to play these emulators that were made specially for The Sega Dreamcast when it used to be the best console on the Market, i know some of you guys won't share my point of view and laugh about it or some may actually agree with me and that's great, you are entitled to your opinion but i honestly don't see any damage in supporting for a future update of the Flycast app all of these emulators that were made to play on a Dreamcast console. Anyhow thank you Flyinghead for your attention on this subject, i still hope you can reconsider this issue. Have a nice day!

**Comment by vkedwardli** [comment]
It's not like he think the idea of emulating an emulator is dumb so he don't support it intentionally, it is just not worth the extra efforts when you can use other native emulator to play the games with better performance
