### ISSUE TITLE
Can't use per-pixel transparent sorting

### ISSUE THREAD

**Issue by leoxxx** [flyinghead/flycast#742]
OS:WIN7 X64
CPU:I5 3470
GPU:7850 1G

Popupu a diaglog, then close.

![2022-09-11_115639](https://user-images.githubusercontent.com/5364709/189511835-2b61cd1f-d9d0-48f5-b5c0-711db2440801.png)

The same error in dojo.
![2022-09-11_113648](https://user-images.githubusercontent.com/5364709/189511837-8484c2e1-984b-408b-81d9-2c9d1c67d148.png)

**Comment by flyinghead** [comment]
It's likely that your GPU doesn't support per-pixel or there's a problem with your driver.

Try enabling logs (Settings > Other > Log to File) and post the resulting flycast.log.

**Comment by leoxxx** [comment]
`00:00:000 rend/dx11/dx11context.cpp:38 N[RENDERER]: DX11 Context initializing
00:00:007 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1680 x 1050)
00:00:026 rend/gui.cpp:260 N[RENDERER]: Screen DPI is 96, size 640 x 480. Scaling by 1.00
00:00:026 rend/dx11/dx11context.cpp:286 N[RENDERER]: Swapchain resized: 640 x 480
00:00:026 rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 6 shaders from G:\flycast\data\dx11_shader_cache.bin
00:00:085 rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
00:00:086 rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 2 shaders from G:\flycast\data\dx11oit_shader_cache.bin
00:05:263 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:05:279 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 000007ffdf7a0000 RAM(16 MB) 000007ffeb7a0000 VRAM64(8 MB) 000007ffe37a0000 ARAM(2 MB) 000007ffff7a0000
00:05:289 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:05:299 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 000007ffdf7a0000 RAM(16 MB) 000007ffeb7a0000 VRAM64(8 MB) 000007ffe37a0000 ARAM(8 MB) 000007ffff7a0000
00:05:317 hw/naomi/naomi_cart.cpp:197 W[NAOMI]: Warning: Region 1 bios not found in awbios
00:06:192 hw/naomi/naomi_cart.cpp:579 N[NAOMI]: NAOMI GAME ID [NEOGEO_BATTLE_COLISEUM] region 0 players 0 vertical 0
00:06:192 emulator.cpp:223 N[BOOT]: Game ID is [NEOGEO_BATTLE_COLISEUM]
00:06:193 sdl/sdl_gamepad.h:354 N[INPUT]: Resetting SDL gamepad to default: 1 1
00:27:098 rend/dx11/oit/dx11_oitshaders.cpp:1102 E[RENDERER]: Shader compilation failed: error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: bufinfo requires resource declared as Buffer, Raw Buffer or Structured Buffer.  Opcode #126, operand #3 (counts are 1-based). 

00:27:098 rend/gui.cpp:2740 E[COMMON]: Verify Failed  : shader != nullptr
 in getShader -> D:/a/flycast/flycast/core/rend/dx11/oit/dx11_oitshaders.cpp : 958`
This error just happen with DX11, not happen with Opengl and Vulkan. But all transparent sorting options have map error when select character with Vulkan.

**Comment by leoxxx** [comment]
`00:00:000 rend/dx11/dx11context.cpp:38 N[RENDERER]: DX11 Context initializing
00:00:007 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1680 x 1050)
00:00:026 rend/gui.cpp:260 N[RENDERER]: Screen DPI is 96, size 640 x 480. Scaling by 1.00
00:00:026 rend/dx11/dx11context.cpp:286 N[RENDERER]: Swapchain resized: 640 x 480
00:00:026 rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 6 shaders from G:\flycast\data\dx11_shader_cache.bin
00:00:085 rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
00:00:086 rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 2 shaders from G:\flycast\data\dx11oit_shader_cache.bin
00:05:263 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:05:279 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 000007ffdf7a0000 RAM(16 MB) 000007ffeb7a0000 VRAM64(8 MB) 000007ffe37a0000 ARAM(2 MB) 000007ffff7a0000
00:05:289 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:05:299 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 000007ffdf7a0000 RAM(16 MB) 000007ffeb7a0000 VRAM64(8 MB) 000007ffe37a0000 ARAM(8 MB) 000007ffff7a0000
00:05:317 hw/naomi/naomi_cart.cpp:197 W[NAOMI]: Warning: Region 1 bios not found in awbios
00:06:192 hw/naomi/naomi_cart.cpp:579 N[NAOMI]: NAOMI GAME ID [NEOGEO_BATTLE_COLISEUM] region 0 players 0 vertical 0
00:06:192 emulator.cpp:223 N[BOOT]: Game ID is [NEOGEO_BATTLE_COLISEUM]
00:06:193 sdl/sdl_gamepad.h:354 N[INPUT]: Resetting SDL gamepad to default: 1 1
00:27:098 rend/dx11/oit/dx11_oitshaders.cpp:1102 E[RENDERER]: Shader compilation failed: error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: bufinfo requires resource declared as Buffer, Raw Buffer or Structured Buffer.  Opcode #126, operand #3 (counts are 1-based). 

00:27:098 rend/gui.cpp:2740 E[COMMON]: Verify Failed  : shader != nullptr
 in getShader -> D:/a/flycast/flycast/core/rend/dx11/oit/dx11_oitshaders.cpp : 958`
This error just happen with DX11, not happen with Opengl and Vulkan. But all transparent sorting options have map error when select character with Vulkan.

**Comment by flyinghead** [comment]
Make sure you have the latest DX11 install/patch for windows 7. The compilation of a shader is failing, which shouldn't happen.

Is it working in Open GL?

**Comment by leoxxx** [comment]
I closed update many years ago. How can I get the patch from other way?
OpenGL is O.K.

**Comment by flyinghead** [comment]
Check this link: https://support.microsoft.com/en-us/topic/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1-d97da9ca-c15c-b21f-ebb0-838f7be8d9f6

**Comment by leoxxx** [comment]
Windows6.1-KB2670838-x64.msu
I have installed it in 2019/1/21.

**Comment by flyinghead** [comment]
I don't know if there are other updates available.
Upgrading to Windows 10 may help too since windows 7 is no longer supported.

**Comment by psakhis** [comment]
Only say in my W7 fails as well, probably related to d3d11 support.

**Comment by flyinghead** [comment]
Try to upgrade to the lastest master build as I made some changes to avoid this issue

**Comment by flyinghead** [comment]
Great news! Thanks for your feedback
