### ISSUE TITLE
Vampire Chronicles For Match Service Dreamcast

### ISSUE THREAD

**Issue by VampireChronicles** [flyinghead/flycast#744]
Morrigan's stage drops the FPS to 1/2 of what it is supposed to be. No options alleviate the issue. It is the only stage that does this. Dark Forces that change the background bring the frames back up to 60. Once they run out, the FPS tanks again and the game stutters.

**Comment by flyinghead** [comment]
I haven't noticed any fps drop in training and vs modes in this stage (Deserted Chateau?). Perhaps it only happens in single player mode so please provide a savestate.

Also some information about your platform and settings would help.

**Comment by VampireChronicles** [comment]
![vampirescreenshot](https://user-images.githubusercontent.com/113554270/190827264-e26dee36-c0a4-49c6-9c9a-3165b2bf696a.jpg)

[save state.zip](https://github.com/flyinghead/flycast/files/9590410/save.state.zip)

![6324c48e](https://user-images.githubusercontent.com/113554270/190827456-10f65fbe-273a-4685-bf00-0fa2b2df6642.jpg)

Maybe, you are brute-forcing through it?

My computer is not the newest out there, but it's not a total potato:

Win 10 Pro x64
i5-4670K
1 TB SSD
16 GB Ram
Page file is on 
AMD RX 580 -- 8GB on Adrenalin 22.5.1

After fiddling further with the settings, it seems to happen with texture upscaling set at 2 or higher and only on this one stage.

**Comment by flyinghead** [comment]
Texture upscaling is done by the CPU and is quite intensive depending on the game. For some reason this stage is too much for your CPU to handle (and for my CPU too). It's updating many textures every frame, which requires a lot of processing power.

The only workaround is to disable texture upscaling for this game.

**Comment by VampireChronicles** [comment]
There is no way to offload some of that on to the GPU?

In addition, could an option be added to automatically drop out of texture upscaling if the target FPS is not net? Some modern games use adaptive V-sync, but I did not find any such option in Flycast. The frameskip set to max doesn't seem to work this out either.

**Comment by flyinghead** [comment]
Related enhancement request: #633
