### ISSUE TITLE
Bug: Mapping analog axes to DPad buttons functions incorrectly.

### ISSUE THREAD

**Issue by adamgp** [flyinghead/flycast#75]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:
Win 10 Pro (Current)
Intel i5
nVidia GT740 (Current)

Github hash:
N/A

Hardware:
Any JoyPad device with an analog axis which is actually a 4-way switch, where the only values per axis are -1, 0, 1

![image](https://user-images.githubusercontent.com/2965239/79542300-4da5bd00-8083-11ea-89b6-e0eb803166d4.png)

Examples:

![image](https://user-images.githubusercontent.com/2965239/79542717-053acf00-8084-11ea-9d2e-0040710496c7.png)
![image](https://user-images.githubusercontent.com/2965239/79542685-f6ecb300-8083-11ea-9582-112757beea2a.png)

**_Description of the Issue_**
**_Debugging Steps Tested_**

See sitenote below first, once the analog axis are set (also set device to Port A for further bug identification). Pressing Up or Down on the joypad results in the following behaviour.

1. Pressing Up, causing the up axis to trigger.
2. Releasing Up (axis returns to centre), does NOT cause the up action to reset (this has been observed in the test menu of a game where the JVS input test still shows the flag for this button as active.
3. Pressing Down (the reverse of the previous axis axis), caused the up action to be cancelled (this has been observed in the test menu of a game where the JVS input test now shows the flag for this button as inactive.
4. Further pressing Down. does not invoke the down action (again observed in the test menu of a game as having no action)
5. The same issue exhibits itself with Left and Right.

![image](https://user-images.githubusercontent.com/2965239/79542936-75e1eb80-8084-11ea-9281-cd186babbee9.png)

Furthermore, if the controller is set to Port A, the above mappings can also control the UI of Flycast, and this issue can be witnessed where the focused UI element constantly changes to the next in line until the reverse of the axis that trigger the issue is invoked.

I have not tested this with an analog device with full range (e.g 0.5 Up), and can only assume that perhaps a value of 0 is ignored for unsetting the actioning of the axis?

So to sumamrise, two bugs:

1. Which ever axis is set last in the control mappings, (Up or Down) is the only control that can be invoked.
2. That mapping is invoked even if the axis is at resting point 0, 0 until the reverse axis is invoked.

Please let me know if that doesnt make sense as its hard to explain, and a video might be in order.

Thanks

_**Sitenote**_
Only 2 of the 4 Dpad axis may be set, for example, setting Down will remove the setting for Up as the same mapping is reported. The same occurs for setting Left and Right.

**Comment by flyinghead** [comment]
I think the main issue here is that these gamepads don't have true analog axes. There might be some analog axis simulation somewhere (windows?, SDL?) but you'll probably have more success sticking with buttons only (left side of the mapping screen).

You can map buttons to analog axes using the following mappings (Left Stick U/D/L/R):
![image](https://user-images.githubusercontent.com/16261910/79564432-ea318480-80ae-11ea-876a-af8c55741742.png)
as well as (Left/Right trigger):
![image](https://user-images.githubusercontent.com/16261910/79564601-44324a00-80af-11ea-858c-78de978644d1.png)

One issue though is that you can't map a single button to multiple actions so you'll have to choose between DPad and Left stick.

**Comment by adamgp** [comment]
Unfortunately the UI is failing to recognise the axis input when pressed on the controllers on the "Buttons" (left) side of the control mappings, the only option is therefore to use the right hand "Analog" side?

**Comment by flyinghead** [comment]
Which controller(s) experience this issue?

**Comment by flyinghead** [comment]
As discussed on Discord, mapping DPad X and DPad Y is the way to go. The latest build hides the mapping of DPad[2] U/D/L/R from the analog axes to avoid confusion.
