### ISSUE TITLE
Commit da0d012 has introduced a background window in the Windows x64 build

### ISSUE THREAD

**Issue by dezraj** [flyinghead/flycast#750]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 64

Github hash: da0d0123

Hardware: i5 10400, 16gb RAM, GTX 1660 Ti

**_Description of the Issue_**

I don't think this is really an issue, but I'm opening an issue in case someone else comes here looking for an answer.

It seems that commit da0d012 has introduced a background window which do not show anything except the executable path in the window title, like this:

![image](https://user-images.githubusercontent.com/27839354/191684110-efd5ee1b-23a6-4f65-b102-4ab97b31a504.png)

I thought it would possibly start rendering the game in there or show some processing information, but it didn't. The game is still rendered in the main program window, which is what happens with the previous versions.

I was wondering why this window is now there and if it could be disabled to give the program a nicer aesthetic look and also to match what we generally have in most emulators.

Thank you so much in advance for your work.

**Comment by flyinghead** [comment]
Thanks for finding the starting commit. It's very likely due to a build environment change but it's good to know when it's started.

Anyway it should be fixed by 73adbc660b3394d3967d20b4c2b570ba978bf8af (dev branch). I'll fix it on master too.

**Comment by flyinghead** [comment]
This should be fixed on master too.
