### ISSUE TITLE
Build error? error: unable to open output file 

### ISSUE THREAD

**Issue by icemanyandy** [flyinghead/flycast#76]
/dreamcastDebug/obj NDK_LIBS_OUT=x\flycast\shell\android-studio\reicast\build\intermediates\ndkBuild\dreamcastDebug\lib -j6 dc}
$TARGET_ARCH_ABI is [armeabi-v7a]
[armeabi-v7a] Compile arm    : dc <= gl32funcs.c
[armeabi-v7a] Compile arm    : dc <= ngen_arm.S

error: unable to open output file 'xxxx/mame_game/flycast/shell/android-studio/reicast/build/intermediates/ndkBuild/dreamcastDebug/obj/local/armeabi-v7a/objs-debug/dc/x/mame_game/flycast/shell/android-studio/reicast/src/main/jni/__/__/__/__/__/__/core/wsi/gl32funcs.o': 'No such file or directory'
1 error generated.
make: *** [x/android-ndk-r21/build//../build/core/build-binary.mk:476: x/mame_game/flycast/shell/android-studio/reicast/build/intermediates/ndkBuild/dreamcastDebug/obj/local/armeabi-v7a/objs-debug/dc/x/mame_game/flycast/shell/android-studio/reicast/src/main/jni/__/__/__/__/__/__/core/wsi/gl32funcs.o] Error 1
make: *** Waiting for unfinished jobs....
error: error opening 'x/flycast/shell/android-studio/reicast/build/intermediates/ndkBuild/dreamcastDebug/obj/local/armeabi-v7a/objs-debug/dc/x/mame_game/flycast/shell/android-studio/reicast/src/main/jni/__/__/__/__/__/__/core/rec-ARM/ngen_arm.o.d': No such file or directory
1 error generated.
make: *** [x/build//../build/core/build-binary.mk:477: x/mame_game/flycast/shell/android-studio/reicast/build/intermediates/ndkBuild/dreamcastDebug/obj/local/armeabi-v7a/objs-debug/dc/x/mame_game/flycast/shell/android-studio/reicast/src/main/jni/__/__/__/__/__/__/core/rec-ARM/ngen_arm.o] Error 1

**Comment by flyinghead** [comment]
Some path issue I suppose. You can look at `/.travis.yml`to see how it's built for android

**Comment by icemanyandy** [comment]
> Some path issue I suppose. You can look at `/.travis.yml`to see how it's built for android

thanks,  fix with  

LOCAL_SHORT_COMMANDS := true
APP_SHORT_COMMANDS := true

**Comment by flyinghead** [comment]
Thanks for the information. Closing as resolved
