### ISSUE TITLE
Retroarch: Wild Riders on Naomi 2 is missing the service button

### ISSUE THREAD

**Issue by FuxorLuck** [flyinghead/flycast#764]
Platform / OS / Hardware: 

Retroarch

**_Description of the Issue_**

On Retroarch there is no Option to use the Service Button for Wild Riders.
This makes the game unplayable since you need the Service Button in order to reach "system assignments" and modify the controls otherwise the player won't be able to move when the game starts

**_Screenshots_**

![image](https://user-images.githubusercontent.com/55870574/193534876-3be560d8-a8ec-42fc-905a-0a70502f1961.png)

**Comment by flyinghead** [comment]
Enable `Quick Menu > Options > System > Allow NAOMI Service Buttons` and restart
