### ISSUE TITLE
NAOMI 2 support NSW / autostart feature

### ISSUE THREAD

**Issue by diekmanu** [flyinghead/flycast#767]
Is NAOMI 2 supported on the Nintendo Switch? 
Can we "autostart" games on startup of flycast? It would be cool to have custom title IDs and logos (custom forwarder channels are working) for every game.

**Comment by flyinghead** [comment]
Naomi 2 is supported on Switch but it's slow.

Passing a game content path as argument will start the game when flycast is executed. Not sure how/if that would work on switch.

**Comment by diekmanu** [comment]
Okay...so the correct BIOS path for the arcade machines (naomi.zip) is /flycast/data?
It's not working for me at the moment. Is flycast always depending on the latest available MAME romsets?

**Comment by cinnamonmatexfce** [comment]
Are all the needed correct files for *NAOMI BIOS* inside `naomi.zip`?

What game are you trying to start?

**Comment by diekmanu** [comment]
VF4cart. It's working now. Strange that 0.248 was failing for me.

**Comment by cinnamonmatexfce** [comment]
> VF4cart. It's working now. Strange that 0.248 was failing for me. 
> 
> 

Strange indeed. No changes from `0.246`.
![VF4CART.jpg](https://user-images.githubusercontent.com/65762930/193985742-263de988-126a-48a5-9ff5-02b3b0ebe5be.jpg)

**Comment by zerofalcon** [comment]
> Can we "autostart" games on startup of flycast? It would be cool to have custom title IDs and logos (custom forwarder channels are working) for every game.

Can confirm games on startup works on Nintendo Switch. I made an nro forwarder for RE2 and launches correctly just showing the loading prompt before the BIOS loads.

**Comment by diekmanu** [comment]
Nice. So much better to have the right game covers. This could also help with different sys-clk settings per game. And no Retroarch overhead that kills your sd card in months. Thanks again @zerofalcon.
