### ISSUE TITLE
vf4evo vulkan issue

### ISSUE THREAD

**Issue by LodanZark** [flyinghead/flycast#778]
Virtua Fighter 4 Evolution (Japan Rev. B) has slowdowns in the Aoi Umenokoji stage while using Vulkan, I assume it's due to the water effect surrounding the stage, this issue it's very noticeable in the Attract Mode scenes.

**Comment by flyinghead** [comment]
What's your hardware platform?
What settings are you using?
...

**Comment by LodanZark** [comment]
@flyinghead 
Maybe this will help:

DxDiag:
[DxDiag.txt](https://github.com/flyinghead/flycast/files/9779500/DxDiag.txt)

Emu Settings:
[emu.zip](https://github.com/flyinghead/flycast/files/9779514/emu.zip)

Attract Mode Video ( always get slowdowns in the same stage):
https://www.youtube.com/watch?v=RmuYjqxmvOQ

**Comment by flyinghead** [comment]
Disable `Settings > Video > Render to Texture > Copy to VRAM` and this should greatly help performance, and improve the quality of water reflections.

This setting is normally enabled automatically for games that need it, so it's best not to touch it.

**Comment by LodanZark** [comment]
@flyinghead thank you! that solved my problem, will close the ticket now.
