### ISSUE TITLE
Gun Survivor 2 Naomi mouse/lightgun buttons wrong and other issues

### ISSUE THREAD

**Issue by Jayinem** [flyinghead/flycast#78]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: flycast-win_x64-fast-17c7e0b3ed531617ea0fe5d3357caec86f8b8bb6

Hardware: PC Windows 10

**_Description of the Issue_**

I've been able to get all Naomi Lightgun games to work normally with my Lightgun by selecting Lightgun for P1 in controls. But when I play RE Gun Survivor 2 if I choose Lightgun for player 1 there's some sort of camera issue where when you move the gun and the controller around (I have controller in P2) the player goes crazy and moves around and you don't have full control of the direction you are moving. So I changed Lightgun to mouse and I'm able to control the characters normally. But there's a small issue with that the buttons are reversed when I pull my trigger on my Lightgun it doesn't fire but button 2 fires. The same action takes place on a mouse you shoot by right clicking. I tried changing the settings by going to mouse and I was unable to change the buttons. I believe A needs to be 3 and B needs to be 1 which is reverse what is in right now. But that is only my best guess when I try to input using either a mouse or the Lightgun it doesn't accept it.  I also did not find where you can change this in the cfg file so I made this an issue because I've posted on forums and gotten no response.

**Comment by flyinghead** [comment]
Gun survivor 2 isn't a lightgun game. It uses three analog axes (aim l/r, forward/backward and strafe l/r). You'll have better success with a regular gamepad with 2 analog sticks.

Also, Naomi/Atomiswave games ignore the type of Dreamcast device selected (controller, lightgun, mouse...) This is only relevant for Dreamcast games.

**Comment by Jayinem** [comment]
Resident Evil Survivor 2 – Code: Veronica is a light gun shooter video game developed and published by Capcom as part of the Resident Evil series. ... The game is the second installment in the Gun Survivor series and sequel to Resident Evil Survivor.

**Comment by flyinghead** [comment]
This is from the arcade user manual:

> **2. HOW TO PLAY**
> This is a shooting game for one or two players. Players explore an island, fighting
against enemies in order to escape from the island.
> *HOW TO CONTROL*
> Sliding the gun backwards/forwards or left/right moves the character on the screen in
a corresponding direction.
> Turning the gun left/right changes the characters field of vision accordingly.

You can go to the game test menu and check the inputs.
