### ISSUE TITLE
Mac Launchpad Game Category

### ISSUE THREAD

**Issue by darkuser89** [flyinghead/flycast#780]
can you add this to the info.plist so that Flycast is recognized as a game in the launchpad?   `<key>LSApplicationCategoryType</key>   <string>public.app-category.games</string>`

**Comment by vkedwardli** [comment]
Just curious, how does the Launchpad category work? Can share a screenshot?

**Comment by darkuser89** [comment]
Games with this will die apps are marked as automatically in the category
<img width="431" alt="Bildschirmfoto 2022-10-15 um 19 15 06" src="https://user-images.githubusercontent.com/29849893/195999482-297b20b1-1345-4047-8c1f-15bc2e49ad4d.png">
