### ISSUE TITLE
Legacy of Kain Soul Reaver: camera rotation and Raziels body twitch with RGB and Composite cable mode but not VGA

### ISSUE THREAD

**Issue by BParks21** [flyinghead/flycast#784]
Platform / OS / Hardware: 
Windows 11
i7 8086K, GTX 1080 ti, 32gb DDR4

Description of the Issue:
Camera rotation is not smooth and Raziel jitters when moving when cable type is set to RGB or Composite. Is smooth when set to VGA. 

More info here:
https://github.com/libretro/flycast/issues/1167

**Comment by flyinghead** [comment]
I don't notice any difference between TV Composite vs. VGA with this game.
Can you post your emu.cfg?

**Comment by BParks21** [comment]
Yeah it's pretty obvious though. Like instantly noticeable. It has to be set to VGA to get smooth camera rotation otherwise it simply isn't when rotating the camera. This is a fresh install of flycast. It does it even at default settings. Are you running on a windows 10 or 11 system? All you have to do is stand in a wide open area and use the dpad (left or right) and rotate the camera. It's there tested on two different rigs. Yes here is my config
[emu.zip](https://github.com/flyinghead/flycast/files/9818987/emu.zip)

**Comment by RainaAudron** [comment]
I have also tested this and I see no difference. Can you upload a video comparison?

**Comment by flyinghead** [comment]
Tested again with your settings on linux (ubuntu 20) and NVidia GTX 1080 and I cannot spot any difference between VGA and TV composite.

**Comment by BParks21** [comment]
Well I've also tested this on another Windows system with a 12700k and an RTX 3080. I will post a video later today. I don't think it is a frame delivery issue more than some kind of physics issue since Raziel also jitters whil traversing but only with RGB or Composite. Which doesn't make sense but yeah his entire body will jitter slightly when being mover around just like when the camera is being rotated with the dpad. @flyinghead Test Windows. I haven't tested this on linux so I can't say if it also occurs with that OS.

**Comment by BParks21** [comment]
> I have also tested this on Windows10 and I see no difference. Can you upload a video comparison?

The main problem with capturing this jitter with say OBS, is the recording will introduce it's own frame stutter which isn't what's happening here, somehow the timings/physics are being affected by the cable mode hence why Raziels body is twitching. I recorded the video and as expected there is new (frame pacing stutter) introduced by the recording software. So I only want you to pay attention to Raziels twitching body while he is running around, particularly his head when running. With the recording you cannot distinguish between the camer jitter generated from the cable setting vs the jitter generated from the recording software but you can distinguish his body twitching/jitter. So pay attention to his head not the camera jitter because one does not occur without the other so if you can see his body twitching then the issue is observable to you. Now if you can't see the difference between his head jittering/twitching you are simply not paying close enough attention. Either that or you should get your eyes checked because his jittering body vs his non jittering body is clearly visible in this comparison. Difference is night and day. 

https://drive.google.com/file/d/1AmhN9eCoD68ZHUpx9QrMDI3hpEnHgFz0/view?usp=sharing

**Comment by BParks21** [comment]
Would also like to mention that I tested this with both the NTSC version and the PAL version. Confirmed clean dumps from redump dat.

**Comment by RainaAudron** [comment]
Ok, the video helped a lot! You originally said you had stand in an area and rotate the camera, but I could only see this when Raziel ran around in circles. Maybe Flying Head can find out why this is happening, but why not just stick to VGA then? It is the default, after all.

**Comment by BParks21** [comment]
@RainaAudron Composite is default on the standalone and libretro core. But I plan to stick to VGA now. I said you had to stand still and rotate the camera to see the camera jitter only. To see Raziel jitter/twitch he needs to be running. Both these issues are related and are only producible with composite and rgb cable mode. They are connected.

**Comment by BParks21** [comment]
> Ah, weird. I couldn´t tell the difference by rotating camera around Raziel, only when he was running. Hopefully, Flying Head can look into it, until then, VGA it is!

Indeed, yes hopefully.

**Comment by BParks21** [comment]
Seems to be fixed now.
