### ISSUE TITLE
Jet Grind Radio per pixel alpha sorting causing lighting bugs 

### ISSUE THREAD

**Issue by BParks21** [flyinghead/flycast#787]
Windows 11, 8086K, GTX 1080ti

When Per Pixel Alpha Sorting is enabled you can see some strange shadow flickering in areas of the game. Tested with the NTSC version of the game. Easiest way to see it is boot the game watch the skater skate passed the bike rack during the initial tutorial. You will see a shadow flicker over the bikes. Does not occur with per triangle. I also tested redream with it's per pixel setting and it looks correct. It looks just like how flycast does with it set to per triangle. Shouldn't a more accurate option typically yield better results? Regression maybe? Not sure? Confirmed clean dump with redump dat.

**Comment by flyinghead** [comment]
Please post a screenshot

**Comment by BParks21** [comment]
![Per Pixel](https://user-images.githubusercontent.com/12180630/196764387-8115d94a-5810-4608-a60c-7d1758ecde85.png)
![Per Triangle](https://user-images.githubusercontent.com/12180630/196764389-37190bcf-1b3b-4bfa-b20c-2af52f86a0a6.png)

Here are the screenshots. They are labeled according to the alpha sorting setting being used.

**Comment by flyinghead** [comment]
There are no labels on these screenshots but I guess the first one is per-pixel.

This game makes heavy use of shadows on transparent surfaces (character model in particular, possibly the bikes as well), which aren't supported by redream as far as I know.

**Comment by BParks21** [comment]
> There are no labels on these screenshots but I guess the first one is per-pixel.
> 
> This game makes heavy use of shadows on transparent surfaces (character model in particular, possibly the bikes as well), which aren't supported by redream as far as I know.

Ahhh sorry I should have uploaded them in zip format. Github upload renamed the raw file name.

**Comment by flyinghead** [comment]
working as designed

**Comment by BParks21** [comment]
> working as designed

So it should be disabled when running this game? I'm confused as designed but looks broken?

**Comment by flyinghead** [comment]
What looks broken?
Here is how it currently looks on the dev branch in per-pixel:
![image](https://user-images.githubusercontent.com/16261910/209410125-7c958223-5cbe-4aa0-a6b7-facfd119bb9e.png)
The character is shadowed as it should be. The bikes aren't.
Please try the latest dev build and post a screenshot if things doesn't look right.

**Comment by BParks21** [comment]
Yeah I'll try the dev build.

**Comment by BParks21** [comment]
Yeah tested the latest dev build and as soon as per pixel alpha is enabled passing the bikes in that scene the shadows with flicker on and off over the bikes. It is still broken, real hardware and Redream do not look like that. As soon as I set it to per triangle it looks correct.
