### ISSUE TITLE
Roadsters racing game doesn't start

### ISSUE THREAD

**Issue by NightWolf2014** [flyinghead/flycast#791]
Roadsters 1999 racing game from Titus doesn't start, the game gets stuck on the Dreamcast intro screen, after the Sega screen appears, the game restarts on the Dreamcast screen again and gets stuck in this infinite looping all the time. Please fix this problem.

**Comment by flyinghead** [comment]
![image](https://user-images.githubusercontent.com/16261910/196961382-f4b8c1be-33de-47bc-8a8e-0b680e828dee.png)
This game works fine for me. Check that your rom is valid. Avoid CDI format.

**Comment by NightWolf2014** [comment]
The problem only happened when i used the USA rom, i opened the PAL rom
after and the game worked.

Em Qui, 20 de out de 2022 11:29, flyinghead ***@***.***>
escreveu:

**Comment by flyinghead** [comment]
I get a reboot loop when selecting `RGB Component` as cable. Some games don't support it so I recommend to use TV Composite instead, which is the default.

**Comment by NightWolf2014** [comment]
Thanks, i do that with PAL version.

Em Qui, 20 de out de 2022 12:30, flyinghead ***@***.***>
escreveu:
