### ISSUE TITLE
Rayman 2.

### ISSUE THREAD

**Issue by Gamergoddess83** [flyinghead/flycast#794]
So on Rayman 2 great escape the are black boxes on the bottom of the screen? Can someone please look into it?.

**Comment by flyinghead** [comment]
screenshot, platform, flycast version, etc...

**Comment by Gamergoddess83** [comment]
Steam Deck can't take a screen shot as for some reason when I uninstalled it and reinstalled flycast it's like very zoomed in.

**Comment by flyinghead** [comment]
See issue #769

**Comment by flyinghead** [comment]
no answer
