### ISSUE TITLE
Sturmwind - Crash at launch

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#799]
Hi,

The game crash after the memory card check:
```
00:00:000 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:110 rend/gui.cpp:262 N[RENDERER]: Screen DPI is 96, size 640 x 486. Scaling by 1.00
00:06:011 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:06:022 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff402060000 RAM(16 MB) 00007ff40e060000 VRAM64(8 MB) 00007ff406060000 ARAM(2 MB) 00007ff422060000
00:06:031 hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
00:06:043 hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff402060000 RAM(16 MB) 00007ff40e060000 VRAM64(8 MB) 00007ff406060000 ARAM(2 MB) 00007ff422060000
00:06:069 emulator.cpp:55 N[BOOT]: Game ID is [DR001]
00:39:572 rec-x64/rec_x64.cpp:80 E[DYNAREC]: SH4ThrownException in mainloop
```

I'm using this version (I checked the md5 of all files):
http://redump.org/disc/70113/

I tried the latest nightly (Win10) with the default config.

**Comment by flyinghead** [comment]
I get the same result with this dump. I read that this game has a copy-protection feature so it might the cause of the crash.

The CDI version works fine though.

**Comment by dukeblooders** [comment]
Thanks for your answer.

I noticed the cue file was different from the other cues.
There is no single/high density areas, but sessions. Could it be the reason ?

Otherwise, I'll keep the .cdi version...

**Comment by flyinghead** [comment]
You're right and that's because the original isn't a GD-ROM but a MIL-CD.

I believe MIL-CDs in .cue format are supported but this support might be incomplete or buggy. I'll have a look.

**Comment by flyinghead** [comment]
I did check and support for MIL-CD seems to work fine. So I assume this crash is due to a copy-protection feature of the .CUE version.

**Comment by dukeblooders** [comment]
OK, thanks for your feedback. I'll keep the CDI version then.
