### ISSUE TITLE
Graphical glitches in kof 99 evolution scenarios

### ISSUE THREAD

**Issue by Tiger3784** [flyinghead/flycast#801]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Pc Windows 11
Github hash: 

Hardware: 
 I5 9400f 16gb ram nvidia 3050
**_Description of the Issue_**

Add a short, concise description of the issue here
Graphical glitches in kof 99 evolution scenarios
**_Debugging Steps Tested_**
tested on all APIs the same problem happens
  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Screenshot?
Flycast version and settings?

**Comment by flyinghead** [comment]
no answer
