### ISSUE TITLE
Request Custom Internal Resolution 

### ISSUE THREAD

**Issue by yudhiyou** [flyinghead/flycast#803]
There have been internal resolution selection on flycast but for 2D fighting games like Street Fighter, Garou, etc. is looked like we need custom resolution because current internal resolution selection can't accommodate the need of original resolution of those games.
Resolution 320x240 is too low for cps arcade games. Resolution 640x480 is too high.
So I think it's better if we can input custom internal resolution manually on flycast.

Thank you...

**Comment by flyinghead** [comment]
When `640x480 (Native)` resolution is selected, it means that the render resolution of the game is respected. For most games it will be 640x480 but some games will use 640x240 or 320x240. In these cases Flycast will render at 640x240 or 320x240.

PS: many Street Fighter releases use 240p but Garou renders at 640x480

**Comment by vkedwardli** [comment]
If you really want a resolution which is not the multiple of 480, may be you can try setting it in `emu.cfg`
e.g. `rend.Resolution = 448` ?

**Comment by flyinghead** [comment]
Working as designed
