### ISSUE TITLE
Support for content reading from external SSD / USB drive.

### ISSUE THREAD

**Issue by DavidAriyan** [flyinghead/flycast#813]
With the new implemented SAF system, the emu could easily read & write to external ssd/ or any USB drive connected via the USB c port.
The device name clearly showed there in the menu. But when I tried to select the directory in it, Flycast unfortunately can't access it.
But the weird is, SD card loading is supported but not external USB.
I'm using android.
Please take a look at this "bug".
We really need this kind of feature. Because having to save everything in the internal SD woulf be messed up.

**Comment by flyinghead** [comment]
What is your android version and device type?

**Comment by DavidAriyan** [comment]
> What is your android version and device type?

Android 12. I'm using Samsung Galaxy S20 FE.

**Comment by DavidAriyan** [comment]
As a proof I'll include the screenshots. As we can see here, the SSD drive is detected, but strangely Flycast can't access it. There's nothing wrong with my portable SSD because it's loaded just fine in File browser like Zarchiver and native file browser and off course in other emulators.
![Screenshot_20221205-085957_Flycast](https://user-images.githubusercontent.com/78215839/205537783-5c9655ed-3a20-4ed0-a543-8a8bb21a12ef.png)
![Screenshot_20221205-090003_Flycast](https://user-images.githubusercontent.com/78215839/205537792-db13bdcf-1147-488d-836f-6cf5f5a66024.png)
![Screenshot_20221205-090048_ZArchiver Pro](https://user-images.githubusercontent.com/78215839/205537796-22db2e9a-c54b-4bb7-9067-37496a043c27.png)

**Comment by flyinghead** [comment]
The latest build on the `dev` branch supports external USB storage devices. Tested on Android 9 and 11.
For now only games (and cheat files) can be loaded from USB devices. Flycast home directory must be on internal or SD card storage.

**Comment by DavidAriyan** [comment]
I'm glad to hear that. Thank you so much for your efforts.

**Comment by flyinghead** [comment]
This required very substantial changes and thus a high probability of bugs, so please test and report. Thanks

**Comment by DavidAriyan** [comment]
I had tested it on my samsung note 10 plus, with portable ssd (brand is
orico) attached to it's usb c port. At first it recognize the folders in
the ssd, but after I selected it, the app crashed and won't recognize the
folder after. Need me to reinstall the app to try again point that ssd
path.
Well my ssd is not really portable it needs a usb power hub and a power
bank in able to connect correctly to the phone. Maybe it's not compatible.
But i tried on other emulators like dolphin & Aethersx2 is just works fine.
I think I'll probably get my self a real ssd portable with usb c male port.
Orico have that product. I just need more money to buy it later. I will
test if it's gonna work.
Probably this is still bug though, like you mentioned.
Because I also tried sd card adapter with usb c port and sd card attached
to it. The app won't recognize it too.

Pada tanggal Kam, 13 Apr 2023 19.04, flyinghead ***@***.***>
menulis:

**Comment by flyinghead** [comment]
Thanks for the feedback. Flycast shouldn't crash like that so that's probably a bug.

Make sure to enable `Automatically Report Crashes` so that crash reports are automatically sent to me. So far I haven't seen any crash related to your issue. Also restart the app after a crash so it gets uploaded.

**Comment by DavidAriyan** [comment]
It's finally works. Great! Thank you so much. Thank you.
