### ISSUE TITLE
Rayman 2: The Great Escape randomly freezes

### ISSUE THREAD

**Issue by SuperSamus** [flyinghead/flycast#815]
Platform / OS / Hardware: Linux (NixOS unstable)
Using Flycast packaged from nixpkgs (to get debug info, I compiled it with `CMAKE_BUILD_TYPE=RelWithDebInfo`).

GitHub hash: 88466ec3523d2c1f4893153a5c6a86d854171ce2

Hardware: Lenovo IdeaPad 5 14ARE05
(AMD Ryzen 5 4500U with iGPU AMD RX Vega 6, 8 GB RAM)

**_Description of the Issue_**

While playing Rayman 2: The Great Escape NTSC 1.003 (I didn't test any other game), the emulator freezes for no apparent reason. When that happens, the window shows the last frame of the game and Flycast becomes completely uninteractable: it needs to be force killed. Interestingly, though, it still logs controller inputs while in this state.

**_Debugging Steps Tested_**

As I said, it seems to happen completely randomly. It may happen after playing for 5 minutes, just like it may happen after playing for 60 minutes.

**_Logs Gathered_**

In these logs, I show a small sample of what the dynarec logs after freezing (notice how the controller inputs are still logged). Then I CTRL+C the program and get backtraces from gdb. If you need any more info, tell me, I still have gdb running.
Ignore the fact that paths are long and weird.

[gdb.log](https://github.com/flyinghead/flycast/files/10103195/gdb.log)

**Comment by flyinghead** [comment]
The stack traces indicate that the UI thread is still active but the emulator thread is blocked or somewhat stuck.
It could be an audio issue so I suggest to try a different audio driver (like SDL2) and check if the problem persists.

Also test other games to make sure it's not due to a corrupted gdrom. Avoid CDI media.

**Comment by SuperSamus** [comment]
I started finishing the game recently with a more recent version of Flycast (I had more than 50% of the game left), and the game never crashed once. I guess I can close this.
