### ISSUE TITLE
Performance regressions comparing v1.2 and v2.0

### ISSUE THREAD

**Issue by Hew-ux** [flyinghead/flycast#818]
Platform / OS / Hardware: 
OS: Batocera
Tested across a Raspberry Pi 3, Raspberry Pi 4 and standard PCs with the following specs:
PC A. Intel i3 4th gen, Nvidia GTX 750Ti
PC B. Intel i5 4th gen, AMD Radeon RX 6500 XT

Github hash: 
4e21391f8cfd481ac1e0ac6b2bf54e0d81f59a1f through to 02d4b821d755087d2db0fcb3bc002e198ac0fa22 , but I am certain the difference is pragmatically between v1.2 **(Edit: actually v1.0)** and v2.0 releases as will be explained later.

Hardware: 
As above.

**_Description of the Issue_**

Performance in Flycast has dramatically dropped across the board. On these weaker devices, the drop is most apparent, with games that previously ran at a constant 60 FPS going down to 30-50 FPS sporadically. For a very obvious example, the game Bangai-O seems to run fine for a minute or so but part way through the first level there is a long stall, and whenever a bomb is used (many particle effects) there is an additional stall.

The go-to testing games for these performance regressions I've been using are Bangai-O, Crazy Taxi and Sega Rally 2.

**_Debugging Steps Tested_**

  * Start up the game Bangai-O (or any game, really) on weak hardware (as above) using Flycast v1.2 **(Edit: v1.0)**.
  * Observe the game running at (nearly) full speed.
  * Start up the same game using Flycast v2.0.
  * Observe the game running at a lower performance, varying based on game (for something like Crazy Taxi it can go down as far as half the original speed, most games aren't as drastically affected though).

**_Logs Gathered_**

Logs are not relevant to this issue. Everything is reported as functioning fine.

**_Additional informaton_**

I've brought this up as an issue to be investigated within Batocera, however I've been advised to bring the issue report directly to this repository.

The reason I'm certain it's to do with the change from Flycast v1.2 and Flycast v2.0 is because the "version bump" in Batocera is when the issue started surfacing. Specifically, in this commit here: https://github.com/batocera-linux/batocera.linux/commit/82e8d45cbf4bec0f3f1493f91c917037aa12d266

I tested taking the compiled Flycast v1.2 **(Edit: v1.0)** binary from Batocera v32 (a version well before this bump) and putting it into Batocera v35 (the current stable version of Batocera as of writing) and comparing it with the built-in Flycast v2.0, the performance differences are immediately apparent. This does not seem to be related to anything that's changed in Batocera at least, otherwise both versions of Flycast would have suffered from the same issues.

This issue affects both Flycast and its libretro port. I've also been benchmarking the performance of Dreamcast emulation using the libretro port of Flycast of various Batocera stable releases in its documentation: https://wiki.batocera.org/choose_a_desktop_computer#benchmarks

**Comment by flyinghead** [comment]
Do you have a way to test v1.3? That would reduce the scope of changes to look at.

It might be difficult on RPi since there are no binary available but there are for windows.

**Comment by Hew-ux** [comment]
I was thinking that, but unfortunately there was no release of Batocera which had Flycast v1.3 available and attempting to compile it myself results in getting stuck on the "save data cannot be found" screen on all games.

I'll try seeing if I can manually patch v1.3 to work around this, just to get in game and test its performance.

**Comment by flyinghead** [comment]
I found and fixed a performance regression that was introduced in February (v2.0). It's very noticeable with Bangai-O since it uses transparent sprites exclusively. So a typical scene would contain 2800 sprites (5600 triangles) leading to 16000 triangles after merging that need to be sorted.

I also added polygon merging when using per-strip but this is done after sorting, which should help reducing the number of draw calls. Without merging Bangai-O needs 2800 draw calls per frame. With merging this is down less than 100.

**Comment by direngrey31** [comment]
Hi, I took core libretro flycast (flycast_libretro.so) from batocera v33 and integrated it into batocera v35 and v36!  the tests are conclusive.  backups are working fine

**Comment by Hew-ux** [comment]
I've got some unfortunate news.

I compiled Flycast from the version https://github.com/flyinghead/flycast/commit/3d5fd61285a2b57ed4ac7b2b25bc2b830cf43d57 (which appears as 1.13.0 Flycast according to RetroArch) and it seems that it also has the slowdown issue, so this means one of the following:

A. The regression was introduced sometime between v1.2 and v1.3 of Flycast
B. My weaker PC hardware has never been able to run the game at full speed and it was only pure luck that I didn't encounter a slowdown during testing specifically v1.2 (unlikely considering the sheer volume of tests I performed)
C. I accidentally just compiled v2.0 again (I have double checked the version in the build folder matches up with the git commit specified above)
![image](https://user-images.githubusercontent.com/67527064/206159706-0e53c6ac-c506-4ef1-bf46-2ad15100301c.png)

I will now try compiling the newest version of Flycast, with your fix employed, to see the results. It could be that that's all which may be needed to mitigate the regression; I'd be okay with closing the issue there (as overall performance is always an ongoing goal and doesn't need a specific issue report for it, as long as there's no regression in performance that is).

**Comment by flyinghead** [comment]
I fixed an issue but there might be more than one.

If you can compile any commit then it would help if you could give me a time period, or commit range, as small as possible. Then I can take it from there to figure out which one is the culprit.

**Comment by Hew-ux** [comment]
I've actually found a mistake I made when recording the information. This clears up something I found really confusing about it. So here are the facts as I see them.

To keep the information in one place here are my findings in bullet list format.

- Batocera v32, the included Flycast v1.0: fast
- Batocera v35, the included Flycast v2.0: slow
- Batocera v35, the Flycast v1.0 binary copied over from Batocera v32: fast
- Batocera v35, Flycast v1.3 compiled from scratch: slow
- Batocera v35, Flycast v1.2 compiled from scratch: slow
- Batocera v35, Flycast v2.0 compiled with latest commit: slow

Where Flycast versions match the following commits:
**Flycast v1.0** included with Batocera v32, as compiled by [this makefile](https://github.com/batocera-linux/batocera.linux/blob/04997549d87eb30ae0195690b018dea48c8b2133/package/batocera/emulators/flycast/flycast.mk):
Contains the following pertinent versioning information;
```
# Version.: Release on May 29, 2021
FLYCAST_VERSION = v1.0
```
**Flycast v1.0** most likely used: https://github.com/flyinghead/flycast/commit/d6e15544bcdb99112f72f0a08acf38268c21a5ae
**Flycast v1.2**: https://github.com/flyinghead/flycast/commit/7555263e38722ea0e3f2b736b92ad0a91389f4b4
**Flycast v1.3**: https://github.com/flyinghead/flycast/commit/3d5fd61285a2b57ed4ac7b2b25bc2b830cf43d57
**Flycast v2.0** original Batocera v35: https://github.com/flyinghead/flycast/commit/71ba0187820da4f89c490bdfa78b006504e57adf
**Flycast v2.0** newest commit: https://github.com/flyinghead/flycast/commit/71ba0187820da4f89c490bdfa78b006504e57adf

In summary: regression most likely happened between https://github.com/flyinghead/flycast/commit/d6e15544bcdb99112f72f0a08acf38268c21a5ae and https://github.com/flyinghead/flycast/commit/7555263e38722ea0e3f2b736b92ad0a91389f4b4

I'll be testing closer commits in the future, but due to changes made in Batocera it will be more and more difficult to retroactively patch older versions of Flycast to be built with it (dependencies now missing in the build change, older dependencies being bumped to new ones, etc.) and it may just not be feasible to continue. This is one of the reasons why I brought it up with Batocera first; it may just be Batocera's compilation method which is causing interference. Looking at [Batocera's current makefile folder for Flycast](https://github.com/batocera-linux/batocera.linux/tree/56fc47b111389ee120bf6d801cf5c697484ff6c8/package/batocera/emulators/flycast), do you notice anything strange that could be causing obvious lost performance?

**Comment by Hew-ux** [comment]
I have now tested **Flycast v1.1** binary from Batocera v33 and it is fast. That was likely built from https://github.com/flyinghead/flycast/commit/a51f310e96a0605b25e8fb59fd0007245335d46b according to https://github.com/batocera-linux/batocera.linux/commit/b1f5ada1b1de12773c57c6dea380cf15a2f32b98

So in summary, the regression likely occurred between https://github.com/flyinghead/flycast/commit/a51f310e96a0605b25e8fb59fd0007245335d46b and https://github.com/flyinghead/flycast/commit/7555263e38722ea0e3f2b736b92ad0a91389f4b4

**Comment by blisstik** [comment]
Does the latest commits fix the issue?

https://github.com/flyinghead/flycast/commit/98123b921582f13f73da36bab88381b4571758bb

**Comment by flyinghead** [comment]
@Hew-ux what game(s) are you testing with at this point?
I'm comparing v1.1 and 98123b921582f13f73da36bab88381b4571758bb and the latter has better performance with Bangai-O.
v1.1: 35 FPS
latest master: 41 FPS

**Comment by Hew-ux** [comment]
I've been testing both Bangai-O and Crazy Taxi. Yes, the latest commit helps a bit, but the performance is still worse than it was compared to Flycast v1.1. I'm doing these latest tests on my "low-end"  PC B, mentioned in the original report. All the tests are being done within Batocera.

I should test this on another OS altogether as I have a suspicion that it might be an issue specific to Batocera, but that involves having to install another OS to a new drive, which may take some time to do.

@blisstik The commit I tested is after the commit you mentioned, so it should be there (unless there was a newer commit which undid the changes of your mentioned commit and that's why you're bringing it up?)

**Comment by blisstik** [comment]
The newest commit was just today, that's why I was asking.

**Comment by flyinghead** [comment]
I have compared the performance of v1.1 vs v1.2 and I find no performance difference between the two on my test system. I have tested Bangai-O and Crazy Taxi.

Flycast settings: per-triangle, no fog, no shadows, autoskip frame max, no vsync, no delay frame swapping, no DSP.

Both binaries are installed on a gameforce CHI (RK3326) running batocera V35.

**Comment by Hew-ux** [comment]
I was just using whatever the default settings were. Checking now, these are the settings that I have been testing with:
Transparent Sorting/Alpha sorting: Per-triangle
Fog Effects: On
Shadows/Volume Modifier: On
Multi-threaded emulation/Threaded Rendering: On
Auto Skip Frame: Off
Frame Skipping: Off
V-sync: On
Delay Frame Swapping: On in standalone, off in libretro (doesn't seem to make a difference switching this anyway)
DSP: On
Graphics API: OpenGL

The settings have been consistent with both libretro and standalone versions of Flycast, and between the versions as well.

**Comment by PIC16f841** [comment]
@flyinghead any possibility you can test this on a raspberry Pi 4 which is the system affected? It may be some poor performance/bottleneck affecting only rpi4 drivers

**Comment by vkedwardli** [comment]
@PIC16f841  would be easier if you can pinpoint which commit causing problem on Pi4, since you already have the hardware

**Comment by flyinghead** [comment]
Unfortunately I don't own a RPi4 but all performance regressions I could find have been fixed, and more.

To make further progress I need to know which commit range to look at.

**Comment by anigwei** [comment]
Hi, 
I'm a "sufferer" from this bug on Batocera 35 in a RPi4. Crazy Taxi is the target :)
Very interesting thread. I have a RPi4 and can check whatever you need.

**Comment by anigwei** [comment]
> I've actually found a mistake I made when recording the information. This clears up something I found really confusing about it. So here are the facts as I see them.
> 
> To keep the information in one place here are my findings in bullet list format.
> 
>     * Batocera v32, the included Flycast v1.0: fast
> 
>     * Batocera v35, the Flycast v1.0 binary copied over from Batocera v32: fast
> 
>     * Batocera v35, Flycast v1.2 compiled from scratch: slow
> 
>     * Batocera v35, Flycast v1.3 compiled from scratch: slow
> 
>     * Batocera v35, the included Flycast v2.0: slow
> 
>     * Batocera v35, Flycast v2.0 compiled with latest commit: slow
> 
> 

So the workaround (By now) for Batocera 35, is simply copying the Flycast binary from v32?

**Comment by flyinghead** [comment]
There are 255 commits from v1.0 to v1.2. I already bisected to find performance regressions and fixed the ones I could find.

Unless someone can point to a specific commit, or reasonably small commit range, I can't spend more time on this.

**Comment by Hew-ux** [comment]
I agree, there doesn't seem to be much evidence that this issue is even with Flycast and not Batocera. Thank you for investigating into this (and for the fixes that came from it, even if they weren't the ultimate solution!) but unless some more concrete evidence appears, I'll leave this issue on closed.
