### ISSUE TITLE
Flycast crash when i open them

### ISSUE THREAD

**Issue by Samueltgg12** [flyinghead/flycast#819]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 

Github hash: Android 

Hardware: Android 

**_Description of the Issue_**

Add a short, concise description of the issue here
Im Sad beacuse i download a flycast commit right but when  i open is crashed why it came out of nowhere for no reason 
**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
I'm sad too
