### ISSUE TITLE
Compile fails when target aarch64 and ogles v2

### ISSUE THREAD

**Issue by Ntemis** [flyinghead/flycast#820]
Platform / OS / Hardware: 
Buildroot /Batocera/Tritium H5
Github hash: 02d4b821d755087d2db0fcb3bc002e198ac0fa22

Hardware: Allwinner H5 (Aarch64 Mesa3d-Lima for Mali450

**_Description of the Issue_**
Compile fails with following log

**_Logs Gathered_**

core/hw/pvr/Renderer_if.cpp: In function ‘void rend_create_renderer()’:
core/hw/pvr/Renderer_if.cpp:159:9: error: expected primary-expression before ‘}’ token
  159 |         }
      |         ^
make[4]: *** [CMakeFiles/flycast.dir/build.make:1658: CMakeFiles/flycast.dir/core/hw/pvr/Renderer_if.cpp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
core/hw/sh4/dyna/ssa.cpp: In member function ‘bool SSAOptimizer::ExecuteConstOp(shil_opcode*)’:
core/hw/sh4/dyna/ssa.cpp:365:61: warning: ‘rd2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  365 |                         constprop_values[RegValue(op->rd2)] = rd2;
{standard input}: Assembler messages:
{standard input}:2557: Warning: ignoring changed section attributes for .text
make[3]: *** [CMakeFiles/Makefile2:205: CMakeFiles/flycast.dir/all] Error 2
make[2]: *** [Makefile:136: all] Error 2

**Comment by flyinghead** [comment]
For GLES 2.0 targets, you need both USE_OPENGL=ON and USE_GLES2=ON cmake parameters.

**Comment by Ntemis** [comment]
Compiles fine now thanks
