### ISSUE TITLE
Android fluctuating framerate, vulkan issue on SD 888

### ISSUE THREAD

**Issue by Flyinggoose2** [flyinghead/flycast#821]
Platform / OS / Hardware: Android 12, Mi 11, Snapdragon 888

Hi there !  Like the title says:
By using the miui gamebooster app everything runs 98% perfect. The gamebooster reduced the stutter to a fluctuating framerate. Its minimal but definitely noticeable. Would be so great If fixed. Affects all emulated systems.

Seconds issue:
On mi 11 5g Snapdragon 888 the vulkan renderer doesnt work per pixel.

  * Fill in any steps already tried here
All settings combination tried without success

**Comment by flyinghead** [comment]
Can you give more specific about your "fluctuating framerate"?
Which game(s) did you test?
What is the variation range of the FPS counter when in game?

Regarding per pixel not working on Snapdragon 888, you will have to complain to Qualcomm. [This is an old post but unfortunately still relevant](https://dolphin-emu.org/blog/2013/09/26/dolphin-emulator-and-opengl-drivers-hall-fameshame/).
It used to work great on SD, then I had to [work around a bug after a driver update](https://github.com/flyinghead/flycast/commit/d75072362a77952d391e72f24c75247f2736518f).
But on SD888 even the most basic features needed for per-pixel don't work. Their drivers are getting worse with each release.

**Comment by Flyinggoose2** [comment]
Seen in doa and ikaruga. Just look carefully for small lags, let doa just
play the demo and in ikaruga when the ship launches after starting the
game. It takes a bit but is nearly periodic and stays. Also see in shodown
on atomiswave in sideways scrolling things. The framecounter isnt static. I
varies within a few frames.

flyinghead ***@***.***> schrieb am Di., 13. Dez. 2022, 22:18:

**Comment by Gonckzilla** [comment]
I've experienced both audio and frame pacing stutters before. Have you tried manually changing audio driver and latency? Enabled vsync? Those two have been the most important in my experience to mitigate stutters. 

Enabling or disabling multithreading might be of use too, but I've not had any certain results yet. I keep it off because my heart tells me to haha, lmk if you test these settings

**Comment by Flyinggoose2** [comment]
Hi there !!!

Keyed all settingcombinations out like i always do. No success.

Thing is the retroarch core seems to run without hiccups. But no wireless
multiplayer so i dont use it. Believe it or not, until its an emergency i
dont use  emulators without netplay or imperfect runtime at all. Like
Nintendo switch multiplayer games without local wireless. Except Doom 2016
and Fortnite. But i keep nagging them both. I find it more than suspicious
those having no wireless...  Having these principles always makes me a very
happy gamer. I own as good as all aaa titles for the switch having wireless.

Gonckzilla ***@***.***> schrieb am Fr., 13. Jan. 2023, 08:26:

**Comment by Flyinggoose2** [comment]
Its only graphic hiccups. Audio stream runs like it has to so far i can say.

Gonckzilla ***@***.***> schrieb am Fr., 13. Jan. 2023, 08:26:

**Comment by flyinghead** [comment]
Inactive
