### ISSUE TITLE
Show Device ID when Using Rawinput for Light Guns

### ISSUE THREAD

**Issue by magicray1028** [flyinghead/flycast#835]
**Is your feature request related to a problem? Please describe.**
Since 2.0 device ID no longer shows when using rawinput, making it hard to identify which mouse is a light gun

**Describe the solution you'd like**
Would be great if we can revert to the 1.3 style where IDs are shown.

**Comment by flyinghead** [comment]
Related to https://github.com/flyinghead/flycast/issues/664
