### ISSUE TITLE
lupinsho offscreen reload button only registers a shot being fired on screen

### ISSUE THREAD

**Issue by WarpedPolygon** [flyinghead/flycast#840]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:
RetroArch Core
Windows 
AMD FX 8350 Eight-Core Processor 4.00 GHz
16GB ram
NVIDIA 960 
Github hash: 

**_Description of the Issue_**
When reloading in this game using "input_player1_gun_offscreen_shot_mbtn" it is just registering a shot being fired on screen 

**_Debugging Steps Tested_**

 Upon checking in the I/O test screen it appears as if the reload button is doing it's job (removing cursor from screen and firing a shot). The test menu registers the gun pointing offscreen and the trigger button registers as on at the same time.

I think I have figured what is going on. The trigger input is being registered BEFORE it is being registered as offscreen. There needs to be a delay between the cursor being removed from screen and the trigger input turning on.

I couldn't find just an offscreen button that doesn't register a trigger input at the same time. This would be a work around as you can simply hold the offscreen button and press the trigger whenever you need to.

**Comment by flyinghead** [comment]
Tested with standalone and reload works normally. The "SCOPE" button (naomi button 2) apparently doesn't need to be pressed for correct reload, and pressing it as well doesn't seem to affect reload.

I'll have to test with RA to figure out what is going on.

**Comment by normchomsky** [comment]
I tried holding every aux gun input at the same time as the trigger and reload button to no avail. I cant see a shot actually being placed on screen when using reload, just get the sound effect of a shot being fired and loose 1 bullet.

**Comment by SeongGino** [comment]
If this is supposed to concern RA, I tested lupinsho with RA release 1.14.0 on Linux and the aux button as offscreen reload seems to work fine.

**Comment by normchomsky** [comment]
Updated RA to 1.14.0 and tried this again with 2 different mice with the same outcome. Windows based. Tried all 4 graphics backends also.

**Comment by flyinghead** [comment]
This is due to the calibration of the light gun. Make sure that you don't calibrate the top-left corner as coordinates 0,0 because this is the gun reload position. Recalibrate so that the top-left is at least 1,1.

**Comment by drewjbx1** [comment]
> Best calibration values :
> 
> Right = ff Left = 01 Top = 01 Bottom = ff Center = 80
> 
> Reload button works fine. If you use RetroArch core be sure to map in Settings->Input->Controller Port A->LightGun same button for Reload and Aux A This is needed for this game and Death Crimson OX.
> 
> GREETs

Hey can you share you libretro nvram for lupinsho.. I cannot get the Left and Right =01 calibration values
