### ISSUE TITLE
hmgeo has Jump incorrectly tagged as Target. With Jump not registering as an input at all

### ISSUE THREAD

**Issue by normchomsky** [flyinghead/flycast#841]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
RetroArch Core
Windows
AMD FX 8350 Eight-Core Processor 4.00 GHz
16GB ram
NVIDIA 960

**_Description of the Issue_**

Tested all inputs in the inputs in the I/o test menu. Button 3 (Jump) isn't registering at all despite having every input set. The input tagged as Jump is actually the Target (lock on) button.

**Comment by flyinghead** [comment]
I tested the game input test and all 4 buttons are accessible, mapped to ABXY on my gamepad.
![image](https://user-images.githubusercontent.com/16261910/209446192-0d8de353-c437-4998-bf64-c90651083a88.png)

**Comment by normchomsky** [comment]
Using the default layout: Jump is actually X not Y when in game, and target is on Y not RB which does not reflect the control settings.

Here is how the default layout appears for me. Even tho Target is on RB it registers on the face buttons instead, not RB as nothing is being registered when pressing this. 

So here is how the default controls appear in the image below, and the image underneath that is of the test menu with me pressing XABY only with that default layout.
![Screenshot (22)](https://user-images.githubusercontent.com/40608991/209449307-4d5ded00-e39b-488c-8001-3b7457ca1cc8.png)
![Screenshot (26)](https://user-images.githubusercontent.com/40608991/209449314-e4786754-9e0a-49bc-8379-537370456036.png)


Now if I simply remap Attack from Y to X like in the image below, I get Shot 3 not being registered at all when Attack is actually Shot 2. Shot 3 is Jump and is being affected by the remap even if you are not changing Shot 3. This happens with any layout.

The input test image is of me holding ABXY only, with the remapped controls. 

![Screenshot (29)](https://user-images.githubusercontent.com/40608991/209449565-e767dc1b-6096-4b1f-bb3d-6601623a61c0.png)
![Screenshot (27)](https://user-images.githubusercontent.com/40608991/209449572-ba0bd468-39b1-477b-af0e-9334f06d87fa.png)

**Comment by flyinghead** [comment]
I fixed the button labels that were wrong. The new settings are:
A: Fire
B: Attack
X: Jump
Y: Target

Note that I just changed the labels, not the mappings, so I'm not sure it will fix the remapping problem.

The changes should be in libretro in the next 24h.

**Comment by normchomsky** [comment]
All fixed with no issues remapping. Dude, you are committed. Updating this on Christmas Day no less, I fully appreciate your work and speed. Cheers mate
