### ISSUE TITLE
[Feature Request] Screenshot by button

### ISSUE THREAD

**Issue by vkedwardli** [flyinghead/flycast#842]
[Blace (Captain N)](https://discord.com/channels/627187835945877505/627187836441067533/1057026376345063424): 
So ehm. I was wondering about something
I was just wondering, are there any plans to implement a screenshot feature in any upcoming updates.
Preferably one that could me mapped to a button on a controller and only do a screenshot of the actual video output in it's native resolution?
It would be a neat little thing to have as messing around with stuff like Print Screen is always so cumbersome

**Comment by MediaMaquina** [comment]
+1 yes please!

**Comment by GravityMage23** [comment]
seconding (er, thirding?) this! I'd kill for a built-in screenshot button

**Comment by dante3732** [comment]
F12 to screenshot please.

**Comment by flyinghead** [comment]
The latest build on the `dev` branch  has a new screenshot feature, bound to F12 by default.

**Comment by flyinghead** [comment]
now on master as well
