### ISSUE TITLE
Sonic Adventure 2 - Background music just stop mid level.

### ISSUE THREAD

**Issue by gittyno1** [flyinghead/flycast#843]
Platform / OS / Hardware: 
Nintendo Switch running Atmosphere + RetroArch Homebrew
Hardware: Nintendo Switch

Description of the Issue:
Sonic Adventure 2: The game stops playing background music mid levels. I think it wont loop the music and once the track ended it wont play it again and its silent. Everything else can be heard except the music.

The game runs basically perfect. If that can be fixed somehow it would be awesome.

If you need any additional info please feel free to ask me, i will provide.

**Comment by flyinghead** [comment]
Which Flycast version are you using?
Which SA2 level(s) are affected?

**Comment by gittyno1** [comment]
> Which Flycast version are you using? Which SA2 level(s) are affected?

I updated cores the other day, but not the RetroArch itself (if that's needed i will).
So... RetroArch version is: v1.10.3 and the Core version is: Flycast **(0.1 4c293f3)**

As for the game, as far as i'm aware of, **all of the levels**, it's a general thing i believe with the background music.
I havent played the whole game since its annoying playing it in silence with just sound effects and no music.
Hehe, music is a big part of Sonic Adventure 2 games. :)

**Comment by flyinghead** [comment]
The issue is the Flycast core on Switch hasn't been updated for some time, and isn't based on the new flycast core in this repository. RA still needs to integrate this new version of the core.

Can you try standalone Flycast to check if the same problem happens?

**Comment by gittyno1** [comment]
I can try, yes.

**Comment by gittyno1** [comment]
> The issue is the Flycast core on Switch hasn't been updated for some time, and isn't based on the new flycast core in this repository. RA still needs to integrate this new version of the core.
> 
> Can you try standalone Flycast to check if the same problem happens?

I just downloaded the latest standalone Flycast from here, tried it, and it does the same.
Not just in levels but title screen BG music after 5 sec. Even worst than in RA i believe.
But the bottom line is that music doesn't loop or play non stop, it just stops after a while, still.

**Comment by flyinghead** [comment]
What of kind of media are you using? cdi, gdi, chd, cue?

I just checked a couple of levels and the music definitely isn't stopping for me. I doubt this is a platform-specific issue and nobody has reported such an issue.

**Comment by gittyno1** [comment]
> 

I'm using CDI, USA version.
Yeah, i have no problems on PC.
Well i guess i have reported, i guess that counts...

What of kind of media are you using? cdi, gdi, chd, cue? So i can replicate what you do.

**Comment by gittyno1** [comment]
> What of kind of media are you using? cdi, gdi, chd, cue?
> 
> I just checked a couple of levels and the music definitely isn't stopping for me. I doubt this is a platform-specific issue and nobody has reported such an issue.

Well, i have reported it, i guess that counts...
I'm using CDI, USA version.
I'm using Switch, Standalone and RetroArch core, same issue, default settings.

What of kind of media are you using? cdi, gdi, chd, cue? So i can replicate what you do.
