### ISSUE TITLE
Unhandled SH4 exception when applying certain cheats

### ISSUE THREAD

**Issue by throwaway1908** [flyinghead/flycast#849]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Windows 10

Github hash: 85188bf

Hardware: Intel core i7-9700KF 3.6GHz, ASUS ROG Strix NVIDIA GeForce RTX 3080 32GB RAM.

**_Description of the Issue_**

After applying cheats to certain games, the game stops running and I get an "Unhandled SH4 exception" and it refuses to boot the rom back up again. This happens at random. Sometimes the cheat codes work with the rom, other times they get this error. 

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![image](https://user-images.githubusercontent.com/60544658/210568394-2adfb94c-bd8e-49be-ac81-34d556be25f4.png)

**Comment by flyinghead** [comment]
Please list the game(s) you have problems with, including the edition (US, JP, EU)

In particular the one(s) that can't be relaunched afterwards.

**Comment by throwaway1908** [comment]
Mostly Sonic Adventure 2 (JP) is the one that has the random relaunch issues.

**Comment by throwaway1908** [comment]
Not sure if this will help locate the issue, but here are the two cheat files which causes the random crashing: 
https://drive.google.com/file/d/1Ae184hewfty6MMAijaR7Dyhu2cDl_oHw/view?usp=share_link
https://drive.google.com/file/d/1-jtyCSCaoepRaeodzhSGYmxU9LA_HuDI/view?usp=share_link

**Comment by flyinghead** [comment]
I thought you were talking about widescreen cheats, which are built in and tested so they don't break the game.

For other cheats you should check with the cheat author. Cheats can write arbitrary data to the game memory at runtime so they can easily make it crash.

As for the rom that cannot be run again, I suppose the cheat is still enabled and prevents the BIOS from booting.

**Comment by throwaway1908** [comment]
Ah, that explains it then. Will you be adding in a feature in the future that allows other cheats to run without crashing?

**Comment by flyinghead** [comment]
Again, it's not a Flycast issue but a cheat one. If a cheat makes a game crash, there's nothing Flycast can do.
