### ISSUE TITLE
Allow 1 keyboard / iPAC to map two players 

### ISSUE THREAD

**Issue by magicray1028** [flyinghead/flycast#850]
When using a keyboard based encoder like iPAC it’s impossible to assign player 1 and 2 individual mappings. Would need two separate keyboard encoders to be able to work 2 players currently.

for example if I wanted to use a single iPAC encoder that sends 1 and 2 for player 1 and 2 start keys , it’s impossible to assign since the encoder only allows mapping for Player A or B not both.

**Describe alternatives you've considered**
Adding mappings for both player 1 and 2 to keyboard only devices would easily fix this problem.

**Comment by flyinghead** [comment]
It's already possible. Assign your keyboard to port `All`:
![image](https://user-images.githubusercontent.com/16261910/211006956-2611635e-24a4-4037-8c9e-8dc9a2fb005e.png)

Then click Map and you can choose which player the binding is assigned to in the upper left corner:
![image](https://user-images.githubusercontent.com/16261910/211007194-7ad0d440-e44b-4fd0-8a28-2e1e3e8497c2.png)

**Comment by magicray1028** [comment]
Thank you!!!!
