### ISSUE TITLE
vf3tb attract mode, issues with BGM and graphics being out of sync

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#853]
Platform / OS / Hardware: win10 1809

Github hash: newest master and dev

Hardware: intel i3 + hd 5300 + dx11

Game: Virtua Fighter 3tb (Japan) (Rev 1)

Issue:

Through the vf3tb attract mode,the BGM and graphics being out of sync.
When the character loading screen appears, the BGM will be interrupted briefly,At the end of the BGM, the title screen does not just appear on the screen.（I tested it with my physical Dreamcast, it should be)

**Comment by crashGG** [comment]
At the end,the BGM is about 10 seconds behind the graphics

**Comment by flyinghead** [comment]
I noticed the BGM running behind the graphics when comparing with a real dreamcast.

However I'm not sure about the other issue with the title screen. I see this title screen when the BGM music stops, and before a demo fight without music.
![image](https://user-images.githubusercontent.com/16261910/211206664-ce127a16-cb1c-4be3-a108-117cac16aaaf.png)

**Comment by crashGG** [comment]
On my computer, when the BGM music stops,the next demo fight (without music) has started for a few seconds

**Comment by crashGG** [comment]
In addition, redream bgm and graphics are synchronized, just like a real DC.

**Comment by flyinghead** [comment]
use redream then

**Comment by crashGG** [comment]
> use redream then

Sorry I didn't mean to offend, and compare the two emulator. I mean, if you're not sure about the other issue with the title screen,and there is no real DC in hand to refer,In this case, you can refer to redream
