### ISSUE TITLE
Emuelec 4.6 build error on Flycast libretro latest commit

### ISSUE THREAD

**Issue by MSHectorCM** [flyinghead/flycast#859]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Emuelec 4.6/ ubuntu 20.04 / odroid n2+

Github hash: 

611946559c12a569af507019694cb369b3587af6 

Hardware: 

Odroid n2+ with Emuelec 4.6 SDL 2.6.1 Retroarch 7213aada8d5fef72a93379a0d700bb1b678e4a70

When building Libretro Version of Flycast getting error

/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycast-611946559c12a569af507019694cb369b3587af6/core/rend/gles/gldraw.cpp: In function 'void writeFramebufferToVRAM()':
/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycast-611946559c12a569af507019694cb369b3587af6/core/rend/gles/gldraw.cpp:701:43: error: 'GL_READ_FRAMEBUFFER' was not declared in this scope; did you mean 'GL_READ_FRAMEBUFFER_NV'?
  701 |                 gl.ofbo.framebuffer->bind(GL_READ_FRAMEBUFFER);
      |                                           ^~~~~~~~~~~~~~~~~~~
      |                                           GL_READ_FRAMEBUFFER_NV
/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycast-611946559c12a569af507019694cb369b3587af6/core/rend/gles/gldraw.cpp:702:48: error: 'GL_DRAW_FRAMEBUFFER' was not declared in this scope; did you mean 'GL_DRAW_FRAMEBUFFER_NV'?
  702 |                 gl.fbscaling.framebuffer->bind(GL_DRAW_FRAMEBUFFER);

Standalone version compiles fine with no issues

**_Debugging Steps Tested_**

  * Starting commit 7fec51146341d2b795cc22bbf6fba0c3ccc8ea97 and onwards the issue is present. Only the libretro version fails. 

**_Logs Gathered_**

``` Logs attached
[buildflyfail.txt](https://github.com/flyinghead/flycast/files/10382356/buildflyfail.txt)


Please paste the contents of the log / logs here
You may leave this field blank if you have none.

``` flycast-611946559c12a569af507019694cb369b3587af6/core/rend/gles/gldraw.cpp:701:43: error: 'GL_READ_FRAMEBUFFER' was not declared in this scope; did you mean 'GL_READ_FRAMEBUFFER_NV'?

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Fixed on master. As expected there were additional issues at runtime but I tested it successfully on a GLES 2.0 device.

**Comment by MSHectorCM** [comment]
@flyinghead thx for the fast answer. It compiles but I noticed that for example Project justice/Moero! Justice Gakuen on libretro is not rendering the polygons correctly however in standalone version it works perfectly. Pls can you recheck it on your end? thx

**Comment by flyinghead** [comment]
Is it a black screen or some other issue?

**Comment by MSHectorCM** [comment]
@flyinghead no, when getting into the battle the fighters polygons and textures do not appear. The rest of the environment is there. You can see it in the pictures attached. 

![Project Justice no fighters 1](https://user-images.githubusercontent.com/122352874/212019655-e434bf54-09a8-448c-86cf-2cee85e93eff.jpeg)
![Project Justice no fighters 2](https://user-images.githubusercontent.com/122352874/212019657-edbd465e-6842-4594-93b5-1951c69ad9dc.jpeg)

Commit https://github.com/flyinghead/flycast/commit/1dd006d846350e96a46949f1e07a900206ae7194 that was latest working fine hadn't any issue.

Thx for your support and help :)

**Comment by flyinghead** [comment]
Can you post a debug RA log?

I thought you were compiling with GLES2 and HAVE_OPENGLES2 on (which means no support for GLES 3.x) but the odroid n2+ has a GLES 3.2 GPU. What may be happening is Flycast is using GLES 3 features but with some 3.x APIs missing.

**Comment by MSHectorCM** [comment]
Hello

Retroarch logs not working version from Jan 11th commit 

https://github.com/flyinghead/flycast/commit/2b70c73f8029c680fec1ee32fc88f09974c18381

[retroarch_notworking_flycast_2b70c73f8029c680fec1ee32fc88f09974c18381.log](https://github.com/flyinghead/flycast/files/10400655/retroarch_notworking_flycast_2b70c73f8029c680fec1ee32fc88f09974c18381.log)

Attaching retroarch logs from working version from dec 16th commit https://github.com/flyinghead/flycast/commit/1dd006d846350e96a46949f1e07a900206ae7194 

[retroarch_working_flycast_dec16_1dd006d846350e96a46949f1e07a900206ae7194.log](https://github.com/flyinghead/flycast/files/10400656/retroarch_working_flycast_dec16_1dd006d846350e96a46949f1e07a900206ae7194.log)

thx!!

**Comment by flyinghead** [comment]
I have confirmation that Flycast uses GLES 3.0 features:
```
[libretro INFO] core/rend/gles/gles.cpp:560 N[RENDERER]: OpenGL ES version 3.2
```

However, based on your initial compilation errors, I assume that you compiled with GLES 2.0 headers and libraries only. And that means that some GLES 3.0 APIs aren't available.

You need to compile with GLES 3 support: `cmake -DUSE_GLES=ON -DUSE_GLES2=OFF ...`

**Comment by MSHectorCM** [comment]
@flyinghead you did it :). Thx so much for your help and support. it is fixed now.
