### ISSUE TITLE
Wave Runner GP Flashing "CAUTION Do not place objects on steps." Message

### ISSUE THREAD

**Issue by doodleintime** [flyinghead/flycast#861]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11 Home 22H2.

Github hash: earliest master build with issue: 493ccc2 latest master build without issue: 85188bf .

Hardware: AMD Ryzen 7 2700X 3.70 GHz, GeForce GTX 1070 8GB VRAM, 16 GB DDR4 RAM.

**_Description of the Issue_**

On 493ccc2 up to the current latest master build, 6119465, after pressing start to start the game, the warning described in the title displays at the bottom of the screen, flashing off and then quickly back on about every 1/3 of a second. After entering a race, the flashing stops, and stays on screen, obscuring the HUD.

**_Debugging Steps Tested_**

1. Booted up the game in 85188bf to see if the issue occurred (it did not).
2. Booted up the game in 493ccc2 to see if the issue occurred (it did).
3. Booted up the game in 6119465 to see if the issue still occurred (it did).

**_Logs Gathered_**

**_Screenshots_**
![Base Profile Screenshot 2023 01 10 - 18 21 30 59](https://user-images.githubusercontent.com/53154503/211685274-68c28766-2a36-4f5e-a237-f0163b73e12a.png)

**Comment by doodleintime** [comment]
I've tested the new build and the bug is fixed, though there is another Caution message that appears when loading a save state. I'll close this issue and open a new one for that bug.

**Comment by flyinghead** [comment]
Make sure to open a "clean" savestate. It's likely that the previous Caution error is saved in the state.

**Comment by doodleintime** [comment]
I did open a clean save sate (if that means saving a new one after this issue was fixed and loading that one).
