### ISSUE TITLE
libretro port does not accept correct widescreen ratio

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#863]
Platform / OS : win10 1809

Github hash: newest master

Hardware: intel i3 + hd 5300 + dx11

Game: all naomi games without widescreen cheats

Issue:

The following is an example of the game alienfnt

In retroarch ,video scaling aspect ratio is "core provided"
In Flycast.opt ,reicast_widescreen_hack = "enabled"，start the game,the screen does not get a 16:9 ratio.
<img width="721" alt="2023-01-11_210545" src="https://user-images.githubusercontent.com/80488411/211886467-200d535b-5b80-4ac6-9a1c-66cb4c1cc2c4.png">

But when reicast_widescreen_hack = "disabled", start the game,and manually open the quick menu - core options - emulation hacks - wildscreen hack - enabled, the screen can get the correct 16:9 ratio.
<img width="913" alt="2023-01-11_210735" src="https://user-images.githubusercontent.com/80488411/211886879-a2b7f5b5-8fb5-4a5c-9079-accc20e50320.png">

**Comment by flyinghead** [comment]
I can't reproduce this issue. I tried both RetroArch 1.9.14 and the latest 1.14.0 and widescreen works fine is all cases. Tested with DX11, OpenGL and Vulkan, with Naomi and console games.

Can you post a RA log? You should see when the framebuffer dimensions or aspect ratio change:
```
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.778.
```

**Comment by crashGG** [comment]
Here is the log when use reicast_widescreen_hack = "enabled" start the game:

[INFO] RetroArch 1.14.0 (Git e3c92b0)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Fullscreen set to 1920x1080 @ 60Hz on device \\.\DISPLAY1.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Found GPU at index 0: "Intel(R) HD Graphics 5300".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\EMU\RetroArch\content_favorites.lpl".
[INFO] [Core]: Using content: "T:\EMU\ARC\roms.naomi\alienfnt.zip".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.14.0 (Git e3c92b0)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "cores\flycast_libretro.dll"
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Overrides]: Redirecting save file to "saves\alienfnt.srm".
[INFO] [Overrides]: Redirecting save state to "states\alienfnt.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] shell/libretro/libretro.cpp:310 N[BOOT]: retro_init
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[libretro INFO] core/hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4dd5e0000 RAM(16 MB) 00007ff4e95e0000 VRAM64(8 MB) 00007ff4e15e0000 ARAM(2 MB) 00007ff4fd5e0000
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] shell/libretro/libretro.cpp:1781 N[BOOT]: retro_load_game: T:\EMU\ARC\roms.naomi\alienfnt.zip
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
[libretro INFO] File extension is: .zip
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: d3d11.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_DIRECT3D.
[INFO] [Environ]: SET_HW_RENDER, context type: d3d11.
[INFO] Requesting D3D11 context.
[INFO] Reached end of SET_HW_RENDER.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] core/hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4dd5e0000 RAM(32 MB) 00007ff4e95e0000 VRAM64(16 MB) 00007ff4e15e0000 ARAM(8 MB) 00007ff4fd5e0000
[libretro INFO] core/hw/naomi/naomi_cart.cpp:582 N[NAOMI]: NAOMI GAME ID [ALIEN FRONT] region ff players 0 vertical 0
[libretro INFO] core/emulator.cpp:236 N[BOOT]: Game ID is [ALIEN FRONT]
[libretro INFO] core/emulator.cpp:236 N[BOOT]: Game ID is [ALIEN FRONT]
[INFO] [Environ]: SET_ROTATION: 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[libretro INFO] shell/libretro/libretro.cpp:2115 N[RENDERER]: retro_get_system_av_info: Res=960
[INFO] [Audio]: Set audio input rate to: 44101.76 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Using HW render, d3d11 driver forced.
[INFO] [Video]: Fullscreen set to 1920x1080 @ 60Hz on device \\.\DISPLAY1.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Found GPU at index 0: "Intel(R) HD Graphics 5300".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[libretro INFO] shell/libretro/libretro.cpp:1729 N[RENDERER]: DX11 context reset
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:64 N[RENDERER]: DX11 Context terminating
[libretro INFO] core/rend/dx11/dx11_shaders.cpp:681 N[RENDERER]: Saved 0 shaders to system\dc\dx11_shader_cache.bin
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:76 N[RENDERER]: DX11 Context terminated
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:28 N[RENDERER]: DX11 Context initializing
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:51 N[RENDERER]: No system-provided shader cache
[libretro INFO] core/rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 0 shaders from system\dc\dx11_shader_cache.bin
[libretro INFO] core/rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[ERROR] Rewind unavailable because this core lacks serialized save state support.
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\EMU\RetroArch\content_favorites.lpl".
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_MESSAGE: Network started

**Comment by crashGG** [comment]
Here is the log when use reicast_widescreen_hack = "disabled" start the game,then manually open wildscreen hack :

[INFO] RetroArch 1.14.0 (Git e3c92b0)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Fullscreen set to 1920x1080 @ 60Hz on device \\.\DISPLAY1.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Found GPU at index 0: "Intel(R) HD Graphics 5300".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\EMU\RetroArch\content_favorites.lpl".
[INFO] [Core]: Using content: "T:\EMU\ARC\roms.naomi\alienfnt.zip".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.14.0 (Git e3c92b0)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "cores\flycast_libretro.dll"
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Overrides]: Redirecting save file to "saves\alienfnt.srm".
[INFO] [Overrides]: Redirecting save state to "states\alienfnt.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] shell/libretro/libretro.cpp:310 N[BOOT]: retro_init
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[libretro INFO] core/hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4dd5e0000 RAM(16 MB) 00007ff4e95e0000 VRAM64(8 MB) 00007ff4e15e0000 ARAM(2 MB) 00007ff4fd5e0000
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] shell/libretro/libretro.cpp:1781 N[BOOT]: retro_load_game: T:\EMU\ARC\roms.naomi\alienfnt.zip
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
[libretro INFO] File extension is: .zip
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: d3d11.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_DIRECT3D.
[INFO] [Environ]: SET_HW_RENDER, context type: d3d11.
[INFO] Requesting D3D11 context.
[INFO] Reached end of SET_HW_RENDER.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] core/hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4dd5e0000 RAM(32 MB) 00007ff4e95e0000 VRAM64(16 MB) 00007ff4e15e0000 ARAM(8 MB) 00007ff4fd5e0000
[libretro INFO] core/hw/naomi/naomi_cart.cpp:582 N[NAOMI]: NAOMI GAME ID [ALIEN FRONT] region ff players 0 vertical 0
[libretro INFO] core/emulator.cpp:236 N[BOOT]: Game ID is [ALIEN FRONT]
[libretro INFO] core/emulator.cpp:236 N[BOOT]: Game ID is [ALIEN FRONT]
[INFO] [Environ]: SET_ROTATION: 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[libretro INFO] shell/libretro/libretro.cpp:2115 N[RENDERER]: retro_get_system_av_info: Res=960
[INFO] [Audio]: Set audio input rate to: 44101.76 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Using HW render, d3d11 driver forced.
[INFO] [Video]: Fullscreen set to 1920x1080 @ 60Hz on device \\.\DISPLAY1.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Found GPU at index 0: "Intel(R) HD Graphics 5300".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[libretro INFO] shell/libretro/libretro.cpp:1729 N[RENDERER]: DX11 context reset
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:64 N[RENDERER]: DX11 Context terminating
[libretro INFO] core/rend/dx11/dx11_shaders.cpp:681 N[RENDERER]: Saved 0 shaders to system\dc\dx11_shader_cache.bin
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:76 N[RENDERER]: DX11 Context terminated
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:28 N[RENDERER]: DX11 Context initializing
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:51 N[RENDERER]: No system-provided shader cache
[libretro INFO] core/rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 0 shaders from system\dc\dx11_shader_cache.bin
[libretro INFO] core/rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[ERROR] Rewind unavailable because this core lacks serialized save state support.
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\EMU\RetroArch\content_favorites.lpl".
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.333.
[INFO] [Environ]: SET_MESSAGE: Network started
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.778.

**Comment by crashGG** [comment]
I used libretro flycast 2.0 (08.09) with reicast_widescreen_hack = "enabled"，start the game,the screen  get a 16:9 ratio.Here is the log:

[INFO] RetroArch 1.14.0 (Git e3c92b0)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Fullscreen set to 1920x1080 @ 60Hz on device \\.\DISPLAY1.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Found GPU at index 0: "Intel(R) HD Graphics 5300".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\EMU\RetroArch\content_favorites.lpl".
[INFO] [Core]: Using content: "T:\EMU\ARC\roms.naomi\alienfnt.zip".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.14.0 (Git e3c92b0)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "cores\flycast_libretro.dll"
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Overrides]: Redirecting save file to "saves\alienfnt.srm".
[INFO] [Overrides]: Redirecting save state to "states\alienfnt.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] shell/libretro/libretro.cpp:308 N[BOOT]: retro_init
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[libretro INFO] core/hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
[libretro INFO] core/hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff4dd5e0000 RAM(16 MB) 00007ff4e95e0000 VRAM64(8 MB) 00007ff4e15e0000 ARAM(2 MB) 00007ff4fd5e0000
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] shell/libretro/libretro.cpp:1785 N[BOOT]: retro_load_game: T:\EMU\ARC\roms.naomi\alienfnt.zip
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
[libretro INFO] File extension is: .zip
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: d3d11.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_DIRECT3D.
[INFO] [Environ]: SET_HW_RENDER, context type: d3d11.
[INFO] Requesting D3D11 context.
[INFO] Reached end of SET_HW_RENDER.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] core/hw/mem/_vmem.cpp:494 N[VMEM]: Info: nvmem is enabled, with addr space of size 512MB
[libretro INFO] core/hw/mem/_vmem.cpp:589 N[VMEM]: BASE 00007ff4dd5e0000 RAM(32 MB) 00007ff4e95e0000 VRAM64(16 MB) 00007ff4e15e0000 ARAM(8 MB) 00007ff4fd5e0000
[libretro INFO] core/hw/naomi/naomi_cart.cpp:579 N[NAOMI]: NAOMI GAME ID [ALIEN FRONT] region ff players 0 vertical 0
[libretro INFO] core/emulator.cpp:223 N[BOOT]: Game ID is [ALIEN FRONT]
[INFO] [Environ]: SET_ROTATION: 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[libretro INFO] shell/libretro/libretro.cpp:2120 N[RENDERER]: retro_get_system_av_info: Res=960
[INFO] [Audio]: Set audio input rate to: 44101.76 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Using HW render, d3d11 driver forced.
[INFO] [Video]: Fullscreen set to 1920x1080 @ 60Hz on device \\.\DISPLAY1.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [D3D11]: Device created (Feature Level: 11.0)
[INFO] [D3D11]: Flip model and tear control supported and enabled.
[INFO] [D3D11]: Found GPU at index 0: "Intel(R) HD Graphics 5300".
[INFO] [D3D11]: Found GPU at index 1: "Microsoft Basic Render Driver".
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: "win32".
[libretro INFO] shell/libretro/libretro.cpp:1732 N[RENDERER]: DX11 context reset
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:61 N[RENDERER]: DX11 Context terminating
[libretro INFO] core/rend/dx11/dx11_shaders.cpp:681 N[RENDERER]: Saved 0 shaders to system\dc\dx11_shader_cache.bin
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:73 N[RENDERER]: DX11 Context terminated
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:28 N[RENDERER]: DX11 Context initializing
[libretro INFO] core/rend/dx11/dx11context_lr.cpp:51 N[RENDERER]: No system-provided shader cache
[libretro INFO] core/rend/dx11/dx11_shaders.cpp:707 N[RENDERER]: Loaded 0 shaders from system\dc\dx11_shader_cache.bin
[libretro INFO] core/rend/dx11/dx11_renderer.cpp:41 N[RENDERER]: DX11 renderer initializing
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[ERROR] Rewind unavailable because this core lacks serialized save state support.
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\EMU\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\EMU\RetroArch\content_favorites.lpl".
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_MESSAGE: Network started

**Comment by flyinghead** [comment]
I just pushed a tentative fix for the issue. I still can't reproduce it on my end but now the window is resized with dx11.

**Comment by crashGG** [comment]
it fixed. test with the newest 93fbd67
