### ISSUE TITLE
Wave Runner GP "CAUTION The motion stop button has been pressed" message appears after loading a save state

### ISSUE THREAD

**Issue by doodleintime** [flyinghead/flycast#864]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11 Home 22H2

Github hash: 673fb26

Hardware: AMD Ryzen 7 2700X 3.70 GHz, GeForce GTX 1070 8GB VRAM, 16 GB DDR4 RAM.

**_Description of the Issue_**

Upon loading a save state that is in gameplay (in other words, racing on a track), the game displays the message "CAUTION The motion stop button has been pressed" message appears. If you load a state before loading a track (for example, loading a state on the attract mode and then starting a game or loading one that is in the start game tutorial/track select) the message will instead be the "Do not place objects on steps" message, which turns into the motion stop button message upon loading a track.

**_Debugging Steps Tested_**

  * Loaded a state in all game states mentioned.
  * Tried to see if interpreter mode would fix it (it didn't).

**_Logs Gathered_**

**_Screenshots_**
![Base Profile Screenshot 2023 01 11 - 16 42 45 64](https://user-images.githubusercontent.com/53154503/211926402-c08ee75e-4da8-4ccd-9f5f-d51c8a7c9d7e.png)

**Comment by flyinghead** [comment]
Previously the default output board value was the "right" one. This isn't the case anymore hence this bug.
It should really be saved in the savestate along with some other values introduced around the same time (18wheeler).

**Comment by flyinghead** [comment]
Should be fixed in the latest master build.

**Comment by doodleintime** [comment]
Tested on commit f7e227a, the issue is fixed. Sorry for the late response, got engrossed in Sega arcade racers. Also, when booting up the game or exiting the test menu, the first attract sequence has the jet ski and the rider rendered in pitch black. I'd figured that if it happened for you that you would mention it, but you have not yet. Even if you have seen it, should I still file a new issue in for it?

**Comment by flyinghead** [comment]
Yes it's a known issue but ... still an issue
