### ISSUE TITLE
Wildscreen cheats of Ikaruga not working in the right way

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#866]
Platform / OS : win10 1809

Github hash: newest master

Hardware: intel i3 + hd 5300 + dx11

Game: Ikaruga (Japan)

Issue:
Wildscreen cheats of Ikaruga not working in the right way

original 4:3：
<img width="721" alt="4b3" src="https://user-images.githubusercontent.com/80488411/212135037-8e1f249e-7d60-4f79-a38b-e8b660a779ff.png">

with wildscreen cheats:
<img width="955" alt="wrong" src="https://user-images.githubusercontent.com/80488411/212135112-b2e58a52-88ab-4a7f-ab0f-2e3b0df1410b.png">

Obviously the widescreen cheats just stretches the screen, the screen loses its right ratio.

**Comment by crashGG** [comment]
On this website,  can see that there are additional renderings on the left and right sides, but I don't know how to achieve it.
https://mazekb.tistory.com/188
![1](https://user-images.githubusercontent.com/80488411/212139542-5628c76b-484e-4e65-b917-6f9a04c418aa.png)
![2](https://user-images.githubusercontent.com/80488411/212139574-7e752d89-f456-4766-a10a-288e25952232.png)

![3](https://user-images.githubusercontent.com/80488411/212139601-2ce04e50-b718-4834-a1a0-4be25f939bbf.png)

**Comment by flyinghead** [comment]
Indeed it doesn't seem to work. I tried a slightly different one, which didn't work either. So I disabled it for now.
