### ISSUE TITLE
Shutokou Battle 2 (Japan) missing some textures

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#867]
Platform / OS : win10 x64 1809

Github hash: 93fbd67 (Jan,12,2023)

Hardware: intel i3 + hd 5300 + dx11

Shutokou Battle 2 (Japan)

Issue:
When using Per-Triangle
Quest - Start Newgame - class select 
The screen is missing some texture
<img width="721" alt="bad" src="https://user-images.githubusercontent.com/80488411/212303825-bcb42d1f-82a6-4642-b5c8-9f5f9aa5df37.png">

But when using Per-Strip  or Per-Pixel, the screen doesn't have this problem
<img width="721" alt="right" src="https://user-images.githubusercontent.com/80488411/212304027-1268d1f3-c44a-4676-af5f-bac8a57d3b5e.png">

and with flycast 2.0,whether using Per-Triangle ,Per-Strip  or Per-Pixel, there is no such problem.

**Comment by flyinghead** [comment]
Same issue with OpenGL and Vulkan. Offending commit: f9feaa313b37b4033651b6be434dd41432fd7806

**Comment by flyinghead** [comment]
Should be fixed on latest master

**Comment by crashGG** [comment]
It has been fixed. test with https://github.com/flyinghead/flycast/commit/1e195b7237afceeef725e4f45afd9821e34bf53c
