### ISSUE TITLE
Unlicensed Teenage Mutant Ninja Turtles: The Cowabunga Collection frozen/halt at startup screen

### ISSUE THREAD

**Issue by Kelvfimer** [flyinghead/flycast#868]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Linux Odroid n2+ emuelec 4.6

Github hash: 

92fa4c041d3e51ac08d7d5b94435fbb5182ba8f4

Hardware: 

Odroid n2+

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

Start game and the game is halt/frozen at start screen

**_Logs Gathered_**

I tried to retrieve logs but no relevant data about it

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```


**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Interestingly fixed by 4efacd7d714c74bce701edd47819bcc788be0bc1.
There is a graphical issue with the Genesis emulator but other emulators seem to work fine.

**Comment by flyinghead** [comment]
Genesis emulator fixed on the `dev` branch:
![image](https://github.com/user-attachments/assets/6a7910fb-2569-4a50-8cd6-98f645f2fc85)

**Comment by Kelvfimer** [comment]
You are an ace!!! Thx @flyinghead !!
