### ISSUE TITLE
[Android] "Horizontal Stretching": customized setting does not save.

### ISSUE THREAD

**Issue by Gonckzilla** [flyinghead/flycast#870]
Platform / OS / Hardware: Android 12, Snapdragon 888. Realme brand device.

Using dev build ac24d9b

When using widescreen, the horizontal stretch will always default to the value "134" after ending the game session and starting a new one. Changing the setting works but you have to change it every time you load a game, it doesn't persist. Behavior is present both in per-game settings and global. 

Tried closing the app after applying too, same result. 

Here's a video (36s) in case it helps https://drive.google.com/file/d/17g_oWb9Dlvkn_m9nyjeec4eewzKMItoA/view?usp=drivesdk

**Comment by flyinghead** [comment]
Confirmed: currently there's no way to override this setting when using a widescreen cheat. A fix is coming.

**Comment by Gonckzilla** [comment]
Yayy, I'll be keeping my eyes peeled! :)

**Comment by flyinghead** [comment]
Should be fixed on master

**Comment by Gonckzilla** [comment]
Yep! Working with no issues so far. The issue is solved. Thank you!
