### ISSUE TITLE
Issues with command line startup games with East Asian filenames

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#875]
Platform / OS : win10 x64 1809

Github hash: newest

Hardware: intel i3 + hd 5300 + dx11

Issue:

Start the games with East Asian filenames at the command line, it doesn't work.for example:
flycast.exe “T:\EMU\DC\roms\首都高 2 (Japan) [T+CHN].chd”

<img width="255" alt="2023-01-14_163210_cr" src="https://user-images.githubusercontent.com/80488411/212474686-da7e19bb-be82-44d0-8fdf-1ba167dabe6c.png">

but it works fine with libretro port,for example:
retroarch.exe -L cores\flycast_libretro.dll “T:\EMU\DC\roms\首都高 2 (Japan) [T+CHN].chd”

**Comment by flyinghead** [comment]
Should be fixed on master

**Comment by crashGG** [comment]
it has been fixed. test with 1e195b7
