### ISSUE TITLE
Mapping Lightgun to a gamepad?

### ISSUE THREAD

**Issue by Bandicoot37** [flyinghead/flycast#881]
Hello ,
Is there a way to map Lightgun to a analog gamepad?
I've got a Positionnal Gun with Y and X axis and not found how to map it for Arcade Gun Game.
Perhaps i've miss something
Thanks

**Comment by flyinghead** [comment]
No, lightgun games need a mouse, a normal lightgun or other pointer devices that gives absolute or relative coordinates.
It won't work if your gun is recognized as a gamepad.

**Comment by Bandicoot37** [comment]
find a way to make it work with Joytokey , better than nothing ;)

**Comment by ckeisc** [comment]
In addition to support some analogue guns available on the market, this is also useful for enable a particular combination of Dolphinbar mode 4 + touchmote software where one dolphinbar can support up to 4 wiimotes as xinput gamepads. Wiimote IR pointer would be route to thumbstick X/Y axis and Xinput would also allow for driving rumble motors on these analogue guns / wiimotes to simulate recoil on games with gun recoil. I tested such combination with emulators / apps that support this - MAME, Supermodel and Demulshooter - it can work as well as simulating mouse.

**Comment by carolis15** [comment]
Yes, to have this option would be great. It works really well with MAME and Supermodel with my Wiimote. I would love to be able to play with 2 players / lightguns

**Comment by flyinghead** [comment]
available on the dev branch

**Comment by flyinghead** [comment]
Now also for the libretro core (but on the master branch this time).

**Comment by ckeisc** [comment]
Tested on dev build and works great. The left thumb stick needs to be mapped though for this to work and that is not self evident. Anyways, great work and this is great news for lightgun fans.

**Comment by Trihy** [comment]
I use this for mame. But can't figure it out how to do it on flycast core.

Can someone tell which settings should I set? Controller 1 and 2 on controller or lightgun? 

Also not sure where to map the input. Analog stick is already mapped.

Thabks

**Comment by Trihy** [comment]
Tried setting controller 1 to pointer, mouse, lightgun, but none seems to use the analog stick.

**Comment by Trihy** [comment]
Oh, I got it working for Naomi. It works pretty much out of the box. No config needed.

I thought it work for DC too, it doesnt, right? Can be done somehow?

**Comment by flyinghead** [comment]
All console games that support lightguns also accept regular gamepads so there's no need for this feature.

**Comment by Trihy** [comment]
Thanks. Seems the same, but on practice is not the same.

I was not able to replicate with a X Y gun the same feeling that I can do on Naomi (mame, model3, etc). I can replicate the same feeling selecting lightgun, but that needs mouse emulation for gun and 2 players is complicated. 

No way to have the same feeling on DC like it´s now on Naomi?

**Comment by carolis15** [comment]
I use the latest dev build with Sinden for P1 and a wiimote as a gamepad for P2 and it works like a charm with DC, Naomi and Sammy

**Comment by Trihy** [comment]
Guess is not the same for wiimotes using analog stick xinput.

**Comment by Trihy** [comment]
Also noticed on Naomi that analog stick reach seems to be 4.3. With 16.9 I won't reach those sides of the screen.

**Comment by carolis15** [comment]
To be more precise I use the wiimote as a left analog stick, config as a lightgun. And you are correct the wiimote only reaches 4:3 sides of the screen

**Comment by Trihy** [comment]
When I set lightgun, it reacts only to mouse input. You can map Wiimote as mouse cursor and will work great, but you can't have two wiimotes that way.

**Comment by Trihy** [comment]
Tried Atomiswave too. Both Naomi and Atomis behave the same and works perfect with two wiimotes with xinput analog stick X Y emulation. Difference is clearly DC.

Shoot outside screen to reload is also some kind of hit&miss, depending on the game. Even doing service menu gun calibration didnt solve that on some games like naomi hotd2 and conf mission. Lupin seems to reload fine shooting outside the screen.

**Comment by Trihy** [comment]
Can we fix the screen area? I mean the 4.3 reach limitation?

**Comment by flyinghead** [comment]
If the light gun is outside the 4:3 area it's considered off screen so no.

Light gun emulation with analog joystick is only supported for arcade games.

**Comment by Trihy** [comment]
In Naomi's hotd2 shoot outside screen to reload doesn't seem to work. Tried on 4.3 and 16.9. none worked. Do you think this could be a flycast bug? Tried on flycast Retroarch core only.

**Comment by flyinghead** [comment]
Have you done a gun calibration in the game test menu?

Also it might be easier to bind the reload button instead of reloading off screen.

**Comment by Trihy** [comment]
> Have you done a gun calibration in the game test menu?
> 
> Also it might be easier to bind the reload button instead of reloading off screen.

Hi. Yes, did that through service menu. But still doesn't work. Tried every axis to shoot outside screen and none do that.

Naomi's Death crimson ox is a good example of shoot outside screen working fine. I think it works in every axis. In case it could be useful for comparing code.

**Comment by Trihy** [comment]
Also tried Naomi's Lupin the third and ninja assault. Both work fine shooting outside screen.

Atomiswave Ranger mission is fine too.

Problem seems to be mainly hotd2, also hotd2 prototype is affected.
