### ISSUE TITLE
"Make Game Config" option does not work so intuitively

### ISSUE THREAD

**Issue by dezraj** [flyinghead/flycast#884]
**Is your feature request related to a problem? Please describe.**
If we load a game, call the settings and click on "make game config" without changing anything it won't save a game config file, but instead a generic one, as you see in the following video:

https://drive.google.com/file/d/1OZrNVgYtLU4SgKTeFrlddlPxaIeA6OQv/view?usp=share_link

If you want to save custom mappings for your controller, you need first to click on "make game config" inside the mappings screen and before you edit something. If you change something and only then you click on "make game config" the file won't be created and if you close the program afterwards you will lose the custom bindings for that game (they will actually become the default ones for all games).

**Describe the solution you'd like**
When we click on "make game config" it should immediately generate a per-game config file with all current settings and update it on the fly as soon as we change something. This will avoid the issue of having to visit a second menu if you want just to change the mappings, for instance. It will also prevent someone from editing all bindings and losing them if he/she decides to click on "make game config" only after all configuration is changed.

**Additional context**
I felt the need for this when trying to create custom mappings for Resident Evil Code Veronica and finding they weren't saved when I thought they were.

Thank you in advance for your time and work.

**Comment by crashGG** [comment]
I think this issue should be comment  in libretro, because this is the operation logic of retroarch, and has nothing to do with the specific core

**Comment by dezraj** [comment]
Thank you so much for your reply and clarification, @flyinghead .

Do you think it's a good idea to merge the two configuration files into one? I suppose a single per-game settings file could retain both the custom mappings and the custom configuration options for that very game. Perhaps this would let this function more user-friendly and avoid some of the issues which I went through in my experience, which I think is likely to happen with others as well.

Thank you again for your time and work.
