### ISSUE TITLE
Microsoft visual c++ runtime Library 

### ISSUE THREAD

**Issue by EPIC3477** [flyinghead/flycast#886]
Platform / OS / Hardware: 
Windows 7
Github hash: 

Hardware: 
Intel i5
**_Description of the Issue_**
it was working at the beginning but not anymore I don't know what happened just suddenly the error appeared and I can't play anymore

```


```

**_Screenshots_**

![received_456507283213645](https://user-images.githubusercontent.com/91116523/213652357-d850c151-134e-48db-9102-877b4a4a1dba.jpeg)

**Comment by flyinghead** [comment]
Delete the `data` and `mappings` folders and `emu.cfg` file and retry.

If the error persists enable `Settings > Advanced > Other > Log to File` and post the `flycast.log` file.

**Comment by EPIC3477** [comment]
[flycast.log](https://github.com/flyinghead/flycast/files/10464734/flycast.log)
here

**Comment by EPIC3477** [comment]
[flycast.log](https://github.com/flyinghead/flycast/files/10464822/flycast.log)
here

**Comment by flyinghead** [comment]
It could be an issue with your DirectX 9 GPU driver.
Edit the file emu.cfg with Notepad and change the following value:
```
[config]
pvr.rend = 1
```

Change it to 0 for OpenGL or 2 for DirectX 11. (You will need the latest DirectX 11 install/patch for it to work)

**Comment by EPIC3477** [comment]
It's works thanks 😄
