### ISSUE TITLE
Force Windows CE makes laggy intro and cutscenes in Sakura Taisen 3 and 4

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [flyinghead/flycast#888]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10 x64 22H2

Github hash: 
[cca7ed6](https://github.com/flyinghead/flycast/commit/cca7ed6)

Hardware: 
Intel i3-3210, GT 710, 8GB RAM

**_Description of the Issue_**

Apparently the intro and cutscenes of both Sakura Taisen 3 and 4 are lagging as well as the intro music. I am not sure about the cutscenes though.

**_Debugging Steps Tested_**

  *Loaded up the games and not skip the intro cutscenes.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
No lag whatsoever here. Just tested Sakura Taisen 3 tho.

What are your settings? Can you post your emu.cfg?

Also what's "laggy" exactly? Low framerate? Bad sound? Something else?

**Comment by AbandonedWitchStarlight** [comment]
Here is my Emu.cfg:
`[audio]
backend = auto
disable = 0

[config]
BoxartDisplayMode = yes
Debug.GDBEnabled = no
Debug.GDBPort = 3263
Debug.GDBWaitForConnection = no
Debug.SerialConsoleEnabled = no
Debug.SerialPTY = no
Dreamcast.AutoLoadState = no
Dreamcast.AutoSaveState = no
Dreamcast.AutoSavestate = no
Dreamcast.Broadcast = 4
Dreamcast.Cable = 3
Dreamcast.ContentPath = D:\Amaichain Inminations\Amaichain DC
Dreamcast.ForceWindowsCE = yes
Dreamcast.FullMMU = no
Dreamcast.HideLegacyNaomiRoms = yes
Dreamcast.Language = 6
Dreamcast.Region = 3
Dreamcast.SavestateSlot = 0
Dynarec.Enabled = yes
Dynarec.idleskip = yes
Dynarec.safe-mode = no
FastGDRomLoad = no
FetchBoxart = yes
ForceFreePlay = yes
LuaFileName = flycast.lua
Profiler.DrawGUI = no
Profiler.Enabled = no
Profiler.FrameWarningTime = 0.018182
Profiler.OutputTTY = no
UploadCrashLogs = yes
UseReios = no
aica.AutoLatency = no
aica.BufferSize = 2822
aica.DSPEnabled = no
aica.NoSound = no
aica.Volume = 100
pvr.AutoSkipFrame = 0
pvr.MaxThreads = 3
pvr.rend = 4
rend.AnisotropicFiltering = 1
rend.CrossHairColor1 = 0
rend.CrossHairColor2 = 0
rend.CrossHairColor3 = 0
rend.CrossHairColor4 = 0
rend.CustomTextures = no
rend.DelayFrameSwapping = no
rend.DumpTextures = no
rend.DupeFrames = no
rend.EmulateFramebuffer = no
rend.ExtraDepthScale = 1.000000
rend.FloatVMUs = no
rend.Fog = yes
rend.MaxFilteredTextureSize = 256
rend.ModifierVolumes = yes
rend.NativeDepthInterpolation = no
rend.PerPixelLayers = 32
rend.PerStripSorting = no
rend.PixelBufferSize = 536870912
rend.RenderToTextureBuffer = no
rend.Resolution = 480
rend.Rotate90 = no
rend.ScreenStretching = 100
rend.ShowFPS = no
rend.SuperWideScreen = no
rend.TextureFiltering = 0
rend.TextureUpscale = 1
rend.ThreadedRendering = yes
rend.TranslucentPolygonDepthMask = no
rend.UseMipmaps = yes
rend.WideScreen = no
rend.WidescreenGameHacks = no
rend.vsync = yes
ta.skip = 0

[input]
MouseSensitivity = 100
RawInput = no
VirtualGamepadVibration = 20
device1 = 0
device1.1 = 1
device1.2 = 3
device2 = 0
device2.1 = 1
device2.2 = 1
device3 = 0
device3.1 = 1
device3.2 = 1
device4 = 0
device4.1 = 1
device4.2 = 1
maple_sdl_joystick_0 = 0
maple_sdl_keyboard = 1
maple_sdl_mouse = 0
maple_sdl_mouse_\\?\HID#VID_18F8&PID_0F97&MI_00#8&3243a1cf&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 2
maple_sdl_mouse_\\?\Root#RDP_MOU#0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd} = 1

[network]
ActAsServer = no
DNS = 46.101.91.123
EmulateBBA = yes
Enable = no
EnableUPnP = yes
GGPO = no
GGPOAnalogAxes = 0
GGPOChat = yes
GGPOChatTimeout = 10
GGPOChatTimeoutToggle = yes
GGPODelay = 0
LocalPort = 37391
NetworkOutput = no
Stats = yes
server = 

[validate]
OpenGlChecks = no

[window]
fullscreen = no
height = 767
left = 238
maximized = no
top = 42
width = 969`


Apparently I think bad framerate and sound may be causing it, since the intro video works fine on the other emus though.

**Comment by flyinghead** [comment]
Disable `Force Windows CE`
This is what's causing the lag.

Never use this option on a non-Windows CE game.

Also I don't recommend setting Broadcast to Default. Set it to NTSC or PAL depending on the game region.

**Comment by crashGG** [comment]
> Disable `Force Windows CE` This is what's causing the lag.
> 
> Never use this option on a non-Windows CE game.
> 
> Also I don't recommend setting Broadcast to Default. Set it to NTSC or PAL depending on the game region.

I'm a bit confused that Broadcast to Default is a common setting for most people(lazy) and is the default for libretro ports. Will setting it to NTSC or PAL to fit the game region increase the performance of the game emulation?

**Comment by flyinghead** [comment]
The default for Broadcast is NTSC, in both standalone and libretro.

Using Default may lead to running an NTSC game in PAL and thus reducing frame rate to 50 FPS.
