### ISSUE TITLE
Great emulator, controller mapping is worst of all time

### ISSUE THREAD

**Issue by Jayinem** [flyinghead/flycast#89]
I don't understand why you would decide to dictate which buttons can and can't be mapped. It should be 100% up to the user to decide that. I click on Left stick and hit up on my stick and doesn't respond. But if I use d-pad it works. Why not just let people decide what buttons they want to use? Isn't this a fork of NullDC which was from the 2000-2010 decade and it let you map whatever buttons you wanted, so does every other emulator ever. I guess I'll have to try Retroach Flycast.

**Comment by flyinghead** [comment]
This is to report issues, not general comments
