### ISSUE TITLE
Widescreen not working correctly on Resident Evil 3 

### ISSUE THREAD

**Issue by Hisham735** [flyinghead/flycast#892]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 10

Github hash: 

Hardware: Kirin 980 /Mali-G76 MP10 

**_Description of the Issue_**

Widescreen not working on RE3 game as shown in the screenshot.. 

**_Screenshots_**

![Screenshot_20230122_224033_com.flycast.emulator.jpg](https://user-images.githubusercontent.com/98933982/213936574-04d8da53-c32d-4df0-abab-c88b9b99dec2.jpg)

![Screenshot_20230122_223650.jpg](https://user-images.githubusercontent.com/98933982/213936575-2191f9f3-23c1-4498-8412-ba0ac16fc850.jpg)

**Comment by flyinghead** [comment]
The widescreen mode simply displays hidden geometry outside of the normal 4:3 Dreamcast screen.

Some games display garbage in this area as is the case here, but there's nothing I can do about it.

Widescreen cheats gives a better experience but there isn't any for this game.

**Comment by normchomsky** [comment]
Because this game uses pre rendered graphics there is simply nothing to display beyond the 4:3 space. Pre rendered games do not have widescreen cheats as a result and can only be played in 4:3 or 16:9 stretched.

**Comment by Hisham735** [comment]
I thought it can be fixed since I tried the Widescreen for same game on different a emulator and it works great. (RD) 

Another thing about RE CV when Widescreen is enabled this happens :

![Screenshot_20230122_230659_com.flycast.emulator_edit_345482193728011.jpg](https://user-images.githubusercontent.com/98933982/213937839-b51bb072-6472-471f-84ee-dd9e62dbb300.jpg)

Apparently this issue was solved on PC but not for android.. Look here please :

https://github.com/flyinghead/flycast/issues/18

**Comment by flyinghead** [comment]
Widescreen cheats are multi-platform so they work the same on Android and PC.

**Comment by Hisham735** [comment]
Thank you
