### ISSUE TITLE
Graphical glitch in Rayman 2 and Resident Evil Code Veronica

### ISSUE THREAD

**Issue by dezraj** [flyinghead/flycast#897]
Platform / OS / Hardware: Windows 10 21H2

Github hash: [f7e227a](https://github.com/flyinghead/flycast/commit/f7e227a)

Hardware: i5-10400, GTX 1660 Ti, 16GB RAM

**_Description of the Issue_**

There is a graphical glitch in Rayman 2 main screen. When you hit Start and the screen scrolls up, some of the textures are not rendered correctly. Here's a short video showing the glitch:
https://drive.google.com/file/d/1Z6aGQeTNwbQ1-9lqqrWi8AHAgMsii3JN/view?usp=sharing

The same for Resident Evil Code Veronica, when there is this fog/gas effect in this room, here:
https://drive.google.com/file/d/13RYFKkRiu5RhX0cGumY6ZNlj4XW4ci-y/view?usp=sharing

I believe the problems are related, that's why I'm opening just one issue for both.

**_Screenshots_**

![image](https://user-images.githubusercontent.com/27839354/214751318-e691053a-5e24-4722-a117-c006effbb7b1.png)
![image](https://user-images.githubusercontent.com/27839354/214751713-f89f653a-f7cd-499c-a026-a454574ec759.png)

Save-state for the Resident Evil Code Veronica room:
[Resident Evil - Code Veronica X v1.000 (2000)(Capcom)(NTSC)(US)(Disc 1 of 2)[!].zip](https://github.com/flyinghead/flycast/files/10506146/Resident.Evil.-.Code.Veronica.X.v1.000.2000.Capcom.NTSC.US.Disc.1.of.2.zip)

You need to enter the room and take the sword from the stone statue to cause the effect, then move to the bottom of the room to see the glitch.

Thank you so much in advance for your attention.

**Comment by flyinghead** [comment]
Which graphics API are you using? And are you using per pixel?
Does changing these settings have any effect on these glitches?

The RECV screenshot looks a lot like the pixel buffer being full. Depending n your internal resolution you might need to increase it to 1GB or more.

**Comment by flyinghead** [comment]
I can reproduce the Rayman 2 issue when upscaling to 3840x2880 (x6) with a 512 MB pixel buffer.
The issue doesn't happen when using a 1 GB pixel buffer.

**Comment by dezraj** [comment]
Thank you for your quick response, @flyinghead .

I'm using Vulkan with per pixel transparent sorting at 6x internal resolution. Changing the pixel buffer size to 1GB fix the issue in both of the reported cases here.

Maybe this could be set automatically with switching to a 6+ multiplier for the internal resolution? Or you could explicitly state the internal resolution number in the pixel buffer tool-tip so it becomes clearer which "large up-scaling factor" is mostly affected. Generally most emulators don't need any further configuration after changing the up-scaling settings, that's why I never checked for other video settings after applying the 6x internal resolution.

Anyway, thank you so much again for your time and work.

**Comment by flyinghead** [comment]
Disclaimer: Upscaling was originally limited to x5. Then someone decided to add x6 and up. Given the texture quality on Dreamcast and Naomi, it doesn't make sense to upscale more than x4 or so. Doing so will only waste GPU memory and will make you run into problems.

There's no way to predict how many transparent pixels will be needed, and thus how large the buffer should be. Some scenes will need a large buffer because they use lots of large transparent geometry. Here, you were overflowing the pixel buffer on very simple scenes, which means similar issues may occur with a 1 GB buffer if the scene gets sufficiently complex.

**Comment by cinnamonmatexfce** [comment]
> Disclaimer: Upscaling was originally limited to x5. Then someone decided to add x6 and up. Given the texture quality on Dreamcast and Naomi, it doesn't make sense to upscale more than x4 or so. Doing so will only waste GPU memory and will make you run into problems.
> 

Good! Thank you for letting us know. 💪

**Comment by flyinghead** [comment]
Each transparent pixel needs 16 bytes. So a full-screen transparent quad at native resolution needs 4.7 MB.
When upscaling you need to multiply this number by your upscale factor __squared__, so around 169MB at x6.
Thus if you have more than 3 full-screen transparent quads, your 512 MB pixel buffer will overflow.

**Comment by dezraj** [comment]
> Disclaimer: Upscaling was originally limited to x5. Then someone decided to add x6 and up. Given the texture quality on Dreamcast and Naomi, it doesn't make sense to upscale more than x4 or so. Doing so will only waste GPU memory and will make you run into problems.
> 
This is an incredibly important disclaimer that is impossible to know if you don't have the technical knowledge for that. You should definitely warn users about that somehow, maybe including a comment in the up-scaling tool-tip, something like "Due to the Dreamcast/Naomi texture quality, using a value higher than 5x will produce no visual difference and only waste your GPU memory."

But I need to ask  something: if you knew there was no benefit in using 6+ internal resolution multipliers, why did you approve this change to the code?

Thank you so much again for your time.
