### ISSUE TITLE
Flycast on Wayland starting in a little window.

### ISSUE THREAD

**Issue by Terminykos** [flyinghead/flycast#898]
Platform / OS / Hardware:  Fedora 37
Github hash: 

Hardware: Ryzen 7 5700G, 48GB DDR4, RX6700XT

**_Description of the Issue_**

I installed Flycast from the flatpak hub, from first boot it always started in a lttle box (see screenshot) and there is now way to go fullscreen. If I press the combination Alt+Enter I get a black fullscreen with a litte windows in the middle (see screenshot)

**_Screenshots_**

![Schermata del 2023-01-27 16-40-45](https://user-images.githubusercontent.com/123756166/215131703-021a7156-5463-4bc8-bfb3-4d17b0196e58.png)
![Schermata del 2023-01-27 16-41-43](https://user-images.githubusercontent.com/123756166/215131782-9b72e0bc-cc87-4a27-a896-86633c27d80a.png)
![Schermata del 2023-01-27 16-42-50](https://user-images.githubusercontent.com/123756166/215131846-acdfce62-0c40-41d7-bfda-9ed7180f2956.png)

**Comment by flyinghead** [comment]
Don't use Wayland. Use X11 instead.

**Comment by Terminykos** [comment]
Great, this solved the problem but now Flycast crashes at "second boot". 
I mean, the first time I launch Flycast after a fresh boot it works flawlessy. If I close the application and try to start Flycast cashes immediately after clicking on the icon. If reboot my computer, again it works the first time only.
[Video del 2023-01-27 17-42-21.webm](https://user-images.githubusercontent.com/123756166/215144002-f1daf4e4-d215-4e5a-86a7-8764c0c2e0dc.webm)

**Comment by flyinghead** [comment]
Can you run Flycast in a terminal to get some logs?

**Comment by Terminykos** [comment]
Sure, here it is.
![Schermata del 2023-01-27 18-04-23](https://user-images.githubusercontent.com/123756166/215149185-aaca2b74-bedd-456c-939a-5bb435da65e3.png)

**Comment by flyinghead** [comment]
No error here so it looks like Flycast is exiting cleanly. Did you bind the Exit button?

**Comment by Terminykos** [comment]
Yes, and that gave me the answer...Exit was binded on my controller, disconnecting the controller it works again! Thank you man

**Comment by flyinghead** [comment]
wayland support should work fine now.
