### ISSUE TITLE
Problem compiling for GLES for Amlogic devices / missing textures

### ISSUE THREAD

**Issue by shantigilbert** [flyinghead/flycast#91]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: EmuELEC on Amlogic s905(x),  Odroid N2, VIM3, etc

Github hash: 34575d577cb1284ef4b56be87ba660a0c53159f8

Hardware: Amlogic using MALI G52, G31, 450

**_Description of the Issue_**
Trying to cross-compile for my device, I tried using armv7h-neon, odroidc1(or ordroidc2 adding my own platform) as my platform and I get this error: 

```/mnt/build.EmuELEC-Amlogic-ng.arm-3.5/flycastsa-34575d577cb1284ef4b56be87ba660a0c53159f8/shell/linux/../../core/wsi/egl.cpp: In member function 'bool EGLGraphicsContext::Init()':
/mnt/build.EmuELEC-Amlogic-ng.arm-3.5/flycastsa-34575d577cb1284ef4b56be87ba660a0c53159f8/shell/linux/../../core/wsi/egl.cpp:153:4: error: 'load_gles_symbols' was not declared in this scope
    load_gles_symbols();
    ^~~~~~~~~~~~~~~~~
/mnt/build.EmuELEC-Amlogic-ng.arm-3.5/flycastsa-34575d577cb1284ef4b56be87ba660a0c53159f8/shell/linux/../../core/wsi/egl.cpp:165:3: error: 'load_gles_symbols' was not declared in this scope
   load_gles_symbols();
   ^~~~~~~~~~~~~~~~~
```
when I use platform odroidxu3 it compiles and it runs but its missing a bunch of textures. 
I assume there is something missing when not using the -DGLES3 that xu3 is using because if I remove it then the compilation error appears. 

EDIT: there is a typo (I think?) on sdl.h line 29 says `#ifndef GLES2` change it to `#ifndef GLES3` and now it compiles with `platform=odroidc1 USE_SDL=1` but the program does not run

```
:00:642 linux/common.cpp:103 E[COMMON]: SIGSEGV @ 0 -> (nil) was not in vram, dynacode:0
00:00:643 rend/gui.cpp:1867 E[COMMON]: Fatal error : segfault
 in fault_handler -> /mnt/build.EmuELEC-Amlogic-ng.arm-3.5/flycastsa-34575d577cb1284ef4b56be87ba660a0c53159f8/shell/linux/../../core/linux/common.cpp : 104
```
However if I instead just add `#include "gl32funcs.h"` to sdl.cpp directly the program runs but the missing textures are the same as if I use platform=odroidxu3, should I open a new issue?

 Here is a small video that shows the missing textures (sorry for the quality) https://youtu.be/RtTXnCTqWl4

**Comment by flyinghead** [comment]
This should help with the build error: https://github.com/flyinghead/flycast/commit/b907aa2d981a6fe558ba4a83d02585fe048899a8
The #ifndef in sdl.h is correct. When GLES2 is defined, there's no dynamic loading of GL/GLES functions, which is done in gl32funcs.h/c.

Not sure why most textures are missing however.

**Comment by shantigilbert** [comment]
Thanks, that fixed the compilation! :) 

Unfortunately textures are still missing, is there anything else I can do to help figure that one out?

**Comment by flyinghead** [comment]
Looking at the video it seems the actual geometry is missing, not only the texture. But then, I have no idea what causes this.

Have you tried playing with the video settings to see if they change anything? Any hint would be helpful.

**Comment by shantigilbert** [comment]
Sure I can test that, any suggestions on what to change? also, is there a menu I can do these changes from, or do I have to edit the emu.cfg directly ?

**Comment by flyinghead** [comment]
pressing tab or select should open the menu then choose Settings. Try disabling shadows, fog, clipping. Also rendering at 0.5 downscale.

**Comment by shantigilbert** [comment]
sorry for the delay

it seems I am out f luck, nothing I do seems to even do any difference, I disabled shadows, fog and clipping, still the same missing textures/geometry.

Anything other than rendering at 1 (native) does not load the game.

Maybe this is something on the Mali-G31/Mali G52 drivers?

**Comment by shantigilbert** [comment]
I actually just tried it on an older device with Mali 450, and it displays correctly, so it has to be something with the newer drivers.

**Comment by flyinghead** [comment]
Fwiw I have a test device with a Mali-G51 running Android and no issue with GLES.

But I had issues with Vulkan which were fixed by upgrading the drivers.

**Comment by shantigilbert** [comment]
I am starting to think this might be the same issue that is causing PPSSPP to not display some geometry, just like this, on the exact same GPUs, it seems that maybe the 32bit version of the mali drivers for this GPUS are broken.

Anyways I guess this is not Flycast at fault, so do you want me to close this issue?

**Comment by flyinghead** [comment]
No problem. This issue can stay open until there is a fix for it

**Comment by shantigilbert** [comment]
I am trying to do some more testing now on aarch64 see if the problem is the same but for some reason I cannot compile it for aarch64, what are the correct parameters to do this? 

this is what I am using `USE_SDL=1 USE_GLES=1 platform=arm64` 

but I always get 
```
In file included from /mnt/SSD/flycastsa-125c1ff37d005809a18086cf60f5418e23caa9d4/shell/linux/../../core/khronos/EGL/egl.h:36,
                 from /mnt/SSD/flycastsa-125c1ff37d005809a18086cf60f5418e23caa9d4/shell/linux/../../core/wsi/gl32funcs.c:21:
/mnt/SSD/flycastsa-125c1ff37d005809a18086cf60f5418e23caa9d4/shell/linux/../../core/khronos/EGL/eglplatform.h:99:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
```

followed by a few other errors:  

````
/shell/linux/../../core/hw/sh4/dyna/../sh4_if.h:355:29: error: can't convert value to a vector
 #define Sh4cntx (sh4rcb.cntx)
```

I am cross compiling and I do not have x11 but I can seem to compile fine for ARM but not for ARM64, am I missing something?

**Comment by flyinghead** [comment]
Sorry for the delay. Did you get this sorted out?

It looks like the included `core/khronos/eglplatform.h`only supports X11 on linux. Can you tweak the include path to use the system egl.h instead?

**Comment by shantigilbert** [comment]
No problem, and thanks! it seems including eglplatform.h from my toolchain worked with the x11 file as I no longer get the error.

But the others are still present

```
/shell/linux/../../core/hw/sh4/dyna/../sh4_if.h:355:29: error: can't convert value to a vector
 #define Sh4cntx (sh4rcb.cntx)
```

```
/mnt/build.EmuELEC-Amlogic-ng.aarch64-3.8/toolchain/lib/gcc/aarch64-libreelec-linux-gnueabi/8.3.0/include/arm_neon.h:24882:40: error: expected primary-expression before 'tab'
 vqtbx4q_p8 (poly8x16_t r, poly8x16x4_t tab, uint8x16_t idx)
                                        ^~~
/mnt/build.EmuELEC-Amlogic-ng.aarch64-3.8/toolchain/lib/gcc/aarch64-libreelec-linux-gnueabi/8.3.0/include/arm_neon.h:24882:56: error: expected primary-expression before 'idx'
 vqtbx4q_p8 (poly8x16_t r, poly8x16x4_t tab, uint8x16_t idx)
                                                        ^~~
/mnt/build.EmuELEC-Amlogic-ng.aarch64-3.8/toolchain/lib/gcc/aarch64-libreelec-linux-gnueabi/8.3.0/include/arm_neon.h:24882:59: error: expression list treated as compound expression in initializer [-fpermissive]
 vqtbx4q_p8 (poly8x16_t r, poly8x16x4_t tab, uint8x16_t idx)
```

Shouldn't neon be disabled for aarch64?

**Comment by shantigilbert** [comment]
Also since I forgot to mention it, I am using the Makefile in shell/linux directly since I cannot find a way to use GLES with cmake...

**Comment by flyinghead** [comment]
neon shouldn't be needed for aarch64. 

And use shell/linux/Makefile for now as cmake support is still being worked on.

**Comment by shantigilbert** [comment]
> neon shouldn't be needed for aarch64.
> 
> And use shell/linux/Makefile for now as cmake support is still being worked on.

Problem is, I can't seem to find where or why neon is being enabled? 

These are my changes

```
# Generic 64 bit ARM (armv8) Linux
else ifneq (,$(findstring arm64,$(platform)))
    NOT_ARM := 1
ifndef USE_SDL
    USE_X11 := 1
endif
    USE_SDL := 1
    USE_GLES := 1
    ARM64_REC := 1
    ISARM64 := 1
    CFLAGS += -DGLES3
    CFLAGS += -D TARGET_LINUX_ARMv8 -fno-builtin-sqrtf
    CXXFLAGS += -fexceptions
    INCS += -I$SYSROOT_PREFIX/usr/include/
    LIBS += -L$SYSROOT_PREFIX/usr/lib -lEGL -lGLESv3
```

**Comment by flyinghead** [comment]
xxhash uses:
```
#  elif defined(__ARM_NEON__) || defined(__ARM_NEON)
#    define inline __inline__  /* clang bug */
#    include <arm_neon.h>
```

**Comment by shantigilbert** [comment]
adding

```
#undef __ARM_NEON__
#undef __ARM_NEON
```
at the top of the `xxh3.h` did the trick :) 

Unfortunately even on aarch64 its the same issue with geometry :( on an Odroid N2+ 

Anyways, thanks for the help!

**Comment by flyinghead** [comment]
When pausing, Crazy Taxi does a rendering of the scene to a texture, then uses this texture as background and draw the pause menu on top of it.
It looks like an issue related to texture not being updated or being messed up.

You might want to change the DEBUG_LOG in BaseTextureCacheData::PrintTextureName() to NOTICE_LOG to check if and when textures are updated, and you can compare with a run on a desktop. But I don't know why this wouldn't work on odroid n2+.

**Comment by shantigilbert** [comment]
Thanks, I will try that changem unfortunately I don't have a desktop version to compare to, but I'll see what I can do. 

Thanks again!

**Comment by flyinghead** [comment]
Thanks for these details. Unfortunately there's quite a few changes between those two points.

Something to try: disable mipmaps by adding this to emu.cfg.
```
[config]
rend.UseMipmaps = no
```

Another big change during that time is the Vulkan renderer, which necessitated some changes in GL as well. But it's much harder to find out which of these changes could be the culprit.

**Comment by shantigilbert** [comment]
Thanks, I've tried all the settings changes so I am sure it's not related
to that, unfortunately.

Oh well I guess the libretro core is the only option for us stuck with
fbdev.

**Comment by shantigilbert** [comment]
thanks for the help @flyinghead I will close this issue now :)
