### ISSUE TITLE
[iOS] Virtual gamepad X button mapping is invalid

### ISSUE THREAD

**Issue by kireily** [flyinghead/flycast#911]
When I press The X button in Virtual Gamepad ,Its reaction the "Down" button,I tryed in TEST MODE to change it but failed....

could some one kindly tell me how to fix it ?  very very thanks!

**Comment by flyinghead** [comment]
It's a bug but not related to this game in particular. A fix is coming.

**Comment by kireily** [comment]
> It's a bug but not related to this game in particular. A fix is coming.

thank you for replying me! and ,Its that possible for Ios mapping Virtual gamepad custom in future not so long ? I really enjoy Flycast in ios, hoping Virtual gamepad will be more convenience :)

**Comment by flyinghead** [comment]
This should be fixed in the latest master build.

**Comment by kireily** [comment]
> This should be fixed in the latest master build.

Than you again~ and ,could I download app sooner or later?
