### ISSUE TITLE
Shenmue Graphical Error

### ISSUE THREAD

**Issue by XxHollicxX** [flyinghead/flycast#912]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: android

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Screenshot_2023-02-09-08-11-10-038_com.flycast.emulator.jpg](https://user-images.githubusercontent.com/124847143/217690709-2ca2e546-4a19-4e09-b834-d59a67be76fa.jpg)

![Screenshot_2023-02-09-08-07-32-533_com.flycast.emulator.jpg](https://user-images.githubusercontent.com/124847143/217690708-c1b80d13-87c8-427a-8865-ecfc67088e2b.jpg)

![Screenshot_2023-02-09-08-16-06-081_com.flycast.emulator.jpg](https://user-images.githubusercontent.com/124847143/217690707-be572db1-b334-4483-9dfd-2c69a16e189b.jpg)

![Screenshot_2023-02-09-08-08-33-276_com.flycast.emulator.jpg](https://user-images.githubusercontent.com/124847143/217690706-409690c3-c30c-4c86-80f2-9db5f1532c72.jpg)

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
Use per pixel transparent sorting

**Comment by vkedwardli** [comment]
You need to switch your Graphics API to Vulkan first (scroll down a little bit)
