### ISSUE TITLE
update Android SDK API

### ISSUE THREAD

**Issue by soundsnow** [flyinghead/flycast#914]
I guess it's Android 10 currently
For Android 11, 12, 12.1(12L), 13, 14

**Comment by flyinghead** [comment]
Flycast supports all Android versions from 4.1 and up, including the versions you mention.
What’s the issue?

**Comment by Raypuia** [comment]
> Flycast supports all Android versions from 4.1 and up, including the versions you mention. What’s the issue?

Google is enforcing another bump to the minimum SDK API, because of Android 14 restrictions with apps with backwards compatibility

**Comment by vkedwardli** [comment]
```
minSdk 16
targetSdk 29
compileSdk 29
```

@Raypuia  Google is bumping the minimum target SDK version (`targetSdk`) only, but not the minimum SDK version of the Android operating system required to run (`minSdk`).

So the current `targetSdk`is 29 is still safe for Android 14, where the new minimum requirement is API level 23

p.s. To sideload apk with lower `targetSdk` version, use `adb install --bypass-low-target-sdk-block FILENAME.apk`
