### ISSUE TITLE
Worms Pinball (Prototype) - Black screen

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#916]
Hello,

The game launches, but the tables are not displayed (black screen). Tested with the latest nightly.

https://en.sega-dreamcast-info-games-preservation.com/unreleased-worms-pinball-dreamcast-prototype-iso-gdi

**Comment by flyinghead** [comment]
Enable `Full Framebuffer Emulation`
![image](https://user-images.githubusercontent.com/16261910/218267221-caf0d39d-564b-4fe6-98a1-9e61a58afb80.png)

**Comment by dukeblooders** [comment]
Yes, works perfectly with that option. Thanks for your very fast reply!

**Comment by flyinghead** [comment]
I'll enable this option by default for this game. Thanks for reporting the issue.
