### ISSUE TITLE
Libretro: framerate issues when VRR is enabled on Vulkan

### ISSUE THREAD

**Issue by aitorciki** [flyinghead/flycast#917]
Platform / OS / Hardware: Windows 10 64bit + RetroArch 1.14.0 (Vulkan)

Github hash: a23362c

Hardware: Ryzen 7 3700X + Nvidia RTX 2070 Super

**_Description of the Issue_**

I'm using a G-Sync capable display (LG Oled G2) at 60hz. When using the Vulkan video driver and enabling VRR in RetroArch (`vrr_runloop_enable` set to `true`), Flycast seems to run games (at least 30fps ones) at a reduced framerate. Disabling VRR for Flycast results in correct framerate. No other settings are modified.

Other video drivers don't show that behaviour (tested with d3d9 and d3d12, both causing other problems).

RetroArch overlay stats don't display any change in framerate for the running core, in both cases the core is reporting 30fps.

Find attached a link to a [video comparison](https://www.youtube.com/watch?v=f1MzFhRmAig): left side is recorded with VRR enabled, right side with VRR disabled, exact same config / versions for the rest.

Enabling `detect frame rate changes` in the core config somehow mitigates the problem, but not completely (e.g. the Dreamcast boot animation framerate is still halfed, but ingame feels closer to target).

**_Debugging Steps Tested_**

  * Just toggling the `vrr_runloop_enable` setting to `true` in `Flycast.cfg` results in framerate issues. Setting it to `false` restores correct framerate.

**_Screenshots_**

[https://www.youtube.com/watch?v=f1MzFhRmAig](https://www.youtube.com/watch?v=f1MzFhRmAig)

Video stats with VRR enabled:
![jgr-stats-vrr](https://user-images.githubusercontent.com/428243/218267060-2efa4b51-be77-4871-86a6-80ed658b66a9.png)

Video stats with VRR disabled:
![jgr-stats-novrr](https://user-images.githubusercontent.com/428243/218267076-ba895eb8-0a95-4397-997e-22e325d00d3a.png)

**Comment by flyinghead** [comment]
I don't know what RA vrr option does exactly but it may choose to present a frame as soon as it's been rendered by the core.
The flycast core relies on video vsync and audio output to synchronize, so enabling vrr is removing one source of synchronization, affecting the frame rate.
I guess it's best not to use this option.

**Comment by aitorciki** [comment]
Since frame rate isn't affected by that setting using a video driver other than Vulkan, I thought it might be an issue with that backend implementation (not a general synchronization problem).

**Comment by flyinghead** [comment]
All renderers are different and may react differently to various options and settings but that doesn't mean they're at fault.
