### ISSUE TITLE
Widescreen rendering issue on Flycast Android on Mali-g52

### ISSUE THREAD

**Issue by Bizz912** [flyinghead/flycast#918]
![Screenshot_20230214_231644_Flycast.jpg](https://user-images.githubusercontent.com/123992372/218823497-6010f7d8-e768-4c1f-a515-91867bdf9596.jpg)

Platform / OS / Hardware: 

Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
what are your setttings (widescreen, super widescreen, widescreen game cheat, horizontal stretching, ...) ?

**Comment by Bizz912** [comment]
![Screenshot_20230215_000501_Flycast.jpg](https://user-images.githubusercontent.com/123992372/218833096-953f89d2-6142-4a17-a7d5-6e122db6a639.jpg)

![Screenshot_20230215_000447_Flycast.jpg](https://user-images.githubusercontent.com/123992372/218833093-56bd4e59-6746-4f8b-ae50-a7cbe9f25321.jpg)

![Screenshot_20230215_000453_Flycast.jpg](https://user-images.githubusercontent.com/123992372/218833094-3a1dfb34-8e2b-4554-aefd-1b38ff69c301.jpg)

**Comment by flyinghead** [comment]
The rendering issues are due to Widescreen/Super Widescreen: these options just display geometry that's normally hidden, and it can be glitchy or non-existent.

Normally, Widescreen Game Cheats don't have such an issue. So disable Widescreen and Super Widescreen for this game.
