### ISSUE TITLE
[NAOMI] vtennis / vtennisg crash

### ISSUE THREAD

**Issue by rtissera** [flyinghead/flycast#92]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
x86_64 / Ubuntu 20.04 LTS / VMWare

Github hash: 9df8e83ef0181edc15559d690a3738cb7c4b6953

Hardware: VMWare x86_84

**_Description of the Issue_**

Both vtennis and vtennisg crash at intro

Add a short, concise description of the issue here

Crash into YUV decoder...

**_Debugging Steps Tested_**

- Build vanilla git (clone, cmake, make)
- Run vtennis or vtennisg
- Observe crash at intro

**_Logs Gathered_**

romain@ubuntu:~/flycast/build$ ./flycast 
00:00:295 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:00:316 hw/mem/_vmem.cpp:513 N[VMEM]: Info: nvmem is enabled, with addr space of size 4GB
00:03:117 hw/naomi/naomi_cart.cpp:378 N[NAOMI]: NAOMI GAME ID [ POWER SMASH --------------]
00:03:117 nullDC.cpp:309 N[BOOT]: Game ID is [ POWER SMASH --------------]
00:32:117 rend/gui.cpp:1867 E[COMMON]: Fatal error : YUV_data : YUV decoder not inited , *WATCH*

 in YUV_data -> /home/romain/flycast/core/hw/pvr/pvr_mem.cpp : 135

**_Screenshots_**

[NONE]

**Comment by rtissera** [comment]
Also observed on lr-flycast with RetroArch on real hardware.

**Comment by flyinghead** [comment]
similar to https://github.com/libretro/flycast/issues/416

**Comment by flyinghead** [comment]
The vtennis crash should be fixed in the next build

**Comment by rtissera** [comment]
Great work

**Comment by flyinghead** [comment]
fixed
