### ISSUE TITLE
Android: Fix 14+ Vertical Orientation Naomi/Atomiswave game Virtual Buttons

### ISSUE THREAD

**Issue by soundsnow** [flyinghead/flycast#920]
Reicast is the truth, that's why we need that option for arcade games and some Dreamcast games
Please don't ignore this suggestion @flyinghead 
It costs my a lot of time to test and design
First image is made by me
As far as I know, Ikaruga Dreamcast Version supports Vertical 
How to Enable it for Dreamcast Vertical games?
Open Ikaruga - Config - Monitor Type - Vertical 1 or Vertical 2
Then Emulator Settings - Video - Rotate Screen 90°
This game is made for rotating monitor obviously

Vertical Orientation

Atomiswave
Animal Basket
Block Pong-Pong
WaiWai Drive

Naomi
Ikaruga
Illvelo
Karous
Psyvariar 2 - The Will To Fabricate
Shikigami no Shiro II / The Castle of Shikigami II
Shooting Love 2007
Star Horse
Star Horse 2001
Trigger Heart Exelica
Trizeal
Under Defeat

![image58](https://user-images.githubusercontent.com/109885044/219099264-7d4044e4-507e-480c-a1c4-f8ce186cb737.png)

![Screenshot_20230216-000701_Trebuchet](https://user-images.githubusercontent.com/109885044/219099609-32655090-1bce-431a-8dc5-b9a2be3e95ce.png)
![Screenshot_20230216-001223_Trebuchet](https://user-images.githubusercontent.com/109885044/219099666-ea6619ed-e1a3-4895-8434-f71614f7e00e.png)
![Screenshot_20230215-235617_Trebuchet](https://user-images.githubusercontent.com/109885044/219099772-b945fc9c-61b9-40a4-8baa-ab0ffe80cc88.png)
![Screenshot_20230216-000026_Trebuchet](https://user-images.githubusercontent.com/109885044/219100237-ce480d0e-8480-4fea-b109-3d78ed2e8919.png)
![Screenshot_20230216-000358_Trebuchet](https://user-images.githubusercontent.com/109885044/219100255-d09559c0-ce16-4cda-8ac9-2b75fd45d684.png)

**Comment by flyinghead** [comment]
Flycast isn’t reicast. Use reicast if you prefer its UI.
