### ISSUE TITLE
Add Swap Disc and Keep Insert/Eject Disk

### ISSUE THREAD

**Issue by soundsnow** [flyinghead/flycast#923]
Reicast: Back - Swap Disc
Flycast: Back - Eject Disk - Back - Insert Disk
It costs me more time
@flyinghead 
![image59](https://user-images.githubusercontent.com/109885044/219107308-fb5f782b-4359-4164-a0b6-2900b25b1075.png)

**Comment by flyinghead** [comment]
This is to let the game know that the disk has been ejected, which is necessary for many games. This is also rarely used so I don't see the need to simulate it with a single button.

PS: You seem to really prefer reicast over flycast, which is fine. But why don't you use reicast then?
