### ISSUE TITLE
Android: Bad Landscape Button Position

### ISSUE THREAD

**Issue by soundsnow** [flyinghead/flycast#924]
Analog Stick Especially
@flyinghead  That position is so close to Camera
Be away from Status Bar Camera Notch and Navigation Bar Rounded Rectangle
![image60](https://user-images.githubusercontent.com/109885044/219116442-b623b6dc-c341-4b42-b9e5-9a7d5fa4d72d.png)

**Comment by flyinghead** [comment]
There are many Android devices available all with different screen layouts so it's difficult to have a perfect layout for all of them.

But you customize the layout to fit your device and preferences: `Settings > Controls > Virtual Gamepad > Edit`.

**Comment by soundsnow** [comment]
> There are many Android devices available all with different screen layouts so it's difficult to have a perfect layout for all of them.
> 
> But you customize the layout to fit your device and preferences: `Settings > Controls > Virtual Gamepad > Edit`.

Thank
Sorry I don't know that
