### ISSUE TITLE
Odroid n2+ rend/gui.cpp:2891 E[COMMON]: Fatal error : Cannot initialize the graphics API starting commit 9d08da1fc9e8867089d089db2a072110d9ce89ef

### ISSUE THREAD

**Issue by Kelvfimer** [flyinghead/flycast#928]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: 9d08da1fc9e8867089d089db2a072110d9ce89ef

Hardware: 

Odroid n2+ Emuelec 4.6 on SD card

From commit 9d08da1fc9e8867089d089db2a072110d9ce89ef onwards Flycast StandAlone doesn't start and crashes with error message. 

00:00:542 sdl/sdl.cpp:561 E[COMMON]: Window creation failed: eglQueryDevicesEXT is missing (EXT_device_enumeration not supported by the drivers?)
00:00:542 rend/gui.cpp:2891 E[COMMON]: Fatal error : Cannot initialize the graphics API
 in initRenderApi -> /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycastsa-9d08da1fc9e8867089d089db2a072110d9ce89ef/core/wsi/switcher.cpp : 90

Libretro one works fine

**_Debugging Steps Tested_**
No debugging steps

**_Logs Gathered_**

```
[emuelec.log](https://github.com/flyinghead/flycast/files/10769210/emuelec.log)

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```
PLATFORM: naomi
ROM NAME: /storage/roms/naomi/vtennis2.zip
BASE ROM NAME: vtennis2.zip
USING CONFIG: /storage/.config/retroarch/retroarch.cfg
1st Argument: /storage/roms/naomi/vtennis2.zip
2nd Argument: -Pnaomi
3rd Argument: --core=flycastsa
4th Argument: --emulator=flycastsa
Full arguments: /storage/roms/naomi/vtennis2.zip -Pnaomi --core=flycastsa --emulator=flycastsa --controllers=-p1index 0 -p1guid 030086655e040000a10200000a060000 
Run Command is:
/usr/bin/bash flycast.sh /storage/roms/naomi/vtennis2.zip
Emulator Output is:
GC_CONFIG=
NO GAME CONTROLLERS WERE DETECTED.
00:00:542 sdl/sdl.cpp:561 E[COMMON]: Window creation failed: eglQueryDevicesEXT is missing (EXT_device_enumeration not supported by the drivers?)
00:00:542 rend/gui.cpp:2891 E[COMMON]: Fatal error : Cannot initialize the graphics API
 in initRenderApi -> /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/flycastsa-9d08da1fc9e8867089d089db2a072110d9ce89ef/core/wsi/switcher.cpp : 90
/emuelec/bin/flycast.sh: line 23: 19143 Trace/breakpoint trap   flycast "${1}"
exit 133
flycastsa flycastsa /storage/roms/naomi/vtennis2.zip
Naomi UNTESTED e63d892cdb8b532351dc7020bb60b6f4 bios/dc/naomi.zip missing BIOS - Could not find all BIOS: 
please make sure you copied the files into the corresponding folder 
> Naomi
UNTESTED e63d892cdb8b532351dc7020bb60b6f4 bios/dc/naomi.zip
exit bios 1

**Comment by flyinghead** [comment]
This is likely due to the previous commit: 4408aa7dbe37cce1cf2cdacba37e2d3e26d06b19
It now builds SDL on linux to add libdecor support for Wayland.
I suppose the resulting SDL build on odroid isn't correct for some reason.

If not using wayland then you can just use the system SDL build for odroid.
i'll add a cmake option to build SDL or use the system version but in the meantime you can patch CMakeLists.txt:
```
		if(NOT APPLE AND (NOT UNIX OR CMAKE_SYSTEM_NAME MATCHES "(FreeBSD|OpenBSD|NetBSD)"))
 			find_package(SDL2)
 		endif()
```
by removing the (NOT UNIX ...)

**Comment by flyinghead** [comment]
I added a cmake option `USE_HOST_SDL` to force the use of the host/platform SDL library.

**Comment by Kelvfimer** [comment]
@flyinghead I added USE_HOST_SDL option on => PKG_CMAKE_OPTS_TARGET+="-DUSE_GLES=ON -DUSE_VULKAN=OFF -USE_HOST_SDL=ON" and tested with ON and OFF and the issue still persists Pls can you help me?

**Comment by flyinghead** [comment]
Use `-DUSE_HOST_SDL=ON` instead of `-USE_HOST_SDL=ON`
