### ISSUE TITLE
NBA on NBC - Commentator audio clipped or wrong

### ISSUE THREAD

**Issue by shoesio** [flyinghead/flycast#93]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Retroarch 

Github hash: 

Hardware: Odroid Go Advance (also occurs in Nintendo Switch)

**_Description of the Issue_**

In game commentary audio (cd audio?) is either clipped incorrectly, or wrong sample is played. 

**_Debugging Steps Tested_**

  * Attempted with different rom files, audio was not present at all. I assume audio tracks had not been ripped.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
I can't reproduce this issue. Can you provide more details: settings used, media type, game region, etc.?
Also a recording of the problem would help.

**Comment by shoesio** [comment]
[https://youtu.be/7wkAqUYe3hs](url)

**Comment by shoesio** [comment]
Compare with this correct sounding video: https://youtu.be/kl-k3UIHrag?t=177

**Comment by flyinghead** [comment]
Yes, this is very obviously wrong but I don't have this problem on all platforms I tested (linux, macOS, android)

Are you sure your media is ok? Are you using a GDI/CUE/CHD or a CDI? BTW the commentator voice isn't a CD audio track but regular audio samples.

**Comment by shoesio** [comment]
File type is CHD, Region is USA. DSP is off. Emulator type is Flycast core running in Retroarch.

**Comment by shoesio** [comment]
I have tried with a few different rom sets, most had no audio at all.

**Comment by flyinghead** [comment]
I've been able to reproduce the problem with this GDI dump: http://redump.org/disc/18035/

But it doesn't happen with the TOSEC dump for this game.

**Comment by flyinghead** [comment]
Note that redump has switched to using .CUE files instead of .GDI. And the redump .CUE file for this game works fine.
As previously mentioned, the TOSEC .GDI dump also works fine.
