### ISSUE TITLE
Skies of Arcadia crashes early in game

### ISSUE THREAD

**Issue by meunierd** [flyinghead/flycast#94]
Platform / OS / Hardware: Nintendo Switch

Github hash: dbf9686

Hardware: N/A

After the first battle, once you've regained control of your character, after Alfonso says "Dispose of them" the game reliably crashes. This is about 5 minutes in. I am using the redump image of Skies of Arcadia.

**Comment by flyinghead** [comment]
What OS are you running?

**Comment by meunierd** [comment]
HOS. Sorry I forgot about Lakka

**Comment by flyinghead** [comment]
There is no release of flycast standalone for Switch. Are you using retroarch?

**Comment by meunierd** [comment]
Yes.

**Comment by flyinghead** [comment]
For future issues, use the retroarch flycast repo: https://github.com/libretro/flycast/issues

I did a quick test on android/aarch64 and no crash so I assume it's a Switch-specific problem.

**Comment by meunierd** [comment]
Really sorry about that, this came up first when I googled `flycast github` and I didn't think to look a couple results down.

**Comment by meunierd** [comment]
I just wanted to chime in that the latest master in retroarch gets past this!
