### ISSUE TITLE
Is there a future project for flycast standalone for jb ps4

### ISSUE THREAD

**Issue by krimnassim** [flyinghead/flycast#942]
hi, is there a chance we get standalone flycast on jb ps4,there is flycast core on unofficial retroarch but its outdated and no longer get the core updates from the online updater if we get flycast standalone on ps4 that will be amazing and thanks.

**Comment by flyinghead** [comment]
It might happen if a PS4 owner decides to port Flycast to it but I don't have a PS4 to do this port.

**Comment by krimnassim** [comment]
> It might happen if a PS4 owner decides to port Flycast to it but I don't have a PS4 to do this port.

if you get a ps4 in the future please port flycast and thank you for your work.

**Comment by krimnassim** [comment]
if you get a ps4 in the future please port flycast and thank you for your work.

**Comment by krimnassim** [comment]
if you get a ps4 in the future please port flycast and thank you for your work.

**Comment by krimnassim** [comment]
if you get a ps4 in the future please port flycast i will be grateful to you.
