### ISSUE TITLE
Dualshock 4 L2/R2 Triggers not very responsive with Naomi/Arcade emulation

### ISSUE THREAD

**Issue by gktonic** [flyinghead/flycast#943]
Is it possible to make arcade triggers more responsive? For example in the Dreamcast version of Capcom vs. SNK 2 hard kicks start immediately (since the game knows it's a trigger),.. but in the Arcade/Naomi version i have to press the trigger (Dualshock 4) almost half way through (wich makes canceling hard kick into hard kick very very hard)

Maybe something like a "Make gamepad triggers act like buttons" option?!

PS - I'm sorry for my english. It's only my second language. ^^"

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/flyinghead/flycast/commit/b564b0bf9142492cde6ca9f2f87363a279b75ecc
