### ISSUE TITLE
screen won't centralize and has uneven borders

### ISSUE THREAD

**Issue by benjis8888** [flyinghead/flycast#944]
San Francisco rush 2049 is one and there is quite a few it happens on, and has a big empty space at the bottom and the inbuilt screen repositioning won't work either

![San Francisco Rush 2049-ECHELON-230223-111632](https://user-images.githubusercontent.com/126162906/220895207-53a40629-6b48-4de9-bda0-2a3fe2925ffb.png)
![San Francisco Rush 2049-ECHELON-230223-111646](https://user-images.githubusercontent.com/126162906/220895212-40db08a9-6344-49b6-b9c2-e2a8576f16e0.png)

**Comment by flyinghead** [comment]
Same issue as #594
