### ISSUE TITLE
Naomi online mode. There is no connection between the players

### ISSUE THREAD

**Issue by Biryuk666** [flyinghead/flycast#945]
**Platform / OS / Hardware:**  PC/ Windows 10 Pro/ Ryzen 2 2700X; RX480 (8GB); 16GB DDR4 (2.4GGhz)

**Flycast v. 2.1 (Stable)**

_*The same image of the game and NAOMI's BIOS were used on the old and on the new versions of Flycast_

**Description of the Issue**

After updating Flycast to version 2.1, it stopped working online on the Naomi version of OUTTRIGGER. Previously, when trying to connect to the server (left window), the number of connected players was displayed on his screen.

![old](https://user-images.githubusercontent.com/42495055/220992076-b06d07f8-c60f-4040-82cc-d1ab3006b5e2.png)

In ver. 2.1 the screen after loading is empty

![v 2 1](https://user-images.githubusercontent.com/42495055/220992284-af41184c-f279-4548-81b0-026d4a355d12.png)

Also after a while the second player, when choosing the USA or another region in the settings (except Jap), the inscription "Illegal country version" appears. 

![v 2 1 (USA)](https://user-images.githubusercontent.com/42495055/220992949-9e423e9e-9f64-4446-80e0-6cfb473b9714.png)

When trying to select a Japanese region, the error "illegal network setting" already appears

![v 2 1 (JAP)](https://user-images.githubusercontent.com/42495055/220993015-5081ba9b-759d-422b-ba6b-4b62503a5cba.png)

**General settings:**

USA Region:
![settings USA region](https://user-images.githubusercontent.com/42495055/220995111-f29a022c-9913-420e-8f92-f1a4039dea57.png)
JAP Region:
![settings JAP region](https://user-images.githubusercontent.com/42495055/220995227-92fbefdd-ab9d-4c30-a0d3-0584d325e660.png)

**Advanced settings:**

Left window (server)
![settings left window](https://user-images.githubusercontent.com/42495055/220995417-b657a032-7ae3-467c-88d4-e2b0a73c5027.png)
Right window
![settings right window](https://user-images.githubusercontent.com/42495055/220995460-294c8802-536c-468c-9959-193b291a53e6.png)

**Logs PL1 (server):**

00:00:000 sdl/sdl.cpp:600 N[RENDERER]: Monitor refresh rate: 59 Hz (1920 x 1080)
00:00:040 rend/gui.cpp:273 N[RENDERER]: Screen DPI is 96, size 640 x 476. Scaling by 1.00
00:00:084 rend/gles/gles.cpp:563 N[RENDERER]: OpenGL version 4.3
00:09:901 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
00:09:911 hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff41bc10000 RAM(16 MB) 00007ff427c10000 VRAM64(8 MB) 00007ff41fc10000 ARAM(2 MB) 00007ff43bc10000
00:09:920 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
00:09:944 hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff41bc10000 RAM(32 MB) 00007ff427c10000 VRAM64(16 MB) 00007ff41fc10000 ARAM(8 MB) 00007ff43bc10000
00:10:620 hw/naomi/naomi_cart.cpp:585 N[NAOMI]: NAOMI GAME ID [OUTTRIGGER     JAPAN] region ff players 0 vertical 0
00:10:621 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
00:10:628 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
00:18:669 network/miniupnp.cpp:50 W[NETWORK]: Internet Gateway not found: error 3
00:23:686 network/miniupnp.cpp:88 W[NETWORK]: Port 37391 redirection failed: error -3
00:23:686 network/naomi_network.cpp:97 N[NETWORK]: Waiting for slave connections
00:43:712 network/naomi_network.cpp:118 N[NETWORK]: Master starting: 1 slaves
04:05:684 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
04:05:708 hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff41bc10000 RAM(32 MB) 00007ff427c10000 VRAM64(16 MB) 00007ff41fc10000 ARAM(8 MB) 00007ff43bc10000
04:06:385 hw/naomi/naomi_cart.cpp:585 N[NAOMI]: NAOMI GAME ID [OUTTRIGGER     JAPAN] region ff players 0 vertical 0
04:06:385 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
04:06:391 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
04:14:439 network/miniupnp.cpp:50 W[NETWORK]: Internet Gateway not found: error 3
04:19:450 network/miniupnp.cpp:88 W[NETWORK]: Port 37391 redirection failed: error -3
04:19:450 network/naomi_network.cpp:97 N[NETWORK]: Waiting for slave connections
04:39:477 network/naomi_network.cpp:118 N[NETWORK]: Master starting: 1 slaves
00:00:000 sdl/sdl.cpp:600 N[RENDERER]: Monitor refresh rate: 59 Hz (1920 x 1080)
00:00:039 rend/gui.cpp:273 N[RENDERER]: Screen DPI is 96, size 640 x 476. Scaling by 1.00
00:00:082 rend/gles/gles.cpp:563 N[RENDERER]: OpenGL version 4.3
00:00:000 sdl/sdl.cpp:600 N[RENDERER]: Monitor refresh rate: 59 Hz (1920 x 1080)
00:00:044 rend/gui.cpp:273 N[RENDERER]: Screen DPI is 96, size 1920 x 1017. Scaling by 1.00
00:00:087 rend/gles/gles.cpp:563 N[RENDERER]: OpenGL version 4.3

**Logs PL2:**

00:00:000 sdl/sdl.cpp:600 N[RENDERER]: Monitor refresh rate: 59 Hz (1920 x 1080)
00:00:039 rend/gui.cpp:273 N[RENDERER]: Screen DPI is 96, size 638 x 480. Scaling by 1.00
00:00:082 rend/gles/gles.cpp:563 N[RENDERER]: OpenGL version 4.3
00:02:303 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
00:02:313 hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4408e0000 RAM(16 MB) 00007ff44c8e0000 VRAM64(8 MB) 00007ff4448e0000 ARAM(2 MB) 00007ff4608e0000
00:02:322 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
00:02:346 hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4408e0000 RAM(32 MB) 00007ff44c8e0000 VRAM64(16 MB) 00007ff4448e0000 ARAM(8 MB) 00007ff4608e0000
00:03:028 hw/naomi/naomi_cart.cpp:585 N[NAOMI]: NAOMI GAME ID [OUTTRIGGER     JAPAN] region ff players 0 vertical 0
00:03:028 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
00:03:035 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
00:11:103 network/miniupnp.cpp:50 W[NETWORK]: Internet Gateway not found: error 3
00:16:121 network/miniupnp.cpp:88 W[NETWORK]: Port 37391 redirection failed: error -3
00:16:121 network/naomi_network.cpp:166 N[NETWORK]: Connecting to server
03:58:353 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
03:58:378 hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4408e0000 RAM(32 MB) 00007ff44c8e0000 VRAM64(16 MB) 00007ff4448e0000 ARAM(8 MB) 00007ff4608e0000
03:59:053 hw/naomi/naomi_cart.cpp:585 N[NAOMI]: NAOMI GAME ID [OUTTRIGGER     JAPAN] region ff players 0 vertical 0
03:59:053 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
03:59:060 emulator.cpp:52 N[BOOT]: Game ID is [OUTTRIGGER     JAPAN]
04:07:117 network/miniupnp.cpp:50 W[NETWORK]: Internet Gateway not found: error 3
04:12:128 network/miniupnp.cpp:88 W[NETWORK]: Port 37391 redirection failed: error -3
04:12:129 network/naomi_network.cpp:166 N[NETWORK]: Connecting to server
00:00:000 sdl/sdl.cpp:600 N[RENDERER]: Monitor refresh rate: 59 Hz (1920 x 1080)
00:00:042 rend/gui.cpp:273 N[RENDERER]: Screen DPI is 96, size 638 x 480. Scaling by 1.00
00:00:085 rend/gles/gles.cpp:563 N[RENDERER]: OpenGL version 4.3

**Comment by flyinghead** [comment]
What was the latest Flycast version you used successfully?

**Comment by Biryuk666** [comment]
> What was the latest Flycast version you used successfully?

![image](https://user-images.githubusercontent.com/42495055/221002448-43d0d2ad-261a-4bd2-a3d4-08c85801cf22.png)

**Comment by flyinghead** [comment]
I just did a quick test with 2.1 and outtrigger connected just fine.

Try deleting the flashrom for this game (otrigger.zip.nvmem, then run the game in single player once so it gets re-created).

**Comment by Biryuk666** [comment]
> I just did a quick test with 2.1 and outtrigger connected just fine.
> 
> Try deleting the flashrom for this game (otrigger.zip.nvmem, then run the game in single player once so it gets re-created).

Its alive! Thank you very much! 
![image](https://user-images.githubusercontent.com/42495055/221010903-0c4ea076-07cf-4272-9cf3-b200c488580c.png)

It turns out that the problem was in a incorrectly written file?

**Comment by Biryuk666** [comment]
> I just did a quick test with 2.1 and outtrigger connected just fine.
> 
> Try deleting the flashrom for this game (otrigger.zip.nvmem, then run the game in single player once so it gets re-created).

After deleting the file, the game settings got lost and, accordingly, just 2 single games started. When changing the settings inside Test Mode, the game stops running again

**Comment by flyinghead** [comment]
You don't need to change any setting in test mode.
Delete the nvmem file again, then run it once in single player (if you try network, you'll get two single player instances as you experienced).
Then try to connect with network again.

**Comment by Biryuk666** [comment]
> You don't need to change any setting in test mode. Delete the nvmem file again, then run it once in single player (if you try network, you'll get two single player instances as you experienced). Then try to connect with network again.

I did everything as you said - deleted the old files and first started a single game for each player without a network connection. Then I xlose the game and turned on networking. But still there was an error

![image](https://user-images.githubusercontent.com/42495055/221016778-4d9a95da-0ac5-4309-9cb0-2ad3d448b2d1.png)

**Comment by flyinghead** [comment]
Check that master and slave are using the same BIOS region.

**Comment by Biryuk666** [comment]
> Check that master and slave are using the same BIOS region.

The same
![image](https://user-images.githubusercontent.com/42495055/221018634-bc68fd44-1001-4cbf-aa5a-c614357e8dec.png)

**Comment by Biryuk666** [comment]
> `Region = Default` is an invalid setting. Set USA or Japan.

![image](https://user-images.githubusercontent.com/42495055/221019527-9b0eb8ab-298f-4c1f-ab69-1257af7d2070.png)
![image](https://user-images.githubusercontent.com/42495055/221019598-2916badf-7f9c-4583-a4ca-f8ad717da52a.png)

**Comment by flyinghead** [comment]
I did another connection test with Japan and USA regions and again no issue connecting.

I noticed you are using the same local port (the default 37391) for both master and slave. This won't work if they run on the same machine. Choose a different port for the slave in that case.

**Comment by Biryuk666** [comment]
Yes, you're right! After I changed the local port number for slave, everything immediately worked! Thank you very much!

It turns out that everything was much simpler

![image](https://user-images.githubusercontent.com/42495055/221405774-ba1e7f21-4925-4deb-b67f-9369a3366a1c.png)
