### ISSUE TITLE
Android virtual gamepad triggers also act as buttons in arcade mode

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#947]
![Screenshot_20230223-163137](https://user-images.githubusercontent.com/96657677/221275862-dc024de9-79b4-41ad-a268-8126bf5f96ea.png)

Title: King of Route 66 (Naomi 2)
Latest Android dev version. Phone is Android 11.

Pressing RT also turns on reverse gear so truck drives in reverse. lol. Occurs with virtual touch gamepad only. Working with hardware controller.

Also, RT & LT are digital with naomi, either on or off. Is this correct? I'm seeing full analog on the thumbsticks.

**Comment by flyinghead** [comment]
With the virtual android gamepad, RT and LT are also mapped to naomi buttons 5 and 6. So this is clearly an issue with this game.

When using a real controller, Flycast tries to find analog axes for LT and RT, and defaults to digital triggers if not found. But you can reassign them to actual analog axes if Flycast fails to find them.

**Comment by MoeFoh** [comment]
The triggers were being mapped properly. When testing input is was either
00 or FF, nothing in-between. I can't imagine gas & brake on the real
arcade machine to be digital in nature.

Flycast is awesome and thanks team Flycast.

**Comment by flyinghead** [comment]
LT and RT are obviously analog axes. This is either an android limitation or a sub optimal input mapping.

**Comment by MoeFoh** [comment]
Update: The triggers are suppose to work that way (digital) when the
controller is set to d-input Android.

Changing the controller to x-input (Windows), and well.. things went crazy.

**Comment by MoeFoh** [comment]
![snapshot_gamepad-tester com_1677343756694](https://user-images.githubusercontent.com/96657677/221369367-4c1bea1e-b54c-496a-be48-92bbb31e9075.png

From gamepad-tester.com. Controller LT & RT are identified as button b6 & b7, respectfully. But it does register analog input. I'm pressing LT half-way in the snapshot.

**Comment by flyinghead** [comment]
Bind these buttons to Left & Right Trigger of the dreamcast controller.

If these buttons send both digital and analog events, try to depress the triggers before binding and release them to bind.

**Comment by MoeFoh** [comment]
> Bind these buttons to Left & Right Trigger of the dreamcast controller.
> 
> If these buttons send both digital and analog events, try to depress the triggers before binding and release them to bind.

Yes, sir. Working now. Triggers show up as brake+ & gas+.

[analog]
bind0 = 0-:btn_analog_left
bind1 = 0+:btn_analog_right
bind2 = 1-:btn_analog_up
bind3 = 1+:btn_analog_down
bind4 = 11-:axis2_left
bind5 = 11+:axis2_right
bind6 = 14-:axis2_up
bind7 = 14+:axis2_down
bind8 = 22+:btn_trigger_right
bind9 = 23+:btn_trigger_left

[digital]
bind0 = 19:btn_dpad1_up
bind1 = 20:btn_dpad1_down
bind10 = 108:btn_start
bind11 = 109:btn_d
bind2 = 21:btn_dpad1_left
bind3 = 22:btn_dpad1_right
bind4 = 96:btn_a
bind5 = 97:btn_b
bind6 = 99:btn_c
bind7 = 100:btn_x
bind8 = 102:btn_y
bind9 = 103:btn_z

[emulator]
dead_zone = 10
mapping_name = Default
rumble_power = 100
version = 3

In the cfg file, is there a command to invert output?

**Comment by flyinghead** [comment]
to invert an axis, change + to - and vice versa on both directions.

**Comment by flyinghead** [comment]
This now fixed on the`dev` branch: buttons 5 and 6 are distinct from the triggers in the virtual gamepad. In arcade mode, only the controls used by the game are shown.
