### ISSUE TITLE
Naomi Crazy Taxi freezes when pressing button 4

### ISSUE THREAD

**Issue by MoeFoh** [flyinghead/flycast#948]
Title: Crazy Taxi
Flycast latest dev version. Phone is on Android 11.

Pressing the Y button results in the video locking. Audio continues to play. Y button is not used in the game from my reading.

It does this on both virtual and real controller.

**Comment by flyinghead** [comment]
That's what the game does. I don't know why and this button isn't wired on real hardware. But this game has undocumented inputs: by pressing P2 start you can open a debug menu with lots of options, so this might be some kind of debug button too.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/16261910/221375942-cc808c43-11f9-4c7f-a00f-c9993593a940.png">

**Comment by flyinghead** [comment]
Apparently Crazy Taxi 3: High Roller on Chihiro does the same thing.

**Comment by kihato** [comment]
This button pauses the game, but pressing it again should cancel it.
It used to work fine.

5722dc9: Can be reproduced.
e3c260f: Can't reproduce.
