### ISSUE TITLE
Support for .zip files?

### ISSUE THREAD

**Issue by stzokev** [flyinghead/flycast#95]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 x64

Github hash: flycast-win_x64-fast-df97c42e4ee3f75988041d2badac2b18249e888e

Hardware: Irrelevant

**_Description of the Issue_**

The libretro documentation (https://docs.libretro.com/library/flycast/) says that .zip files are supported extension, however I have not been able to run .zip games neither from libretro nor from the standalone flycast binary. Can you confirm whether this is a bug or documentation error?

Background: the new DC redump consists of only cue/bin files and the converted .chd files DO NOT work. So I was trying .zip as different archiving option.

Thanks!

**Comment by flyinghead** [comment]
.zip files are supported for Naomi/Atomiswave roms only.

Zipped cue/bin or .gdi aren't supported.

**Comment by stzokev** [comment]
Thanks for the info! Interesting then why the new DC redump is chosen to be in cue/bin .. basically makes it unusable for archiving purposes.
