### ISSUE TITLE
[AMD] Enable Native Depth Interpolation option crashes

### ISSUE THREAD

**Issue by XieTieqiang** [flyinghead/flycast#952]
Libretro using AMD RX6700 12G graphics card, renderer setting vulkan, crashes with Native Depth Interpolation option on. But there is no such problem on HD7950 3G or RX480 8G.

The Windows version of flycast does not have this problem either.

[INFO] RetroArch 1.14.0 (Git 9192abb)
[INFO] === Build =======================================
[INFO] CPU Model Name: 12th Gen Intel(R) Core(TM) i5-12400F
[INFO] 容量: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Feb 25 2023
[INFO] Version: 1.14.0
[INFO] Git: 9192abb
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_w".
[INFO] [Vulkan]: Detecting screen resolution: 1920x1080.
[INFO] [Vulkan]: Found GPU at index 0: "AMD Radeon RX 6700 XT".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "AMD Radeon RX 6700 XT".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 960x720.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: 正在加载收藏文件: "E:\RetroArch\content_favorites.lpl".
[INFO] [Core]: Using content: "E:\MAME ROMs (split)\hotd2.zip".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.14.0 (Git 9192abb)
[INFO] === Build =======================================
[INFO] CPU Model Name: 12th Gen Intel(R) Core(TM) i5-12400F
[INFO] 容量: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Feb 25 2023
[INFO] Version: 1.14.0
[INFO] Git: 9192abb
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "E:\RetroArch\cores\flycast_libretro.dll"
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "12".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Overrides]: 重定向游戏存档文件至 "E:\RetroArch\saves\hotd2.srm".
[INFO] [Overrides]: 正在重定向状态存储至 "E:\RetroArch\states\hotd2.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[libretro INFO] shell/libretro/libretro.cpp:309 N[BOOT]: retro_init
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[libretro INFO] core/hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4dd4b0000 RAM(16 MB) 00007ff4e94b0000 VRAM64(8 MB) 00007ff4e14b0000 ARAM(2 MB) 00007ff4fd4b0000
[INFO] [Content]: 跳过游戏加载。实现将自行加载。
[libretro INFO] shell/libretro/libretro.cpp:1793 N[BOOT]: retro_load_game: E:\MAME ROMs (split)\hotd2.zip
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "E:\RetroArch\system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[ERROR] [Environ]: GET_VARIABLE: pvr.rend - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: rend.PerStripSorting - Invalid value.
[INFO] [Environ]: SET_SAVE_STATE_IN_BACKGROUND: yes.
[libretro INFO] File extension is: .zip
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: vulkan.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_VULKAN.
[INFO] [Environ]: SET_HW_RENDER, context type: vulkan.
[INFO] Requesting Vulkan context.
[INFO] [Environ]: SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] core/hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
[libretro INFO] core/hw/mem/_vmem.cpp:508 N[VMEM]: BASE 00007ff4dd4b0000 RAM(32 MB) 00007ff4e94b0000 VRAM64(16 MB) 00007ff4e14b0000 ARAM(8 MB) 00007ff4fd4b0000
[ERROR] [Environ]: GET_VARIABLE: pvr.rend - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: rend.PerStripSorting - Invalid value.
[libretro WARN] core/hw/naomi/naomi_cart.cpp:199 W[NAOMI]: Warning: Region 3 bios not found in hod2bios
[libretro INFO] core/hw/naomi/naomi_cart.cpp:591 N[NAOMI]: NAOMI GAME ID [hotd2] region 0 players 0 vertical 0
[libretro INFO] core/emulator.cpp:52 N[BOOT]: Game ID is [hotd2]
[libretro WARN] core/hw/naomi/naomi_cart.cpp:624 W[NAOMI]: Can't read ROM boot ID
[libretro INFO] core/emulator.cpp:52 N[BOOT]: Game ID is [hotd2]
[INFO] [Environ]: SET_ROTATION: 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [SRAM]: 跳过游戏存档加载。
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[libretro INFO] shell/libretro/libretro.cpp:2127 N[RENDERER]: retro_get_system_av_info: Res=480
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Set video size to: 1440x1080.
[INFO] [Video]: Using HW render, vulkan driver forced.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_w".
[INFO] [Vulkan]: Detecting screen resolution: 1920x1080.
[INFO] [Vulkan]: Got HW context negotiation interface 1.
[INFO] [Vulkan]: Found GPU at index 0: "AMD Radeon RX 6700 XT".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "AMD Radeon RX 6700 XT".
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1440x1041.
[INFO] [Vulkan]: Using BGRA8888 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Video]: Found display server: "win32".
[libretro INFO] shell/libretro/libretro.cpp:1616 N[RENDERER]: retro_vk_context_reset
[libretro INFO] core/rend/vulkan/vk_context_lr.cpp:193 N[RENDERER]: GPU Supports Vulkan API: 1.3.237
[libretro INFO] core/rend/vulkan/vk_context_lr.cpp:199 N[RENDERER]: GPU Supports vkGetPhysicalDeviceProperties2
[libretro INFO] core/rend/vulkan/vulkan_context.h:266 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
[libretro INFO] core/rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_music_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_video_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "E:\RetroArch\content_image_history.lpl".
[INFO] [Playlist]: 正在加载收藏文件: "E:\RetroArch\content_favorites.lpl".
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.333.
[libretro WARN] core/rend/vulkan/oit/oit_renderer.cpp:95 W[RENDERER]: Vulkan system error vk::Queue::submit: ErrorDeviceLost
[libretro WARN] core/rend/vulkan/oit/oit_renderer.cpp:95 W[RENDERER]: Vulkan system error vk::Queue::submit: ErrorDeviceLost

**Comment by flyinghead** [comment]
This looks like a Vulkan driver bug. The only difference when Native Depth Interpolation is enabled is in the shaders. So it shouldn't crash with ErrorDeviceLost, even if the shader is invalid (which isn't the case).

**Comment by flyinghead** [comment]
Assuming this is a driver bug. Reopen if needed.
