### ISSUE TITLE
Command line for HOST / JOIN

### ISSUE THREAD

**Issue by bdiederichs** [flyinghead/flycast#958]
Is there a way to HOST and JOIN via command line?

I've been digging around for hours but cannot find any way to trigger these via command line interface

**Comment by blueminder** [comment]
Host:
`-config network:GGPO=yes -config network:ActAsServer=yes -config network:server="127.0.0.1"`

Join:
`-config network:GGPO=yes -config network:ActAsServer=no -config network:server="127.0.0.1"`

**Comment by bdiederichs** [comment]
Thanks!
I replaced the 127.0.0.1 IP with the HOST computer IP
And this does get the host started with the desired "Waiting for Opponent to Connect" 

However, when In run the JOIN command on the 2nd PC it just launches the game in what seems to be OFFLINE mode

the HOST PC still shows "Waiting for Opponent to Connect"

**Comment by bdiederichs** [comment]
Thank you!

this did the trick!

**Comment by bdiederichs** [comment]
once the Player 2 connects, Is there a way to Start the game by script?

Back on the HOST window I'm at the set delay / Start Game screen
I tried to arrow down to start game and press Spacebar via an AHK, But I can't get any Keys to work via an AHK for flycast

**Comment by flyinghead** [comment]
There's an issue on the Start game screen where you need to press Start on a gamepad to start the game. Pressing Start on the keyboard is ignored and there's no UI button either.
