### ISSUE TITLE
La Keyboard does not start at 2P

### ISSUE THREAD

**Issue by model-123** [flyinghead/flycast#960]
La Keyboard  does not start when keyboard setting is set to port B(2P)
When setting the same, TOD and Lupine type start with 2P

**Comment by flyinghead** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/16261910/222891322-d4d3b683-710b-4b1d-b27f-618c334a054e.png)

**Comment by model-123** [comment]
thank you for the test
I'll try changing the settings

**Comment by model-123** [comment]
I tried the latest release build and CI build on windows 11 and 10

If you press enter while in attract mode, the title screen will appear.
but the game won't start

TOD and Lupine types work as 2P in this setting

![スクリーンショット 2023-03-05 070905](https://user-images.githubusercontent.com/109840450/222930897-d2bf5982-e0ce-4545-b954-e44666b538c3.png)

**Comment by flyinghead** [comment]
I still can't reproduce the problem.
If I press P2 enter key in attract mode, the title screen appears, then I press P2 enter once again and the game starts like in my screenshot above.

**Comment by model-123** [comment]
thank you again for testing
I don't know the cause, but if I redo it in a folder with a different name, I can now start with 2P
It seems to be a problem with the config file or something.

I will close this time
