### ISSUE TITLE
Fast Disc Speed to reduce loading screens (if possible) 

### ISSUE THREAD

**Issue by German-Herrador** [flyinghead/flycast#961]
Enhancement that accelerates the disc speed reducing loading times (can be unstable (like save states))

For games like Soldier Of Fortune or the unofficial Half-Life port that have extremely long loading screens (or every game you want) 

I don't know if this is possible on the emulator or simply haven't been implemented yet.

**Comment by flyinghead** [comment]
There's already such an option in Flycast but only exposed in the Flycast RetroArch core. Unfortunately it doesn't help that much regarding loading times, and it does break some games.

I see no change whatsoever with Soldier of Fortune, and 18% faster load times with Half-Life with this option on.

**Comment by flyinghead** [comment]
Using Fast Forward is probably the easiest and safest way to decrease load times.

**Comment by German-Herrador** [comment]
Hey, that's actually a very good idea. Haven't thought about that.

Regarding the the initial issue, do you think the hack/enhancement works as intended or maybe there's something that could be done about it.

If it already works as intended and those statistics are the results of the hack/enhancement then you can close the issue. Np

**Comment by flyinghead** [comment]
I'd rather not expose the Fast GD-ROM Load option since it has very little effect on load times compared to fast forward and it breaks some games (Skies of Arcadia is one of them).
