### ISSUE TITLE
[Feature Request] [UI] Vulkan features extension info and driver bugs info.

### ISSUE THREAD

**Issue by ghost** [flyinghead/flycast#965]
Just like what ppsspp did
screenshot what I'm requesting
![Screenshot_20230307_122258_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/223320552-135fad7e-c9bc-44e5-9a20-a1d3f41e78fc.jpg)
![Screenshot_20230307_122313_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/223320563-e11fdfe6-b83f-4c27-a15d-e88652ece413.jpg)
![Screenshot_20230307_122321_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/223320572-d6a7e14f-6dc3-450e-95a5-457c411afc55.jpg)

Show what vulkan extension is available and what is enable.
Also show driver bugs that is not fixable.

BTW opengl performs better than vulkan on my vivo y11 snapdragon 439 adreno 505 gpu.

**Comment by flyinghead** [comment]
Use https://vulkan.gpuinfo.org
