### ISSUE TITLE
Crash when trying to play space herrier on shenmue 1

### ISSUE THREAD

**Issue by pantomm** [flyinghead/flycast#967]
Platform / OS / Hardware: Android 12

Github hash: V2.1

Hardware: xiaomi 11t

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```03:45:072 rend/vulkan/vulkan_context.cpp:247 N[RENDERER]: Vulkan API 1.1. Device Mali-G77 MC9
03:45:094 rend/vulkan/vulkan_context.h:266 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
03:45:114 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
04:17:556 rend/vulkan/vulkan_context.cpp:247 N[RENDERER]: Vulkan API 1.1. Device Mali-G77 MC9
04:17:572 rend/vulkan/vulkan_context.h:266 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
04:17:582 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
04:45:429 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
04:45:437 hw/mem/_vmem.cpp:512 N[VMEM]: BASE 0x74fd620000 RAM(16 MB) 0x7509620000 VRAM64(8 MB) 0x7501620000 ARAM(2 MB) 0x751d620000
04:45:445 hw/mem/_vmem.cpp:473 N[VMEM]: Info: nvmem is enabled
04:45:453 hw/mem/_vmem.cpp:512 N[VMEM]: BASE 0x74fd620000 RAM(16 MB) 0x7509620000 VRAM64(8 MB) 0x7501620000 ARAM(2 MB) 0x751d620000
04:45:462 emulator.cpp:52 N[BOOT]: Game ID is [MK-51059]
04:45:469 emulator.cpp:52 N[BOOT]: Game ID is [MK-51059]
05:16:793 nullDC.cpp:218 N[SAVESTATE]: Loaded state ver 826 from /storage/emulated/0/r/Dreamcast/data/Shenmue (USA) (Disc 3).state size 28094988
05:57:570 rc/Android.cpp:720 E[BOOT]: terminating with uncaught exception of type vk::DeviceLostError: vk::Device::waitForFences: ErrorDeviceLost



**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
can you post your savestate?

**Comment by pantomm** [comment]
> can you post your savestate?

I dont know how to post file on github

**Comment by flyinghead** [comment]
Use the attach image button and select your savestate file instead of an image.

Also enable 'Advanced > Automatically Report Crashes' to have your crash report sent to me.

**Comment by pantomm** [comment]
> Use the attach image button and select your savestate file instead of an image.
> 
> Also enable 'Advanced > Automatically Report Crashes' to have your crash report sent to me.

**Comment by pantomm** [comment]
I cant select it ![Screenshot_2023-03-08-17-23-48-115_com.google.android.documentsui.jpg](https://user-images.githubusercontent.com/50849304/223674281-2c6bacf7-1dc3-45d7-a79d-7aa439b53655.jpg)

Also i already enabled crash report ![Screenshot_2023-03-08-17-20-54-397_com.flycast.emulator.jpg](https://user-images.githubusercontent.com/50849304/223674657-b3fa2fb7-65f9-455a-812b-654f9afc68ae.jpg)

Before crash happen

**Comment by pantomm** [comment]
Here

**Comment by flyinghead** [comment]
Thank you for the savestate, it helped.

The first thing is you need to enable the `Video > Render to Texture > Copy To VRAM` option. Otherwise you'll get a blackscreen.
I'll see if I can enable it automatically for this game.

I did find a vulkan validation error when changing this option while in game but I don't think that's the cause of the crash. After fixing it no other vulkan error was reported. I tested it on desktop nvidia and adreno 630 without issue. However I had the same DeviceLostError vulkan crash on Mali-G51. So my guess is this is a driver bug.

It only happens in per-pixel so you can switch to per-triangle before running this arcade game.

**Comment by pantomm** [comment]
Copy to vram fixed it, i didn't need to change to per-triangle

**Comment by flyinghead** [comment]
`Render to Texture > Copy To VRAM` is now automatically enabled for Shenmue
