### ISSUE TITLE
Fast-foward dosen't work in DirectX 11, but only in full screen mode

### ISSUE THREAD

**Issue by doodleintime** [flyinghead/flycast#970]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 11 Home 22H2.

Github hash: 52754cb

Hardware: AMD Ryzen 7 2700X 3.70 GHz, GeForce RTX 3070, 16 GB DDR4 RAM.

**_Description of the Issue_**

Add a short, concise description of the issue here

When fast-forwarding in full screen mode (via alt+enter if that matters) with Direct X 11, the audio is muted, but the framerate is still capped to the game's framerate. In windowed mode, the framerate uncaps and the game speeds up as normal.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Flycast Screenshot 2023 03 11 - 14 45 44 77](https://user-images.githubusercontent.com/53154503/224508725-559655e5-6cae-488f-90b2-fc323f8f1158.png)

**Comment by doodleintime** [comment]
No, I'm using the emulator's vsync. I tried turning that off and it didn't fix the issue either. Since you were using Windows 10, I tried using Windows 8 and 7 compatibility modes, and that didn't fix it either. I then installed a clean copy of 8ca89ea (clean copy means in a folder with no files from previous versions), and that didn't fix it either.

**Comment by flyinghead** [comment]
Not using an NVidia application profile for flycast?

When fast-forwarding, Flycast presents the frames with the `DXGI_PRESENT_DO_NOT_WAIT` option, which should avoid waiting for the next VSync. Something is making your gpu driver wait regardless of this option.

**Comment by doodleintime** [comment]
I was not using one for Flycast. I tried adding one for it and leaving the vsync option at [Use the 3D application setting], but that didn't fix it either.

**Comment by doodleintime** [comment]
I updated my drivers and now it works, but it's choppy and not as fast compared to fast-forwarding with the other backends. Is that a known issue?

**Comment by doodleintime** [comment]
When I updated my drivers, I did a custom install and checked the box to do a clean install, which sets the driver settings back to default, and by doing that, I was able to find out what was causing the issue: Low Latency Mode. Setting it to anything other than [off] causes the fast-forwarding to not work.

**Comment by flyinghead** [comment]
Good find! Hopefully this will help other people facing the same issue.

Regarding your previous, do you mean that fast-forward is choppy? It's supposed to render frames as fast as possible and most of them won't be displayed to it's not supposed to be smooth.

**Comment by doodleintime** [comment]
Yeah, I do mean that it's choppy, but only for Direct X 11, and it also doesn't fast-forward as fast as the other backends despite otherwise having better performance for me.

**Comment by flyinghead** [comment]
All backends are different. I don't see any obvious reason why dx11 fast forward would be choppy and slower than with other backends. But that's why Flycast supports multiple graphics API, so that users can choose what works best for them.
