### ISSUE TITLE
Rainbow six no video on boot while using threaded renderer

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#973]
using latest dev libretro core on dx11 xbox series x, with threaded renderer enabled there is no video but audio plays fine on game boot, getting past the menus and into actual gameplay restores video, this issue does not occur when threaded renderer is off

**Comment by flyinghead** [comment]
Fixed in latest master

**Comment by Nejsplitter** [comment]
confirmed fixed on xbox series x, thanks flyinghead
