### ISSUE TITLE
Alone in the Dark 4 cutscenes black screen.

### ISSUE THREAD

**Issue by gesandovalr** [flyinghead/flycast#974]
Platform / OS / Hardware: Windows 10 
Hardware: Ryzen 7 5800x / Nvidia 3080ti
Alone in the Dark 4 cutscenes showing black screen DX11

Issue:
https://streamable.com/fdsy5h

**Comment by flyinghead** [comment]
Fixed in latest master

**Comment by kihato** [comment]
Although it is partially displayed, it is almost pitch black (DX11).

It happens at commit afc1f5f.

**Comment by flyinghead** [comment]
latest regression should be fixed on both branches

**Comment by kihato** [comment]
I've verified that it renders fine on both branches. Thanks.
I just noticed one more thing, is this a bug in the game?

https://github.com/flyinghead/flycast/assets/14366233/7f747013-284e-4fe0-ae0c-ddd306d42509

**Comment by flyinghead** [comment]
I'm not sure but the polygon being drawn clearly doesn't cover the entire screen:
![image](https://github.com/flyinghead/flycast/assets/16261910/56e3d0df-e110-448f-a425-78daf48150fa)

**Comment by flyinghead** [comment]
I believe this is a game bug. Here is a screenshot of this game running on original hardware with the same issue:
![image](https://github.com/flyinghead/flycast/assets/16261910/76f431f3-545f-46b9-b1ca-f28dc085e859)

Source:
https://youtu.be/vmT0S0TlRgI?t=70

**Comment by kihato** [comment]
Thanks again. This issue should be closed.
