### ISSUE TITLE
Automatic Frame Skipping works only if Delay Frame Swapping is enabled

### ISSUE THREAD

**Issue by Kvn0l** [flyinghead/flycast#975]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
ARM / Android 9 / Weak

Github hash: 
Standalone 52754cbb / Libretro fbc69b6 (i think)

Hardware: 
MT6763V powered smartphone

**_Description of the Issue_**
'Cause i'm on weak hardware, need "Automatic Frame Skipping" on "Maximum" to ensure it'll run at full speed, but I noticed it's only working if I leave "Delay Frame Swapping" enabled, otherwise the auto frame skip acts if it were disabled. Happens both on standalone and Libretro, tested only with OpenGL as vulkan support is very bad on my SoC, I can test if required.

**_Debugging Steps Tested_**

1. Hardware that can't sustain stable 60fps on games
2. Enable Automatic Frame Skipping with Maximum option
3. Enable Delay Frame Swapping
4. Frames will auto skip as intended, eg 40fps 100% speed
5. Disable Delay Frame Swapping
6. Frames will not auto skip, eg 40fps slow speed audio crackling 

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by Kvn0l** [comment]
Tested on my laptop now (Ryzen 7 2700U with Vega 10).
I've increased resolution upscale 'til hit a GPU bottleneck to get around 40 fps-ish on Sonic Adventure 2 and tested the frame skip with/without delay swap and indeed, the same bug happened, tested both on OpenGL and Vulkan.

**Comment by flyinghead** [comment]
Yes, I can easily reproduce it too.

**Comment by flyinghead** [comment]
Should be fixed on master

**Comment by Kvn0l** [comment]
Yeah, it indeed fixed! But I noticed something strange on superficial test, with delay frame disabled the game (SA2) got more stutter and lower FPS on some scenes, which is counter intuitive as disabling it is suposed to help performance. Since this may be a new problem, I'll close this issue and investigate more, if I do indeed find anything new gonna create a new one, thanks!
