### ISSUE TITLE
[mesa] OpenGL More than 64 Layers failure

### ISSUE THREAD

**Issue by anonyme-x22** [flyinghead/flycast#977]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Linux - Lubuntu 22.04.2 - AMD HD 7970

Github hash: 

17ab0ab

**_Description of the Issue_**

Use OpenGL backend, per pixel mode
Setting more than 64 layer hang the system reboot needed.

**_Debugging Steps Tested_**

* Reducing layer to 64. Ok
* Increasing layer to 128. System hang , video screen show strange display, reboot needed.
* Increasing layer to 96. System hang , video screen show strange display, reboot needed.
* Increasing layer to 76. System hang , video screen show strange display, reboot needed.
  
**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

Log can be furnished on demand.


**_Screenshots_**

No screenshot possible as the system hang.

**Comment by flyinghead** [comment]
It's likely a limitation or bug of the underlying GPU hardware or driver (which you didn't specify)

**Comment by anonyme-x22** [comment]
Driver is messa latest
Hardware is amd HD7970

**Comment by flyinghead** [comment]
I did a quick test on Ubuntu 20 with NVidia GTX 1080 proprietary drivers and no issue with 128 layers.

The fact that Vulkan works fine with 128 layers on your system tends to point to a Mesa driver issue.

**Comment by anonyme-x22** [comment]
Hi,

Those damn mesa, they don't work with my video card with vulkan!
They don't work correctly on open gl...
Yes i agree, if that worked with vulkan on amdgpu driver, it should also works on Open GL!
So unless it's not on your side, it's on the driver side.
Shame i cannot force anymore amdgpu driver!

Have a good day,
Rgds,
