### ISSUE TITLE
Subtitles don't display in Space Channel 5 Part 2

### ISSUE THREAD

**Issue by getmorecabbage** [flyinghead/flycast#979]
Standalone / Windows 10 / AMD Radeon 5700 XT, AMD Ryzen 7 3800X

Github hash: 253301b (I think)

**_Description of the Issue_**

During the karaoke sections of reports, the subtitles won't display unless transparent sorting is set to per triangle or per strip.

**_Screenshots_**

Per-pixel setting

![per pixel sort](https://user-images.githubusercontent.com/128099455/225763932-48639d66-1b7f-4c9d-b7ae-e7af83c3077e.png)

Per-strip setting (The black box behind the subtitles is a bug)

![per strip sort (black box bug)](https://user-images.githubusercontent.com/128099455/225763951-5b68def4-04da-4898-9e25-c9ca4cb00219.png)

Correct effect on original hardware

![correct effect on original hardware](https://user-images.githubusercontent.com/128099455/225763963-04119ca5-5aae-4fdb-8aba-90c8c5dec765.png)

**Comment by flyinghead** [comment]
Fixed in latest master
