### ISSUE TITLE
Resetting a VMU with dreamcast BIOS fails

### ISSUE THREAD

**Issue by flyinghead** [flyinghead/flycast#98]
1. Boot the BIOS -> Files
2. Select a VMU
3. Delete all files (Reset)
4. Error message: "The memory card reset failed" and the VMU is no longer available

**Comment by flyinghead** [comment]
should be fixed by https://github.com/flyinghead/flycast/commit/130110324519787bac1e7c542a0fe3a090e3a08f

**Comment by turnerl72** [comment]
thanks flyinghead for the quick fix, much appreciated!
