### ISSUE TITLE
Sports Jam broken audio

### ISSUE THREAD

**Issue by Goosfranco** [flyinghead/flycast#980]
Retroarch, Windows 10, Ryzen 5 3600, Geforce GTX 1650

Audio is broken as seen in second 0:14 in the video below, the announcer just mumbles. There's sound glitches before but nothing significant. 

Video of the problem here: https://streamable.com/3ncblu

**Comment by flyinghead** [comment]
Should be fixed in latest master. Audio still isn't perfect as there are some audible glitches but at least the announcer voice is understandable.

**Comment by Goosfranco** [comment]
Indeed, there are some small glitches but the intro sounds excellent and the announcer's voice is understandable which is fair enough so far. Thank you!
