### ISSUE TITLE
app unresponsive on xbox uwp after imgui updates

### ISSUE THREAD

**Issue by Nejsplitter** [flyinghead/flycast#986]
dev branch standalone, inputs not responding at all after launching app, i think one of these is causing it, installing any dev branch from then/after then has the issue

https://github.com/flyinghead/flycast/actions/runs/4462372564

https://github.com/flyinghead/flycast/actions/runs/4470197672

**Comment by flyinghead** [comment]
should be fixed in the latest dev build

**Comment by Nejsplitter** [comment]
confirmed fixed on xbox, thanks flyinghead
