### ISSUE TITLE
San Francisco Rush 2049 graphics glitches on Mali GPU

### ISSUE THREAD

**Issue by mrfixit2001** [flyinghead/flycast#99]
Testing latest commit on a Rock64 RK3328 - Mali 450

The sky has glitching horizontal lines thru it after a race starts.
It appears this issue is specific to the GPU driver. 
I tested this on a RK3399 with a Mali 860 and it does not occur.
I am using the Rockchip Mali driver.

It's also possible that this is GLES2 related, as my RK3399 supports GLES3.

![image0](https://user-images.githubusercontent.com/38842252/84421370-78c30d80-abe9-11ea-88ab-a9ac0959d1c7.jpg)

**Comment by flyinghead** [comment]
FYI: same issue on Android 5 with Mali-400
![sfrush2049-mali400](https://user-images.githubusercontent.com/16261910/99300649-28fa0980-284d-11eb-8869-f801081113e2.png)

**Comment by flyinghead** [comment]
This is likely due to the lack of high precision floats in pixel shaders on Mali 400/450.
