### ISSUE TITLE
[iOS] Can’t edit virtual gamepad

### ISSUE THREAD

**Issue by parmezan70** [flyinghead/flycast#990]
Platform / OS / Hardware: 
iOS 16.3.1, iPhone XR

**_Github hash_**
a21b79cf

**_Description of the Issue_**
There is no Edit button near iOS Virtual Gamepad device. 

There is no way to adjust on-screen buttons size, placement etc.

**Comment by parmezan70** [comment]
I guess it’s rather bag than enchantment. That’s essential future for the emulator (already presented in Android version).

**Comment by parmezan70** [comment]
Any chance this to be implemented in the next release?

**Comment by flyinghead** [comment]
Fixed in the latest `dev` build

**Comment by flyinghead** [comment]
Fixed in the latest `dev` build
