### ISSUE TITLE
Sega Strike Fighter, graphical bugs

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#996]
Platform / OS / Hardware:  Windows 11. AMD Ryzen 5 5600H, RTX 3050ti Laptop GPU

Using the latest ci build 

some models are bugged on the how to play and mission briefing

Using Perpixel renderer 

https://user-images.githubusercontent.com/91135037/228101378-193d544f-fc20-4e80-a791-a7dbf64a6440.mp4

**Comment by flyinghead** [comment]
Doesn't happen with OpenGL but does with Vulkan.

**Comment by flyinghead** [comment]
Should be fixed on master

**Comment by flyinghead** [comment]
Happens on DX11 too

**Comment by flyinghead** [comment]
Fixed for dx11 too
