### ISSUE TITLE
[Libretro] Libretro build fails when Opengl is disabled and Vulkan is enabled.

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#997]
Platform / OS / Hardware: GNU/Linux

Github hash: 4514a4bfccf3b29531d58a85e3d5c00e75d58526

Hardware: Raspberry Pi 4 (Debian aarch64 with a Wayland based desktop), X86_64 

**_Description of the Issue_**

Libretro build fails when Opengl is disabled and Vulkan is enabled.
So, configuring with:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON -DUSE_VULKAN=ON -DUSE_OPENGL=OFF`
Results in:
```

/root/src/libretro/flycast/core/wsi/libretro.cpp:31:1: error: 'GraphicsContext' does not name a type
   31 | GraphicsContext *GraphicsContext::instance;
      | ^~~~~~~~~~~~~~~

```
**_Debugging Steps Tested_**

Try to build a libretro core with OpenGL disabled and Vulkan enabled.

**Comment by flyinghead** [comment]
You can apply this patch:
```
diff --git a/core/wsi/libretro.cpp b/core/wsi/libretro.cpp
index d9b14056..7b7a4453 100644
--- a/core/wsi/libretro.cpp
+++ b/core/wsi/libretro.cpp
@@ -24,9 +24,7 @@
 LibretroGraphicsContext theGLContext;
 #endif
 
-#if defined(HAVE_D3D11) && !(defined(HAVE_OPENGL) || defined(HAVE_OPENGLES))
 #include "context.h"
-#endif
 
 GraphicsContext *GraphicsContext::instance;
 #endif
```

I'll commit this change in my next update.

**Comment by vanfanel** [comment]
@flyinghead Ah, thanks for taking a look! I will close this issue when it's commited.
