### ISSUE TITLE
Windows Defender detects a trojan in the latest Flycast CI Builds (28/03 5df9127)

### ISSUE THREAD

**Issue by carlosluisbm** [flyinghead/flycast#998]
Windows defender (update 1.385.1608.0) removes the zip instantly upon download.

With the previous version of 03/25 (4514a4b) it does not happen.

A few days ago I detected this same Trojan in another zip file of a firmware image of a tv box.

Maybe it's just a false positive...

![image](https://user-images.githubusercontent.com/90100644/229055651-a7f9b84f-b2a0-4ae2-ba70-1e156ea88f78.png)

**Comment by flyinghead** [comment]
Likely a false positive since I checked the zip with 3 different virus scanners and nothing suspicious was found.
