### ISSUE TITLE
Naomi/Naomi 2 /Atomiswave ffb using a controller

### ISSUE THREAD

**Issue by retrofan2019** [flyinghead/flycast#999]
I'm using a ps3 controller in xbox360 mode (ds4windows/dshidmini) ... and I'm not getting any rumble effect at all in any of the arcade games I tested that support ffb except Initial D 3  .. first i thought it might be something wrong with my setup but it worked perfectly fine with Initial D ...

**Comment by flyinghead** [comment]
Atomiswave games have ffb support but no rumble. Recent FFB support is still on the dev branch so make sure you use a dev build.
Also, list the Naomi games you tested if you still have issues.

**Comment by retrofan2019** [comment]
I'm using the latest dev build ..  and I tested 18 Wheeler,Club Kart,Faster Than Speed,King Of Route 66,Maximum Speed and of course Initial D stage/2/3 .... got nothing at all from all the games except the Initial D games .. i think the only games i haven't tested r F355 and sega driving simulator .

**Comment by flyinghead** [comment]
18 Wheeler doesn't seem to be using rumble (at least I didn't feel any) but King of Route 66 and Club Kart (2k3) do.

Make sure the motor drive is enabled in the game test menu.

**Comment by retrofan2019** [comment]
i set steering power to max in club kart 2k3 and I got nothing ....in king of route 66 the motor power was set to no use but when i change to anything else i got "analog IO port initializing error! bad communication  ... hmm maybe I'm using bad roms or older roms and i should get the latest roms and update and test .

**Comment by flyinghead** [comment]
I don't think it's a rom problem.
Which version of flycast are you using?

**Comment by retrofan2019** [comment]
latest one  
build date : 2023-03-31

**Comment by flyinghead** [comment]
There was no build on the dev branch on this date. So you're using a master branch build, which explains the issue.

Scroll down to the dev on the builds page. The latest build was on 2023-03-30.

**Comment by retrofan2019** [comment]
doh yep i grabbed the latest master build not the dev build ... but I'm 100% sure the version i used before this one was a dev build ...but maybe the ffb was not implemented in that build or since the rumble effect is only present in a few games i just didn't notice it  .. 
and yea i just tested king of route 66 on the latest dev build and i got light rumble effect (set motor to heavy ) ..maybe that is another reason why i didn't notice it before cuz it's not like the inital D games ..it's a very light effect .

**Comment by retrofan2019** [comment]
I quickly tested all the games i have .. and yea now I got a light rumble effect in King of route 66 and a really good effect in Club Kart and of course the initial d games work perfectly fine  ...but yea that is it ,there is no rumble at all in the other games .. I mean they r not really meant to be played with a controller so that is the limitation of using a controller.

so i guess we can close this thread ...and one last thing I just have to say u have been doing an amazing job on the emulator ... I never thought i would see Naomi 2 games running that well with almost no problems on an emulator ...and I even saw posts here with ppl claiming that it can't be done with flycast but u managed to pull it off ..

**Comment by flyinghead** [comment]
Yes, King of Route 66 has soft rumble. Club Kart on the other hand is quite strong.

**Comment by flyinghead** [comment]
Thanks for your kind words
